### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by lervag** [lervag/vimtex#2129]
### Description

My description here.

### Steps to reproduce

1. `vim -u minimal.vim minimal.tex`
2. Keys
3. blahrg

### Expected behavior

asdfasdf

### Actual behavior

asdfasdf

### Do you use a latexmkrc file?

- [X] Yes

### VimtexInfo

```yaml
System info
  OS: Linux 5.13.9-arch1-1
  Vim version: NVIM v0.6.0-dev+127-g1a10acb99
  Has clientserver: true
  Servername: /tmp/nvimjDRE5e/0

VimTeX project: main
  base: main.tex
  root: /home/lervag/.local/plugged/vimtex/test/example-minimal
  tex: /home/lervag/.local/plugged/vimtex/test/example-minimal/main.tex
  out: 
  log: 
  aux: 
  fls: 
  main parser: current file verified
  compiler: latexmk
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: Zathura
    xwin id: 0
  qf: LaTeX logfile
    addqflist: 169
    fix_paths: 170
    set_errorformat: 168
  document class: minimal
```
