### ISSUE TITLE
Compiler running after Compilation completed

### ISSUE THREAD

**Issue by chriskisskiss** [lervag/vimtex#2131]
### Description

I often run into weird behaviour when compiling (most of the times complaints about missing references, which are there, or a corrupt `.bcf` file), which in most of the cases can be temporarily solved by manually stopping, cleaning and recompiling. I didn't dig deep into that problem so far, but what I noticed that after a `"Compilation complete"`, `:VimtexStatus` still tells me `"Compiler is running"` ... is that expected behaviour? I always have to run `:VimtexCompile` twice, the first time the compiler is being stopped, the second time for compiling.

(newest neovim, newest vimtex, MacOS)

Thank you!

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info
  OS: macOS 11.4 (20F71)
  Vim version: NVIM v0.6.0-dev+15-g3de777d25
  Has clientserver: true
  Servername: /var/folders/md/c8lh6y493xq4xgcc6fp2cdzh0000gn/T/nvim7dhjxX/0

 compiler: latexmk
    configuration: 
      continuous: 1
      callback: 1
      build_dir: build
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
    job: 167
    pid: 47468
    cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -outdir=build -pvc -view=none -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'main.tex'
  viewer: Skim
    process: 
      pid: -
      cmd: osascript -e 'set theFile to POSIX file "/Users/abc/main.pdf"' -e 'set thePath to POSIX path of (theFile as alias)' -e 'tell application "Skim"' -e 'try' -e 'set theDocs to get documents whose path is thePath' -e 'if (count of theDocs) > 0 then revert theDocs' -e 'end try' -e 'open theFile' -e 'end tell' >/dev/null 2>&1 &
  qf: LaTeX logfile
```
