### ISSUE TITLE
Why is the log output of vimtex incomplete?

### ISSUE THREAD

**Issue by ThSGM** [lervag/vimtex#2136]
### Description

Here is a minimal working example showing error log output using vimtex (above) versus Sublime Text and LaTexTools (below). As you can see the vimtex log doesn't show the location of the error of the missing brace in the \frac command. 

I currently have the following error suppression settings:
```
let g:vimtex_quickfix_enabled=1
let g:vimtex_quickfix_mode=2
let g:vimtex_quickfix_autoclose_after_keystrokes=2

let g:vimtex_log_ignore = [
        \ 'Underfull',
        \ 'Overfull',
        \ 'specifier changed to',
        \ 'Token not allowed in a PDF string',
      \ ]
let g:vimtex_log_verbose = "1"
```

![vimtexerror](https://user-images.githubusercontent.com/3396578/129698642-ef895f57-790b-4ded-bbda-ef0e6a37eacc.jpg)

### Steps to reproduce

```
\documentclass{minimal}

\begin{document}
Hello world.

\begin{equation}
  \frac{1}{\sqrt{{1}}
\end{equation}
\end{document}

```

### Expected behavior

Detailed relevant error log info.

### Do you use a latexmkrc file?

NA

### VimtexInfo

```yaml
System info
  OS: Mac OS X 10.14.6 (18G9323)
  Vim version: NVIM v0.5.0
  Has clientserver: true
  Servername: /var/folders/qs/_xq028k12tjgp6btpj5rn3l40000gn/T/nvimw4gppn/0

VimTeX project: temp
  base: temp.tex
  root: /Users/tr/temp
  tex: /Users/tr/temp/temp.tex
  out: /Users/tr/temp/temp.pdf
  log: /Users/tr/temp/temp.log
  aux: /Users/tr/temp/temp.aux
  fls: /Users/tr/temp/temp.fls
  main parser: current file verified
  compiler: latexmk
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
    job: 4
    pid: 98659
    cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'temp.tex'
  viewer: Skim
  qf: LaTeX logfile
    root: /Users/tr/temp
    addqflist: 321
    fix_paths: 322
    main: /Users/tr/temp/temp.tex
    set_errorformat: 320
  document class: minimal
```
