### ISSUE TITLE
E688/E712 on :VimtexTocOpen

### ISSUE THREAD

**Issue by lucc** [lervag/vimtex#2145]
### Description

The command `VimtexTocOpen` fails on my document. The first time I run it I get an E688 and from then on I get E712.

### Steps to reproduce

I use neovim (did not test vim).
I use the following document and the (your) minimal.vim init file from below.

```tex
\documentclass[a4paper]{article}
\usepackage{biblatex}
\addglobalbib{main.bib}
\begin{document}
\cite{something}
\printbibliography
\begin{refsection}
\nocite{*}
\printbibliography[title={Temporary, complete list of references}]
\end{refsection}
\end{document}
``` 

and run `:VimtexTocOpen`.  This results in the following error:
```
Error detected while processing function 74[12]..79[5]..vimtex#parser#toc[14]..vimtex#parser#toc#parse[57]..233[21]..235:
line    4:
E688: More targets than List items
```
and if I run the command again (and again each time) in
```
Error detected while processing function 74[12]..79:                                                                                                                          
line   12:
E712: Argument of filter() must be a List or Dictionary
```

### Expected behavior

The TOC should be shown

### Actual behavior

I get an error message, no TOC is shown.

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
System info
  OS: Linux 5.10.57
  Vim version: NVIM v0.5.0
  Has clientserver: true
  Servername: /tmp/nvimkzZLlD/0

VimTeX project: minimal
  base: minimal.tex
  root: /home/luc/uni/master
  tex: /home/luc/uni/master/minimal.tex
  out: 
  log: 
  aux: 
  fls: 
  main parser: current file verified
  compiler: latexrun
    output: /tmp/nvimkzZLlD/1
    configuration: 
      latexrun options:
        --verbose-cmds
        --latex-args="-synctex=1"
      latexrun engine: pdflatex
  viewer: General
  qf: LaTeX logfile
    addqflist: 72
    fix_paths: 73
    set_errorformat: 71
  document class: article
  packages:
    biblatex
```
