### ISSUE TITLE
help using textidote grammer checker

### ISSUE THREAD

**Issue by rudrab** [lervag/vimtex#2147]
### Description

Dear all,
I am trying to use textidote for grammar check, which is supported by vimtex. 

> Configuration of the wrapper is controlled by the Vim dictionary
> |g:vimtex_grammar_textidote|. In particular, it is important to specify the
> `jar` key to the path of the executable jar file `textidote.jar`. 

This is given in `help`. But I don't understand how to give the path and a map to run textidote in a tex file opened in vim.

My textidote is in ~/.local/bin  and I want to use <Ctrl>+F10 for grammar checking. 

What should I give in `g:vimtex_grammar_textidote`

### Steps to reproduce

NA

### Expected behavior

NA

### Actual behavior

NA

### Do you use a latexmkrc file?

NA

### VimtexInfo

```yaml
System info
  OS: Linux 5.13.12-200.fc34.x86_64
  Vim version: VIM 8.2 (1-3354)
  Has clientserver: true
  Servername: GVIM

VimTeX project: manybody
  base: manybody.tex
  root: /home/rudra/Projects/Book
  tex: /home/rudra/Projects/Book/manybody.tex
  out: /home/rudra/Projects/Book/manybody.pdf
  log: 
  aux: 
  fls: 
  main parser: current file verified
  compiler: latexmk
    configuration: 
      continuous: 0
      callback: 1
      latexmk options:
        -verbose
        -pv
        -file-line-error
        -synctex=1
        -shell-escape
        -interaction=nonstopmode
      latexmk engine: -lualatex
  viewer: General
  qf: LaTeX logfile
    addqflist: 323
    fix_paths: 324
    set_errorformat: 322
  document class: scrartcl
  packages:
    adjustbox
    cancel
    geometry
```
