### ISSUE TITLE
:VimtexCompile does not respect :silent

### ISSUE THREAD

**Issue by lucc** [lervag/vimtex#2149]
### Description

I have an autocomand to run `VimtexCompile` on `BufPostWrite` but its output results in a "press enter" prompt.  Prefixing the command with `silent` does not help.

### Steps to reproduce

I am using neovim only
I run these commands:
```vim
:let g:vimtex_compiler_method = 'latexrun' " not sure if needed for the problem
:edit minmal.tex
:au BufPostWrite <buffer> silent VimtexCompile
:write
```

(I was not able to stop neovim from loading my ftplugin/tex.vim file even though I am using the minimal init file. I hope that does not interfere with reproducability, it does influence VimtexInfo a bit.)

### Expected behavior

File is saved and compilation starts but no "hit enter" prompt. Just the output from `:write` in the command line.

### Actual behavior

File is saved and compilation starts, message from write *and*  the text `VimTeX: Compiler started in background!` appear in the command line causing a "hit enter" pormpt.

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
System info
  OS: Linux 5.10.57
  Vim version: NVIM v0.5.0
  Has clientserver: true
  Servername: /tmp/nvim4A6eeV/0

VimTeX project: minimal
  base: minimal.tex
  root: /home/luc/vimtex-bug
  tex: /home/luc/vimtex-bug/minimal.tex
  main parser: current file verified
  document class: article
  source files:
    minimal.tex
    minimal.tex.d/file.tex
  compiler: latexrun
    engine: pdflatex
    options:
      --verbose-cmds
      --latex-args="-synctex=1 -shell-escape"
      --bibtex-cmd=biber
    build_dir: latex.out
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
