### ISSUE TITLE
Broken indent after \item in insert mode (with YouCompleteMe)

### ISSUE THREAD

**Issue by seyaryuki** [lervag/vimtex#2156]
### Description

I recently updated all my plugins, and now, if I type multiple items in insert mode, they will be indented like this :

```
\begin{itemize}
  \item foo
    \item bar
      \item foobar
\end{itemize}
```

However, `=ie` will indent it correctly.

The problem disappears if I turn off YCM.
This may be related to : https://github.com/lervag/vimtex/issues/239

### Steps to reproduce

Minimal vimrc :

```
set nocompatible
call plug#begin()
Plug 'lervag/vimtex'
Plug 'Valloric/YouCompleteMe', { 'do': './install.py --all' } " commenting this line fixes the issue
call plug#end()
filetype plugin indent on
syntax enable
```

### Expected behavior

For the `\item` to be correctly indented after typing them in insert mode.

### Actual behavior

Nothing happens when I type `\item` (the line is not indented properly).

### Do you use a latexmkrc file?

Yes

### VimtexInfo

```yaml
System info
  OS: Debian GNU/Linux 11 (bullseye)
  Vim version: VIM 8.2 (1-2434)
  Has clientserver: true
  Servername: undefined (vim started without --servername)

VimTeX project: test
  base: test.tex
  root: /home/seyaryuki/tmp/test_vimtex
  tex: /home/seyaryuki/tmp/test_vimtex/test.tex
  main parser: current file
  document class: 
  compiler: latexmk
    engine: -pdf
    options:
      -pdflatex="xelatex --shell-escape %O %S"
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
```
