### ISSUE TITLE
Can't use % move matching  $ with nvim-treesitter

### ISSUE THREAD

**Issue by krisfans** [lervag/vimtex#2158]
### Description

Can't use `%` key move matching `$` with [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter).

### Steps to reproduce

Steps to reproduce:
1. `nvim -u minimal.vim minimal.tex`
2. Move the cursor to the `$` and press the `%` key

**minimal.vim**

```vim
set nocompatible
set runtimepath+=~/.cache/nvim/dein/repos/github.com/Shougo/dein.vim
call dein#begin($HOME . '/.cache/nvim/dein')
call dein#add($HOME . '/.cache/nvim/dein')
call dein#add('nvim-treesitter/nvim-treesitter')
call dein#add('nvim-treesitter/nvim-treesitter-refactor')
call dein#add('lervag/vimtex')
call dein#end()

filetype plugin indent on
syntax enable

lua << EOF
require'nvim-treesitter.configs'.setup {
    ensure_installed = "all",
    highlight = { enable = true, },
    indent = { enable = true },
    refactor = {
        highlight_definitions = { enable = true },
        highlight_current_scope = { enable = false },
    },
}
EOF
```

**minimal.tex**
```latex
\documentclass{article}
\begin{document}
$ a+b = b+a$, $\sin^2 x + \cos^2 x =1$,
\[ f(x) = f(-x)\]
$\{1 \in N\}$
\end{document}
```

### Actual behavior

![Peek 2021-09-04 23-14](https://user-images.githubusercontent.com/57793534/132100036-5c2feb1e-4a00-45d7-b2ec-3d2140e6db82.gif)

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
System info
  OS: Ubuntu 20.04.3 LTS
  Vim version: NVIM v0.5.0
  Has clientserver: true
  Servername: /tmp/nvimTdkDmm/0

VimTeX project: minimal
  base: minimal.tex
  root: /home/kris/文档
  tex: /home/kris/文档/minimal.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    process: 
      jobid: 3
      output: /tmp/nvimTdkDmm/1
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -e '$pdf_previewer = "xdg-open"' -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'minimal.tex'
      pid: 15580
  viewer: General
  qf method: LaTeX logfile
```
