### ISSUE TITLE
help with deprecated options

### ISSUE THREAD

**Issue by andynameistaken** [lervag/vimtex#2159]
### Description

Hi, I haven't used vimtex in ages and I wish to get back to it however things I have in my `init.nvim` seem depreceated:

```
" ---------------------------------------
"  	VimTex	
" -----------------------------------------------------------------------------
"  VIMTEX OPTIONS
"  ----------------------------------------------------------------------------
if has('unix')
    if has('mac')
        let g:vimtex_view_method = "skim"
        let g:vimtex_view_general_viewer
                \ = '/Applications/Skim.app/Contents/SharedSupport/displayline'
        let g:vimtex_view_general_options = '-r @line @pdf @tex'

        " This adds a callback hook that updates Skim after compilation
        let g:vimtex_compiler_callback_hooks = ['UpdateSkim']
        function! UpdateSkim(status)
            if !a:status | return | endif

            let l:out = b:vimtex.out()
            let l:tex = expand('%:p')
            let l:cmd = [g:vimtex_view_general_viewer, '-r']
            if !empty(system('pgrep Skim'))
            call extend(l:cmd, ['-g'])
            endif
            if has('nvim')
            call jobstart(l:cmd + [line('.'), l:out, l:tex])
            elseif has('job')
            call job_start(l:cmd + [line('.'), l:out, l:tex])
            else
            call system(join(l:cmd + [line('.'), shellescape(l:out), shellescape(l:tex)], ' '))
            endif
        endfunction
    else
        let g:latex_view_general_viewer = "zathura"
        let g:vimtex_view_method = "zathura"
    endif
elseif has('win32')

endif

let g:tex_flavor = "latex"
let g:vimtex_quickfix_open_on_warning = 0
let g:vimtex_quickfix_mode = 2
if has('nvim')
    let g:vimtex_compiler_progname = 'nvr'
endif

" Can hide specifc warning messages from the quickfix window
" Quickfix with Neovim is broken or something
" https://github.com/lervag/vimtex/issues/773
let g:vimtex_quickfix_latexlog = {
            \ 'default' : 1,
            \ 'fix_paths' : 0,
            \ 'general' : 1,
            \ 'references' : 1,
            \ 'overfull' : 1,
            \ 'underfull' : 1,
            \ 'font' : 1,
            \ 'packages' : {
            \   'default' : 1,
            \   'natbib' : 1,
            \   'biblatex' : 1,
            \   'babel' : 1,
            \   'hyperref' : 1,
            \   'scrreprt' : 1,
            \   'fixltx2e' : 1,
            \   'titlesec' : 1,
            \ },
            \}
```

How to replace deprecated  `vimtex_compiler_callback_hooks `vimtex_quickfix_latexlog` to make it work again with no errors? Is it valid config for macOS with Skim as pdf reader or should I redo it?

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info
  OS: Mac OS X 10.15.7 (19H1323)
  Vim version: NVIM v0.5.0
  Has clientserver: true
  Servername: /var/folders/jn/vb71t3z977jdp4f_br390y5h0000gn/T/nvimHG4hm0/0

VimTeX project: Main
  base: Main.tex
  root: /Users/andy/Devel/Java/Java_Tutorial/tex
  tex: /Users/andy/Devel/Java/Java_Tutorial/tex/Main.tex
  main parser: current file verified
  document class: scrbook
  packages: mystyle scrhack
  source files:
    Main.tex
    control-flow.tex
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Skim
  qf method: LaTeX logfile
```
