### ISSUE TITLE
inner environment text-object fails on { being the first char after \begin{}

### ISSUE THREAD

**Issue by habamax** [lervag/vimtex#2160]
### Description

No way to visually select or delete inner environment with `vie`, `die` for the code block of the json source.

### Steps to reproduce

1. `vim -u minimal.vim minimal.tex`
2. position cursor on `"contacts"`
3. `vie`

## minimal.tex
```
\documentclass{minimal}
\begin{document}
\begin{minted}
    {
        "contacts": [
          {
            "source_id": "mandatory"
          }
        ]
    }
\end{minted}
\end{document}
```

### Expected behavior

Contents of the `minted` environment is visually selected:
![image](https://user-images.githubusercontent.com/234774/132125625-23cdcdb1-de0c-467a-b4ed-b3a379ccbf16.png)

### Actual behavior

A single char is selected at the end of the environment:
![image](https://user-images.githubusercontent.com/234774/132125662-a90d3aa0-0330-40e9-b81f-9481749d52bb.png)

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info
  OS: Microsoft Windows 10 Pro (10.0.19041 N/A Build 19041)
  Vim version: VIM 8.2 (1-3399)
  Has clientserver: true
  Servername: GVIM

VimTeX project: minimal
  base: minimal.tex
  root: C:\Users\maksim.kim
  tex: C:\Users\maksim.kim\minimal.tex
  main parser: current file
  document class: 
  compiler: latexmk
    engine: -lualatex
    options:
      -shell-escape
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    build_dir: minimal
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
