### ISSUE TITLE
vimtex_quickfix_autoclose_after_keystrokes close active Quickfix buffer

### ISSUE THREAD

**Issue by einhander** [lervag/vimtex#2161]
### Description

Hi, I use nvim and  vimtex_quickfix_autoclose_after_keystrokes. Vimtex count movement in Quickfix buffer and close it after couner reached. It's somehow connected with language settings because if I use LANG=C  vimtex_quickfix_autoclose_after_keystrokes works as expected.

### Steps to reproduce

Set language into non English locale.
set vimtex_quickfix_autoclose_after_keystrokes non zero.
Open quickfix buffer and switch to it.

### Expected behavior

Quickfix buffer is open, despite vimtex_quickfix_autoclose_after_keystrokes value.

### Actual behavior

Quickfix buffer close after vimtex_quickfix_autoclose_after_keystrokes reached.

### Do you use a latexmkrc file?

yes, but non relevant

### VimtexInfo

```yaml
System info
  OS: Debian GNU/Linux bookworm/sid
  Vim version: NVIM v0.4.4
  Has clientserver: true
  Servername: /tmp/nvimHpe4n5/0

VimTeX project: lecture
  base: lecture.tex
  root: /home/einhander/Documents/1Печатное/Учебные/Лекции/Экологическая безопасность/Лекция 01
  tex: /home/einhander/Documents/1Печатное/Учебные/Лекции/Экологическая безопасность/Лекция 01/lecture.tex
  main parser: current file
  document class: 
  source files:
    lecture.tex
    inc/settings.tex
  compiler: latexmk
    engine: -pdf
    options:
      -pdf
      -shell-escape
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
