### ISSUE TITLE
E716: Key not present in Dictionary: "custom_patterns"

### ISSUE THREAD

**Issue by qshzh** [lervag/vimtex#2169]
### Description

I tried my previous worked tex file. The error popped when I opened the tex file.
```shell
Error detected while processing BufRead Autocommands for "*.tex"..function dist#ft#FTtex[47]..FileType Autocommands for "*"..function <SNR>35_LoadFTPlugin[17]..script /home/qzhang419/dotfiles/vim/bundle/vimtex/ ftplugin/tex.vim[25]..function vimtex#init[8]..<SNR>113_init_buffer[74]..BufRead Autocommands for "*.tex"..function dist#ft#FTtex[47]..FileType Autocommands for "*"..function <SNR>35_LoadFTPlugin[17]..script /h ome/qzhang419/dotfiles/vim/bundle/vimtex/ftplugin/tex.vim[25]..function vimtex#init[8]..<SNR>113_init_buffer[71]..vimtex#complete#init_buffer[9]..242: 
line 4: 
E716: Key not present in Dictionary: "custom_patterns"
```

### Steps to reproduce

1. vim -u minimal.vim minimal.tex
2. minimal.vim and minimal.tex are copied from below example

### Expected behavior

no error message

### Actual behavior

"minimal.tex" 4L, 69B
Error detected while processing BufRead Autocommands for "*.tex"..function dist#ft#FTtex[47]..FileType Autocommands for "*"..Syntax Autocommands for "*"..function <SNR>8_SynSet[25]..script /home/qzhang419/dotfi
les/vim/bundle/vimtex/syntax/tex.vim[23]..function vimtex#syntax#core#init[402]..<SNR>87_match_math_sub_super:
line   10:
E475: Invalid argument: texMathSuper "(" contained conceal cchar=~A

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info
  OS: Ubuntu 20.04.2 LTS
  Vim version: VIM 8.2 (1-2815)
  Has clientserver: false

vimtex project: minimal
  base: minimal.tex
  root: /tmp
  tex: /tmp/minimal.tex
  out:
  log:
  aux:
  fls:
  main parser: current file verified
  compiler: latexmk
    configuration:
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: General
  qf: LaTeX logfile
    addqflist: 56
System info
  OS: Ubuntu 20.04.2 LTS
  Vim version: VIM 8.2 (1-2815)
  Has clientserver: false

vimtex project: minimal
  base: minimal.tex
  root: /tmp
  tex: /tmp/minimal.tex
  out:
  log:
  aux:
  fls:
  main parser: current file verified
  compiler: latexmk
    configuration:
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: General
  qf: LaTeX logfile
    addqflist: 56
    fix_paths: 57
    set_errorformat: 55
  document class: minimal
```
