### ISSUE TITLE
Regression in package detection

### ISSUE THREAD

**Issue by clason** [lervag/vimtex#2170]
### Description

The commit https://github.com/lervag/vimtex/commit/92d268ad74ebee209403c2a23d8c3ea30b47493f introduced a regression in the detection of packages that are included "recursively".

Consider the following minimal(!) example:
* `test.sty`
```tex
\RequirePackage{cleveref}
```
* `test1.tex`
```tex
\cref{foo}
```
* `test.tex`
```tex
\documentclass{minimal}
\usepackage{test}

\begin{document}
\include{test1}
\end{document}
```

A similar issue occurs with packages loaded in a custom `myclass.cls`. 

### Steps to reproduce

1. `pdflatex test.tex`
2. `nvim --clean -u minimal.vim test1.tex` (note: subfile!)

### Expected behavior

Syntax highlighting for `\cref`.

### Actual behavior

No syntax highlighting for `\cref`.

### Do you use a latexmkrc file?

N/A

### VimtexInfo

```yaml
VimTeX project: test
  base: test.tex
  root: /Users/clason
  tex: /Users/clason/test.tex
  main parser: recursive search
  document class: minimal
  packages: test
  source files:
    test.tex
    test1.tex
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
