### ISSUE TITLE
Significant slowdown doing basic tasks in vimtex

### ISSUE THREAD

**Issue by ThSGM** [lervag/vimtex#2174]
### Description

I am trying to diagnose some significant slowdown when using vimtex. For example, the lag is so bad that just simple scrolling up and down via 'j' and 'k' is significantly laggy.

I ran the following profile commands:

```vim
:profile start profile.log
:profile func *
:profile file *
" At this point do slow actions
:profile pause
:noautocmd qall!
```

and then did some simple scrolling up/down using 'j' and 'k'. I have uploaded the profile.log file at the [following gist](https://gist.github.com/ThSGM/4131d3575e7b1de4154af9192f70daa8). It indicates the main culprits are:

```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
  101   0.577608   0.006751  176()
   51   0.229148   0.004134  vimtex#delim#get_matching()
  173   0.225098   0.127928  <SNR>117_get_delim()
  101   0.202192   0.200406  <SNR>62_Highlight_Matching_Pair()
  101   0.191496   0.001175  vimtex#syntax#in_comment()
  101   0.190321   0.002001  vimtex#syntax#in()
  101   0.188321             vimtex#syntax#stack()
  101   0.176010   0.002344  vimtex#delim#get_current()
   27   0.165812   0.165549  <SNR>117_get_matching_delim()
  101   0.122420             UltiSnips#CursorMoved()
  101   0.121095             provider#python3#Call()
   24   0.104004   0.000876  vimtex#cmd#get_at()
   24   0.101313   0.001430  vimtex#cmd#get_current()
   24   0.097361   0.003269  <SNR>114_get_cmd()
   72   0.092461   0.004705  <SNR>114_get_cmd_part()
   72   0.052833   0.001401  vimtex#delim#get_next()
   24   0.052817   0.001810  <SNR>117_parser_env()
   75   0.032646   0.011724  <SNR>117_parser_delim()
  101   0.024568   0.006274  <SNR>151_handle_autocmd()
  491   0.016589   0.005265  vimtex#pos#set_cursor()

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
  101   0.202192   0.200406  <SNR>62_Highlight_Matching_Pair()
  101              0.188321  vimtex#syntax#stack()
   27   0.165812   0.165549  <SNR>117_get_matching_delim()
  173   0.225098   0.127928  <SNR>117_get_delim()
  101              0.122420  UltiSnips#CursorMoved()
  101              0.121095  provider#python3#Call()
  150   0.014280   0.012480  <SNR>117_parser_delim_get_regexp()
  563   0.012758   0.012279  <SNR>132_parse_args()
   75   0.032646   0.011724  <SNR>117_parser_delim()
  101   0.016553   0.008053  <SNR>151_source_move()
  101   0.577608   0.006751  176()
   75              0.006642  <SNR>117_parser_delim_get_corr()
  101   0.024568   0.006274  <SNR>151_handle_autocmd()
  491   0.016589   0.005265  vimtex#pos#set_cursor()
   72   0.092461   0.004705  <SNR>114_get_cmd_part()
   51   0.229148   0.004134  vimtex#delim#get_matching()
  101   0.007850   0.003669  <SNR>151_highlight_line()
   24   0.097361   0.003269  <SNR>114_get_cmd()
   96              0.002623  <SNR>114_text_between()
  101              0.002369  <SNR>151_set_line_color()
```

Moreover, the highest offender is 176(), which related to this:

```
FUNCTION  176()
    Defined: ~/.local/share/nvim/plugged/vimtex/autoload/vimtex/matchparen.vim:72
Called 101 times
Total time:   0.577608
 Self time:   0.006751


```

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info
  OS: Mac OS X 10.14.6 (18G9323)
  Vim version: NVIM v0.5.0
  Has clientserver: true
  Servername: /var/folders/qs/_xq028k12tjgp6btpj5rn3l40000gn/T/nvim2gTKxb/0

VimTeX project: expasymbook
  base: expasymbook.tex
  root: /Users/localstuff/expasymbook
  tex: /Users/localstuff/myfile.tex
  main parser: current file verified
  document class: memoir
  packages: afterpage amsbsy amsfonts amsgen amsmath amsopn amssymb amstext array atbegshi atveryend auxhook bigintcalc bitset bm book-maths book-preamble bookmark calc caption caption3 cleveref colortbl dcolumn delarray derivative empheq enumitem eso-pic etexcmds everysel everyshi expl3 float fontenc fontspec fontspec-xetex gettitlestring graphics graphicx hycolor hypcap hyperref ifluatex iftex ifthen ifxetex import infwarerr intcalc keyval kvdefinekeys kvoptions kvsetkeys leading letltxmacro listings lscape lstlang1 lstmisc ltxcmds luatex85 mathrsfs mathtools memhfixc metalogo mhsetup microtype multirow nameref natbib nicefrac ntheorem oubraces pdfescape pdflscape pdfpages pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfplots pgfplotstable pgfrcs pgfsys pifont preview ragged2e realscripts refcount relsize rerunfilecheck showkeys soul stringenc subfig tabularx tabulary textcase textcomp tikz trig uniquecounter url xcolor xltxtra xparse xunicode
  tex program: xelatex
  source files:
    expasymbook.tex
    title/title.tex
    contents/contents.tex
    chap_expint/expint.tex
    chap_airy/airy.tex
    chap_higherorder/higherorder.tex
    chap_rules/rules.tex
    chap_lineareig/lineareig.tex
    chap_fkdv/fkdv.tex
    chap_crystal/crystal.tex
    chap_lowfroude/lowfroude.tex
    chap_fingering/fingering.tex
    chap_complexrays/complexrays.tex
    chap_MMS/MMS.tex
    chap_PDEs/PDEs.tex
    appendices/problems.tex
  compiler: latexmk
    engine: -xelatex
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    process: 
      jobid: 5
      output: /var/folders/qs/_xq028k12tjgp6btpj5rn3l40000gn/T/nvim2gTKxb/2
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -xelatex -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'expasymbook.tex'
      pid: 42904
  viewer: Skim
    process: 
      pid: -
      cmd: osascript -e 'set theFile to POSIX file "/Users/trinh/GoogleDrive/scratch_gdrive/articles-in-progress/expasymbook/expasymbook.pdf"' -e 'set thePath to POSIX path of (theFile as alias)' -e 'tell application "Skim"' -e 'try' -e 'set theDocs to get documents whose path is thePath' -e 'if (count of theDocs) > 0 then revert theDocs' -e 'end try' -e 'open theFile' -e 'end tell' >/dev/null 2>&1 &
  qf method: LaTeX logfile
```
