### ISSUE TITLE
Folding incorrect when comments are present in environments

### ISSUE THREAD

**Issue by ffeppon** [lervag/vimtex#2177]
### Description

Dear Karl Lervag,

I noticed that the folding of vimtex seems to fail when comments are present in the equation environment as in the example below:

```latex
\documentclass[a4paper,10pt,reqno,draft]{amsart}

\begin{document}

\section{Introduction}

Blabla 

\section{A second thing}
 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec imperdiet posuere
 venenatis. Aliquam dapibus interdum elit. Proin convallis non justo et mollis. Donec
 ut risus sagittis, lacinia sem laoreet, pulvinar eros. Mauris accumsan blandit
 sapien et consectetur. Morbi fringilla, urna ut vehicula volutpat, sapien erat
 iaculis purus, sed laoreet augue orci nec ligula. Nullam quis dignissim dui. Aenean
 sit amet nunc sed nisi imperdiet bibendum sed eget neque. Sed maximus quam ut diam
 fermentum faucibus. Nunc non commodo justo.

\begin{equation}
    |||A|||_N=
%\max_{z\equiv (z_{i_2j_2})_{\substack{1\<i_2\<N \\ 1\<j_2\<K_{i_2}}}} 
%    \frac{\sum_{\substack{1\<i_1\<N \\ 1\<j_1\<K_{i_1}}} \left|
%    \sum_{\substack{1\<i_2\<N \\ 1\<j_2\<K_{i_2}}} A_{i_1j_1,i_2j_2}z_{i_2j_2}
%    \right|^{2} }{\sum_{\substack{1\<i_2\<N \\
%    1\<j_2\<K_{i_2}}} |z_{i_2j_2}|^{2}} =
    \max_{z\equiv (z_{i_2j_2})_{\substack{1\<i_2\<N \\ 1\<j_2\<K_{i_2}}}} 
    \frac{||A z||_2}{||z||_2}.
\end{equation}
Nam malesuada mollis consequat. Suspendisse ac pellentesque justo. Donec ac turpis
urna. Nunc quis tempor tortor. Mauris sagittis aliquam diam eget lacinia. Vestibulum
aliquet porttitor mattis. Suspendisse gravida, justo non ullamcorper feugiat, quam
sapien vulputate magna, nec lacinia augue velit et mi. Morbi non massa vitae tellus
semper bibendum. Vestibulum ante nisl, mattis et erat vel, suscipit aliquam felis.
Phasellus convallis in enim vitae scelerisque. Nunc pulvinar lacinia lectus, ut
facilisis diam ornare ac. Nam sit amet sodales est. Cras vestibulum quam at venenatis
sagittis. Fusce id est lobortis, pretium ante nec, suscipit turpis.

\section{A third thing}

Aenean at condimentum arcu, a consectetur enim. Ut vitae lacinia ante, pretium
consectetur leo. Sed congue nisl a elit iaculis sollicitudin non in tellus. Donec non
eros et purus porta accumsan a id dui. Vivamus bibendum, turpis id rutrum volutpat,
massa nisl vestibulum purus, at viverra felis justo quis urna. Vivamus et erat eget
%tellus volutpat maximus. Donec urna massa, mollis sed lacus in, porttitor ornare ex.
%Aliquam erat volutpat. Nam vel auctor nibh. In ullamcorper, libero eget blandit
%sagittis, odio nunc blandit eros, eu sodales mauris risus nec sem. Nulla ultrices
%finibus ipsum, quis viverra urna scelerisque quis. 

consectetur leo. Sed congue nisl a elit iaculis sollicitudin non in tellus. Donec non
eros et purus porta accumsan a id dui. Vivamus bibendum, turpis id rutrum volutpat,
massa nisl vestibulum purus, at viverra felis justo quis urna. Vivamus et erat eget
\bibliography{bibliography}
\bibliographystyle{acm}
\end{document}
```

When enabling the folding with 
```vim
let g:vimtex_fold_enabled = 1
set fillchars=fold:\ 
```
the second section does not get folded completely and stops at line 22.

Is it to be expected ?

Many thanks,
Florian 

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info
  OS: Fedora release 32 (Thirty Two)
  Vim version: NVIM v0.4.4
  Has clientserver: true
  Servername: /tmp/nvimpI19oT/0

VimTeX project: test
  base: test.tex
  root: /scratch/users/ffeppon/polybox/latex/draft_homogenization
  tex: /scratch/users/ffeppon/polybox/latex/draft_homogenization/test.tex
  main parser: current file verified
  document class: amsart
  compiler: latexmk
    engine: -pdf
    options:
      -pdf
      -shell-escape
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    engine: -pdf
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
