### ISSUE TITLE
`\lv` does not reopen a viewer if it has been accidentally closed

### ISSUE THREAD

**Issue by Rmano** [lervag/vimtex#2182]
### Description

I am *almost* sure that it used to work. Basically, if you start compilation and accidentally close the viewer, issuing a `\lv` command will not re-open it again.
Maybe I am wrong and it never worked like that, in that case please forgive me...

### Steps to reproduce

1. `gvim -u ./minivimrc reopen.tex`
2. issue `\ll`
3. close the viewer window
4. issue `\lv`

nothing happens...

The files are (`reopen.tex`, `minivimrc`, `latexmkrc`)

```latex
\documentclass{article}
\usepackage[T1]{fontenc}
\begin{document}
    Hello world!
\end{document}
```

```vim
set nocompatible
let &rtp  = '~/.vim/plugged/vimtex,' . &rtp
let &rtp .= ',~/.vim/plugged/vimtex/after'
filetype plugin indent on
syntax enable
```

```perl
$pdflatex = 'pdflatex -synctex=1 %O %S';
$pdf_update_method = 0;
$dvi_mode = 0;
$pdf_mode = 1;
$preview_continuous_mode = 1;
$pdf_previewer = 'start evince';

push @generated_exts, "cb";
push @generated_exts, "cb2";
push @generated_exts, "spl";
push @generated_exts, "nav";
push @generated_exts, "snm";
push @generated_exts, "tdo";
push @generated_exts, "nmo";
push @generated_exts, "brf";
push @generated_exts, "nlg";
push @generated_exts, "nlo";
push @generated_exts, "nls";
push @generated_exts, "synctex.gz";
push @generated_exts, "tex.latexmain";
push @generated_exts, "run.xml";
```

### Expected behavior

I was expecting a new viewer window to appear.

### Actual behavior

No viewer window appears; I have to do a `\ll \ll` (next time, I'll learn to not to close the window...)

### Do you use a latexmkrc file?

Yes

### VimtexInfo

```yaml
System info
  OS: Ubuntu 20.04.3 LTS
  Vim version: VIM 8.1 (1-2269)
  Has clientserver: true
  Servername: GVIM1

VimTeX project: reopen
  base: reopen.tex
  root: /home/romano/software/bugs/vimtex
  tex: /home/romano/software/bugs/vimtex/reopen.tex
  main parser: current file verified
  document class: article
  packages: fontenc
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    engine: -pdf
    callback: 1
    continuous: 1
    executable: latexmk
    process: 
      jobid: process 23769 run
      output: /tmp/vkmeC7J/1
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -e '$pdf_previewer = "xdg-open"' -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'reopen.tex'
      pid: 23769
  viewer: General
    process: 
      pid: -
      cmd: xdg-open '/home/romano/software/bugs/vimtex/reopen.pdf' >/dev/null 2>&1 &
  qf method: LaTeX logfile
```
