### ISSUE TITLE
`imaps` break when using treesitter highlighting

### ISSUE THREAD

**Issue by Thyrum** [lervag/vimtex#2183]
### Description

The `imaps` defined by vimtex (like `` `l`` for `\lambda`) break when using
TreeSitter for highlighting.

### Steps to reproduce

Using `minimal.tex` and `minimal.vim` as below (with `vim-plug` installed), the imaps don't work. Calling `TSBufToggle highlight` causes them to work again.

`minimal.tex`:
```TeX
\documentclass{article}

\usepackage{amsmath}

\begin{document}
\begin{align}
	\text{Type }`l\text{ here: }
\end{align}

\end{document}
```

`minimal.vim`:
```vim
call plug#begin()

Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
Plug 'lervag/vimtex'

call plug#end()

lua <<EOF
require'nvim-treesitter.configs'.setup {
  ensure_installed = { "latex" },
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false,
  },
}
EOF
```

### Expected behavior

I expect `` `l`` to produce `\lambda` whenever I am in math mode, both with and without treesitter highlighting enabled.

### Actual behavior

Typing `` `l`` in a math mode area only produces `\lambda` whenever treesitter highlighting is disabled.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info
  OS: on:       Arch Linux
  Vim version: NVIM v0.5.0
  Has clientserver: true
  Servername: /tmp/nvimnWNZGc/0

VimTeX project: test
  base: test.tex
  root: /home/aron/treesitter
  tex: /home/aron/treesitter/test.tex
  main parser: current file verified
  document class: article
  packages: amsmath
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    build_dir: build
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
