### ISSUE TITLE
10x longer startup times when using specific settings

### ISSUE THREAD

**Issue by ThSGM** [lervag/vimtex#2185]
### Description

I am trying to diagnose what can be done to reduce my vimtex startup times. It is quite significant at the moment. I have prepared a video below using [this profiler.](https://github.com/hyiltiz/vim-plugins-profile) Basically, when I comment in the following code: 

```
let g:vimtex_view_method = "skim"
let g:vimtex_compiler_progname = "nvr"
let g:vimtex_view_general_viewer
	\ = '/Applications/Skim.app/Contents/SharedSupport/displayline'
let g:vimtex_view_general_options = '-r @line @pdf @tex'
```

the neovim startup time is about 10x longer than if I comment out that code. I have attached the [profile.log here](https://gist.github.com/ThSGM/bb05589890dba167858771310c4350e1). 

https://user-images.githubusercontent.com/3396578/135076324-91ea20cc-97b7-4697-8231-61a75da18304.mp4

I can try and prepare a minimal test file, but that might require some more time for me to strip out the necessary stuff and re-run the tests. Perhaps this may do to get the ball rolling.

 

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info
  OS: Mac OS X 10.15.7 (19H1217)
  Vim version: NVIM v0.6.0-dev+59-g2475161de
  Has clientserver: true
  Servername: /var/folders/yr/htyy1zjx2pb9_1s11ns1yz1m0000gn/T/nvimB0St0M/0

VimTeX project: test
  base: test.tex
  root: /Users/trinh/Downloads/vim-plugins-profile-master
  tex: /Users/trinh/Downloads/vim-plugins-profile-master/test.tex
  main parser: current file
  document class: 
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Skim
  qf method: LaTeX logfile
```
