### ISSUE TITLE
Change compiler options on the fly, specifically shell-escape

### ISSUE THREAD

**Issue by hamdav** [lervag/vimtex#2187]
### Description

Hi!

### Steps to reproduce

I am trying to map a key to toggle compiling with shell-escape and compiling without it. I thus put

```vim
" Create mapping to toggle compiling with shell escape or not
nnoremap <F12> :call ShellEscape()<CR>
let g:shell_escape_is_on = 0
function! ShellEscape()
    if g:shell_escape_is_on
        let g:vimtex_compiler_latexmk = {
                    \ 'options' : [
                        \   '-verbose',
                        \   '-file-line-error',
                        \   '-synctex=1',
                        \   '-interaction=nonstopmode',
                        \ ],
                        \}
        echo "shell escape disabled"
        let g:shell_escape_is_on = 0
    else
        let g:vimtex_compiler_latexmk = {
                    \ 'options' : [
                        \   '-shell-escape',
                        \   '-verbose',
                        \   '-file-line-error',
                        \   '-synctex=1',
                        \   '-interaction=nonstopmode',
                        \ ],
                        \}
        let g:shell_escape_is_on = 1
        echo "shell escape enabled"
    endif
endfunction
```

in `.config/nvim/ftplugin/tex.vim` and try to compile some file requiring shell escape: for example

```tex
\documentclass{article}
\usepackage{minted}
\begin{document}
\begin{minted}{c}
int main() {
printf("hello, world");
return 0;
}
\end{minted}
\end{document}
```

press `F12`, compile with `\ll`.

### Expected behavior

I'd expect the new compiler options to be loaded and the file to be compiled with shell-escape.

### Actual behavior

In reality, the options seem to be ignored. If I set the shell-escape option directly in tex.vim, it works.

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
System info
  OS: macOS 11.2.3 (20D91)
  Vim version: NVIM v0.5.0
  Has clientserver: true
  Servername: /var/folders/mn/7wv53fcj6m95stzmb3nq73bw0000gn/T/nvimkcSbCp/0

VimTeX project: tmp
  base: tmp.tex
  root: /Users/davidhambraeus/tmp
  tex: /Users/davidhambraeus/tmp/tmp.tex
  main parser: current file verified
  document class: article
  packages: calc catchfile etexcmds etoolbox fancyvrb float framed fvextra ifluatex ifplatform iftex ifthen infwarerr keyval kvoptions kvsetkeys lineno ltxcmds minted pdftexcmds shellesc upquote xcolor xstring
  compiler: latexmk
    engine: -pdf
    options:
      -shell-escape
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    engine: -pdf
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Skim
  qf method: LaTeX logfile
```
