### ISSUE TITLE
Startup Error "List or Blob required"

### ISSUE THREAD

**Issue by ryleelyman** [lervag/vimtex#2188]
### Description

When opening a LaTeX file in a project I get the following error:
<img width="1437" alt="Screen Shot 2021-10-01 at 11 45 41 AM" src="https://user-images.githubusercontent.com/46907231/135649540-a0503074-1bf7-4ab3-9bc7-3b1425ae65e8.png">

After this it appears that VimTeX fails to load; expected commands like `gf`, `\ll` and others do not work, and `:VimtexInfo` returns "Not an editor command".

### Steps to reproduce

Minimal test file:
``` lua
vim.g.maplocallleader = '\\'
vim.cmd 'packadd packer.nvim'

return require('packer').startup(function(use)
	use 'lervag/vimtex'
end)
```

Minimal test tex file: (opening `test.tex` as a new file works fine. After writing this and invoking `:e preamble.tex` I get the error above.)
``` latex
\documentclass{article}
\input{preamble}

\begin{document}
\input{content}
\end{document}
```

### Expected behavior

Vimtex to load

### Actual behavior

The error mentioned above:
<img width="1437" alt="Screen Shot 2021-10-01 at 11 45 41 AM" src="https://user-images.githubusercontent.com/46907231/135651007-1d4002da-c080-4753-ab47-cab4f307ef13.png">
 

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
This is what I get when running `:VimtexInfo` on the above file after saving it.
I also get a similar error to the one described above.

System info
  OS: macOS 11.5.2 (20G95)
  Vim version: NVIM v0.6.0-dev+368-g9337fff8a
  Has clientserver: true
  Servername: /var/folders/2y/hwll5x9j6271lr30klvck8f80000gn/T/nvimmPPTRh/0
```

If I instead run `:VimtexInfo` on a completely blank TeX document I get
```
System info
  OS: macOS 11.5.2 (20G95)
  Vim version: NVIM v0.6.0-dev+368-g9337fff8a
  Has clientserver: true
  Servername: /var/folders/2y/hwll5x9j6271lr30klvck8f80000gn/T/nvimmPPTRh/0

VimTeX project: test2
  base: test2.tex
  root: /Users/rylee/.config/nvim
  tex: /Users/rylee/.config/nvim/test2.tex
  main parser: current file
  document class: 
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
```
