### ISSUE TITLE
E714: List required with omnifunc

### ISSUE THREAD

**Issue by oponkork** [lervag/vimtex#2189]
### Description

I get the following error on omnicompletion

```vim 
Error detected while processing function vimtex#complete#omnifunc[30]..141[1]..142[4]..<SNR>72_load_from_package[18]..vimtex#kpsewhich#find:
line   10:
E714: List required
```
Information:
```txt
NVIM v0.5.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim/src/neovim-0.5.1/build/config -I/build/neovim/src/neovim-0.5.1/src -I/usr/include -I/build/neovim/src/neovim-0.5.1/build/src/nvim/auto -I/build/neovim/src/neovim-0.5.1/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Steps to reproduce

Minimal vimrc:
```vim
filetype indent plugin on
syntax on

call plug#begin('~/.local/share/nvim/plugged')
Plug 'lervag/vimtex'
call plug#end()
```

Steps to reproduce:

-  Open a new tex file
- Write `$\al$`, with cursor after `l` try omnicomplete using `C-X, C-O`, the error appears

### Do you use a latexmkrc file?

Irrelevant?

### VimtexInfo

```yaml
System info
  OS: Linux 5.14.5-arch1-1
  Vim version: NVIM v0.5.1
  Has clientserver: true
  Servername: /tmp/nvimdGjMao/0

VimTeX project: a
  base: a.tex
  root: /home/oponkork
  tex: /home/oponkork/a.tex
  main parser: current file
  document class: 
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
