### ISSUE TITLE
Iist \item is being indented despite indentation settings

### ISSUE THREAD

**Issue by K4LCIFER** [lervag/vimtex#2193]
### Description

I am trying to disable all automatic indentation for latex files, but for some reason I cannot disable the indentation for the `\item` macro. As soon as I finish typing `\item`, it gets autoindented despite `cin`, `ai`, and `si` and `inde` being disabled in vim. 
I have tracked it down to vimtex, as if I disable the vimtex plugin, the `\item` macro is no longer being indented.

### Steps to reproduce

1. enter the command `:setlocal noautoindent nosmartindent nocindent inde= `
2. create an itemize environment
```
\begin{itemize}
\end{itemize}
```
3. type `\item` within that environment and observe that it is indented despite being disabled as shown above.

### Expected behavior

I expect that when I disable indentation, indentation will indeed be disabled. I would expect that this auto indentation of `\item` would be governed by the `smartindent` setting in vim, but apparently it is not.

### Actual behavior

The `\item` macro is being indented despite indentation being disabled.

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
System info
  OS: Arch Linux
  Vim version: NVIM v0.6.0-dev+1-g62d67de59
  Has clientserver: true
  Servername: /tmp/nvim7tbIgb/0

VimTeX project: learning_journal
  base: learning_journal.tex
  root: <file path>
  tex: <file path>
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
