### ISSUE TITLE
Zathura Somehow attaches to /System/Volumes/Data/

### ISSUE THREAD

**Issue by storopoli** [lervag/vimtex#2196]
### Description

I've followed the FAQ to install zathura on MacOS. Everything works fine! From NeoVim to Zathura.

But when I do the reverse (from Zathura to NeoVim) I get the following error message:

`File not readable: "/System/Volumes/Data/home/storopoli/Desktop/temp/demo_black.tex"`

The file is in my `Desktop/temp` folder.

Zathura somehow attaches the path `/System/Volumes/Data/` to the tex file location.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info
  OS: macOS 11.6 (20G165)
  Vim version: NVIM v0.5.1
  Has clientserver: true
  Servername: /var/folders/b3/ljynthyj3ybc9hscwx_wgr440000gp/T/nvim4jLjjz/0

VimTeX project: demo_black
  base: demo_black.tex
  root: /Users/storopoli/Desktop/temp
  tex: /Users/storopoli/Desktop/temp/demo_black.tex
  main parser: current file verified
  document class: beamer
  packages: FiraMono FiraSans amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm appendixnumberbeamer atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook babel beamerbaseauxtemplates beamerbaseboxes beamerbasecolor beamerbasecompatibility beamerbasedecode beamerbasefont beamerbaseframe beamerbaseframecomponents beamerbaseframesize beamerbaselocalstructure beamerbasemisc beamerbasemodes beamerbasenavigation beamerbasenotes beamerbaseoptions beamerbaseoverlay beamerbaserequires beamerbasesection beamerbasetemplates beamerbasethemes beamerbasetheorems beamerbasetitle beamerbasetoc beamerbasetranslator beamerbasetwoscreens beamerbaseverbatim beamercolorthemedefault beamercolorthemepureminimalistic beamerfontthemedefault beamerfontthemepureminimalistic beamerinnerthemedefault beamerinnerthemepureminimalistic beamerouterthemedefault beamerouterthemepureminimalistic beamerthemedefault beamerthemepureminimalistic biblatex bigintcalc bitset blx-case-expl3 calc csquotes enumerate epstopdf-base etexcmds etoolbox expl3 fontaxes fontenc geometry gettitlestring graphics graphicx hycolor hyperref ifluatex ifpdf iftex ifthen ifvtex ifxetex infwarerr inputenc intcalc keyval kvdefinekeys kvoptions kvsetkeys letltxmacro logreq ltxcmds mweights nameref pdfescape pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfrcs pgfsys refcount rerunfilecheck sansmathaccent scrlfile scrlfile-hook scrlogo silence textcomp tikz translator trig uniquecounter url xcolor xkeyval xparse xpatch xxcolor
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    process: 
      jobid: 28
      output: /var/folders/b3/ljynthyj3ybc9hscwx_wgr440000gp/T/nvim4jLjjz/1
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -e '$new_viewer_always = "0"' -e '$pdf_previewer = "zathura  -x \"nvr --servername /var/folders/b3/ljynthyj3ybc9hscwx_wgr440000gp/T/nvim4jLjjz/0 --remote-expr \"\\\"\"vimtex#view#reverse_goto(\%{line}, '"'"'\%{input}'"'"')\"\\\"\"\" \%S"' -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'demo_black.tex'
      pid: 29385
  viewer: Zathura
    xwin id: Warning: XTEST extension unavailable on '(null)'. Some functionality may be disabled; See 'man xdotool' for more info.
    process: 
      pid: -
      cmd: zathura -x "nvr --servername /var/folders/b3/ljynthyj3ybc9hscwx_wgr440000gp/T/nvim4jLjjz/0 --remote-expr \"vimtex#view#reverse_goto(%{line}, '%{input}')\"" --synctex-forward 122:22:'/Users/storopoli/Desktop/temp/demo_black.tex'  '/Users/storopoli/Desktop/temp/demo_black.pdf' >/dev/null 2>&1 &
  qf method: LaTeX logfile
```
