### ISSUE TITLE
Is WSL + windows texlive supported?

### ISSUE THREAD

**Issue by habamax** [lervag/vimtex#2201]
### Description

I have vimtex that works fine in gVim + texlive (windows intallation).

When I try to use vimtex in WSL1 vim I have several following issues:

1. Compiler is not found due to non-explicit check for `executable('latexmk')` and if I change in the source `latexmk -> latexmk.exe` then tex files are opened without errors but
2. After I start compilation I get following error:
![image](https://user-images.githubusercontent.com/234774/136656264-363a46d4-dce5-4d24-9936-96f4c4d6cc14.png)

So does vimtex supports WSL vim + non-WSL texlive?

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info
  OS: Debian GNU/Linux 11 (bullseye)
  Vim version: VIM 8.2 (1-3487)
  Has clientserver: true
  Servername: undefined (vim started without --servername)

VimTeX project: mdm_json_msg
  base: mdm_json_msg.tex
  root: /mnt/c/Users/maksim.kim/docs/customers/c/mdm-new-src
  tex: /mnt/c/Users/maksim.kim/docs/customers/c/mdm-new-src/mdm_json_msg.tex
  main parser: current file verified
  document class: article
  packages: array babel currfile-abspath fancyhdr fontspec geometry hyperref ifthen isodate longtable mdframed minted titlesec xcolor
  compiler: latexmk
    engine: -lualatex
    options:
      -shell-escape
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    build_dir: mdm_json_msg
    callback: 1
    continuous: 1
    executable: latexmk.exe
    job: 
      jobid: process 643 run
      output: /tmp/v2Bnl7z/3
      cmd: max_print_line=2000 latexmk.exe -shell-escape -verbose -file-line-error -synctex=1 -interaction=nonstopmode -lualatex -outdir=mdm_json_msg -pvc -e '$pdf_previewer = "xdg-open"' -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'mdm_json_msg.tex'
      pid: 643
  viewer: General
  qf method: LaTeX logfile
```
