### ISSUE TITLE
Issue with window swallow when running `(vimtex-view)`

### ISSUE THREAD

**Issue by paniash** [lervag/vimtex#2203]
### Description

Previously mentioned in #1768, the recent commit (not sure specifically) made changes to the `<plug>(vimtex-view)` function which now swallows windows by default. This was not the case before. 

I am currently running vimtex from commit 45d59be8017efabd7fe0249bc3d666e71f38ef6c, which does not have this issue.

### Expected behavior

Running `<plug>(vimtex-view)` spawns a new window for the pdf viewer.

### Actual behavior

The pdf-viewer gets swallowed by the terminal when running `<plug>(vimtex-view)`.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info
  OS: Linux 5.10.70-1-lts
  Vim version: NVIM v0.6.0-dev+449-gf4359b5db
  Has clientserver: true
  Servername: /tmp/nvimT2RZgx/0

VimTeX project: main
  base: main.tex
  root: /home/ashish/documents/sixth-sem/project/bscthesis
  tex: /home/ashish/documents/sixth-sem/project/bscthesis/main.tex
  main parser: current file verified
  document class: thesis
  packages: amsmath biblatex circuitikz cleveref csquotes fontenc graphicx hyperref hyphenat inputenc microtype pgf tgschola tikz xcolor
  source files:
    main.tex
    abstract.tex
    acknowledgements.tex
    chapter1.tex
    chapter2.tex
    chapter3.tex
    chapter4.tex
    chapter5.tex
    nonlocal-with-field.pgf
    chapter6.tex
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 0
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
