### ISSUE TITLE
kpsewhich cache causes "List or Blob required" error on completion

### ISSUE THREAD

**Issue by user202729** [lervag/vimtex#2206]
### Description

Reproduce:

Put this into the kpsewhich.json cache file

```
{"inputenc.tex":"",
"ucs.sty":"/usr/share/texmf-dist/tex/latex/ucs/ucs.sty",
"geometry.tex":"",
"xparsex.cls":[["",
"/tmp"]],
"inputenc.sty":"/usr/share/texmf-dist/tex/latex/base/inputenc.sty",
"ifvtex.tex":"",
"keyval.tex":"/usr/share/texmf-dist/tex/generic/xkeyval/keyval.tex",
"hyperref.tex":"",
"geometry.sty":"/usr/share/texmf-dist/tex/latex/geometry/geometry.sty",
"iftex.tex":"",
"expl3.tex":"",
"#1.cls":"",
"ifvtex.sty":"/usr/share/texmf-dist/tex/generic/iftex/ifvtex.sty",
"hyperref.sty":"/usr/share/texmf-dist/tex/latex/hyperref/hyperref.sty",
"#1.def":"",
"iftex.sty":"/usr/share/texmf-dist/tex/generic/iftex/iftex.sty",
"amsmath.tex":"",
"kvsetkeys.tex":"",
"shellesc.sty":"/usr/share/texmf-dist/tex/latex/tools/shellesc.sty",
"pdftexcmds.tex":"",
"xparse.tex":"",
"amsmath.sty":"/usr/share/texmf-dist/tex/latex/amsmath/amsmath.sty",
"xparsex.tex":[["",
"/tmp"]],
"kvsetkeys.sty":"/usr/share/texmf-dist/tex/generic/kvsetkeys/kvsetkeys.sty",
"shellesc.tex":"",
"ucshyper.tex":"",
"atbegshi.tex":"",
"pdftexcmds.sty":"/usr/share/texmf-dist/tex/generic/pdftexcmds/pdftexcmds.sty",
"xparse.sty":"/usr/share/texmf-dist/tex/latex/l3packages/xparse/xparse.sty",
"xparsex.sty":[["",
"/tmp"]],
"ucshyper.sty":"/usr/share/texmf-dist/tex/latex/ucs/ucshyper.sty",
"atbegshi.sty":"/usr/share/texmf-dist/tex/generic/atbegshi/atbegshi.sty",
"expl3.sty":"/usr/share/texmf-dist/tex/latex/l3kernel/expl3.sty"}
```
is
Open a TeX file with this content

```
\usepackage{xparse}
\a
```

Put the cursor after the last `a` then press ctrl+N.

Error:

```
Scanning tags.
Error detected while processing function vimtex#include#expr[41]..<SNR>108_search_candidates_kpsewhich[22]..vimtex#kpsewhich#find:
line   27:
E897: List or Blob required
Press ENTER or type command to continue
```

The problem does not happen without the cache, but because VimTeX (presumably) generate that cache, it's still the plugin's bug?

### Do you use a latexmkrc file?

Yes

### VimtexInfo

```yaml
System info
  OS: Arch Linux
  Vim version: VIM 8.2 (1-2891)
  Has clientserver: true
  Servername: undefined (vim started without --servername)

VimTeX project: d
  base: d.tex
  root: /tmp
  tex: /tmp/d.tex
  main parser: current file
  document class: 
  packages: xparse
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -latexoption=--shell-escape
      -interaction=nonstopmode
    build_dir: /tmp/.vimtex_build_dir/
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
```
