### ISSUE TITLE
Incorrect syntax highlighting for \nameref

### ISSUE THREAD

**Issue by zoomiti** [lervag/vimtex#2208]
### Description

When using \nameref{something} something is not syntax highlighted white, and spell is still turned on for something. 

### Steps to reproduce

1. nvim -u minimal.vim minimal.tex

```latex
\documentclass{article}
\usepackage{hyperref}

\begin{document}

\section{Test}
\label{osc}
\autoref{osc}
\nameref{osc}
\ref{osc}
\eqref{osc}

\end{document}
```

### Expected behavior

I expect all the \ref to syntax highlight their contents white and turn spell off within them.

### Actual behavior

All but \nameref is correctly syntax highlighted.

![image](https://user-images.githubusercontent.com/34012653/137516826-fca7b23b-3a96-4997-a385-4e3c013065ab.png)

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info
  OS: Linux 5.10.16.3-microsoft-standard-WSL2
  Vim version: NVIM v0.5.1
  Has clientserver: true
  Servername: /tmp/nvim51nQtp/0

VimTeX project: test
  base: test.tex
  root: /mnt/c/Users/sotol/OneDrive/Documents/School/2021 Fall/Circuits/Lab5
  tex: /mnt/c/Users/sotol/OneDrive/Documents/School/2021 Fall/Circuits/Lab5/test.tex
  main parser: current file verified
  document class: article
  packages: atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook bigintcalc bitset etexcmds gettitlestring hycolor hyperref iftex infwarerr intcalc keyval kvdefinekeys kvoptions kvsetkeys letltxmacro ltxcmds nameref pdfescape pdftexcmds refcount rerunfilecheck uniquecounter url
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  qf method: LaTeX logfile
```
