### ISSUE TITLE
`tse` affetcs `\begin{document}`

### ISSUE THREAD

**Issue by petRUShka** [lervag/vimtex#2210]
### Description

`tse` affetcs `\begin{document}` and suddenly makes it `\begin{document*}`. If you use `tse` in wrong place it  is able to break document without noticing.

### Steps to reproduce

1. Open any latex document
2. Make `tse` outside environment.
3. Enjoy broken document

### Expected behavior

Doesn't touch `document` environment and may be some more non starrable enironments.

### Actual behavior

touch `document` environment and may be some more non starrable enironments.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info
  OS: Arch Linux
  Vim version: VIM 8.2 (1-3441)
  Has clientserver: true
  Servername: undefined (vim started without --servername)

VimTeX project: file
  base: file.tex
  root: /home/user/folder
  tex: /home/user/folder/file.tex
  main parser: current file verified
  document class: article
  packages: amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook babel bigintcalc bitset cleveref color etexcmds gettitlestring hycolor hyperref iftex infwarerr inputenc intcalc keyval kvdefinekeys kvoptions kvsetkeys letltxmacro ltxcmds nameref pdfescape pdftexcmds refcount rerunfilecheck uniquecounter url xcolor
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    build_dir: build/
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: process 381955 run
      output: /tmp/vYlfLWW/2
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -outdir=build/ -pvc -e '$new_viewer_always = "0"' -e '$pdf_previewer = "zathura  -x \"/usr/bin/vim --servername  --remote-expr \"\\\"\"vimtex#view#reverse_goto(\%{line}, '"'"'\%{input}'"'"')\"\\\"\"\" \%S"' -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'file.tex'
      pid: 381955
  viewer: Zathura
    xwin id: 69206017
    cmd_start: zathura -x "/usr/bin/vim --servername  --remote-expr \"vimtex#view#reverse_goto(%{line}, '%{input}')\"" --synctex-forward 112:27:'/home/user/folder/file.tex'  '/home/user/folder/build//file.pdf'&
  qf method: LaTeX logfile
```
```
