### ISSUE TITLE
packages

### ISSUE THREAD

**Issue by tjallemaal** [lervag/vimtex#2211]
### Description

Hi, currently trying to switch from `Texstudio` to ``Nvim`/Vimtex.` 

`Where do I add packages` so vimtex/latex can find them?

I succeeded compiling a minimal example via skim, but I have some older tex files which make use of linguistics packages and alike. I believe those manually added packages reside within the Texstudio directory and Vimtex may not be able to reach them...

Long story short: How do i find out where Vimtex has its `latex packages`, so I can go there and add stuff?

I'm a complete noob, please excuse my naive question and the helpless phrasing of the issue :)
also, if there is a written documentation on this to work through I would be grateful ...

cheers

### Do you use a latexmkrc file?

no, at least not in that place

### VimtexInfo

```yaml
System info
  OS: Mac OS X 10.15.7 (19H1419)
  Vim version: NVIM v0.5.1
  Has clientserver: true
  Servername: /var/folders/r7/yckgcqts7gvfy6p5x0yfyzb00000gn/T/nvimzBHCPA/0

VimTeX project: test
  base: test.tex
  root: /Users/halemjankirgil
  tex: /Users/halemjankirgil/test.tex
  main parser: current file verified
  document class: minimal
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    engine: -pdf
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Skim
  qf method: LaTeX logfile
```
