### ISSUE TITLE
Wrong View method when set in ftplugin or after/ftplugin

### ISSUE THREAD

**Issue by LoeschMaximilian** [lervag/vimtex#2218]
### Description

I'm trying to keep my init.vim as small and modular as possible.

But trying to move this Plugin setting to ftplugin does not use my view_method (zathura). Instead it opens Firefox, which is set in mime to open pdfs.

I use latexmk and set there zathura as previewer as-well.
When queried nvim reports g:vimtex_view_method to be correctly set.

### Do you use a latexmkrc file?

yes

### VimtexInfo

```yaml
System info
  OS: Linux 5.14.12-zen1-1-zen
  Vim version: NVIM v0.6.0-dev+463-g68b2a9e56
  Has clientserver: true
  Servername: /tmp/nvimEIhkAF/0

VimTeX project: bewerbung
  base: bewerbung.tex
  root: /home/max/Projekte/Bewerbung
  tex: /home/max/Projekte/Bewerbung/bewerbung.tex
  main parser: current file verified
  document class: scrlttr2
  packages: amsmath babel graphics hyperref inputenc
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
