### ISSUE TITLE
VimTeX: Compiler did not start successfully on Windows Powershel

### ISSUE THREAD

**Issue by jeofo** [lervag/vimtex#2220]
### Description

I installed MiKTeX for windows and confirmed that `latexmk` works without a problem. However when I run `\ll` in nvim, this is the error output I get. I assume it has something to do with Powershell. Any help is appreciated!

`latexmkrc` has one line setting the engine to `pdflatex`.

```
At line:1 char:185
+ ... f_previewer = 'start'" -e "$compiling_cmd = ($compiling_cmd ? $compil ...
+                                                                 ~
Unexpected token '?' in expression or statement.
At line:1 char:184
+ ... pdf_previewer = 'start'" -e "$compiling_cmd = ($compiling_cmd ? $comp ...
+                                                                  ~
Missing closing ')' in expression.
At line:1 char:215
+ ... mpiling_cmd = ($compiling_cmd ? $compiling_cmd . ' ^& ' : '') . 'echo ...
+                                                                 ~
Unexpected token ')' in expression or statement.
At line:1 char:295
+ ... piler_callback_compiling'" -e "$success_cmd = ($success_cmd ? $succes ...
+                                                                 ~
Unexpected token '?' in expression or statement.
At line:1 char:294
+ ... ompiler_callback_compiling'" -e "$success_cmd = ($success_cmd ? $succ ...
+                                                                  ~
Missing closing ')' in expression.
At line:1 char:323
+ ... e "$success_cmd = ($success_cmd ? $success_cmd . ' ^& ' : '') . 'echo ...
+                                                                 ~
Unexpected token ')' in expression or statement.
At line:1 char:401
+ ... ompiler_callback_success'" -e "$failure_cmd = ($failure_cmd ? $failur ...
+                                                                 ~
Unexpected token '?' in expression or statement.
At line:1 char:400
+ ... _compiler_callback_success'" -e "$failure_cmd = ($failure_cmd ? $fail ...
+                                                                  ~
Missing closing ')' in expression.
At line:1 char:429
+ ... e "$failure_cmd = ($failure_cmd ? $failure_cmd . ' ^& ' : '') . 'echo ...
+                                                                 ~
Unexpected token ')' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken
 
At line:1 char:185
+ ... f_previewer = 'start'" -e "$compiling_cmd = ($compiling_cmd ? $compil ...
+                                                                 ~
Unexpected token '?' in expression or statement.
At line:1 char:184
+ ... pdf_previewer = 'start'" -e "$compiling_cmd = ($compiling_cmd ? $comp ...
+                                                                  ~
Missing closing ')' in expression.
At line:1 char:215
+ ... mpiling_cmd = ($compiling_cmd ? $compiling_cmd . ' ^& ' : '') . 'echo ...
+                                                                 ~
Unexpected token ')' in expression or statement.
At line:1 char:295
+ ... piler_callback_compiling'" -e "$success_cmd = ($success_cmd ? $succes ...
+                                                                 ~
Unexpected token '?' in expression or statement.
At line:1 char:294
+ ... ompiler_callback_compiling'" -e "$success_cmd = ($success_cmd ? $succ ...
+                                                                  ~
Missing closing ')' in expression.
At line:1 char:323
+ ... e "$success_cmd = ($success_cmd ? $success_cmd . ' ^& ' : '') . 'echo ...
+                                                                 ~
Unexpected token ')' in expression or statement.
At line:1 char:401
+ ... ompiler_callback_success'" -e "$failure_cmd = ($failure_cmd ? $failur ...
+                                                                 ~
Unexpected token '?' in expression or statement.
At line:1 char:400
+ ... _compiler_callback_success'" -e "$failure_cmd = ($failure_cmd ? $fail ...
+                                                                  ~
Missing closing ')' in expression.
At line:1 char:429
+ ... e "$failure_cmd = ($failure_cmd ? $failure_cmd . ' ^& ' : '') . 'echo ...
+                                                                 ~
Unexpected token ')' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken
 
```

### Do you use a latexmkrc file?

yes

### VimtexInfo

```yaml
System info
  OS: JEFFERON-DING
 (Microsoft Windows 11 Pro
)
  Vim version: NVIM v0.5.1
  Has clientserver: true
  Servername: \\.\pipe\nvim-9716-0

VimTeX project: main
  base: main.tex
  root: C:\Users\tydin\Downloads\Rocket Lab Report
  tex: C:\Users\tydin\Downloads\Rocket Lab Report\main.tex
  main parser: current file verified
  document class: article
  packages: amsbsy amsgen amsmath amsopn amstext array babel caption caption3 epstopdf-base float gensymb geometry graphics graphicx iftex ifvtex keyval multicol multirow pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfplots pgfplotstable pgfrcs pgfsys subcaption tikz trig xcolor
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 4
      output: C:\Users\tydin\AppData\Local\Temp\nvimieK7vf\1
      cmd: set max_print_line=2000 & latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -e "$pdf_previewer = 'start'" -e "$compiling_cmd = ($compiling_cmd ? $compiling_cmd . ' ^& ' : '') . 'echo vimtex_compiler_callback_compiling'" -e "$success_cmd = ($success_cmd ? $success_cmd . ' ^& ' : '') . 'echo vimtex_compiler_callback_success'" -e "$failure_cmd = ($failure_cmd ? $failure_cmd . ' ^& ' : '') . 'echo vimtex_compiler_callback_failure'" "main.tex"
      pid: 0
  viewer: General
  qf method: LaTeX logfile
```
