### ISSUE TITLE
Error when repeatedly toggle compiler start/stop status

### ISSUE THREAD

**Issue by user202729** [lervag/vimtex#2222]
### Description

When I repeatedly press `\ll` , occasionally I get

```
Error detected while processing function vimtex#compiler#compile[2]..vimtex#compiler#stop:
line   11:
E121: Undefined variable: b:vimtex
E116: Invalid arguments for function vimtex#log#info
```

### Steps to reproduce

1. Create some TeX file (the exact content doesn't really matter)

```latex
%! TEX program = lualatex
\documentclass[12pt]{article}
\begin{document}
line 1
\end{document}
```

2. Repeatedly press `\ll`. 

Probably some race condition (recently with synctex enabled sometimes zathura takes a few seconds to open (and use some CPU). I don't know if it's relevant to the issue)

### Expected behavior

No error, and the compiler stops normally.

### Actual behavior

The error message mentioned above is displayed, then the log is displayed in a separate pane (the standard "compile successful" log, something like this

```
Rc files read:
  NONE
Latexmk: This is Latexmk, John Collins, 29 September 2020, version: 4.70b.
Viewing pdf

...

Latexmk: All targets (*.pdf) are up-to-date
vimtex_compiler_callback_success
```

### Do you use a latexmkrc file?

Yes

### VimtexInfo

```yaml
System info
  OS: Arch Linux
  Vim version: VIM 8.2 (1-2891)
  Has clientserver: true
  Servername: vim

VimTeX project: a
  base: a.tex
  root: /tmp
  tex: /tmp/a.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -lualatex
    options:
      -verbose
      -file-line-error
      -synctex=1
      -latexoption=--shell-escape
      -interaction=nonstopmode
    build_dir: /tmp/.vimtex_build_dir/
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: process 10573 dead
      output: /tmp/vZE0Wdx/1
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -latexoption=--shell-escape -interaction=nonstopmode -lualatex -outdir=/tmp/.vimtex_build_dir/ -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'a.tex'
      pid: 10573
  viewer: Zathura
    xwin id: 46137347
  qf method: LaTeX logfile
```
