### ISSUE TITLE
Auto ending of begin work with altgr+8 altgr+8, but it does not work for map

### ISSUE THREAD

**Issue by Mauhing** [lervag/vimtex#2223]
### Description

Vimtex provides auto ending feature such that it can automatically close an environment by typing `]]` in the insert mode, like this `end{enviroment}` of a `\begin{enviroment}`. It works well.

However, I have a norwegain keyboard, I need to `Altgr`+`99` to type `]]`.
so, I set `imap å ]`. I typed `åå`, but it only show `]]` and vimtex does not close the environment.

How can I use `åå` just like `Altgr` + `99` such that vimtex works? Thanks

### Do you use a latexmkrc file?

NO

### VimtexInfo

```yaml
System info
  OS: Pop!_OS 20.04 LTS
  Vim version: VIM 8.1 (1-2269)
  Has clientserver: false

VimTeX project: elegantbook-en
  base: elegantbook-en.tex
  root: /home/mhyip/Insync/mauhingyip@gmail.com/Google Drive/05_Latex/sensor_fusion
  tex: /home/mhyip/Insync/mauhingyip@gmail.com/Google Drive/05_Latex/sensor_fusion/elegantbook-en.tex
  main parser: recursive search
  document class: elegantbook
  packages: accents adforn amsbsy amsfonts amsgen amsmath amsopn amssymb amstext anyfontsize appendix apptools array atbegshi atveryend auxhook bbding biblatex bigintcalc bitset blindtext bm booktabs caption caption3 colortbl comment csquotes enumerate enumitem environ epstopdf-base etexcmds etoolbox everyshi expl3 fancyhdr fancyvrb fontaxes fontenc footmisc geometry gettitlestring graphics graphicx hologo hycolor hyperref iftex ifthen ifvtex indentfirst infwarerr intcalc keyval kvdefinekeys kvoptions kvsetkeys letltxmacro lipsum listings logreq lstlang1 lstlang2 lstlang3 lstmisc ltxcmds makecell manfnt mathbbol mathrsfs multicol multirow mwe nameref newtxtext pdfescape pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfrcs pgfsys pifont refcount rerunfilecheck setspace tcolorbox textcomp tikz titleps titlesec trig trimspaces uniquecounter url verbatim xcolor xkeyval xparse xspace
  source files:
    elegantbook-en.tex
    tex_files/prerequisite.tex
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
