### ISSUE TITLE
"Something went wrong when parsing log files!" during quickly repeated single shot compilations

### ISSUE THREAD

**Issue by ji-cerny** [lervag/vimtex#2225]
### Description

I have a relatively long LaTeX document which needs ~4s for a single compilation, more when more passes are required. I have a key mapped to VimtexCompileSS and it happens that I start a new compilation while an old one is still running.  Then, occasionally, the following error message appears: 
```
VimTeX: Something went wrong when parsing log files!
Error detected while processing function airline#extensions#vimtex#get_scope[20]..311[1]..<SNR>97_callback[1]..vim
tex#compiler#callback[54]..vimtex#qf#open[19]..function airline#extensions#vimtex#get_scope[20]..311[1]..<SNR>97_c
allback[1]..vimtex#compiler#callback[54]..vimtex#qf#open:
line   16:
E565: Not allowed to change text or change window:       cclose
Press ENTER or type command to continue
```

I do not know if it is vim-airline or vimtex problem, I ask here first, since the `cclose` command is in `vimtex/qf.vim`. 

I am ready to do some testing/small coding, but a hint where to start would be welcomed.   

### Steps to reproduce

It is not completely easy to reproduce, it seems to happen by long Latex files only. 

### Do you use a latexmkrc file?

It is not latexmk specific. Infact it happens with latexrun and latexmk.

### VimtexInfo

```yaml
System info
  OS: Fedora release 35 (Thirty Five)
  Vim version: VIM 8.2 (1-3404)
  Has clientserver: true
  Servername: VIM

VimTeX project: foo
  base: foo.tex
  root: /home/cerny/foo/
  tex: /home/cerny/foo/foo.tex
  main parser: current file verified
  document class: scrbook
  packages: alltt amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm array atbegshi atbegshi-ltx atverye
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: process 910791 dead
      output: /tmp/vvk9LKb/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf 'EiS.tex
      pid: 910791
  viewer: General
  qf method: LaTeX logfile
```
