### ISSUE TITLE
(N)vim freezing after :VimtexView with Zathura

### ISSUE THREAD

**Issue by Djoop** [lervag/vimtex#2231]
### Description

After running :VimtexView, the viewer opens the file to visualize (as expected), but the vim interface is not responsive at all (until the pdf viewer is closed). I have not tried with vim so I cannot say if it is specific to nvim or not. The problem seems to disappear if I don't explicitly set g:vimtex_view_method in the configuration (although zathura is my default pdf viewer, i.e. in this case zathura will open but the interface will not freeze).

### Steps to reproduce

# Minimal init.vim

```
call plug#begin()
Plug 'lervag/vimtex'
call plug#end()
let g:vimtex_view_method = "zathura" 
```

# minimal.tex

```
\documentclass[]{article}
\begin{document}
Test
\end{document}
```

# Steps
1. nvim minimal.tex
2. :VimtexCompile
3. close the pdf viewer and re-open it with :VimtexView

### Expected behavior

nvim should not freeze

### Actual behavior

The interface does not respond anymore (until I close the pdf viewer)

### Do you use a latexmkrc file?

Yes (but not relevant)

### VimtexInfo

```yaml
System info
  OS: Linux 5.14.14-arch1-1
  Vim version: NVIM v0.5.1
  Has clientserver: true
  Servername: /tmp/nvimrJBIUE/0

VimTeX project: main
  base: main.tex
  root: /home/XXX
  tex: /home/XXX/main.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
