### ISSUE TITLE
What is the command or shortcut for folding a section 

### ISSUE THREAD

**Issue by ihsanCurse** [lervag/vimtex#2232]
### Description

I want to fold a section after it has been opened 

### Steps to reproduce

1. nvim -u minimal.vim minimal.tex
2. section are closed
3. open section with `space` 
4. close section ???

```
cat minimal.vim minimal.tex
set nocompatible
let &runtimepath  = stdpath('data') .'/plugged/vimtex,' . &runtimepath
let &runtimepath .= stdpath('data') .'/plugged/vimtex/after'

filetype plugin indent on
let g:vimtex_view_method = "zathura"
let g:vimtex_fold_enabled = 1
let g:vimtex_fold_bib_enabled = 0

nmap <localleader>rf :VimtexRefreshFolds<CR>

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass{article}
\begin{document}

\section{First }
Hello world!
\section{Second }
Hello world!
\end{document}
```

### Expected behavior

There is function that closes the section again 

### Actual behavior
No explanation how to fold back in 
Why is there reference to `:VimtexRefreshFolds` when the function does not exist

```
E492: Not an editor command: VimtexRefreshFolds
```

### Do you use a latexmkrc file?

no 

### VimtexInfo

```yaml
System info
  OS: Arch Linux
  Vim version: NVIM v0.5.1
  Has clientserver: true
  Servername: /tmp/nvimuJtH1F/0

VimTeX project: minimal
  base: minimal.tex
  root: /home/user/Downloads/testLatex
  tex: /home/user/Downloads/testLatex/minimal.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
~
```
