### ISSUE TITLE
Add missing texMathCmdSI

### ISSUE THREAD

**Issue by QUICKguils** [lervag/vimtex#2245]
### Description

Really minor issue here, but I've noticed that commands \qty, \unit and \qtyrange (from siunitx package) were not properly highlighted in math environment. I think somebody forgot to add
```vim
  syntax match texMathCmdSI contained nextgroup=texSIOptU,texSIArgUnit skipwhite "\\unit\>"
  syntax match texMathCmdSI contained nextgroup=texSIOptNU,texSIArgNumU skipwhite "\\qty\>"
  syntax match texMathCmdSI contained nextgroup=texSIOptNNU,texSIArgNumNU skipwhite "\\qtyrange\>"
```
in `autoload/vimtex/syntax/p/siunitx.vim`.

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
System info
  OS: Fedora release 35 (Thirty Five)
  Vim version: NVIM v0.5.1
  Has clientserver: true
  Servername: /tmp/nvimZ5NA0N/0

VimTeX project: main
  base: main.tex
  root: /home/guil/Documents/Essais/Latex/Report_small
  tex: /home/guil/Documents/Essais/Latex/Report_small/main.tex
  main parser: recursive search
  document class: article
  packages: babel bm booktabs calc csquotes fancyhdr floatrow geometry graphicx hyperref inputenc lastpage lettrine lipsum listings matlab-prettifier microtype newtxmath pgfplots placeins ragged2e roboto roboto-mono sectsty siunitx stickstootext subfig tabularx tikz tikzscale tocvsec2 varioref xcolor
  source files:
    main.tex
    preambule.tex
    titlepage.tex
    dser.tex
    img/srl-turb.tex
    graph/MNT-turb.tex
    graph/MNT-alt.tex
    img/srl-alt.tex
    graph/dser.tex
    fatigue.tex
    graph/stress-max.tex
    vibratoire.tex
    annexes.tex
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 0
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
