### ISSUE TITLE
`.aux` files are broken

### ISSUE THREAD

**Issue by KermanGreem** [lervag/vimtex#2250]
### Description

For some reason, the aux files for all my latex projects are apparently broken (although I didn't change anything), since I'm 
getting the error 
```
latexfile/latexfile.aux|1 error| Text line contains an invalid character. ...@^^@^^@^^@^^@^^@^^@^^@^^@^^@^^@^^@^^@^^@^^@
```
and this multiple times in a row.
When compiling everything in vscode, it seems to work fine however. I really don't know which issue is causing this weird behaviour.

### Do you use a latexmkrc file?

yes

### VimtexInfo

```yaml
System info
  OS: macOS 11.2.2 (20D80)
  Vim version: VIM 8.2 (1-2681)
  Has clientserver: true
  Servername: undefined (vim started without --servername)

VimTeX project: latexfile
  base: latexfile
  root: /Users/me/Documents/latexfile
  tex: /Users/me/Documents/latexfile
  main parser: current file verified
  document class: article
  packages: algorithm algorithmicx algpseudocode amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm array atbegshi atveryend auxhook bigintcalc bitset booktabs calc commath enumitem eso-pic etexcmds everyshi expl3 float geometry gettitlestring graphics graphicx hycolor hyperref ifmtarg iftex ifthen ifvtex import infwarerr intcalc karnaugh-map keyval kvdefinekeys kvoptions kvsetkeys l3keys2e letltxmacro lscape ltxcmds mathtools mhsetup nameref numprint pdfescape pdflscape pdfpages pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfrcs pgfsys refcount rerunfilecheck setspace siunitx stringenc systeme tikz translator trig uniquecounter url xcolor xifthen xparse xstring
  compiler: latexmk
    engine: -xelatex
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    process: 
      jobid: process 11413 run
      output: /var/folders/6n/m87834dd08gckw2538s2k7qc0000gn/T/vShGISX/1
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -xelatex -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'randomaf.tex'
      pid: 11413
  viewer: General
  qf method: LaTeX logfile
```
