### ISSUE TITLE
Slow editing

### ISSUE THREAD

**Issue by jokasimr** [lervag/vimtex#2252]
### Description

I have a quite basic setup using nvim and vimtex.
Still, editing small documents containing equations makes the editor slow on a relatively new laptop.

### Steps to reproduce

`minimal.vim`
```vim
call plug#begin(stdpath('data') . '/plugged')

Plug 'lervag/vimtex'

call plug#end()

let maplocalleader = ","

let g:vimtex_view_method = 'zathura'
let g:vimtex_compiler_method = 'latexmk'
let g:vimtex_quickfix_mode=0
let g:tex_flavor='latex'
let g:tex_conceal='abdmg'
```

`minimal.tex`
```latex
\documentclass[12pt,a4paper]{report}
\usepackage{amssymb}
\usepackage{amsthm}
\usepackage{amsmath}

\begin{document}

\begin{align}
\label{itgs}
(\mathbf{A}_{\Gamma \Gamma}^{(2)} - \mathbf{A}_{\Gamma I}^{(2)} \mathbf{A}_{II}^{(2)-1} \mathbf{A}_{I\Gamma}^{(2)}) \mathbf{u}_\Gamma^{k+1} = \\
\nonumber
 (\mathbf{A}_{\Gamma I}^{(1)}\mathbf{A}_{II}^{(1)-1}\mathbf{A}_{I\Gamma}^{(1)} - \mathbf{A}_{\Gamma \Gamma}^{(1)}) \mathbf{u}_\Gamma^{k} + \mathbf{f}_\Gamma - \mathbf{A}_{\Gamma I}^{(1)}\mathbf{A}_{II}^{(1)-1} \mathbf{f}^{(1)}_I  - \mathbf{A}_{\Gamma I}^{(2)} \mathbf{A}_{II}^{(2)-1}\mathbf{f}^{(2)}_I
\end{align}
\begin{align}
(\mathbf{A}_{\Gamma \Gamma}^{(2)} - \mathbf{A}_{\Gamma I}^{(2)} \mathbf{A}_{II}^{(2)-1} \mathbf{A}_{I\Gamma}^{(2)}) \mathbf{u}_\Gamma^{k+1} = \\
\nonumber
(\mathbf{A}_{\Gamma I}^{(1)}\mathbf{A}_{II}^{(1)-1}\mathbf{A}_{I\Gamma}^{(1)} - \mathbf{A}_{\Gamma \Gamma}^{(1)}) \mathbf{u}_\Gamma^{k-1} + \mathbf{f}_\Gamma - \mathbf{A}_{\Gamma I}^{(1)}\mathbf{A}_{II}^{(1)-1} \mathbf{f}^{(1)}_I  - \mathbf{A}_{\Gamma I}^{(2)} \mathbf{A}_{II}^{(2)-1}\mathbf{f}^{(2)}_I.
\end{align}
	
\end{document}
```

Steps to reproduce:
1. Run `nvim minimal.tex`
2. Move down to the line containing `\begin{document}`
3. Try to move sideways using `h` and `l`

### Expected behavior

When doing the steps described above I expect the editor cursor to smoothly move left and right.

### Actual behavior

The cursor lags a lot.

Below is a printout from profiling using
:profile start profile.log
:profile func *
:profile file *
" At this point do slow actions
:profile pause
:noautocmd qall

[profile.log](https://github.com/lervag/vimtex/files/7562991/profile.log)
!

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info
  OS: Ubuntu 20.04.3 LTS
  Vim version: NVIM v0.4.3
  Has clientserver: true
  Servername: /tmp/nvim0ayo8n/0

VimTeX project: minimal
  base: minimal.tex
  root: /home/johkas/crap
  tex: /home/johkas/crap/minimal.tex
  main parser: current file verified   
  document class: report
  packages: amsmath amssymb amsthm
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
