### ISSUE TITLE
Synctex Error : can't sync from pdf to tex

### ISSUE THREAD

**Issue by flaviusbuffon** [lervag/vimtex#2253]
### Description

vim tex config
```
function config.vimtex()
    vim.cmd [[let g:tex_flavor = "latex"]]
    vim.cmd [[let g:vimtex_quickfix_open_on_warning = 0]]
    vim.cmd [[let g:vimtex_compiler_progname = 'nvr']]
    vim.cmd [[let g:vimtex_view_automatic = 1]]
    vim.cmd [[let g:latex_view_general_viewer = 'zathura']]
    vim.cmd [[let g:vimtex_view_method = 'zathura']]
end
```

### Steps to reproduce

`nvim main.tex`
`\ll`

### Expected behavior

sync from pdf to tex file.

### Actual behavior

can't sync, just sync from tex to pdf

### Do you use a latexmkrc file?

Yes

### VimtexInfo

```yaml
System info
  OS: Arch Linux
  Vim version: NVIM v0.6.0-dev+515-gd918759dee
  Has clientserver: true
  Servername: /tmp/nvimmYCTr4/0

VimTeX project: formulation
  base: formulation.tex
  root: /home/jczhang/a
  tex: /home/jczhang/a/formulation.tex
  main parser: current file verified
  document class: article
  packages: amsbsy amsfonts amsgen amsmath amsopn amstext booktabs color float geometry graphics graphicx iftex ifvtex keyval listings lstlang1 lstmisc mathrsfs pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfplots pgfrcs pgfsys tikz trig xcolor
  compiler: latexmk
    engine: -xelatex
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 10
      output: /tmp/nvimmYCTr4/1
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -xelatex -pvc -e '$new_viewer_always = "0"' -e '$pdf_previewer = "zathura  -x \"/usr/bin/nvim --headless -c \"\\\"\"VimtexInverseSearch \%{line} '"'"'\%{input}'"'"'\"\\\"\"\" \%S"' -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'formulation.tex'
      pid: 7958
  viewer: Zathura
    xwin id: 39845891
  qf method: LaTeX logfile
```
