### ISSUE TITLE
Wrong conceal distance for mathcal and mathbbm.

### ISSUE THREAD

**Issue by PhyX-Meow** [lervag/vimtex#2254]
### Description

![image](https://user-images.githubusercontent.com/17513581/142723869-b834a39a-3051-4f7b-ad23-f51c1d717b1b.png)
![image](https://user-images.githubusercontent.com/17513581/142723973-8a725eb5-cb37-425d-b97f-d5128b8ec398.png)
![image](https://user-images.githubusercontent.com/17513581/142723985-4051d413-4b7f-4d93-b7c5-8a52b62a6c5e.png)

minimal.vim:
```
set nocompatible
let &runtimepath  = '~/.vim/plugged/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/plugged/vimtex/after'
let g:tex_conceal = 'abdmg'
set conceallevel=2
filetype plugin indent on
syntax enable
```

minimal.tex:
```
\documentclass{minimal}
\begin{document}
We prove \(V\mathcal{T}_w\) is not.
We prove \(V\mathcal{T}_w\) is not.
\end{document}
```

### Steps to reproduce

1. `vim -u minimal.vim minimal.tex`.
2. Wrtie `\mathcal{T}` or someing similar in mathmode.
3. Move cursor to other lines and see conceal effect.

### Expected behavior

Right conceal.

### Actual behavior

Extra char after the concealed letter. Guess reason to be may be wrong conceal distance, since `\mathbb` looks well and `\mathbbm` is one char longer in length.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info
  OS: Arch Linux
  Vim version: VIM 8.2 (1-3582)
  Has clientserver: true
  Servername: VIM

VimTeX project: mimimal
  base: mimimal.tex
  root: /home/wuli
  tex: /home/wuli/mimimal.tex
  main parser: current file verified
  document class: minimal
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile

```
```
