### ISSUE TITLE
zathura backward search not working

### ISSUE THREAD

**Issue by hbenevides** [lervag/vimtex#2255]
### Description

after updating vimtex plugin, the backward search in Zathura stopped working. Forward search works fine though.

### Steps to reproduce

1. `nvim minmal.vim minimal.tex`
2. compile
3. use `ctrl + mouse left button` in any text on the pdf

**minimal.vim**

```vim
call plug#begin('~/.config/nvim/plugged')
     Plug 'lervag/vimtex', {'for': 'tex'}
call plug#end()
```

**minmal.tex**

```tex
\documentclass{minimal}
\begin{document}
Hello world!
\end{document}
```

### Expected behavior

I expect the cursor jumping to the corresponding line on the source code in nvim

### Actual behavior

Nothing happens when using zathura's `ctrl + mouse clicking` shortcut for backward search

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info
  OS: Linux 5.15.3-arch1-1
  Vim version: NVIM v0.5.1
  Has clientserver: true
  Servername: /tmp/nvim4mIfnF/0

VimTeX project: minimal
  base: minimal.tex
  root: /home/benevides
  tex: /home/benevides/minimal.tex
  main parser: current file verified
  document class: minimal
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 7
      output: /tmp/nvim4mIfnF/1
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -e '$pdf_previewer = "xdg-open"' -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'minimal.tex'
      pid: 82621
  viewer: General
  qf method: LaTeX logfile
```
