### ISSUE TITLE
Compiler not starting successfully in VimTex on Windows

### ISSUE THREAD

**Issue by naths84** [lervag/vimtex#2258]
### Description

Getting the following output when trying to compile in gVim using vimtex.

```
panic: no console

goroutine 1 [running]:
modernc.org/libc.newFile(0x0, 0xc000000000, 0xc0000e2000)
    D:/a/cli/cli/vendor/modernc.org/libc/libc_windows.go:227 +0x185
modernc.org/libc.init()
    D:/a/cli/cli/vendor/modernc.org/libc/libc.go:53 +0x22a5
```

The latex file is the most basic template:

```tex
\documentclass{article}
\begin{document}
This is a test.
\end{document}
```

saved under `test.tex`

Here is the `.vimrc`.

```vim
set encoding=utf-8   

call plug#begin()
" On-demand loading
Plug 'lervag/vimtex'
call plug#end()

filetype plugin indent on
syntax enable
let g:tex_flavor='latex'
```

For information: vimtex is installed (syntax does highlight), Latex is installed and the file compiles when I type

```sh
pdflatex .\test.tex
```

in the PowerShell.

Thank you!

### Steps to reproduce

As described above.

### Expected behavior

Compiler starts.

### Actual behavior

Compiler is not starting successfully.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info
  OS: DESKTOP-26E83P7 (Microsoft Windows 10 Professionnel)
  Vim version: VIM 8.2 (1-2825)
  Has clientserver: true
  Servername: GVIM

VimTeX project: test
  base: test.tex
  root: C:\Users\Nathan\Documents\ens_latex
  tex: C:\Users\Nathan\Documents\ens_latex\test.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: process 11468 dead
      output: C:\Users\Nathan\AppData\Local\Temp\V992603.tmp
      cmd: set max_print_line=2000 & latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -e "$pdf_previewer = 'SumatraPDF -reuse-instance'" -e "$compiling_cmd = ($compiling_cmd ? $compiling_cmd . ' & ' : '') . 'echo vimtex_compiler_callback_compiling'" -e "$success_cmd = ($success_cmd ? $success_cmd . ' & ' : '') . 'echo vimtex_compiler_callback_success'" -e "$failure_cmd = ($failure_cmd ? $failure_cmd . ' & ' : '') . 'echo vimtex_compiler_callback_failure'" "test.tex"
      pid: 11468
  viewer: General
  qf method: LaTeX logfile
```
