### ISSUE TITLE
In neovim, vimtex compiler not compiling (latexmk not being recognized and initialized)

### ISSUE THREAD

**Issue by olliequ** [lervag/vimtex#2260]
### Description

Using MacOS. I've installed MacTeX and made sure latexmk is there. Typing `latexmk -v` returns correctly in the shell. Here's a picture of what happens when I try to compile a .tex document in neovim: https://imgur.com/a/5QnGWbJ

It's clear that latexmk isn't being recognized, or something. Here's my vimtex settings in `init.vim`: 
```
syntax enable
let g:tex_flavor='latex'
let g:vimtex_view_method='skim'
let g:vimtex_quickfix_mode=0
```

I've clearly tried setting the compiler to latexmk (even though it should be this by default as per the documentation). Of course, I've installed the plug-in vimtex using `Plug 'lervag/vimtex'`.

I've uninstalled vimtex and reinstalled it (I use `vim-plug`) and it *still* has the same error!

The `.tex` file I've been trying is the test one from the repo.

### Expected behavior

The .tex file to compile.

### Actual behavior

Compilation error.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info
  OS: Mac OS X 10.14.6 (18G6020)
  Vim version: NVIM v0.5.1
  Has clientserver: true
  Servername: /var/folders/r9/4hrwhqb95tl06ygytjjfwcwh0000gn/T/nvimjW9NZy/0

VimTeX project: test
  base: test.tex
  root: /Users/Ollie
  tex: /Users/Ollie/test.tex
  main parser: current file verified
  document class: article
  packages: amsmath
  viewer: Skim
  qf method: LaTeX logfile
```
