### ISSUE TITLE
Unable to have two seperate neovim instances open zathura

### ISSUE THREAD

**Issue by ss7m** [lervag/vimtex#2265]
### Description

If I open a tex file in neovim and start compiling with `\lv`, zathura opens as expected (and forwards/backwards search both work as expected). However, if in a second terminal I open a different tex file and try and start compiling with `\lv`, no zathura window is opened. (I still get the "VimTeX: Compilation completed" message.)

### Steps to reproduce

foo.tex and bar.tex both contain:
```tex
\documentclass{article}

\begin{document}
Hello, World!
\end{document}
```

minimal.vim contains:
```vim
call plug#begin()
Plug 'lervag/vimtex'
call plug#end()

let g:vimtex_view_method='zathura'
```

Then, run `nvim -u minimal.vim foo.tex`, and start compiling with `\lv`.
Next, in a second terminal, run `nvim -u minimal.vim bar.tex` and start compiling with `\lv`.

### Expected behavior

Both neovim instances have their pdf document opened in zathura by vimtex. 

### Actual behavior

Only the neovim instance with foo.tex had its pdf document opened in zathura.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info
  OS: Linux 5.15.5-arch1-1
  Vim version: NVIM v0.6.0
  Has clientserver: true
  Servername: /tmp/nvimYuOoKM/0

VimTeX project: x
  base: x.tex
  root: /home/sam/Documents/bar
  tex: /home/sam/Documents/bar/x.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 81788931
  qf method: LaTeX logfile
```
