### ISSUE TITLE
Vlty Compiler Error - Illegal variable name l:list

### ISSUE THREAD

**Issue by nela** [lervag/vimtex#2268]
### Description

**Issue**

I am trying to setup a vlty for grammar checking. However, whenever starting the vlty compiler I get the following error on [this line of code](https://github.com/lervag/vimtex/blob/1f0c205b961e4cf7770237e3e5cae7ceabacecbb/compiler/vlty.vim#L92):

```
Error detected while processing .../vimtex/compiler/vlty.vim:
line 92
```

Running `:compiler vlty`, gives following output:

```
E461: Illegal variable name: l:list
```

**Setup**

I have tried editing and trouble shooting `g:the vimtex_grammar_vlty` command, with no luck. My vimtex config:

```vim
set colorcolumn=100
set textwidth=99
set spell spelllang=en_gb
" set foldmethod=syntax
set fillchars=fold:\

" Format paragraph (selected or not)
nnoremap <leader>gp gqap
xnoremap <leader>gp gqa

let g:vimtex_complete_recursive_bib=1
let g:vimtex_fold_enabled=1

let g:tex_flavor = 'latex'

function! Callback(msg)
  let l:m = matchlist(a:msg, '\vRun number (\d+) of rule ''(.*)''')
  if !empty(l:m)
    echomsg l:m[2] . ' (' . l:m[1] . ')'
  endif
endfunction

let g:vimtex_compiler_latexmk = {
      \ 'callback' : 1,
      \ 'continuous' : 1,
      \ 'executable' : 'latexmk',
      \ 'hooks' : [function('Callback')]
      \ }

let g:vimtex_view_method = 'skim'
let g:vimtex_view_skim_activate = 1
let g:vimtex_view_skim_reading_bar = 1

let g:vimtex_grammar_vlty = {
      \ 'lt_command': 'languagetool',
      \ 'show_suggestions' : 1,
      \ 'server': 'my',
      \ 'shell_options':
          \  ' --packages "*"'
          \ . ' --add-modules /Users/nela/skole/master/thesis/main.tex'
          \ . ' --define /Users/nela/skole/master/thesis/aux/commands.tex'
          \ . ' --equation-punctuation display'
          \ . ' --single-letters "I.\,A.\|a.\,B.\|\|"'
          \ }

map <F9> :w <bar> compiler vlty <bar> make <bar> :cw <cr><esc>
```

**Versions** 
- `vim: NVIM v0.6.0`
- `languagetool: 5.5`
- `yalafi: 1.3.0`

### Steps to reproduce

1. Install neovim, vimtex, languagetool, yalafi.
2. Copy the config from above, place in `ftplugin/`
3. Open a `.tex`document, `minimal.tex`for example
4. Press `F9`

**minimal.tex**
```latex
\documentclass{minimal}
\begin{document}
Hello world!
\end{document}
```

### Expected behavior

When following the steps above, I expect to start the languagetool as a running server, along with yalafi, to continuously filter and process text.

### Actual behavior

Languagetool http server crashes. No output besides the error messages is given.

### Do you use a latexmkrc file?

Yes

### VimtexInfo

```yaml
System info
  OS: macOS 11.6 (20G165)
  Vim version: NVIM v0.6.0
  Has clientserver: true
  Servername: /var/folders/2z/5wwlz56106bg0p3hrgdbn9lr0000gn/T/nvim70fnoq/0
  
VimTeX project: minimal
  base: minimal.tex
  root: /Users/nela/test/
  tex: /Users/nela/test/minimal.tex
  main parser: current file verified
  document class: minimal
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    build_dir: out
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Skim
  qf method: LaTeX logfile
```
