### ISSUE TITLE
skim shows reading bar when point to location

### ISSUE THREAD

**Issue by uthpalaherath** [lervag/vimtex#2270]
### Description

Dear developer, 

Vimtex works great with skim, but there is a minor issue I'm facing. I am not sure if it is coming from skim or vimlatex though. 
After successfully compiling the tex file with `\ll`, I press `\lv ` to point to the line in skim, it does show the location of the line in skim but it automatically turns on the reading bar as well (see below). 

![image](https://user-images.githubusercontent.com/28810161/144888469-4a65a8d1-2606-4c6e-a5ea-058351d50e90.png)

Is there a way to fix this?
I am testing with the minimal vim configurations. 

Thanks, 
Uthpala

### Expected behavior

I would expect the reading bar in skim to not be enabled when I press `\lv` to point to the location of the text.

### Actual behavior

The reading bar in skim shows up automatically masking all the other lines. 

### Do you use a latexmkrc file?

Yes 

### VimtexInfo

```yaml
System info
  OS: macOS 12.0.1 (21A559)
  Vim version: VIM 8.2 (1-2681)
  Has clientserver: true
  Servername: VIM

VimTeX project: minimal
  base: minimal.tex
  root: /Users/uthpala
  tex: /Users/uthpala/minimal.tex
  main parser: current file verified
  document class: minimal
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: process 29049 run
      output: /var/folders/p0/pvjs8qqx7f38164jxqrwsw2w0000gn/T/vPDn4kX/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'minimal.tex'
      pid: 29049
  viewer: Skim
    cmd_view_callback: osascript -e 'set theFile to POSIX file "/Users/uthpala/minimal.pdf"' -e 'set thePath to POSIX path of (theFile as alias)' -e 'tell application "Skim"' -e 'try' -e 'set theDocs to get documents whose path is thePath' -e 'if (count of theDocs) > 0 then revert theDocs' -e 'end try' -e 'open theFile' -e 'end tell'
    cmd_view: osascript -e 'set theLine to 3 as integer' -e 'set theFile to POSIX file "/Users/uthpala/minimal.pdf"' -e 'set thePath to POSIX path of (theFile as alias)' -e 'set theSource to POSIX file "/Users/uthpala/minimal.tex"' -e 'tell application "Skim"' -e 'try' -e 'set theDocs to get documents whose path is thePath' -e 'if (count of theDocs) > 0 then revert theDocs' -e 'end try' -e 'open theFile' -e 'tell front document to go to TeX line theLine from theSource showing reading bar true'  -e 'end tell'
  qf method: LaTeX logfile
```
