### ISSUE TITLE
Backward search of GVim + Zathura broken

### ISSUE THREAD

**Issue by zexiangliu** [lervag/vimtex#2273]
### Description

The backward search function of GVim with Zathura is broken after I updated vimtex to the latest version. By switching to the past versions, I found that the latest commit **without** this issue is [74b6d59](https://github.com/lervag/vimtex/commit/74b6d59ea52ee4a660d62e4e6cc5ef5da7ef5c68). 

### Steps to reproduce

- In the terminal, type `gvim -u minimal.vim minimal.tex`
- In GVim, compile the tex file by pressing `\ll` and then ctrl+left click the word "Hello" in the pop-up Zathura window.

minimal.vim
```vim
set nocompatible
let &runtimepath  = '~/.vim/plugged/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/plugged/vimtex/after'
filetype plugin indent on
syntax enable
let g:tex_flavor='latex'
let g:vimtex_view_method='zathura'
if empty(v:servername) && exists('*remote_startserver')
    call remote_startserver('VIM')
endif
```

minimal.tex
```tex
\documentclass[12pt,letterpaper]{article}
\author{test}
\title{Test}
\date{}
\begin{document}
\maketitle
Hello
\end{document}
```

### Expected behavior

The backward search is triggered after clicking the word "Hello" in Zathura.

### Actual behavior

- Following the steps above, there is no response in GVim after clicking the word "Hello" in Zathura.
- For the attached `minimal.vim` and `minimal.tex`, the backward search works for Vim with Zathura. 
- By commenting out the last three lines in the attached `minimal.vim`, surprisingly, the backward search works for GVim with Zathura. But in this case, the backward search does not work for Vim with Zathura anymore, since the server is not started. 

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info
  OS: Ubuntu 20.04.3 LTS
  Vim version: VIM 8.1 (1-2269)
  Has clientserver: true
  Servername: GVIM

VimTeX project: minimal
  base: minimal.tex
  root: /home/zexiang/test
  tex: /home/zexiang/test/minimal.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: process 75146 run
      output: /tmp/vnI7w7K/1
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -e '$new_viewer_always = "0"' -e '$pdf_previewer = "zathura  -x \"/usr/bin/vim.gtk3 -T dumb --not-a-term -n -c \"\\\"\"VimtexInverseSearch \%{line} '"'"'\%{input}'"'"'\"\\\"\"\" \%S"' -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'minimal.tex'
      pid: 75146
  viewer: Zathura
    xwin id: 92274691
  qf method: LaTeX logfile
```
