### ISSUE TITLE
Slow syntax highlighting when cursorcolumn enabled

### ISSUE THREAD

**Issue by PhyX-Meow** [lervag/vimtex#2275]
### Description

With vimtex and cursorcolumn enabled, the cursor just move very laggy when I press `j` or `k`, for example editing this file: [FAHW21.txt](https://github.com/lervag/vimtex/files/7684574/FAHW21.txt). Github does not allow to upload tex file, so I renamed it to txt.

Edit: I have disabled matchparen functionality, before that it is even more laggy.

Well... May be just disable cursorcolumn is a not bad solution, but still I'd like to let you know. Any way thank you for your work.

### Steps to reproduce

1. `vim -u minimal.vim minimal.tex`
2. Press `j` and watch cursor moving.

minimal.vim
```vim
set nocompatible
let &runtimepath  = '~/.vim/plugged/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/plugged/vimtex/after'
let g:tex_conceal = 'abdmg'
set conceallevel=2
set relativenumber
filetype plugin indent on
syntax enable

let g:vimtex_matchparen_enabled = 0
set cursorcolumn
```

### Expected behavior

The lag is acceptable compare to without `set cursorcolumn`

### Actual behavior

To laggy.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info
  OS: Arch Linux
  Vim version: VIM 8.2 (1-3582)
  Has clientserver: true
  Servername: VIM

VimTeX project: FAHW21
  base: FAHW21.tex
  root: /home/wuli/CodesWSL/TeX/Homework
  tex: /home/wuli/CodesWSL/TeX/Homework/FAHW21.tex
  main parser: current file verified
  document class: article
  packages: amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook bbm biblatex bigintcalc bitset blx-case-expl3 bm calc caption caption3 cleveref color commath enumerate epstopdf-base etexcmds etoolbox expl3 extarrows geometry gettitlestring graphics graphicx hycolor hyperref ifpdf iftex ifthen ifvtex infwarerr intcalc keyval kvdefinekeys kvoptions kvsetkeys latexsym letltxmacro logreq ltxcmds mathrsfs mathtools mhsetup nameref pdfescape pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfrcs pgfsys phyxmeow phyxmeow-common refcount rerunfilecheck subfig tikz tikz-3dplot trig uniquecounter url xcolor xparse xy xypic
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
