### ISSUE TITLE
`VimtexCompileSS` no messages on compiler state

### ISSUE THREAD

**Issue by mrajner** [lervag/vimtex#2276]
### Description

I prefer to use single shot compilation with `VimtexCompileSS` command. This command used to be informative, but now it only gives you one message `VimTeX: Compilation completed`. There is no information on start `compiler started` or if compilation is long I really liked message that `compiler is already running`. 
I was able to track the commit which changed this behaviour: `2ac3d045982aabca6f6a0430da8680feeaabd5fb`, actually this messages were cut off from `autoload/vimtex/compiler/_template.vim` file.

I do not know if that quietness was intentional for single shot compilation, but without that feature you can compulsively run `VimtexCompileSS` without knowing if it is already started, running or not working at all.
Tracking down code I was not able to easily switch on this verboseness.

### Steps to reproduce

`:VimtexCompileSS`

### Expected behavior

VimTeX: Compiler started
VimTeX: Compiler is already running

### Actual behavior

no messages

### Do you use a latexmkrc file?

Yes, but it is irrelevan

### VimtexInfo

```yaml
System info
  OS: Linux 5.15.6-arch2-1
  Vim version: VIM 8.2 (1-3582)
  Has clientserver: true
  Servername: undefined (vim started without --servername)

VimTeX project: wyklad6
  base: wyklad6.tex
  root: /home/mrajner/dyd/rw/wyklady
  tex: /home/mrajner/dyd/rw/wyklady/wyklad6.tex
  main parser: current file
  document class: 
  packages: adjustbox blx-case-expl3 epstopdf-base expl3 gettitlestring infwarerr kvoptions ltxcmds nameref node_on_specific_x pgfplots refcount rw tikz xparse
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: process 62542 dead
      output: /tmp/vb2CyAP/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf 'wyklad6.tex'
      pid: 62542
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
