### ISSUE TITLE
vimtex_compiler_latexmk is not openning the pdf

### ISSUE THREAD

**Issue by rudrab** [lervag/vimtex#2277]
### Description

Is there a new update either from latexmk or vimtex? My setup used to open compiled pdf in evince until last week. Suddenly it stopped opening. It is updating the if the document is already open. 
My minimal vimrc is :
```
" VimPlug {{{
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
call plug#begin('~/.vim/plugged')
" General
Plug 'dense-analysis/ale'
Plug 'fholgado/minibufexpl.vim'                                                     " Buffer explorer
Plug 'neoclide/coc.nvim'                      , {'branch':'release'}
Plug 'lervag/vimtex'                          , {'for':'tex'}                       " Latex
call plug#end()
filetype plugin indent on
syntax enabled
"}}}

"APPERAENCE {{{
colorscheme vimgnome
"}}}
"LaTeX {{{2
augroup FT_LaTex
  autocmd BufReadPost *.tex setlocal filetype=tex
  " au FileType tex let b:ale_linters =  ['texlab']
  " au filetype tex let b:ale_fixers = ['latexindent', 'remove_trailing_lines', 'trim_whitespace']
  let g:tex_flavor = 'latex'
  au FileType tex inoremap "" ``"<++><esc>4hi
  au FileType bib inoremap "" ""<++><esc>4hi
  au FileType tex,bib  inoremap $$ $$<++><esc>4hi
  au VimLeavePre  *.tex  exe "! latexmk -c"
  au filetype tex syntax region texZone start='\\begin{minted}' end='\\end{minted}'
  autocmd Filetype tex nmap <buffer> <f10> :w<CR> :VimtexCompileSS<CR><Esc>
  autocmd Filetype tex imap <buffer> <f10> <esc>:w<cr>:VimtexCompileSS<cr><esc>
  autocmd FileType tex setlocal textwidth=129
  autocmd FileType tex setlocal colorcolumn=130
  autocmd User VimtexEventView call EvinceForwardSearch()
augroup END
"}}}2

" VimTeX {{{1
let g:vimtex_grammar_textidote = {'jar': '/home/rudra/.local/bin/textidote.jar',}
let g:vimtex_imaps_leader='`'
let g:vimtex_compiler_latexmk = {
      \ 'continuous' : 0,
      \ 'options' : [
        \   '-verbose',
        \   '-pv',
        \   '-file-line-error',
        \   '-synctex=1',
        \   '-shell-escape',
        \   '-interaction=nonstopmode',
        \ ],
        \}
let g:vimtex_compiler_latexmk_engines = {
      \ '_' : '-lualatex',
      \}
"}}}1

```

### Expected behavior

after the compilation finished successfully, pdf file should be opend.

### Actual behavior

pdf file is not opened. If I open the file manually, successive compilations keeps the pdf updating.

### Do you use a latexmkrc file?

NA

### VimtexInfo

```yaml
System info:
  OS: Linux 5.15.6-200.fc35.x86_64
  Vim version: VIM 8.2 (1-3755)
  Has clientserver: true
  Servername: VIM1

VimTeX project: mwp
  base: mwp.tex
  root: /home/rudra/Projects/Book/Fortran
  tex: /home/rudra/Projects/Book/Fortran/mwp.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -lualatex
    options:
      -verbose
      -pv
      -file-line-error
      -synctex=1
      -shell-escape
      -interaction=nonstopmode
    callback: 1
    continuous: 0
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
