### ISSUE TITLE
Issue on texMathZones and  math() to idenfity math regions.

### ISSUE THREAD

**Issue by chenle02** [lervag/vimtex#2278]
### Description

Recently I migrated from nvim 0.4 to nvim 0.7. I am using nvim_compe for completion. My snippets work well for all those without math(). But it cannot identify math region. Here is the beginning of the snippet file:

```
global !p
texMathZones = ['texMathZone' + x for x in ['', 'X', 'XX', 'Env', 'EnvStarred', 'Ensured']]
texIgnoreMathZones = ['texMathTextArg']
texMathZoneIds = vim.eval('map('+str(texMathZones)+", 'hlID(v:val)')")
texIgnoreMathZoneIds = vim.eval('map('+str(texIgnoreMathZones)+", 'hlID(v:val)')")
ignore = texIgnoreMathZoneIds[0]
def math():
		synstackids = vim.eval("synstack(line('.'), col('.') - (col('.')>=2 ? 1 : 0))")
		try:
				first = next(i for i in reversed(synstackids) if i in texIgnoreMathZoneIds or i in texMathZoneIds)
				return first != ignore
		except StopIteration:
				return False
...
...
endglobal
```

Should one update this math() function for neovim 0.5+ with nvim_compe? Thanks a lot for your great help!

### Expected behavior

When typing 1/2 in the math region, we expect to have

```tex
\begin{align}
  \frac{1}{2}
\end{align}
```

### Actual behavior

```tex
\begin{align}
  1/2
\end{align}
```

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 20.04.3 LTS
  Vim version: NVIM v0.7.0-dev
  Has clientserver: true
  Servername: /tmp/nvim3rKONa/0

VimTeX project: SolX_STAT3600_2021Fall
  base: SolX_STAT3600_2021Fall.tex
  root: /home/aaaaaa/Dropbox/....
  tex: /home/aaaaaa/Dropbox/....
  main parser: current file verified
  document class: article
  packages: amscd amsmath amssymb amsthm enumerate fancyhdr geometry graphicx ifsym inputenc lipsum mathabx mdframed poker subcaption tikz url xcolor
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
