### ISSUE TITLE
Skim forward search not working on macOS 12.1

### ISSUE THREAD

**Issue by Zeta611** [lervag/vimtex#2279]
### Description

I recently got an M1 Mac (if relevant) and setup Neovim + vimtex almost identically to my previous intel Mac.
However, forward search does not work anymore.

I installed both Neovim and Skim via Homebrew.

### Steps to reproduce

I invoked `neovim` with `NVIM_LISTEN_ADDRESS=/tmp/nvimsocket nvim -u minimal.vim minimal.tex`.

```vim
set nocompatible

let &runtimepath  = '~/.local/share/nvim/plugged/vimtex,' . &runtimepath
let &runtimepath .= ',~/.local/share/nvim/plugged/vimtex/after'

filetype plugin indent on
syntax on

let g:vimtex_view_method = 'skim'
```

```tex
\documentclass{article}

\begin{document}
Hello, \TeX!
\end{document}
```

### Expected behavior

Forward search should work with `\ll` or `:VimtexView`.

### Actual behavior

Skim does not get focused nor 'forward-search'ed.

Initial `\ll` does wake Skim and open the document (without current line being focused).

Backward search does work properly.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 12.1 (21C52)
  Vim version: NVIM v0.6.0
  Has clientserver: true
  Servername: /tmp/nvimsocket

VimTeX project: test
  base: test.tex
  root: /Users/jay/Developer/TeXProjects/test
  tex: /Users/jay/Developer/TeXProjects/test/test.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Skim
  qf method: LaTeX logfile
```
