### ISSUE TITLE
zathura backward search not working

### ISSUE THREAD

**Issue by danjenson** [lervag/vimtex#2281]
### Description

Backward search with ctrl+click in zathura not working.

### Steps to reproduce

`minimal.vim`:
```vim
set nocompatible
let &rtp = '~/.local/share/nvim/plugged/vimtex,' . &rtp
let &rtp .= ',~/.local/share/nvim/plugged/vimtex/after'
filetype plugin indent on
syntax enable
let g:vimtex_view_method = 'zathura'
```

`minimal.tex`:
```tex
\documentclass{minimal}
\begin{document}
Hello world!
\newpage
Bye world!
\end{document}
```

`.latexmkrc`
```perl
$out_dir = 'build';
$pdf_mode = 1;
$pdf_previewer = 'zathura';
set_tex_cmds('-synctex=1 -interaction=nonstopmode -shell-escape %O %S');
```

`~/.config/zathura/zathurarc`
```
set adjust-open "best-fit"
set recolor "true"
set completion-bg "#181b22"
set completion-fg "#c3d6dd"
set completion-group-bg "#181b22"
set completion-group-fg "#AA778A"
set completion-highlight-bg "#c3d6dd"
set completion-highlight-fg "#181b22"
set recolor-lightcolor "#181b22"
set recolor-darkcolor "#c3d6dd"
set default-bg "#181b22"
set inputbar-bg "#181b22"
set inputbar-fg "#c3d6dd"
set notification-bg "#181b22"
set notification-fg "#c3d6dd"
set notification-error-bg "#5F748B"
set notification-error-fg "#c3d6dd"
set notification-warning-bg "#5F748B"
set notification-warning-fg "#c3d6dd"
set statusbar-bg "#181b22"
set statusbar-fg "#c3d6dd"
set index-bg "#181b22"
set index-fg "#c3d6dd"
set index-active-bg "#c3d6dd"
set index-active-fg "#181b22"
set render-loading-bg "#181b22"
set render-loading-fg "#c3d6dd"
set window-title-home-tilde true
set statusbar-basename true
set selection-clipboard clipboard
```

`nvim --version`:
```
NVIM v0.6.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by void-buildslave@a-fsn-de
```

`ldd /usr/bin/zathura | rg libsynctex`
```
libsynctex.so.2 => /usr/lib/libsynctex.so.2 (0x00007fcbfcd2b000)
```

`pip install neovim neovim-remote` -> packages are installed.

### Expected behavior

Backward search works on control+click.

### Actual behavior

Nothing happens.

### Do you use a latexmkrc file?

yes

### VimtexInfo

```yaml
System info:
  OS: Void Linux
  Vim version: NVIM v0.6.0
  Has clientserver: true
  Servername: /tmp/nvimpEe5pQ/0

VimTeX project: minimal
  base: minimal.tex
  root: /home/danj
  tex: /home/danj/minimal.tex
  main parser: current file
  document class:
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    build_dir: build
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
