### ISSUE TITLE
open pdf associated with bibtex citation

### ISSUE THREAD

**Issue by rhaynes74** [lervag/vimtex#2284]
### Description

Hi folks, all of my bibtex references have a file="filename.pdf" entry, pointing to a directory on my harddrive.   I would like to be able to autocomplete \cite commands (searching by author or title keyword) and also would like to be able to open the pdf associated with a citation.   Anyone develop an extension to vimtex that would enable this?

### Do you use a latexmkrc file?

No

### VimtexInfo
```yaml
System info
  OS: macOS 12.1 (21C52)
  Vim version: NVIM v0.6.0
  Has clientserver: true
  Servername: /var/folders/6n/6bq6zkqd00s4wgrkml1rgs4h0000gr/T/nvimTXQaUd/0

VimTeX project: bigdiscreteRa21Dec2021RH
  base: bigdiscreteRa21Dec2021RH.tex
  root: /Users/rhaynes/Dropbox/HaynesKhaledDB/2Paper1_THETA_SWR
  tex: /Users/rhaynes/Dropbox/HaynesKhaledDB/2Paper1_THETA_SWR/bigdiscreteRa21Dec2021RH.tex
  main parser: current file verified
  document class: siamltex
  packages: amsfonts amsmath caption environ epstopdf float graphicx inputenc natbib resizegather subcaption tikz verbatim xcolor
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
