### ISSUE TITLE
Continuous mode can not work in Neovim

### ISSUE THREAD

**Issue by RnYi** [lervag/vimtex#2291]
### Description

1. Cannot auto open sumatraPDF while in continuous mode. But it can work in vim.
2. Multiple errors are reported when running some commands, such as `VimtexCompile`, `VimtexClean`.

### Steps to reproduce

1. nvim -u minimal.vim minimal.tex
2. run `:VimtexCompile`

### Expected behavior

Auto open sumatraPDF.

### Actual behavior

latexmk succeed in compiling tex file and producing a pdf, but doesn't open sumatraPDF.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS:  ()
  Vim version: NVIM v0.7.0-dev+761-g0d7a97224
  Has clientserver: true
  Servername: \\.\pipe\nvim-12348-0

VimTeX project: mininal
  base: mininal.tex
  root: C:\Users\RanY\.vim
  tex: C:\Users\RanY\.vim\mininal.tex
  main parser: current file verified
  document class: minimal
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
