### ISSUE TITLE
Writing double dollar '$$' turns into '$$<++>'

### ISSUE THREAD

**Issue by MatteoGaetzner** [lervag/vimtex#2297]
### Description

Behavior:
When writing two dollar signs consecutively, the second dollar sign gets replaced with $<++>, which yields '$$<++>' as the final output.

Expected:
Writing two dollar signs yields '$$'.

### Steps to reproduce

minimal.vim:
`if empty(glob('~/.config/nvim/autoload/plug.vim'))
  silent !curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

call plug#begin('~/.config/nvim/autoload/plugged')

Plug 'lervag/vimtex'

call plug#end()`

minimal.tex:
``

I don't know how to reproduce it in the way that you describe.
If I use the -u flag, the issue disappears.

Nevertheless here is how I get the error:
1. `nvim minimal.tex`
2. Type `$$`

### Expected behavior

Nothing should happen.

### Actual behavior

$$ gets expanded to $$<++>.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Linux 5.15.13-arch1-1
  Vim version: NVIM v0.6.1
  Has clientserver: true
  Servername: /tmp/nvimPjqUUd/0

VimTeX project: minimal
  base: minimal.tex
  root: /home/matteo/.config/nvim
  tex: /home/matteo/.config/nvim/minimal.tex
  main parser: current file
  document class: 
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
