### ISSUE TITLE
Conceallevet not working anymore

### ISSUE THREAD

**Issue by SingularisArt** [lervag/vimtex#2298]
### Description

I had this plugin installed for a long time. But, just a couple of days ago, the conceallevel just stopped working. It doesn't show any of the symbols, fractions, super scripts, sub scripts, etc.

You can view my plugins [here](https://github.com/SingularisArt/Death.NeoVim/blob/master/lua/core/plugins.lua)
You can view my vimtex config [here](https://github.com/SingularisArt/Death.NeoVim/blob/master/lua/plugin-configs/vimtex.lua)

### Steps to reproduce

1. use { 'lervag/vimtex' }
2. PackerInstall

### Expected behavior

I expect to see the fractions to show as fractions, not as \frac{1}{2}, the symbols to show, not \delta.

### Actual behavior

I don't get any of the symbols to show.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Arch Linux
  Vim version: NVIM v0.6.0
  Has clientserver: true
  Servername: /tmp/nvim5uBTGw/0

VimTeX project: main
  base: main.tex
  root: /home/hashem/Documents/notes/Grade-10/semester-1/assignments
  tex: /home/hashem/Documents/notes/Grade-10/semester-1/assignments/main.tex
  main parser: current file verified
  document class: article
  packages: aliasctr amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm array atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook babel biblatex bigintcalc bitset blx-case-expl3 bm booktabs cabin calc cancel caption caption3 cleveref cmbright color csquotes emptypage enumitem environ epstopdf-base erewhon eso-pic etexcmds etoolbox expl3 fancyhdr float fontaxes fontenc gettitlestring graphics graphicx hycolor hyperref ifluatex ifmtarg ifsym iftex ifthen ifxetex import infwarerr inputenc intcalc keyval kvdefinekeys kvoptions kvsetkeys l3keys2e letltxmacro lipsum lmodern logreq longdivision lscape ltxcmds mathrsfs mathtools mdframed media9 mhsetup microtype multicol multirow mweights nameref needspace ocgbase parseargs parskip pdfbase pdfcol pdfescape pdflscape pdfpages pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfplots pgfrcs pgfsys polynom refcount rerunfilecheck scalefnt siunitx stmaryrd subcaption systeme tcolorbox textcomp thm-amsthm thm-autoref thm-kv thm-listof thm-patch thm-restate thmdef-mdframed thmtools tikz tikz-cd titletoc tocbibind todonotes translator transparent trig trimspaces ulem uniquecounter upgreek url verbatim xcolor xifthen xkeyval xparse xparse-2020-10-01 xstring zref-abspage zref-base
  source files:
    main.tex
    preamble.tex
    government/latex-files/04.02-Judicial-Review.tex
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
