### ISSUE TITLE
\ll starts two viewers

### ISSUE THREAD

**Issue by st-bender** [lervag/vimtex#2299]
### Description

Using \ll to compile and view the pdf leads to two open windows with the pdf.

### Steps to reproduce

1. Create or open a latex file (the minimal example at the bottom, for example)
2. Press \ll for compilation

### Expected behavior

One window opens with the compiled document.

### Actual behavior

Two windows open with the compiled document.

### Do you use a latexmkrc file?

yes

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 18.04.6 LTS
  Vim version: VIM 8.0 (1-1453)
  Has clientserver: true
  Servername: undefined (vim started without --servername)

VimTeX project: project
  base: project.tex
  root: /home/user/Documents/project
  tex: /home/user/Documents/project/project.tex
  main parser: current file verified
  document class: scrartcl
  packages: SIunits adjcalc adjustbox amsbsy amsfonts amsgen amsmath amsopn amssymb amstext auxhook babel biblat
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: process 23962 run
      output: /tmp/vli0TXx/1
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -
      pid: 23962
  viewer: MuPDF
    xwin id: 167772235
```
