### ISSUE TITLE
\lfloor and \rfloor conceal symbols are flipped

### ISSUE THREAD

**Issue by Dophin2009** [lervag/vimtex#2304]
### Description

The conceal symbols used for `\lfloor` and `\rfloor` are flipped.

### Steps to reproduce

1. `vim -u minimal.vim minimal.tex`
2. Observe that conceal symbols are incorrect.

`minimal.vim`
```vim
set nocompatible
let &runtimepath = '~/.vim/bundle/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable
set conceallevel=1
```

`minimal.tex`
```tex
\documentclass{minimal}
\begin{document}
  $\lfloor x \rfloor$
\end{document}
```

### Expected behavior

The current `\lfloor` symbol should be used for `\rfloor`, and vice versa.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Arch Linux
  Vim version: VIM 8.2 (1-4106)
  Has clientserver: false

VimTeX project: minimal
  base: minimal.tex
  root: /home/dophin2009/home/programming/clone/vimtex
  tex: /home/dophin2009/home/programming/clone/vimtex/minimal.tex
  main parser: current file verified
  document class: minimal
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
