### ISSUE TITLE
VimtexCompile and VimtexView shows cmd.exe

### ISSUE THREAD

**Issue by habamax** [lervag/vimtex#2305]
### Description

Whenever I start VimtexCompile on a new document or VimtexView on a document that is compiled I get cmd.exe screen with title of compiled pdf document. No PDF viewer is showed.

If I do VimtexInfo and grab cmd command:

      cmd: start "C:\Users\maksim.kim\docs\test/test/test.pdf"

and manually do `:!start "C:\Users\maksim.kim\docs\test/test/test.pdf"` -- it is opened in my SumatraPDF.

## test.tex
```
\documentclass{article}

\title{Document}
\author{Test}

\begin{document}

test

\end{document}
```

## minimal.vim

```
filetype plugin indent on
syntax on
```

## Steps
1. `vim -Nu minimal.vim test.tex`
2. `:VimtexCompile`

![vimtex-compile](https://user-images.githubusercontent.com/234774/150673827-48e199c9-a96f-4e3e-b99c-ee614eba30a0.gif)

### Expected behavior

As usual, my PDF viewer should show the compiled document.

### Actual behavior

![image](https://user-images.githubusercontent.com/234774/150673413-355cd33d-ff02-4308-ab17-7846d84da28d.png)

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: MKIM2 ( ©ªà®á®äâ Windows 10 Pro)
  Vim version: VIM 8.2 (1-4186)
  Has clientserver: true
  Servername: VIM

VimTeX project: test
  base: test.tex
  root: C:\Users\maksim.kim\docs\test
  tex: C:\Users\maksim.kim\docs\test\test.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -lualatex
    options:
      -shell-escape
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    build_dir: test
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: process 17200 run
      output: C:\Users\maksim.kim\AppData\Local\Temp\VHPDECE.tmp
      cmd: set max_print_line=2000 & latexmk -shell-escape -verbose -file-line-error -synctex=1 -interaction=nonstopmode -lualatex -outdir=test -pvc -view=none -e "$compiling_cmd = ($compiling_cmd ? $compiling_cmd . ' & ' : '') . 'echo vimtex_compiler_callback_compiling'" -e "$success_cmd = ($success_cmd ? $success_cmd . ' & ' : '') . 'echo vimtex_compiler_callback_success'" -e "$failure_cmd = ($failure_cmd ? $failure_cmd . ' & ' : '') . 'echo vimtex_compiler_callback_failure'" "test.tex"
      pid: 17200
  viewer: General
    job: 
      pid: 15220
      cmd: start "C:\Users\maksim.kim\docs\test/test/test.pdf"
  qf method: LaTeX logfile
```
