### ISSUE TITLE
:help vimtex-non-features doesn't seem to exist anymore

### ISSUE THREAD

**Issue by sourav-majumdar-math** [lervag/vimtex#2306]
### Description

The README mentions,

>  For a more detailed listing of these, please see :help vimtex-non-features

This doesn't seem to be there

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Linux 5.15.16-1-lts
  Vim version: NVIM v0.6.1
  Has clientserver: true
  Servername: /tmp/nvimaOypRe/0

VimTeX project: main
  base: main.tex
  root: ****
  tex: ****
/main.tex
  main parser: current file verified
  document class: article
  packages: adjustbox algorithm algpseudocode amsmath amssymb amsthm apacite authblk babel biblatex blkarray commath csquotes filecontents float geometry graphicx hyperref inputenc lineno mathrsfs soul stmaryrd tikz-cd xcolor
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
