### ISSUE TITLE
Incorrect filename detection when parsing log files

### ISSUE THREAD

**Issue by nightuser** [lervag/vimtex#2312]
### Description

VimTeX reports incorrect filenames in the quickfix window. The parser extracts filenames from `LaTeX Font Info` entries in the log file.

### Steps to reproduce

1. `nvim -u minimal.vim minimal.tex`
2. Try to compile with `:VimtexCompile`
3. The file has a correct warning, but the filename is incorrect. For example, with MacTeX I get
    ```
    /usr/local/texlive/2021/texmf-dist/tex/latex/sansmathaccent/ot1mathkerncmss.fd|34 warning| Overfull \vbox (5.5187pt too high) detected at line 34
    ```

`minimal.vim`:
```vim
set nocompatible
let &runtimepath  = '~/.local/share/nvim/plugged/vimtex,' . &runtimepath
let &runtimepath .= ',~/.local/share/nvim/plugged/vimtex/after'
filetype plugin indent on
syntax enable
```

`minimal.tex`:
```tex
\documentclass{beamer}

\usepackage[T1]{fontenc}
\renewcommand{\familydefault}{\sfdefault}
\title{Test}

\begin{document}

\begin{frame}[t]{VC-dimension}
    \begin{itemize}
        \item Test.
        \item Test.
        \item Test.
        \item Test.
        \item Test.
        \item Test.
        \item Test.
        \item Test.
        \item Test.
        \item Test.
        \item Test.
        \item Test.
        \item Test.
        \item Test.
        \item Test.
        \item Test.
        \item Test.
        \item Test.
    \end{itemize}
\end{frame}

\end{document}
```

### Expected behavior

Should output the correct filename (instead of the fd file).

### Actual behavior

Outputs
```
/usr/local/texlive/2021/texmf-dist/tex/latex/sansmathaccent/ot1mathkerncmss.fd|34 warning| Overfull \vbox (5.5187pt too high) detected at line 34
```

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:                                                        
  OS: macOS 12.1 (21C52)                          
  Vim version: NVIM v0.6.1
  Has clientserver: true                                            
  Servername: /var/folders/x8/85pdv65j5wb0gcbzk5tx2pd00000gn/T/nvimeiUOwB/0
                                       
VimTeX project: minimal                  
  base: minimal.tex                                                 
  root: /Users/nightuser/dev/vc-short                                     
  tex: /Users/nightuser/dev/vc-short/minimal.tex                            
  main parser: current file verified                           
  document class: beamer
  packages: amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook beamerbaseauxtemplates beamerbaseboxes beamerbasecolor beamerbasecompatibilit
  compiler: latexmk                                                          
    engine: -pdf                                             
    options:       
      -verbose                                                       
      -file-line-error                                                        
      -synctex=1                                                          
      -interaction=nonstopmode                                            
    callback: 1    
    continuous: 1  
    executable: latexmk 
    job:           
      jobid: 5                           
      output: /var/folders/x8/85pdv65j5wb0gcbzk5tx2pd00000gn/T/nvimeiUOwB/1
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex
      pid: 74362       
  viewer: General      
    job:               
      pid: -                  
      cmd: open '/Users/nightuser/dev/vc-short/minimal.pdf'
  qf method: LaTeX logfile
```
