### ISSUE TITLE
Citation completion not working on windows unless full ~/textmf/bibtex/bib/... path is specified

### ISSUE THREAD

**Issue by lyeoh** [lervag/vimtex#2322]
### Description

I'm not sure if it's just my setup or which versions of `kpsewhich` are doing this but as of `kpathsea version 6.3.3`, the absolute paths that `kpsewhich` returns can have a lowercase drive letter on windows. Then `vimtex#kpsewhich#find` thinks this is a relative path and prepends `l:root` to it.

### Steps to reproduce

1. `nvim -u minimal.vim minimal.tex`
2. `:VimtexCompile`
3. enter insert mode in the \cite command `\cite{citeke|}`
4. attempt citation completion with `<C-X><C-O>`

minimal.tex
```
\documentclass{article}
\begin{document}
\cite{citeke}
\bibliographystyle{unsrt}
\bibliography{minimal}
% \bibliography{C:/Users/luke/texmf/bibtex/bib/minimal.bib}
\end{document}
```
minimal.vim
```
set nocompatible
let &runtimepath  = '~/AppData/Local/nvim/plugged/vimtex,' . &runtimepath
let &runtimepath .= ',~/AppData/Local/nvim/plugged/vimtex/after'
filetype plugin indent on
syntax enable
```
~\texmf\bibtex\bib\minimal.bib
```
@article{citekey,
  title = {Title},
  author = {Author},
  year = {Year},
  journal = {Journal},
}
```

### Expected behavior

`citeke` completes to `citekey`

### Actual behavior

- No completion takes place, with the error message `Pattern not found`.
- `:echo vimtex#bib#files()` returns `[]`
- `:echo vimtex#kpsewhich#find('minimal.bib')` returns `C:\Users\luke\Downloads\issue/c:Users/luke/texmf/bibtex/bib/minimal.bib`
- `:echo vimtex#jobs#capture('kpsewhich minimal.bib')` returns `['c:/Users/luke/texmf/bibtex/bib/minimal.bib']`

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: WINDOUGH (Microsoft Windows 10 Education)
  Vim version: NVIM v0.4.4
  Has clientserver: true
  Servername: \\.\pipe\nvim-60692-0

VimTeX project: minimal
  base: minimal.tex
  root: C:\Users\luke\Downloads\issue
  tex: C:\Users\luke\Downloads\issue\minimal.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 5
      output: C:\Users\luke\AppData\Local\Temp\nvimOclcoH\0
      cmd: set max_print_line=2000 & latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e "$compiling_cmd = ($compiling_cmd ? $compiling_cmd . ' ^& ' : '') . 'echo vimtex_compiler_callback_compiling'" -e "$success_cmd = ($success_cmd ? $success_cmd . ' ^& ' : '') . 'echo vimtex_compiler_callback_success'" -e "$failure_cmd = ($failure_cmd ? $failure_cmd . ' ^& ' : '') . 'echo vimtex_compiler_callback_failure'" "minimal.tex"
      pid: 64744
  viewer: General
    job: 
      pid: 51580
      cmd: SumatraPDF -reuse-instance -forward-search "C:\Users\luke\Downloads\issue\minimal.tex" 1 "C:\Users\luke\Downloads\issue/minimal.pdf"
  qf method: LaTeX logfile
```
