### ISSUE TITLE
VimR + sioyek and inverse search seems not to work

### ISSUE THREAD

**Issue by pitkling** [lervag/vimtex#2323]
### Description

I recently started to use [sioyek](https://sioyek.info) instead of Skim with vimtex (under macOS 12.1). I use Neovim either directly in the terminal or through [VimR](https://github.com/qvacua/vimr). In the terminal, everything works as expected. However, under VimR inverse search seems broken. It simply does nothing.

I checked `VimtexInfo` for the actual inverse search command that is passed to sioyek in both cases. In the terminal, my nvim binary (v0.6.0), while under VimR it uses `/Applications/VimR.app/Contents/Resources/NvimView_NvimView.bundle/Contents/Resources/NvimServer` (which is reported as NVIM v0.6.1). If I manually call this NvimServer binary with the proper arguments (like `--headless -c "VimtexInverseSearch 100 'main.tex'"`), I get the message `We need at least 4 arguments! Printing --version and exiting...`.

While using Skim I configured it to use `nvr` (similar as described in the [Wiki](https://github.com/lervag/vimtex/wiki/introduction#neovim)). I might be able to configure sioyek directly via its config file to use `nvr`, but I would suspect (and a first test seems to confirm this) that the command line parameters given to sioyek by vimtex would overwrite that.

Any hints at what I'm doing wrong or whether this is indeed a bug of some sort (not necessarily in vimtex)? Is there any way I can overwrite arguments vimtex uses to tell sioyek is supposed to perform an inverse search?

### Steps to reproduce

1. open some tex file in VimR
2. compile via vimtex configured with sioyek
3. use inverse search in sioyek (synctex-mode is enabled)

### Expected behavior

VimR should jump to the correct line of the source file.

### Actual behavior

Nothing happens.

### Do you use a latexmkrc file?

Yes

### VimtexInfo

```yaml
System info:
  OS: macOS 12.1 (21C52)
  Vim version: NVIM v0.6.1
  Has clientserver: true
  Servername: /var/folders/3d/3k3v6hm178q07wh9163lkq800000gn/T/vimr_7FDC59DC-1A5C-4459-AAC8-19AAF5AA5BD2.sock

VimTeX project: main
  base: main.tex
  root: /private/tmp
  tex: /private/tmp/main.tex
  main parser: current file verified
  document class: scrartcl
  packages: accsupp aliasctr amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook auxlib babel biblatex bibretriever bigintcalc bitset blx-case-expl3 bm bookmark braket calc cleveref color csquotes enumitem epstopdf-base etexcmds etoolbox expl3 float fontenc footmisc geometry gettitlestring graphics graphicx grfext hycolor hyperref ifdraft iftex ifthen ifvtex infwarerr inputenc intcalc keyval kvdefinekeys kvoptions kvsetkeys letltxmacro lineno listings logreq lstmisc ltxcmds mathtools mhsetup microtype mparhack nameref nccmath parseargs pdfescape pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfrcs pgfsys refcount regexpatch relsize rerunfilecheck scrbase scrkbase scrlfile scrlfile-hook scrlogo silence textcomp thm-amsthm thm-autoref thm-kv thm-listof thm-patch thm-restate thmtools tikz tocbasic translator trig typearea uniquecounter url xcolor xparse xpatch xspace
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    build_dir: _build.nosync
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 18
      output: /var/folders/3d/3k3v6hm178q07wh9163lkq800000gn/T/nvimikmtq9/1
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -outdir=_build.nosync -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'main.tex'
      pid: 84307
  viewer: sioyek
    job: 
      pid: -
      cmd: /Applications/sioyek.app/Contents/MacOS/sioyek --reuse-instance --inverse-search "/Applications/VimR.app/Contents/Resources/NvimView_NvimView.bundle/Contents/Resources/NvimServer --headless -c \"VimtexInverseSearch %2 '%1'\"" --forward-search-file '/private/tmp/main.tex' --forward-search-line 1 '/private/tmp/_build.nosync/main.pdf'
    cmd_start: /Applications/sioyek.app/Contents/MacOS/sioyek --reuse-instance --inverse-search "/Applications/VimR.app/Contents/Resources/NvimView_NvimView.bundle/Contents/Resources/NvimServer --headless -c \"VimtexInverseSearch %2 '%1'\"" --forward-search-file '/private/tmp/main.tex' --forward-search-line 1 '/private/tmp/_build.nosync/main.pdf'
  qf method: LaTeX logfile
```
