### ISSUE TITLE
NVim, Windows: "Invalid viewer: SumatraPDF"

### ISSUE THREAD

**Issue by gilbh** [lervag/vimtex#2324]
### Description

Setup works fine on my laptop, but the same configuration breaks on my desktop when I open a `.tex` file with
```
VimTex: Invalid viewer: SumatraPDF
```
SumatraPDF seems to be installed correctly, and it is in $PATH, (and runs from the command shell when I type: `sumatrapdf.exe`) so I am not sure what's wrong. 

Here's my VimTex configuration in `.vimrc`:
```
let g:vimtex_view_method='SumatraPDF'
let g:vimtex_view_general_viewer = 'SumatraPDF'
let g:vimtex_view_general_options
    \ = '-reuse-instance -forward-search @tex @line @pdf'
let g:vimtex_view_general_options_latexmk = '-reuse-instance'
let g:vimtex_quickfix_mode=0
```

Thanks for any help.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info
  OS: C081539 (Microsoft Windows 10 Pro)
  Vim version: NVIM v0.6.0
  Has clientserver: true
  Servername: \\.\pipe\nvim-8272-0

VimTeX project: god_is
  base: god_is.tex
  root: C:\Dropbox\Documents_and_Writings\Research\God Is an
  tex: C:\Dropbox\Documents_and_Writings\Research\God Is an\god_is.tex
  main parser: current file verified
  document class: article
  packages: expl3 fontenc fontspec fontspec-luatex natbib newunicodechar xparse
  compiler: latexmk
    engine: -lualatex
    options:
      -pdf
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  qf method: LaTeX logfile
```
