### ISSUE TITLE
weird behaviour about indent delim

### ISSUE THREAD

**Issue by Freed-Wu** [lervag/vimtex#2328]
### Description

I don't sure about this behaviour is a bug or a feature`:(`

in vimtex, default configuration of VimtexIndentExpr() will indent the following code 
```tex
\command{
  a
  }{
  b
}
```

the original behaviour is weird, it looks like VimtexIndentExpr() treat `}{` as same as `a` `b`

Expected behaviour:
```tex
\command{
  a
}{
  b
}
```

And behaviour:
```tex
\command{
  a
  }\command{
  b
}
```

Expected behaviour:
```tex
\command{
  a
}\command{
  b
}
```

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Arch Linux
  Vim version: NVIM v0.6.1
  Has clientserver: true
  Servername: /tmp/nvimDLQ3rR/0

VimTeX project: .tikz
  base: .tikz
  root: /home/wzy/.config/nvim/template
  tex: /home/wzy/.config/nvim/template/.tikz
  main parser: current file
  document class: standalone
  packages: hyperref
  compiler: latexmk
    engine: -lualatex
    options:
      -verbose
      -synctex=1
      -interaction=nonstopmode
      -shell-escape
      -8bit
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
