### ISSUE TITLE
vimtex with zathura requires dbus

### ISSUE THREAD

**Issue by dkwo** [lervag/vimtex#2329]
### Description

This is just a question. I wanted to confirm: on linux, to use vimtex with zathura, it seems dbus is required, otherwise I get `VimTeX: Viewer cannot find Zathura window ID!`. Is that expected?

This is indeed what I get from the command:
```
$ zathura -x "/usr/bin/vim-x11 -T dumb --not-a-term -n -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 1:2:'/home/nicol
o/Documents/drafts/Gamme/main.tex'  '/home/nicolo/Documents/drafts/Gamme/main.pdf'&
[1] 2576
$ error: Could not connect to session bus: Error spawning command line “dbus-launch --autolaunch=7818fdfca1741e84e1d89d015f666154 --binary-syntax --close-stderr”: Child process exited with code 1
error: Got no usable data from SyncTeX or D-Bus failed in some way.
```
Thanks.

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
System info:
  OS: Void Linux
  Vim version: VIM 8.2 (1-4221)
  Has clientserver: true
  Servername: VIM

VimTeX project: main
  base: main.tex
  root: /home/nicolo/Documents/drafts/Gamme
  tex: /home/nicolo/Documents/drafts/Gamme/main.tex
  main parser: current file verified
  document class: article
  packages: amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm array atbegshi atbegshi-ltx atveryend atveryend-ltx authblk auxhook babel biblatex bigintcalc bitset blx-case-expl3 calc cleveref csquotes epstopdf-base etexcmds etoolbox expl3 fontenc fullpage ge
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job:
      jobid: process 2229 run
      output: /tmp/vJlGPEm/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ?
      pid: 2229
  viewer: Zathura
    xwin id: 0
    cmd_start: zathura -x "/usr/bin/vim-x11 -T dumb --not-a-term -n -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 1:2:'/home/nicolo/Documents/drafts/Gamme/main.tex'  '/home/nicolo/Documents/drafts/Gamme/main.pdf'&
  qf method: LaTeX logfile
```
