### ISSUE TITLE
General auto-unindent not working for a minimal install

### ISSUE THREAD

**Issue by abhijit-c** [lervag/vimtex#2332]
### Description

Hello,

First off, thank you. I've been using this plugin for many years and it's been fantastic.

That being said, recently I've run into an issue where my environments are refusing to auto-unindent on a `\end{env}` line. This is present on both of my Fedora workstations, but doesn't seem to happen on my MacOS install. I'm wondering if there were any tweaks to how indentation works that you recall might affect this?

### Steps to reproduce

With `minimal.vim` being
```vim
set nocompatible "No vi compatible
call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex' "latex syntax highlighting, ToC view, synctex, etc.
call plug#end()
filetype plugin indent on "Load plugins + file specific indent
syntax on
```
and `minimal.tex`
```tex
\documentclass{minimal}
\begin{document}
Hello, work!
\begin{equation}
  \end{equation}
\end{document}
```
I'm running my test with `vim -u minimal.vim minimal.tex`.

### Expected behavior

When I type `\end{equation}` on line 5, I expect that the line should auto-unindent to match the indentation of \begin{equation}.

### Actual behavior

Upon typing the last `}` on line 5, the indentation remains one level higher than the `\begin{equation}` line.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Fedora release 35 (Thirty Five)
  Vim version: VIM 8.2 (1-4314)
  Has clientserver: false

VimTeX project: minimal
  base: minimal.tex
  root: /home/trostaft/Documents/vimtex-testing
  tex: /home/trostaft/Documents/vimtex-testing/minimal.tex
  main parser: current file verified
  document class: minimal
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
```

**Comment by abhijit-c** [comment]
If it helps, here's the VimtexInfo from my Macbook on which indentation works as expected.

```yaml
System info
  OS: macOS 12.1 (21C52)
  Vim version: VIM 8.2 (1-2671, 3402, 3409, 3428, 3489)
  Has clientserver: false

vimtex project: minimal
  base: minimal.tex
  root: /Users/trostaft/Documents/vimtex-testing
  tex: /Users/trostaft/Documents/vimtex-testing/minimal.tex
  out:
  log:
  aux:
  fls:
  main parser: current file verified
  compiler: latexmk
    configuration:
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: General
  qf: LaTeX logfile
    config:
      packages:
        default: 1
      default: 1
  document class: minimal
```
