### ISSUE TITLE
forward and backward search for mupdf

### ISSUE THREAD

**Issue by xyegithub** [lervag/vimtex#2339]
### Description

I set `let g:vimtex_view_general_viewer = 'mupdf'`. However, I do not know how to add the forward and backward search of it. I know it is related to `xdotool`. But how to use it?

### Steps to reproduce

1. set `let g:vimtex_view_general_viewer = 'mupdf'`
2. compile the tex file.

### Expected behavior

enable forward and backward search.

### Actual behavior

do not enable forward and backward search.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 20.04.4 LTS
  Vim version: NVIM v0.6.1
  Has clientserver: true
  Servername: /tmp/nvimqj6LHz/0

VimTeX project: template
  base: template.tex
  root: /home/yexiang/try
  tex: /home/yexiang/try/template.tex
  main parser: current file verified
  document class: svjour3
  packages: amsbsy amsfonts amsgen amsmath amsopn amssymb amstext array booktabs cite color epsfig epstopdf-base fix-cm graphics graphicx ifpdf iftex keyval multirow natbib subfigure trig ulem xy
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 7
      output: /tmp/nvimqj6LHz/2
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'template.tex'
      pid: 22060
  viewer: General
    job: 
      pid: 22070
      cmd: mupdf '/home/yexiang/try/template.pdf'
  qf method: LaTeX logfile
```
