### ISSUE TITLE
Can I use docker contained latexmk with vimtex?

### ISSUE THREAD

**Issue by artur-shaik** [lervag/vimtex#2341]
### Description

Now with generated command:

```
max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -e '$new_viewer_always = "0"' -e '$pdf_previewer = "zathura  -x \"/usr/local/bin/nvim --headless -c \"\\\"\"VimtexInverseSearch \%{line} '"'"'\%input}'"'"'\"\\\"\"\" \%S"' -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'main.tex'
```

I have compile output:

```
Latexmk: -x unknown option
Latexmk: -headless unknown option
Rc files read:
  /etc/LatexMk

Latexmk: Bad options specified
Use
   latexmk -help
to get usage information
```

Is there any possibility to make it work?

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info
  OS: openSUSE Tumbleweed
  Vim version: NVIM v0.6.0-dev+559-gc0ba315b5
  Has clientserver: true
  Servername: /tmp/nvimcwii1b/0

VimTeX project: main
  base: main.tex
  root: /home/user/projects/resume/latexcv/modern
  tex: /home/user/projects/resume/latexcv/modern/main.tex
  main parser: current file verified
  document class: article
  packages: array babel calc color epstopdf-base etexcmds everyshi fancyhdr float fontenc geometry graphics graphicx grfext ifluatex ifmtarg ifpdf ifthen ifvtex ifxetex infwarerr inputenc kvdefinekeys kvoptions kvsetkeys ltxcmds moresize multicol multirow mweights pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfrcs pgfsys raleway tikz trig wrapfig xcolor xifthen xkeyval
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
