### ISSUE TITLE
[regression] zathura forward search opens a new instance when pwd is a symlink

### ISSUE THREAD

**Issue by MoetaYuko** [lervag/vimtex#2342]
### Description

This is a regression after https://github.com/lervag/vimtex/commit/71554107aa2ca28aa93099bdb46cc0c0fdf69a52

When the real place of tex file is ~/foo and I'm working in a symlink ~/bar -> ~/foo, `<localleader>ll` opens a zathura _window A_, `<localleader>lv` opens another _window B_, where:
* backward search works in _window A_ only
* forward search works in _window B_ only

Moreover, when having the autocmd to close viewer on exit, only _window A_ gets closed.

### Steps to reproduce

1. mkdir foo
2. ln -s foo bar
3. cd bar
4. vim -u minimal.vim minimal.tex

minimal.vim
```vim
call plug#begin()
 Plug 'lervag/vimtex'
call plug#end()

set nocp

call remote_startserver('VIM')
let g:vimtex_view_method = 'zathura'

" Close viewers when VimTeX buffers are closed
function! CloseViewers()
  if executable('xdotool')
        \ && exists('b:vimtex.viewer.xwin_id')
        \ && b:vimtex.viewer.xwin_id > 0
    call system('xdotool windowclose '. b:vimtex.viewer.xwin_id)
  endif
endfunction
augroup vimtex_event_2
  au!
  au User VimtexEventQuit call CloseViewers()
augroup END
```
minimal.tex
```tex
\documentclass{minimal}
\begin{document}
Hello world!
\end{document}
```

### Expected behavior

forward search works in _window A_ and no new window opens

### Actual behavior

as described before

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Arch Linux
  Vim version: VIM 8.2 (1-4464)
  Has clientserver: true
  Servername: VIM

VimTeX project: minimal
  base: minimal.tex
  root: /home/dianlujitao/foo
  tex: /home/dianlujitao/foo/minimal.tex
  main parser: current file verified
  document class: minimal
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
