### ISSUE TITLE
vimtex#syntax#in_mathzone() not work correctly in markdown file.

### ISSUE THREAD

**Issue by yqwu905** [lervag/vimtex#2346]
### Description

I use vimtex detect mathzone in ultisnips, and I try to do this for markdown too.
But strange thing is, the `vimtex#syntax#in_mathzone` function is loaded, but it always return 0.
It seem that no syntax file for markdown contain math environment was loaded, because math environment was not correctly highlight, and math symbol conceal not work with `conceallevel=2`.
I use packer as package manager, and load `vimtex` for specified filetype:
`    {"lervag/vimtex", ft = {"plaintex", "tex", "latex", "markdown"}}`
I only configure that:
```
vim.cmd("filetype plugin indent on")
vim.cmd("syntax enable")
```
And I add a autocmd:
```
autocmd BufNewFile,BufRead *.md call vimtex#init()
```
Sorry for my poor English and unclear description due to I have no idea why this situation happen.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Linux 5.10.93.2-microsoft-standard-WSL2
  Vim version: NVIM v0.6.1
  Has clientserver: true
  Servername: /tmp/nvimCHW71J/0

VimTeX project: test
  base: test.md
  root: /home/yqwu
  tex: 
  main parser: current file
  document class: 
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
