### ISSUE TITLE
Deactivating delimiters indentation seems to be no more possible.

### ISSUE THREAD

**Issue by PatrBal** [lervag/vimtex#2347]
### Description

I have had the following line in my .vimrc for years
`let g:vimtex_indent_delims = {'include_modified_math': 0, 'close_indented': 0, 'open': [], 'close': []}
`
in order to deactivate delimiters indentation in LaTeX. It has broken recently.
Now, whenever a closed brace '}' is typed in a .tex file, vim (but the same is true with neovim) gets frozen, and nothing can be typed anymore.
If the above line is commented out in the .vimrc file (or, simply, the 'open' and 'close' entries are removed), everything runs smoothly, but braces induce indentation in LaTeX files.

### Steps to reproduce

1. Add the following line at the end of minimal.vim
`let g:vimtex_indent_delims = {'include_modified_math': 0, 'close_indented': 0, 'open': [], 'close': []}
`
2. Run 
`nvim -u minimal.vim minimal.tex
`
3. Type 'A}' in normal mode
 

### Expected behavior

A closing brace ‘}' appears at the end of the current line.

### Actual behavior

Neovim (but the same is true with vim) is frozen. 

### Do you use a latexmkrc file?

Yes

### VimtexInfo

```yaml
System info:
  OS: macOS 12.2.1 (21D62)
  Vim version: NVIM v0.6.1
  Has clientserver: true
  Servername: /tmp/nvimsocket

VimTeX project: minimal
  base: minimal.tex
  root: /Users/patrick.ballard/Desktop
  tex: /Users/patrick.ballard/Desktop/minimal.tex
  main parser: current file verified
  document class: minimal
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
