### ISSUE TITLE
Use latexrun's default build_dir behavior but open the pdf in the tex's directory

### ISSUE THREAD

**Issue by anntzer** [lervag/vimtex#2350]
### Description

With `let g:vimtex_compiler_method = 'latexrun'`, vimtex defaults to explicitly setting build_dir to `.`, which also puts all the intermediate files in the current directory.  If one wants these files to be hidden in a build dir, one can set `let g:vimtex_compiler_latexrun = {'build_dir': 'latex.out'}`, but then vimtex's viewer interface opens the pdf at `latex.out/foo.pdf` rather than the (identical) `./foo.pdf`.  This is mostly harmless, except that I often first open the pdf (in the "top" directory) e.g. for proofreading, note that I want to make some changes, open vim and start editing, and then vimtex opens a second pdf file (in the "latex.out" directory), which is mildly annoying.

### Steps to reproduce

minimal.vim:
```vim
set nocompatible
silent! call plug#begin()  " using vim-plug, or the plugin manager of your choice
Plug 'lervag/vimtex'
let g:vimtex_compiler_method = 'latexrun'
let g:vimtex_compiler_latexrun = {'build_dir': 'latex.out'}  " with or without this line
call plug#end()
```
minimal.tex as in the example.

Compile.

### Expected behavior

vimtex opens `./minimal.pdf` (which is always created, regardless of whether `-O somedir` is passed to latexrun), not `./latex.out/minimal.pdf`.

### Actual behavior

Either all the intermediate files end up in the current directory, or the "wrong" pdf is opened.

### Do you use a latexmkrc file?

No.

### VimtexInfo

```yaml
System info:
  OS: Arch Linux
  Vim version: VIM 8.2 (1-4464)
  Has clientserver: true
  Servername: undefined (vim started without --servername)

VimTeX project: test
  base: test.tex
  root: /tmp/foo
  tex: /tmp/foo/test.tex
  main parser: current file verified
  document class: minimal
  compiler: latexrun
    engine: pdflatex
    options:
      --verbose-cmds
      --latex-args="-synctex=1"
    build_dir: latex.out
    job: 
      jobid: process 148040 dead
      output: /tmp/vfUyRJZ/0
      cmd: latexrun --verbose-cmds --latex-args="-synctex=1" --latex-cmd pdflatex -O latex.out 'test.tex'
  viewer: General
    job: 
      pid: 148043
      cmd: xdg-open '/tmp/foo/latex.out/test.pdf'
  qf method: LaTeX logfile
```
