### ISSUE TITLE
Mathzone detection fails sometimes (scrolling fixes/produces the bug)

### ISSUE THREAD

**Issue by atticus-sullivan** [lervag/vimtex#2352]
### Description

Hello,

sometimes the detection of mathzones fails (I only experienced this in large documents, my current one has ~400 lines).
Actually the problem fixes itself temporarily if scrolling a bit in the document (but arises after some scrolling as well). For the major part I see this in the highlighting of my written text (this would be unpleasant but ok) and in the math specific behavior of my snippets (this is annoying, since I use some autotriggering ones for math mode). 

### Steps to reproduce

[nvimrc-min.txt](https://github.com/lervag/vimtex/files/8218850/nvimrc-min.txt)
[master-testing.txt](https://github.com/lervag/vimtex/files/8218854/master-testing.txt)
1. Rename `master-testing.txt` to `xxx.tex` so that it is detected as latex file
2. Scrolling down to the bottom already does the trick for me (showing the problem). See for yourself
![Peek 2022-03-10 00-23](https://user-images.githubusercontent.com/60581958/157556019-6ea6b44b-07b5-4b43-86ea-7c7aff6f841d.gif)
I use `page down/up` here so don't get confused with the scrolling.
![Untitled](https://user-images.githubusercontent.com/60581958/157556037-e4f42ba6-498f-4ef2-81a0-77164c590be0.png)
because of the minimal `vimrc` one can't see that good the difference between math mode and normal mode, so maybe it's easier to focus on the red highlighted `\end{array}` lines.

### Expected behavior

That math/normal mode is detected correctly.

### Actual behavior

That math/normal mode is **not** detected correctly.

## My thoughts
I'm not quite sure if this really is a bug or if the problem really is the big size of the file (though ~400 lines doesn't seem that big). Due to the fact that this is fixed/produced by just scrolling around maybe the problem really is just that some buffer in the syntax thing is too small for a document containing much math with nested braces etc (my whole file consists of much math stuff mixed with some normal text as it is supposed to be some sort of formulary (collection of formula)).
If this is the case, is there a way to increase this buffer? (this most probable will make things slower, but if its necessary for some documents it would make sense to at lease set the size for such troubling documents manually)

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Arch Linux
  Vim version: NVIM v0.6.1
  Has clientserver: true
  Servername: /tmp/nvimWFMPJm/0

VimTeX project: master-testing
  base: master-testing.tex
  root: /home/lukas
  tex: /home/lukas/master-testing.tex
  main parser: current file verified
  document class: scrartcl
  packages: amsmath amssymb babel booktabs circuitikz csquotes fontspec graphicx hyperref ltxtable mathtools multicol nicematrix pgfkeys pgfplots scrlayer-scrpage tabularx tikz todo unicode-m
  compiler: latexmk
    engine: -lualatex
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
```
