### ISSUE TITLE
Weird "gqap" results when formatting multibyte text.

### ISSUE THREAD

**Issue by wenpengy** [lervag/vimtex#2357]
### Description

1. When formatting pure multibyte text, the following message appears: `VimTex: Formatting of selected text failed!` The text was not formatted.
2.  When formatting text that contains multibyte characters, `gq` command always break lines after English spaces.

The option of formatting are:

```vim
set textwidth=78
set formatoptions=tcqmBj1ron
```

### Steps to reproduce

```tex
\documentclass{paper}

\begin{document}

单词单词单词单词单词单词单词单词单词单词单词单词单词 a 单词单词单词单词单词单词单词单词单词单词单词单词单词 a 单词 ab 单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词 单词单词单词单词单词单词单词单词

单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词

\end{document}
```

### Expected behavior

```tex
\documentclass{paper}

\begin{document}

单词单词单词单词单词单词单词单词单词单词单词单词单词 a单词单词单词单词单词单词
单词单词单词单词单词单词单词 a 单词 ab单词单词单词单词单词单词单词单词单词单词
单词单词单词单词单词单词单词单词单词单词单词单词单词单词

单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单
词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词
单词单词单词单词单词单词单词单词单词单词单词单词

\end{document}
```

### Actual behavior

```tex
\documentclass{paper}

\begin{document}

单词单词单词单词单词单词单词单词单词单词单词单词单词 a
单词单词单词单词单词单词单词单词单词单词单词单词单词 a 单词 ab 
单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词

单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词单词 (failed)

\end{document}
```

### Do you use a latexmkrc file?

Yes

### VimtexInfo

```yaml
System info:
  OS: YWP-T460P (Microsoft Windows 10 רҵ°æ)
  Vim version: VIM 8.2 (1-2825)
  Has clientserver: true
  Servername: GVIM

VimTeX project: main
  base: main.tex
  root: E:/teset
  tex: E:/teset/main.tex
  main parser: current file verified
  document class: paper
  packages: amsgen amstext array color epstopdf-base etoolbox expl3 graphics graphicx iftex infwarerr keyval l3keys2e ltxcmds pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfrcs pgfsys siunitx tikz translations trig xcolor
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -shell-escape
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
