### ISSUE TITLE
Compilation Failed!

### ISSUE THREAD

**Issue by johnclev23** [lervag/vimtex#2359]
### Description

Whenever I attempt to compile anything, it fails.

### Steps to reproduce

algebra.tex:
```
documentclass{article}
\begin{document}
proof goes here
\end{document}
```

.vimrc:
```
call plug#begin()

Plug 'lervag/vimtex'
let g:texflavor='latex'
let g:vimtex_view_method='zathura'
let g:vimtex_quickfix_mode=0
set conceallevel=1
let g:texconceal='abdmg'

Plug 'arcticicestudio/nord-vim' 
Plug 'itchyny/lightline.vim'

set laststatus=2
set noshowmode
      
Plug 'preservim/nerdtree'
      
call plug#end()

let g:lightline = {
    \ 'colorscheme': 'nord',
    \ }
colorscheme nord

"removes toolbar
set go-=T
set go-=m

```

Opening the tex file with vim and pressing \ll results in an error.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 21.10
  Vim version: VIM 8.2 (1-4625)
  Has clientserver: false

VimTeX project: Algebra
  base: Algebra.tex
  root: /home/john/Documents/LaTeX
  tex: /home/john/Documents/LaTeX/Algebra.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
