### ISSUE TITLE
Zathura reverse search don't work for gvim -v

### ISSUE THREAD

**Issue by gzqx** [lervag/vimtex#2363]
### Description

Enjoying vimtex for years, thank you for developing such an impressive project.

## Current question

As mentioned in origin problem, there is a temporary window appears and disappears when backward searching, can this behavior to be configured to be done at background?

## Origin main problem is solved, apologies for not examining carefully before posting
I use `gvim -v` for vim in terminal as native vim doesn't come with x clipboard support.
Forward search (vim to zathura) work perfectly.
Backward search (zathura to vim) works on gvim with GUI window.
However, when I use `gvim -v` in terminal, it does not work.
In both backward search situation, a small blank gvim window is opened and closed immediately, difference is after it flashes, gvim can jump to the <c-click> place while `gvim -v` can't.

BTW, is this flash window necessary and is there a way to make it background?

OS: Fedora Plasma 35

### Steps to reproduce

Example of minimal test files is sufficient without modification. 

### Expected behavior

jump to location as in GUI gvim.

### Actual behavior

Nothing happens.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Linux 5.16.15-201.fc35.x86_64
  Vim version: VIM 8.2 (1-4621)
  Has clientserver: true
  Servername: undefined (vim started without --servername)

VimTeX project: minimal
  base: minimal.tex
  root: /home/<username>/try/vimtex
  tex: /home/<username>/try/vimtex/minimal.tex
  main parser: current file verified
  document class: minimal
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
