### ISSUE TITLE
regression: two zathura launched after starting compiling

### ISSUE THREAD

**Issue by MoetaYuko** [lervag/vimtex#2366]
### Description

After committing https://github.com/lervag/vimtex/commit/3b4a5a195b9b1cc4015f50e3a19b079c33855c99, two zathura get launched after starting compiling w/ `<localleader>lv` in vim8, but nvim works fine. I guess the regex `^` needs to be applied to https://github.com/lervag/vimtex/blob/3c14f6912318ac3d92d32eca7d66c7c1c4f3e92c/autoload/vimtex/compiler/_template.vim#L319 as well?

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Arch Linux
  Vim version: VIM 8.2 (1-4651)
  Has clientserver: true
  Servername: VIM

VimTeX project: t
  base: t.tex
  root: /home/xxx/tmp
  tex: /home/xxx/tmp/t.tex
  main parser: current file
  document class: 
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -shell-escape
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
