### ISSUE TITLE
Pressing <F8> returns 'Unknown function: vimtex#delim#add_modifiers'

### ISSUE THREAD

**Issue by angryluck** [lervag/vimtex#2370]
### Description

It seems that the function adding modifiers to delimiters (eg \left \right) does not exists. I looked through vimtex/autoload/vimtex/delim.vim, and found the line

```
nnoremap <silent><buffer> <plug>(vimtex-delim-add-modifiers) 
        \ :<c-u>call vimtex#delim#add_modifiers()<cr>
endfunction
```

but 'vimtex#delim#add_modifers', or anything close to it is not mentioned anywhere in the file apart from here.

### Steps to reproduce

1. Open a tex-file
2. Write ()
3. Press \<F8\> (or whatever might be bound to <plug>(vimtex-delim-add-modifiers) )

### Expected behavior

() is changed to \left( \right)

### Actual behavior

Commandline states: "Unknown function: vimtex#delim#add_modifiers"

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Manjaro Linux
  Vim version: VIM 8.2 (1-4464)
  Has clientserver: true
  Servername: undefined (vim started without --servername)

VimTeX project: projectcisinski
  base: projectcisinski.tex
  root: /home/angryluck/Documents/projectBlok3/projectCisinski
  tex: /home/angryluck/Documents/projectBlok3/projectCisinski/projectcisinski.tex
  main parser: latexmain specifier
  document class: article
  packages: amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm babel bbm enumitem epstopdf-base euscript geometry graphics graphicx grfext iftex ifvtex infwarerr inputenc keyval kvdefinekeys kvoptions kvsetkeys ltxcmds pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfrcs pgfsys tikz tikz-cd trig xcolor
  source files:
    projectcisinski.tex
    notation.tex
    shs.tex
    kh.tex
    6functor.tex
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
