### ISSUE TITLE
`]]` doesn't close `document` environment

### ISSUE THREAD

**Issue by Skillmon** [lervag/vimtex#2371]
### Description

The `]]` key binding to automatically close the current environment doesn't work with the `document` environment.

### Steps to reproduce

Create a document up to the following point, then, while in insert mode, press `]]` on the last line.

```tex
\documentclass{article}

\begin{document}

```

### Expected behavior

`\end{document}` should be inserted

### Actual behavior

Nothing happens.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Arch Linux
  Vim version: NVIM v0.6.1
  Has clientserver: true
  Servername: /tmp/nvimYSar60/0

VimTeX project: ekvpparser
  base: ekvpparser.tex
  root: /home/archie/tmp/testtex
  tex: /home/archie/tmp/testtex/ekvpparser.tex
  main parser: current file
  document class: 
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
