### ISSUE TITLE
Using build_dir causes compilation to fail

### ISSUE THREAD

**Issue by medwatt** [lervag/vimtex#2372]
### Description

I usually have the compilation files in a build directory to avoid clutter. My vimtex setup is shown below.

```vim
let g:vimtex_compiler_latexmk = {
        \ 'build_dir' : 'out',
        \ 'callback' : 1,
        \ 'continuous' : 1,
        \ 'executable' : 'latexmk',
        \ 'hooks' : [],
        \ 'options' : [
        \   '-verbose',
        \   '-shell-escape',
        \   '-file-line-error',
        \   '-synctex=1',
        \   '-interaction=nonstopmode',
        \ ],
        \}
```

I am trying to compile a file that uses the minted package. With the above setup, vimtex gives the error `Package minted Error: Missing Pygments output; \inputminted was`. Now, if I remove the `build_dir` lines, the file compiles fine. Do you know why this is happening?

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Manjaro Linux
  Vim version: NVIM v0.7.0-dev+1400-g233014f92
  Has clientserver: true
  Servername: /tmp/nvimOMmD6u/0

VimTeX project: a
  base: a.tex
  root: /home/medwatt/coding/test
  tex: /home/medwatt/coding/test/a.tex
  main parser: current file verified
  document class: article
  packages: minted
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -shell-escape
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    build_dir: out
    callback: 1
    continuous: 1
    executable: latexmk
    job:
      jobid: 7
      output: /tmp/nvimOMmD6u/1
      cmd: max_print_line=2000 latexmk -verbose -shell-escape -file-line-error -synctex=1 -interaction=nonstopmode -pdf -outdir=out -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'a.tex'
      pid: 55907
  viewer: General
  qf method: LaTeX logfile
```
