### ISSUE TITLE
Calling Zathura from Vimtex on Mac

### ISSUE THREAD

**Issue by marc-brouard** [lervag/vimtex#2373]
### Description

I am trying to setup Zathura to be called from NeoVim VimTex. But Zathura does not open.

When I try and run the `cmd_start` from the terminal I get the errors described below in "Actual Behaviour".

I have checked dbus and it seems to be working.

I know that this may not be a VimTex issues but would someone be able to suggest anything as I am out of ideas. Even if you could suggest somewhere else more appropiate to ask this question

### Steps to reproduce

minimal.vim
```vim
set nocompatible
let &runtimepath  = '~/.vim/bundle/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable
let g:vimtex_view_method = 'zathura'
```

minimal.tex
```tex
\documentclass{minimal}
\begin{document}
Hello world!
\end{document}
```

1. `nvim -u minimal.vim minimal.tex`
2. Compile with `:VimtexCompile`
3. Get `:VimtexInfo`
4. Copy `start_cmd`
5. Run `start_cmd` in terminal

### Expected behavior

I would expect Zathura to load the PDF

### Actual behavior

```
❯ zathura  -x "/usr/local/Cellar/neovim/0.6.1/bin/nvim --headless -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 1:1:'minimal.tex' 'build/minimal.pdf'&
[1] 79854
error: Could not connect to session bus: Cannot autolaunch D-Bus without X11 $DISPLAY
error: Got no usable data from SyncTeX or D-Bus failed in some way.
[1]  + exit 255   zathura -x  --synctex-forward 1:1:'minimal.tex' 'build/minimal.pdf'
```

### Do you use a latexmkrc file?

Yes

### VimtexInfo

```yaml
System info:
  OS: macOS 11.6.4 (20G417)
  Vim version: NVIM v0.6.1
  Has clientserver: true
  Servername: /var/folders/nv/3s2f_8nj0x90xd827kb05cmm0000gn/T/nvimJaNtzl/0

VimTeX project: minimal
  base: minimal.tex
  root: /Users/marcbrouard/temp
  tex: /Users/marcbrouard/temp/minimal.tex
  main parser: current file verified
  document class: minimal
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    build_dir: ./build
    callback: 1
    continuous: 1
    executable: latexmk
    job:
      jobid: 6
      output: /var/folders/nv/3s2f_8nj0x90xd827kb05cmm0000gn/T/nvimJaNtzl/1
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -outdir=./build -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler
      pid: 77596
  viewer: Zathura
    xwin id: Failed creating new xdo instance.
    cmd_start: zathura  -x "/usr/local/Cellar/neovim/0.6.1/bin/nvim --headless -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 1:1:'minimal.tex' 'build/minimal.pdf'&
  qf method: LaTeX logfile
```
