### ISSUE TITLE
Backtick shortcuts for greek letters broken under nvim 0.7.0

### ISSUE THREAD

**Issue by raw-bacon** [lervag/vimtex#2374]
### Description

With nvim 0.6.*, typing `` `a`` would expand to `\alpha`. This is no longer the case with nvim 0.7.0.

### Steps to reproduce

1. Make sure to have nvim 0.7.0 installed.
2. Open the default `minimal.tex` file by means of `nvim minimal.tex` (any configuration of nvim including the vimtex plugin should work fine).
3. After `Hello world!`, type ``$`a$``.

### Expected behavior

I expect that ``$`a$`` expands to `$\alpha$`.

### Actual behavior

However, no expansion happens, and the line is ``$`a$``.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Arch Linux
  Vim version: NVIM v0.7.0
  Has clientserver: true
  Servername: /tmp/nvim3yUuBk/0

VimTeX project: minimal
  base: minimal.tex
  root: /home/levi/minimal
  tex: /home/levi/minimal/minimal.tex
  main parser: current file
  document class: 
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 16
      output: /tmp/nvim3yUuBk/1
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'minimal.tex'
      pid: 3473
  viewer: Zathura
    xwin id: 0
    cmd_start: zathura -x "/usr/bin/nvim --headless -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 1:1:'/home/levi/minimal/minimal.tex'  '/home/levi/minimal/minimal.pdf'&
  qf method: LaTeX logfile
```
