### ISSUE TITLE
`g:vimtex_indent_list` still active although the list is empty

### ISSUE THREAD

**Issue by TornaxO7** [lervag/vimtex#2375]
### Description

I have the following settting in my `ftplugin/tex/settings.vim`:

```vim
let g:vimtex_indent_lists = []
```

Now if I'm inside an `enumerate` environment and press `<CR>`, then the `\item` is still added to the next line.

### Steps to reproduce

Use this as your `~/.config/nvim/init.vim`:

```vim
set nocompatible
let &runtimepath  = '~/.vim/bundle/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable

let g:vimtex_indent_lists = []
```

open up a new latex file with the following template:

```tex
\documentclass{minimal}
\begin{document}
\begin{enumerate}
\end{enumerate}

\end{document}
```

Go to the line which I marked with `% your cursor should be here now` and press your Return-key (`<CR>`).

### Expected behavior

Nothing should be added in a new line if I'm in an `enumerate`.

### Actual behavior

`\item` is added to the new line in an `enumerate` environment.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Linux 5.17.3-arch1-1
  Vim version: NVIM v0.8.0-dev+3-g3f2e9298bd
  Has clientserver: true
  Servername: /tmp/nvimN5azpf/0

VimTeX project: Document
  base: Document.tex
  root: /windows/Latex_Sandbox
  tex: /windows/Latex_Sandbox/Document.tex
  main parser: current file verified
  document class: scrartcl
  packages: amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm babel etoolbox expl3 fontenc footmisc inputenc keyval scrbase scrkbase scrlfile scrlfile-hook scrlogo tocbasic tocloft typearea xparse xpatch
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
      -logfilewarninglist
      -shell-escape
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
