### ISSUE TITLE
`\begin{minted}` does not get proper syntax highlighting

### ISSUE THREAD

**Issue by awa5114** [lervag/vimtex#2376]
### Description

I just intalled vimtex using vim-plug on my Windows machine. I noticed that the syntax highlighting is strange when I'm beginning a `minted` environment:

![image](https://user-images.githubusercontent.com/24267968/164719447-9cfca8c2-c821-4067-a591-f2e9b8ff8966.png)

### Steps to reproduce

1. install vim using Chocolatey on Windows
2. Modify vimrc file as follows:

    ```vim
    set number
    set belloff=all
    set backspace=indent,eol,start
    set expandtab
    set tabstop=4
    set shiftwidth=4
    set autoindent
    set ruler
    syntax on

    call plug#begin()
    Plug 'lervag/vimtex'
    call plug#end()
    ```

3. install vimtex plugin using `plug.vim`
4. Create following file and open using vim

    ```tex
    \documentclass{article}
    \usepackage[outputdir=notes]{minted}
    \usepackage{fontspec}

    \setmonofont{Courier New}

    \begin{document}

    \begin{listing}[H]
        \definecolor{bg}{rgb}{0.95, 0.95, 0.95}
        \begin{minted}[bgcolor=bg, gobble=8, linenos]{Python}
            def print_hello():
                print("Hello world, Goodbye")

            if __name__=="__main__":
                print_hello()
        \end{minted}
        \caption{test}
        \label{test}
    \end{listing}

    \end{document}
    ```

### Expected behavior

That `\begin{minted}` on line 12 is properly highlighted.

### Actual behavior

`\begin{minted}` on line 12 is not properly highlighted.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: LAPTOP-JUAE71NA (Microsoft Windows 11 Home)
  Vim version: VIM 8.2 (1-4036)
  Has clientserver: true
  Servername: VIM

VimTeX project: decorator
  base: decorator.tex
  root: C:\Users\amine\Desktop\TEMP\head_first_design_patterns\notes
  tex: C:\Users\amine\Desktop\TEMP\head_first_design_patterns\notes\decorator.tex
  main parser: current file verified
  document class: article
  packages: fontspec minted
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
