### ISSUE TITLE
Default syntax highlighting for `\emph`

### ISSUE THREAD

**Issue by awa5114** [lervag/vimtex#2378]
### Description

I find the default `\emph` highlighting to be very distracting
in VimTeX. Can I change it?

![image](https://user-images.githubusercontent.com/24267968/165768914-0ded1a28-6e21-49b2-ba7b-16f90a2e8364.png)

### Steps to reproduce

1. Install vimtex using chocolatey with powershell
2. type `\emph{blablabla}`

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: LAPTOP-JUAE71NA (Microsoft Windows 11 Home)
  Vim version: VIM 8.2 (1-4036)
  Has clientserver: true
  Servername: VIM

VimTeX project: decorator
  base: decorator.tex
  root: C:\Users\amine\Desktop\TEMP\head_first_design_patterns\notes
  tex: C:\Users\amine\Desktop\TEMP\head_first_design_patterns\notes\decorator.tex
  main parser: current file verified
  document class: article
  packages: fontspec minted
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
