### ISSUE TITLE
Yet another \item indentation error

### ISSUE THREAD

**Issue by hamdav** [lervag/vimtex#2382]
### Description

I've tried checking out the other \item indentation error issues but they are either claimed to be resolved or not quite the same as this one, so I'm making a new one.
The problem is this: I have a couple of lines hastily written down like so:

    the first item
    the second item
    and so on

And then when I later go to clean up what I've written, I end up with

    \begin{itemize}
        \item the first item
            \item the second item
                 \item the third item
    \end{itemize}

What I am doing is first putting the environment around the lines that will become the list, and then insert \item to the front of the line. If I from the beginning write the items in order then the indentation becomes correct. `=ie` does fix it but it's annoying to have to do that all the time.

### Steps to reproduce

Minimal init.vim:

    all plug#begin('~/.config/nvim/plugged')
    Plug 'lervag/vimtex'
    call plug#end()

1. Open a tex document
2. write two lines
3. surround in `\begin{itemize}` / `\end{itemize}`
4. Insert `\item` at the beginning of the two lines
The first one is correctly indented, the second is indented too much

### Expected behavior

All \items being indented one tab / four spaces

### Actual behavior

Indent level increasing with each \item

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
System info:
  OS: macOS 11.2.3 (20D91)
  Vim version: NVIM v0.6.1
  Has clientserver: true
  Servername: /var/folders/mn/7wv53fcj6m95stzmb3nq73bw0000gn/T/nvimSyp5Hp/0

VimTeX project: main
  base: main.tex
  root: /Users/davidhambraeus/Hive/Courses/QIP_II/Excercises/ps8_paper_reading
  tex: /Users/davidhambraeus/Hive/Courses/QIP_II/Excercises/ps8_paper_reading/main.tex
  main parser: current file verified
  document class: article
  packages: aligned-overset amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm a
  source files:
    main.tex
    packages.tex
    mathCommands.tex
    textSettings.tex
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
