### ISSUE TITLE
Can't get inverse search working in Okular

### ISSUE THREAD

**Issue by MetriC-DT** [lervag/vimtex#2383]
### Description

For neovim, the docs indicated that using `nvim --headless -c "VimtexInverseSearch %l '%f'"` was sufficient to perform inverse searches. However, placing this line in Okular "Editor Options" section does not make inverse search work.

Previously, using nvr, with `nvr --remote-silent +%l %f` worked.

### Steps to reproduce

Put `nvim --headless -c "VimtexInverseSearch %l '%f'"` in Okular's "Editor Options" section.

### Expected behavior

Inverse Search works

### Actual behavior

Inverse search doesn't work

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Linux 5.17.4-200.fc35.x86_64
  Vim version: NVIM v0.8.0-dev+101-ga23440bf7
  Has clientserver: true
  Servername: /tmp/nvimAhB9UD/0

VimTeX project: test
  base: test.tex
  root: /home/derickwtseng/.config/nvim/test
  tex: /home/derickwtseng/.config/nvim/test/test.tex
  main parser: current file verified
  document class: article
  packages: adjcalc adjustbox amsbsy amsfonts amsgen amsmath amsopn amssymb amstext array chemformula collectbox enumitem epstopdf-base expl3 geometry graphics graphicx ifoddpage iftex ifthen ifvtex inputenc keyval l3keys2e listings lstmisc multicol nicefrac pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfrcs pgfsys siunitx textcomp tikz translator trig trimclip url varwidth xcolor xfrac xkeyval xparse xparse-2020-10-01 xtemplate xurl
  compiler: latexmk
    engine: -pdf
    options:
      -pdf
      -interaction=nonstopmode
      -synctex=1
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 18
      output: /tmp/nvimAhB9UD/1
      cmd: max_print_line=2000 latexmk -pdf -interaction=nonstopmode -synctex=1 -pdf -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'test.tex'
      pid: 90112
  viewer: General
    job: 
      pid: 90115
      cmd: okular --unique file:'/home/derickwtseng/.config/nvim/test/test.pdf'\#src:25'/home/derickwtseng/.config/nvim/test/test.tex'
  qf method: LaTeX logfile
```
