### ISSUE TITLE
Skim viewer opens new window

### ISSUE THREAD

**Issue by avonmoll** [lervag/vimtex#2384]
### Description

Using the `vimtex_view_method = 'skim'`, a new Skim window opens, unless the associated output pdf is already open in a Skim instance or the Skim window is _on the current desktop_. Previously, if I had Skim already running (on another desktop with some other pdfs already opened in tabs), the output pdf would be opened as a tab in the existing Skim window.

Vimtex options:

```
let g:tex_flavor = 'latex'
let g:vimtex_compiler_method = 'latexmk'
let g:vimtex_view_method = 'skim'
let g:vimtex_view_skim_activate = 1
let g:vimtex_view_skim_sync = 1
```

### Steps to reproduce

1. (have Skim open already, but on another desktop)
2. `nvim -u minimal.vim minimal.tex`
3. `:VimtexCompile`

### Expected behavior

`minimal.pdf` is opened as a tab on the existing Skim window.

### Actual behavior

A new Skim window appears on the current desktop with a single tab containing `minimal.pdf`.

### Do you use a latexmkrc file?

Yes

### VimtexInfo

```yaml
System info:
  OS: macOS 11.6.5 (20G527)
  Vim version: NVIM v0.8.0-dev+2-g08a144912
  Has clientserver: true
  Servername: /var/folders/8s/1p9l6htd1ql9qm3xncp6mhjm0000gq/T/nvimYGeF7Q/0

VimTeX project: minimal
  base: minimal.tex
  root: /Users/user/---/---
  tex: /Users/user/---/---/minimal.tex
  main parser: current file verified
  document class: minimal
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    build_dir: build
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 6
      output: /var/folders/8s/1p9l6htd1ql9qm3xncp6mhjm0000gq/T/nvimYGeF7Q/1
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -outdir=build -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ?
      pid: 81154
  viewer: Skim
  qf method: LaTeX logfile
```
