### ISSUE TITLE
callback fails after compilation success or saving the .tex file

### ISSUE THREAD

**Issue by roao** [lervag/vimtex#2386]
### Description

Recently, I returned to write latex with vimtex, but I find I can't write latex with vimtex as before, because the callback doesn't work after compilation or saving the .tex file. I can callback mannually by `:echo vimtex#comiler#callback(2)`,  but I prefer it can callback automatically, just like previous. What happened in the newest vimtex?
I can reproduce the bug with example test file: `minimal.vim` and `minimal.tex` .
After compilation, when I can open minimal.pdf savely, the cmdline of neovim remains unchanged as show in image unless I type new commands in cmdline:

![image](https://user-images.githubusercontent.com/45995795/167272443-7e834350-f4c4-4795-b769-362e1a4eaed6.png)

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
System info:
  OS: 61F-THINKPAD (Microsoft Windows 10 专业版)
  Vim version: NVIM v0.7.0
  Has clientserver: true
  Servername: \\.\pipe\nvim-15048-0

VimTeX project: minimal
  base: minimal.tex
  root: C:\Users\61F\Desktop\shishi
  tex: C:\Users\61F\Desktop\shishi\minimal.tex
  main parser: current file verified
  document class: minimal
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 6
      output: C:\Users\61F\AppData\Local\Temp\nvimzePWKl\0
      cmd: set max_print_line=2000 & latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e "$compiling_cmd = ($compiling_cmd ? $compiling_cmd . ' ^& ' : '') . 'echo vimtex_compiler_callback_compiling'" -e "$success_cmd = ($success_cmd ? $success_cmd . ' ^& ' : '') . 'echo vimtex_compiler_callback_success'" -e "$failure_cmd = ($failure_cmd ? $failure_cmd . ' ^& ' : '') . 'echo vimtex_compiler_callback_failure'" "minimal.tex"
      pid: 3016
  viewer: General
  qf method: LaTeX logfile
```
