### ISSUE TITLE
Conceal on NeoVim not working

### ISSUE THREAD

**Issue by ignamartinoli** [lervag/vimtex#2388]
### Description

I tried to set the concealment as shown in [this guide](https://castel.dev/post/lecture-notes-1/) with the following entries in the package configuration file `~/.config/nvim/lua/plugins/vimtex.lua`:
```lua
local g = require 'utils'.g

g.tex_conceal = 'abdmg'
g.vimtex_view_method = 'zathura'
g.vimtex_toc_config = {
	name = 'ToC',
	layers = { 'content', 'todo', 'include' },
	show_help = false
}
```
After that I created a LaTeX file to try it out but unsuccessfully.

### Steps to reproduce

1. Open a LaTeX file with Neovim
2. Type:
```
\documentclass{article}

\usepackage{amsmath}

\begin{document}
	\section{A}
		\begin{align}
			\in \cdot
		\end{align}
\end{document}
```

### Expected behavior

Seeing the concealment

### Actual behavior

The concealment isn't working

### Do you use a latexmkrc file?

Yes

### VimtexInfo

```yaml
System info:
  OS: Gentoo Base System release 2.8
  Vim version: NVIM v0.8.0-dev+11-gd3121f1e6-dirty
  Has clientserver: true
  Servername: /tmp/nvimnv2zo3/0

VimTeX project: doe
  base: doe.tex
  root: /home/sicro/Code/LaTeX
  tex: /home/sicro/Code/LaTeX/doe.tex
  main parser: current file verified
  document class: article
  packages: amsmath
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    build_dir: output
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
