### ISSUE TITLE
Error detected while processing function vimtex#nvim#check_treesitter

### ISSUE THREAD

**Issue by SimonKvantdator** [lervag/vimtex#2389]
### Description

When opening a .tex file in neovim, I get an error message saying that "module 'vim.treesitter.highlighter'", "field package.preload['vim.treesitter.highlighter']", and a bunch of files are missing.

Sorry if this is not a vimtex problem!

### Steps to reproduce

Putting this code in my init.vim reproduces the error message:
let g:plugged_home = '~/.vim/plugged'
call plug#begin(g:plugged_home)
        Plug 'lervag/vimtex'
call plug#end()


### Expected behavior

_No response_

### Actual behavior

When opening a .tex file, I get the following error message:

Error detected while processing function vimtex#nvim#check_treesitter:
line    9:
E5105: Error while calling lua chunk: [string "<VimL compiled string>"]:1: module 'vim.treesitter.highlighter' not found:
no field package.preload['vim.treesitter.highlighter']
no file '/home/simonj/.config/nvim/lua/vim/treesitter/highlighter.lua'
no file '/home/simonj/.config/nvim/lua/vim/treesitter/highlighter/init.lua'
no file '/home/simonj/.vim/plugged/vimtex/lua/vim/treesitter/highlighter.lua'
no file '/home/simonj/.vim/plugged/vimtex/lua/vim/treesitter/highlighter/init.lua'
no file '/etc/xdg/xdg-i3/nvim/lua/vim/treesitter/highlighter.lua'
no file '/etc/xdg/xdg-i3/nvim/lua/vim/treesitter/highlighter/init.lua'
no file '/etc/xdg/nvim/lua/vim/treesitter/highlighter.lua'
no file '/etc/xdg/nvim/lua/vim/treesitter/highlighter/init.lua'
no file '/usr/share/kubuntu-default-settings/kf5-settings/nvim/lua/vim/treesitter/highlighter.lua'
no file '/usr/share/kubuntu-default-settings/kf5-settings/nvim/lua/vim/treesitter/highlighter/init.lua'
no file '/home/simonj/.local/share/nvim/site/lua/vim/treesitter/highlighter.lua'
no file '/home/simonj/.local/share/nvim/site/lua/vim/treesitter/highlighter/init.lua'
no file '/usr/share/i3/nvim/site/lua/vim/treesitter/highlighter.lua'
no file '/usr/share/i3/nvim/site/lua/vim/treesitter/highlighter/init.lua'
no file '/usr/local/share/nvim/site/lua/vim/treesitter/highlighter.lua'
no file '/usr/local/share/nvim/site/lua/vim/treesitter/highlighter/init.lua'
no file '/usr/share/nvim/site/lua/vim/treesitter/highlighter.lua'
no file '/usr/share/nvim/site/lua/vim/treesitter/highlighter/init.lua'
no file '/usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua'
no file '/usr/share/nvim/runtime/lua/vim/treesitter/highlighter/init.lua'
no file '/usr/share/nvim/runtime/pack/dist/opt/matchit/lua/vim/treesitter/highlighter.lua'
no file '/usr/share/nvim/runtime/pack/dist/opt/matchit/lua/vim/treesitter/highlighter/init.lua'
no file '/usr/share/nvim/site/after/lua/vim/treesitter/highlighter.lua'
no file '/usr/share/nvim/site/after/lua/vim/treesitter/highlighter/init.lua'
no file '/usr/local/share/nvim/site/after/lua/vim/treesitter/highlighter.lua'
no file '/usr/local/share/nvim/site/after/lua/vim/treesitter/highlighter/init.lua'
no file '/usr/share/i3/nvim/site/after/lua/vim/treesitter/highlighter.lua'
no file '/usr/share/i3/nvim/site/after/lua/vim/treesitter/highlighter/init.lua'
no file '/home/simonj/.local/share/nvim/site/after/lua/vim/treesitter/highlighter.lua'
no file '/home/simonj/.local/share/nvim/site/after/lua/vim/treesitter/highlighter/init.lua'
no file '/usr/share/kubuntu-default-settings/kf5-settings/nvim/after/lua/vim/treesitter/highlighter.lua'
no file '/usr/share/kubuntu-default-settings/kf5-settings/nvim/after/lua/vim/treesitter/highlighter/init.lua'
no file '/etc/xdg/nvim/after/lua/vim/treesitter/highlighter.lua'
no file '/etc/xdg/nvim/after/lua/vim/treesitter/highlighter/init.lua'
no file '/etc/xdg/xdg-i3/nvim/after/lua/vim/treesitter/highlighter.lua'
no file '/etc/xdg/xdg-i3/nvim/after/lua/vim/treesitter/highlighter/init.lua'
no file '/home/simonj/.vim/plugged/vimtex/after/lua/vim/treesitter/highlighter.lua'
no file '/home/simonj/.vim/plugged/vimtex/after/lua/vim/treesitter/highlighter/init.lua'
no file '/home/simonj/.config/nvim/after/lua/vim/treesitter/highlighter.lua'
no file '/home/simonj/.config/nvim/after/lua/vim/treesitter/highlighter/init.lua'
no file './vim/treesitter/highlighter.lua'
no file '/usr/share/luajit-2.1.0-beta3/vim/treesitter/highlighter.lua'
no file '/usr/local/share/lua/5.1/vim/treesitter/highlighter.lua'
no file '/usr/local/share/lua/5.1/vim/treesitter/highlighter/init.lua'
no file '/usr/share/lua/5.1/vim/treesitter/highlighter.lua'
no file '/usr/share/lua/5.1/vim/treesitter/highlighter/init.lua'
no file '/home/simonj/.config/nvim/lua/vim/treesitter/highlighter.so'
no file '/home/simonj/.vim/plugged/vimtex/lua/vim/treesitter/highlighter.so'
no file '/etc/xdg/xdg-i3/nvim/lua/vim/treesitter/highlighter.so'
no file '/etc/xdg/nvim/lua/vim/treesitter/highlighter.so'
no file '/usr/share/kubuntu-default-settings/kf5-settings/nvim/lua/vim/treesitter/highlighter.so'
no file '/home/simonj/.local/share/nvim/site/lua/vim/treesitter/highlighter.so'
no file '/usr/share/i3/nvim/site/lua/vim/treesitter/highlighter.so'
no file '/usr/local/share/nvim/site/lua/vim/treesitter/highlighter.so'
no file '/usr/share/nvim/site/lua/vim/treesitter/highlighter.so'
no file '/usr/share/nvim/runtime/lua/vim/treesitter/highlighter.so'
no file '/usr/share/nvim/runtime/pack/dist/opt/matchit/lua/vim/treesitter/highlighter.so'
no file '/usr/share/nvim/site/after/lua/vim/treesitter/highlighter.so'
no file '/usr/local/share/nvim/site/after/lua/vim/treesitter/highlighter.so'
no file '/usr/share/i3/nvim/site/after/lua/vim/treesitter/highlighter.so'
no file '/home/simonj/.local/share/nvim/site/after/lua/vim/treesitter/highlighter.so'
no file '/usr/share/kubuntu-default-settings/kf5-settings/nvim/after/lua/vim/treesitter/highlighter.so'
no file '/etc/xdg/nvim/after/lua/vim/treesitter/highlighter.so'
no file '/etc/xdg/xdg-i3/nvim/after/lua/vim/treesitter/highlighter.so'
no file '/home/simonj/.vim/plugged/vimtex/after/lua/vim/treesitter/highlighter.so'
no file '/home/simonj/.config/nvim/after/lua/vim/treesitter/highlighter.so'
no file './vim/treesitter/highlighter.so'
no file '/usr/local/lib/lua/5.1/vim/treesitter/highlighter.so'
no file '/usr/lib/x86_64-linux-gnu/lua/5.1/vim/treesitter/highlighter.so'
no file '/usr/local/lib/lua/5.1/loadall.so'
no file '/home/simonj/.config/nvim/lua/vim.so'
no file '/home/simonj/.vim/plugged/vimtex/lua/vim.so'
no file '/etc/xdg/xdg-i3/nvim/lua/vim.so'
no file '/etc/xdg/nvim/lua/vim.so'
no file '/usr/share/kubuntu-default-settings/kf5-settings/nvim/lua/vim.so'
no file '/home/simonj/.local/share/nvim/site/lua/vim.so'
no file '/usr/share/i3/nvim/site/lua/vim.so'
no file '/usr/local/share/nvim/site/lua/vim.so'
no file '/usr/share/nvim/site/lua/vim.so'
no file '/usr/share/nvim/runtime/lua/vim.so'
no file '/usr/share/nvim/runtime/pack/dist/opt/matchit/lua/vim.so'
no file '/usr/share/nvim/site/after/lua/vim.so'
no file '/usr/local/share/nvim/site/after/lua/vim.so'
no file '/usr/share/i3/nvim/site/after/lua/vim.so'
no file '/home/simonj/.local/share/nvim/site/after/lua/vim.so'
no file '/usr/share/kubuntu-default-settings/kf5-settings/nvim/after/lua/vim.so'
no file '/etc/xdg/nvim/after/lua/vim.so'
no file '/etc/xdg/xdg-i3/nvim/after/lua/vim.so'
no file '/home/simonj/.vim/plugged/vimtex/after/lua/vim.so'
no file '/home/simonj/.config/nvim/after/lua/vim.so'
no file './vim.so'
no file '/usr/local/lib/lua/5.1/vim.so'
no file '/usr/lib/x86_64-linux-gnu/lua/5.1/vim.so'
no file '/usr/local/lib/lua/5.1/loadall.so'

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:                                                                                                                                                                                                       
  OS: Ubuntu 20.04.4 LTS                                                                                                                                                                                           
  Vim version: NVIM v0.4.3                                                                                                                                                                                         
  Has clientserver: true                                                                                                                                                                                           
  Servername: /tmp/nvimPKMlks/0                                                                                                                                                                                    
                                                                                                                                                                                                                   
VimTeX project: main                                                                                                                                                                                               
  base: main.tex                                                                                                                                                                                                   
  root: /home/simonj/Documents/dagbok_2022                                                                                                                                                                         
  tex: /home/simonj/Documents/dagbok_2022/main.tex                                                                                                                                                                 
  main parser: recursive search                                                                                                                                                                                    
  document class: report                                                                                                                                                                                           
  packages: aligned-overset amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm array atbegshi atveryend auxhook babel bigintcalc bitset braket calc cancel caption caption3 cleveref color csquotes datet
  source files:                                                                                                                                                                                                    
    main.tex                                                                                                                                                                                                       
    preamble/preamble.tex                                                                                                                                                                                          
    preamble/my_commands.tex                                                                                                                                                                                       
    include/v8.tex                                                                                                                                                                                                 
    include/v10.tex                                                                                                                                                                                                
    include/v11.tex                                                                                                                                                                                                
    include/v12.tex                                                                                                                                                                                                
    include/v13.tex                                                                                                                                                                                                
    include/v14.tex                                                                                                                                                                                                
    include/v15.tex                                                                                                                                                                                                
    include/v17.tex                                                                                                                                                                                                
    include/v19.tex                                                                                                                                                                                                
  compiler: latexmk                                                                                                                                                                                                
    engine: -pdf                                                                                                                                                                                                   
    options:                                                                                                                                                                                                       
      -verbose                                                                                                                                                                                                     
      -file-line-error                                                                                                                                                                                             
      -synctex=1                                                                                                                                                                                                   
      -interaction=nonstopmode                                                                                                                                                                                     
    callback: 1                                                                                                                                                                                                    
    continuous: 1                                                                                                                                                                                                  
    executable: latexmk                                                                                                                                                                                            
  viewer: General                                                                                                                                                                                                  
  qf method: LaTeX logfile
```
