### ISSUE TITLE
Zathura doesn't open when called

### ISSUE THREAD

**Issue by liamd101** [lervag/vimtex#2391]
### Description

I am trying to set up Zathura to view pdfs when working with Vimtex, but I cannot get it to work. When I run `:VimtexCompile` or `:VimtexView`, nothing seems to happen and I cannot figure out why. I am very new to this, so I apologize if I am missing something obvious.

### Steps to reproduce

minimal.vim
```
set nocompatible
let &runtimepath  = '~/.vim/plugged/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/plugged/vimtex/after'
filetype plugin indent on
syntax enable
let g:vimtex_view_method = 'zathura'
```
minimal.tex
```
\documentclass{minimal}

\begin{document}
Hello world!
\end{document}
```

1. vim -u minimal.vim minimal.tex
2. Compile with `\ll` or `:VimtexCompile`
3. Get VimtexInfo
4. `\lv` or `:VimtexView`

### Expected behavior

Zathura to open up with a pdf preview of the document.

### Actual behavior

Nothing happens.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 12.3.1 (21E258)
  Vim version: VIM 8.2 (1-3455)
  Has clientserver: true
  Servername: undefined (vim started without --servername)

VimTeX project: minimal
  base: minimal.tex
  root: /Users/liamdodds
  tex: /Users/liamdodds/minimal.tex
  main parser: current file verified
  document class: minimal
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: process 5030 run
      output: /var/folders/kc/pj12l0192gg4ljyhsk5y9w1h0000gn/T/v0Fason/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ;
      pid: 5030
  viewer: Zathura
    xwin id: Failed creating new xdo instance.
    cmd_start: zathura  -x "/usr/local/Cellar/macvim/8.2-172_1/MacVim.app/Contents/MacOS/Vim -T dumb --not-a-term -n -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward
  qf method: LaTeX logfile
```
```
