### ISSUE TITLE
Forward search fails to work (Neovim + Zathura on Linux over SSH)

### ISSUE THREAD

**Issue by llinfeng** [lervag/vimtex#2392]
### Description

I am new to compiling TeX documents on Linux OS, and wonder if the specific `latexmk` version and/or the MikTeX distribution may impact how forward search behave? After consulting [this issue](https://github.com/lervag/vimtex/issues/2255) for the minimum config that should work for Neovim + Tmux, I am experiencing:
* Perfectly functional backward search over SSH, with Ctrl-Click on a locally rendered Zathura window
* However, forward search keeps sending me to the first page in Zathura.

### Steps to reproduce

`min.vim` content:

```vim
" Need to source plug.vim to get things going.
" Use this bash command to fetch the file: "mkdir ~/.config/nvim/autoload/; curl  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim > ~/.config/nvim/autoload/plug.vim"
source ~/.config/nvim/autoload/plug.vim

call plug#begin('~/.vim/plugged')
    Plug 'lervag/vimtex'
call plug#end()

" let g:tex_flavor = 'latex'
let g:vimtex_view_method = 'zathura'
```

`min.tex` content:

```tex
\documentclass{minimal}
\begin{document}
Hello world!
\newpage
Hello world!
\newpage
Page 3
\newpage
Page 4
\end{document}
```

And, for Zathura, `~/.config/zathura/zathurarc` is left empty for this test.

**Setup**: I am accessing the Linux server using a WSL session on Win 10 machine. The SSH connection is established with `-Y` flag, permitting GUI programs to get rendered locally on the WSL machine. I will update this line when I verify how things behave with direct access to the Linux server.

Then, I followed the following steps to reproduce the problem.

1. `nvim --clean -u min.vim min.tex`,
2. Navigate to the line with "Page 3" in `min.tex`,
3. Compile, and view. (`\ll` and `:VimtexView`)

### Expected behavior

The Zathura window shall jump to Page 3. It should also highlight the corresponding line with text "Page 3"

### Actual behavior

Instead of jumping to Page 3, the first page is shown with `:VimtexView`. And, there is no highlight drawn on Page 3.

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
System info:
  OS: Linux Mint 20.2
  Vim version: NVIM v0.6.1
  Has clientserver: true
  Servername: /tmp/nvimPSG6PR/0

VimTeX project: min
  base: min.tex
  root: /home/llinfeng/tmp/min_VimTex_ForwardBackward
  tex: /home/llinfeng/tmp/min_VimTex_ForwardBackward/min.tex
  main parser: current file verified
  document class: minimal
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job:
      jobid: 10
      output: /tmp/nvimPSG6PR/1
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf 'min.tex'
      pid: 0
  viewer: Zathura
    xwin id: 12582915
    cmd_forward_search: zathura --synctex-forward 8:8:'min.tex' 'min.pdf'&
    cmd_start: zathura  -x "/usr/bin/nvim --headless -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 7:1:'min.tex'  qf method: LaTeX logfile
```
