### ISSUE TITLE
Error detected while processing function 83[30]..91[44]..92[14]..94:

### ISSUE THREAD

**Issue by slonik-az** [lervag/vimtex#2399]
### Description

When opening a LaTeX file in __read-only__ mode (with `gview`) and then opening table-of-contents by pressing `<localLeader>lt` the following error pops up:

```
Error detected while processing function 83[30]..91[44]..92[14]..94:
line 31:W10: Warning: Changing a readonly file
Press ENTER or type command to continue
```

After pressing enter the error message goes away and the ToC is displayed normally. Not critical but annoying.

When opening the same file in __read-write__ mode (with 'gvim') there is no errors getting the ToC.

I am using latest vimtex master (hash: `ef773236`) with MacVim-172 (8.2.3455) over MacOS-12.3.1 Monterey on MacBookPro-M1-Max.

### Expected behavior

No errors when opening table-of-contents

### Actual behavior

See above

### Do you use a latexmkrc file?

Yes (but it is irrelevant for this problem)

### VimtexInfo

```yaml
System info:
  OS: macOS 12.3.1 (21E258)
  Vim version: VIM 8.2 (1-3455)
  Has clientserver: true
  Servername: VIM1

VimTeX project: autodiff
  base: autodiff.tex
  root: /Users/leor/templates/latex/lr-article/06
  tex: /Users/leor/templates/latex/lr-article/06/autodiff.tex
  main parser: current file verified
  document class: article
  packages: algorithm algorithmicx algpseudocode aliasctr amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm array atbegshi-ltx atveryend-ltx auxhook biblatex bigintcalc bitset blx-case-expl3 booktabs calc cancel catchfile colortbl comment currfile delarray empheq enumitem epstopdf-base etexcmds etoolbox expl3 extarrows fancyhdr fancyvrb filehook filehook-2020 fix-cm float fontenc fontsetup fontspec fontspec-luatex framed fspdefault fvextra geometry gettitlestring graphics graphicx hycolor hyperref ifluatex ifplatform iftex ifthen ifvtex ifxetex infwarerr intcalc keyval kvdefinekeys kvoptions kvsetkeys l3keys2e lastpage letltxmacro libertinus-otf lineno logreq ltxcmds lualatex-math mathtools mhsetup microtype minted nameref nicefrac parseargs parskip pdfescape pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfrcs pgfsys pifont refcount relsize rerunfilecheck shellesc stringenc tabulary textcomp thm-amsthm thm-autoref thm-kv thm-listof thm-patch thm-restate thmtools tikz titlesec tocloft todonotes trig ulem unicode-math unicode-math-luatex uniquecounter upquote url xcolor xkeyval xparse xparse-2020-10-01 xspace xstring
  compiler: latexmk
    engine: -lualatex
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Skim
  qf method: LaTeX logfile
```
