### ISSUE TITLE
Recent upgrade breaks pdf view

### ISSUE THREAD

**Issue by a-figment** [lervag/vimtex#2400]
### Description

Recently upgraded vimtex and have since been experiencing problems with pdf live preview. Previously only used `zathura`, but after switching to `mupdf` (in hope of resolving the problem) I noticed many of the same issues. It is very difficult to reproduce all the bugs, which are all related to the live preview that gets generated/updated when editing .tex documents. Prior to a `:PlugUpgrade` a few days ago, none of these issues were observed.

### Steps to reproduce

0. Open a pdf file with `mupdf`. This should be a file not associated with vimtex.
1. vimx article.tex
2. `:VimtexCompile`
3. Edit  and `:w` on the file which is `\input{}` into `article.tex`.

article.tex:

```tex
\documentclass[12pt]{article}
\begin{document}
\tableofcontents
\input{article1.tex}
\end{document}
```

article1.tex:

```tex
\section{b section}
some text
% here is some more text $x = y$ % After `:VimtexCompile`ing from within `article.tex`, uncomment this line
```

### Expected behavior

Writing changes to a .tex file which is included in some other main.tex file should update the live preview generated by vimtex. 

### Actual behavior

Observe that the pdf preview doesn't update. `:VimtexStopAll` from `article.tex` and `:VimtexCompile` is required to observe every edit. On larger documents, it may also be the case that text is scrambled/missing from the pdf preview. 

Have also noticed other issues with files that have been opened with `mupdf` at the time ov `:VimtexCompile`ing. Often, these other files (which do not correspond to a `vimtex` session) will change the page which is currently being viewed.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Manjaro Linux
  Vim version: VIM 8.2 (1-4827)
  Has clientserver: true
  Servername: undefined (vim started without --servername)

VimTeX project: Chapter0
  base: article.tex
  main parser: current file
  document class: 
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: MuPDF
    xwin id: 0
  qf method: LaTeX logfile
```
