### ISSUE TITLE
Do not kill viewer sioyek when exiting vim

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#2401]
### Description

The pdf viewer [sioyek](https://github.com/ahrm/sioyek) recently introduced the possibility to open several windows per instance in commits https://github.com/ahrm/sioyek/commit/8096178ba7d5c172ce44d1f04d823ca1da402f75 and https://github.com/ahrm/sioyek/commit/2c508f5cc83a1816cabc9e9820fb27c93dce7ebd .

When I open a tex file with vimtex and view it in the current instance and then exit neovim, the single sioyek instance with all opened pdf files is closed.

### Steps to reproduce

1. `nvim -u minimal.vim minimal.tex`
2. compile pdf
3. open pdf viewer sioyek from vimtex
4. exit neovim

### Expected behavior

Only  close the corresponding sioyek window. If this is currently not possible, just leave sioyek running also with the pdf belonging to the tex file.

### Actual behavior

Sioyek instance with all opened pdf files is closed.

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
System info:
  OS: macOS 11.6.5 (20G527)
  Vim version: NVIM v0.8.0-dev+1527-g521e91e1c
  Has clientserver: true
  Servername: /var/folders/2z/bljkcy1j2cbf7l9zf3dk0nqc0000gn/T/nvimX1b6QN/0

VimTeX project: mueller-2013-fig-11.5
  base: mueller-2013-fig-11.5.tex
  root: /Users/kiryph/Projects/LaTeX/gu-4th-5th-steps
  tex: /Users/kiryph/Projects/LaTeX/gu-4th-5th-steps/mueller-2013-fig-11.5.tex
  main parser: current file
  document class: standalone
  packages: amsbsy amsgen amsmath amsopn amstext array calc chemgreek defpattern epstopdf-base expl3 fp fp-addons fp-basic fp-eqn fp-eval fp-exp fp-pas fp-random fp-snap fp-trigo fp-upn graphics graphicx gu ifluatex iftex ifthen keyval l3keys2e mhchem pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfrcs pgfsys pict2e preview shellesc tabularx tikz trig xcolor xkeyval xparse
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: sioyek
    job: 
      pid: 55360
      cmd: /Applications/sioyek.app/Contents/MacOS/sioyek --new-window  --inverse-search "/usr/local/bin/nvim --headless -c \"VimtexInverseSearch %2 '%1'\"" --forward-search-file '/Users/kiryph/Projects/LaTeX/gu-4th-5th-steps/mueller-2013-fig-11.5.tex' --forward-search-line 1 '/Users/kiryph/Projects/LaTeX/gu-4th-5th-steps/mueller-2013-fig-11.5.pdf'
    cmd_start: /Applications/sioyek.app/Contents/MacOS/sioyek --new-window  --inverse-search "/usr/local/bin/nvim --headless -c \"VimtexInverseSearch %2 '%1'\"" --forward-search-file '/Users/kiryph/Projects/LaTeX/gu-4th-5th-steps/mueller-2013-fig-11.5.tex' --forward-search-line 1 '/Users/kiryph/Projects/LaTeX/gu-4th-5th-steps/mueller-2013-fig-11.5.pdf'
  qf method: LaTeX logfile
```

### Minimal ~/.config/nvim/init.lua

```lua
vim.g.vimtex_view_method = 'sioyek'
vim.g.vimtex_view_sioyek_exe = '/Applications/sioyek.app/Contents/MacOS/sioyek'
```

### `minimal.tex`

```tex
\documentclass{minimal}
\begin{document}
Hello world!
\end{document}
```
