### ISSUE TITLE
`texArg` group doesnt work for syntax highlighting (nvim)

### ISSUE THREAD

**Issue by Weznon** [lervag/vimtex#2406]
### Description

I am trying to customize syntax highlighting colors as in https://github.com/lervag/vimtex/wiki/Syntax#customized-syntax-highlight. However, the `texArg` group does not appear to work when I attempt to change the color.

In the minimal example provided calling `:echo vimtex#syntax#stack()` while the cursor is on `\textul` and `test` gives `['texCmd']` and `['texArg']`, respectively.

### Steps to reproduce

1. nvim -u minimal.vim minimal.tex
minimal.vim
```
call plug#begin()
        Plug 'lervag/vimtex'
call plug#end()

function! s:hi(group, guifg, guibg, attr)
  let l:cmd = 'highlight ' . a:group
  if a:guifg != ''
    let l:cmd .= ' guifg=' . a:guifg
  endif
  if a:guibg != ''
    let l:cmd .= ' guibg=' . a:guibg
  endif
  if a:attr != ''
    let l:cmd .= ' gui='   . a:attr
  endif
  execute l:cmd
endfunction

let s:blue = '#0000FF'
let s:red = '#FF0000`

filetype plugin indent on
syntax enable
set termguicolors

call s:hi('texArg', s:blue, '', '')
call s:hi('texCmd', s:blue, '', '')
```
minimal.tex
```\documentclass{minimal}
\begin{document}
Hello world!
\textul{test}
\end{document}
```

### Expected behavior

I expect the `\textul` and `test` to be the same color

### Actual behavior

The `\textul` and `test` are not the same color.

![2022-06-03-1654281527](https://user-images.githubusercontent.com/14968011/171926149-3e9463a9-9576-4edb-b0c2-7a40353f81f4.png)

It does work for `texCmd` though, as changing to
```
call s:hi('texArg', s:red, '', '')
call s:hi('texCmd', s:red, '', '')
```
gives

![2022-06-03-1654281722](https://user-images.githubusercontent.com/14968011/171926669-a45ab6c9-3608-4324-85d2-056f889fdd00.png)

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Arch Linux
  Vim version: NVIM v0.7.0
  Has clientserver: true
  Servername: /tmp/nvimXeP3NM/0

VimTeX project: test
  base: test.tex
  root: /home/weznon/note/comalg
  tex: /home/weznon/note/comalg/test.tex
  main parser: current file verified
  document class: minimal
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
