### ISSUE TITLE
Syntax highlighting falsely marks brace as error

### ISSUE THREAD

**Issue by danielrainer** [lervag/vimtex#2408]
### Description

The trailing curly brace in line 3 of `minimal.tex` is highlighted as an error (`texGroupError`) despite being valid.

### Steps to reproduce

[minimal.vim](https://github.com/lervag/vimtex/files/8840139/minimal.vim.txt)
[minimal.tex](https://github.com/lervag/vimtex/files/8840140/minimal.tex.txt)

Install vimtex and look at the syntax highlighting of the file. The last closing curly brace in the `\begin{tabular}` line is highlighted as an error, although it is valid. This error does not show up when using the default syntax highlighting without vimtex.

### Expected behavior

Valid syntax is not marked as an error.

### Actual behavior

The last curly brace in the line `    \begin{tabular}{*{1}{p{1cm}}}` is highlighted as an error (`texGroupError`).

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Linux 5.18.1-arch1-1
  Vim version: NVIM v0.5.1
  Has clientserver: true
  Servername: /tmp/nvimOddEaA/0

VimTeX project: repro
  base: repro.tex
  root: /root
  tex: /root/repro.tex
  main parser: current file verified
  document class: minimal
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
