### ISSUE TITLE
sumatrapdf backward search not working

### ISSUE THREAD

**Issue by gaofengnan** [lervag/vimtex#2412]
### Description

Everything works including forward search, except the backward search with sumatrapdf on my windows 10 machine.

Following the official doc, I set in the sumatrapdf option `cmd /c start /min "" vim -v --not-a-term -T dumb -c "VimtexInverseSearch %l '%f'"`, and double click on a resulting pdf, nothing happens to my vim session except a cmd window pops up with pwd set to the directory where sumatrapdf is.  

I tried several other hacks I found on Google, and none works.  I am rather confused.  Do so few people use vimtex on Windows?  

This is the revelant bit in vimrc.

```vim
let g:vimtex_view_general_viewer = 'SumatraPDF'
let g:vimtex_view_general_viewer = 'SumatraPDF -reuse-instance '
                \ . '-inverse-search "gvim --servername ' . v:servername
                \ . ' --remote-send \"^<C-\^>^<C-n^>'
                \ . ':drop \%f^<CR^>:\%l^<CR^>:normal\! zzzv^<CR^>'
                \ . ':execute ''drop '' . fnameescape(''\%f'')^<CR^>'
                \ . ':\%l^<CR^>:normal\! zzzv^<CR^>'
                \ . ':call remote_foreground('''.v:servername.''')^<CR^>\""'


let maplocalleader = ","
```

And this is in my sumatrapdf `cmd /c start /min "" vim -v --not-a-term -T dumb -c "VimtexInverseSearch %l '%f'"`

### Steps to reproduce

Not relevant

### Expected behavior

Not relevant

### Actual behavior

Not relevant

### Do you use a latexmkrc file?

Not revelant

### VimtexInfo

```yaml
System info:
  OS: DESKTOP (Microsoft Windows 10 )
  Vim version: VIM 8.2 (1-5069)
  Has clientserver: true
  Servername: GVIM

VimTeX project: 
  base: 
  root: 
  tex: 
  main parser: current file verified
  document class: article
  packages: algorithm2e amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook bbm bbold bigintcalc bitset bm booktabs caption caption3 cleveref cmap color comment dsfont enumitem epstopdf-base etexcmds fontenc geometry gettitlestring graphics graphicx hycolor hyperref ifoddpage iftex ifthen ifvtex infwarerr inputenc intcalc keyval kvdefinekeys kvoptions kvsetkeys latexsym letltxmacro lmodern ltxcmds multirow nameref natbib pdfescape pdftexcmds refcount relsize rerunfilecheck soul trig ulem uniquecounter url xcolor xspace
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: process 18908 run
      output: C:\Users\fengnan\AppData\Local\Temp\V1TB5C9.tmp
      cmd: set max_print_line=2000 & latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e "$compiling_cmd = ($compiling_cmd ? $compiling_cmd . ' & ' : '') . 'echo vimtex_compiler_callback_compiling'" -e "$success_cmd = ($success_cmd ? $success_cmd . ' & ' : '') . 'echo vimtex_compiler_callback_success'" -e "$failure_cmd = ($failure_cmd ? $failure_cmd . ' & ' : '') . 'echo vimtex_compiler_callback_failure'" "xxx.tex"
      pid: 18908
  viewer: General
    job: 
      pid: 15768
      cmd: SumatraPDF -reuse-instance -forward-search "" 81 ""
  qf method: LaTeX logfile
```
