### ISSUE TITLE
close quickfix window when project is closed

### ISSUE THREAD

**Issue by pitkling** [lervag/vimtex#2420]
### Description

When I close the last file of a LaTeX project and the quick fix window is open, it currently stays open and I have to close it manually via `:q`. Now I wanted to ask for a feature to automate this, but than I found the following old and closed issue: lervag/vimtex#385.

So it seems that feature was there at some point and either got removed (on purpose or by accident) or I'm doing something wrong. I did a quick search for `cclose` in the current code base and tried to retrace whether it is supposed to be called on quit, and it seems it is not (but I'm not experienced in vimscript).

### Steps to reproduce

Open a simple latex project consisting of one file. Add an error in the code and compile, such that the quick fix window opens. Close the LaTeX file via `:q`.

### Expected behavior

Both the buffer with the LaTeX file and the quickfix buffer should close.

### Actual behavior

Only the buffer with the LaTeX file closes, the quickfix buffer remains open and must be closed manually.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 12.1 (21C52)
  Vim version: NVIM v0.7.0
  Has clientserver: true
  Servername: /var/folders/_q/rbdgd7yx5gz3zwhq47sv4h700000gn/T/vimr_CCC3C4F4-1A72-4A89-80D7-8A13A395A1F0.sock

VimTeX project: main
  base: main.tex
  root: /Users/peter/Downloads/Test
  tex: /Users/peter/Downloads/Test/main.tex
  main parser: current file verified
  document class: scrartcl
  packages: algorithmic auxlib bibretriever
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -synctex=1
      -interaction=nonstopmode
    build_dir: _build.nosync
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: sioyek
  qf method: LaTeX logfile using pplatex
```
