### ISSUE TITLE
Completion with ]] in Neovim 0.7.1 and later

### ISSUE THREAD

**Issue by MckinleyX** [lervag/vimtex#2421]
### Description

When trying to autocomplete(?) with `]]` on Neovim 0.7.1 and later, indentation is not corrected, and instead a `^F` character is added to the end.

### Steps to reproduce

1. `nvim --clean -u minimal.vim minimal.tex`

    ```vim
    set runtimepath^=$XDG_CONFIG_HOME/vim 
    call plug#begin()
    Plug 'lervag/vimtex'
    call plug#end()
    ```

3. Type `$a` 
4. Autocomplete with `]]`

### Expected behavior

Completion works properly (i.e. `$a$`)

### Actual behavior

Completion does complete, but adds an extra (control?) character to the end (i.e. `$a$^F`)

### Do you use a latexmkrc file?

Yes

### VimtexInfo

```yaml
System info:
  OS: Arch Linux
  Vim version: NVIM v0.7.1
  Has clientserver: true
  Servername: /tmp/nvimJFyjZr/0

VimTeX project: minimum
  base: minimum.tex
  root: /home/faefeyfa
  tex: /home/faefeyfa/minimum.tex
  main parser: current file
  document class: 
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    build_dir: build
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
