### ISSUE TITLE
i load the zathura or skim, but when i use \lv, it shows `not using a previewer`

### ISSUE THREAD

**Issue by EdwardWong1994** [lervag/vimtex#2424]
### Description

I have been struggled for almost two days just want to make the pdfviewer show up.  But i can not succeed due to the problem "not using a previewer", not much solution i can find.

Here is my environment for mac system:
Darwin MacBook-Pro.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101 arm64

I do not know what's the real problem for this. I do not know whether it is related with `dbus`. When i use `brew services list`, the status of dbus is stopped, not runing. But i can not solve.  

Here is one of the suspected reason, see below figure:

![suspected reason](https://user-images.githubusercontent.com/96438179/176588235-6fc7fe6e-4492-49c9-8e4b-7f01949697f6.jpg)

### Steps to reproduce

I am not using minimal.vim , i edit all the setting in `~/.vimrc` and using `\ll` compile the .tex file.

### Expected behavior

It run with no error but pdf viewer did not pop up

### Actual behavior

I compile my latex file without no error using `\ll`, but when i use command `\lv` to show the pdf, the viewer did not show up.  I try to find such problem and find a similar, but the reason is quite different. I use `\lo` to output the compile information as below figure
![error information](https://user-images.githubusercontent.com/96438179/176587704-205c8493-8964-46a0-a1f0-5cc37d1fca13.jpg)

I can use `zathura a.pdf` to open the file in the terminal, but when i try to show up the pdf file after compilation, it did not showup.   I also try skim as my default viewer, it occur the same "not using a previewer" information. 

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 11.4 (20F71)
  Vim version: VIM 9.0 ()
  Has clientserver: false

VimTeX project: exercise
  base: exercise.tex
  root: /Users/wangchenchen/Desktop/WCC/Latex
  tex: /Users/wangchenchen/Desktop/WCC/Latex/exercise.tex
  main parser: current file verified
  document class: article
  packages: amsbsy amsgen amsmath amsopn amstext
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
