### ISSUE TITLE
Wrong indentation/softwrap of inline maths when the paragraph span to 3+ lines while inside another environment

### ISSUE THREAD

**Issue by 0804d23d** [lervag/vimtex#2426]
### Description

I'm using MacVim, and I have some 'misbehaving' automatic indent, visualization of indentations, and softwrap settings in my `.vimrc`. I'm not exactly sure what's wrong with that, but I will mention what I really want to achieve here just in case it has something to do with the weird indentation/softwrap I'm getting for the softwrap/indentation of the inline maths environment when inside another environment that happen to span 3+ lines under softwrap (and I'm also hoping to fix it if someone happen to know what's wrong with it):

In particular, I want all my indentations (which are converted to 4 spaces) to show up, but nothing else (I currently have `listchars=multispace:•`), and I also want softwrap, but the softwrap 'indentations' preceding any softwrap seems to trigger `listchars=multispace:•` as well, and this is not something I want. (perhaps it's actually doing hardwrap or something?)

Something else I just remembered is that with my current `.vimrc` configuration, when I press tab after 3 or less characters (either number, alphabet, punctuations, or a mix of them), I only get 3 spaces after 1 character, two spaces after 2 characters, and 1 space after 3 characters. But when I have 4 or more characters, and I follow it with a tab, I get my 4 spaces, like I wanted.

Now, for the main issue, when I want to have inline maths environment inside another environment, then if the paragraph span 3+ lines, and the paragraph is indented to begin with, then if the softwrap happens to be triggered along the inline maths environment on the 3+ lines, the indentation/softwrap seems to remove one indent for each of the following lines (e.g., on the 3rd lines, if you have 4 tabs [16 spaces] before, you only get 3 tabs now; then for the 4th lines, if you have 4 tabs before, you only get 2 tabs; etc.,).

### Steps to reproduce

Here is my `.vimrc`:

```vim
call plug#begin(has('nvim') ? stdpath('data') . '/plugged' : '~/.vim/plugged')

Plug 'lervag/vimtex'
    let g:vimtex_view_method = 'skim'
    let g:vimtex_view_skim_activate = 1
    let g:vimtex_view_skim_sync = 1
    let g:vimtex_view_skim_reading_bar = 1
    let g:vimtex_cache_root = '/Volumes/T7/Local'
    let g:vimtex_syntax_conceal_disable = 1
    let g:vimtex_compiler_latexmk = {'continuous' : 0}
    let g:vimtex_toc_config = {
        \'layer_status' :
            \{ 'content': 1,
                \'label': 0,
                \'todo': 0,
                \'include': 0
            \},
            \'indent_levels': 1,
            \'resize': 0,
            \'show_help': 0,
            \'split_width': 30,
            \'refresh_always': 0
        \}
    let g:vimtex_complete_close_braces = 1
    let g:vimtex_quickfix_ignore_filters = [
            \ 'Package fancyhdr Warning',
            \ 'Overfull \hbox',
        \]
    let g:vimtex_quickfix_open_on_warning = 0

call plug#end()

set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set autoindent
set copyindent
set backspace=indent,eol,start
set list
set listchars=multispace:•
set wrap
set breakindent
set textwidth=79
set fo+=t
set fo-=l

highlight SpecialKey ctermfg=250 guifg=#bcbcbc
```

1. Start a fresh TeX file with appropriate preambles.
2. Add an outer environment (say figure).
3. Then inside that environment, say the figure environment, and you want to add a caption to it, you type a bunch of stuff that spans to the 2nd line, the softwrap/indentation works as expected (mostly).
4. Now, you continue to type more stuff, but when you reach the end of the 2nd line, and you want add an inline maths environment that will be softwrapped to the next (3rd) line, you will notice that the softwrap removes one tab (4 spaces) from the indentations of the parent paragraph.

Here is a `minimal.tex`:

```tex
\documentclass{minimal}
\usepackage{graphicx,float}

\begin{document}

\section{Some Section}

    \begin{figure}
        \centering
        \caption{The first line is fine, for example, if we now have
        $f(y)=y(y+1)$, all the softwrap/indentations are alright. But then
    $f(y)=y(y+1)$, here it goes, what happened here?}
    \end{figure}

\end{document}
```

### Expected behavior

I would expect the same indentataion/softwrap to follow for a long paragraph that span several lines, and under softwrap.

### Actual behavior

One indentataion per line is removed for 3+ lines.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info
  OS: macOS 12.4 (21F79)
  Vim version: VIM 8.2 (1-3455)
  Has clientserver: true
  Servername: VIM

VimTeX project: test
  base: test.tex
  root: /Volumes/T7/Local
  tex: /Volumes/T7/Local/test.tex
  main parser: current file verified
  document class: article
  packages: epstopdf-base float graphics graphicx keyval trig
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 0
    executable: latexmk
  viewer: Skim
  qf method: LaTeX logfile
```
