### ISSUE TITLE
Fold only manually

### ISSUE THREAD

**Issue by zhyiyu** [lervag/vimtex#2427]
### Description

Hi, first of all, thanks for making this brilliant plug-in for Vim!

I am trying to achieve the following with folding:

- Nothing is folded upon opening of a file.
- Only fold and unfold manually.

In order to do that, I have the following in my `.vim/vimrc` file:

```vim
set foldmethod=manual

"" vimtex
filetype plugin indent on
syntax enable
let g:vimtex_fold_enabled=1
let g:vimtex_fold_manual=1
```

But still, preamble and equations are folded upon open, and the opening is slow (takes 3 seconds for a file with 5.5k lines).

Am I missing something or is this not supported yet?

Thanks in advance!

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Mac OS X 10.15.7 (19H1922)
  Vim version: VIM 8.1 (1-503, 505-680, 682-2292, 3402, 3409, 3428, 3489)
  Has clientserver: false

VimTeX project: main
  base: main.tex
  root: /Users/zyy/Dropbox/research/working/jet structure/note
  tex: /Users/zyy/Dropbox/research/working/jet structure/note/main.tex
  main parser: current file verified
  document class: article
  packages: adjcalc adjustbox amsbsy amsfonts amsgen amsmath amsopn amssymb amstext array atbegshi authblk authoraftertitle auxhook babel biblatex calc caption caption3 catchfile catoptions cleveref collectbox currfile defpattern doi enumitem esvect etex etexcmds etoolbox everyshi expl3 filehook float fp fp-a
  compiler: latexmk
    engine: -xelatex
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1 
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
