### ISSUE TITLE
Zathura set up on ARM Mac 

### ISSUE THREAD

**Issue by Noahyt** [lervag/vimtex#2428]
### Description

I am following the guide to setting up Vimtex with `zathura` in the vimtex.txt FAQ section `vimtex-faq-zathura-macos` and step 3. does not seem to apply/work on my M1 MacBook Air.

This step states: 

>  3. Changed the value of `<auth><\auth>` in
>       `/usr/local/opt/dbus/share/dbus-1/session.conf` from `EXTERNAL` to
>       `DBUS_COOKIE_SHA1`.

The directory /opt/ does not exist on my computer.

I followed the rest of the guide and `zathura` appears to work with the exception of reverse-search. Could this be related? Why does the `session.conf` file not exist on my computer? 

### Steps to reproduce

Following guide https://github.com/lervag/vimtex/blob/master/doc/vimtex.txt

### Expected behavior

`/usr/local/opt/dbus/share/dbus-1/session.conf` should exist.

### Actual behavior

`/usr/local/opt/dbus/share/dbus-1/session.conf` does not exist.

### Do you use a latexmkrc file?

N/A

### VimtexInfo

```yaml
System info:
  OS: macOS 12.1 (21C52)
  Vim version: VIM 8.2 (1-2671, 3402, 3409, 3428, 3489)
  Has clientserver: false

VimTeX project: test
  base: test
  root: /Users/noahtoyonaga/Documents/
  tex: /Users/noahtoyonaga/Documents/test.tex
  main parser: current file verified
  document class: article
  packages: inputenc
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: process 10117 run
      output: /var/folders/bn/93vnvhxd7vl08z9z7r82dwnw0000gn/T/vp8K2G2/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'initial_write_up.tex'
      pid: 10117
  viewer: Zathura
    xwin id: 0
    cmd_start: zathura  -x "vim -T dumb --not-a-term -n -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 7:1:'/Users/noahtoyonaga/Documents/test.tex' 'test'&
  qf method: LaTeX logfile
```
