### ISSUE TITLE
Unable to remap \lv to something else

### ISSUE THREAD

**Issue by schneiderfelipe** [lervag/vimtex#2431]
### Description

I would like to remap `\lv` to something else (to use [SVED](https://github.com/peterbjorgensen/sved) with Evince), but I'm having trouble.

### Steps to reproduce

SVED suggests the following remapping:

```vim
nmap <F4> :call SVED_Sync()<CR>
```

so I tried

```vim
nmap \lv :call SVED_Sync()<CR>
```

(I use `\` as the leader, but with aliases to `<space>` and `,`. If I map the above with `<leader>lv`, it works with `,lv` and the equivalent with space, but not with `\`. Could this be related?)

The above was also tested within a `autocmd VimEnter * ...` as well. Nothing worked.

### Expected behavior

Having Evince work with Synctex through SVED.

### Actual behavior

The old behavior is still in place.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 22.04 LTS
  Vim version: NVIM v0.6.1
  Has clientserver: true
  Servername: /tmp/nvimTCQ1ol/0

VimTeX project: main
  base: main.tex
  root: /home/schneider/Dropbox/thesis
  tex: /home/schneider/Dropbox/thesis/main.tex
  main parser: recursive search
  document class: abntex2
  packages: abntex2abrev abntex2cite array atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook babel backref bigintcalc bitset bookmark calc color dcolumn delarray enumitem epstopdf-base etexcmds etoolbox expl3 fontenc gettitlestring graphics graphicx hycolor hyperref ifpdf iftex ifthen ifxetex import indentfirst infwarerr inputenc intcalc keyval kvdefinekeys kvoptions kvsetkeys l3keys2e letltxmacro lipsum lmodern ltxcmds memhfixc microtype nameref pdfescape pdftexcmds refcount relsize rerunfilecheck scalefnt setspace tabularx textcase trig uniquecounter url
  source files:
    main.tex
    src/preamble/config.tex
    src/preamble/spacing.tex
    src/preamble/quadros.tex
    src/preamble/info.tex
    src/before.tex
    src/ficha.tex
    src/commands.tex
    src/after.tex
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
