### ISSUE TITLE
% does not work in .bib file

### ISSUE THREAD

**Issue by zhyiyu** [lervag/vimtex#2433]
### Description

With `vimtex` installed, `%` does move cursor between matching parentheses in Vim normal mode.

### Steps to reproduce

1. Install and setup `vimtex`.
2. Open a `.bib` file with Vim.
3. Type in something that contains matching parentheses.
4. In normal mode, you will find that `%` will not let you jump between parentheses.

### Expected behavior

In Vim normal mode, pressing `%` should move cursor between matching parentheses.

### Actual behavior

Pressing `%` has no effect in `.bib` files.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Mac OS X 10.15.7 (19H1922)
  Vim version: VIM 8.1 (1-503, 505-680, 682-2292, 3402, 3409, 3428, 3489)
  Has clientserver: false

VimTeX project: main
  base: main.tex
  root: /Users/zyy/Dropbox/research/working/jet structure/note
  tex: /Users/zyy/Dropbox/research/working/jet structure/note/main.tex
  main parser: current file verified
  document class: article
  packages: adjcalc adjustbox amsbsy amsfonts amsgen amsmath amsopn amssymb amstext array atbegshi authblk authoraftertitle auxhook babel biblatex calc caption caption3 catchfile catoptions cleveref collectbox currfile defpattern doi enumitem esvect etex etexcmds etoolbox everyshi expl3 filehook float fp fp-a
  compiler: latexmk
    engine: -xelatex
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
