### ISSUE TITLE
Only `p` fixed width column type supported (not `m` or `b`)

### ISSUE THREAD

**Issue by MarcelRobitaille** [lervag/vimtex#2434]
### Description

Only the `p` tabular fixed-width column type is supported. There also exists `m` for middle and `b` for bottom.

For this table:
```tex
\begin{tabular}{p{30mm}m{40mm}}
\end{tabular}
```
As expected, the `p` character is `texTabularCol` and the `30mm` is `texLength`.
However, the `m` character is `texTabularArg` and the `40mm` is `texTabularMulti`.

I think this can easily be fixed by adding lines similar to [`core.vim:314`](https://github.com/lervag/vimtex/blob/master/autoload/vimtex/syntax/core.vim#L314) for `m` and `b`.

### Steps to reproduce

1. `vim -u minimal.vim minimal.tex`
2. Put cursor over `p` of `p{30mm}`. Press F10.
3. Put cursor over `m` of `m{40mm}`. Press F10.

(The footer of the textbox says to drag and drop the files, but GitHub does not support `.vim` or `.tex`. Is this right?)

`minimal.vim`:
```vim
call plug#begin('~/.config/nvim/plugged')
	Plug 'lervag/vimtex'
call plug#end()

map <F10> :echo "hi<" . synIDattr(synID(line("."),col("."),1),"name") . '> trans<'
\ . synIDattr(synID(line("."),col("."),0),"name") . "> lo<"
\ . synIDattr(synIDtrans(synID(line("."),col("."),1)),"name") . ">"<CR>

function! SynStack()
	if !exists("*synstack")
		return
	endif
	echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
endfunc

```

`minimal.tex`:
```tex
\documentclass{article}
\usepackage{tabular}
\begin{document}
\begin{tabular}{p{30mm}m{40mm}}
\end{tabular}
\end{document}
```

### Expected behavior

Both times, pressing F10 shows `texTabularCol`

### Actual behavior

Pressing F10 with the cursor on the `m` character prints `texTabularArg`.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Pop!_OS 22.04 LTS
  Vim version: NVIM v0.8.0-dev
  Has clientserver: true
  Servername: /tmp/nvimv2qokv/0

VimTeX project: minimal
  base: minimal.tex
  root: /tmp
  tex: /tmp/minimal.tex
  main parser: current file verified
  document class: article
  packages: tabular
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
