### ISSUE TITLE
Unable to compile with lualatex

### ISSUE THREAD

**Issue by occludedpixel** [lervag/vimtex#2447]
### Description

Unable to compile with lualatex using `:VimtexCompile` .

However, copying the command 
```
max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -lualatex -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'minimal.tex'
```
from `:VimtexInfo` and running it in a separate terminal works. Trying to run the command within Vim also fails.

### Steps to reproduce

1. vim -u minimal.vim minimal.tex
2. `:VimtexCompile`

`minimal.vim`:
```
set nocompatible
let &runtimepath  = '~/.vim/plugged/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/plugged/vimtex/after'
filetype plugin indent on
syntax enable
```

`minimal.tex`:
```
%! TeX program = lualatex

\documentclass{article}
\usepackage{emoji}

\begin{document}

\emoji{leaves}

\end{document}
```

### Expected behavior

PDF compiles and PDF viewer opens to show it.

### Actual behavior

Command line displays `VimTeX: Compilation failed!`

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 12.4 (21F79)
  Vim version: VIM 8.2 (1-4113)
  Has clientserver: false

VimTeX project: minimal
  base: minimal.tex
  root: /Users/danielyap/Documents/emoji
  tex: /Users/danielyap/Documents/emoji/minimal.tex
  main parser: current file verified
  document class: article
  packages: emoji
  compiler: latexmk
    engine: -lualatex
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: process 29738 run
      output: /var/folders/26/3wn7sn716w50nb7yxzg35lxh0000gn/T/vtHWN2X/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -lualatex -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'minimal.tex'
      pid: 29738
  viewer: General
  qf method: LaTeX logfile
```
