### ISSUE TITLE
Neovim hangs/takes a long time to load after using VimtexCompile

### ISSUE THREAD

**Issue by evesdropper** [lervag/vimtex#2448]
### Description

Set up Neovim and LaTeX on my new computer and everything was fine yesterday; however, today I needed to use the `minted` package and then VimTeX started running into issues. I noticed it would go into "Compilation Completed" quickly a lot of the time (even yesterday) even though there were apparent errors in my document but sometimes VimTeX does this randomly, even on my previous setup, so I didn't think much of it. However, after compiling something with a minted block as a test, the terminal hangs or takes a long time to load.

### Steps to reproduce

`minimal.vim`
```vim
call plug#begin()
Plug 'lervag/vimtex'
call plug#end()

let g:vimtex_view_method = 'zathura'
```

`minimal.tex`
```TeX
\documentclass{minimal}
\usepackage{minted}
\begin{document}
Hello world.
\begin{minted}{python}
test = "Hello World"
\end{minted}
\end{document}
````

1. `nvim -u minimal.vim minimal.tex`
2. `<Leader>ll` or `:VimtexCompile`

### Expected behavior

The tex file should compile and display pdf, and I should be able to continue editing the file.

### Actual behavior

It displays `VimTeX: Compilation Completed` and I cannot use the terminal window anymore.

Something strange is that after copying over the `minimal.tex` file after it froze, it had a moment where it unfroze and took in some keyboard input that I had entered in a few minutes ago only long after I started `:VimtexCompile`, leading me to think that it might not be completely hanging but rather being very slow to compile?

### Do you use a latexmkrc file?

Yes - I made some adjustments for the `minted` package, namely adding the `-shell-escape` flag.

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 20.04.4 LTS
  Vim version: NVIM v0.7.2
  Has clientserver: true
  Servername: /tmp/nvimTH9p8X/0

VimTeX project: test
  base: test.tex
  root: /mnt/c/Users/ekoor/Documents/university
  tex: /mnt/c/Users/ekoor/Documents/university/test.tex
  main parser: current file verified
  document class: minimal
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
