### ISSUE TITLE
iftoggle indenting

### ISSUE THREAD

**Issue by alkim0** [lervag/vimtex#2450]
### Description

The `iftoggle` comment is not indenting properly. It indents twice instead of once as expected.

### Steps to reproduce

```
\iftoggle{paper}{}{%
    Line
  }%
```
Here, Line is indented twice (4 spaces) instead of 2 spaces. It also messes up every subsequent line with an extra indent.

### Expected behavior

Please update `g:vimtex_indent_conditionals` to have:
```
'open': '\v%(\\newif)@<!\\if%(f>|field|name|numequal|thenelse|toggle)@!',
```

### Actual behavior

If updated in vimrc, it works as expected.

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
System info:
  OS: Arch Linux
  Vim version: VIM 9.0 ()
  Has clientserver: true
  Servername: undefined (vim started without --servername)

VimTeX project: main
  base: main.tex
  root: /dir
  tex: /dir/main.tex
  main parser: texroot specifier
  document class: vldb
  packages: algorithm algorithmicx algpseudocode aliasctr amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook balance bigintcalc bitset calc caption caption3 datetime datetime-defaults enumitem epsfig epstopdf-base etexcmds etoolbox fcnumparser fcprefix float fmtcount geometry gettitlestring graphics graphicx grffile hycolor hyperref ifmtarg iftex ifthen ifvtex infwarerr intcalc keyval kvdefinekeys kvoptions kvsetkeys latexsym letltxmacro ltxcmds mathtools mhsetup multicol multirow nameref parseargs pdfescape pdftexcmds refcount rerunfilecheck silence subcaption thm-amsthm thm-autoref thm-kv thm-listof thm-patch thm-restate thmtools trig ulem uniquecounter url xcolor xifthen xkeyval xspace
  source files:
    main.tex
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```

P.S. Thanks for the awesome plugin!
