### ISSUE TITLE
Vimtex + nvim-cmp not working.

### ISSUE THREAD

**Issue by Pyrole-2002** [lervag/vimtex#2453]
### Description

I was trying to get vimtex working with nvim-cmp, I found similar issues which were solved using omni (idk what that is).

Here are my configs:

vimtex.lua: http://ix.io/46HO
cmp.lua: http://ix.io/46HP

my directory structure

```
/home/pyrole/.config/nvim
├── init.lua
├── lua
│   └── pyrole
│       ├── autopairs.lua
│       ├── bufferline.lua
│       ├── cmp.lua
│       ├── colorizer.lua
│       ├── colorscheme.lua
│       ├── comment.lua
│       ├── gitsigns.lua
│       ├── indent.lua
│       ├── kanagawa.lua
│       ├── keymaps.lua
│       ├── lspconfig.lua
│       ├── luasnip.lua
│       ├── nvim-tree.lua
│       ├── options.lua
│       ├── plugins.lua
│       ├── tabnine.lua
│       ├── telescope.lua
│       ├── toggleterm.lua
│       ├── treesitter.lua
│       └── vimtex.lua
├── oldinit.vim
└── plugin
    └── packer_compiled.lua

3 directories, 23 files
```

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Arch Linux
  Vim version: NVIM v0.7.2
  Has clientserver: true
  Servername: /tmp/nvimTn11aS/0

VimTeX project: main
  base: main.tex
  root: /home/pyrole/Programming/Latex
  tex: /home/pyrole/Programming/Latex/main.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
```
