### ISSUE TITLE
`syntax on` in neovim causes zathura to open multiple windows

### ISSUE THREAD

**Issue by jam1015** [lervag/vimtex#2454]
### Description

I know `syntax on` is redundant in neovim. But when I have it on and I hit `\lv` to view a document in zathura, it causes a new window to open each time. When I remove `syntax on` the problem goes away.

### Steps to reproduce

minimal init.vim

```vim
syntax on
lua require('plugins') -- ~/.config/nvim/lua/plugins.lua
```

corresponding `~/.config/nvim/lua/plugins.lua`:

```lua
return require('packer').startup(function(use)

  use {'lervag/vimtex',
    config = function()
      vim.cmd([[
        let g:vimtex_view_method = 'zathura'
        let g:vimtex_view_general_viewer = 'zathura'
        let g:vimtex_view_enabled=1
      ]])
    end
  }
end)
```

minimal tex file compiled with synctex:

```tex
\documentclass{article}
\begin{document}
This is our first document here we go!
\end{document}
```

### Expected behavior

`syntax on` makes plus `\lv` should just update position in current document.

### Actual behavior

`syntax on` causes a problem, new window is opened with each `\lv`.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Linux 5.18.14-arch1-1
  Vim version: NVIM v0.7.2
  Has clientserver: true
  Servername: /tmp/nvimsocket

VimTeX project: example1
  base: example1.tex
  root: /home/jordan/Documents/latex_learning/latex_beginners_guide
  tex: /home/jordan/Documents/latex_learning/latex_beginners_guide/example1.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
    job:
      pid: -
      cmd: zathura '/home/jordan/Documents/latex_learning/latex_beginners_guide/example1.pdf'
  qf method: LaTeX logfile
```
