### ISSUE TITLE
pdflatex#####.fls generated by latexmk/not deleted by \lc

### ISSUE THREAD

**Issue by ajsenko5** [lervag/vimtex#2455]
### Description

I get a few files like "pdflatex61757.fls" (or 5 other numbers) after clean my session. I think this is a latexmk issue (I've seen it before with other editors like atom) but I was wondering if there was a spot where I could easily remove such files by adding the line "rm pdflatex*.fls"

### Steps to reproduce

open a .tex file in vim, and compile/stop compiling a few times. next clean and exit
It doesn't always happen though. very confusing

### Expected behavior

I expect no files other than the synctex.gz, pdf, and tex to remain

### Actual behavior

I get anywhere from like 0-5 pdflatex####.fls files

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Pop!_OS 22.04 LTS
  Vim version: VIM 8.2 (1-3995)
  Has clientserver: false

VimTeX project: graph2
  base: graph2.tex
  root: /home/adam/Desktop/Thesis_Work/latex_stuff/graph2
  tex: /home/adam/Desktop/Thesis_Work/latex_stuff/graph2/graph2.tex
  main parser: current file
  document class: standalone
  packages: mhchem
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0 
  qf method: LaTeX logfile
~
```
