### ISSUE TITLE
MacVim+Vimtex+Zathura Forward search works but inverse search does not

### ISSUE THREAD

**Issue by Feliconut** [lervag/vimtex#2456]
### Description

I tried to set up MacVim+Vimtex+Zathura. The forward search worked but backward search did not.

### Steps to reproduce

1. put the following to `~/.vimrc`

    ```vim
    set nocompatible
    let &runtimepath  = '~/.vim/plugged/vimtex,' . &runtimepath
    let &runtimepath .= ',~/.vim/plugged/vimtex/after'
    filetype plugin indent on
    syntax enable
    " Add relevant options and VimTeX configuration below.
    call plug#begin()
    Plug 'lervag/vimtex'
    let g:vimtex_view_method='zathura'
    call plug#end()
    ```

2. run `vim test.tex`, where `test.tex` has the following content:

    ```tex
    \documentclass[12pt,letterpaper]{article}
    \author{test}
    \title{Test}
    \date{}
    \begin{document}
    \maketitle
    Hello
    \end{document}
    ```

3. type `\ll`. Now Zathura opens correctly with forward search highlight.

4. `C+click` some text in Zathura.

### Expected behavior

Backward search should work normally.

### Actual behavior

Nothing happens.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 12.5 (21G72)
  Vim version: VIM 9.0 (1-65)
  Has clientserver: true
  Servername: undefined (vim started without --servername)

VimTeX project: test
  base: test.tex
  root: /Users/xiaoyu
  tex: /Users/xiaoyu/test.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job:
      jobid: process 41119 run
      output: /var/folders/6m/hhdhqqf52hd50wpbypwvsbjc0000gn/T/vp0DRJs/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmdw . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "bbecho vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'test.tex'
      pid: 41119
  viewer: Zathura
    xwin id: 0
    cmd_start: zathura  -x "/opt/homebrew/Cellar/macvim/9.0.0065/MacVim.app/Contents/MacOS/Vim -T dumb --not-a-term -n -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 1:1:'/Users/xiaoyu/test.tex' 'test.pdf'&
  qf method: LaTeX logfile
```
