### ISSUE TITLE
mathzone fails for inline math inbetween $...$ for snippets

### ISSUE THREAD

**Issue by chenle02** [lervag/vimtex#2470]
### Description

The ultisnipts for snippets stops wroking for identify $...$ is a math region. It still works for the enviroment such as 

\begin{align} 
   ...
 \end{align}

Below is the math() function in my tex.snippets file.

```
global !p
# The following two lines are from https://github.com/lervag/vimtex/issues/1863
texMathZones = ['texMathZone' + x for x in ['', 'X', 'XX', 'Env', 'EnvStarred', 'Ensured']]
texIgnoreMathZones = ['texMathTextArg']
texMathZoneIds = vim.eval('map('+str(texMathZones)+", 'hlID(v:val)')")
texIgnoreMathZoneIds = vim.eval('map('+str(texIgnoreMathZones)+", 'hlID(v:val)')")
ignore = texIgnoreMathZoneIds[0]

def math():
    synstackids = vim.eval("synstack(line('.'), col('.') - (col('.')>=2 ? 1 : 0))")
    try:
        first = next(i for i in reversed(synstackids) if i in texIgnoreMathZoneIds or i in texMathZoneIds)
        return first != ignore
    except StopIteration:
        return False
```

### Expected behavior

Within $...$  why I type 1/2, I would like to see \frac{1}{2}, but it doesn't produce this result.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 20.04.4 LTS
  Vim version: NVIM v0.8.0-dev
  Has clientserver: true
  Servername: /run/user/1001/nvim.2417914.0

VimTeX project: minimal
  base: minimal.tex
  root: /home/lechen
  tex: /home/lechen/minimal.tex
  main parser: fallback current file
  document class: 
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
