### ISSUE TITLE
Compilation error due to failed mainfile detection!  for standalone files

### ISSUE THREAD

**Issue by Rmano** [lervag/vimtex#2471]
### Description

After the last upgrade (of `vimtex` as well as of the operating system), I have often the following error on simple files:

![image](https://user-images.githubusercontent.com/6414907/187039299-35910e49-b748-4d6c-b027-6cc20540aad6.png)

this is with `lalla.tex`

```latex
\documentclass[border=10pt]{standalone}
\usepackage[siunitx, RPvoltages]{circuitikz}
  \begin{document}
  \begin{tikzpicture}[]
      \draw[red] (0,0) to[R] ++(2,0);
  \end{tikzpicture}
\end{document}
```
opened with `vim -u ~/software/bugs/vimtex/minivimrc lalla.tex` where the `minivimrc` is:

```vim
set nocompatible
let &rtp  = '~/.vim/plugged/vimtex,' . &rtp
let &rtp .= ',~/.vim/plugged/vimtex/after'
filetype plugin indent on
syntax enable
```

and `~/.latexmkrc` 

```
$pdflatex = 'pdflatex -synctex=1 %O %S';
$pdf_update_method = 0;
$dvi_mode = 0;
$pdf_mode = 1;
$preview_continuous_mode = 1;
$pdf_previewer = 'start evince';

push @generated_exts, "cb";
push @generated_exts, "cb2";
push @generated_exts, "spl";
push @generated_exts, "nav";
push @generated_exts, "snm";
push @generated_exts, "tdo";
push @generated_exts, "nmo";
push @generated_exts, "brf";
push @generated_exts, "nlg";
push @generated_exts, "nlo";
push @generated_exts, "nls";
push @generated_exts, "synctex.gz";
push @generated_exts, "tex.latexmain";
push @generated_exts, "run.xml";
```

That seems to happen only when I try to compile files with `standalone` class...

```yaml
System info:
  OS: Ubuntu 22.04.1 LTS
  Vim version: VIM 8.2 (1-3995)
  Has clientserver: true
  Servername: undefined (vim started without --servername)

VimTeX project: lalla
  base: lalla.tex
  root: /home/romano/tmp
  tex: /home/romano/tmp/lalla.tex
  main parser: fallback current file
  document class: standalone
  packages: circuitikz
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
