### ISSUE TITLE
vimtex throws errors despite successfully compiling

### ISSUE THREAD

**Issue by mrb1358** [lervag/vimtex#2473]
### Description

When attempting compilation vimtex throws errors and fails to open the document viewer despite compilation succeeding (a correct PDF is outputted).

This only occurs when using nvim, everything works as expected with vim.

p.s. Thanks for your work on this plugin and for taking the time to look over this issue.

### Steps to reproduce

Files used are below.

1. `nvim -u minimal.vim minimal.tex`
2. Begin continuous compilation: `\ll`

**minimal.vim**

```vim
set nocompatible
filetype plugin indent on
syntax enable

call plug#begin(stdpath('data').'/plugged')
  Plug 'lervag/vimtex'
call plug#end()

let g:vimtex_view_method = 'zathura'
```

**minimal.tex**

```tex
\documentclass{article}

\begin{document}
 Hello World!
\end{document}
```

### Expected behavior

I expect compilation to succeed and the document viewer to open.

### Actual behavior

Compilation succeeds but vimtex throws the following errors and fails to open the document viewer.

```
Error detected while processing function vimtex#compiler#compile[4]..vimtex#compiler#start[25]..vimtex#log#info[1]..184[24]..185[5]..vimtex#ui#echo:
line    2:
E121: Undefined variable: #
E116: Invalid arguments for function extend
E15: Invalid expression: extend(#{indent: 0}, a:0 > 0 ? a:1 : {})
```

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 20.04.4 LTS
  Vim version: NVIM v0.4.3
  Has clientserver: true
  Servername: /tmp/nvimedYhYS/0

VimTeX project: minimal
  base: minimal.tex
  root: /home/buckm
  tex: /home/buckm/minimal.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 5
      output: /tmp/nvimedYhYS/1
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'minimal.tex'
      pid: 29740
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
