### ISSUE TITLE
\cite{} completion not working unless path of .bib file is specified

### ISSUE THREAD

**Issue by Eternex49** [lervag/vimtex#2474]
### Description

Completion for citations doesn't work unless the path to the .bib file is specified in the \bibliography statement.

The problem is the same as reported in issue #1815 . Unfortunately, in the thread, there is no explanation as to why the problem is occuring.

### Steps to reproduce

1. nvim -u minimal.vim test.tex
2. attempt an omni-completion after typing \cite{

### Expected behavior

A completion menu should appear and allow the user to select a citation.

### Actual behavior

The menu doesn't appear and the following error is reported:
Pattern not found

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Linux 5.19.2-arch1-1
  Vim version: NVIM v0.7.2
  Has clientserver: true

VimTeX project: test
  base: test.tex
  root: /home/user/latex
  tex: /home/user/latex/test.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
