### ISSUE TITLE
viewer stays general instead of 'sioyek'

### ISSUE THREAD

**Issue by cheiktraore** [lervag/vimtex#2476]
### Description

I am trying to set vimtex_viewer_method to 'sioyek' but looking at VimtexInfo I can see that it stays to general. It is the same behavior with 'skim' or whatever. i am using macos with neovim.

### Steps to reproduce

```lua
-- Automatically install packer
local install_path = fn.stdpath("data") .. "/site/pack/packer/start/packer.nvim"
if fn.empty(fn.glob(install_path)) > 0 then
	PACKER_BOOTSTRAP = fn.system({
		"git",
		"clone",
		"--depth",
		"1",
		"https://github.com/wbthomason/packer.nvim",
		install_path,
	})
	print("Installing packer close and reopen Neovim...")
	vim.cmd([[packadd packer.nvim]])
end

return require("packer").startup(function(use)
   use "wbthomason/packer.nvim"
   use "lervag/vimtex"
end)

vim.g.vimtex_view_sioyek_exe="/Applications/sioyek.app"
vim.g.vimtex_view_method = "sioyek"
vim.g.vimtex_complete_enabled = 1  -- autocomplete option
vim.g.vimtex_fold_enabled = 1 -- folding according to chapter, section, ...
vim.g.vimtex_syntax_enabled = 0 --  syntex hightlighting
vim.g.vimtex_quickfix_enabled = 1
-- --Don't open QuickFix for warning messages if no errors are present
vim.g.vimtex_quickfix_open_on_warning = 0

-- " whether to automatically open PDF viewer after first compilation or not
vim.g.vimtex_view_automatic = 1

---- " Define a custom shortcut to trigger VimtexView
vim.cmd([[nmap <localleader>v <plug>(vimtex-view)]])

-- " This will only work if `vim --version` includes `+clientserver`!
vim.cmd([[
if empty(v:servername) && exists('*remote_startserver')
  call remote_startserver('VIM')
endif
]])
```

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 12.5.1 (21G83)
  Vim version: NVIM v0.7.2
  Has clientserver: true
  Servername: /var/folders/5k/x_67q0gs48qd8mqm2q727vyr0000gn/T/nvimO2clhK/0

VimTeX project: malga_template_pres
    base: malga_template_pres.tex
    root: /Users/cheik/Documents/Presentation_First
    tex: /Users/cheik/Documents/Presentation_First/presentation.tex
  main parser: current file verified
  document class: beamer
  packages: amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook beamerbaseauxtemplates beamerbaseboxes beamerbasecolor beamerbasecompat
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
    job:
      pid: -
      cmd: open '/Users/temci/Documents/Presentation_First/presentation.pdf'
  qf method: LaTeX logfile
```
