### ISSUE TITLE
okular inverse search does not work

### ISSUE THREAD

**Issue by Q-Xue** [lervag/vimtex#2478]
### Description

installed neovim-remote and nvr works normally from terminal
open article.tex from terminal and compile, then article.pdf is shown in okular

I run from terminal

```sh
nvr --servername `cat /tmp/vimtexserver.txt` -c "call vimtex#view#inverse_search(30,'article.tex')"
```

it works.
but when I put inside okular

```sh
nvr --servername `cat /tmp/vimtexserver.txt` -c "call vimtex#view#inverse_search(%l,'%f')"
```

nothing works

I try from terminal

```sh
nvr --servername `cat /tmp/vimtexserver.txt` -c "echo 'hello'"
```

it works.
but when I put inside okular

```
nvr --servername `cat /tmp/vimtexserver.txt` -c "echo 'hello'"
```

it does not connect to the nvim server and hello is not printed.

I think the command put in okular is not executed at all.
Where did I do wrong? Please give me some guide. Thanks!

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 20.04.5 LTS
  Vim version: NVIM v0.7.2
  Has clientserver: true
  Servername: /tmp/nvimMFIV3f/0

VimTeX project: article
  base: article.tex
  root: /home/etg/dev/latex-playground
  tex: /home/etg/dev/latex-playground/article.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 0
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
