### ISSUE TITLE
Need to press TAB twice to get the fallback keyword <c-p> completion when used with SuperTab

### ISSUE THREAD

**Issue by benshuailyu** [lervag/vimtex#2479]
### Description

I have both SuperTab and vimtex installed and have configured SuperTab to fall back to the default  `<c-p>` keyword completion if omini-completion returns nothing. Both SuperTab and vimtex are in their latest versions (as for 3 Sept 2022). I have MacVim version 9.0 installed on macOS Monterey 12.5.1. 

This is similar to an earlier issue reported at #502 and discussed [here](https://www.reddit.com/r/vim/comments/8cf0k0/supertab_help_is_it_normal_to_have_to_press_tab/).

I have my .vimrc configured for SuperTab as follows:

```vim
let g:SuperTabDefaultCompletionType = "context"
let g:SuperTabContextDefaultCompletionType = "<c-p>"
let g:SuperTabCompletionContexts = ['s:ContextDiscover', 's:ContextText']
let g:SuperTabContextDiscoverDiscovery = ["&completefunc:<c-x><c-u>", "&omnifunc:<c-x><c-o>"]
```

### minimal working test file minimal.vim

```vim
set nocompatible
let &runtimepath  = '~/.vim/bundle/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/bundle/vimtex/after' . &runtimepath
let &runtimepath  = '~/.vim/bundle/supertab'
filetype plugin indent on
syntax enable

let g:SuperTabDefaultCompletionType = "context"
let g:SuperTabContextDefaultCompletionType = "<c-p>"
let g:SuperTabCompletionContexts = ['s:ContextDiscover', 's:ContextText']
let g:SuperTabContextDiscoverDiscovery = ["&completefunc:<c-x><c-u>", "&omnifunc:<c-x><c-o>"]
```

### minimal working test file minimal.tex

```tex
\documentclass{article}

\begin{document}
This is a test line.
Th
\end{document}
```

### Steps to reproduce the behavior

1. `mvim -u minimal.vim minimal.tex`
2. The first line "This is a test line" has already been typed in the .tex file.
3. The second line starts with "Th". If putting current cursor after "Th" then pressing TAB, one would expect a completion list containing "This" to pop us. But this did not happen until I press TAB for the second time.

### Expected behavior

When following the above steps, I expect  a completion list containing "This"

### Actual behavior

The completion list did not pop up until I press TAB for the second time.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 12.5.1 (21G83)
  Vim version: VIM 9.0 (1-65)
  Has clientserver: true
  Servername: VIM

VimTeX project: minimal
  base: minimal.tex
  root: /Users/name/minimal/
  tex: /Users/name/minimal.tex
  main parser: fallback current file
  document class: 
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Skim
  qf method: LaTeX logfile
```
