### ISSUE TITLE
Sioyek doesn't open a new window

### ISSUE THREAD

**Issue by BonfireAtNight** [lervag/vimtex#2481]
### Description

First off, I'm not fully certain that the issue to be described is due to vimtex or to my window manager (i3). So, apology in advance if the problem is to be searched for elsewhere.
  
I've recently switched from Zathura to Sioyek. To reflect this, I've changed `"let g:vimtex_view_method = 'zathura'` to `let g:vimtex_view_method = 'sioyek'` (this is all I've done). If Sioyek is not yet running, issuing VimtexView opens up Sioyek as expected. However, if Sioyek is already running, it appears to be hidden under the running instance (or not visible in any way).

According to my i3 settings, SIoyek windows are embedded in different tabs on the same workspace. If I run VimtexView and _then_ open another Sioyek instance it appears in its own tab (but as explained, not the other way around). What makes me think that this may be a vimtex rather than an i3 issue, when I do the same with Zathura, it opens a new tab in all of the described scenarios (as expected).

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: ArcoLinux
  Vim version: NVIM v0.7.2
  Has clientserver: true
  Servername: /tmp/nvim083Gka/0

VimTeX project: XXX
  main parser: current file verified
  document class: scrartcl
  source files: XXX
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 0
    executable: latexmk
  viewer: sioyek
    job: 
      pid: -
      cmd: sioyek --reuse-instance --inverse-search "/usr/bin/nvim --headless -c     
cmd_start: sioyek --reuse-instance --inverse-search "/usr/bin/nvim --headless -c   qf method: LaTeX logfile
```
