### ISSUE TITLE
vimtex fzf does not show any texts [On Windows]

### ISSUE THREAD

**Issue by huweiATgithub** [lervag/vimtex#2486]
### Description

calling `:call vimtex#fzf#run()` does not contain any texts as shown in the image
![image](https://user-images.githubusercontent.com/37072526/189509264-0c4efe4a-7484-4eaf-8acc-dbf230a149e6.png)

However, vimtex-toc-open can show all information properly and fzf itself works (e.g. the `:History` command)

Running in Windows with the latest vimtex.
However, the same configuration in my other Linux laptop works without any issue.

I have no idea how to trace the issue further. Any suggestion is appreciated!

Information from vimtex-info-full

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS:  ()
  Vim version: NVIM v0.7.2
  Has clientserver: true
  Servername: \\.\pipe\nvim-25756-0

VimTeX project: ...
  base: ...
  root: ...
  tex: ...tex
  main parser: current file verified
  document class: article
  packages: ...
  compiler: latexmk
    root: ...
    target: ...
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
