### ISSUE TITLE
Multi-file detection for `_preamble.tex` and `_postamble.tex` files generated by Tectonic

### ISSUE THREAD

**Issue by parksb** [lervag/vimtex#2490]
### Description

Hi, I'm using Tectonic to compile documents by configuring `let g:vimtex_view_method = 'tectonic'`.

Tectonic recommends `tectonic -X new sample` command which generates `_preamble.tex`, `_postamble.tex`, and `index.tex` files under the `sample/src` directory to create a new TeX project. Each file contains:

```tex
% _preamble.tex
\documentclass{article}
\title{My Title}
\begin{document}
```

```tex
% index.tex
Hello, world.
```

```tex
% _postamble.tex
\end{document}
```

When I run `<localleader>ll` in the `index.tex` to compile, VimTex shows an error message. I found that VimTeX works if the contents of `_preamble.tex` and `_postamble.tex` are combined into `index.tex`, but I wonder if is there a way to use VimTeX without any modification to the directory generated by Tectonic.

### Steps to reproduce

1. `tectonic -X new sample`
2. `nvim sample/src/index.tex`
3. Run `<localleader>ll`.

### Expected behavior

VimTeX starts compilation.

### Actual behavior

VimTeX shows an error message:

```
VimTeX: Compilation error due to failed mainfile detection!
        Please ensure that VimTeX can locate the proper main .tex file.
        Read ":help vimtex-multi-file" for more info
```

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 12.4 (21F2081)
  Vim version: NVIM v0.7.2
  Has clientserver: true
  Servername: /var/folders/c9/kkczqw7d28bf31_wkkzmrhpr0000gn/T/nvimxiWFtQ/0

VimTeX project: index
  base: index.tex
  root: /Users/my/sample/src
  tex: /Users/my/sample/src/index.tex
  main parser: fallback current file
  document class: 
  compiler: tectonic
    options:
      --keep-logs
      --synctex
  viewer: General
  qf method: LaTeX logfile
```
```
