### ISSUE TITLE
Compilation error due to failed mainfile detection!

### ISSUE THREAD

**Issue by timoleistner** [lervag/vimtex#2491]
### Description

I'm using the moderncv package for which I have a "mainfile" which is called `moderncv.tex`.
This file contains `!% TeX root: moderncv.tex` on the first line and later on a `\documentclass`.
Then I have two other files, `letter.tex` and `cv.tex` which both `\include{moderncv.tex}` this file on their own. I want to compile these files using this mentioned "mainfile" for shared information.

This has been working before and after I've read the previous issues about this I'm wondering why you changed working code for stricter mainfile detection.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Arch Linux
  Vim version: NVIM v0.7.2
  Has clientserver: true
  Servername: /tmp/nvim9FEs4C/0

VimTeX project: letter
  base: letter.tex
  root: /home/timo/Documents/Bewerbungsunterlagen/moderncv
  tex: /home/timo/Documents/Bewerbungsunterlagen/moderncv/letter.tex
  main parser: fallback current file
  document class: moderncv
  packages: babel etoolbox fontenc geometry inputenc numprint ragged2e setspace
  source files:
    letter.tex
    moderncv.tex
  compiler: latexmk
    engine: -pdf
    options:
      -xelatex
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
