### ISSUE TITLE
Not compiling on save when PDF is open in Zathura

### ISSUE THREAD

**Issue by annTull** [lervag/vimtex#2498]
### Description

OK, here's a hard one to debug - that I have waited months to report so I could observe the behavior closely.

From time to time, I face a rather odd issue that, after a while, disappears with me doing nothing.

When the issue is present, I can initially compile `.tex` files from within Vim or GVim with vimtex (by pressing `\ll`) and everything works, the compilation in continuous mode is said to complete and the PDF is opened through Zathura. Now, if I introduce any changes to the document and save it (pressing `:w`), after the document is saved, the compilation fails () if the PDF is open in Zathura but completes if the PDF is closed.

As I said, when the issue is active, the above-described scenario happens with any `.tex` file, even MWE like:

```tex
\documentclass[]{article}

\title{My Test}
\author{Me}

\begin{document}

\maketitle

Text body.

\end{document}
```

The only lines I still have in my .vimrc that relate to vimtex are:

```vim
let g:vimtex_view_method = 'zathura'
let g:vimtex_quickfix_mode = 2
let g:vimtex_quickfix_open_on_warning = 0
let g:vimtex_quickfix_autoclose_after_keystrokes = 0
```

However, after a while, without me doing anything - neither closing Vim/GVim nor even rebooting the machine - the issue disappears and everything works as expected. The annoying problem is that sometimes the issue lasts for a relevant amount of time, making it impossible to work since changes to the `.tex` files I am working on do not get updated to the PDF unless I close it and open it again.

I wonder if you would have any idea on what may be going on? The only thing I could think of is some temporary issues with the background Zathura processes, in which case it would be unrelated to Vimtex per se, but perhaps some Vimtex-level workarounds could be thought out.

### Steps to reproduce

As described above, the issue happens when, while in continuous mode, I save any .tex file after changes but have the PDF currently opened in Zathura.

### Expected behavior

Normal successful compilation with the open PDF being eventually refreshed to the newly saved changes made to the `.tex` code.

### Actual behavior

Compilation fails.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 18.04.6 LTS
  Vim version: VIM 8.2 (1-4929)
  Has clientserver: true
  Servername: GVIM3

VimTeX project: test
  base: test.tex
  root: /media/tests
  tex: /media/tests/test.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
