### ISSUE TITLE
Zathura pdf not updating when saving TeX file in neovim v0.8.0

### ISSUE THREAD

**Issue by k-gomez** [lervag/vimtex#2502]
### Description

The pdf in the created zathura instance is not updating when I save a TeX file using `:w`.

## Versions
```
NVIM v0.8.0-dev-1132-g37a71d1f2
```

```
➜  ~ zathura -v
zathura 0.4.9
girara 0.3.7 (runtime: 0.3.7)
(plugin) pdf-poppler (0.3.0) (/usr/lib/x86_64-linux-gnu/zathura/libpdf-poppler.so
```
```
➜  ~ zathura -h
Usage:
  zathura [OPTION…]  [file1] [file2] [...]

Help Options:
  -h, --help                           Show help options

Application Options:
  -e, --reparent=xid                   Reparents to window specified by xid (X11)
  -c, --config-dir=path                Path to the config directory
  -d, --data-dir=path                  Path to the data directory
  --cache-dir=path                     Path to the cache directory
  -p, --plugins-dir=path               Path to the directories containing plugins
  --fork                               Fork into the background
  -w, --password=password              Document password
  -P, --page=number                    Page number to go to
  -l, --log-level=level                Log level (debug, info, warning, error)
  -v, --version                        Print version information
  -x, --synctex-editor-command=cmd     Synctex editor (forwarded to the synctex command)
  --synctex-forward=position           Move to given synctex position
  --synctex-pid=pid                    Highlight given position in the given process
  --mode=mode                          Start in a non-default mode
  -b, --bookmark=bookmark              Bookmark to go to
  -f, --find=string                    Search for the given phrase and display results
```

```
➜  ~ synctex help
This is SyncTeX command line utility, version 1.5
usage: synctex <subcommand> [options] [args]
Synchronize TeXnology command-line client, version 1.21

The Synchronization TeXnology by Jérôme Laurens is a rather new feature of recent TeX engines.
It allows to synchronize between input and output, which means to
navigate from the source document to the typeset material and vice versa.

Available subcommands:
   view     to perform forwards synchronization
   edit     to perform backwards synchronization
   update   to update a synctex file after a dvi/xdv to pdf filter
   help     this help

Type 'synctex help <subcommand>' for help on a specific subcommand.
There is also an undocumented test subcommand.
```

## Configuration

.vimrc
```
set encoding=utf8
filetype plugin indent on
syntax enable
let g:vimtex_view_method = 'zathura'
let maplocalleader = ","
```
No .zathurarc.

I have no other vim, neovim, or zathura instances open.

### Steps to reproduce

This is the process I follow when editing TeX files:
1. Open up vim (in my case neovim v0.8.0-dev-1132-g37a71d1f2)
2. Edit the TeX file
3. Run `:VimtexCompile`
4. Zathura opens
5. I change something in the TeX file (in neovim) and execute `:w`
6. The pdf in the zathura session does not update

When I run `:VimtexCompile` again with zathura opened, the pdf does not update. I have to close zathura first and run `:VimtexCompile` again to spawn a new zathura instance.

## Sometimes it works

Sometimes (but very rarely), the zathura pdf updates after saving the file. Yesterday I randomly closed neovim / zathura and executed :VimtexCompile (in no particular order) and it suddenly worked. However, I was not able to reproduce it yet.

### Expected behavior

`vimtex` automatically updates the pdf file in zathura when I save the TeX file with `:w`.

### Actual behavior

The pdf file in zathura is not updated when I change the TeX file and save with `:w`.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 22.04.1 LTS
  Vim version: NVIM v0.8.0-dev-1132-g37a71d1f2
  Has clientserver: true
  Servername: /run/user/1000/nvim.41425.0

VimTeX project: text
  base: text.tex
  root: /home/kgb/test
  tex: /home/kgb/test/text.tex
  main parser: current file verified
  document class: article
  packages: inputenc
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 5
      output: /tmp/nvim.kgb/zIMeaZ/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'text.tex'
      pid: 41478
  viewer: Zathura
    xwin id: 71303171
    cmd_start: zathura  -x "/home/kgb/tools/neovim/nvim-linux64/bin/nvim --headless -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 1:1:'/home/kgb/test/text.tex' 'text.pdf'&
  qf method: LaTeX logfile
```
