### ISSUE TITLE
mainfile detection fails if one inputs the file with \documentclass

### ISSUE THREAD

**Issue by druduche** [lervag/vimtex#2504]
### Description

Minimal example: Two files a.tex and b.tex in the same directory.
File a.tex: `\documentclass{article}`
File b.tex: `\input{a.tex} \begin{document} content \end{document}`

Compiling b.tex fails because of failed mainfile detection. It worked fine with previous (albeit old!) versions of vimtex (I only recently updated my configuration) 

Disclaimer: All my projects are structured that way. There are probably many different (better?) ways to structure them. However, I am interested in a solution to this problem, not in other ways to structure my projects.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Linux 5.19.9-arch1-1
  Vim version: VIM 9.0 (1-354)
  Has clientserver: true
  Servername: GVIM

VimTeX project: b
  base: b.tex
  root: /home/XXX/Documents/test
  tex: /home/XXX/Documents/test/b.tex
  main parser: fallback current file
  document class: article
  source files:
    b.tex
    a.tex
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: process 4830 dead
      output: /tmp/vimOgDz/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'b.tex'
      pid: 4830
  viewer: Zathura
    xwin id: 29360131
    cmd_start: zathura  -x "/usr/bin/vim -T dumb --not-a-term -n -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 3:23:'/home/XXX/Documents/test/b.tex' 'b_vimtex.pdf'&
  qf method: LaTeX logfile
```
