### ISSUE TITLE
\lc does not clean files on either debian linux or ubuntu linux.

### ISSUE THREAD

**Issue by jfgodfrey** [lervag/vimtex#2505]
### Description

After compiling with \ll, I run a \lc.  Checking in the directory, no files have been deleted.

### Steps to reproduce

1. vim -u minimal.vim minimal.tex.
2. \ll and produced expected output.
3. \lc, no errors reported.
4. No files were deleted by \lc.

### Expected behavior

I expected the files to be cleaned up.

### Actual behavior

No files were cleaned up.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Debian GNU/Linux 11 (bullseye)
  Vim version: VIM 8.2 (1-2434)
  Has clientserver: true
  Servername: undefined (vim started without --servername)

VimTeX project: minimal
  base: minimal.tex
  root: /home/johnfg/tmp
  tex: /home/johnfg/tmp/minimal.tex
  main parser: current file verified
  document class: minimal
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: process 28015 run
      output: /tmp/vstQsRa/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e '$compi
      pid: 28015
  viewer: General
    job: 
      pid: 28021
      cmd: xdg-open '/home/johnfg/tmp/minimal.pdf'
  qf method: LaTeX logfile
```
