### ISSUE TITLE
float.sty not found error while other .sty files are found fine

### ISSUE THREAD

**Issue by TryerGit** [lervag/vimtex#2508]
### Description

I am able to get VimTex to work fine on a windows subsystem for linux (WSL) installation. `\ll` compiles the .tex file below and produces an output pdf file.

```
\documentclass[11pt]{article}
\usepackage[latin9]{inputenc}
\usepackage{amsmath}
\usepackage{amsthm}
\usepackage{amssymb}
\usepackage{graphicx}
\usepackage[authoryear,comma]{natbib}

\makeatletter

\usepackage{latexsym}\usepackage{amsthm}\usepackage{graphics}\usepackage{epsfig}\usepackage{verbatim}\usepackage{array}

\begin{document}
\title{Test}
\maketitle
\begin{abstract}
Abstract goes here
\end{abstract}

\section{Introduction}
Introduction
\end{document}


```

However, on adding line `usepackage{float}`, I obtain an error that states that :

```
olddelete.tex|| File `float.sty' not found.
olddelete.tex|14 error| Emergency stop.
olddelete.tex|14 error| ==> Fatal error occurred, no output PDF file produced!

```

The file `float.sty` does exist on my windows folder structure in `C:\PCTeX\PCTeXv6\texmf-dist\tex\latex\float`. However, this is apparently not accessed from within WSL. All of the other packages such as `amsmath`, etc., are accessible.

Could it be clarified how I should go about having VimTex access `float.sty` from within WSL?

Thank you.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info
   OS: Ubuntu 20.04.3 LTS
   Vim version: VIM 8.1 (1-2269)
   Has clientserver: false

 VimTeX project: olddelete
   base: olddelete.tex
   root: /mnt/c/Users/doc  8   tex: /mnt/c/Users/doc/  9   main parser: current file verified
    document class: article
    packages: amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm array epsfig epstopdf-base graphics grap 12   compiler: latexmk
      engine: -pdf
      options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      callback: 1
      continuous: 1
      executable: latexmk
      job:
        jobid: process 391 run
        output: /tmp/vHmNeu3/1
        cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -e 26       pid: 391
    viewer: General
    qf method: LaTeX logfile
```
