### ISSUE TITLE
Slow left/right scrolling with long lines

### ISSUE THREAD

**Issue by zsteinberg** [lervag/vimtex#2512]
### Description

With certain long lines with lots of brackets, vimtex slows down noticeably when holding left/right to scroll through a page.

I used this python script to generate an example:

```
with open("example.tex", "w") as f:
  f.write("\\begin{document}\n")
  for i in range(2):
    f.write(str(i))
    for j in range(300):
      f.write(" \\frac {a}{b} ")
    f.write("\n")

  f.write("\\end{document}\n")
  ```
  
  Github won't let me attach a file that ends in .tex, so here's [example.txt](https://github.com/lervag/vimtex/files/9742468/example.txt).
  
  If you open example.txt with vim and try to scroll right, on my computer it looks like this, lag-free:

[scrolling_example_txt.webm](https://user-images.githubusercontent.com/1816168/194777643-520271c2-51fe-4286-b418-050f871bb768.webm)

 However, if you rename example.txt to example.tex, open it with neovim, and scroll right, the scrolling is full of lag:
 
[scrolling_laggy_tex.webm](https://user-images.githubusercontent.com/1816168/194777645-a59c178a-a609-450a-ac51-e3433fae395e.webm)

Interestingly, not all long lines cause this lag. I modified the above program to generate repeats of inline math, to make  
[nonexample.txt](https://github.com/lervag/vimtex/files/9742479/nonexample.txt). If you rename nonexample.txt to nonexample.tex, then open it with vimtex, there's only slight lag when scrolling - nowhere near the grinding to a halt we see when scrolling left/right with example.tex.

### Steps to reproduce

1. `nvim example.txt`.
2. press down once to go to line 2. Verify that holding down the right arrow key doesn't lag.
3. close nvim, and run `cp example.txt example.vim`.
4. `nvim example.vim`
5. press down once to go to line 2, then hold right. Note the lag.
6. Let go of the right arrow key and tap up once. Note how long it takes for nvim to stop pressing right and scroll up.

### Expected behavior

Scrolling right should behave like scrolling right on example.txt: nice and lag-free.

### Actual behavior

Scrolling is laggy. If I hold right, then press up/down, the up/down takes several seconds to complete.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info
  OS: Linux Mint 20.3
  Vim version: NVIM v0.4.3
  Has clientserver: true
  Servername: /tmp/nvimLlp8HP/0

VimTeX project: example                                                                                          base: example.tex
  root: /tmp
  tex: /tmp/example.tex
  main parser: current file
  document class: 
  compiler: latexmk                                                                                                engine: -pdf                                                                                                   options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1                                                                                                  executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
