### ISSUE TITLE
`g:vimtex_compiler_latexmk` ignored

### ISSUE THREAD

**Issue by StevenWhitaker** [lervag/vimtex#2514]
### Description

I have the same problem reported in #2336, in that `g:vimtex_compiler_latexmk` is set but ignored. Somehow the linked issue was resolved, but it wasn't clear how.

Basically, I want all the build files to go to a build/ directory, but I haven't been able to get it to work.

# ~/.config/nvim/after/ftplugin/tex.lua
```lua
vim.cmd[[
let g:vimtex_view_general_viewer = 'okular'
let g:vimtex_view_general_options = '--unique file:@pdf\#src:@line@tex'
let g:vimtex_compiler_latexmk = {
    \ 'build_dir': 'build',
    \}
]]
```
I've also tried putting this directly in my init.lua, to no avail. I've also verified that `g:vimtex_view_general_options` does work.

### Expected behavior

A build/ directory should be created and populated with all the LaTeX build files.

### Actual behavior

The LaTeX build files populate the current directory.

### Do you use a latexmkrc file?

Yes, but the problem also occurs when not using one.

### VimtexInfo

```yaml
System info:
  OS: Manjaro Linux
  Vim version: NVIM v0.8.0
  Has clientserver: true
  Servername: /run/user/1000/nvim.12365.0

VimTeX project: main
  base: main.tex
  root: /home/steven/tmp/latex
  tex: /home/steven/tmp/latex/main.tex
  main parser: current file verified
  document class: article
  packages: main
  source files:
    main.tex
    hello.tex
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
