### ISSUE TITLE
Statusline flickering when typing with Heirline.

### ISSUE THREAD

**Issue by Bahnschrift** [lervag/vimtex#2518]
### Description

Hi,
I'm using this plugin with [AstoNvim](https://github.com/AstroNvim/AstroNvim/) which recently switched from using Feline to Heirline for the statusbar. Since this change, I've noticed that the statusbar flickers whenever typing in insert mode.
![Flickering](https://user-images.githubusercontent.com/31170809/196143508-55f4699e-5072-418f-9a99-fdf4fc1cd771.gif)

I've confirmed that the flickering doesn't occur when vimtex is disabled. I've also tried ensuring that vimtex loads after heirline, but that didn't seem to help.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 22.04.1 LTS
  Vim version: NVIM v0.8.0-1210-gd367ed9b2
  Has clientserver: true
  Servername: /mnt/wslg/runtime-dir/nvim.12901.0

VimTeX project: q1
  base: q1.tex
  root: /home/kbeck/COMP3121/ass/ass03
  tex: /home/kbeck/COMP3121/ass/ass03/q1.tex
  main parser: current file verified
  document class: article
  packages: amsfonts amsmath mleftright parskip subcaption tikz
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
