### ISSUE TITLE
Undefined control sequence, but don't display more detail

### ISSUE THREAD

**Issue by Freed-Wu** [lervag/vimtex#2526]
### Description

When I `latexmk`,

```
./2022-10-21.tex:89: Undefined control sequence.
<recently read> \cdashline

l.89 \end{frame}

?
```

However, in vimtex, it don't display any information about this control 
sequence's name.

```
...
2022-10-21.tex|89 error| Undefined control sequence.
2022-10-21.tex|89 warning| Overfull \hbox (68.54958pt too wide) in paragraph at lines 89--89
...
```

I think `&errorfmt` should be rewrite to display its name.

Thanks!

### Do you use a latexmkrc file?

Yes

### VimtexInfo

```yaml
System info:
  OS: Arch Linux
  Vim version: NVIM v0.8.0
  Has clientserver: true
  Servername: /run/user/1000/nvim.1399382.0

VimTeX project: 2022-10-17
  base: 2022-10-17.tex
  root: /home/wzy/Documents/weekly-report
  tex: /home/wzy/Documents/weekly-report/2022-10-17.tex
  main parser: recursive search (bib)
  document class: article
  packages: array autofancyhdr geometry hyperref longtable natbib parskip xcolor xspace
  compiler: latexmk
    engine: -xelatex
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
