### ISSUE TITLE
VimTex can't find log file

### ISSUE THREAD

**Issue by tyalie** [lervag/vimtex#2534]
### Description

VimTex cannot find the log file when latexmk is used together with `$emulate_aux=1`. When using `:VimtexErrors` (or similar) in Vim, the message `VimTeX: No log file found` appears.

### Steps to reproduce

1. Create `.latexmk` with:
    ```perl
    $emulate_aux = 1
    $out_dir = "gen"
    $aux_dir = ".aux"
    ```
2. open vim and compile
3. try to use `:VimtexErrors`

### Do you use a latexmkrc file?

Yes

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 22.04.1 LTS
  Vim version: NVIM v0.7.2
  Has clientserver: true
  Servername: /tmp/nvimo5jleA/0

VimTeX project: main
  base: main.tex
  root: /project
  tex: /project/main.tex
  main parser: current file verified
  document class: IEEEtran
  packages: base
  source files:
    main.tex
    chapters/01_introduction.tex
  compiler: latexmk
    engine: -lualatex
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    build_dir: gen
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 19
      output: /tmp/nvimo5jleA/2
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -lualatex -outdir=gen -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'main.tex'
      pid: 1460577
  viewer: General
  qf method: LaTeX logfilel
```
