### ISSUE TITLE
Cosmetic issues with formatting of the text displayed for a closed fold

### ISSUE THREAD

**Issue by PatrBal** [lervag/vimtex#2545]
### Description

The formatting of the text displayed for a closed fold is based on an incorrect estimation of the full width of the current window. This issue is actually two-folds.
1) If there is no signcolumn, then the full width is underestimated of 1. In the case of a folded labelled environment, this results in an unaethestic '·' at the end of the text displayed for the closed fold.
2) If there is a signcolumn, its width is not taken into account in the estimation of the full width of the current window. If the width is larger than 1, this results in the fact that the label of a folded labelled environment is not entirely displayed.

### Steps to reproduce

[minimal.vim.zip](https://github.com/lervag/vimtex/files/9895962/minimal.vim.zip)
[minimal.tex.zip](https://github.com/lervag/vimtex/files/9895965/minimal.tex.zip)

1. `nvim -u minimal.vim ~/Desktop/minimal.tex`
2. The equation environment should be folded and a '·' is visible at the end of the text displayed for the closed fold.
3. Type `:set scl=yes:5`
4. The label of the folded equation is no longer entirely visible.

### Expected behavior

The closing parentheses of the label of a folded labelled environment should be the last character of the line in any case.

### Do you use a latexmkrc file?

Yes

### VimtexInfo

```yaml
System info:
  OS: macOS 13.0 (22A380)
  Vim version: NVIM v0.8.0
  Has clientserver: true
  Servername: /tmp/nvimsocket

VimTeX project: minimal
  base: minimal.tex
  root: /Users/patrick.ballard/Desktop
  tex: /Users/patrick.ballard/Desktop/minimal.tex
  main parser: current file verified
  document class: minimal
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
