### ISSUE TITLE
%TODO & %FIXME not appearing in TOC

### ISSUE THREAD

**Issue by HawkinsT** [lervag/vimtex#2546]
### Description

If there's no space between `%` the keyword `TODO` or `FIXME`, then this line will not appear in the Vimtex TOC under the todo/fixme section. Since vim and neovim both still highlight these keywords if they're written as, e.g. `%TODO` (instead of `% TODO`), I'd expect them to still show up in the todo/fixme list in the Vimtex TOC.

### Do you use a latexmkrc file?

Sometimes

### VimtexInfo

```yaml
System info:
  OS: Arch Linux
  Vim version: NVIM v0.9.0-dev-136-gfad558b6a
  Has clientserver: true
  Servername: /run/user/1000/nvim.450305.0

VimTeX project: main
  base: main.tex
  root: /home/username
  tex: /home/username/main.tex
  main parser: fallback current file
  document class: 
  compiler: latexmk
    engine: -lualatex
    options:
      -pdflatex=lualatex
      -pdf
      -shell-escape
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
