### ISSUE TITLE
`lstlisting` environment it not treated as `verbatim`, which results in several false positives

### ISSUE THREAD

**Issue by c-h-e-n-e-l** [lervag/vimtex#2553]
### Description

Vim or Vimtex (not sure which is responsible) does not treat text inside of listing environments  like verbatim, which spawns many whitespace related errors (i.e. space before punctuation marks, etc.). I've found somewhat of an answer on StackExchange [here](https://tex.stackexchange.com/questions/285301/ignore-errors-in-environments-in-latex-suite-in-vim), however this seems to be outdated, and does not work. After a bit of researching I've found that in order to solve this I simply need to add listings to append the `texzone` variable, which will make vim ignore all errors within the confines of the listing. I'd like to know how I can accomplish this, I believe that [this piece of code](https://github.com/vim/vim/blob/master/runtime/syntax/tex.vim#L639) is concerned.

### Steps to reproduce

1. use any general listing environment

### Expected behavior

treat the listing environment as verbatim

### Actual behavior

does not treat the listing environment as verbatim

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:                                                                                  1   OS: Ubuntu 20.04.5 LTS
  Vim version: VIM 8.1 (1-2269, 3612, 3625, 3669, 3741)
  Has clientserver: false

VimTeX project: c5x-2-ln
  base: c5x-2-ln.tex
  root: /mnt/c/users/chenel/dropbox/arc/hv/c5x/2/ln
  tex: /mnt/c/users/chenel/dropbox/arc/hv/c5x/2/ln/c5x-2-ln.tex
  main parser: current file verified
  document class: article
  packages: caption caption3 epstopdf-base float fontenc geometry graphics graphicx iftex if 
  compiler: latexmk
   engine: -pdf
   options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
   executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
