### ISSUE TITLE
Question: unknown green vertical bar on the left side of vim

### ISSUE THREAD

**Issue by m-zheng** [lervag/vimtex#2562]
### Description

After installing vimtex, somehow an unknown green vertical bar pops up on the left side of vim as shown in the picture below. I am not sure if it is related to my [other vim plugins](https://github.com/amix/vimrc). Do you happen to know what it is? If yes, is there any way to turn it off?
![Screenshot from 2022-11-08 10-33-04](https://user-images.githubusercontent.com/18236342/200543480-57705dd5-1827-499a-8250-653d7993841e.png)

The latexmkrc is borrowed from [overleaf](https://www.overleaf.com/learn/how-to/How_does_Overleaf_compile_my_project%3F#A_listing_of_Overleaf.E2.80.99s_LatexMk_file_.282022.29).

### Steps to reproduce

write some latex code and save it.

### Expected behavior

No green vertical bar on the left side of vim.

### Actual behavior

No green vertical bar on the left side of vim. Everything is normal.

### Do you use a latexmkrc file?

yes

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 20.04 LTS
  Vim version: VIM 9.0 (1-749)
  Has clientserver: true
  Servername: undefined (vim started without --servername)

VimTeX project: thesis
  base: thesis.tex
  root: /home/xxx/xxx
  tex: /home/xxx/xxx/thesis.tex
  main parser: current file verified
  document class: Classes/PhDThesisPSnPDF
  packages: algorithm2e amsbsy amsfonts amsgen amsmath amsopn amssymb amstext appendix array atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook bigintcalc bitset bm booktabs calc calrsfs caption caption3 color datetime datetime-defaults dsfont epstopdf epstopdf-base etexcmds etoolbox everypage expl3 fancyhdr fcnumparser fcprefix fmtcount fontenc geometry gettitlestring graphics graphicx grfext hycolor hyperref ifoddpage ifpdf iftex ifthen ifvtex ifxetex infwarerr inputenc intcalc keyval kvdefinekeys kvoptions kvsetkeys l3keys2e letltxmacro lineno lscape ltxcmds makeidx mathptmx microtype multirow nameref natbib nomencl pdfescape pdftexcmds refcount relsize rerunfilecheck scrbase scrlfile scrlfile-hook scrlogo setspace siunitx subcaption textcomp textpos tocbasic tocbibind translations trig uniquecounter url xkeyval xspace
  source files:
    thesis.tex
    Preamble/preamble.tex
    thesis-info.tex
    Chapter3/chapter3.tex

  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: process 863605 run
      output: /tmp/vouIzoM/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'thesis.tex'
      pid: 863605
  viewer: Zathura
    xwin id: 0
    cmd_start: zathura  -x "/usr/bin/vim.gtk3 -T dumb --not-a-term -n -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 20:1:'/home/xxx/xxx//Chapter3/chapter3.tex' 'thesis.pdf'&
  qf method: LaTeX logfile
```
