### ISSUE TITLE
Zathura not starting on compile

### ISSUE THREAD

**Issue by iStagnant** [lervag/vimtex#2564]
### Description

Whenever i `<leader>ll` or `:VimtexCompile` the file compiles but zathura does not open and vimtex returns

`Zathura is not linked to libsynctex!` and `Viewer cannot find Zathura window ID!`.
If I manually open zathura and save the file the changes appear, but `<leader>lv` does not work.
Running `zathura -v` returns `error: Built without synctex support, but synctex specific option was specified.` which makes me think that the problem is with the installation of zathura even though i have libsynctex installed. I saw this exact issue here but it was for mac and the solution was adding `--with-synctex` when installing zathura, I tried reinstalling zathura and even installing zathura-git from the aur ~which didn't compile and returned an error, fun~ and nothing worked

### Expected behavior

Zathura opening and `<leader>lv` functionning.

### Actual behavior

Zathura does not start and i have to start it manually, and `<leader>lv` does not work.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Linux 6.0.7-artix1-1
  Vim version: NVIM v0.8.0
  Has clientserver: true
  Servername: /run/user/1000/nvim.2955.0

VimTeX project: mwe
  base: mwe.tex
  root: /home/elias/Desktop
  tex: /home/elias/Desktop/mwe.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 5
      output: /tmp/nvim.elias/PKhGel/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'mwe.tex'
      pid: 2961
  viewer: Zathura
    xwin id: 0
    cmd_start: zathura  -x "/usr/bin/nvim --headless -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 1:1:'/home/elias/Desktop/mwe.tex' 'mwe.pdf'&
  qf method: LaTeX logfile
```
