### ISSUE TITLE
<localleader> doesn't respond

### ISSUE THREAD

**Issue by Manuelmik** [lervag/vimtex#2568]
### Description

Hi! I'm using Lunarvim, installed the plugin with packer and copied the configuration into `init.vim`.

My issue is that `<localleader>` doesn't do anything. Same issue if I remap localleader (`let maplocalleader = "ö"`). E.g. if I press `öll` it just recognizes l and moves the curser one character to the left. If I use `\ll` simply nothing happens.

Another problem is that if I use `:VimtexCompile` it opens my PDF in a browser, although I set up zathura  (`let g:vimtex_view_method = 'zathura'`).

### Do you use a latexmkrc file?

No, but I got an `*.fdb_latexmk`.

### VimtexInfo

```yaml
System info:
  OS: phyOS
  Vim version: NVIM v0.8.1
  Has clientserver: true
  Servername: /run/user/1000/nvim.23417.0

VimTeX project: test
  base: test.tex
  root: /home/manuel/latex/projects
  tex: /home/manuel/latex/projects/test.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
