### ISSUE TITLE
Reverse and forward search with zathura suddenly stopped working

### ISSUE THREAD

**Issue by gzqx** [lervag/vimtex#2573]
### Description

I am using Fedora so I am not sure if it is because the newest version of vim/zathura break it. (VIM - Vi IMproved 9.0, zathura 0.4.9)

 The reverse and forward search of zathura has been working till this week.

Now, when I `\ll`, I get `VimTeX: Viewer cannot find Zathura window ID!`. Reverse search from Zathura to vim also doesn't work now.

### Steps to reproduce

1. Add `let g:vimtex_view_method='zathura'` to example minimal test file
2. `\ll`

### Expected behavior

Search normally.

### Actual behavior

`VimTeX: Viewer cannot find Zathura window ID!`

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Linux 6.0.8-200.fc36.x86_64
  Vim version: VIM 9.0 (1-828)
  Has clientserver: true
  Servername: VIM

VimTeX project: minimal
  base: minimal.tex
  main parser: current file verified
  document class: minimal
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: process 525006 run
      output: /tmp/vSx92Jv/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e '$compiling_cmd = ($compilin
      pid: 525006
  viewer: Zathura
    xwin id: 0
    cmd_start: zathura  -x "/usr/bin/gvim -T dumb --not-a-term -n -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 1:1:'
  qf method: LaTeX logfile
```
