### ISSUE TITLE
Viewer/compiler doesn't work?

### ISSUE THREAD

**Issue by Yeet7** [lervag/vimtex#2578]
### Description

Sorry for the post in here, just didn't know where else to put it. Not sure if this is a VimTeX thing or if it's okular.

So basically title. I'll link my .vimrc, the .tex file, and all errors at the end of the post.

**tldr**; Okular says it has 2 instances running and that it can't open my file. I don't get why. I've tried most of the other viewers and compilers, none of them seem to be working either. All of the compilers I've tried spit out the error VimtexCompile is not a command.

Basically, I've been trying to follow the vimtex installation guide and such, but I haven't had any luck with the viewers. Compiling works beutifully. I type ":VimtexCompile", and within a second it sends back "Compiled Successfully." However, after that, it tries to boot okular, the viewer I chose. Theres two problems after this. Okular first says "There is already a unique Okular Instance running. This instance won't be the unique one." Which makes no sense as there is nothing showing in Task Manager. After that, it says " Could not open file: ..." (Also, just as a side note, after the errors, if I want to reproduce them, I have to restart the entire file.)

**ps**; the file 100% compiles perfectly in LaTeX. Preamble, macros, and letterfonts are all just creating different macros.
also, the Vimtex info file is all hand typed. I went through it but something may be spelled wrong. My copy and paste doesn't work either for some reason. Tried a bunch of things, nothing works. Oh well.

**Pics**;

* [.vimrc](https://gyazo.com/ee6f1bedf4f8360e398d10c9dd1ef137)
* [.tex file](https://gyazo.com/55b96581eb33f9fcaaefaa4c397d5422)
* [okular err. 1](https://gyazo.com/04e6e87ad3c7f45c27e12f695cc99130)
* [okular err. 2](https://gyazo.com/53daa3614de38c220270f9e0245192b9)

### Steps to reproduce

I don't know how to describe the amount of steps I took to get here. Most of my code is jumbled together through many sources while I was trying to fix so many issues. (most were my fault)

### Expected behavior

For okular to compile the file correctly?

### Actual behavior

Two errors. One saying there are multiple existences, the other saying it can't load the file.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
    OS: Desktop-SM7V63K (Microsoft Windows 10 Home)
    Vim version: VIM 9.0 ()
    Has clientserver: true
    Servername: VIM1

VimTex project: what
    base: what.tex
    root: C:\Users\[REDACTED]\Desktop\Math\Math
    tex: C:\Users\[REDACTED]\Desktop\Math\Math\what.tex
    main parser: current file verifies
    document class: report
    packages: algorithm2e amsfonts amsmath amssymb amsthm array bookmark cancel comment enumitem etoolbox geometry hyperref import mathtools multicol nameref newpxmath pdfpages tcolorbox theoremref tikz tikz-cd tikzsymbols titletoc transparent varwidth xcolor xfrac xifthen
    source files:
        what.tex
        preamble.tex
        macros.tex
        letterfonts.tex
    compiler: arara
        options:
            --log
    viewer: General
    qf method: LaTeX logfile
```
