### ISSUE TITLE
Not all of the default text-objects are being defined

### ISSUE THREAD

**Issue by mroavi** [lervag/vimtex#2587]
### Description

Running `:om` results in:

```
:om
o  %            @<Plug>(vimtex-%)
o  [*           @<Plug>(vimtex-[*)
o  [/           @<Plug>(vimtex-[/)
o  [r           @<Plug>(vimtex-[r)
o  [R           @<Plug>(vimtex-[R)
o  [N           @<Plug>(vimtex-[N)
o  [m           @<Plug>(vimtex-[m)
o  [M           @<Plug>(vimtex-[M)
o  [[           @<Plug>(vimtex-[[)
o  []           @<Plug>(vimtex-[])
o  ]*           @<Plug>(vimtex-]*)
o  ]/           @<Plug>(vimtex-]/)
o  ]r           @<Plug>(vimtex-]r)
o  ]R           @<Plug>(vimtex-]R)
o  ]N           @<Plug>(vimtex-]N)
o  ]m           @<Plug>(vimtex-]m)
o  ]M           @<Plug>(vimtex-]M)
o  ][           @<Plug>(vimtex-][)
o  ]]           @<Plug>(vimtex-]])
o  am           @<Plug>(vimtex-am)
o  aP           @<Plug>(vimtex-aP)
o  a$           @<Plug>(vimtex-a$)
o  ad           @<Plug>(vimtex-ad)
o  im           @<Plug>(vimtex-im)
o  iP           @<Plug>(vimtex-iP)
o  i$           @<Plug>(vimtex-i$)
o  <Plug>(vimtex-am) *@:<C-U>call vimtex#text_obj#items(0, 0)<CR>
o  <Plug>(vimtex-im) *@:<C-U>call vimtex#text_obj#items(1, 0)<CR>
o  <Plug>(vimtex-aP) *@:<C-U>call vimtex#text_obj#sections(0, 0)<CR>
o  <Plug>(vimtex-iP) *@:<C-U>call vimtex#text_obj#sections(1, 0)<CR>
o  <Plug>(vimtex-a$) *@:<C-U>call vimtex#text_obj#delimited(0, 0,'math')<CR>
o  <Plug>(vimtex-i$) *@:<C-U>call vimtex#text_obj#delimited(1, 0,'math')<CR>
o  <Plug>(vimtex-ae) *@:<C-U>call vimtex#text_obj#delimited(0, 0,'normal')<CR>
o  <Plug>(vimtex-ie) *@:<C-U>call vimtex#text_obj#delimited(1, 0,'normal')<CR>
o  <Plug>(vimtex-ad) *@:<C-U>call vimtex#text_obj#delimited(0, 0,'delims')<CR>
o  <Plug>(vimtex-id) *@:<C-U>call vimtex#text_obj#delimited(1, 0,'delims')<CR>
o  <Plug>(vimtex-ac) *@:<C-U>call vimtex#text_obj#commands(0, 0)<CR>
o  <Plug>(vimtex-ic) *@:<C-U>call vimtex#text_obj#commands(1, 0)<CR>
o  <Plug>(vimtex-[*) *@:execute "normal \<SNR>153_(V)" . v:count1 . "\<SNR>153_(vimtex-[*)"<CR>
o  <Plug>(vimtex-[/) *@:execute "normal \<SNR>153_(V)" . v:count1 . "\<SNR>153_(vimtex-[/)"<CR>
o  <Plug>(vimtex-]*) *@:execute "normal \<SNR>153_(V)" . v:count1 . "\<SNR>153_(vimtex-]*)"<CR>
o  <Plug>(vimtex-]/) *@:execute "normal \<SNR>153_(V)" . v:count1 . "\<SNR>153_(vimtex-]/)"<CR>
o  <Plug>(vimtex-[R) *@:execute "normal \<SNR>153_(V)" . v:count1 . "\<SNR>153_(vimtex-[R)"<CR>
o  <Plug>(vimtex-[r) *@:execute "normal \<SNR>153_(V)" . v:count1 . "\<SNR>153_(vimtex-[r)"<CR>
o  <Plug>(vimtex-]R) *@:execute "normal \<SNR>153_(V)" . v:count1 . "\<SNR>153_(vimtex-]R)"<CR>
o  <Plug>(vimtex-]r) *@:execute "normal \<SNR>153_(V)" . v:count1 . "\<SNR>153_(vimtex-]r)"<CR>
o  <Plug>(vimtex-[M) *@:execute "normal \<SNR>153_(V)" . v:count1 . "\<SNR>153_(vimtex-[M)"<CR>
o  <Plug>(vimtex-[m) *@:execute "normal \<SNR>153_(V)" . v:count1 . "\<SNR>153_(vimtex-[m)"<CR>
o  <Plug>(vimtex-]M) *@:execute "normal \<SNR>153_(V)" . v:count1 . "\<SNR>153_(vimtex-]M)"<CR>
o  <Plug>(vimtex-]m) *@:execute "normal \<SNR>153_(V)" . v:count1 . "\<SNR>153_(vimtex-]m)"<CR>
o  <Plug>(vimtex-[N) *@:execute "normal \<SNR>153_(V)" . v:count1 . "\<SNR>153_(vimtex-[N)"<CR>
o  <Plug>(vimtex-[n) *@:execute "normal \<SNR>153_(V)" . v:count1 . "\<SNR>153_(vimtex-[n)"<CR>
o  <Plug>(vimtex-]N) *@:execute "normal \<SNR>153_(V)" . v:count1 . "\<SNR>153_(vimtex-]N)"<CR>
o  <Plug>(vimtex-]n) *@:execute "normal \<SNR>153_(V)" . v:count1 . "\<SNR>153_(vimtex-]n)"<CR>
o  <Plug>(vimtex-[[) *@:execute "normal \<SNR>153_(V)" . v:count1 . "\<SNR>153_(vimtex-[[)"<CR>
o  <Plug>(vimtex-[]) *@:execute "normal \<SNR>153_(V)" . v:count1 . "\<SNR>153_(vimtex-[])"<CR>
o  <Plug>(vimtex-][) *@:execute "normal \<SNR>153_(V)" . v:count1 . "\<SNR>153_(vimtex-][)"<CR>
o  <Plug>(vimtex-]]) *@:execute "normal \<SNR>153_(V)" . v:count1 . "\<SNR>153_(vimtex-]])"<CR>
o  <Plug>(vimtex-%) *@:execute "normal \<SNR>153_(v)\<SNR>153_(vimtex-%)"<CR>
```

Some of the operator-pending mode mappings which should be defined by default according to `:h vimtex-default-mappings` are not being defined. For example, the environment operator `ae` and `ie` is not being defined.

Nvim version:
```
:version
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

Vimtex version: latest

### Steps to reproduce

1. Open a `.tex` file in nvim.
2. Run `:om`

### Expected behavior

All operator-pending mode mappings in `:h vimtex-default-mappings` should be defined.

### Actual behavior

Not all operator-pending mode mappings in `:h vimtex-default-mappings` should be defined.

### Do you use a latexmkrc file?

Yes

### VimtexInfo

```yaml
System info:
  OS: Manjaro Linux
  Vim version: NVIM v0.8.0
  Has clientserver: true
  Servername: /run/user/1000/nvim.8619.0

VimTeX project: paper
  base: paper.tex
  root: /home/mroavi/repos/___2023/paper
  tex: /home/mroavi/repos/___2023/paper/paper.tex
  main parser: current file verified
  document class: juliacon
  packages: algorithm algorithmicx algpseudocode amsbsy amsfonts amsgen amsmath amsopn amssymb amstext atbegshi atbegshi-ltx atveryend atveryend-ltx authblk auxhook bigintcalc bitset bm booktabs calc cancel caption caption3 catchfile circledsteps epstopdf-base esvect etexcmds etoolbox eurosym float fontenc gettitlestring graphics graphicx grfext helvet hycolor hyperref ifluatex ifmtarg ifplatform iftex ifthen infwarerr inputenc intcalc jlcode keyval kvdefinekeys kvoptions kvsetkeys latexsym letltxmacro listings lstmisc ltxcmds nameref pdfescape pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfplots pgfrcs pgfsys pict2e picture refcount rerunfilecheck scrbase scrlfile scrlfile-hook scrlogo shellesc subcaption svg textcomp tikz times transparent trig trimspaces uniquecounter url xcolor xcolor-material xifthen
  source files:
    paper.tex
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    build_dir: build
    callback: 1
    continuous: v:true
    executable: latexmk
    job: 
      jobid: 97
      output: /tmp/nvim.mroavi/fRQ4jS/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -outdir=build -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'paper.tex'
      pid: 28141
  viewer: General
    job: 
      pid: -
      cmd: okular --unique file:'/home/mroavi/repos/___2023/paper/build/paper.pdf'\#src:177'/home/mroavi/repos/___2023/paper/paper.tex'
  qf method: LaTeX logfile
```
