### ISSUE TITLE
Compile tex, skim is not responding

### ISSUE THREAD

**Issue by PEKEW** [lervag/vimtex#2589]
### Description

Hi, I configured vimtex with NeoVIM, but previewing with skim is frequently not responding when I compile a tex file. The timeline of the issue is as follows:
- Earlier: Repeated compilation many times, not responding
- Later: When Skim's reload is turned on automatically, modify the text of the figure and algorithm. It is not responding.
- Now: Just compile, not responding.
The tex document in question is a template I downloaded from the IEEE trans, and I checked it for no errors. However, I didn't get any exceptions when I compiled another beamer file.

my config:
```
if ( g:is_win || g:is_mac ) && executable('latex')
  " Hacks for inverse search to work semi-automatically,
  " see https://jdhao.github.io/2021/02/20/inverse_search_setup_neovim_vimtex/.
  function! s:write_server_name() abort
    let nvim_server_file = (has('win32') ? $TEMP : '/tmp') . '/vimtexserver.txt'
    call writefile([v:servername], nvim_server_file)
  endfunction

  augroup vimtex_common
    autocmd!
    autocmd FileType tex call s:write_server_name()
    autocmd FileType tex nmap <buffer> <F9> <plug>(vimtex-compile)
  augroup END

  let g:vimtex_compiler_latexmk = {
        \ 'build_dir' : 'build',
        \ }

  " TOC settings
  let g:vimtex_toc_config = {
        \ 'name' : 'TOC',
        \ 'layers' : ['content', 'todo', 'include'],
        \ 'resize' : 1,
        \ 'split_width' : 30,
        \ 'todo_sorted' : 0,
        \ 'show_help' : 1,
        \ 'show_numbers' : 1,
        \ 'mode' : 2,
        \ }


    "let g:vimtex_view_general_viewer = '/Applications/Skim.app/Contents/SharedSupport/displayline'
    "let g:vimtex_view_general_options = '-r @line @pdf @tex'
"    let g:vimtex_view_method = 'skim'
let g:vimtex_compiler_progname = 'nvr'
let g:vimtex_compiler_latexmk = {
\ 'backend' : 'nvim',
\ 'background' : 1,
\ 'build_dir' : '',
\ 'callback' : 1,
\ 'continuous' : 1,
\ 'executable' : 'latexmk',
\ 'options' : [
\ '-pvc',
\ '-shell-escape',
\ '-verbose',
\ '-file-line-error',
\ '-synctex=1',
\ '-interaction=nonstopmode',
\ ]}

endif

```

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 12.3 (21E230)
  Vim version: NVIM v0.8.0
  Has clientserver: true
  Servername: /var/folders/qz/fnb_5_7101l4_5_m58kxxc_40000gn/T/nvim.mac/VZX7Ix/nvim.39759.0

VimTeX project: New_IEEEtran_how-to
  base: New_IEEEtran_how-to.tex
  root: /Volumes/H/conserved sequence/IEEE-Transactions-LaTeX2e-templates-and-instructions
  tex: /Volumes/H/conserved sequence/IEEE-Transactions-LaTeX2e-templates-and-instructions/New_IEEEtran_how-to.tex
  main parser: current file verified
  document class: IEEEtran
  packages: algorithm algorithmic amsbsy amsfonts amsgen amsmath amsopn amstext array balance caption3 epstopdf-base float graphics graphicx ifthen keyval stfloats subfig textcomp trig url verbatim
  compiler: latexmk
    engine: -pdf
    options:
      -pvc
      -shell-escape
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
```
