### ISSUE TITLE
Viewer cannot find Zathura window ID

### ISSUE THREAD

**Issue by qihangL** [lervag/vimtex#2591]
### Description

I followed the steps in vimtex-faq-zathura-macos, but still got error message "VimTeX: Viewer cannot find Zathura window ID!". 

### Steps to reproduce

`.SpaceVim/autoload/SpaceVim.vim` has no change

 ---

`minimal.tex`
```tex
\documentclass{article}
\begin{document}
testtesttest
\end{document
```

---

`init.toml` (only show changes related to vimtex)
```toml
[options]
# something else
    bootstrap_before = 'mytex#before
[[layers]]
name = 'lang#latex'
#something else
```
---

`.SpaceVim/autoload/mytex.vim`
```vim
function! mytex#before() abort
    let g:vimtex_view_method = "zathura"
endfunction
```

---

### Steps:
1. `nvim minimal.tex`
2. `[SPC]l-l`
3. `[SPC]l-v`

---

### Other information

```shell
echo $DBUS_SESSION_BUS_ADDRESS
``` 
gives 
> unix:path=/private/tmp/com.apple.launchd.sGCW1uDyJn/unix_domain_listener

```shell
grep "<auth>" /opt/homebrew/Cellar/dbus/1.14.4/share/dbus-1/session.conf
```
gives 
> comment out the <auth> element to allow fallback to DBUS_COOKIE_SHA1. -->
  <auth>DBUS_COOKIE_SHA1</auth>

### Expected behavior

open Zathura with the pdf

### Actual behavior

error message "VimTeX: Viewer cannot find Zathura window ID!". 

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 13.0.1 (22A400)
  Vim version: NVIM v0.8.1
  Has clientserver: true
  Servername: /var/folders/9c/rx7zrllj0cx0wdsqswlk1y500000gn/T/nvim.qihang/VlYoO7/nvim.1488.0

VimTeX project: main
  base: main.tex
  root: /Users/qihang/Documents/experiments
  tex: /Users/qihang/Documents/experiments/main.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
```
