### ISSUE TITLE
\cite{ and \ref{ not triggering autocompletion

### ISSUE THREAD

**Issue by stervel** [lervag/vimtex#2592]
### Description

Hello. I've seen the similar problem on this one but it's locked so I open a new issue.

I can not seem to make `\cite{` and `\ref{` autocompletion work.

Can you point where I probably miss?

### Steps to reproduce

Consider this MWE where `example.bib` is any bib generated by Zotero using BBT.

```
\documentclass{minimal}

\usepackage[backend=biber]{biblatex}
\addbibresource{example.bib}

\begin{document}

\begin{figure}[]
  \centering
  \includegraphics[width=\linewidth]{example.png}
  \label{fig:example}
\end{figure}

\ref{fig:example} % <-- not autocompleted

\cite{key1} \parencite{key2} \textcite{key3} % <-- not autocompleted

\end{document}
```

Both `\ref{` and `\cite{` (and other variations) are not triggering any autocomplete.

### Do you use a latexmkrc file?

I don't think this is relevant.

### VimtexInfo

```yaml
System info:
  OS: Linux 6.0.8-arch1-1
  Vim version: NVIM v0.8.0
  Has clientserver: true
  Servername: /run/user/1000/nvim.8619.0

VimTeX project: test
  base: test.tex
  root: /home/andre/Documents
  tex: /home/andre/Documents/test.tex
  main parser: current file verified
  document class: article
  packages: biblatex
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: sioyek
  qf method: LaTeX logfile
```
```
