### ISSUE TITLE
Problem with Skim Inverse Search on MacOS

### ISSUE THREAD

**Issue by fahasch** [lervag/vimtex#2597]
### Description

If a tex-file is opened via inverse search on MacOS (with Skim and MacVim), the tex-file can not be compiled. 

### Steps to reproduce

1) Use Skim and MacVim on MacOS (I have not tested it using other setups)
2) A PDF-file that is compiled with pdfsync (either using vimtex or otherwise)
3) It is important to quit the MacVim application (if the application is already running in step 4, everything works)
4) Open the PDF-file in Skim and do a reverse search
5) Go in the MacVim application and execute `:VimtexCompile`

I have attached files that facilitate the reproduction. Simply put them in a folder and start with step 3) above:
[test.zip](https://github.com/lervag/vimtex/files/10164777/test.zip)

### Expected behavior

I do expect that the tex file can also be compiled when MacVim is opened via inverse search.

### Actual behavior

I obtain the error
`Error detected while processing function vimtex#compiler#compile:`
`line    1:`
`E716: Key not present in Dictionary: "is_running"``

In general, it seems that the compiler dict does not get properly initialized when starting MacVim in this way. Executing `:echo b:vimtex.compiler`, I obtain only `{}`.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 13.0.1 (22A400)
  Vim version: VIM 9.0 (1-472)
  Has clientserver: true
  Servername: VIM

VimTeX project: test
  base: test.tex
  root: /Users/Shared/test
  tex: /Users/Shared/test/test.tex
  main parser: current file verified
  document class: article
  viewer: Skim
  qf method: LaTeX logfile
```
