### ISSUE TITLE
-shell-escape does not work with build_dir

### ISSUE THREAD

**Issue by WhiteBlackGoose** [lervag/vimtex#2600]
### Description

Thanks for this amazing plugin!

Disclaimer: I'm not entirely sure it's vimtex's issue. Could be latexmk's or minted's.

I'm using `minted` package for language syntax highlighting

Here's my config:
```
vim.g.vimtex_compiler_latexmk = { 
    build_dir = '.out',
    options = { 
        '-shell-escape',
        '-verbose',
        '-file-line-error',
        '-interaction=nonstopmode',
        '-synctex=1'
    } 
}
```

However, it does not work as intended, minted produces no output, which is a symptom of the lack of arguments for the compiler.

However, if I remove `build_dir` line, it suddenly works.

### Steps to reproduce

Minimal document to try:
```tex
\documentclass{article}
\usepackage{graphicx}
\usepackage{amsfonts}
\usepackage[cache=false]{minted}

\begin{minted}{python}
Some code here
\end{minted}

\end{document}
```

Try with `build_dir` line and without it.

### Expected behavior

`build_dir` affects nothing

### Actual behavior

Looks like it's shadowing out some compiler options

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Debian GNU/Linux bookworm/sid
  Vim version: NVIM v0.9.0-dev-441+g5c9bf0ea7
  Has clientserver: true
  Servername: /run/user/1000/nvim.2787957.0
VimTeX project: file
  base: file.tex
  root: /home/goose
  tex: /home/goose/file.tex
  main parser: current file verified
  document class: article
  packages: amsbsy amsfonts amsgen amsmath amsopn amstext calc catchfile epstopdf-base etexcmds etoolbox fancyvrb float framed fvextra graphics graphicx ifluatex ifplatform iftex ifthen infwarerr keyval kvoptions kvsetkeys lineno listings lstmisc ltxcmds minted pdftexcmds shellesc textcomp trig upquote xcolor xstring
  compiler: latexmk
    engine: -pdf
    options:
      -shell-escape
      -verbose
      -file-line-error
      -interaction=nonstopmode
      -synctex=1
    build_dir: .out
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 9
      output: /tmp/nvim.goose/zt6Mf2/1
      cmd: max_print_line=2000 latexmk -shell-escape -verbose -file-line-error -interaction=nonstopmode -synctex=1 -pdf -outdir=.out -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'file.tex'
      pid: 2788118
  viewer: Zathura
    xwin id: 52428803
    cmd_start: zathura  -x "/usr/local/bin/nvim --headless -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 1:1:'/home/goose/file.tex' '.out/file.pdf'&
  qf method: LaTeX logfile
```
