### ISSUE TITLE
Inverse Search with Skim + Neovim + Packer not working

### ISSUE THREAD

**Issue by danieleavitabile** [lervag/vimtex#2610]
### Description

I am in the middle of a transition from using neovim with vim script/vimPlug to lua/Packer. I work on MacOs and with the latest vimtex version, I believe (I have installed it today).

I successfully pass options to vimtex, and everything seems to work well, including forward search, but inverse search from  Skim has stopped working. I use synctex, and Skim is configured using `nvim -headless -c "VimtexInverseSearch %line '%file'"`

### Steps to reproduce

1. Run nvim -u minimal.vim minimal.tex using the attached [minimal.zip](https://github.com/lervag/vimtex/files/10318070/minimal.zip)
2. Press \lv to verify that forward search is working correctly
3. Move to a different page in the PDF file
4. Press Shift+Cmd+Click 

For reference, `minimal.vim` is as below
```vim
set nocompatible
let &runtimepath  = '~/.local/share/nvim/site/pack/packer/start/vimtex,' . &runtimepath
let &runtimepath .= ',~/.local/share/nvim/site/pack/packer/start/vimtex/after'
filetype plugin indent on
syntax enable
" Add relevant options and VimTeX configuration below.
```

### Expected behavior

An inverse search is performed (with cursor moving at the correct position in the source file)

### Actual behavior

Nothing happens

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 12.6 (21G115)
  Vim version: NVIM v0.8.1
  Has clientserver: true
  Servername: /var/folders/80/xh961vxs28z0m3kpysjd6wn40000gn/T/nvim.daniele/yB1ONt/nvim.80057.0

VimTeX project: minimal
  base: minimal.tex
  root: /Users/daniele/Desktop/TestVimTex
  tex: /Users/daniele/Desktop/TestVimTex/minimal.tex
  main parser: current file verified
  document class: minimal
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 0
    executable: latexmk
  viewer: Skim
  qf method: LaTeX logfile
```
