### ISSUE TITLE
[Question] Getting minted language using VimTeX syntax?

### ISSUE THREAD

**Issue by evesdropper** [lervag/vimtex#2613]
### Description

Again, this is a bit more of a question - I was wondering if it were possible to use VimTeX highlighting to detect which language minted is using?

e.g. suppose I had the following:

```latex
\begin{minted}{python}
insert something 
\end{minted}
```

It's possible to get VimTeX to detect we're in `minted` environment, but is there a way to get that the language used in the environment is Python? (Maybe something with respect to `vimtex#env#get_all`, but I'm not exactly sure.) Thanks!

### Do you use a latexmkrc file?

N/A

### VimtexInfo

```yaml
System info:
  OS: Linux 5.19.11-arch1-1
  Vim version: NVIM v0.8.2
  Has clientserver: true
  Servername: /run/user/1000/nvim.52506.0

VimTeX project: pytest
  base: pytest.tex
  root: /home/revise/Documents/test
  tex: /home/revise/Documents/test/pytest.tex
  main parser: fallback current file
  document class: 
  packages: aliascnt aliasctr amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm array atbegshi-ltx atveryend-ltx auxhook babel bigintcalc bitset bm bookmark booktabs calc cancel caption caption3 catchfile centernot changepage cleveref comment diffcoeff enumitem epstopdf-base etexcmds etoolbox expl3 fancyhdr fancyvrb fix-cm float fontenc fontspec fontspec-luatex framed fvextra geometry gettitlestring graphics graphicx hycolor hyperref ifluatex ifplatform iftex ifthen ifvtex import infwarerr intcalc kbordermatrix keyval kvdefinekeys kvoptions kvsetkeys l3keys2e letltxmacro lineno listings lscape lstmisc ltxcmds lualatex-math luatex85 mathtools mhsetup microtype minted multicol multirow nameref nccmath oubraces parseargs parskip pdfescape pdflscape pdflscape-nometadata pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfplots pgfplotstable pgfrcs pgfsubpic pgfsys pgftree physics-minimal pifont random refcount rerunfilecheck sectsty shellesc signchart siunitx stringenc subcaption subfiles suffix systeme textcomp thm-amsthm thm-autoref thm-kv thm-listof thm-patch thm-restate thmtools tikz tikz-3dplot tikz-qtree titlesec titletoc titling tocloft topsection translations trig unicode-math unicode-math-luatex uniquecounter upquote url widebar xcolor xkeyval xparse xr xstring xtemplate
  compiler: latexmk
    engine: -lualatex
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    build_dir: out
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 9
      output: /tmp/nvim.revise/VmEO4s/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -lualatex -outdir=out -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'pytest.tex'
      pid: 52527
  viewer: sioyek
    job: 
      pid: 52550
      cmd: sioyek --inverse-search "/usr/bin/nvim --headless -c \"VimtexInverseSearch %2 '%1'\"" --forward-search-file '/home/revise/Documents/test/pytest.tex' --forward-search-line 7 '/home/revise/Documents/test/out/pytest.pdf'
    cmd_start: sioyek --inverse-search "/usr/bin/nvim --headless -c \"VimtexInverseSearch %2 '%1'\"" --forward-search-file '/home/revise/Documents/test/pytest.tex' --forward-search-line 7 '/home/revise/Documents/test/out/pytest.pdf'
```
