### ISSUE TITLE
No italics in \emph{}

### ISSUE THREAD

**Issue by hcf-n** [lervag/vimtex#2614]
### Description

I'm new to vimtex. I've managed to get basic functionality working, but have some problems with syntax/conceal.

When I open a .tex file, text inside  \emph{} is highlighted, but I would like to have it in italics. My problem is the same as described here [https://github.com/lervag/vimtex/issues/911](https://github.com/lervag/vimtex/issues/911)
But I have not been able to solve it from the instructions there.

I use VIM on OS X iterm2. My terminal returns italics when i type: `echo -e "\e[3mfoo\e[23m"` 

Here is my .vimrc

```
filetype plugin indent on
syntax enable

set encoding=utf-8
set nocompatible
set linebreak
set formatoptions=want1
set backspace=indent,eol,start
set breakindent
set shiftwidth=2

"cursor
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_SR = "\<Esc>]50;CursorShape=2\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"

set ttimeout
set ttimeoutlen=1
set listchars=tab:>-,trail:~,extends:>,precedes:<,space:.
set ttyfast


call plug#begin()
  Plug 'junegunn/goyo.vim'
  Plug 'lervag/vimtex'
call plug#end()


"****** vimtex ********
let g:vimtex_view_method = 'skim'
let g:vimtex_view_skim_sync = 1 " Value 1 allows forward search after every successful compilation
let g:vimtex_view_skim_activate = 1 " Value 1 allows change focus to skim after command `:VimtexView` is given
let g:vimtex_compiler_latexmk_engines = {
    \ '_'                : '-xelatex',
    \}
let g:tex_flavor  = 'latex'
let g:vimtex_quickfix_mode=0
set conceallevel=1
let mapleader =" "

"****** GOYO *********
let g:goyo_width = 60
"let g:goyo_margin_top = 10
"let g:goyo_margin_bottom = 10

"Denne funksjonen sikrer at q! også avslutter Goyo'
function! s:goyo_enter()
  let b:quitting = 0
  let b:quitting_bang = 0
  autocmd QuitPre <buffer> let b:quitting = 1
  cabbrev <buffer> q! let b:quitting_bang = 1 <bar> q!
endfunction

function! s:goyo_leave()
  " Quit Vim if this is the only remaining buffer
  if b:quitting && len(filter(range(1, bufnr('$')), 'buflisted(v:val)')) == 1
    if b:quitting_bang
      qa!
    else
      qa
    endif
  endif
endfunction

autocmd! User GoyoEnter call <SID>goyo_enter()
autocmd! User GoyoLeave call <SID>goyo_leave()
```

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 11.4 (20F71)
  Vim version: VIM 8.2 (1-2029)
  Has clientserver: false

VimTeX project: Tre-teknikker
  base: Tre-teknikker.tex
  root: /Users/hcf/Dropbox/Manus/Tre teknikker
  tex: /Users/hcf/Dropbox/Manus/Tre teknikker/Tre-teknikker.tex
  main parser: current file verified
  document class: artikkel
  packages: babel biblatex blx-case-expl3 csquotes enumitem etoolbox expl3 fontenc fontspec fontspec-xetex geometry iftex ifthen ifvtex infware
  compiler: latexmk
    engine: -xelatex
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Skim
  qf method: LaTeX logfile
```
