### ISSUE TITLE
Indentation in \footnote{}

### ISSUE THREAD

**Issue by hcf-n** [lervag/vimtex#2615]
### Description

When I type text in a `.tex`-file text inside the curly brackets of a `\footnote` is indented while typing. When I close the brackets, the indentation disappears.

When I type, it is  like this:
```tex
\footnote{bla bla bla bla bla
   bla blab
```
After I close the brackets, it is like this:
```tex
\footnote{bla bla bla bla bla
bla bla}
```
How can i prevent indentation while the brackets are open? That is: I would like Neovim and Vimtex to completly ignore indentation for `\footnote{}`.

I have tried:
```tex
let g:vimtex_indent_ignored_envs = ['document', 'footnote']
```
but this seems to have no effect.

Thank you for making vimtex!

My init.vim:

```vim
filetype plugin indent on
syntax enable

set encoding=utf-8
set linebreak
set formatoptions=want
set backspace=indent,eol,start
set breakindent
set shiftwidth=2
set noshowmode
set noshowcmd
set cmdheight=0
set laststatus=0
set tw=60
  
" Set mapleader
let mapleader = " "

call plug#begin()
  Plug 'junegunn/goyo.vim'
  Plug 'lervag/vimtex'
call plug#end()



"****** vimtex ********
let g:vimtex_view_method = 'skim'
let g:vimtex_view_skim_sync = 1 " Value 1 allows forward search after every successful compilation
let g:vimtex_view_skim_activate = 1 " Value 1 allows change focus to skim after command `:VimtexView` is given
let g:vimtex_compiler_latexmk_engines = {
    \ '_'                : '-xelatex',
    \}
let g:vimtex_quickfix_mode=0
let g:vimtex_indent_ignored_envs = ['document', 'footnote']

"****** GOYO *********
let g:goyo_width = 61
"let g:goyo_margin_top = 10
"let g:goyo_margin_bottom = 10

"Denne funksjonen sikrer at q! også avslutter Goyo'
function! s:goyo_enter()
  let b:quitting = 0
  let b:quitting_bang = 0
  autocmd QuitPre <buffer> let b:quitting = 1
  cabbrev <buffer> q! let b:quitting_bang = 1 <bar> q!
endfunction

function! s:goyo_leave()
  " Quit Vim if this is the only remaining buffer
  if b:quitting && len(filter(range(1, bufnr('$')), 'buflisted(v:val)')) == 1
    if b:quitting_bang
      qa!
    else
      qa
    endif
  endif
endfunction

augroup vimrc
  autocmd!
  autocmd! User GoyoEnter call <SID>goyo_enter()
  autocmd! User GoyoLeave call <SID>goyo_leave()
augroup END

au FileType tex hi clear texStyleItal 
au FileType tex hi clear texStyleBold

autocmd vimenter * Goyo	



```

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 11.4 (20F71)
  Vim version: NVIM v0.8.1
  Has clientserver: true
  Servername: /var/folders/dy/smm4_0w12n976m5_jlp83t180000gn/T/nvim.hcf/MZQIFL/nvim.45275.0

VimTeX project: Tre-teknikker
  base: Tre-teknikker.tex
  root: /Users/hcf/Dropbox/Manus/Tre teknikker
  tex: /Users/hcf/Dropbox/Manus/Tre teknikker/Tre-teknikker.tex
  main parser: current file verified
  document class: artikkel
  packages: babel biblatex blx-case-expl3 csquotes enumitem etoolbox expl3 fontenc fontspec fontspec-xetex geometry iftex ifthen ifvtex infware
  compiler: latexmk
    engine: -xelatex
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Skim
  qf method: LaTeX logfile
```
My question seems to be tagged with #bug. I don't know how to remove/change that.
