### ISSUE TITLE
Highlight for \mathbb affects its argument

### ISSUE THREAD

**Issue by suzuyu1729** [lervag/vimtex#2616]
### Description

I'm new to Vim and VimTeX and so I'm sorry if this is an easy problem.

I'm trying to make my own colorscheme using VimTeX's syntax groups. Meanwhile, I found that if I assign some highlight to the `texCmd` group, then this highlight rule is applied to the "argument part" as well.

For example, if I use `guifg=red` to `texCmd`, then in the LaTeX source `\mathbf{R}` only `\mathbf` is red but in the LaTeX source `\mathbb{R}` the argument part `{R}` is also red.

### Steps to reproduce

1. `vim -u minimal.vim minimal.tex`
2. `:colorscheme quiet`
3. `:hi texCmd ctermfg=red`

or

1. `mvim -u minimal.vim minimal.tex`
2. `:colorscheme quiet`
3. `:hi texCmd guifg=red`

minimal.tex:

```tex
\documentclass{amsart}
\begin{document}
\begin{equation}
\mathbb{R}
\mathcal{R}
\mathfrak{R}
\mathbf{R}
\mathrm{R}
\mathnormal{R}
\end{equation}
\end{document}
```

minimal.vim (without ftplugin/tex*):

```vim
set nocompatible
filetype plugin indent on
syntax enable
call plug#begin()
Plug 'lervag/vimtex'
call plug#end()
let g:vimtex_compiler_method = 'latexmk'
let g:vimtex_view_method = 'skim'
let maplocalleader = ' '
```

### Expected behavior

Only `\cmd` parts are colored red, e.g. in `\mathrm{R}`, `\mathrm` is red and `{R}` is white.

### Actual behavior

The whole of `\cmd{R}` parts are colored red for cmd=\mathbb, \mathcal, \mathfrak, e.g. in `\mathbb{R}`, `\mathbb` is red and `{R}` is also red.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 13.1 (22C65)
  Vim version: VIM 9.0 (1-472)
  Has clientserver: true
  Servername: undefined (vim started without --servername)

VimTeX project: minimal
  base: minimal.tex
  root: /Users/suzuyu
  tex: /Users/suzuyu/minimal.tex
  main parser: current file verified
  document class: amsart
  compiler: latexmk
    engine: -pdfdvi
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Skim
  qf method: LaTeX logfile
```
