### ISSUE TITLE
Cannot use the forword and reverse search using nvim and zathura in wsl2.

### ISSUE THREAD

**Issue by meicale** [lervag/vimtex#2622]
### Description

I installed the newest nvim, zathura and latex-live. With the help of this plugin I find it working well. But I can not do forword and reverse search.

### Steps to reproduce

Except for install the plugin and software package(such as xdotool), I left anything default. I can use vimtex plugin in tex file by :command. It works well, and when I saved the file it automatically open zathura to view the updated version. 

### Expected behavior

I can not do forward and reverse search, it does not highlight anything and the ctrl+left click get no response.

### Actual behavior

But I can do forward and reverse search, it can highlight the line and the ctrl+left click on pdf file get me to the responding sourcecode.
I guess this link may help and I cannot figure out how. #2392

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 20.04.5 LTS
  Vim version: NVIM v0.8.1
  Has clientserver: true
  Servername: /mnt/wslg/runtime-dir/nvim.1761.0

VimTeX project: test
  base: test.tex
  root: /mnt/i/data/workspace/playground
  tex: /mnt/i/data/workspace/playground/test.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 16
      output: /tmp/nvim.bill/VBZDxm/2
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'test.tex'
      pid: 0
  viewer: General
    job: 
      pid: -
      cmd: xdg-open '/mnt/i/data/workspace/playground/test.pdf'
  qf method: LaTeX logfile
```
