### ISSUE TITLE
Compilation Failed!

### ISSUE THREAD

**Issue by tim0120** [lervag/vimtex#2625]
### Description

`\ll` gives the error `VimTeX: Compilation failed!`
Not sure what is the problem, so any help would be appreciated!

### Steps to reproduce

minimal.tex:
```tex
\documentclass{article}
\begin{document}
   ciao mondo
\end{document}
```
init.vim
```vim
" Leader key
nnoremap <SPACE> <Nop>
let mapleader = ' '
set showcmd

" Line numbers
set number relativenumber

" Fast scrolling
set ttyfast

" Syntax highlighting
syntax on

" Tab/indentation: set to 2 spaces and indent to match code
set autoindent expandtab tabstop=2 shiftwidth=2

" Key remappings
inoremap jk <esc>

filetype on

" Ward off unexpected things that your distro might have made, as
" well as sanely reset options when re-sourcing .vimrc
set nocompatible

" Set Dein base path (required)
let s:dein_base = '/Users/timkostolansky/.cache/dein'

" Set Dein source path (required)
let s:dein_src = '/Users/timkostolansky/.cache/dein/repos/github.com/Shougo/dein.vim'

" Set Dein runtime path (required)
execute 'set runtimepath+=' . s:dein_src

" Call Dein initialization (required)
call dein#begin(s:dein_base)

call dein#add(s:dein_src)

" Your plugins go here:
"call dein#add('Shougo/neosnippet.vim')
"call dein#add('Shougo/neosnippet-snippets')
call dein#add('lervag/vimtex')

" Finish Dein initialization (required)
call dein#end()

" Attempt to determine the type of a file based on its name and possibly its
" contents. Use this to allow intelligent auto-indenting for each filetype,
" and for plugins that are filetype specific.
if has('filetype')
  filetype indent plugin on
endif

" Enable syntax highlighting
if has('syntax')
  syntax on
endif

" Uncomment if you want to install not-installed plugins on startup.
"if dein#check_install()
" call dein#install()
"endif

" Vimtex stuff
filetype plugin on
syntax enable
let g:vimtex_view_method = 'skim'
" let g:vimtex_quickfix_method = 0
" let g:latex_view_general_viewer = 'skim'
" let g:vimtex_view_general_options = '--unique file:@pdf\#src:@line@tex'
" let g:vimtex_compiler_progname = 'nvr'
" let g:tex_flavor = 'latex'
```

### Expected behavior

Compilation into pdf

### Actual behavior

Error: `VimTeX: Compilation failed!`

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
System info:
  OS: macOS 13.0.1 (22A400)
  Vim version: NVIM v0.7.2
  Has clientserver: true
  Servername: /var/folders/w9/25754qg172l1hyl55m3q0t6r0000gn/T/nvimRSEFeU/0

VimTeX project: mineralai_coverletter
  base: mineralai_coverletter.tex
  root: /Users/tim/Documents
  tex: /Users/tim/Documents/minimal.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job:
      jobid: 6
      output: /var/folders/w9/25754qg172l1hyl55m3q0t6r0000gn/T/nvimRSEFeU/1
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cm …
      pid: 92231
  viewer: Skim
  qf method: LaTeX logfile
```
