### ISSUE TITLE
Let g:vimtex_view_method = 'zathura' , but cannot open zathura after compilation.

### ISSUE THREAD

**Issue by ez4lionky** [lervag/vimtex#2630]
### Description

I set g:vimtex_view_method = 'zathura' in ftplugin/tex/tex.vim.
In neovim I execute ":echo g:vimtex_view_method", it outputs "zathura".
But when I query the VimtexInfo, the value of viewer is still "General". 
The neovim cannot open the zathura when finishing compilation as well as use shortcut \lv.
![image](https://user-images.githubusercontent.com/23551503/218312041-6efd28bc-0fc8-4650-a066-61b7fab475f6.png)
![image](https://user-images.githubusercontent.com/23551503/218312060-edee45ee-0f5d-4f7c-97fa-2c1bf5e5b66a.png)

But I can use zathura main.pdf to open the pdf file.
"ldd $(which zathura) | grep libsynctex" also shows the linked .so file.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 20.04.4 LTS
  Vim version: NVIM v0.8.1
  Has clientserver: true
  Servername: /run/user/1000/nvim.1314874.0

VimTeX project: main
  base: main.tex
  root: /home/lionky/Documents/
  tex: /home/lionky/Documents/main.tex
  main parser: current file verified
  document class: article
  packages: amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm atbegshi auxhook bm booktabs calc color empheq epstopdf-base etexcmds etoolbox everyshi expl3 geometry graphics graphicx iftex ifvtex infwarerr keyval kvdefinekeys kvoptions kvsetkeys lipsum ltxcmds mathtools mdframed mhsetup needspace pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfplots pgfrcs pgfsys psfrag tikz trig xcolor xparse zref-abspage zref-base
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
    job: 
      pid: -
      cmd: xdg-open '/home/lionky/Documents/main.pdf'
  qf method: LaTeX logfile
```
