### ISSUE TITLE
Minted requires `-shell-escape` flag with compiler.

### ISSUE THREAD

**Issue by JxJxxJxJ** [lervag/vimtex#2632]
### Description

I'm trying to use `-shell-escape` with `latexmk` using `vimtex` so that I can use the LaTeX package minted. 

I've tried
```lua
vim.g.vimtex_compiler_latexmk.options = {
  '-pdf',
  '-shell-escape',
  '-verbose',
  '-file-line-error',
  '-synctex=1',
  '-interaction=nonstopmode',
}
```

But when compiling it still doesn't see the `-shell-escape` flag

### Steps to reproduce

I use lunarvim, so `vim -u minimal.lua minimal.tex`

```lua
-- minimal.lua 
vim.g.vimtex_compiler_latexmk.options = {
  '-pdf',
  '-shell-escape',
  '-verbose',
  '-file-line-error',
  '-synctex=1',
  '-interaction=nonstopmode',
}
```

```minimal.tex 
\documentclass{article}
\usepackage{minted}
\usepackage{xcolor} % to access the named colour LightGray
\definecolor{LightGray}{gray}{0.9}
\begin{document}
\begin{minted}
[
frame=lines,
framesep=2mm,
baselinestretch=1.2,
bgcolor=LightGray,
fontsize=\footnotesize,
linenos
]
{python}
import numpy as np
    
def incmatrix(genl1,genl2):
    m = len(genl1)
    n = len(genl2)
    M = None #to become the incidence matrix
    VT = np.zeros((n*m,1), int)  #dummy variable
    
    #compute the bitwise xor matrix
    M1 = bitxormatrix(genl1)
    M2 = np.triu(bitxormatrix(genl2),1) 

    for i in range(m-1):
        for j in range(i+1, m):
            [r,c] = np.where(M2 == M1[i,j])
            for k in range(len(r)):
                VT[(i)*n + r[k]] = 1;
                VT[(i)*n + c[k]] = 1;
                VT[(j)*n + r[k]] = 1;
                VT[(j)*n + c[k]] = 1;
                
                if M is None:
                    M = np.copy(VT)
                else:
                    M = np.concatenate((M, VT), 1)
                
                VT = np.zeros((n*m,1), int)
    
    return M
\end{minted}
\end{document}
```

### Expected behavior

Source Code should be displayed 

### Actual behavior

Nothing is displayed and the following errors appear 

> my-preamble-latex/preamble.tex|30 error| Package minted Error: You must invoke LaTeX with the -shell-escape flag.
> Escritorio/cosas-latex/algo-1/algoritmos.tex|11 error| Package minted Error: You must have `pygmentize' installed to use this package.
> Escritorio/cosas-latex/algo-1/algoritmos.tex|| Package hyperref Warning: old toc file detected, not used; run LaTeX again.
> Escritorio/cosas-latex/algo-1/algoritmos.tex|1124 error| Package catchfile Error: File `_minted-algoritmos/default.pygstyle' not found.
> Escritorio/cosas-latex/algo-1/algoritmos.tex|1124 error| Package catchfile Error: File `_minted-algoritmos/default.pygstyle' not found.
> Escritorio/cosas-latex/algo-1/algoritmos.tex|1124 error| Package minted Error: Cannot find Pygments style default.
> Escritorio/cosas-latex/algo-1/algoritmos.tex|1124 error| Package minted Error: Missing Pygments output; \inputminted was
> Escritorio/cosas-latex/algo-1/algoritmos.tex|| LaTeX Warning: Label(s) may have changed. Rerun to get cross-references right.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
MY_COMMENT: Here I can see the `-shell-escape` flag is being skipped, I wonder why.

System info:
  OS: Linux 5.15.94-1-lts
  Vim version: NVIM v0.8.3
  Has clientserver: true
  Servername: /run/user/1000/nvim.39331.0

VimTeX project: algoritmos
  base: algoritmos.tex
  root: /home/Jx/Escritorio/cosas-latex/algo-1
  tex: /home/Jx/Escritorio/cosas-latex/algo-1/algoritmos.tex
  main parser: current file verified
  document class: report
  packages: algorithm2e amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm array atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook babel bigintcalc bitset bookmark calc cancel catchfile centernot color comment enumitem environ epstopdf-base eso-pic etexcmds etoolbox expl3 fancyvrb float framed fvextra geometry gettitlestring graphics graphicx hycolor hyperref ifluatex ifmtarg ifoddpage ifplatform iftex ifthen ifvtex import infwarerr inputenc intcalc keyval kvdefinekeys kvoptions kvsetkeys l3keys2e letltxmacro lineno listings listingsutf8 lscape lstmisc ltxcmds mathtools mhsetup minted mleftright multicol nameref newpxmath pdfcol pdfescape pdflscape pdfpages pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfrcs pgfsys refcount relsize rerunfilecheck setspace shellesc stringenc tcolorbox textcomp theoremref tikz tikz-cd tikzsymbols titletoc transparent trig trimspaces uniquecounter upquote url varwidth verbatim xcolor xfrac xifthen xkeyval xparse xspace xstring xtemplate
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 6
      output: /tmp/nvim.Jx/sh6wdw/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'algoritmos.tex'
      pid: 39404
  viewer: Zathura
    xwin id: 6291459
    cmd_start: zathura  -x "/usr/bin/nvim --headless -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 1:8:'/home/Jx/Escritorio/cosas-latex/algo-1/algoritmos.tex' 'Escritorio/cosas-latex/algo-1/algoritmos.pdf'&
  qf method: LaTeX logfile
```
