### ISSUE TITLE
The symbols in the listing break the highlighting.

### ISSUE THREAD

**Issue by oriyia** [lervag/vimtex#2636]
### Description

Packages in question: `shortvrb`, `listings`.
Using the `%`, `$` symbols in the short versions of the commands of the specified packages, syntax highlighting breaks.

### Steps to reproduce

Launched with minimal configuration:
`nvim minimal.vim minimal.tex`
![2023-02-19-152606_1802x511_scrot](https://user-images.githubusercontent.com/64345976/219948345-598b4f31-45a3-4fe4-88f5-2edd32f89e8d.png)

### Do you use a latexmkrc file?

Нет

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 22.04.1 LTS
  Vim version: NVIM v0.9.0-dev-414+gef5ab2bf7
  Has clientserver: true
  Servername: /run/user/1000/nvim.633996.0

VimTeX project: test
  base: test.tex
  root: /home/oriyia/abstracts/test
  tex: /home/oriyia/abstracts/test/test.tex
  main parser: current file verified
  document class: book
  packages: keyval listings lstmisc shortvrb
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
