### ISSUE TITLE
Buggy interaction of `g:vimtex_quickfix_autoclose_after_keystrokes` with command-line window.

### ISSUE THREAD

**Issue by Aster89** [lervag/vimtex#2637]
### Description

When `g:vimtex_quickfix_autoclose_after_keystrokes > 0`, say `n`, moving the cursor `n` times in the command-line window causes an error.

### Steps to reproduce

1. Ensure `let g:vimtex_quickfix_autoclose_after_keystrokes > 0`, say `n`
2. Open the quickfix window (even without compiling, technically, but you do need a log to make it open).
3. Open the command line window (via `q:`, `q/` or whatever)
4. Move the cursor `n` times, and you'll see an error
5. Dismiss the error and move the cursor again `n` times, and you'll see the error again.

### Expected behavior

VimTeX's quickfix closing normally upon `n` cursor movements.

### Actual behavior

Every 
```
Error detected while processing CursorMoved Autocommands for "*"..function <SNR>56_qf_autoclose_check:
line   19:
E11: Invalid in command-line window; :q<CR> closes the window:     cclose
```

### Do you use a latexmkrc file?

Yes, but I'm pretty sure it's irrelevant

### VimtexInfo

```yaml
System info:
  OS: Arch Linux
  Vim version: VIM 9.0 (1-1302)
  Has clientserver: true
  Servername: VIM2

VimTeX project: main
  base: main.tex
  root: /home/enrico/deleteme
  tex: /home/enrico/deleteme/main.tex
  main parser: current file verified
  document class: book
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
