### ISSUE TITLE
[Q] How do i set fonts (variables) for compiling latex ?

### ISSUE THREAD

**Issue by LamprosPitsillos** [lervag/vimtex#2652]
### Description

When using `pandoc` I do

```shell
pandoc -f gfm+hard_line_breaks **** \
  -t pdf --pdf-engine=xelatex \
  -V 'mainfont=Fira Code' \
  -V 'mainfontoptions:BoldFont=Fira Code SemiBold, ItalicFont=JetBrains Mono Italic, BoldItalicFont=JetBrains Mono Bold Italic' \
  -V 'monofont=Fira Mono'
```

And have support and my files compile properly , how do i set this using VimTex?

This is my current config in Neovim

```lua
return {
    "lervag/vimtex",
    ft = "tex",
    config = function()
        vim.g.vimtex_view_general_viewer = "zathura"
        vim.g.vimtex_compiler_method = "tectonic"
        vim.g.vimtex_compiler_tectonic = {
               executable = 'tectonic',
               callback = 1,
               continuous = 1,
               options = {
                 '--synctex',
                 '--keep-logs',
                '--keep-intermediates'
            }
        }
    end
}
```

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
System info:
  OS: Linux 6.1.12-artix1-1
  Vim version: NVIM v0.9.0-dev-1036+g3f35ebb14
  Has clientserver: true
  Servername: /run/user/1000/nvim.27672.0

VimTeX project: HW1
  base: HW1.tex
  root: /home/inferno/UoC/8ο Εξαμηνο/HY-111 Απειροστικός Λογισμός ΙΙ/Assignments
  tex: /home/inferno/UoC/8ο Εξαμηνο/HY-111 Απειροστικός Λογισμός ΙΙ/Assignments/HW1.tex
  main parser: current file verified
  document class: article
  compiler: tectonic
    options:
      --synctex
      --keep-logs
      --keep-intermediates
  viewer: General
  qf method: LaTeX logfile
```
