### ISSUE TITLE
Concealment conceals \left\|e with nothing

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#2656]
### Description

```tex
\documentclass{article}
\usepackage{mathtools}
\begin{document}
\begin{align*}
  \left\|e_k\right\|^2
\end{align*}
\end{document}
```

### Expected behavior

![Screenshot 2023-03-02 at 17 25 36](https://user-images.githubusercontent.com/371756/222489871-f5195018-2750-489b-a10a-668d80cd7099.png)

maybe without throwing away my indentation.

### Actual behavior

![Screenshot 2023-03-02 at 17 24 34](https://user-images.githubusercontent.com/371756/222489447-c00325b3-3aea-4cc3-ae77-1648595a5a17.png)

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
System info:
  OS: macOS 12.6.1 (21G217)
  Vim version: NVIM v0.8.2
  Has clientserver: true
  Servername: /var/folders/2z/bljkcy1j2cbf7l9zf3dk0nqc0000gn/T/vimr_B62C856C-D95E-4A7C-9CE2-2372374DB9F7.sock

VimTeX project: demo2
  base: demo2.tex
  root: /Users/kiryph
  tex: /Users/kiryph/demo2.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: sioyek
  qf method: LaTeX logfile
```
```
