### ISSUE TITLE
vimtex-cmd-create doesn't seem to be working

### ISSUE THREAD

**Issue by evesdropper** [lervag/vimtex#2659]
### Description

Was looking through the documentation and found F7 to wrap text around commands; however, it doesn't seem to be working for me.

### Steps to reproduce

1. `nvim test.tex`
2. Tried pressing F7 for vimtex-cmd-create

### Expected behavior

Should have something that allows me to insert a command.

### Actual behavior

Nothing happens.
![vimtex-cmd-create](https://user-images.githubusercontent.com/82856360/222882097-5ff274f6-09c1-4f3b-9f78-be518357200f.gif)

### Do you use a latexmkrc file?

Yes, though not relevant to the current issue.

### VimtexInfo

```yaml
System info:
  OS: Linux 5.19.11-arch1-1
  Vim version: NVIM v0.8.3
  Has clientserver: true
  Servername: /run/user/1000/nvim.32003.0

VimTeX project: test
  base: test.tex
  root: /home/revise/Documents/university/bachelor-2/sp23/math113/hw
  tex: /home/revise/Documents/university/bachelor-2/sp23/math113/hw/test.tex
  main parser: current file verified
  document class: article
  packages: random
  compiler: latexmk
    engine: -lualatex
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    build_dir: out
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: sioyek
  qf method: LaTeX logfile
```
