### ISSUE TITLE
weird jump movement after vimtex compiled

### ISSUE THREAD

**Issue by lee-shun** [lervag/vimtex#2661]
### Description

Hello!

Every time vimtex finishes compiling, if at that moment I am navigating using "h", there will be a weird movement that takes me to the next line.

**NOTE:** I tried without noice and notify, the bug disappears.

For example, in the following gif, I am pressing "h" only, but once the "message vimtex compile failed!" there will be a movement takes me to the next line...

![Peek 2023-03-04 22-27](https://user-images.githubusercontent.com/46647235/222985213-99df4d26-f92b-4664-9ec8-88f9930fd1ef.gif)

### Steps to reproduce

I use lazy.nvim.

```lua
{
	"lervag/vimtex",
	ft = "tex",
	config = function()
		vim.g.vimtex_view_method = "zathura"
		vim.g.vimtex_quickfix_mode = 0
		vim.g.vimtex_mappings_enabled = 0
		vim.g.vimtex_imaps_enabled = 0
		vim.g.vimtex_text_obj_enabled = 0
		vim.g.vimtex_fold_enabled = 0
		vim.g.tex_conceal = "abdmg"
		vim.g.vimtex_syntax_conceal_disable = 1
		vim.g.vimtex_format_enabled = 0
		vim.g.vimtex_syntax_enabled = 0
	end,
}
```

noice.nvim

```lua
{
	"folke/noice.nvim",
	event = "VeryLazy",
	dependencies = { "MunifTanjim/nui.nvim" },
	opts = {
		lsp = {
			override = {
				["vim.lsp.util.convert_input_to_markdown_lines"] = true,
				["vim.lsp.util.stylize_markdown"] = true,
				["cmp.entry.get_documentation"] = true,
			},
		},
		presets = {
			bottom_search = false,
			command_palette = false,
			long_message_to_split = false,
			inc_rename = true,
			lsp_doc_border = true,
		},
	},
  -- stylua: ignore
  keys = {
    { "<S-Enter>", function() require("noice").redirect(vim.fn.getcmdline()) end, mode = "c", desc = "Redirect Cmdline" },
    { "<leader>nl", function() require("noice").cmd("last") end, desc = "Noice Last Message" },
    { "<leader>nh", function() require("noice").cmd("history") end, desc = "Noice History" },
    { "<leader>na", function() require("noice").cmd("all") end, desc = "Noice All" },
    { "<c-f>", function() if not require("noice.lsp").scroll(4) then return "<c-f>" end end, silent = true, expr = true, desc = "Scroll forward", mode = {"i", "n", "s"} },
    { "<c-b>", function() if not require("noice.lsp").scroll(-4) then return "<c-b>" end end, silent = true, expr = true, desc = "Scroll backward", mode = {"i", "n", "s"}},
  },
	config = function(_, opts)
		require("noice").setup(opts)
		require("which-key").register({
			n = { name = "Noice" },
		}, {
			mode = "n",
			prefix = "<leader>",
			buffer = nil,
			silent = true,
			noremap = true,
			nowait = false,
		})
	end,
}
```

notify.nvim

```lua
{
	"rcarriga/nvim-notify",
	keys = {
		{
			"<leader>nu",
			function()
				require("notify").dismiss({ silent = true, pending = true })
			end,
			desc = "Delete all Notifications",
		},
	},
	opts = {
		timeout = 3000,
		max_height = function()
			return math.floor(vim.o.lines * 0.75)
		end,
		max_width = function()
			return math.floor(vim.o.columns * 0.75)
		end,
	},
	config = function(_, opts)
		require("notify").setup(opts)
		require("telescope").load_extension("notify")

		local wk = require("which-key")
		local telescope_map = {
			f = {
				name = "Find",
				n = { "<cmd>Telescope notify<cr>", "Find notify" },
			},
		}
		local telescope_map_opt = {
			mode = "n",
			prefix = "<leader>",
			buffer = nil,
			silent = true,
			noremap = true,
			nowait = false,
		}
		wk.register(telescope_map, telescope_map_opt)
	end,
}
```

### Actual behavior

weird movement

### Do you use a latexmkrc file?

NO

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 20.04.5 LTS
  Vim version: NVIM v0.9.0-dev
  Has clientserver: true
  Servername: /run/user/1000/nvim.2135.0

VimTeX project: main
  base: main.tex
  root: /home/ls/forest_fire_thesis/CU_thesis
  tex: /home/ls/forest_fire_thesis/CU_thesis/main.tex
  main parser: recursive search
  document class: report
  packages: ConcordiaU algorithm algorithmicx algpseudocode amsbsy amsfonts amsgen amsmath amsopn amstext appendix atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook bigintcalc bitset cite color enumitem epstopdf-base etexcmds float geometry gettitlestring graphics graphicx hycolor hyperref iftex ifthen ifvtex indentfirst infwarerr intcalc keyval kvdefinekeys kvoptions kvsetkeys letltxmacro ltxcmds multirow nameref pdfescape pdftexcmds refcount rerunfilecheck setspace setup/ConcordiaU subfigure times trig uniquecounter url
  source files:
    main.tex
    configs/Constants.tex
    supplements/Abstract.tex
    supplements/Acknowledgements.tex
    chapters/Introduction.tex
    chapters/Related_Works.tex
    chapters/System_Platform.tex
    chapters/Alg_detection.tex
    chapters/Alg_geolocation.tex
    chapters/Alg_reconstruction.tex
    chapters/Experiment.tex
    chapters/Conclusion.tex
    supplements/Appendix_A.tex
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
