### ISSUE TITLE
VimTex executes tectonic compiler without escaping path spaces

### ISSUE THREAD

**Issue by dartacao** [lervag/vimtex#2664]
### Description

Maybe I'm messing up somewhere, since I've seen that the "output-dir" issue has been supposedly fixed in a PR, but I'm having it nonetheless. I'm using neovim 0.9.0, latest vimtex, lazy.nvim as a package manager. Executing VimtexInfo (which errors out on the first execution, see below) gives the following information:
![image](https://user-images.githubusercontent.com/2131630/224371302-f7126081-49f5-4337-be9d-4e7f9bb529ce.png)
Image with censored name. If the path is `C:\Users\Albert Einstein\Documents\a.tex`, it shows up as `C:\Users\Albert\ Einstein\(...)`
I'm not sure why it's erroring out on the first execution of VimtexInfo, but it might be related. Configuration is literally 2 lines in init.lua:
```
vim.g.vimtex_view_method = 'sioyek'
vim.g.vimtex_compiler_method = 'tectonic'
```

### Steps to reproduce

1. Open a tex file whose path contains spaces
2. Run :VimtexCompile or :VimtexInfo
3. See that file doesn't compile or compiles with an error. VimtexInfo shows the command as escaped with `"\ "`

### Expected behavior

The document to compile and VimtexInfo to work

### Actual behavior

VimtexInfo errors on first execution.
Tectonic is run with an output dir that has a space

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS:  ()
  Vim version: NVIM v0.9.0-dev-974+g631775c05
  Has clientserver: true
  Servername: \\.\pipe\nvim-nvr

VimTeX project: curriculum-pt
  base: curriculum-pt.tex
  root: C:\Users\---\Internxt\Documentos\CV\CV
  tex: C:\Users\---\Internxt\Documentos\CV\CV\curriculum-pt.tex
  main parser: current file verified
  document class: moderncv
  packages: geometry ragged2e
  source files:
    curriculum-pt.tex
    cm-pt.tex
  compiler: tectonic
    options:
      --keep-logs
      --synctex
  viewer: sioyek
  qf method: LaTeX logfile
```
```
