### ISSUE TITLE
siunitx undefined control sequence 

### ISSUE THREAD

**Issue by HaiTengZheng** [lervag/vimtex#2665]
### Description

`\qty` and other commands in siunitx package didn't work, while compiler, the result display : "Undefined Control sequence".

![Screenshot from 2023-03-13 01-05-26](https://user-images.githubusercontent.com/91372225/224561468-564f5955-3207-4f36-9e3e-dc4eda6c0514.png)

### Steps to reproduce

```tex
\usepackage{siunitx}
\usepackage{xeCJK}
\begin{document}
湿空气的焓是指$\qty{1}{\kg}$
\end{document}
```

![image](https://user-images.githubusercontent.com/91372225/224562192-39d103b7-e733-45b4-bdb8-68bd461b48f7.png)

### Expected behavior

I wish it can correctly export the SI, and display in the PDF file.

### Actual behavior

![Screenshot from 2023-03-13 01-00-41](https://user-images.githubusercontent.com/91372225/224561129-69fceff1-7d86-4c0d-9e22-f9eced778a39.png)

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
System info:
  OS: Linux 6.1.7-200.fc37.x86_64
  Vim version: NVIM v0.8.3
  Has clientserver: true
  Servername: /run/user/1000/nvim.16120.0

VimTeX project: main
  base: main.tex
  root: /home/mustang/Dropbox/HVAC
  tex: /home/mustang/Dropbox/HVAC/main.tex
  main parser: current file verified
  document class: article
  packages: amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook bigintcalc bitset bm calc color ctexhook environ etexcmds etoolbox expl3 fancyhdr fontenc fontspec fontspec-xetex geometry gettitlestring graphics graphicx hycolor hyperref iftex ifvtex infwarerr intcalc keyval kvdefinekeys kvoptions kvsetkeys l3keys2e letltxmacro listings lstmisc ltxcmds mathtools mhsetup multirow nameref pdfcol pdfescape pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfrcs pgfsys refcount rerunfilecheck shellesc siunitx stringenc tcolorbox tikz trig trimspaces uniquecounter url verbatim xcolor xeCJK xeCJK-listings xparse xparse-2020-10-01 xtemplate
  source files:
    main.tex
    preamble.tex
    section/wetAir.tex
    section/loadCalculation.tex
  compiler: latexmk
    engine: -xelatex
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
