### ISSUE TITLE
Unnecessary reverse indent of \item in nested enumerate environment

### ISSUE THREAD

**Issue by lutalli** [lervag/vimtex#2670]
### Description

The indentation of `\item` seems to work improperly in a nested `enumerate` environment (`enumerate` in another `enumerate`). When I enter an `\item` in a nested `enumerate` and type a space, the `\item` gets indented backwards unnecessarily.

### Steps to reproduce

1. Begin with the following minimal TeX file:
```tex
\begin{document}

\begin{enumerate}
\end{enumerate}

\end{document}
```
2. Type `\item` in the `enumerate` environment, after that start another `enumerate` (where `|` stands for the cursor position):
```tex
\begin{document}

\begin{enumerate}
    \item \begin{enumerate}|
\end{enumerate}

\end{document}
```
3. Start a newline, type another `\item` (which belongs to the inner `enumerate`):
```tex
\begin{document}

\begin{enumerate}
    \item \begin{enumerate}
            \item|
\end{enumerate}

\end{document}
```
4. Type a space:
```tex
\begin{document}

\begin{enumerate}
    \item \begin{enumerate}
        \item |
\end{enumerate}

\end{document}
```

### Expected behavior

The inner `\item` should stay in place after the space is typed, like this:

<img width="333" alt="image" src="https://user-images.githubusercontent.com/47910890/225862095-041b0d30-5ee6-432e-8050-27cb06049a7d.png">

### Actual behavior

The following recording shows the problematic actual behavior - `\item` gets falsely indented back:

https://user-images.githubusercontent.com/47910890/225861501-dc21d433-2f6e-48ca-b081-68fae8c97880.mov

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 12.4 (21F79)
  Vim version: NVIM v0.8.2
  Has clientserver: true
  Servername: /var/folders/zx/08zvm7jx3k70j_1_nyt1lc_80000gn/T/nvim.lutalli/2amYJE/nvim.66614.0

VimTeX project: tmp
  base: tmp.tex
  root: /
  tex: /tmp.tex
  main parser: fallback current file
  document class: 
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 0
    executable: latexmk
  viewer: Skim
  qf method: LaTeX logfile
```
