### ISSUE TITLE
:VimtexInfo fails on first attempt to run

### ISSUE THREAD

**Issue by henriqpsantos** [lervag/vimtex#2671]
### Description

With the specified minimal config, `:VimtexInfo` fails on the first attempt to run it. Full error is in #2664.

### Steps to reproduce

```lua
vim.cmd ('filetype plugin indent on')
vim.cmd ('syntax enable')
vim.opt.runtimepath:prepend "C:/Users/-----/Documents/.data/nvim-data/lazy/vimtex"
vim.opt.runtimepath:append "C:/Users/-----/Documents/.data/nvim-data/lazy/vimtex/after"
```

### Expected behavior

VimTeX information to be displayed.

### Actual behavior

```
Error: string "<ff>091 MB" contains byte that does not start any UTF-8 character.
```

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: LAPTOP-QDMBVVL7 (Microsoft Windows 10 Home)
  Vim version: NVIM v0.9.0-dev-1028+gd422fc827
  Has clientserver: true
  Servername: \\.\pipe\nvim-nvr

VimTeX project: minimal
  base: minimal.tex
  root: C:\Users\----\Internxt\Development\.config\minimal with spaces
  tex: C:\Users\----\Internxt\Development\.config\minimal with spaces\minimal.tex
  main parser: current file verified
  document class: minimal
  compiler: tectonic
    options:
      --keep-logs
      --synctex
    job: 
      jobid: 5
      output: C:\Users\----\AppData\Local\Temp\nvim.0\wt0xJ8\0
      cmd: tectonic --keep-logs --synctex --outdir=C:\Users\----\Internxt\Development\.config\minimal\ with\ spaces "minimal.tex"
  viewer: sioyek
    job: 
      pid: -
      cmd: sioyek  --inverse-search "C:\Program Files\Neovim\bin\nvim.exe --headless -c \"VimtexInverseSearch %2 '%1'\"" --forward-search-file "C:\\Users\\----\\Internxt\\Development\\.config\\minimal with spaces\\minimal.tex" --forward-search-line 1 "C:\\Users\\----\\Internxt\\Development\\.config\\minimal with spaces/minimal.pdf"
    cmd_start: sioyek  --inverse-search "C:\Program Files\Neovim\bin\nvim.exe --headless -c \"VimtexInverseSearch %2 '%1'\"" --forward-search-file "C:\\Users\\----\\Internxt\\Development\\.config\\minimal with spaces\\minimal.tex" --forward-search-line 1 "C:\\Users\\----\\Internxt\\Development\\.config\\minimal with spaces/minimal.pdf"
  qf method: LaTeX logfile
```
