### ISSUE TITLE
Viewer cannot find zathura window id

### ISSUE THREAD

**Issue by Geostartico** [lervag/vimtex#2678]
### Description

when executing \ll or \lv vim shows the error "Vimtex: Viewer cannot find zathura window id"

### Steps to reproduce

executing \ll or \lv 

### Expected behavior

not showing an error, however i don't remember if the extension is supposed to highlight the text along the cursor as i haven't used it in along time

### Actual behavior

shows an error

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: EndeavourOS Linux
  Vim version: NVIM v0.8.3
  Has clientserver: true
  Servername: /run/user/1000/nvim.2568.0

VimTeX project: testo
  base: testo.tex
  root: /home/geostartico/Documents/tesi/testo
  tex: /home/geostartico/Documents/tesi/testo/testo.tex
  main parser: current file verified
  document class: article
  compiler: tectonic
    options:
      --keep-logs
      --synctex
    job: 
      jobid: 182
      output: /tmp/nvim.geostartico/yPcVtF/1
      cmd: tectonic --keep-logs --synctex --outdir=/home/geostartico/Documents/tesi/testo 'testo.tex'
  viewer: Zathura
    xwin id: 0
    cmd_start: zathura  -x "/usr/bin/nvim --headless -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 2:48:'/home/geostartico/Documents/tesi/testo/testo.tex' 'Documents/tesi/testo/testo.pdf'&
  qf method: LaTeX logfile
```
