### ISSUE TITLE
Conceal feature hides but doesn't replace concealed text

### ISSUE THREAD

**Issue by AadiWaghray** [lervag/vimtex#2679]
### Description

When using the default conceal features which are enabled by default (and syntax enable and set conceallevel=2 as stated in the documentation), the text in question (_{a}, \omega, ^{a}, etc.) is hidden but not replaced with the appropriate characters. The error is likely a silly mistake on my side, but I have not figured it out and would like to use the conceal feature. 

### Steps to reproduce

Relevant information init.vim information is given above. Short dot file can be found at https://github.com/AadiWaghray/dotfiles (note that I currently have the feature disabled because it doesn't function). Any LaTeX file with text which should be concealed by default conceal settings should produce error. 

### Expected behavior

The text in question (_{a}, \omega, ^{a}, etc.) should be replaced with the appropriate super/subscript or greek letter.

### Actual behavior

When using the default conceal features (and syntax enable and set conceallevel=2 as stated in the documentation), the text in question (_{a}, \omega, ^{a}, etc.) is hidden but not replaced with the appropriate characters.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 13.0.1 (22A400)
  Vim version: NVIM v0.8.0-dev-775-g27ce21ac8
  Has clientserver: true
  Servername: /var/folders/pp/r7_p49sx7b94ztpczpwhflmm0000gn/T/nvim.aadiwaghray/FshY7c/nvim.18680.0

VimTeX project: Homework_3
  base: Homework_3.tex
  root: /Users/aadiwaghray/Documents/College_Notes/CS_253/Homework/Homework_3
  tex: /Users/aadiwaghray/Documents/College_Notes/CS_253/Homework/Homework_3/Homework_3.tex
  main parser: current file verified
  document class: report
  packages: algorithm2e amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm array atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook bigintcalc bitset bookmark calc cancel centernot color comment enumitem environ epstopdf-base eso-pic etexcmds etoolbox expl3 geometry gettitlestring graphics graphicx hycolor hyperref ifmtarg ifoddpage iftex ifthen ifvtex import infwarerr inputenc intcalc keyval kvdefinekeys kvoptions kvsetkeys l3keys2e letltxmacro listings listingsutf8 lscape lstlang1 lstmisc ltxcmds mathtools mhsetup multicol nameref newpxmath pdfcol pdfescape pdflscape pdfpages pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfrcs pgfsys physics pict2e qtree refcount relsize rerunfilecheck shellesc stringenc tcolorbox textcomp theoremref tikz tikz-cd tikzsymbols titletoc transparent trig trimspaces uniquecounter url varwidth verbatim xcolor xfrac xifthen xkeyval xparse xspace xtemplate
  source files:
    Homework_3.tex
    ../preamble.tex
    ../macros.tex
    ../letterfonts.tex
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
