### ISSUE TITLE
\lv opening a new window and not resizing the terminal

### ISSUE THREAD

**Issue by basava70** [lervag/vimtex#2681]
### Description

Hi, Thanks for the awesome plugin, however, I have problem with opening pdf side by side with `.tex` file. Everytime, I press `\lv`, I get a new window pop up rather than resizing of terminal. I have installed zathura, xdotools. I am using neovim fyi.

Any help or suggestion will be very helpful.
Thanks.

### Steps to reproduce

My `/plugin/vimtex-config/init.lua` file:

```lua
vim.api.nvim_command('filetype plugin indent on')
vim.g.vimtex_syntax_enabled = 1
vim.g.vimtex_view_method = 'zathura'
vim.g.vimtex_compiler_method = 'latexmk'
vim.g.maplocalleader = " "
```

I add  use `'lervag/vimtex'` in `lua/plugin/init.lua`

I call them from `init.lua`:

```lua
require('plugin')
require('vimtex-config')
```

### Expected behavior

I saw may videos and tutorials, where after `\lv` and `\ll`, termial would be resized into 2 vertical halves and pdf will be in one while `.tex` is on other.

### Actual behavior

I get a new  pop up window for the pdf from zathura.

### Do you use a latexmkrc file?

Yes

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 22.04.2 LTS
  Vim version: NVIM v0.8.3
  Has clientserver: true
  Servername: /run/user/1000/nvim.319407.0

VimTeX project: plot
  base: plot.tex
  root: /home/seshu/Desktop/Documents/Hamburg/Phase-Field/Documents/ThermalExample/mode_1/E_5e7_nu_0.4999/mode_15/[-2,2]
  tex: /home/seshu/Desktop/Documents/Hamburg/Phase-Field/Documents/ThermalExample/mode_1/E_5e7_nu_0.4999/mode_15/[-2,2]/plot.tex
  main parser: current file verified
  document class: article
  packages: amsbsy amsfonts amsgen amsmath amsopn amssymb amstext bm caption caption3 epstopdf-base float geometry graphics graphicx iftex ifvtex keyval pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfrcs pgfsys subcaption tikz trig xcolor
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 5
      output: /tmp/nvim.seshu/chqtBe/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'plot.tex'
      pid: 319533
  viewer: Zathura
    xwin id: 56623107
    cmd_start: zathura  -x "/usr/local/bin/nvim --headless -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 1:1:'/home/seshu/Desktop/Documents/Hamburg/Phase-Field/Documents/ThermalExample/mode_1/E_5e7_nu_0.4999/mode_15/[-2,2]/plot.tex' '[-2,2]/plot.pdf'&
  qf method: LaTeX logfile
```
