### ISSUE TITLE
]] imap enabled even when g:vimtex_imaps_enabled=0

### ISSUE THREAD

**Issue by shanewstone** [lervag/vimtex#2682]
### Description

The `]]` imap is enabled even if imaps are disabled using `g:vimtex_imaps_enabled`. Should the below mapping be behind some logic like `if g:vimtex_imaps_enabled`?

https://github.com/lervag/vimtex/blob/e8542f26b45e489fe7cfa7894737ccb0fe937fcd/autoload/vimtex.vim#L191

### Steps to reproduce

1. `let g:vimtex_imaps_enalbed=0` in `minimal.vim`
2. `nvim -u minimal.vim minimal.tex`

### Expected behavior

No imaps enabled

### Actual behavior

`]]` imap enabled

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Arch Linux
  Vim version: NVIM v0.9.0
  Has clientserver: true
  Servername: /run/user/1000/nvim.533192.0

VimTeX project: minimal
  base: minimal.tex
  root: /home/user
  tex: /home/user/minimal.tex
  main parser: fallback current file
  document class: 
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
