### ISSUE TITLE
<plug>(vimtex-%) fails if default mappings are turned off

### ISSUE THREAD

**Issue by Le-Kat** [lervag/vimtex#2684]
### Description

I have default keybindings disabled, since I prefer to define their keybindings myself (and I don't need like half of them). However even if I do `vim.keymap.set ("n", "%", "<plug>(vimtex-%)")`, when I open up a latex document, the `%` key doesn't properly switch between math delimiters like it does when the default mappings are enabled.

### Steps to reproduce

minimal.lua
```lua
-- not including the boilerplate needed to load plugins
vim.g["vimtex_mappings_enabled"] = false
vim.keymap.set ("n", "]]", "<plug>(vimtex-]])")
```

minimal.tex
```latex
\documentclass{minimal}
\begin{document}
$L = \{lose, C\ lose, C\ C\ lose, ...\ C^{n}\ lose\}, n \geq 0$.
\end{document}
```
steps:
1. nvim -u minimal.lua minimal.tex
2. hover over the first character of line 3 (the `$`)
3. press `%`

### Expected behavior

my cursor to jump to the final `$`

### Actual behavior

my cursor jumps to the last `}`

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
System info:
  OS: on:	Arch Linux
  Vim version: NVIM v0.8.3
  Has clientserver: true
  Servername: /run/user/1000/nvim.2925935.0

VimTeX project: assignment
  base: assignment.tex
  root: /home/le3kat/docs/code/school/latex/discreet 2/a4
  tex: /home/le3kat/docs/code/school/latex/discreet 2/a4/assignment.tex
  main parser: current file verified
  document class: article
  compiler: arara
    options:
      --log
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
