### ISSUE TITLE
Apostrophe and syntax highlighting

### ISSUE THREAD

**Issue by pwintergerst** [lervag/vimtex#2690]
### Description

I'm writing in French, so I'm using a lot of apostrophe. It is more convenient to use the _simple quote_ symbol `'` than the _real_ apostrophe `’`  because ... well ... keyboard. But every time I write an apostrophe (with simple quote), vimtex highlight it in a different color than regular text. As a result the tex source get less readable.

<img width="518" alt="Capture d’écran 2023-04-21 à 11 28 13" src="https://user-images.githubusercontent.com/96541888/233600501-98bd16f3-f255-4140-85dd-f759e35e5548.png">

I'm don't know of I misuse vimtex of if it's a bug...

I use nvim 9.0 and I don't know is it's relevant but I use Catppuccin color-scheme.

Thanks!

### Steps to reproduce

1. `nvim foo.tex`
2. Writing something like `C'est comme ça qu'on fait.`

### Expected behavior

The syntax highlight of the apostrophe should be the same than the regular text.

### Actual behavior

The syntax highlight of the apostrophe differs from the regular text.

### Do you use a latexmkrc file?

Yes. My `.latexmkrc`:

```perl
$pdflatex = 'pdflatex --shell-escape %O %S';
push @generated_exts, "synctex.gz";
push @generated_exts, "snm";
push @generated_exts, "nav";
```

### VimtexInfo

```yaml
System info:
  OS: macOS 13.1 (22C65)
  Vim version: NVIM v0.9.0
  Has clientserver: true
  Servername: /var/folders/5g/lhg4c7j51838yt0nqzhxh1rh0000gn/T/nvim.philemon/8gbWwU/nvim.1394.0

VimTeX project: test
  base: test.tex
  root: /Users/philemon
  tex: /Users/philemon/test.tex
  main parser: fallback current file
  document class: 
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Skim
  qf method: LaTeX logfile
```
