### ISSUE TITLE
Vimtex Inverse Search with Skim not working

### ISSUE THREAD

**Issue by Xydru** [lervag/vimtex#2692]
### Description

Hello, I tried setting up Inverse Search on Skim, but it didn't work. I'm using Neovim as my editor and I'm running on MacOS. I did it in the exact same as the documentation told me to do - to be more precise, I did the exact same thing as this article did in the section Inverse-Search (I can't spot any differences compared to the documentation): https://dr563105.github.io/blog/skim-vimtex-setup/

But when I opened the PDF in my `.tex` file via `:VimtexCompile`, the Skim-provided Shortcut `<cmd>-<shift>-<left-click>` doesn't do anything. Vimtex, Neovim as well as Skim have all been installed this week so everything should be up-to-date.

My Skim settings in the Sync tab:
<img width="556" alt="image" src="https://user-images.githubusercontent.com/59253224/233681570-caaffd3c-aada-4fb7-b960-1066190fdc4f.png">

My init.vim:
```vim
call plug#begin()
if has('nvim')
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
  Plug 'Shougo/deoplete.nvim'
  Plug 'roxma/nvim-yarp'
  Plug 'roxma/vim-hug-neovim-rpc'
endif
let g:deoplete#enable_at_startup = 1

Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets' " Necessary for Ultisnips
Plug 'lervag/vimtex'
Plug 'ludovicchabant/vim-gutentags'
call plug#end()

imap <C-S> <ESC>:w<CR>a

let g:tex_flavor='latex'
let g:vimtex_view_method = "skim"
let g:vimtex_view_skim_sync = 1
let g:vimtex_view_skim_activate = 1

call deoplete#custom#var('omni', 'input_patterns', {
      \ 'tex': g:vimtex#re#deoplete
      \})

let g:UltiSnipsExpandTrigger='<tab>'
let g:UltiSnipsJumpForwardTrigger='<c-b>'
let g:UltiSnipsJumpBackwardTrigger='<c-z>'
```

### Steps to reproduce

1. `nvim test.tex`
2. compiling with `:VimtexCompile`
3. `<cmd>-<shift>-<left-click>` on an arbitrary word in the pdf document in Skim (openend by vimtex)

### Expected behavior

The pointer in nvim moves to the corresponding line

### Actual behavior

Nothing happens

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 13.2.1 (22D68)
  Vim version: NVIM v0.9.0
  Has clientserver: true
  Servername: /var/folders/pc/lxy6kdgs4j7c3hdgntkkf0jh0000gn/T/nvim.felix/xVKw7I/nvim.69087.0

VimTeX project: test
  base: test.tex
  root: /Users/felix/Documents/Test
  tex: /Users/felix/Test/test.tex
  main parser: current file verified
  document class: article
  packages: algorithm algorithmicx algpseudocode amsbsy amsgen amsmath amsopn amstext babel float ifthen inputenc
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job:
      jobid: 7
      output: /var/folders/pc/lxy6kdgs4j7c3hdgntkkf0jh0000gn/T/nvim.felix/xVKw7I/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex
_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "ech
o vimtex_compiler_callback_failure"' 'test.tex'
      pid: 69097
  viewer: Skim
  qf method: LaTeX logfile
```
