### ISSUE TITLE
Highlight error in neovim 0.9

### ISSUE THREAD

**Issue by MetriC-DT** [lervag/vimtex#2693]
### Description

```
Error detected while processing BufReadPost Autocommands for "*":
Error executing lua callback: /usr/share/nvim/runtime/filetype.lua:21: Error executing lua: /usr/share/nvim/runtime/filetype.lua:22: BufReadPost Autocommands for "*"..FileType Autocommands for "*"..Syntax Autocommands for "*"..function <SNR>14_SynSet[25]..script /home/derickwtseng/.local/share/nvim/site/pack/packer/start/vimtex/syntax/tex.vim[22]..function vimtex#syntax#core#init, line 638: Vim(if):E716: Key not present in Dictionary: "spacing"

stack traceback:
        [C]: in function 'nvim_cmd'
        /usr/share/nvim/runtime/filetype.lua:22: in function </usr/share/nvim/runtime/filetype.lua:21>
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:21: in function </usr/share/nvim/runtime/filetype.lua:10>
stack traceback:
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:21: in function </usr/share/nvim/runtime/filetype.lua:10>
```

### Steps to reproduce

1. `nvim -u minimal.vim minimal.tex`

### Expected behavior

No error message on startup, and proper highlights.

### Actual behavior

Error message on startup, and no highlights

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Linux 6.2.11-300.fc38.x86_64
  Vim version: NVIM v0.9.0
  Has clientserver: true
  Servername: /run/user/1000/nvim.52913.0

VimTeX project: minimal
  base: minimal.tex
  root: /home/derickwtseng/Downloads/test
  tex: /home/derickwtseng/Downloads/test/minimal.tex
  main parser: current file verified
  document class: minimal
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
