### ISSUE TITLE
Compilation Failed

### ISSUE THREAD

**Issue by eurislee** [lervag/vimtex#2694]
### Description

Hello, I have a problem with making vimtex working on Arch Linux. Whenever I run `\ll` I get `VimTeX: Compilation failed!`. I'm not sure what is a problem, so any help would be appreciated!

`main.tex`:

```tex
\documentclass{article}
\begin{document}
First document. This is a simple example, with no
extra parameters or packages included.
\end{document}
```

`.vimrc`:

```vim
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => VimTex
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
filetype indent plugin on
syntax on
let g:tex_flavor='latex'
let g:vimtex_view_method='zathura'
let g:vimtex_quickfix_mode=0
let g:vimtex_compiler_latexmk_engines = {'_':'-xelatex'}
let g:vimtex_compiler_latexrun_engines ={'_':'xelatex'}
let maplocalleader = ","
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Tex-Conceal
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set conceallevel=1
let g:tex_conceal='abdmg'
hi Conceal ctermbg=none
```

`main.log`

```
This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023/Arch Linux) (preloaded format=xelatex 2023.4.23)  23 APR 2023 12:00
entering extended mode
 restricted \write18 enabled.
 file:line:error style messages enabled.
 %&-line parsing enabled.
**main.tex
(./main.tex
LaTeX2e <2022-11-01> patch level 1
L3 programming layer <2023-02-22> (/usr/share/texmf-dist/tex/latex/base/article.cls
Document Class: article 2022/07/02 v1.4n Standard LaTeX document class
(/usr/share/texmf-dist/tex/latex/base/size10.clo
File: size10.clo 2022/07/02 v1.4n Standard LaTeX file (size option)
)
\c@part=\count181
\c@section=\count182
\c@subsection=\count183
\c@subsubsection=\count184
\c@paragraph=\count185
\c@subparagraph=\count186
\c@figure=\count187
\c@table=\count188
\abovecaptionskip=\skip48
\belowcaptionskip=\skip49
\bibindent=\dimen140
) (/usr/share/texmf-dist/tex/latex/l3backend/l3backend-xetex.def
File: l3backend-xetex.def 2023-01-16 L3 backend support: XeTeX
\g__graphics_track_int=\count189
\l__pdf_internal_box=\box51
\g__pdf_backend_object_int=\count190
\g__pdf_backend_annotation_int=\count191
\g__pdf_backend_link_int=\count192
) (./main.aux)
\openout1 = `main.aux'.

LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 2.
LaTeX Font Info:    ... okay on input line 2.
LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 2.
LaTeX Font Info:    ... okay on input line 2.
LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 2.
LaTeX Font Info:    ... okay on input line 2.
LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 2.
LaTeX Font Info:    ... okay on input line 2.
LaTeX Font Info:    Checking defaults for TS1/cmr/m/n on input line 2.
LaTeX Font Info:    Trying to load font information for TS1+cmr on input line 2.
 (/usr/share/texmf-dist/tex/latex/base/ts1cmr.fd
File: ts1cmr.fd 2022/07/10 v2.5l Standard LaTeX font definitions
)
LaTeX Font Info:    ... okay on input line 2.
LaTeX Font Info:    Checking defaults for TU/lmr/m/n on input line 2.
LaTeX Font Info:    ... okay on input line 2.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 2.
LaTeX Font Info:    ... okay on input line 2.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 2.
LaTeX Font Info:    ... okay on input line 2.
 [1

] (./main.aux) )
Here is how much of TeX's memory you used:
 460 strings out of 476683
 9400 string characters out of 5809790
 1843018 words of memory out of 5000000
 20786 multiletter control sequences out of 15000+600000
 512295 words of font info for 33 fonts, out of 8000000 for 9000
 1348 hyphenation exceptions out of 8191
 33i,5n,38p,143b,107s stack positions out of 5000i,500n,10000p,200000b,80000s

Output written on main.xdv (1 page, 1268 bytes).
```

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
   OS: Arch Linux
   Vim version: VIM 9.0 (1-1420)
   Has clientserver: false

 VimTeX project: main
   base: main.tex
   root: /home/euris/Documents/notes
   tex: /home/euris/Documents/notes/main.tex
   main parser: current file verified
   document class: article
   compiler: latexmk
     engine: -xelatex
     options:
       -verbose
       -file-line-error
       -synctex=1
       -interaction=nonstopmode
     callback: 1
     continuous: 1
     executable: latexmk
   viewer: Zathura
     xwin id: 0
   qf method: LaTeX logfile
```
