### ISSUE TITLE
Rnw files cause a message error on macos with neovim 0.9.0

### ISSUE THREAD

**Issue by jpasquier** [lervag/vimtex#2695]
### Description

When I open a rnoweb file, I get the following error message:

```
Error detected while processing BufReadPost Autocommands for "*":
Error executing lua callback: ...brew/Cellar/neovim/0.9.0/share/nvim/runtime/filetype.lua:21: Error executing lua: ...brew/Cellar/neovim/0.9.0/share/nvim/runtime/filetype.lua:22: BufReadPost Autocommands for "*"..FileType Autocommands for "*"..function <SNR>2_LoadIndent[14]..script /Users/u0189152/.brew/Cellar/neovim/0.9.0/share/nvim/runtime/indent/rnoweb.vim, line 21: Vim(let):E475: Invalid argument: VimtexIndent(v:lnum)
stack traceback:
        [C]: in function 'nvim_cmd'
        ...brew/Cellar/neovim/0.9.0/share/nvim/runtime/filetype.lua:22: in function <...brew/Cellar/neovim/0.9.0/share/nvim/runtime/filetype.lua:21>
        [C]: in function 'nvim_buf_call'
        ...brew/Cellar/neovim/0.9.0/share/nvim/runtime/filetype.lua:21: in function <...brew/Cellar/neovim/0.9.0/share/nvim/runtime/filetype.lua:10>
stack traceback:
        [C]: in function 'nvim_buf_call'
        ...brew/Cellar/neovim/0.9.0/share/nvim/runtime/filetype.lua:21: in function <...brew/Cellar/neovim/0.9.0/share/nvim/runtime/filetype.lua:10>
Press ENTER or type command to continue
```
 
Is that related to issue #759 (closed)?

### Steps to reproduce

minimal.vim:

```
call plug#begin('~/.local/share/nvim/plugged')
Plug 'lervag/vimtex'
call plug#end()
```

minimal.Rnw:

```
\documentclass{article}
\begin{document}
\end{document}
```

### Expected behavior

No error message

### Actual behavior

Error message (see above)

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 12.6.3 (21G419)
  Vim version: NVIM v0.9.0
  Has clientserver: true
  Servername: /var/folders/cm/hv6w580n247gnkdjfqgpf9wdkk3cvh/T/nvim.u0189152/Lah5Tl/nvim.11940.0

VimTeX project: minimal
  base: minimal.Rnw
  root: /Users/u0189152
  tex: 
  main parser: fallback current file
  document class: 
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Skim
  qf method: LaTeX logfile
```
