### ISSUE TITLE
Weird slowdown after compilation on complex projects

### ISSUE THREAD

**Issue by griffinwxk** [lervag/vimtex#2696]
### Description

This is a weird issue that I did some digging myself but with little success so it might take a while. Also this issue probably won't appear for light LaTeX users so I apologize ahead for not able to produce an MWE at this time but am happy to assist with debugging over time.

So I'm a pretty heavy user of LaTeX and I put all my common settings and commands into a .sty file, about 800+ lines in total. I have this LaTeX document of about 1500+ lines (about the length of a section or a chapter in any of my typical projects, so dividing the file is usually not an option) with lots of math. Here's the list of weird behaviors:
-  If I open the file on Neovim without compiling it (or delete all the compilations), everything is fine.
- After compiling it, if the cursor is on some early lines (like less than 1100 or something), things are fine too. 
- Then if I jump to some late part of the file (say with G command), the UI suddenly starts to crawl. 
- If I jump back to early part of the file (say with gg), things revert back to normal. 
- If I manually move up the cursor from, say line 1200 back to some 1100, things also suddenly revert back to normal (so there's a "breaking point" of some sorts past certain line number or file size). 
- Moreover, if in the late part of the file I press C-d to scroll down (or some other command to go down, like pressing j enough times), it will also revert the UI back to being responsive again, but if I then move cursor up with C-u or just k enough times (going past the point I started using C-d/j/etc.), UI starts to crawl again until it moves back to the "breaking point" of about line 1100.
- I tried to move stuff from my .sty file into the document instead, and it DOES fix the problem but I use my "personal package" for all my LaTeX project and I don't want to just copy-paste for every new project.
- I tried removing the VimTeX highlighting, and (IIRC) it DOES fix the problem but I don't want to give it up because it's so good.
- I tried the same document with all math removed, and everything is good. So definitely math and syntax highlighting related.
- I tried turning conceal off, no good.

I'm reasonably confident it's related to some interaction between VimTeX syntax (about math) and custom packages, so here are the main things I did with syntax:
- I use conceal on and conceallevel=1, and I defined some new conceals based on my own LaTeX commands. But conceal doesn't seem to be the culprit as I noted above.
- I use kanagawa theme and used their color palette to customize some of the VimTeX highlight groups (but not all)

Finally, I don't believe the said behavior was there early last year. I noticed it between late 2022 and like Feb 2023 or something but I cannot pinpoint the time and a lot has happened in Neovim landscape during the time.

I don't expect this to be immediately solvable so I will keep monitoring this issue and happy to discuss and provide more details. Thanks! (And thanks for the awesome plugin as always!)

### Steps to reproduce

Currently I cannot generate a reproducible example without posting some of my personal stuff due to the nature of the issue (being related to some complex customization), but am happy to help with testing potential solutions.

### Expected behavior

UI should always be responsive

### Actual behavior

UI has weird slowness described in the description.

### Do you use a latexmkrc file?

Yes with only aux_dir set to "build"

### VimtexInfo

```yaml
System info:
  OS: macOS 12.6 (21G115)
  Vim version: NVIM v0.9.0
  Has clientserver: true
  Servername: /var/folders/y0/rlskvs3n0tb77fjc8v33zqcc0000gn/T/nvim.(my username)/DsJu9w/nvim.65346.0

VimTeX project: test
  base: test.tex
  root: /Users/(my username)/workbench/LaTeXtmp/mwe
  tex: /Users/(my username)/workbench/LaTeXtmp/mwe/test.tex
  main parser: current file verified
  document class: amsart
  packages: amsbsy amsfonts amsgen amsmath amsopn amsrefs amssymb amstext atbegshi-ltx atveryend-ltx autonum auxhook bigintcalc bitset calc cleveref (my personal package here) ctablestack environ epstopdf-base etex etexcmds etextools etoolbox expl3 fix-cm fontenc fontspec fontspec-luatex geometry gettitlestring graphics graphicx hycolor hyperref ifluatex ifoption iftex ifvtex import infwarerr intcalc keyval kvdefinekeys kvoptions kvsetkeys l3keys2e letltxmacro ltxcmds luacode lualatex-math luatexbase mathscinet mathtools mhsetup nameref pcatcode pdfescape pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfrcs pgfsys refcount rerunfilecheck rkeyval stmaryrd stringenc tcolorbox textcmds textpos tikz tikz-cd tikzfill-common tikzfill.image trig trimspaces unicode-math unicode-math-luatex uniquecounter url verbatim xcolor xparse
  compiler: latexmk
    engine: -lualatex
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    build_dir: ./build
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 5
      output: /var/folders/y0/rlskvs3n0tb77fjc8v33zqcc0000gn/T/nvim.(my username)/DsJu9w/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -lualatex -outdir=./build -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'test.tex'
      pid: 65616
  viewer: Skim
  qf method: LaTeX logfile
```
