### ISSUE TITLE
Mac Skim inverse search not working -- resolved

### ISSUE THREAD

**Issue by ThSGM** [lervag/vimtex#2701]
### Description

I don't have time to write a detailed report, but I will write a few words because it is important to document. I could not get my inverse search working with vimtex and macos Skim. Terminal was iTerm2. I documented this issue [here](https://www.reddit.com/r/neovim/comments/12dlkhh/nvim_vimtex_why_isnt_neovim_creating_a_server_by/)

I am trying to get reverse searching working with vimtex ([u/lervag](https://www.reddit.com/u/lervag)) on macOS with Skim. Here is the [guide](https://dr563105.github.io/blog/skim-vimtex-setup/). However, it wasn't working. Typing in:

    :echo v:servername

returned blank. I managed however to get it working by running

```sh
nvim --listen tmp/nvimsocket filename.tex
```

And now the echo commands returns the name of that folder, and also the reverse searching now works. I thought that neovim should already be creating a server by default on launch. Do you know why it's not and I have to create one manually?

#### Issue 1

This thread helped me: https://github.com/neovim/neovim/issues/20865

In particular, the command:

    :edit $NVIM_LOG_FILE

indicated that it was unable to start a server due to not having the folder `$XDG_RUNTIME_DIR` which was my home folder with .xdg.

I created this folder with mkdir and now the servers start up and the reverse searching works. I don't know why I didn't have this folder in the first place.

#### Issue 2

For whatever reason, the snippet for Skim listed in the vimtex help file did not work. I can confirm that the below command does not work on my version of Skim: 

    --headless -c "VimtexInverseSearch %l '%file'"

However, this version does work:

    --headless -c "VimtexInverseSearch %line '%file'"

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
System info:
  OS: macOS 12.6.3 (21G419)
  Vim version: NVIM v0.8.1
  Has clientserver: true
  Servername: /Users/redacted/.xdg/nvim.2195.0

VimTeX project: MA30287-2022-23Supplemental2
  base: MA30287-2022-23Supplemental2.tex
  root: Redacted
  tex: Redacted
main parser: current file verified
  document class: exam
  packages: amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm atbegshi atbegshi-ltx auxhook bm calc caption caption3 color comment empheq enumitem epstopdf-base etexcmds etoolbox exam expl3 fancyheadings graphics graphicx iftex infwarerr keyval kvdefinekeys kvoptions kvsetkeys lastpage ltxcmds mathtools mdframed mhsetup microtype needspace pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfplots pgfrcs pgfsys pifont soul textcomp tikz trig wasysym xcolor xparse zref-abspage zref-base
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -f
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 5
      output: /var/folders/nj/g3zn51j90_x4m2w7kzh0k7br0000gp/T/nvim.redacted/VPzQgF/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -f -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'MA30287-2022-23Supplemental2.tex'
      pid: 2202
  viewer: Skim
  qf method: LaTeX logfile
```
