### ISSUE TITLE
Syntax not detecting minted environment

### ISSUE THREAD

**Issue by evesdropper** [lervag/vimtex#2702]
### Description

Tested out some python snippets in tex document, and they don't seem to be working. Upon further inspection, in a minted environment `:echo vimtex#syntax#in("texMintedZonePython")` returns 0.

This also seems to be the case for other languages, but otherwise the syntax works fine for other tasks such as detecting mathzone.

### Steps to reproduce

1. `nvim test.tex`
2. Ensure cursor is in minted environment, go to command mode, and enter `:echo vimtex#syntax#in("texMintedZonePython")`

### Expected behavior

Returns 1

### Actual behavior

Returns 0

### Do you use a latexmkrc file?

Yes, but probably not too applicable here

### VimtexInfo

```yaml
System info:
  OS: Linux 5.19.11-arch1-1
  Vim version: NVIM v0.9.0
  Has clientserver: true
  Servername: /run/user/1000/nvim.32079.0

VimTeX project: test
  base: test.tex
  root: /home/revise
  tex: /home/revise/test.tex
  main parser: fallback current file
  document class: 
  compiler: latexmk
    engine: -lualatex
    options:
      -shell-escape
      -verbose
      -file-line-error
      -interaction=nonstopmode
      -synctex=1
    build_dir: out
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: sioyek
  qf method: LaTeX logfile
```
