### ISSUE TITLE
Tectonic compiler method doesn't parse errors properly

### ISSUE THREAD

**Issue by doronbehar** [lervag/vimtex#2703]
### Description

Using Tectonic 0.12.0, I noticed that an error appearing on CLI like this:

```
error: nanophotonics-hw2.tex:78: Missing $ inserted
error: halted on potentially-recoverable error as specified
```

Doesn't _always_ appear on Vimtex' quickfix - I experience this with some files, an example file appears below.

### Steps to reproduce

Open Vimtex' `test/test-doc/test.tex` and add a single `$` that will produce an error:

```patch
diff --git i/test/test-doc/test.tex w/test/test-doc/test.tex
index d13fab9d..fee8bb51 100644
--- i/test/test-doc/test.tex
+++ w/test/test-doc/test.tex
@@ -6,6 +6,8 @@
 
 \begin{document}
 
+$
+
 Hello World!
 
 \end{document}
```

Try to compile the error after you `let g:vimtex_compiler_method = 'tectonic'`.

### Expected behavior

Vimtex opens the quickfix and showing the error:

```
error: test.tex:10: Missing $ inserted
```

### Actual behavior

Vimtex doesn't open up the quickfix, and it is empty. Where if you run manually `tectonic test.tex` you see:

```
Running TeX ...
error: test.tex:10: Missing $ inserted
error: halted on potentially-recoverable error as specified
```

### Do you use a latexmkrc file?

No, tectonic.

### VimtexInfo

```yaml
System info:
  OS: NixOS 23.05 (Stoat)
  Vim version: NVIM v0.9.0
  Has clientserver: true
  Servername: /run/user/1000/nvim.570012.0

VimTeX project: test
  base: test.tex
  root: /home/doron/.files/.config/nvim/pack/filetype/start/tex/test/test-doc
  tex: /home/doron/.files/.config/nvim/pack/filetype/start/tex/test/test-doc/test.tex
  main parser: current file verified
  document class: article
  packages: amsmath mathtools tikz
  compiler: tectonic
    options:
      --keep-logs
      --synctex
    job: 
      jobid: 42
      output: /tmp/nvim.doron/3mWc7y/0
      cmd: tectonic --keep-logs --synctex --outdir="/home/doron/.files/.config/nvim/pack/filetype/start/tex/test/test-doc" 'test.tex'
  viewer: General
  qf method: LaTeX logfile
```
