### ISSUE TITLE
Weird cmd prompt pop up when compiling

### ISSUE THREAD

**Issue by resort09** [lervag/vimtex#2706]
### Description

Hi everyone, I am a beginner of Nvim and GitHub. I know almost nothing about the cool techy knowledge (programming, operation system, etc.). However, as my study gets more math-intense, I was trying to use latex to document lecture notes and all kinds of writings. And I finally found the combination of Nvim+Vimtex has been proved to be a feasible solution. 

After days' struggling, I finally made my Nvim and Vimtex work. It could compile and produce pdfs. However, two problems showed.

1. When compiling, a weird cmd prompt popped up. And I can't input anything into this cmd prompt.

https://github.com/lervag/vimtex/assets/34515663/cc13add3-aa5b-4d9f-a7c6-fef14ce7d4bb

2. After I closed Sumatrapdf and wanted re-compile the `.tex` again, compiler stopped. And it won't compile until I `\ll` or `VimtexCompile` at the second time.

https://github.com/lervag/vimtex/assets/34515663/b268a861-5c3a-42c6-b9d4-dad4cead8665

And the closest case I found is #2601, however, my problem didn't get fixed when I run Nvim as Administrator.

I really appreciate any comments and/or advice! Also, I am quite new to GitHub, please let me know if I missed any information or failed to follow GitHub rules! Thank you!

### Steps to reproduce

1. Set `init.vim` file as below.
```
call plug#begin()

Plug 'lervag/vimtex'
Plug 'SirVer/ultisnips'

call plug#end()

let g:tex_flavor='latex'
let g:vimtex_compiler_method = 'latexmk'
let g:vimtex_view_general_viewer='sumatrapdf'
let g:vimtex_quickfix_mode=0
let g:tex_conceal='abdmg'
```
2. Edit `.tex` file as below.
```
\documentclass{article}
\begin{document}
\[x^2+y^3+6^e\]
\[xy^3\]
di
thi
\end{document}
```
3. `\ll`, the Problem 1 showed.
4. Close cmd prompt and PDFviewer,  `\\`, then it suggest compiler stopped.
5. `\ll` again, worked.

### Expected behavior

1. No cmd prompt window popped up.
2. I can compile again after I close the PDFviewer. (No need to compile twice and failed the first one)

### Actual behavior

1. A cmd prompt poped up.
2. After I close the PDFviewer and wanted to compile again, compiler stopped. I needed to `\ll` the second time to make it work.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
info:
  OS: LASTRESORT (Microsoft Windows 11 Home)
  Vim version: NVIM v0.9.0
  Has clientserver: true
  Servername: \\.\pipe\nvim.6356.0

VimTeX project: text
  base: text.tex
  root: C:\Users\stard
  tex: C:\Users\stard\text.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 11
      output: C:\Users\stard\AppData\Local\Temp\nvim.0\85e4l9\0
      cmd: set max_print_line=2000 & latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e "$compiling_cmd = ($compiling_cmd ? $compiling_cmd . ' ^& ' : '') . 'echo vimtex_compiler_callback_compiling'" -e "$success_cmd = ($success_cmd ? $success_cmd . ' ^& ' : '') . 'echo vimtex_compiler_callback_success'" -e "$failure_cmd = ($failure_cmd ? $failure_cmd . ' ^& ' : '') . 'echo vimtex_compiler_callback_failure'" "text.tex"
      pid: 9048
  viewer: General
    job: 
      pid: -
      cmd: sumatrapdf -reuse-instance -forward-search "C:\Users\stard\text.tex" 7 "C:\Users\stard/text.pdf"
  qf method: LaTeX logfile
```
