### ISSUE TITLE
Inline math environment is not detected by ts$ command

### ISSUE THREAD

**Issue by Ma94xx** [lervag/vimtex#2707]
Inline math  (`$1+1=2$`) is not detected as environment, hence no commands like `ts$` or `ci$` are working. If I try to toggle from displaymath, it works as expected. 

### Steps to reproduce

1. `nvim -u minimal.vim minimal.tex`
2. Insert some inline math e.g. `$3+3=6$`
3. Jump to the delimiter 
4. Press `ts$` in normalmode

### Expected behavior

I expect `$3+3=6$` to change to `\begin{displaymath}3+3=6\end{displaymath}`

### Actual behavior

The cursor jumps to the next `$` sign or does nothing, but no other changes are made

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Linux 6.3.1-arch1-1
  Vim version: NVIM v0.9.0
  Has clientserver: true
  Servername: /run/user/1000/nvim.136216.0

VimTeX project: minimal
  base: minimal.tex
  root: /home/max
  tex: /home/max/minimal.tex
  main parser: fallback current file
  document class: 
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```

Edit: After updating nvim, I get this error message when trying to toggle displaymath with `ts$`
![photo_2023-05-15_21-49-50](https://github.com/lervag/vimtex/assets/33165574/927b5c34-87a8-4314-9804-672b36e21e6a)
