### ISSUE TITLE
`syntax foldlevel` not available for vim < 8.2

### ISSUE THREAD

**Issue by bwhelm** [lervag/vimtex#2708]
### Description

With commit 18255a2, vimtex uses `syntax foldlevel`. However, `syntax foldlevel` was introduced in patch 8.2.0865, and throws an error (`E410: Invalid :syntax subcommand`) on earlier versions of vim whenever a `.tex` file is opened.

### Do you use a latexmkrc file?

n/a

### VimtexInfo

```yaml
System info:
  OS: MacOS/i[Pad]OS
  Vim version: VIM 8.1 (1-2110)
  Has clientserver: false

VimTeX project: 
  base: 
  root: 
  tex: 
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
