### ISSUE TITLE
Citation completion replaces seach term by first suggestion

### ISSUE THREAD

**Issue by firubat** [lervag/vimtex#2709]
### Description

When I trigger citation completion using some search term, the term is automatically replaced by the first suggestion in the popup menu. This way, if I want to refine my search I have to delete what was inserted (which is quite annoying).
 Is there a way to configure so that the search term is replaced only when I specifically choose a suggestion?

### Steps to reproduce

`minimal.vim`  as example.
`minimal.tex`:
```\documentclass{minimal}
\begin{document}
Hello world!
\cite{
\bibliography{Bib.file}
\end{document} 
```
Replace Bib.file with some .bib file containing entries.
With cursor at at `\cite{` press `<C-x><C-o>`

### Expected behavior

Popup menu should appear, but no text inserted after the \cite{ until I choose a specific option. 
When typing, search results narrow.

### Actual behavior

Key of first suggestion is inserted after \cite{

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
System info:
  OS: Linux 6.0.16-300.fc37.x86_64
  Vim version: NVIM v0.9.0
  Has clientserver: true
  Servername: /run/user/1000/nvim.214720.0

VimTeX project: minimal
  base: minimal.tex
  root: /home/ur
  tex: /home/ur/minimal.tex
  main parser: current file verified
  document class: minimal
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
