### ISSUE TITLE
"Scratch" window appearing at citation completion

### ISSUE THREAD

**Issue by firubat** [lervag/vimtex#2710]
### Description

When I trigger citation completion, a window (etitled [scratch] [preview] ) opens with the info of the highlighted suggestion. It remains open after selection.

![image](https://github.com/lervag/vimtex/assets/22095250/1b4d4b9b-4519-49ce-956b-f29e90ea31f0)

[Screencast from 2023-05-16 21-38-02.webm](https://github.com/lervag/vimtex/assets/22095250/42efe610-2b69-4b6a-b13e-116fe1cc443f)

### Steps to reproduce

`minimal.vim`  as example.
`minimal.tex`:
```\documentclass{minimal}
\begin{document}
Hello world!
\cite{
\bibliography{Bib.file}
\end{document} 
```
Replace Bib.file with some .bib file containing entries.
With cursor at at `\cite{` press `<C-x><C-o>`

### Expected behavior

Either no additional window is opened (as the info appears in the menu as well) OR that the menu disappears with the popup menu after selecting a suggestion.

### Actual behavior

As described above,

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
System info:
  OS: Linux 6.0.16-300.fc37.x86_64
  Vim version: NVIM v0.9.0
  Has clientserver: true
  Servername: /run/user/1000/nvim.214720.0

VimTeX project: minimal
  base: minimal.tex
  root: /home/ur
  tex: /home/ur/minimal.tex
  main parser: current file verified
  document class: minimal
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
