### ISSUE TITLE
luaError links to Error on closing luaParen with lualatex

### ISSUE THREAD

**Issue by ejmastnak** [lervag/vimtex#2711]
### Description

I would like to preface this by saying that:

1. I am completely new to LuaLaTeX, and so might be missing something obvious
1. I totally understand if handling LuaLaTeX syntax is out of scope for VimTeX, since I imagine this a whole new can of worms to deal with

## Description

I'm running into a few syntax errors with LuaLaTeX (using the `\directlua` command and `luacode` environment, both to inject Lua code into LaTeX) that I believe should not be there; this is probably best summarized with the screenshot below and should (hopefully) be reproducible with the supplied `minimal.tex`
 
![screenshot](https://github.com/lervag/vimtex/assets/50270681/7cbc2ad5-7e5b-4e40-b219-7b8b8aadc42a)

## minimal.tex

```tex
% !TEX program = lualatex
\documentclass{minimal}
\usepackage{luacode}

\begin{document}

% `:Inspect` shows "luaError links to Error"  on closing ) and } 
\directlua{tex.print("Foo")}

\end{document}
```

## minimal.vim

```vim
set nocompatible
let &runtimepath  = '~/dotfiles/config/nvim/plugged/vimtex,' . &runtimepath
let &runtimepath .= ',~/dotfiles/config/nvim/plugged/vimtex/after'
filetype plugin indent on
syntax enable
```

## not-so-minimal.tex

I originally ran into a problem with the `luacode` environment when using Lua to parse some JSON; I'm including this as well since I'm not sure if it involves the same issue as with `\directlua` in `minimal.tex`

![not-quite-minimal](https://github.com/lervag/vimtex/assets/50270681/ce037e43-6b06-489b-8537-a3481e293e94)

Here is the file:

```tex
% !TEX program = lualatex
\documentclass{article}
\usepackage{luacode}

\begin{document}

% Not-quite minimal example (which will not compile without unless a foo.json
% is in the working directory)
\begin{luacode}
local file = "foo.json"
local str = file:read('*a')
file:close()
require("lualibs.lua")
tab =  utilities.json.tolua(str)
\end{luacode}

\end{document}
```

Thank you as always for the amazing plugin, which makes LaTeX a pleasure to write!

### Steps to reproduce

1. `nvim --clean -u minimal.vim minimal.tex`
3. Move cursor to closing paren or brace
3. `:Inspect`

### Expected behavior

No syntax errors reported for `minimal.tex`

### Actual behavior

`:Inspect` shows `luaError`

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Arch Linux
  Vim version: NVIM v0.9.0
  Has clientserver: true
  Servername: /run/user/1000/nvim.2505783.0

VimTeX project: minimal
  base: minimal.tex
  root: /home/ej/tmp/luatex
  tex: /home/ej/tmp/luatex/minimal.tex
  main parser: current file verified
  document class: minimal
  packages: ctablestack ifluatex iftex luacode luatexbase
  compiler: latexmk
    engine: -lualatex
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
```
