### ISSUE TITLE
Default mappings cannot be enabled

### ISSUE THREAD

**Issue by Zezinoo** [lervag/vimtex#2714]
### Description

Firstly, thanks for the amazing plugin. It has been a joy learning to use it and it has made writing latex way more enjoyable for me. That being said, It seems i can't be able to use the default mappings , as defined in the documentation. I've resorted to manually remapping the plugin options in my init files (I'm using an init.lua in neovim) and that works fine, but i would like to know if there's something I'm missing that makes the mappings be deactivated.
As of now, I've tried adding `"let g:vimtex_mappings_enabled=1"` (wrapped inside a `vim.cmd() `function )  to the init files and also disabling all other plugins except for vimtex and my package manager, but that yielded no different results 

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 22.04.2 LTS
  Vim version: NVIM v0.10.0-dev
  Has clientserver: true
  Servername: /run/user/1000/nvim.22097.0

VimTeX project: test
  base: test.tex
  root: /home/jalves/.config/nvim
  tex: /home/jalves/.config/nvim/test.tex
  main parser: fallback current file
  document class: 
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
