### ISSUE TITLE
Getting vimtex completion to work in LunarVim?

### ISSUE THREAD

**Issue by a-torgovitsky** [lervag/vimtex#2719]
### Description

I'm trying to get vimtex completion working in LunarVim, which uses nvim-cmp.
Here is my config.lua:
```lua
lvim.plugins = {
  {'lervag/vimtex',
    init = function()
    end},
  {'hrsh7th/cmp-omni'}, -- Needed for vimtex completion with nvim-cmp
}

local cmp = require('cmp')
cmp.setup {
  sources = cmp.config.sources { { name = 'omni', }, }
}
```

The second bit of code is as described in `h: vimtex-complete-nvim-cmp`.

I don't get any vimtex-specific completion (e.g. packages, citations) in .tex files.
Other vimtex features work as expected.

Any idea what I am doing wrong?

### Steps to reproduce

LunarVim 1.3
NVim 0.9.0

### Expected behavior

Package completion after `\usepackage{`

### Actual behavior

The only completions suggested are from snippet and buffer.

### Do you use a latexmkrc file?

Yes, but I don't think it should be relevant. (Compilation works fine, as do all other vimtex features.)

### VimtexInfo

```yaml
System info:
  OS: Linux Mint 20
  Vim version: NVIM v0.9.0
  Has clientserver: true
  Servername: /run/user/1000/lvim.3343735.0

VimTeX project: minimal
  base: minimal.tex
  root: /home/at/pantheon/scratchspace/vim-testing
  tex: /home/at/pantheon/scratchspace/vim-testing/minimal.tex
  main parser: fallback current file
  document class: 
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
