### ISSUE TITLE
Running `:PackerSync` with vimtex causes neovim to crash

### ISSUE THREAD

**Issue by thatonemailbox** [lervag/vimtex#2724]
### Description

I use Neovim, and I use [packer](https://github.com/wbthomason/packer.nvim) to install and manage my plugins. I have the following code in my "plugins.lua":
```
return packer.startup(function(use)

	use "wbthomason/packer.nvim"
	use "nvim-lua/popup.nvim"
	use "nvim-lua/plenary.nvim"
	use 'lervag/vimtex'

end)
```
If I run `:PackerSync` with any other plugin, everything will be fine; but if I include the line 	`use 'lervag/vimtex'`, Neovim will crash after every sync.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: LAPTOP-7RC87GHR (Microsoft Windows 11 Home)
  Vim version: NVIM v0.9.0
  Has clientserver: true
  Servername: \\.\pipe\nvim.16888.0

VimTeX project: test
  base: test.tex
  root: C:\Users\danim\Desktop
  tex: C:\Users\danim\Desktop\test.tex
  main parser: fallback current file
  document class: 
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
