### ISSUE TITLE
Viewer issues

### ISSUE THREAD

**Issue by karma-riuk** [lervag/vimtex#2725]
### Description

After a recent update of all my plugins, I don't know what happened, but I am unable to perform both forward and backward search.

Furthermore, even when I with the line 
```vim
let g:vimtex_view_method = 'zathura'
```
vimtex seems to ingore it.

Finally, each time I start he compiler in continuous mode, it opens a new instance of zathura regardless of whether one was already open with that same file inside already.

### Expected behavior

What I expect (and what was happening before) is that:

1. When I'm on a line in neovim and I press `\lv`, it highlights in `zathura`. Similarly, for backward search, I control-clicked a word in `zathura` and my cursor in neovim what moved to the corresponding spot in the document.

2. When I set the variable 
    ```vim
    let g:vimtex_view_method = 'zathura'
    ```
    The viewer in `VimtexInfo` changes to `zathura` (not sure that it happened before on this one because I never really looked at `VimtexInfo` before now).
3. When I open a new instance of neovim, start the compiler in continuous mode, if there is an instance of `zathura` showing the compiled file, it doens't open a new instance.

### Actual behavior

Now what happens is that:
1. When I press `\lv` it just opens a new instance of zathura. No forward search is performed. Similarly, when I control-click, nothing happens in neovim.
2. Independently of what value I put in `g:vimtex_view_method` (I tried with `"zathura"` and `"mupdf"`), `VimtexInfo` always shows the viewer as `General` using `cmd: xdg-open`. If I have the following line though
    ```vim
    let g:vimtex_view_general_viewer = 'mupdf'
    ```
    The `cmd` of `General` shows `mupdf`.
3. When I open a new instance of neovim, start the compiler in continuous mode, a new instance of `zathura` is opened regardless of pre-existing instances.

### Do you use a latexmkrc file?

Yes

### VimtexInfo

```yaml
System info:
  OS: Linux 6.3.5-arch1-1
  Vim version: NVIM v0.9.1
  Has clientserver: true
  Servername: /run/user/1000/nvim.253296.0

VimTeX project: asdf
  base: asdf.tex
  root: /tmp/tests
  tex: /tmp/tests/asdf.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 11
      output: /tmp/nvim.karma/oMddb2/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'asdf.tex'
      pid: 253373
  viewer: General
    job: 
      pid: 253494
      cmd: xdg-open '/tmp/tests/asdf.pdf'
  qf method: LaTeX logfile
```
