### ISSUE TITLE
`\hyperref[` not behaving as `\ref{` and not showing list of labels to cross-reference

### ISSUE THREAD

**Issue by whisperity** [lervag/vimtex#2730]
### Description

Reference label completion list does not open following `\hyperref[` (for [custom-labelled references](http://example.com)) even though `\ref{` or `\cref{` opens the list normally.

### Steps to reproduce

```latex
\documentclass{report}

\usepackage{hyperref}
\usepackage{cleveref} % #pragma comment "must be loaded *after* hyperref!"

\begin{document}

\chapter{X}\label{ChX}
\section{Foo}\label{Foo}
\subsection{Bar}\label{Bar}

%

\end{document}
```

Navigate to the line indicated by `%` and start typing `\ref{` or `\cref{`, and `\hyperref[`

### Expected behavior

A dropdown should appear for all three commands, like this:
![`\ref{` drop-down auto-completing labels](https://github.com/lervag/vimtex/assets/1969470/daca7cec-1bb5-45a4-89a7-3fa3d52cd40b)

### Actual behavior

No drop-down is shown for arguments of the `\hyperref[` command.

![Stale `\hyperref[` command entered](https://github.com/lervag/vimtex/assets/1969470/8a9fc6e3-6d54-477b-9436-f21808f22d60)

----

The code is valid nevertheless and the PDF otherwise generates normally:

![Generated PDF file for the minimal example](https://github.com/lervag/vimtex/assets/1969470/eec1ed60-d7f5-4d9d-a868-687a9ad2a33f)

### Do you use a latexmkrc file?

Yes (but this should not be relevant to the issue).

```latexmkrc
$pdf_mode = 5;
$dvi_mode = $postscript_mode = 0;
$max_repeat = 12;
$out_dir = "Build";
```

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 22.04.1 LTS
  Vim version: NVIM v0.9.0-dev-1204+g0ce626b78
  Has clientserver: true
  Servername: /run/user/1000/nvim.8073.0

VimTeX project: minimal
  base: minimal.tex
  root: /home/whisperity/University/PhD-Thesis
  tex: /home/whisperity/University/PhD-Thesis/minimal.tex
  main parser: fallback current file
  document class:
  packages: atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook bigintcalc bitset cleveref etoolbox gettitlestring hycolor hyperref iftex infwarerr intcalc keyval kvdefinekeys kvoptions kvsetkeys letltxmacro ltxcmds nameref pdfescape pdftexcmds refcount rerunfilecheck stringenc uniquecounter url
  compiler: latexmk
    engine: -xelatex
    options:
      -shell-escape
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    build_dir: Build
    callback: 1
    continuous: 1
    executable: latexmk
    job:
      jobid: 992
      output: /tmp/nvim.whisperity/3lfpQp/3
      cmd: max_print_line=2000 latexmk -shell-escape -verbose -file-line-error -synctex=1 -interaction=nonstopmode -xelatex -outdir=Build -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'minimal.tex'
      pid: 87146
  viewer: General
    job:
      pid: -
      cmd: xdg-open '/home/whisperity/University/PhD-Thesis/Build/minimal.pdf'
  qf method: LaTeX logfile
```
