### ISSUE TITLE
VimTeX error: Latexmk is not executable

### ISSUE THREAD

**Issue by paniash** [lervag/vimtex#2735]
### Description

After the recent update of texlive, I'm getting an error through vimtex stating that "latexmk is not executable". I understand this is not a vimtex-specific issue but I'd appreciate if anyone could help me figure out what happened to latexmk.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Linux 6.1.34-1-lts
  Vim version: NVIM v0.10.0-dev-535+g8c9dab3e0
  Has clientserver: true
  Servername: /run/user/1000/nvim.8375.0

VimTeX project: resume
  base: resume.tex
  root: /home/ashish/documents/personal/resume
  tex: /home/ashish/documents/personal/resume/resume.tex
  main parser: current file verified
  document class: article
  packages: beramono changepage charter enumitem etaremune fontawesome5 fontenc fourier-orns geometry hyperref hyphenat mathabx microtype needspace nopageno parskip pifont setspace titlesec titling xcolor xpatch
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 0
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
