### ISSUE TITLE
Vimtex compile no longer works following move from texlive-core to texlive-basic

### ISSUE THREAD

**Issue by squishram** [lervag/vimtex#2742]
### Description

Texlive has replaced their texlive-core package with texlive-basic.

Following the update to the new package, compilation no longer works, and nor does `let g:vimtex_log_ignore = [...]`. Vimtex does seem to load correctly and works in many other capacities (can still list errors, keymaps for changing/ removing environments and modifiers still work).

Running `pdflatex file.tex` and `zathura file.pdf` both still work as expected.

### Steps to reproduce

`pacman -Syu`
-> texlive-core deleted
-> texlive-basic installed

Vimtex config: (using neovim with lua config, hence why ```vim.cmd("")``` is used)

```lua
vim.cmd("filetype plugin indent on")
vim.cmd("let g:vimtex_view_method = 'zathura'")
vim.cmd("let g:vimtex_quickfix_mode = 0")
vim.cmd("let g:vimtex_context_pdf_viewer = 1")
vim.cmd("let g:vimtex_context_pdf_viewer = 'zathura'")
vim.cmd("let g:vimtex_compiler_method = 'latexmk'")
vim.cmd(
  "let g:vimtex_log_ignore = ['Underfull', 'Overfull', 'specifier changed to', 'Token not allowed in a PDF string']"
)
```

Then, in `.tex` file: `:VimtexCompile`.

### Expected behavior

`.tex` file should compile and zathura output should be produced.

### Actual behavior

Nothing happens.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
with file paths redacted:

System info:
  OS: EndeavourOS Linux
  Vim version: NVIM v0.9.1
  Has clientserver: true
  Servername: /run/user/1000/nvim.28711.0

VimTeX project: *************
  base: ***********.tex
  root: ************************************************************
  tex: ************************************************************.tex
  main parser: current file verified
  document class: article
  packages: amsbsy amsgen amsmath amsopn amstext array atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook bigintcalc bitset color enumitem environ epstopdf-base etexcmds etoolbox geometry gettitlestring graphics graphicx hycolor hyperref iftex ifvtex infwarerr inputenc intcalc keyval kvdefinekeys kvoptions kvsetkeys letltxmacro listings listingsutf8 lstmisc ltxcmds nameref pdfcol pdfescape pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfrcs pgfsys refcount rerunfilecheck shellesc stringenc tabularx tabulary tcolorbox tikz tikzfill-common tikzfill.image titlesec trig trimspaces uniquecounter url verbatim xcolor
  source files:
    ***************.tex
    *******.tex
    ********.tex
    *******.tex
    ********.tex
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
