### ISSUE TITLE
IEEEeqnarray not recognized as math environment when using `ieeecolor` class

### ISSUE THREAD

**Issue by ThomasChaffey** [lervag/vimtex#2743]
### Description

Essentially the same issue as one I raised previously: https://github.com/lervag/vimtex/issues/2675#issuecomment-1486504629

`IEEEeqnarray` is not automatically recongized as a math environment when using the `ieeecolor` class.  A workaround is adding
```
let g:vimtex_syntax_packages = {
      \ 'ieeetrantools': {'load': 2},
      \}
```
to `.vimrc`.  

`ieeecolor` replaces the older `IEEEtran` as the submission template for some IEEE journals.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 13.4 (22F66)
  Vim version: VIM 9.0 (1-1276)
  Has clientserver: true
  Servername: undefined (vim started without --servername)

VimTeX project: intrinsic
  base: intrinsic.tex
  root: /Users/tlc37/Dropbox (Cambridge University)/Rodolphe+Fulvio+Tom+Henk/TAC
  tex: /Users/tlc37/Dropbox (Cambridge University)/Rodolphe+Fulvio+Tom+Henk/TAC/intrinsic.tex
  main parser: current file verified
  document class: ieeecolor
  packages: ./TLC TLC algorithm algorithmicx algpseudocode aliasctr amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm array biblatex blox blx-case-expl3 calc circuitikz color epigraph epstopdf-base etoolbox expl3 float flushend gensymb graphics graphicx iftex ifthen infwarerr keyval kvoptions kvsetkeys l3keys2e logreq ltxcmds mathtools mhsetup nextpage parseargs pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfplots pgfrcs pgfsys shellesc siunitx thm-amsthm thm-autoref thm-kv thm-listof thm-patch thm-restate thmtools tikz translations trig url xcolor xparse
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Skim
  qf method: LaTeX logfile
```
