### ISSUE TITLE
VimtexClean dosen't work with aux folder and input files

### ISSUE THREAD

**Issue by AndreaDiPietro92** [lervag/vimtex#2746]
### Description

Using the latexmk `out` and `aux` folder the `\lc` or `\lC` dosen't work.
The `latexmk -c`  or `latexmk -C`  works perfectly.

### Steps to reproduce

1. Create a folder with a minimal `main.tex`
2. Create a folder `source` with a `cap1.tex`
3. Insert in `main.tex` the `\input{source/cap1.tex}`
4. Create a `.latexmkrc`. Mine is
```
$pdflatex = 'pdflatex -synctex=1 -interaction=nonstopmode';
$out_dir = 'out';
$aux_dir = 'aux';
$pdf_previewer = 'start zathura';
$pdf_mode = 1;   
$bibtex_use = 2;
@default_files = ('test.tex');

@generated_exts = qw(aux idx ind lof lot out toc acn acr alg glg glo gls ist);
$clean_ext = "toc log mtc* maf aux bak bbl sav xml fls soc loc";

# Run latexmk silently, not output to text
$silent     = $ENV{'SILENT'};
$quiet      = $ENV{'SILENT'};
```
5. Compile the `main.tex`
6. Use the `\lc` command.

### Expected behavior

All the files in `aux` folder should desappear 

### Actual behavior

Nothing happens.

### Do you use a latexmkrc file?

Yes

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 23.04
  Vim version: NVIM v0.10.0-dev-510+g3c4890d1e
  Has clientserver: true
  Servername: /run/user/1000/nvim.128782.0

VimTeX project: test
  base: test.tex
  root: /home/user/temp_latex
  tex: /home/user/temp_latex/test.tex
  main parser: current file verified
  document class: report
  packages: amsmath booktabs cleveref csquotes fancyhdr float fontsetup fontspec graphicx hyperref listings longtable mdframed mhchem microtype minitoc multirow pdfpages pgf pgfplots polyglossia siunitx subcaption tabularray tcolorbox tikz varioref
  source files:
    test.tex
    source/cap1.tex
  compiler: latexmk
    engine: -pdflatex
    options:
      -verbose
      -synctex=1
      -interaction=nonstopmode
    out_dir: out
    aux_dir: aux
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
