### ISSUE TITLE
forward search sumatra pdf windows doesn't work

### ISSUE THREAD

**Issue by 777uliahshafar** [lervag/vimtex#2747]
### Description

I understand forward search need additional configuration to make it work, but I have searched through internet its prerequisite and I could not find any configuration worked in windows 11 using neovim. Some of them are old issues, I could not tell which has been implemented on vimtex system related to sumatra pdf on windows 11. 

I move to windows from wsl2, after opening issue of the zathura pdf opening yesterday. Now, I have encountered problem of forward search on sumatraPDF in _windows 11_ using _neovim_. The compilation of latex documents is working, but it can't highlight the text.  I also wanted to point out the inverse search doesn't work with the configuration I set up.

I have set up the vimtex requirement. I have read faq-windows, installingperl strawberry, 
I use Powershell not built-in windows powershell.

On inverse search I have read [this blog](https://jdhao.github.io/2021/02/20/inverse_search_setup_neovim_vimtex/) but it won't work, only show a glimpse of windows. Thank you very much everyone, 

### Steps to reproduce

minimal.lua
```
vim.cmd[[filetype plugin indent on
syntax enable]]

vim.g.vimtex_compiler_latexmk_engines = {
    _ = '-lualatex'
}

vim.g.vimtex_compiler_method = "latexmk"
vim.g.vimtex_compiler_latexmk = {
    options = {
        "-shell-escape",
        "-verbose",
        "-file-line-error",
        "-synctex=1",
        "-interaction=nonstopmode",
    },
}

-- configuration is used by default on Windows if SumatraPDF is detected as executable.
--vim.g.vimtex_view_method = 'SumatraPDF'
--vim.g.vimtex_view_general_options = "-forward-search @tex @line @pdf"

" Add relevant options and VimTeX configuration below.

```
minimal.tex
```
\documentclass{minimal}
\begin{document}
Hello world!

\pagebreak

Hello world!
\end{document}
```

### Expected behavior

The sumatraPDF can't do forward search on windows 11 using neovim

### Actual behavior

The sumatra only open after compilation with the last view page.

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
System info:
  OS: DESKTOP-RMKJQL5 (Microsoft Windows 11 Home Single Language)
  Vim version: NVIM v0.9.1
  Has clientserver: true
  Servername: \\.\pipe\nvim.12124.0

VimTeX project: simart
  base: simart.tex
  root: C:\Users\ul\Documents\simart
  tex: C:\Users\ul\Documents\simart\simart.tex
  main parser: current file verified
  document class: simart
  packages: arabicnumbers array atbegshi-ltx atveryend-ltx auxhook bigintcalc bitset booktabs calc caption caption3 ctablestack enumitem epstopdf-base etoolbox expl3 fancyhdr fontenc fontspec fontspec-luatex geometry gettitlestring graphics graphicx hijrical hycolor hyperref iftex ifvtex import infwarerr intcalc kvdefinekeys kvoptions kvsetkeys l3keys2e letltxmacro lipsum listings lstmisc ltxcmds luatexbase makecmds nameref natbib paralist pdfescape pdftexcmds polyglossia refcount rerunfilecheck setspace stringenc subfiles tabularx titlesec trig uniquecounter url xkeyval xparse
  source files:
    simart.tex
    subfiles/subfile.tex
  compiler: latexmk
    engine: -lualatex
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 6
      output: C:\Users\ul\AppData\Local\Temp\nvim.0\yRMEUe\0
      cmd: set max_print_line=2000 & latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -lualatex -pvc -view=none -e "$compiling_cmd = ($compiling_cmd ? $compiling_cmd . ' ^& ' : '') . 'echo vimtex_compiler_callback_compiling'" -e "$success_cmd = ($success_cmd ? $success_cmd . ' ^& ' : '') . 'echo vimtex_compiler_callback_success'" -e "$failure_cmd = ($failure_cmd ? $failure_cmd . ' ^& ' : '') . 'echo vimtex_compiler_callback_failure'" "simart.tex"
      pid: 6344
  viewer: General
    job: 
      pid: -
      cmd: start "" "C:\Users\ul\Documents\simart/simart.pdf"
  qf method: LaTeX logfile
```
