### ISSUE TITLE
Not getting citation preview

### ISSUE THREAD

**Issue by PMassicotte** [lervag/vimtex#2749]
### Description

First, thank you for the great plugin. The problem I am facing is that whereas citation autocomplete is working, I am not getting a preview of the citations.

![image](https://github.com/lervag/vimtex/assets/4519221/65678fb8-7950-4021-b5f0-ec1d996e3ba8)

Here is my configuration file:

```lua
{
    'lervag/vimtex',
    dependencies = {
      'hrsh7th/cmp-omni',
    },
    init = function()
      -- PDF Viewer:
      -- http://manpages.ubuntu.com/manpages/trusty/man5/zathurarc.5.html
      vim.g.vimtex_view_method = 'zathura'
      vim.g.vimtex_quickfix_mode = 0
      -- Ignore mappings
      vim.g.vimtex_mappings_enabled = 1
      -- Auto Indent
      vim.g.vimtex_indent_enabled = 1
      -- Syntax highlighting
      vim.g.vimtex_syntax_enabled = 1
      -- Complete bib view
      vim.g.vimtex_complete_bib = {
        simple = 0,
        menu_fmt = "@year, @author_short, @title",
      }
      -- Error suppression:
      -- https://github.com/lervag/vimtex/blob/master/doc/vimtex.txt
      vim.g.vimtex_log_ignore = {
        'Underfull',
        'Overfull',
        'specifier changed to',
        'Token not allowed in a PDF string',
      }
      vim.g.vimtex_context_pdf_viewer = 'okular'
      require('cmp').setup {
        sources = {
          {
            name = 'omni',
            option = {
              disable_omnifuncs = { 'v:lua.vim.lsp.omnifunc' }
            }
          }
        }
      }
    end
  },
```

Any ideas on what I am missing out?

Thank you,
Phil

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 23.04
  Vim version: NVIM v0.10.0-dev
  Has clientserver: true
  Servername: /run/user/1000/nvim.402608.0

VimTeX project: template
  base: template.tex
  root: /media/work/latex_templates
  tex: /media/work/latex_templates/template.tex
  main parser: current file verified
  document class: scrartcl
  packages: array atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook biblatex bigintcalc bitset blx-case-expl3 bookmark color colortbl enumitem epstopdf-base etexcmds etoolbox expl3 fontaxes fontenc footmisc geometry gettitlestring graphics graphicx hycolor hyperref ifluatex iftex ifthen ifvtex ifxetex infwarerr intcalc keyval kvdefinekeys kvoptions kvsetkeys letltxmacro logreq ltxcmds nameref opensans pdfescape pdftexcmds refcount rerunfilecheck scrbase scrkbase scrlfile scrlfile-hook scrlogo tocbasic trig typearea uniquecounter url xcolor xkeyval xparse
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 15
      output: /tmp/nvim.filoche/otmnME/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'template.tex'
      pid: 402750
  viewer: Zathura
    xwin id: 0
    cmd_start: zathura  -x "/usr/bin/nvim --headless -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 70:42:'/media/work/latex_templates/template.tex' 'template.pdf'&
  qf method: LaTeX logfile
```
