### ISSUE TITLE
fontspec creating compilation in neovim but not in regular terminal

### ISSUE THREAD

**Issue by Khyta** [lervag/vimtex#2750]
### Description

I have a custom font I want to use for my documents. I use latexmk with the XeLaTex option like this in my `lua.init` config. The base config for `lua.init` is from [kickstart.nvim](https://github.com/nvim-lua/kickstart.nvim). I put this here at the very bottom of the `lua.init` file.

    vim.g.vimtex_compiler_latexmk = {
    executable = 'latexmk',
    options = {
    '-xelatex',
    '-synctex=1',
    '-interaction=nonstopmode',
    '-shell-escape',
        }
    }

My vimtex plugin also apparently sees the correct config changes

    System info:
    OS: Ubuntu 22.04.2 LTS
    Vim version: NVIM v0.10.0-dev
    Has clientserver: true
    Servername: /run/user/1000/nvim.858933.0

    VimTeX project: letter
      base: letter.tex
      root: /home/khyta/Desktop/Company/LaTex_templates/letter
      tex: /home/khyta/Desktop/Company/LaTex_templates/letter/letter.tex
      main parser: current file verified
      document class: letter
      packages: babel caption expl3 float fontspec geometry graphicx iftex ifvtex inputenc keyval microtype setspace xparse
      compiler: latexmk
        engine: -pdf
        options:
          -xelatex
          -synctex=1
          -interaction=nonstopmode
          -shell-escape
        callback: 1
        continuous: 1
        executable: latexmk
      viewer: General
      qf method: LaTeX logfile

Yet when I want to compile with `<leader>ll`, it says `VimTex: Compilation failed!`. It is definitely related to the usage of `\usepackacge{fontspec}` because when I comment that line out in my document, it compiles successfully.

What is even stranger is that it compiles successfully *with* the usage of `\usepackacge{fontspec}` and the custom font in the terminal when I type in this command here:

    latexmk -pdf -xelatex -synctex=1 -interaction=nonstopmode -shell-escape letter.tex

I'm at loss. I just want the compilation with the custom font to work directly in neovim.

### Steps to reproduce

0. Unzip the `minimal.zip` file.
1. `nvim -u minimal.lua minimal.tex`  
2. Compile with `\ll`
3. See that it fails to compile

[minimal.zip](https://github.com/lervag/vimtex/files/11951109/minimal.zip)

### Expected behavior

I expect it to compile successfully so that I can use a custom font with XeLaTex in my Document.

### Actual behavior

I observe that the document fails to compile correctly. It only compiles when removing the line `\usepackage{fontspec}` 

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 22.04.2 LTS
  Vim version: NVIM v0.10.0-dev
  Has clientserver: true
  Servername: /run/user/1000/nvim.867782.0

VimTeX project: minimal
  base: minimal.tex
  root: /home/khyta/minimal
  tex: /home/khyta/minimal/minimal.tex
  main parser: current file verified
  document class: paper
  packages: expl3 fontspec xparse
  compiler: latexmk
    engine: -pdf
    options:
      -xelatex
      -synctex=1
      -interaction=nonstopmode
      -shell-escape
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 10
      output: /tmp/nvim.khyta/ZbZqPH/0
      cmd: max_print_line=2000 latexmk -xelatex -synctex=1 -interaction=nonstopmode -shell-escape -pdf -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'minimal.tex'
      pid: 867920
  viewer: General
    job: 
      pid: -
      cmd: xdg-open '/home/khyta/minimal/minimal.pdf'
  qf method: LaTeX logfile
```
