### ISSUE TITLE
Unexpected behaviour conceal command with custom delims with argument not delimited by `{}` 

### ISSUE THREAD

**Issue by sandersantema** [lervag/vimtex#2751]
### Description

This is somewhat in between a feature request and a bug report as the feature which I want currently works partially but I think it should either not work at all or fully. I hope I didn't forget anything here, if so I'll be happy to provide more info. Thanks a lot for this essential plugin!

### Steps to reproduce

1. Declare custom command with concealed delimiters (including minimal config):
for neovim: 
```vimscript
let &runtimepath  = '/home/sandersantema/.local/share/nvim/site/pack/packer/opt/vimtex,' . &runtimepath
let g:vimtex_syntax_custom_cmds_with_concealed_delims = [
      \ {'name': 'semantics',
      \  'mathmode': 1,
      \  'cmdre': 'semantics\s*',
      \  'cchar_open':  '〚',
      \  'cchar_close':  '〛'},
      \]

set conceallevel=2
```
or for vim:
```vimscript
set nocompatible
let &runtimepath  = '/home/sandersantema/.local/share/nvim/site/pack/packer/opt/vimtex,' . &runtimepath
filetype plugin indent on
syntax enable

let g:vimtex_syntax_custom_cmds_with_concealed_delims = [
      \ {'name': 'semantics',
      \  'mathmode': 1,
      \  'cmdre': 'semantics\s*',
      \  'cchar_open':  '〚',
      \  'cchar_close':  '〛'},
      \]

set conceallevel=2
```
I could reproduce for both vim and neovim.
3. Put in the following:
```tex
\semantics foo:   \(\semantics foo\)
\semantics {foo}: \(\semantics {foo}\)
```

### Expected behavior

The second line is as expected, the first should either also show a `〛` or not conceal at all. I'd prefer the latter, which would be a feature request.

### Actual behavior

The results of step 2 is the following:
![image](https://github.com/lervag/vimtex/assets/21057514/d1575980-cb1a-4450-a1ec-4219e9a98c6f)

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: openSUSE Tumbleweed
  Vim version: NVIM v0.10.0-dev-627+gcf5f1492d
  Has clientserver: true
  Servername: /run/user/1000/nvim.29508.0

VimTeX project: tex_test
  base: tex_test.tex
  root: /home/sandersantema/.config/nvim/debug
  tex: /home/sandersantema/.config/nvim/debug/tex_test.tex
  main parser: fallback current file
  document class: 
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
