### ISSUE TITLE
Nested itemize indent behavior

### ISSUE THREAD

**Issue by a-torgovitsky** [lervag/vimtex#2758]
### Description

`testing.tex`:
```tex
\documentclass{minimal}
\begin{document}
  \begin{itemize}
    \item a
    \begin{itemize}
      \item b
    \end{itemize}
  \end{itemize}
\end{document}
```
I put my cursor at the end of the second-to-last `\end{itemize}` (line 7).
`o` in normal mode, places me on a new line aligned with `\end{itemize}`.
If I type `\item<Space>` in insert mode, some sort of autoindent pushes it back to be completely unindented.

### Steps to reproduce

`init-test.vim`:
```vim
call plug#begin()
Plug 'lervag/vimtex'
call plug#end()
filetype plugin indent on
syntax enable
```

Then
```bash
nvim -u init-test.vim testing.tex
```

### Expected behavior

I expect that `\item` should not be auto-indented.

### Do you use a latexmkrc file?

Yes, but doesn't seem relevant

### VimtexInfo

```yaml
System info:
  OS: Linux Mint 20.2
  Vim version: NVIM v0.9.0
  Has clientserver: true
  Servername: /run/user/1000/nvim.732749.0

VimTeX project: testing
  base: testing.tex
  root: [redacted]
  tex: [redacted]/testing.tex
  main parser: current file verified
  document class: minimal
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
