### ISSUE TITLE
Compiler is not stopped on \lx (plugin reload)

### ISSUE THREAD

**Issue by user202729** [lervag/vimtex#2760]
### Description

Title.

### Steps to reproduce

1. Press `\ll` to start latexmk.
2. Press `\lx` to reload plugin. Check process manager/htop, latexmk is still running.
3. Press `\ll`. Another latexmk process will be started.

### Do you use a latexmkrc file?

Yes

### VimtexInfo

```yaml
System info:
  OS: Arch Linux
  Vim version: VIM 9.0 (1-1628)
  Has clientserver: true
  Servername: vim1
```
