### ISSUE TITLE
i am facing the error while opening latex fiels in vimtex

### ISSUE THREAD

**Issue by Aneeqasif** [lervag/vimtex#2763]
### Description

![image](https://github.com/lervag/vimtex/assets/78728701/d0acca2a-5813-4211-b444-de6466a51d07)

latexmkrc
```
# $pdflatex = 'pdflatex -synctex=1 %O %S';

$latex = 'latex -synctex=1 %O  --shell-escape %S';
$pdflatex = 'pdflatex -synctex=1 -interaction=nonstopmode %O  --shell-escape %S';

```

### Steps to reproduce

```lua
-- Disable imaps (using Ultisnips)
-- vim.g.vimtex_imaps_enabled = 0
-- Do not open pdfviwer on compile
-- vim.g.vimtex_view_automatic = 0
-- Disable conceal
vim.g.vimtex_syntax_conceal = {
    accents = 1,
    cites = 1,
    fancy = 1,
    greek = 1,
    math_bounds = 1,
    math_delimiters = 1,
    math_fracs = 1,
    math_super_sub = 1,
    math_symbols = 1,
    sections = 1,
    styles = 1,
}
vim.api.nvim_command('set conceallevel=2')

-- PDF viewer settings
-- for zathura
-- vim.g.vimtex_view_general_viewer = "zathura"
-- vim.g.vimtex_view_method = "zathura"
-- vim.g['vimtex_context_pdf_viewer'] = 'zathura'

--  for okular

vim.g['vimtex_context_pdf_viewer'] = 'okular'
vim.g.vimtex_view_general_viewer = "okular"
vim.cmd([[

    let g:vimtex_view_general_options = '--unique file:@pdf\#src:@line@tex'
    " let g:vimtex_view_general_options_latexmk = '--unique' 
]])




vim.g.tex_conceal= "abdmg"

vim.cmd([[


let g:vimtex_mappings_prefix = '<localleader>v'
let g:vimtex_imaps_leader = "`"


" let g:vimtex_grammar_textidote = {
"       \ 'jar': '/usr/share/java/textidote.jar',
"       \ 'args': '',
"       \}

set spelllang=en_gb


" let g:vimtex_grammar_vlty = {
"       \ 'lt_directory': '/usr/bin/',
"       \ 'lt_command': 'languagetool',
"       \ 'lt_disable': 'WHITESPACE_RULE',
"       \ 'lt_enable': '',
"       \ 'lt_disablecategories': '',
"       \ 'lt_enablecategories': '',
"       \ 'server': 'my',
"       \ 'shell_options': '',
"       \ 'show_suggestions': 1,
"       \ 'encoding': 'auto',
"       \}



" let g:livepreview_engine = 'latexmk' . ' ["-shell-escape"]' 
let g:vimtex_complete_enabled = 1
" let g:vimtex_compiler_progname = 'nvr'
" let g:vimtex_compiler_latexmk.options += ['-shell-escape']
" Silent all messages
" let g:vimtex_compiler_silent=1

let g:vimtex_toc_config = {
    \'split_width':  30,
    \'show_help':  0,
    \'layer_status' : { 
        \'content': 1,
        \'label': 0,
        \'todo': 1,
        \'include': 0 
    \ }
    \}

let g:vimtex_log_ignore = [
      \ 'Underfull \\hbox',
      \ 'Overfull \\hbox',
      \ 'LaTeX Warning: .\+ float specifier changed to',
      \ 'LaTeX hooks Warning',
      \ 'Package siunitx Warning: Detected the "physics" package:',
      \ 'Package hyperref Warning: Token not allowed in a PDF string',
      \ 'Compilation completed',
      \]

" let g:vimtex_compiler_latexmk = {
"     \ 'options' : [
"     \   '-shell-escape',
"     \   '-verbose',
"     \   '-file-line-error',
"     \   '-synctex=1',
"     \   '-interaction=nonstopmode',
"     \ ],
"     \}

" let vim.g.vimtex_compile_latexmk_engines = {
"   ['_'] = '-xelatex',
" }

]])


-- Disable quickfix auto open
vim.g.vimtex_quickfix_ignore_mode = 0

-- vim.g.vimtex_view_general_options = "-reuse-instance -forward-search @tex @line @pdf"
-- Do not auto open quickfix on compile erros
vim.g.vimtex_quickfix_mode = 0



vim.g.vimtex_fold_enabled = 1
vim.g.vimtex_fold_manual = 1




```

### Actual behavior

whenever it try to open a file it just through error. the plugin keybindings and commandly only work if the file is main.tex. otherwise it throues some autocmd error.

### Do you use a latexmkrc file?

yes

### VimtexInfo

```yaml
System info:
  OS: ArcoLinux
  Vim version: NVIM v0.9.1
  Has clientserver: true
  Servername: /run/user/1000/lvim.253396.0

VimTeX project: main
  base: main.tex
  root: /home/aneeq/Documents/FYP/latex/thesis-bs
  tex: /home/aneeq/Documents/FYP/latex/thesis-bs/main.tex
  main parser: current file verified
  document class: report
  packages: amsbsy amsfonts amsgen amsmath amsopn amssymb amstext babel blindtext caption caption3 cite color epsfig etoolbox fancyhdr float geometry graphics graphicx hyperref inputenc keyval lmodern mathdots pdftexcmds setspace siunitx subcaption translations trig url wrapfig xcolor
  source files:
    main.tex
    TP1.tex
    blankpage.tex
    submission approval.tex
    TP2.tex
    dedications.tex
    Abstract.tex
    Chapter 1.tex
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
