### ISSUE TITLE
auto-complete with cmp do not work untill i do :vimtexreload

### ISSUE THREAD

**Issue by Aneeqasif** [lervag/vimtex#2765]
### Description

i have tried https://github.com/benbrastmckie latex set up using lazyman and it works really fine with same latex project but when  i open my own lunarvim config it do not work (i cannot get \cite{} completions) untill i do  `:vimtexreload`, i have added the omni source to cmp.

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
System info:
  OS: ArcoLinux
  Vim version: NVIM v0.9.1
  Has clientserver: true
  Servername: /run/user/1000/lvim.46263.0

VimTeX project: main
  base: main.tex
  root: /home/aneeq/Documents/FYP/latex/thesis-bs
  tex: /home/aneeq/Documents/FYP/latex/thesis-bs/main.tex
  main parser: recursive search
  document class: report
  packages: amsbsy amsfonts amsgen amsmath amsopn amssymb amstext array atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook babel bigintcalc bitset blindtext caption caption3 catchfile cite color colortbl epsfig epstopdf-base etexcmds etoolbox fancyhdr float geometry gettitlestring graphics graphicx hycolor hyperref ifluatex ifplatform iftex ifvtex infwarerr inputenc intcalc keyval kvdefinekeys kvoptions kvsetkeys letltxmacro lmodern ltxcmds mathdots nameref pdfescape pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfrcs pgfsys refcount rerunfilecheck scrbase scrlfile scrlfile-hook scrlogo setspace shellesc siunitx subcaption svg tikz translations transparent transparent-nometadata trig trimspaces uniquecounter url wrapfig xcolor xspace
  source files:
    main.tex
    TP1.tex
    blankpage.tex
    submission approval.tex
    TP2.tex
    dedications.tex
    Abstract.tex
    Chapter 1.tex
    Chapter 2.tex
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
this might be related https://github.com/LunarVim/LunarVim/issues/3723
