### ISSUE TITLE
VimTex: Viewer cannot find zathura window id

### ISSUE THREAD

**Issue by DockterTeagle** [lervag/vimtex#2767]
### Description

When running VimtexCompile I get greeted with the following

![Screenshot 2023-08-07 210843](https://github.com/lervag/vimtex/assets/65212972/d822c663-0c14-4719-9633-1622736ff94f)
I am running wsl version 2 and `uname -a` returns:

```
Linux CHRISTHINK 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### Steps to reproduce

This is my `tex.vim` in `/usr/share/nvim/runtime/plugin`

```vim
" let g:vimtex_imaps_enabled = 0
let g:vimtex_view_method= 'zathura'
let g:vimtex_delim_toggle_mod_list = [
  \ ['\left', '\right'],
  \ ['\big', '\big'],
  \]
let g:vimtex_quickfix_open_on_warning = 0
let g:vimtex_compiler_latexmk = {
    \ 'options' : [
    \   '-verbose',
    \   '-file-line-error',
    \   '-synctex=1',
    \   '-interaction=nonstopmode',
    \   '-shell-escape',
    \ ],
    \}
```

and this is my `~/.config/latexmk/latexmkrc` file:

```perl
$pdflatex = "pdflatex -file-line-error -halt-on-error -interaction=nonstopmode -synctex=1 -shell-escape";
```

I ran neovim and tried to compile the following file:

```tex
\documentclass{article}
\usepackage{minted}
\begin{document}

Lorem ipsum dolor sit amet, officia excepteur ex fugiat reprehenderit enim labore culpa sint ad nisi Lorem pariatur mollit ex esse exercitation amet. Nisi anim cupidatat excepteur officia. Reprehenderit nostrud nostrud ipsum Lorem est aliquip amet voluptate voluptate dolor minim nulla est proident. Nostrud officia pariatur ut officia. Sit irure elit esse ea nulla sunt ex occaecat reprehenderit commodo officia dolor Lorem duis laboris cupidatat officia voluptate. Culpa proident adipisicing id nulla nisi laboris ex in Lorem sunt duis officia eiusmod. Aliqua reprehenderit commodo ex non excepteur duis sunt velit enim. Voluptate laboris sint cupidatat ullamco ut ea consectetur et est culpa et culpa duis.
\end{document}
```

### Expected behavior

to be able to compile the document and view it in zathura

### Actual behavior

I observe the following

![Screenshot 2023-08-07 210843](https://github.com/lervag/vimtex/assets/65212972/b02a3e32-18a9-4849-8485-c253059ad5f6)

### Do you use a latexmkrc file?

yes

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 22.04.3 LTS
  Vim version: NVIM v0.10.0-dev
  Has clientserver: true
  Servername: /run/user/1000//nvim.1424.0

VimTeX project: hello
  base: hello.tex
  root: /home/chris
  tex: /home/chris/hello.tex
  main parser: current file verified
  document class: article
  packages: calc catchfile etexcmds etoolbox fancyvrb float framed fvextra ifluatex ifplatform iftex ifthen infwarerr keyval kvoptions kvsetkeys lineno ltxcmds minted pdftexcmds shellesc textcomp upquote xcolor xstring
  compiler: latexmk
    engine: -xelatex
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
      -shell-escape
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
