### ISSUE TITLE
build_dir not working

### ISSUE THREAD

**Issue by AgarwalSaurav** [lervag/vimtex#2778]
### Description

I am not able to get build_dir to work. It used to work previously. Maybe there has been an update that is causing this issue.

latexmk version: 4.79
pdflaex version: pdfTeX 3.141592653-2.6-1.40.25 (TeX Live 2023/Arch Linux)

```vim
set nocompatible
let &runtimepath  = '~/.vim/bundle/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable
" Add relevant options and VimTeX configuration below.
"
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'lervag/vimtex'
call vundle#end()            " required

" Enable syntax and plugins
syntax enable
filetype plugin indent on

let g:vimtex_view_method = 'zathura'
let g:vimtex_fold_enabled=1

let g:vimtex_compiler_latexmk = {'build_dir' : './build',}

```

```tex
\documentclass{article}
\begin{document}
Minimal document.
\end{document}
```

### Steps to reproduce

1. `vim -u minimal.vim minimal.tex`

### Expected behavior

A `build` subdirectory should have been created with the build files in it.

### Actual behavior

No `build` directory is created. The build files are placed in the same directory.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Arch Linux
  Vim version: VIM 9.0 (1-1736)
  Has clientserver: true
  Servername: undefined (vim started without --servername)

VimTeX project: minimal
  base: minimal.tex
  root: /data/Documents/dumps/vimtex
  tex: /data/Documents/dumps/vimtex/minimal.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
