### ISSUE TITLE
Vimtex Inverse Search not working (again)

### ISSUE THREAD

**Issue by Xydru** [lervag/vimtex#2779]
### Description

Hello, basically this can be seen as a continuation of my previous issue, so I'm gonna leave out the introduction:
https://github.com/lervag/vimtex/issues/2692

After a while and some small additions I made to neovim I noticed that the Inverse Search stopped working again (for any kind of .tex file and any kind of filepath for that file).
I will just try to provide as much information as possible that might be helpful to find the problem:

My Skim settings:
<img width="559" alt="image" src="https://github.com/lervag/vimtex/assets/59253224/67feed21-d3f6-4939-8ea7-5f38807bb492">

My init.vim:
```vim
call plug#begin()
if has('nvim')
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
  Plug 'Shougo/deoplete.nvim'
  Plug 'roxma/nvim-yarp'
  Plug 'roxma/vim-hug-neovim-rpc'
endif
let g:deoplete#enable_at_startup = 1

Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets' " Necessary for Ultisnips
Plug 'lervag/vimtex'
Plug 'ludovicchabant/vim-gutentags'
Plug 'neomake/neomake'
Plug 'folke/tokyonight.nvim', { 'branch': 'main' }
Plug 'jiangmiao/auto-pairs'
Plug 'jdhao/better-escape.vim'
call plug#end()

colorscheme tokyonight
set number
set relativenumber

imap <C-S> <ESC>:w<CR>a
map <C-S> :w<CR>
imap <C-F> <ESC>\lva
map <C-F> <ESC>\lv

filetype plugin indent on
set tabstop=4
set shiftwidth=4
set expandtab

let g:vimtex_view_method = "skim"
let g:vimtex_view_skim_sync = 1
let g:vimtex_view_skim_activate = 1

call neomake#configure#automake('w')
call neomake#configure#automake('nw', 750)
call neomake#configure#automake('rw', 1000)
call neomake#configure#automake('nrwi', 500)

call deoplete#custom#var('omni', 'input_patterns', {
      \ 'tex': g:vimtex#re#deoplete
      \})

let g:UltiSnipsExpandTrigger='<tab>'
let g:UltiSnipsJumpForwardTrigger='<tab>'
let g:UltiSnipsJumpBackwardTrigger='<s-tab>'
```

When I type a command like `nvim --headless -c "VimtexInverseSearch 10 test.tex"` into my terminal it works and does what I expect it to do (going to line 10 in test.tex).
When I put a command like `echo test789 > ~/test789.txt` into Skim (which means I set Befehl=`echo` and Argumente=`test789 > ~/test789.txt`) it works as exactly as expected and creates a file at `~/` named `test789.txt` that contains `test789`.
Furthermore, when I put the command `echo "--headless -c \"VimtexInverseSearch %line '%file'\"" > ~/test789.txt` into Skim it also works exactly as expected and creates a file at `~/` named `test789.txt` that contains `--headless -c "VimtexInverseSearch 64 '/Users/felix/test/test.tex'"` (the file I performed InverseSearch on was `test.tex` which is located at `/Users/felix/test/test.tex` and the line I clicked on was indeed 64 in the tex file).
But now comes the interesting part: if I put the command `nvim --headless -c "VimtexInverseSearch 64 '/Users/felix/test/test.tex'"` into Skim, it doesn't do anything while when I put it into the Terminal it does exactly what it should (moving the cursor to line 64 in text.tex)!

To me it feels like this probably isn't an issue with VimTeX but rather with Skim, but I think it also could have something to do with the way the InverseSearch command is implemented, so I'm going to post this issue here for now.

### Steps to reproduce

1. `nvim test.tex`
2. compiling with `:VimtexCompile`
3. `<cmd><shift><left-click>` on an arbitrary word in the pdf document in Skim (opened by Vimtex)

### Expected behavior

The pointer in nvim moves to the corresponding line

### Actual behavior

Nothing happens

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 13.2.1 (22D68)
  Vim version: NVIM v0.9.0
  Has clientserver: true
  Servername: /var/folders/pc/lxy6kdgs4j7c3hdgntkkf0jh0000gn/T/nvim.felix/amN0XM/nvim.34823.0

VimTeX project: test
  base: test.tex
  root: /Users/felix/test
  tex: /Users/felix/test/test.tex
  main parser: current file verified
  document class: article
  packages: algorithm algorithmicx algpseudocode amsbsy amsfonts amsgen amsmath amsopn amssymb amstext babel float ifthen inputenc
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 11
      output: /var/folders/pc/lxy6kdgs4j7c3hdgntkkf0jh0000gn/T/nvim.felix/amN0XM/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'test.tex'
      pid: 34833
  viewer: Skim
  qf method: LaTeX logfile
```
