### ISSUE TITLE
Syntax error using neovim

### ISSUE THREAD

**Issue by stefankiebacher** [lervag/vimtex#2781]
### Description

I get the following error when opening a `*.tex` file 
```
Error detected while processing function vimtex#syntax#core#init_post[12]..vimtex#syntax#packages#init[14]..vimtex#
syntax#p#amsmath#load:
line   10:
E121: Undefined variable: #
E116: Invalid arguments for function vimtex#syntax#core#new_env
```

### Steps to reproduce

Tried using `nvim -u minimal.vim minimal.tex`, which works.
Tried using `nvim -u test.vim minimal.tex`, which works.
Tried using `nvim -u test.vim main.tex`, getting the above error
with 
`test.vim`:
```
" Specify a directory for plugins
call plug#begin('~/.config/nvim/plugged')
Plug 'lervag/vimtex'
call plug#end()

let g:python3_host_prog = "/usr/bin/python3"
let g:python_host_prog = "/usr/bin/python2.7"

"LATEX
" This is necessary for VimTeX to load properly. The "indent" is optional.
" Note that most plugin managers will do this automatically.
filetype plugin indent on

" This enables Vim's and neovim's syntax-related features. Without this, some
" VimTeX features will not work (see ":help vimtex-requirements" for more
" info).
syntax enable

" Viewer options: One may configure the viewer either by specifying a built-in
" viewer method:
"let g:vimtex_view_method = 'zathura'
"let g:vimtex_view_method = ''
let g:vimtex_quickfix_enabled = 1

" Or with a generic interface:
let g:vimtex_view_general_viewer = 'okular'
let g:vimtex_view_general_options = '--unique file:@pdf\#src:@line@tex'

" VimTeX uses latexmk as the default compiler backend. If you use it, which is
" strongly recommended, you probably don't need to configure anything. If you
" want another compiler backend, you can change it as follows. The list of
" supported backends and further explanation is provided in the documentation,
" see ":help vimtex-compiler".
"let g:vimtex_compiler_method = '~/build_from_src/latexrun/latexrun'
"let g:vimtex_compiler_method = '/usr/bin/pdflatex'
let g:vimtex_compiler_method = 'latexmk'
let g:vimtex_compiler_latexmk = {
			\ 'build_dir' : '',
			\ 'callback' : 1,
			\ 'continuous' : 0,
			\ 'executable' : 'latexmk',
			\ 'hooks' : [],
			\ 'options' : [
			\   '-verbose',
			\	'-pdf',
			\   '-file-line-error',
			\   '-synctex=1',
			\   '-interaction=nonstopmode',
			\ ],
			\}
let g:vimtex_parser_bib_backend = 'bibtex'
let g:vimtex_fold_bib_enable = 1
let g:Tex_DefaultTargetFormat='pdf'
let g:Tex_MultipleCompileFormats='pdf,bibtex,pdf'
let g:vimtex_compiler_latexmk_engines = {
			\ '_'                : '-pdf',
			\ 'pdfdvi'           : '-pdfdvi',
			\ 'pdfps'            : '-pdfps',
			\ 'pdflatex'         : '-pdf',
			\ 'luatex'           : '-lualatex',
			\ 'lualatex'         : '-lualatex',
			\ 'xelatex'          : '-xelatex',
			\ 'context (pdftex)' : '-pdf -pdflatex=texexec',
			\ 'context (luatex)' : '-pdf -pdflatex=context',
			\ 'context (xetex)'  : '-pdf -pdflatex=''texexec --xtx''',
			\}
" Most VimTeX mappings rely on localleader and this can be changed with the
" following line. The default is usually fine and is the symbol "\".
let maplocalleader = ","
map <f5> :w<cr>,ll

```

### Expected behavior

No error message

### Actual behavior

above error message

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
For using `nvim -u test.vim main.tex` running `:VimtexInfo` I get the following:

System info:
  OS: openSUSE Leap 15.4
  Vim version: NVIM v0.4.4
  Has clientserver: true
  Servername: /tmp/nvimQrFWWC/0

VimTeX project: fission
  base: fission.tex
  root: /users/tp/kiebacher/Documents/physik/phd/Projects/BetterClusters/paper
  tex: /users/tp/kiebacher/Documents/physik/phd/Projects/BetterClusters/paper/fission.tex
  main parser: current file verified
  document class: svjour
  packages: algorithm algorithmic amsbsy amsfonts amsgen amsmath amsopn amssymb amstext atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook bigintcalc bitset caption caption3 cite color epstopdf-base etexcmds float gettitlestring graphics graphicx hycolor hyperref iftex ifthen infwarerr inputenc intcalc keyval kvdefinekeys kvoptions kvsetkeys letltxmacro ltxcmds multirow nameref pdfescape pdftexcmds refcount rerunfilecheck snapshot subcaption trig uniquecounter url
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -pdf
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 0
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
```
