### ISSUE TITLE
Environment text object doesn't work with optional parameters delimited by non-[ or { characters

### ISSUE THREAD

**Issue by Nora-n** [lervag/vimtex#2782]
### Description

I have created a `NewDocumentEnvironment` using optional parameters delimited by, *in order*, `[]`, `()`, `<>`, `""` and `''` before a *mandatory* argument in `{}`. When using `vie`, selected text starts after `\begin{}[]`. I was expecting the selected text to start after the last `}`, "on the line below".

I sought the closed issues and found both #410 and #2160, more precisely [here](https://github.com/lervag/vimtex/issues/2160#issuecomment-913148198_); from what I understand, it might not be easy to parse things between these delimiters, though I put my optional parameters in that order to mimick the usual `[option1]{option2}` of an environment in the hope it would.

## `minimal.vim`

```
set nocompatible
let &runtimepath  = '~/.vim/bundle/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable
" Add relevant options and VimTeX configuration below.
```
## `minimal.tex`
```
\documentclass{article}

\usepackage{xparse}
\NewDocumentEnvironment{test}{O{default1}r()D<>{default3}D""{default4}D''{default5}mb}{
    First: #1\par
    Second: #2\par
    Third: #3\par
    Fourth: #4\par
    Fifth: #5\par
    Sixth: #6\par
    Body: #7\par
} {}

\begin{document}

\begin{test}[hello](world)<select>"vie"'other'{Title}
	Hi
\end{test}

\end{document}
```

### Steps to reproduce

1. `nvim -u minimal.vim minimal.tex`
2. Position cursor on `Hi`
3. `vie`

### Expected behavior

Selected text would only be `Hi`, meaning everything after a `\begin{}`, but *starts with `[]` and ends with `{}`* would not be selected.
![image](https://github.com/lervag/vimtex/assets/49752842/74301141-d739-4efb-9db7-caab555c23b6)

### Actual behavior

Selected text is
```latex
(world)<select>"vie"'other'{Title}
  Hi
```
![image](https://github.com/lervag/vimtex/assets/49752842/f110ce78-4d26-4a28-9944-8cc90844d3fb)

### Do you use a latexmkrc file?

No.

### VimtexInfo

```yaml
System info:
  OS: Arch Linux
  Vim version: NVIM v0.9.1
  Has clientserver: true
  Servername: /run/user/1000/nvim.174769.0

VimTeX project: minimal
  base: minimal.tex
  root: /home/nora/Documents/Enseignement/Prepa/figures_generales
  tex: /home/nora/Documents/Enseignement/Prepa/figures_generales/minimal.tex
  main parser: current file verified
  document class: article
  packages: expl3 xparse
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 14
      output: /tmp/nvim.nora/LRpSke/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'minimal.tex'
      pid: 174896
  viewer: Zathura
    xwin id: 77594627
    cmd_start: zathura  -x "/usr/bin/nvim --headless -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 11:15:'/home/nora/Documents/Enseignement/Prepa/figures_generales/minimal.tex' 'minimal.pdf'&
  qf method: LaTeX logfile
```
