### ISSUE TITLE
Catton problem

### ISSUE THREAD

**Issue by yang-datong** [lervag/vimtex#2783]
### Description

There will be a brief stutter when I type "[]"

### Steps to reproduce

1. `nvim demo.tex` 2. `[]`

### Expected behavior

Enter as fast as I type "()" or "{}"

### Actual behavior

When I open xx.tex normally, I get a stutter of about half a second when I type "[]" (in any case)

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 11.6 (20G165)
  Vim version: NVIM v0.9.1
  Has clientserver: true
  Servername: /var/folders/v0/z8vb_cnd0f166wwv48ztdwk40000gn/T/nvim.hi/UHPD0N/nvim.12345.0

VimTeX project: demo
  base: demo.tex
  root: /Users/hi
  tex: /Users/hi/demo.tex
  main parser: fallback current file
  document class:
  compiler: latexmk
    engine: -pdf
    options:
      -file-line-error
      -synctex=1
      -interaction=batchmode
      -pretex='\\def\\StandardModel{true}\\def\\ShowAfterClassExercises{true}\\def\\UseInkscape
      -usepretex
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Skim
  qf method: LaTeX logfile
```
