### ISSUE TITLE
`:VimtexCompile` not producing a PDF

### ISSUE THREAD

**Issue by coderpotter** [lervag/vimtex#2784]
### Description

Hi! I am trying to compile my 'main.tex' and I get no errors but it does not produce a PDF.
`<leader>lo` output:
```
Rc files read:
  NONE
Latexmk: This is Latexmk, John Collins, 17 Mar. 2022. Version 4.77, version: 4.77.
======= Need to update make_preview_continuous for target files
Not using a previewer
------------
Running 'echo vimtex_compiler_callback_compiling'
------------
vimtex_compiler_callback_compiling
Latexmk: applying rule 'pdflatex'...
Rule 'pdflatex': The following rules & subrules became out-of-date:
  pdflatex
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -file-line-error -synctex=1 -interaction=nonstopmode -recorder  "main.tex"'
------------
This is pdfTeX, Version 3.141592653-2.6-1.40.24 (TeX Live 2022) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./main.tex
LaTeX2e <2021-11-15> patch level 1
L3 programming layer <2022-02-24> (/usr/local/texlive/2022/texmf-dist/tex/latex/graphics/color.sty (/usr/local/texlive/2022/texmf-dist/tex/latex/graphics-cfg/color.cfg) (/usr/local/texlive/2022/texmf-dist/tex/latex/graphics-def/pdftex.def)) (./usfmanus.cls
Document Class: usfmanus 2019/09/15 2.0 jbsubils University of South Florida Manuscript Class
(/usr/local/texlive/2022/texmf-dist/tex/latex/setspace/setspace.sty) (/usr/local/texlive/2022/texmf-dist/tex/latex/base/size12.clo)) (/usr/local/texlive/2022/texmf-dist/tex/latex/geometry/geometry.sty (/usr/local/texlive/2022/texmf-dist/tex/latex/graphics/keyval.sty) (/usr/local/texlive/2022/texmf-dist/tex/generic/iftex/ifvtex.sty (/usr/local/texlive/2022/texmf-dist/tex/generic/iftex/iftex.sty))) (/usr/local/texlive/2022/texmf-dist/tex/latex/base/inputenc.sty) (/usr/local/texlive/2022/texmf-dist/tex/generic/iftex/ifpdf.sty) (/usr/local/texlive/2022/texmf-dist/tex/latex/tools/verbatim.sty) (/usr/local/texlive/2022/texmf-dist/tex/latex/tocloft/tocloft.sty) (/usr/local/texlive/2022/texmf-dist/tex/latex/multirow/multirow.sty) (/usr/local/texlive/2022/texmf-dist/tex/latex/url/url.sty) (/usr/local/texlive/2022/texmf-dist/tex/latex/graphics/graphicx.sty (/usr/local/texlive/2022/texmf-dist/tex/latex/graphics/graphics.sty (/usr/local/texlive/2022/texmf-dist/tex/latex/graphics/trig.sty) (/usr/local/texlive/2022/texmf-dist/tex/latex/graphics-cfg/graphics.cfg))) (/usr/local/texlive/2022/texmf-dist/tex/latex/adjustbox/adjustbox.sty (/usr/local/texlive/2022/texmf-dist/tex/latex/xkeyval/xkeyval.sty (/usr/local/texlive/2022/texmf-dist/tex/generic/xkeyval/xkeyval.tex (/usr/local/texlive/2022/texmf-dist/tex/generic/xkeyval/xkvutils.tex))) (/usr/local/texlive/2022/texmf-dist/tex/latex/adjustbox/adjcalc.sty) (/usr/local/texlive/2022/texmf-dist/tex/latex/adjustbox/trimclip.sty (/usr/local/texlive/2022/texmf-dist/tex/latex/collectbox/collectbox.sty) (/usr/local/texlive/2022/texmf-dist/tex/latex/adjustbox/tc-pdftex.def)) (/usr/local/texlive/2022/texmf-dist/tex/latex/ifoddpage/ifoddpage.sty) (/usr/local/texlive/2022/texmf-dist/tex/latex/varwidth/varwidth.sty)) (/usr/local/texlive/2022/texmf-dist/tex/latex/floatrow/floatrow.sty (/usr/local/texlive/2022/texmf-dist/tex/latex/caption/caption3.sty)) (/usr/local/texlive/2022/texmf-dist/tex/latex/amscls/amsthm.sty)
(/usr/local/texlive/2022/texmf-dist/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(/usr/local/texlive/2022/texmf-dist/tex/latex/amsmath/amstext.sty (/usr/local/texlive/2022/texmf-dist/tex/latex/amsmath/amsgen.sty)) (/usr/local/texlive/2022/texmf-dist/tex/latex/amsmath/amsbsy.sty) (/usr/local/texlive/2022/texmf-dist/tex/latex/amsmath/amsopn.sty)) (/usr/local/texlive/2022/texmf-dist/tex/latex/amsfonts/amssymb.sty (/usr/local/texlive/2022/texmf-dist/tex/latex/amsfonts/amsfonts.sty)) (/usr/local/texlive/2022/texmf-dist/tex/latex/base/alltt.sty) (/usr/local/texlive/2022/texmf-dist/tex/latex/leftidx/leftidx.sty) (/usr/local/texlive/2022/texmf-dist/tex/latex/graphics/epsfig.sty) (/usr/local/texlive/2022/texmf-dist/tex/latex/appendix/appendix.sty

Package appendix Warning: No \appendix command in this document class!
(appendix)                Trying to create an appendix will probably fail.

) (/usr/local/texlive/2022/texmf-dist/tex/latex/algorithms/algorithm.sty (/usr/local/texlive/2022/texmf-dist/tex/latex/base/ifthen.sty)) (/usr/local/texlive/2022/texmf-dist/tex/latex/algorithms/algorithmic.sty) (/usr/local/texlive/2022/texmf-dist/tex/generic/babel/babel.sty (/usr/local/texlive/2022/texmf-dist/tex/generic/babel/txtbabel.def) (/usr/local/texlive/2022/texmf-dist/tex/generic/babel-english/english.ldf)) (/usr/local/texlive/2022/texmf-dist/tex/latex/enumitem/enumitem.sty) (/usr/local/texlive/2022/texmf-dist/tex/latex/tools/tabularx.sty (/usr/local/texlive/2022/texmf-dist/tex/latex/tools/array.sty)) (/usr/local/texlive/2022/texmf-dist/tex/latex/comment/comment.sty Excluding comment 'comment') (/usr/local/texlive/2022/texmf-dist/tex/latex/base/textcomp.sty) (/usr/local/texlive/2022/texmf-dist/tex/latex/xcolor/xcolor.sty (/usr/local/texlive/2022/texmf-dist/tex/latex/graphics-cfg/color.cfg)) (/usr/local/texlive/2022/texmf-dist/tex/latex/caption/caption.sty

Package caption Warning: Unknown document class (or package),
(caption)                standard defaults will be used.
See the caption package documentation for explanation.

) (/usr/local/texlive/2022/texmf-dist/tex/latex/preprint/balance.sty) (/usr/local/texlive/2022/texmf-dist/tex/latex/colortbl/colortbl.sty) (/usr/local/texlive/2022/texmf-dist/tex/latex/booktabs/booktabs.sty) (/usr/local/texlive/2022/texmf-dist/tex/latex/caption/subcaption.sty) (/usr/local/texlive/2022/texmf-dist/tex/latex/tools/hhline.sty) (/usr/local/texlive/2022/texmf-dist/tex/latex/pgf/basiclayer/pgf.sty (/usr/local/texlive/2022/texmf-dist/tex/latex/pgf/utilities/pgfrcs.sty (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/utilities/pgfutil-common.tex (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/utilities/pgfutil-common-lists.tex)) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/utilities/pgfutil-latex.def) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/utilities/pgfrcs.code.tex (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/pgf.revision.tex))) (/usr/local/texlive/2022/texmf-dist/tex/latex/pgf/basiclayer/pgfcore.sty (/usr/local/texlive/2022/texmf-dist/tex/latex/pgf/systemlayer/pgfsys.sty (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/systemlayer/pgfsys.code.tex (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/utilities/pgfkeys.code.tex (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/utilities/pgfkeysfiltered.code.tex)) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/systemlayer/pgf.cfg) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/systemlayer/pgfsys-pdftex.def (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/systemlayer/pgfsys-common-pdf.def))) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/systemlayer/pgfsyssoftpath.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/systemlayer/pgfsysprotocol.code.tex)) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/basiclayer/pgfcore.code.tex (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/math/pgfmath.code.tex (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/math/pgfmathcalc.code.tex
(/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/math/pgfmathutil.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/math/pgfmathparser.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.code.tex (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.basic.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.trigonometric.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.random.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.comparison.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.base.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.round.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.misc.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.integerarithmetics.code.tex))) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/math/pgfmathfloat.code.tex)) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/math/pgfint.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepoints.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathconstruct.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathusage.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/basiclayer/pgfcorescopes.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/basiclayer/pgfcoregraphicstate.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/basiclayer/pgfcoretransformations.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/basiclayer/pgfcorequick.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreobjects.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathprocessing.code.tex)
(/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/basiclayer/pgfcorearrows.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreshade.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreimage.code.tex (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreexternal.code.tex)) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/basiclayer/pgfcorelayers.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/basiclayer/pgfcoretransparency.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepatterns.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/basiclayer/pgfcorerdf.code.tex))) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/modules/pgfmoduleshapes.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/modules/pgfmoduleplot.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/latex/pgf/compatibility/pgfcomp-version-0-65.sty) (/usr/local/texlive/2022/texmf-dist/tex/latex/pgf/compatibility/pgfcomp-version-1-18.sty)) (/usr/local/texlive/2022/texmf-dist/tex/latex/pgf/frontendlayer/tikz.sty (/usr/local/texlive/2022/texmf-dist/tex/latex/pgf/utilities/pgffor.sty (/usr/local/texlive/2022/texmf-dist/tex/latex/pgf/utilities/pgfkeys.sty (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/utilities/pgfkeys.code.tex)) (/usr/local/texlive/2022/texmf-dist/tex/latex/pgf/math/pgfmath.sty (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/math/pgfmath.code.tex)) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/utilities/pgffor.code.tex (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/math/pgfmath.code.tex))) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/frontendlayer/tikz/tikz.code.tex (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/libraries/pgflibraryplothandlers.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/modules/pgfmodulematrix.code.tex)
(/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tikzlibrarytopaths.code.tex))) (/usr/local/texlive/2022/texmf-dist/tex/latex/pdflscape/pdflscape.sty (/usr/local/texlive/2022/texmf-dist/tex/latex/graphics/lscape.sty)) (/usr/local/texlive/2022/texmf-dist/tex/latex/pgfplots/pgfplotstable.sty (/usr/local/texlive/2022/texmf-dist/tex/generic/pgfplots/pgfplots.revision.tex) (/usr/local/texlive/2022/texmf-dist/tex/latex/pgfplots/pgfplots.sty (/usr/local/texlive/2022/texmf-dist/tex/generic/pgfplots/pgfplots.revision.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgfplots/pgfplots.code.tex (/usr/local/texlive/2022/texmf-dist/tex/generic/pgfplots/pgfplotscore.code.tex (/usr/local/texlive/2022/texmf-dist/tex/generic/pgfplots/sys/pgfplotssysgeneric.code.tex)) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgfplots/libs/pgfplotslibrary.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgfplots/oldpgfcompatib/pgfplotsoldpgfsupp_loader.code.tex (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/libraries/pgflibraryfpu.code.tex)) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgfplots/util/pgfplotsutil.code.tex (/usr/local/texlive/2022/texmf-dist/tex/generic/pgfplots/liststructure/pgfplotsliststructure.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgfplots/liststructure/pgfplotsliststructureext.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgfplots/liststructure/pgfplotsarray.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgfplots/liststructure/pgfplotsmatrix.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgfplots/numtable/pgfplotstableshared.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgfplots/liststructure/pgfplotsdeque.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgfplots/util/pgfplotsbinary.code.tex (/usr/local/texlive/2022/texmf-dist/tex/generic/pgfplots/util/pgfplotsbinary.data.code.tex))
(/usr/local/texlive/2022/texmf-dist/tex/generic/pgfplots/util/pgfplotsutil.verb.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgfplots/libs/pgflibrarypgfplots.surfshading.code.tex (/usr/local/texlive/2022/texmf-dist/tex/generic/pgfplots/sys/pgflibrarypgfplots.surfshading.pgfsys-pdftex.def))) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgfplots/util/pgfplotscolormap.code.tex (/usr/local/texlive/2022/texmf-dist/tex/generic/pgfplots/util/pgfplotscolor.code.tex)) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgfplots/pgfplotsstackedplots.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgfplots/pgfplotsplothandlers.code.tex (/usr/local/texlive/2022/texmf-dist/tex/generic/pgfplots/pgfplotsmeshplothandler.code.tex (/usr/local/texlive/2022/texmf-dist/tex/generic/pgfplots/pgfplotsmeshplotimage.code.tex))) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgfplots/pgfplots.scaling.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgfplots/pgfplotscoordprocessing.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgfplots/pgfplots.errorbars.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgfplots/pgfplots.markers.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgfplots/pgfplotsticks.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgfplots/pgfplots.paths.code.tex) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tikzlibrarydecorations.code.tex (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/modules/pgfmoduledecorations.code.tex)) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tikzlibrarydecorations.pathmorphing.code.tex (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/libraries/decorations/pgflibrarydecorations.pathmorphing.code.tex)) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tikzlibrarydecorations.pathreplacing.code.tex
(/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/libraries/decorations/pgflibrarydecorations.pathreplacing.code.tex)) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgfplots/libs/tikzlibrarypgfplots.contourlua.code.tex)) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tikzlibraryplotmarks.code.tex (/usr/local/texlive/2022/texmf-dist/tex/generic/pgf/libraries/pgflibraryplotmarks.code.tex))) (/usr/local/texlive/2022/texmf-dist/tex/generic/pgfplots/numtable/pgfplotstable.code.tex (/usr/local/texlive/2022/texmf-dist/tex/generic/pgfplots/numtable/pgfplotstable.coltype.code.tex))) (/usr/local/texlive/2022/texmf-dist/tex/latex/sfmath/sfmath.sty) (/usr/local/texlive/2022/texmf-dist/tex/latex/lipsum/lipsum.sty (/usr/local/texlive/2022/texmf-dist/tex/latex/l3packages/l3keys2e/l3keys2e.sty (/usr/local/texlive/2022/texmf-dist/tex/latex/l3kernel/expl3.sty (/usr/local/texlive/2022/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def))) (/usr/local/texlive/2022/texmf-dist/tex/latex/lipsum/lipsum.ltd.tex)) (/usr/local/texlive/2022/texmf-dist/tex/latex/collcell/collcell.sty (/usr/local/texlive/2022/texmf-dist/tex/latex/etoolbox/etoolbox.sty)) (/usr/local/texlive/2022/texmf-dist/tex/latex/everypage/everypage.sty

Package everypage Warning: Functionality similar to this package has recently
(everypage)                been implemented in LaTeX. This package is now in
(everypage)                legacy status.
(everypage)                Please, don't use it in new documents and packages.


Package everypage Warning: You appear to be running a version of LaTeX
(everypage)                providing the new functionality.
(everypage)                Doing the best to deliver the original `everypage`
(everypage)                interface on top of it. Strict equivalence is
(everypage)                not possible, breakage may occur.
(everypage)                If truly needed, Use `everypage-1x` to force the
(everypage)                loading of an older code base.

) (/usr/local/texlive/2022/texmf-dist/tex/latex/blindtext/blindtext.sty (/usr/local/texlive/2022/texmf-dist/tex/latex/tools/xspace.sty)) (/usr/local/texlive/2022/texmf-dist/tex/latex/fancyhdr/fancyhdr.sty))
Runaway definition?
->\newpage \pagestyle {empty} \par \addtocontents {toc}{\protect \contentsline \ETC.
! File ended while scanning definition of \printvita.
<inserted text> 
                }
<*> main.tex
            
! Emergency stop.
<*> main.tex
            
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on main.log.
Latexmk: Getting log file 'main.log'
Latexmk: Examining 'main.fls'
Latexmk: Examining 'main.log'
Latexmk: Errors, so I did not complete making targets
------------
Running 'echo vimtex_compiler_callback_failure'
------------
vimtex_compiler_callback_failure
Latexmk: Failure to make the files correctly
    ==> You will need to change a source file before I do another run <==
```

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 14.0 (23A5312d)
  Vim version: NVIM v0.9.1
  Has clientserver: true
  Servername: /var/folders/ty/246zyzyn7jv69xjxv2c5l32h0000gn/T/nvim.coderpotter/YUHgAm/nvim.3667.0

VimTeX project: main
  base: main.tex
  root: /Users/coderpotter/storage/USF/Research/dissertation
  tex: /Users/coderpotter/storage/USF/Research/dissertation/main.tex
  main parser: current file verified
  document class: usfmanus
  packages: adjcalc adjustbox algorithm algorithmic alltt amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm appendix array babel balance blindtext booktabs caption caption3 collcell collectbox color colortbl comment enumitem epsfig etoolbox everypage expl3 fancyhdr float floatrow geometry graphics graphicx hhline ifoddpage ifpdf iftex ifthen ifvtex inputenc keyval l3keys2e leftidx lipsum lscape multirow pdflscape pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfplots pgfplotstable pgfrcs pgfsys rotating setspace sfmath subcaption tabularx textcomp tikz tocloft trig trimclip url varwidth verbatim xcolor xkeyval xspace
  source files:
    main.tex
    dedication.tex
    Chapter1/chapter1.tex
    Chapter2/chapter2.tex
    Chapter3/chapter3.tex
    dictionary.tex
    appendixA.tex
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 11
      output: /var/folders/ty/246zyzyn7jv69xjxv2c5l32h0000gn/T/nvim.coderpotter/YUHgAm/1
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'main.tex'
      pid: 4489
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
