### ISSUE TITLE
Inconsistent compilation behavior

### ISSUE THREAD

**Issue by agarmu** [lervag/vimtex#2785]
### Description

I have noticed that on occasion, compilation randomly fails, but upon executing `\ll` twice it magically seems to work again.

### Steps to reproduce

1. `\ll` — Starts compiling
2. Make edits
3. Compilation fails upon save
4. `\ll` — Stops compiling
5. `\ll` — Starts compiling again (works now)

### Expected behavior

I would expect not to have `\ll` fail randomly while using only to work again upon restarting it.

### Actual behavior

Vimtex sometimes fails for no reason at all.

### Do you use a latexmkrc file?

N/A

### VimtexInfo

```yaml
System info:
  OS: macOS 14.0 (23A5276g)
  Vim version: NVIM v0.9.1
  Has clientserver: true
  Servername: REDACTED
```
