### ISSUE TITLE
Unable to set build directory

### ISSUE THREAD

**Issue by SebastianRefsnes** [lervag/vimtex#2788]
### Description

I'm trying to set a build directory in my vimtex config, but it doesn't seem to do anything.
My config is quite minimal, it looks like this:
```vim
filetype plugin indent on

syntax enable

let g:vimtex_view_method = 'zathura'

" Not sure why, but this does not seem to do anything
let g:vimtex_compiler_latexmk = {
    \ 'build_dir' : 'build',
    \}

let maplocalleader = " "
```

And minimal.tex is just a copy of the example minimal.tex, that is:
```latex
\documentclass{minimal}
\begin{document}
Hello world!
\end{document}
```

I am sure that the file is sourced, because if I for example, remove `let maplocalleader = " "`, then I can no longer use space + ll to compile the tex file that I am editing

### Steps to reproduce

1. Use the above config file
2. open `minimal.tex` in neovim, hit leader + ll to compile

### Expected behavior

I expected the generated files to be placed in a directory called `build`

### Actual behavior

All files generated ended up being placed next to minimal.tex.
If I run `ls` in the directory afterwards, I get something like:
```bash
$ ls
minimal.aux  minimal.fdb_latexmk  minimal.fls  minimal.log  minimal.pdf  minimal.synctex.gz  minimal.tex
```

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 22.04.3 LTS
  Vim version: NVIM v0.9.1
  Has clientserver: true
  Servername: /run/user/1000/nvim.84283.0

VimTeX project: minimal
  base: minimal.tex
  root: /home/me/programming/tmp_example
  tex: /home/me/programming/tmp_example/minimal.tex
  main parser: current file verified
  document class: minimal
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
