### ISSUE TITLE
Can't have flatpak sioyek as view method 

### ISSUE THREAD

**Issue by enrico223** [lervag/vimtex#2791]
### Description

I have `sioyek` installed as `flatpak` and when I try the live preview I get a prompt saying `sioyek is not executrable`.
I tryiens

### Steps to reproduce

1. install `sioyek` via flatpak
2. open a tex document
3. try `:VimtexCompile`

### Do you use a latexmkrc file?

No 

### VimtexInfo

```yaml
System info:
  OS: EndeavourOS Linux
  Vim version: NVIM v0.9.2
  Has clientserver: true
  Servername: /run/user/1000/nvim.6111.0

VimTeX project: main
  base: main.tex
  root: /home/enrico/Documents/Università/MAGISTRALE/Thesis/final_writing
  tex: /home/enrico/Documents/Università/MAGISTRALE/Thesis/final_writing/main.tex
  main parser: recursive search
  document class: report
  packages: amsbsy amsgen amsmath amsopn amstext array atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook biblatex bigintcalc bitset blindtext blx-case-expl3 booktabs enumitem environ epstopdf-base etexcmds etoolbox expl3 fontenc footmisc geometry gettitlestring graphics graphicx hycolor hyperref iftex ifthen ifvtex import infwarerr inputenc intcalc keyval kvdefinekeys kvoptions kvsetkeys letltxmacro logreq longtable ltxcmds makecell microtype multirow nameref pdfescape pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgfrcs pgfsys refcount rerunfilecheck scrbase scrlfile scrlfile-hook scrlogo setspace shellesc svg tabularx tcolorbox threeparttable titleps titlesec transparent transparent-nometadata trig trimspaces uniquecounter url verbatim xcolor xparse xspace
  source files:
    main.tex
    chapters/introduction.tex
    chapters/terminology_of_data.tex
    chapters/EU_approach.tex
    chapters/analysis_acts.tex
    chapters/data_sharing_platforms.tex
    chapters/data_spaces.tex
    chapters/conclusion.tex
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 10
      output: /tmp/nvim.enrico/r7dtf3/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'main.tex'
      pid: 6151
  viewer: sioyek
  qf method: LaTeX logfile
```
```
