### ISSUE TITLE
VimTeX says "Compilation failed" when "\texit{}" is used although the document compiles (without italic text ofc).

### ISSUE THREAD

**Issue by morrismuehl** [lervag/vimtex#2793]
### Description

I ran into this today. The below mwe produces a pdf file just fine, although the first line is not rendered italic (obviously). 
VimTeX still outputs "Compilation failed". I believe this should not be intended behaviour?

I'll omit my latexmkrc right now because I think its not relevant, but I'll happily provide further info if needed. 

### Steps to reproduce

```
%!TEX TS-program = pdflatex
\documentclass{article}`

\begin{document}

\texit{This is not the correct way to make something italic}
\textit{This is}


\end{document}
```

### Expected behavior

I'd expect VimTeX to not output "Compilation failed" when a pdf file is reliably produced. I see the above problem more akin to an undefined reference.

### Actual behavior

VimTeX spits out "Compilation failed" along with a compiled pdf.

### Do you use a latexmkrc file?

Yes

### VimtexInfo

```yaml
System info:
  OS: Void Linux
  Vim version: NVIM v0.9.2
  Has clientserver: true
  Servername: /run/user/1000/nvim.5692.0

VimTeX project: mwe
  base: mwe.tex
  root: /home/moz/Uni/tex/mwe
  tex: /home/moz/Uni/tex/mwe/mwe.tex
  main parser: current file verified
  document class: article
  packages: graphics graphicx keyval trig
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 32
      output: /tmp/nvim.moz/UvDiRN/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'mwe.tex'
      pid: 8355
  viewer: Zathura
    cmd_start: zathura  -x "/usr/bin/nvim --headless -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 9:1:'/home/moz/Uni/tex/mwe/mwe.tex' 'mwe.pdf'&
  qf method: LaTeX logfile
```
