### ISSUE TITLE
out_dir and aux_dir will not be specified if multi-file project

### ISSUE THREAD

**Issue by MKrbm** [lervag/vimtex#2794]
### Description

As you can see in `:VimtexInfo`, `out_dir` and `aux_dir` are specified only for `latex.tex` while main file is `main.tex`.

### Steps to reproduce

1. use lazy.nvim for package manager
2. add plugin using
    ```lua
      {
        "lervag/vimtex",
        ft = {
          "tex",
        },
        config = function()
          vim.cmd "call vimtex#init()"
          vim.g.vimtex_compiler_method = "latexmk"
          vim.g.vimtex_view_general_viewer = "okular"
          -- vim.g.tex_flavor = "main"
          vim.g.vimtex_compiler_latexmk = {
            aux_dir = "./aux",
            out_dir = "./out",
          }
          vim.g.vimtex_indent_enabled = 0
          vim.g.vimtex_view_general_options = "--noraise --unique file:@pdf\\#src:@line@tex"
        end,
      },
    ```
3. prepare multi-file project. I just downloaded [this](https://www.overleaf.com/latex/templates/creighton-university-physics-thesis-template/dgyfzfzjwcfr) for example. 
4. `mkdir out`
5. compile with `<leader>ll` 
6. files will be generated under `cwd`.

### Expected behavior

generate build files under `out` and `aux` dir as the case of single-file project.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 22.04.2 LTS
  Vim version: NVIM v0.9.1
  Has clientserver: true
  Servername: /tmp/runtime-user/nvim.3965.0

VimTeX project: main
  base: main.tex
  root: /home/user/project/latex/thesis_test
  tex: /home/user/project/latex/thesis_test/main.tex
  main parser: current file verified
  document class: report
  packages: amsbsy amsgen amsmath amsopn amstext appendix array atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook bigintcalc bitset booktabs breqn calc color colortbl datatool-base datatool-fp defpattern epstopdf-base eso-pic etexcmds etoolbox expl3 flexisym fp fp-addons fp-basic fp-eqn fp-eval fp-exp fp-pas fp-random fp-snap fp-trigo fp-upn geometry gettitlestring glossaries glossaries-compatible-307 glossary-hypernav glossary-list glossary-long glossary-super glossary-tree graphics graphicx hycolor hyperref iftex ifthen ifvtex indentfirst infwarerr intcalc keyval kvdefinekeys kvoptions kvsetkeys letltxmacro longtable lscape ltxcmds mathstyle mfirstuc multicol nameref pdfescape pdflscape pdfpages pdftexcmds refcount rerunfilecheck setspace subfigure substr supertabular textcase trig uniquecounter url xcolor xfor xkeyval
  source files:
    main.tex
    glossary.tex
    approval.tex
    cover.tex
    abstract.tex
    acknowledgments.tex
    dedication.tex
    chapter1.tex
    chapter2.tex
    latex.tex
    refhowto.tex
    flow.tex
    chapter3.tex
    chapter4.tex
    chapter5.tex
    appendixa.tex
    appendixb.tex
    biblio.tex
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 19
      output: /tmp/nvim.user/Mmt3BY/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'main.tex'
      pid: 5121
  viewer: General
    job: 
      pid: -
      cmd: okular --noraise --unique file:'/home/user/project/latex/thesis_test/main.pdf'\#src:98'/home/user/project/latex/thesis_test/main.tex'
  qf method: LaTeX logfile

VimTeX project: latex
  base: latex.tex
  root: /home/user/project/latex/thesis_test
  tex: /home/user/project/latex/thesis_test/latex.tex
  main parser: local file
  document class: 
  source files: -1
  compiler: latexmk
    root: /home/user/project/latex/thesis_test
    target: /home/user/project/latex/thesis_test/latex.tex
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    out_dir: ./out
    aux_dir: ./aux
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
