### ISSUE TITLE
Help with custom conceal using regex

### ISSUE THREAD

**Issue by userrand** [lervag/vimtex#2795]
### Description

The following command works in a vimrc file without vimtex

```vim
syntax match TexMathSymbol '\%(\\frac\)\@<={\%([^}]\{-}}{[^}]\{-}}\)\@='  conceal cchar=❬
```

But I cannot get it to work with vimtex in neovim. I tried the following, (According to the documentation, it seems the regex is expected to be in very magic mode)

```vim
let g:tex_conceal='abdmg'
set concealcursor=nvic
set conceallevel=2
let g:vimtex_syntax_custom_cmds = [
      \ {'name': 'frac', 'cmdre': '(\\frac)@<={([^}]{-}}{[^}]{-}})@='    , 'mathmode': 1, 'concealchar': '❬'},
      \]
```

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Linux 6.4.12-100.fc37.x86_64
  Vim version: NVIM v0.9.1
  Has clientserver: true
  Servername: /run/user/1000/nvim.113725.0

VimTeX project: test
  base: test.tex
  root: /home/claude/projects
  tex: /home/claude/projects/test.tex
  main parser: current file verified
  document class: article
  packages: algorithm algorithmic amsfonts amsmath amssymb amsthm babel bbm bm cancel caption cite color enumitem epsfig fontenc footmisc graphicx helvet inputenc lmodern setspace soul subfigure textcomp titlesec url verbatim wasysym wrapfig
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
