### ISSUE TITLE
zathura_simple view fails health check

### ISSUE THREAD

**Issue by LimaoC** [lervag/vimtex#2796]
### Description

Setting `g:vimtex_view_method` to `zathura_simple` fails the health check (`:checkhealth`), as `check_view_zathura_simple()` does not exist.

### Steps to reproduce

**minimal.vim**
```vim
let g:vimtex_view_method = 'zathura_simple'
```
1. Open any `.tex` file and run `:checkhealth`.

### Expected behavior

`:checkhealth` output for `zathura_simple` should be like `zathura` minus the `xdotool` check:
```
VimTeX
- OK Vim version should have full support!
- WARNING Zathura requires xdotool for forward search!
- OK Compiler should work!
```

### Actual behavior

On running `:checkhealth` with `zathura_simple`:
```
vimtex: health#vimtex#check

- ERROR Failed to run healthcheck for "vimtex" plugin. Exception:
  function health#check[25]..health#vimtex#check[7]..<SNR>122_check_view, line 1
  Vim(call):E117: Unknown function: <SNR>122_check_view_zathura_simple
```

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 22.04.2 LTS
  Vim version: NVIM v0.9.2
  Has clientserver: true
  Servername: /run/user/1000/nvim.13711.0

VimTeX project: minimal
  base: minimal.tex
  root: /tmp
  tex: /tmp/minimal.tex
  main parser: fallback current file
  document class: 
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
      -shell-escape
    out_dir: build-minimal
    aux_dir: build-minimal
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
  qf method: LaTeX logfile
```
