### ISSUE TITLE
VimtexEventView is not being recognized by neovim.

### ISSUE THREAD

**Issue by 0range0range** [lervag/vimtex#2803]
### Description

I am following the guide here:  https://www.ejmastnak.com/tutorials/vim-latex/pdf-reader/#zathura

I successfully set neovim window ID to a global neovim variable. But when I am trying to set autocommand to trigger "VimtexEventView", I get: `E5113: lua: ...: unexpected event`

Here is the code for autocommand.
```lua
autocommand("VimtexEventView",
{
  group = augroup("vimtex_event_focus", {clear = true}),
  desc = "Add forward search refocusing in vimtex",
  pattern = {"*.tex"},
  callback = TeXFocusVim,
})
```
with TeXFocusVim being:

```lua 
local function TeXFocusVim()
  os.execute("sleep 0.2")
  os.execute("xdotool windowfocus " .. vim.g.nvim_window_id)
end
```
 I tested it with "BufWritePost" event and it worked. Is it a `vimtex` problem or some more general problem with neovim and plugin events? I could not find info on that.

Maybe related: https://github.com/lervag/vimtex/issues/2733

### Expected behavior

autocommand is registered and working

### Actual behavior

VimtexEventView is not known to neovim.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Linux 5.15.93-1-lts
  Vim version: NVIM v0.9.2
  Has clientserver: true
  Servername: /run/user/1000/nvim.1025570.0

VimTeX project: test
  base: test.tex
  root: some/path
  tex: some/path
  main parser: current file verified
  document class: article
  packages: expl3 l3keys2e lipsum
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 56623107
    cmd_forward_search: zathura --synctex-forward 21:1:'some/path' 'test.pdf'&
  qf method: LaTeX logfile
```
