### ISSUE TITLE
Inverse search with sioyek does not work in latest nightly neovim

### ISSUE THREAD

**Issue by haoming-li-ling** [lervag/vimtex#2809]
### Description

On the latest stable version of neovim, inverse search is fine. However, on the lastest nightly, inverse search only works with Skim but not sioyek.

### Steps to reproduce

Open any file with the lastest nightly and try to perform sioyek inverse search after a forward search

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 14.0 (23A344)
  Vim version: NVIM v0.10.0-dev-6823fdb
  Has clientserver: true
  Servername: /var/folders/0j/154blqm96cjgtf7dwtccvk680000gn/T/nvim.haomingli/IrdYPe/nvim.39639.0

VimTeX project: draft
  base: draft.tex
  root: /Users/haomingli/Documents/MIT/generals-1/draft
  tex: /Users/haomingli/Documents/MIT/generals-1/draft/draft.tex
  main parser: current file verified
  document class: article
  packages: amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm array atbegshi-ltx atveryend-ltx auxhook biblatex bigintcalc bitset blx-case-expl3 booktabs calc centernot cgloss cgloss4e cleveref csquotes csvsimple csvsimple-legacy elocalloc enumitem environ epstopdf-base etexcmds etoolbox expl3 fancyvrb fontenc fontspec fontspec-luatex forest forest-lib-linguistics geometry gettitlestring gobble graphics graphicx hycolor hyperref ifluatex iftex ifthen ifvtex ifxetex infwarerr inlinedef intcalc keyval kvdefinekeys kvoptions kvsetkeys l3keys2e letltxmacro linguex logreq ltxcmds markdown mathtools mhsetup mweights nameref newpxmath newpxtext paralist pdfescape pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfopts pgfrcs pgfsys pifont realscripts refcount rerunfilecheck scalefnt shellesc stmaryrd stringenc tabularx textcomp tikz tikz-cd trig trimspaces ulem uniquecounter url xcolor xkeyval xparse xpatch xspace xstring
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    out_dir: ./output
    aux_dir: ./output
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: sioyek
    job: 
      pid: -
      cmd: sioyek  --inverse-search "/Users/haomingli/.local/share/bob/nvim-bin/nvim --headless -c \"VimtexInverseSearch %2 '%1'\"" --forward-search-file '/Users/haomingli/Documents/MIT/generals-1/draft/draft.tex' --forward-search-line 1 '/Users/haomingli/Documents/MIT/generals-1/draft/output/draft.pdf'
    cmd_start: sioyek  --inverse-search "/Users/haomingli/.local/share/bob/nvim-bin/nvim --headless -c \"VimtexInverseSearch %2 '%1'\"" --forward-search-file '/Users/haomingli/Documents/MIT/generals-1/draft/draft.tex' --forward-search-line 1 '/Users/haomingli/Documents/MIT/generals-1/draft/output/draft.pdf'
  qf method: LaTeX logfile
```
