### ISSUE TITLE
Return to original window when closing toc or word count

### ISSUE THREAD

**Issue by petobens** [lervag/vimtex#2817]
### Description

If I have a split buffer and either open the table of contents or the word count buffer and then quit those buffers then the cursor doesn't return to the original window.

### Steps to reproduce

Note: I can add a minimal.tex file if this is not immediately reproducible.

1. Open a `foo.tex` file with minimal content:
```tex
\documentclass{article}
\begin{document}
\section{Foo}
Foo
\end{document}
```
2. Open the TOC or the count word buffer
3. Press `q` to close such buffers.
![vimtex](https://github.com/lervag/vimtex/assets/2583971/50541c0f-d39e-4637-9e73-81f0cd193852)

### Expected behavior

After 3. the cursor should return to the original window (right)

### Actual behavior

It goes to the left window

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Arch Linux
  Vim version: NVIM v0.10.0-dev-1413+g684e93054b
  Has clientserver: true
  Servername: /tmp/nvimsocket

VimTeX project: foo
  base: foo.tex
  root: /home/pedro/Desktop/foo-latex
  tex: /home/pedro/Desktop/foo-latex/foo.tex
  main parser: current file verified
  document class: article
  compiler: arara
    options:
      --log
```
