### ISSUE TITLE
VimTex compiles within symlink directory instead of base directory

### ISSUE THREAD

**Issue by ravibrock** [lervag/vimtex#2820]
### Description

For my math homework, I store the $\LaTeX$ source files in a git repo, and symlink them to my desktop for easy access. This is my VimTex config (for Lazy):
```lua
{
    "lervag/vimtex",
    ft = { "tex" },
    keys = {
        { "<leader>ll", "<CMD>VimtexCompile<CR>" },
        { "<leader>lv", "<CMD>VimtexView<CR>"},
        { "<leader>lc", "<CMD>VimtexWipe<CR>"},
    },
    config = function()
        vim.g.vimtex_view_method = "sioyek"
        vim.g.vimtex_view_sioyek_options = "--new-window"
        vim.g.tex_conceal = "abdmg"

        function VimtexWipe()
            local current_file = vim.fn.expand("%:t:r") -- Filename without extension
            local extensions_to_delete = {
                ".aux",
                ".bbl",
                ".bcf",
                ".blg",
                ".cps*",
                ".fdb_latexmk",
                ".fls",
                ".log",
                ".mw",
                ".out",
                ".run.xml",
                ".synctex.gz",
                ".toc",
            }
            for _, ext in ipairs(extensions_to_delete) do
                vim.cmd("silent! !rm " .. current_file .. ext)
            end
            vim.cmd([[echo "VimTex: Compiler clean finished"]])
        end

        vim.api.nvim_create_user_command("VimtexWipe", VimtexWipe, {})
        vim.api.nvim_create_autocmd("VimLeave", { command = "lua VimtexWipe()" })
    end,
}
```
I have a function in my Neovim configuration that automatically opens symlinks in their base directory:
```lua
function FollowSymlink()
    local file = vim.fn.expand("%:p")
    local real_file = vim.fn.resolve(file)
    if (string.match(real_file, "[^%d]+:/") or real_file == file) then
        return
    end
    vim.cmd("file " .. real_file)
    vim.cmd("silent! w!")  -- Workaround for "file exists" error on write
end
autocmd("BufRead", { command = "lua FollowSymlink()" })
```
and I also have a custom template that I source with the following commands:
```tex
\usepackage{import}
\import{templates/math}{homework.sty}
```
However, I noticed that if I open the symlink, rather than the full filename, VimTex compiles in my Desktop folder (i.e. the auxfiles appear in my desktop) and it therefore produces an error as the `templates/math` folder is in the git repo with my homework, not my desktop.

This isn't a major bug, of course, so if there's not a trivial solution feel free to close the issue and I can live with it. Thank you!

### Steps to reproduce

```tex
\ProvidesPackage{homework}
\newcommand\testtesttest{\LaTeX}
```

```tex
\usepackage{import}
\import{test}{homework.sty}
\begin{document}
\testtesttest
\end{document}
```

1. `cd ~/Desktop`
2. `ln -s test/math.tex math.tex`
3. `vim math.tex`
4. `:VimtexCompile`

### Expected behavior

I would expect VimTex to compile in the base directory, not the symlink directory. Vim appears to be in the correct directory, as it (for example) provides tab completions for files in the proper git repo, not my desktop.

### Actual behavior

VimTex compiles in my Desktop, and that's where it generates auxfiles. It's clear from `VimtexInfo` that it doesn't recognize the directory change, for some reason.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 13.3.1 (22E772610a)
  Vim version: NVIM v0.9.4
  Has clientserver: true
  Servername: /var/folders/5j/84p0q84s4452bjhnyb8bjtqr0000gn/T/nvim.ravibrock/c0JZ41/nvim.60816.0

VimTeX project: MATH147
  base: MATH147.tex
  root: /Users/ravibrock/Desktop
  tex: /Users/ravibrock/Desktop/MATH147.tex
  main parser: current file verified
  document class: report
  packages: import silence
  source files:
    MATH147.tex
    templates/math/homework.sty
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: sioyek
  qf method: LaTeX logfile
```
