### ISSUE TITLE
Some Compilation issues with ctex.

### ISSUE THREAD

**Issue by lin-behappy** [lervag/vimtex#2823]
### Description

It is my first time use vimtex, some of the problems encountered as follows:

1.  `\ll` compile the `minimal.tex` and view in sumatraPDF.  then I add some word and save the `.tex`, sumatraPDF won't refresh the pdf, it need to close the pdf and open again to see the changes.

2. if  `minimal.tex`  use `\input{}` path has Chinese text like `\input{files/中文路径/中文文件名}`, then I have changed the `中文文件名.tex` and compile the `minimal.tex` it won't changed the pdf. I have tried compile it several times, but the pdf won't change. But if I add some word (like add blank line) in minimal.tex and compile it the changes in `中文文件名.tex` could be shown in pdf.

### Steps to reproduce

here is the minimal.tex

```tex
%! TEX TS-program = xelatex
\documentclass{ctexbook}
\begin{document}

\input{files/中文路径/中文文件名}
\end{document}
```

here is the minimal `.lua`

```lua
vim.g.vimtex_quickfix_mode=0
vim.g.vimtex_view_general_viewer = "SumatraPDF"
vim.g.vimtex_view_general_options = "-reuse-instance -forward-search @tex @line @pdf"
```

### Do you use a latexmkrc file?

no

### VimtexInfo
There is some messy code in OS: line and I can't copy it; like `<be><d2>□<b0>..`, perhaps is my Chinese name.

```yaml
System info:
 OS: DESKTOP-QO5KIHH (Microsoft Windows 10 …
 Vim version: NVIM v0.9.4
  Has clientserver: true
  Servername: \\.\pipe\nvim.5716.0

VimTeX project: minimal
  base: minimal.tex
  root: C:\tmp\minimal
  tex: C:\tmp\minimal\minimal.tex
  main parser: current file verified
  document class: ctexbook
  packages: CJK CJKpunct CJKspace CJKutf8 MULEenc ctexhook ctexpatch everysel everysel-2011-10-28 expl3 fix-cm fontenc hyperref ifpdf iftex inputenc l3keys2e xparse xparse-2020-10-01 zhnumber
  source files:
    minimal.tex
    files/中文路径/中文文件名.tex
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 13
      output: C:\Users\JehuL\AppData\Local\Temp\nvim.0\QuStdN\0
      cmd: set max_print_line=2000 & latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -pvctimeout- -view=none -e "$compiling_cmd = ($compiling_cmd ? $compiling_cmd . ' ^& ' : '') . 'echo vimtex_compiler_callback_compiling'" -e "$success_cmd = ($success_cmd ? $success_cmd . ' ^& ' : '') . 'echo vimtex_compiler_callback_success'" -e "$failure_cmd = ($failure_cmd ? $failure_cmd . ' ^& ' : '') . 'echo vimtex_compiler_callback_failure'" "minimal.tex"
      pid: 11664
  viewer: General
    job: 
      pid: -
      cmd: SumatraPDF -reuse-instance -forward-search "C:\tmp\minimal\minimal.tex" 1 "C:\tmp\minimal/minimal.pdf"
  qf method: LaTeX logfile
```
