### ISSUE TITLE
Can't get dbus working on M1 as guide suggests

### ISSUE THREAD

**Issue by s1gtrap** [lervag/vimtex#2824]
### Description

Hi, I'm trying to get this working on an M1 machine.

This is my 5th or so attempt but I’m fairly certain it is a clean install (having run `brew unlink`/`brew uninstall` for `dbus`, `zathura-pdf-poppler`, `zathura` and `girara`. This also seems like it might be a `dbus` problem as the current problem is seemingly only with `dbus`,  but I figured I would try here first as others seem to have resolved their `dbus` with help from here.

Following the `:help vimtex-faq-zathura-macos` docs:

1. `brew install dbus` finishes successfully

2. So does adding `export DBUS_SESSION_BUS_ADDRESS="unix:path=$DBUS_LAUNCHD_SESSION_BUS_SOCKET”` to `.zshrc`, naturally.

3. I assume `/usr/local/opt/dbus/share/dbus-1/session.conf` is substituted by `/opt/homebrew/Cellar/dbus/1.14.10/share/dbus-1/session.conf` in my case, since I’m on an M1, but if that’s true the entry is changed to the following
    ```
    <auth>DBUS_COOKIE_SHA1</auth>
    ```
4. This is where it starts to go wrong… Upon reloading the shell and running `brew services start dbus`, it seemingly starts fine:
    ```
    $ brew services start dbus
    ==> Successfully started `dbus` (label: org.freedesktop.dbus-session)
    ```
    but upon checking
    ```
    $ brew services info dbus
    dbus (org.freedesktop.dbus-session)
    Running: ✘
    Loaded: ✔
    Schedulable: ✘
    ```
    which is where it all starts to go wrong. Running  `brew services start dbus` again
    ```
    $ brew services start dbus
    Bootstrap failed: 5: Input/output error
    Try re-running the command as root for richer errors.
    Error: Failure while executing; `/bin/launchctl bootstrap gui/501 /Users/s1g/Library/LaunchAgents/org.freedesktop.dbus-session.plist` exited with 5.
    ```
    and `dbus-launch` gets me
    ```
    $ dbus-launch
    dbus-daemon[9336]: Failed to start message bus: launchd's environment variable DBUS_LAUNCHD_SESSION_BUS_SOCKET is empty, but should contain a socket path.

    EOF in dbus-launch reading address from bus daemon
    ```
    also running the `launchctl` command as `sudo` just gets me:
    ```
    $ sudo /bin/launchctl bootstrap gui/501 /Users/s1g/Library/LaunchAgents/org.freedesktop.dbus-session.plist
    Bootstrap failed: 5: Input/output error
    ```

So yea I’m really at a loss..

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 14.1 (23B74)
  Vim version: NVIM v0.9.4
  Has clientserver: true
  Servername: /var/folders/m6/nyw0tbd5239gngtm06pzykr00000gn/T/nvim.s1g/GvUYPs/nvim.9533.0

VimTeX project: article
  base: article.tex
  root: /Users/s1g/Workspaces/BSc/report
  tex: /Users/s1g/Workspaces/BSc/report/article.tex
  main parser: current file verified
  document class: article
  packages: adjcalc beramono biblatex blx-case-expl3 collectbox courier epstopdf-base etoolbox expl3 fontenc graphics graphicx iftex ifthen infwarerr keyval kvoptions kvsetkeys listings logreq lstlang1 lstlang2 lstlang3 lstmisc ltxcmds pdftexcmds realboxes titlesec trig url xcolor xkeyval xparse xpatch
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
