### ISSUE TITLE
SumatraPDF doesn't auto-reload / refresh compiled PDF when using xelatex engine

### ISSUE THREAD

**Issue by xarthurx** [lervag/vimtex#2830]
### Description

When compiling large document, SumatraPDF won't auto-reload/update the PDF when I make changes to my `.tex` file.

But pressing `r` inside SumatraPDF can manually reload the PDF.

I tested the minimal example, and actually this should not be a default VimTex error. But there're some strange things I observed, let me explain.

For the `minimal.tex` example, if I observe (eye-ball) the `build` folder, I don't see the PDF got `deleted` and "re-generated".

However, when compiling my own tex project, I observe (eye-ball) that inside the `build` folder, the corresponding PDF file got deleted and re-generated... I don't know if this is related to my issue... 

Perhaps by pressing `r` inside SumatraPDF, the program reload by file locations, but for the auto-update with `-reuse-instance`, SumatraPDF somehow tries to find the original PDF (which won't exist)?

### Do you use a latexmkrc file?

YES

`latexmkrc` file:
```
$pdflatex="xelatex %O %S";
```

### VimtexInfo

```yaml
System info:
  OS: XOMEN (Microsoft Windows 11 Home)
  Vim version: NVIM v0.9.2
  Has clientserver: true
  Servername: \\.\pipe\nvim.17892.0

VimTeX project: researchStatement
  base: researchStatement.tex
  root: C:\Users\xarthurx\source\docRepo\doc_CV.Resume\20_latex
  tex: C:\Users\xarthurx\source\docRepo\doc_CV.Resume\20_latex\researchStatement.tex
  main parser: current file verified
  document class: x-cv
  packages: amsbsy amsgen amsmath amsopn amstext array atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook bigintcalc bitset calc color cormorantgaramond csquotes enumitem environ etoolbox expl3 fancyhdr fix-cm fontawesome5 fontawesome5-utex-helper fontenc fontspec fontspec-xetex geometry gettitlestring graphics graphicx hycolor hyperref ifluatex ifmtarg iftex ifthen ifvtex ifxetex infwarerr intcalc keyval kvdefinekeys kvoptions kvsetkeys l3keys2e letltxmacro longtable ltxcmds makecell nameref parskip pdfescape pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfrcs pgfsys ragged2e refcount rerunfilecheck roboto setspace stringenc tabularx tcolorbox textcomp tikz tikzfill-common tikzfill.image trig trimspaces unicode-math unicode-math-xetex uniquecounter url verbatim xcolor xifthen xkeyval xparse
  compiler: latexmk
    engine: -xelatex
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    out_dir: build
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 217
      output: C:\Users\xarthurx\AppData\Local\Temp\nvim.0\AjpRcv\0
      cmd: set max_print_line=2000 & latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -xelatex -outdir=build -pvc -pvctimeout- -view=none -e "$compiling_cmd = ($compiling_cmd ? $compiling_cmd . ' ^& ' : '') . 'echo vimtex_compiler_callback_compiling'" -e "$success_cmd = ($success_cmd ? $success_cmd . ' ^& ' : '') . 'echo vimtex_compiler_callback_success'" -e "$failure_cmd = ($failure_cmd ? $failure_cmd . ' ^& ' : '') . 'echo vimtex_compiler_callback_failure'" "researchStatement.tex"
      pid: 20108
  viewer: General
    job: 
      pid: -
      cmd: SumatraPDF -reuse-instance -forward-search "C:\Users\xarthurx\source\docRepo\doc_CV.Resume\20_latex\researchStatement.tex" 139 "C:\Users\xarthurx\source\docRepo\doc_CV.Resume\20_latex/build/researchStatement.pdf"
  qf method: LaTeX logfile

```
