### ISSUE TITLE
E117: Unknown function: vimtex#syntax#core#new_region_math

### ISSUE THREAD

**Issue by zhuosongz** [lervag/vimtex#2834]
### Description

I used this command in after/syntax/tex.vim, to add new math zones in my files including new math environments. However, after I update the plugin today, it shows this error. May I know why this function is removed? Thank you!

 

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 14.1 (23B74)
  Vim version: VIM 9.0 (1-1897)
  Has clientserver: true
  Servername: VIM

VimTeX project: test22
  base: test22.tex
  main parser: current file verified
  document class: article
  packages: CJK CJKfntef amsbsy amsgen amsmath amsopn amssymb amstext amsthm cite ctex ctexhook ctexpatch expl3 fix-cm fontenc fontspec fontspec-xetex graphicx hyperref indentfirst xeCJK xeCJKfntef xparse xtemplate zhnumber
  compiler: latexmk
    engine: -xelatex
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 0
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
