### ISSUE TITLE
health#report_start is deprecated

### ISSUE THREAD

**Issue by jfvillablanca** [lervag/vimtex#2838]
### Description

```
==============================================================================
vimtex: health#vimtex#check

VimTeX ~
- WARNING health#report_start is deprecated, use vim.health.start instead. :help |deprecated|
  This feature will be removed in Nvim version 0.11
- OK Vim version should have full support!
- WARNING health#report_ok is deprecated, use vim.health.ok instead. :help |deprecated|
  This feature will be removed in Nvim version 0.11
- OK Zathura should work properly!
- OK Compiler should work!
```
I use neovim and I believe the `health` API changed. I am not too familiar if this change also affects vim. Just thought you should know

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Linux 6.1.62
  Vim version: NVIM v0.10.0-dev-d2983dc
  Has clientserver: true
  Servername: /run/user/1000/nvim.526681.0

VimTeX project: document
  base: document.tex
  root: /home/jmfv/dev/tex-playground
  tex: /home/jmfv/dev/tex-playground/document.tex
  main parser: current file verified
  document class: article
  packages: nicematrix
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
