### ISSUE TITLE
Some features broken with lazy.nvim

### ISSUE THREAD

**Issue by shortestgiraffe** [lervag/vimtex#2840]
### Description

I switched from packer to lazy.nvim and for some reason I cannot get some features to work with vimtex. Mainly continuous compilation and auto-completion for citing.

I have following config which I copied from another issue:
```lua
return {
    "lervag/vimtex",
    init = function()
      vim.g.vimtex_compiler_method = 'latexmk'
      vim.g.vimtex_compiler_latexmk = {
        continuous = 1
      }
    end,
}
```
I have read issues in vimtex as well as in lazy.nvim and have tried the solutions there but for some reason I just can't get it to work. It works just fine with packer.

When running `VimtexInfo` it seems that the settings are not read correctly like continuous is set to `0` while in the config it is `1`.
I use ltex-ls alongside, but I have also used it with packer. Any suggestions?

### Do you use a latexmkrc file?

tested both

### VimtexInfo

```yaml
System info:
  OS: Debian
  Vim version: NVIM v0.9.4
  Has clientserver: true
  Servername: /run/user/1000/nvim.27641.0

VimTeX project: test
  base: test.tex
  root: /home/user/journal
  tex: /home/user/journal/test.tex
  main parser: current file verified
  document class: custom
  packages:  babel biblatex bigintcalc hyperref todonotes
  source files:
    test.tex
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 0
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
