### ISSUE TITLE
Quickfix only gets populated using single shot compilation and at first compilation error of continuous mode

### ISSUE THREAD

**Issue by aabbccddeeffggj** [lervag/vimtex#2847]
### Description

Hi, compilations done within the continuous compilation mode only populates the quickfix list the first time it finds an error, in the subsequent compilations I do not get my quickfix populated.

### Steps to reproduce

1. Have errors, then compile.
2. Check quickfix window, it's populated with the compiler error messages.
3. Have no errors, then compile
4. Check quickfix window, now there's no error messages.
5. Have errors, then compile.
6. Check quickfix window, now there's no error messages, but it should have been populated.

### Expected behavior

Quickfix window always get populated with the compilers errors when there're such.

### Actual behavior

Quickfix window only get populated with the compilers errors when there's such in the first time errors are found.

### Do you use a latexmkrc file?

Yes, it's content is: "$pdf_mode = 4;"

### VimtexInfo

```yaml
System info:
  OS: Arch Linux
  Vim version: NVIM v0.9.4
  Has clientserver: true
  Servername: /run/user/1000/nvim.1349705.0

VimTeX project: tex
  base: tex.tex
  root: /home/user/8-working/tex
  tex: /home/user/8-working/tex/tex.tex
  main parser: current file verified
  document class: book
  packages: amsbsy amsgen amsmath amsopn amstext calc epstopdf-base etoolbox expl3 fix-cm fontenc fontspec fontspec-luatex geometry graphics graphicx iftex ifvtex keyval l3keys2e lualatex-math mathastext mathtools mhsetup trig unicode-math unicode-math-luatex xparse
  compiler: latexmk
    engine: -lualatex
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 5
      output: /tmp/nvim.user/3XoMvB/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode  -lualatex -pvc -pvctimeout- -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'tex.tex'
      pid: 1349740
  viewer: Zathura
    xwin id: 46137347
    cmd_start: zathura  -x "/usr/bin/nvim --headless -c \"VimtexInverseSearch %{line} '%{input}'\"" 'tex.pdf'&
  qf method: LaTeX logfile
```
