### ISSUE TITLE
dynamic build_dir not working after an update

### ISSUE THREAD

**Issue by rgsrepo** [lervag/vimtex#2851]
### Description

Hi,
I recently updated Vimtex after a while. Right after the first compilation I got an error message which I did not really pay attention too. I am practically sure it was related to this issue. The error message does not show up anymore, but the option 
```vim
let g:vimtex_compiler_latexmk = {'build_dir': {-> expand("%:t:r")}}
```
which was described [here](https://github.com/lervag/vimtex/issues/2137) does not work anymore. Has it been removed? 

Thank you and best regards, 
N.

### Steps to reproduce

Compile with pdflatex `\ll`

```vim
let g:vimtex_view_general_viewer = 'SumatraPDF'
let g:vimtex_quickfix_open_on_warning = 0
let g:vimtex_compiler_latexmk = {'build_dir': {-> expand("%:t:r")}}
```

### Do you use a latexmkrc file?

Yes

### VimtexInfo

```yaml
VimTeX project: 1_ensemble_priorite
  base: 1_ensemble_priorite.tex
  root: C:\Users\N\Documents\Enseignement\ens_latex\11e\Series11\Revisions
  tex: C:\Users\N\Documents\Enseignement\ens_latex\11e\Series11\Revisions\1_ensemble_priorite.tex
  main parser: current file verified
  document class: report
  packages: ../coursclasse afterpage ams-mdbch amsbsy amsfonts amsgen amsmath amsopn amssymb amstext appendix arev arevmath arevtext array beramono calc color coursclasse enumitem environ epstopdf-base eso-pic etoolbox expl3 fancybox fancyhdr float fncychap fontawesome5 fontawesome5-generic-helper fontenc framed geometry graphics graphicx icomma ifluatex iftex ifthen ifvtex infwarerr inputenc keyval kvoptions kvsetkeys l3keys2e listings listingsutf8 lscape lstmisc ltxcmds multicol multido niceframe paralist pdfcol pdfescape pdflscape pdfpages pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfplots pgfrcs pgfsys psfrag pst-3d pst-calculate pst-circ pst-math pst-node pst-plot pst-xkey pstricks pstricks-add refcount shellesc siunitx stringenc systeme tasks tcolorbox textcomp tikz tikz-3dplot tikz-cd titlesec tkz-euclide translations trig trimspaces verbatim version xcolor xfp xkeyval xparse xstring xtemplate
  compiler: latexmk
    engine: -pdflatex
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: process 19708 run
      output: C:/Users/N/AppData/Local/Temp/VP5F7D3.tmp
      cmd: set max_print_line=2000 & latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode  -pdflatex -pvc -pvctimeout- -view=none -e "$compiling_cmd = ($compiling_cmd ? $compiling_cmd . ' & ' : '') . 'echo vimtex_compiler_callback_compiling'" -e "$success_cmd = ($success_cmd ? $success_cmd . ' & ' : '') . 'echo vimtex_compiler_callback_success'" -e "$failure_cmd = ($failure_cmd ? $failure_cmd . ' & ' : '') . 'echo vimtex_compiler_callback_failure'" "1_ensemble_priorite.tex"
      pid: 19708
  viewer: General
    job: 
      pid: 23416
      cmd: SumatraPDF -reuse-instance -forward-search "C:\Users\N\Documents\Enseignement\ens_latex\11e\Series11\Revisions\1_ensemble_priorite.tex" 30 "C:\Users\N\Documents\Enseignement\ens_latex\11e\Series11\Revisions/1_ensemble_priorite.pdf"
  qf method: LaTeX logfile
```
