### ISSUE TITLE
Can't open file with an empty name

### ISSUE THREAD

**Issue by paulecode** [lervag/vimtex#2853]
### Description

Hello,

Compiling `.tex` files in terminal with `latexmk` works, but in my nvim upon running `:VimtexCompile` it simply says `E482: Can't open file with an empty name`. The most confusing part of it all is that LazyVim (the distro) gets the same error BUT still compiles it somehow. 

My `vimtex.lua`:

```lua
return {
    "lervag/vimtex",
    lazy = false
}
```

The test file I am trying to compile is also nothing fancy:

```tex
\documentclass{article}
\title{"Test Document"}
\author{"Your Name"}
\date{\today}

\begin{document}
\maketitle

\section{Introduction}
This is a test document created for testing VimTeX functionality.

\section{Mathematics}
Here is an equation: $E=mc^2$.

\section{Lists}
\begin{itemize}
  \item Item 1
  \item Item 2
  \item Item 3
\end{itemize}

\section{Conclusion}
Testing complete. This is the end of the document.

\end{document}
```

So I'd argue this is not the problem either. I have tried using different files, with different names in different location to exclude permission hick ups etc. I can't find anything upon googling this error. I'm using lazy.nvim as a plugin manager and it seems to load just fine, since I can run `:VimtexInfo` in `.tex` files.

If any information necessary to help me here is still missing, please let me know and I'll add it.

### Steps to reproduce

1. `nvim main.tex`
2. `\ll`

### Expected behavior

The document to compile

### Actual behavior

I get `E482: Can't open file with an empty name`, and it does not compile.

```
Error detected while processing function vimtex#compiler#compile[6]..vimtex#compiler#start[17]..53:
line    6:
E482: Can't open file with an empty name
```

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
      OS: macOS 14.2 (23C64)
      Vim version: NVIM v0.9.4
      Has clientserver: true
      Servername: undefined (vim started without --servername)
    
    VimTeX project: main
      base: main.tex
      root: /Users/paul/Development/tmp/Playground/Latex/vimtex
      tex: /Users/paul/Development/tmp/Playground/Latex/vimtex/main.tex
      main parser: current file verified
      document class: article
      compiler: latexmk
        engine: -pdf
        options:
          -verbose
          -file-line-error
          -synctex=1
          -interaction=nonstopmode
        callback: 1
        continuous: 1
        executable: latexmk
      viewer: General
      qf method: LaTeX logfile
```
