### ISSUE TITLE
Indentation problem with matrix in align environment

### ISSUE THREAD

**Issue by Arfs6** [lervag/vimtex#2857]
### Description

Indentation doesn't reduce after closing a matrix environment in an align environment. This is the case while writing or when using the `=` to manually fix it.

### minimal.lua

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
vim.opt.rtp:prepend(lazypath)
require("lazy").setup({"lervag/vimtex"})
```
### minimal.tex

```latex
\begin{align}
	X &= \begin{bmatrix}
		2 + 9 & 11 + 5\\
		6 + 1 & 0 + 8\\
	\end{bmatrix}\\
	\end{align}
```
### steps

1. Go to the first line: `gg`
2. Type `=G` to fix indentation of the whole file.

### Expected behavior

The `\end{bmatrix}` and `\end{align}` lines shouldn't be indented.

### Actual behavior

The `\end{bmatrix}` and `\end{align}` are still indented.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 22.04.2 LTS
  Vim version: NVIM v0.9.2
  Has clientserver: true
  Servername: /mnt/wslg/runtime-dir/nvim.3983.0

VimTeX project: minimal
  base: minimal.tex
  root: /tmp
  tex: /tmp/minimal.tex
  main parser: fallback current file
  document class: 
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    out_dir: /tmp/tex/out
    aux_dir: /tmp/tex/aux
    callback: 1
    continuous: 1
    executable: latexmk
  qf method: LaTeX logfile
```
