### ISSUE TITLE
Error using arara as compiler-method

### ISSUE THREAD

**Issue by mms-neuro** [lervag/vimtex#2861]
### Description

Using arara as a compile_method suddenly broke down a few months ago. `:VimtexCompile` now results in an error - on different computers with different tex-files. 

### Steps to reproduce

Somehow, github does not like `.vim`/`.tex` files (anymore?).
So here the content:

`cat minimal.tex`

```tex
% arara: lualatex
\documentclass{minimal}
\begin{document}
Hello world!
\end{document}
```

`cat minimal.vim`

```vim
filetype plugin indent on
syntax on
call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex'
let g:vimtex_compiler_method = 'arara'
call plug#end()
```

arara has version 7.0.4 (latest on Fedora 38, but not latest in general). 

Steps to reproduce: 
1. Run `nvim -u minimal.vim minimal.tex` in bash
2. Execute `:VimtexCompile` in neovim.

### Expected behavior

Document compiles using arara. 

### Actual behavior

The following error is raised immediately:
```
Fehler beim Ausführen von "function vimtex#compiler#compile[6]..vimtex#compiler#start[17]..38[10]..52":
Zeile    1:
E714: List benötigt
```
Sorry - I couldn't change the language from German to English. The translation is:
```
Error while executing "function vimtex#compiler#compile[6]..vimtex#compiler#start[17]..38[10]..52":
Line   1:
E714: List required
```

* Calling arara directly in neovim (`:!arara %`) works perfectly fine.
* Changing the compile-method to latexmk (`let g:vimtex_compiler_method = 'latexmk'`) results also in error-free behaviour.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Fedora release 38 (Thirty Eight)
  Vim version: NVIM v0.9.4
  Has clientserver: true
  Servername: /run/user/1000/nvim.56974.0

VimTeX project: minimal
  base: minimal.tex
  root: /home/matthiasms
  tex: /home/matthiasms/minimal.tex
  main parser: current file verified
  document class: minimal
  compiler: arara
    options:
      --log
  viewer: General
  qf method: LaTeX logfile
```
