### ISSUE TITLE
Arabic text is concealed when indented

### ISSUE THREAD

**Issue by avidseeker** [lervag/vimtex#2867]
### Description

Arabic text is concealed when it is indented and vim is in Arabic mode.

### Steps to reproduce

1. Paste this in a latex vim buffer
```tex
\documentclass{article}

\begin{document}
	تجربة كتابة عربية
\end{document}
```
2. Indent the inside of \begin{document}
3. Change direction: `:set arabic`

### Actual behavior

This results in hidden Arabic text.

### Do you use a latexmkrc file?

N/A

### VimtexInfo

```yaml
System info:
  OS: Linux 6.5.9
  Vim version: NVIM v0.9.5
  Has clientserver: true
  Servername: /run/user/1000/nvim.87686.0
```
