### ISSUE TITLE
Partial concealment of symbols

### ISSUE THREAD

**Issue by mrbertp** [lervag/vimtex#2868]
### Description

I am new to vimtex, so I apologize in advance if I ask for something that has been already solved or if it is trivial.

I have installed vimtex with vim-plug in vim and I can see concealment for some elements, such as turning invisible the `$` and `$$` (inline and multi-line math environment boundaries) and correct conversion of some latex symbols (e.g. `\cap` -> ∩). The problem is that some other symbols are not concealed, such as `\in` that does not convert to `ϵ` or `\implies` that does not convert to `⟹`, among others...

I have also installed `latexmk` package through `sudo apt install`.

Here is my `.vimrc`:

```vim
" Basics
set t_u7=
syntax enable
color default
set number
set showcmd
set title
set shell=/usr/bin/bash
set mouse=a
set viminfo='100,<1000,s100,h,<100
set backspace=indent,eol,start
set encoding=utf8
filetype plugin indent on

" ...

" -- vim pluggins --
call plug#begin('~/.vim/plugged')
" - vimtex -
Plug 'lervag/vimtex'
let g:tex_flavor='latex'
let g:vimtex_view_method='zathura'
let g:vimtex_quickfix_mode=1
set conceallevel=2
let g:tex_conceal='abdmg'
" - ultisnips -
Plug 'SirVer/ultisnips'
let g:UltiSnipsExpandTrigger = '<tab>'
let g:UltiSnipsJumpForwardTrigger = '<tab>'
let g:UltiSnipsJumpBackwardTrigger = '<s-tab>'
let g:UltiSnipsEditSplit = 'vertical'
call plug#end()
hi clear Conceal
```

I attach an image of how my .tex code looks like:

`$$` boundary shows up if I place the cursor on that line (ok), but the symbols on the line below are only partially concealed.

![image](https://github.com/lervag/vimtex/assets/49736270/93405253-e7b0-4866-b5b7-225d94c47739)

When I place the cursor on that line, you can see the symbols as they are written.

![image](https://github.com/lervag/vimtex/assets/49736270/04b83935-c1c5-4c97-a408-d1327cf39ea8)

Thank you very much for the plugin.

### Steps to reproduce

1. Install vimtex (add it with vim-plug in the `.vimrc`)
2. Configure `.vimrc` file as indicated above
3. Open .tex file with vim and write example code indicated above

### Expected behavior

All symbols and boundaries should be concealed (converted to actual symbol or made invisible, respectively) when the cursor is not on the line containing these symbols or boundaries. These should not be concealed and shown as they are written when the cursor is on the line.

### Actual behavior

Math environment boundaries and only some symbols are concealed, but other symbols are not concealed.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Linux 4.4.0-19041-Microsoft
  Vim version: VIM 9.1 (1-15)
  Has clientserver: true
  Servername: undefined (vim started without --servername)

VimTeX project: rel_equ
  base: rel_equ.tex
  root: /mnt/c/Users/Bert/Desktop/gutemberg/raw/notes/mathematics2
  tex: /mnt/c/Users/Bert/Desktop/gutemberg/raw/notes/mathematics2/rel_equ.tex
  main parser: fallback current file
  document class: 
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
