### ISSUE TITLE
Automatically source syntax highlight changes for vimtex highlight groups

### ISSUE THREAD

**Issue by omuhr** [lervag/vimtex#2871]
### Description

This is more of a tech support question than an issue. Sorry if asking this here is inappropriate but I couldn't find any community dedicated to vimtex.

I'm using[ 'blazkowolf/gruber-darker.nvim'](https://github.com/blazkowolf/gruber-darker.nvim) as a colorscheme and was unhappy with how it highlighted vimtex groups. I've reassigned the colors for each vimtex highlight group using `vim.api.nvim_set_hl()` in a lua file.

Sourcing the file when editing a .tex file works and I'm happy with the results. When trying to figure out how to automatically enable my new settings I run into problems.

It seems I'm not able to apply the settings in a nvim instance without having already had a .tex file open previously, presumably the highlight groups aren't created until vimtex loads?

I tried setting up a autocmd for .tex files where i source the .lua file, using `vim.api.nvim_command('so ..')` but it seems this runs before vimtex and doesn't work. It does work when first opening a .tex file and then switching to another .tex, since vimtex has already loaded at that point I assume.

The only relevant code being executed in the lua file is some version of:

```lua
vim.api.nvim_set_hl(0, 'texComment', {
    fg = '#cc8c3c',
    italic = true,
})
```

Any ideas on a good way to implement this configuration?

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: DESKTOP-KSQQED4 (Microsoft Windows 10 Pro)
  Vim version: NVIM v0.9.5
  Has clientserver: true
  Servername: \\.\pipe\nvim.21376.0

VimTeX project: text
  base: text.tex
  root: ...
  tex: ...
  main parser: fallback current file
  document class: 
  compiler: latexmk
    engine: -lualatex
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    out_dir: ./out
    aux_dir: ./tmp
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: sioyek
  qf method: LaTeX logfile
```
