### ISSUE TITLE
citekey autofill not working with \Volcite and \volcite when using correct biblatex syntax

### ISSUE THREAD

**Issue by alexandreroberts** [lervag/vimtex#2878]
### Description

This is closely related to the [feature request](https://github.com/lervag/vimtex/issues/2875) I recently made:

When I type `<C-x><C-o>` in the citekey field of cite commands of the form `\volcite{1}[23]{w}` and `\Volcite{1}[23]{w}` (in insert mode, with cursor after the `w`), the expected citekey autofill menu does not pop up. It only works when I omit the mandatory volume number argument.

I suspect that while the highlighting issue raised in my feature request was fixed, there is another change necessary to make the autofill work.

### Steps to reproduce

nvim -u test.vim main.tex

main.tex:

```tex
%!TEX TS-program = xelatex
%!TEX encoding = UTF-8 Unicode

% Normal:
\documentclass[12pt,article,draft]{memoir}

\usepackage{biblatex-chicago}
\addbibresource{biblatex-examples.bib}

\begin{document}

\volcite{1}[23]{w}

\volcite[23]{w} 

\end{document}
```

test.vim:

```vim
set nocompatible 
set mmp=5000

call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex'
call plug#end()

set spell
```

### Expected behavior

The menu should pop up in both cases.

### Actual behavior

It only does when the biblatex syntax is *incorrect*.

### Do you use a latexmkrc file?

yes (but it is not relevant)

### VimtexInfo

```yaml
System info:
  OS: macOS 13.2 (22D49)
  Vim version: NVIM v0.9.4
  Has clientserver: true
  Servername: /var/folders/92/6c80fs_55hnf_1s2ybgbv5c40000gn/T/nvim.robe941/0BlfjY/nvim.50469.0

VimTeX project: main
  base: main.tex
  root: /Users/robe941/Google Drive/tex-issues-and-MWEs/vimtex-volcite-citekeyAutofill
  tex: /Users/robe941/Google Drive/tex-issues-and-MWEs/vimtex-volcite-citekeyAutofill/main.tex
  main parser: current file verified
  document class: memoir
  packages: biblatex-chicago
  compiler: latexmk
    engine: -xelatex
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
