### ISSUE TITLE
zathura_simple on wayland not outputting pdf

### ISSUE THREAD

**Issue by pyfb78** [lervag/vimtex#2880]
### Description

I am trying to use Zathura on my manjaro linux setup which uses wayland. I have use put `zathura_simple` as my view method and while vimtex is able to compile my document, it is not able to actually give me a pdf output for me to see it. 

### Steps to reproduce

minimal init.vim

```
let g:vimtex_view_method = 'zathura_simple'
```

Go to any random latex document, mine is `poop.tex`
```
\documentclass{article}

\begin{document}
hi
\end{document}
```

Compile it using `:VimtexCompile`. 

### Expected behavior

I expect it to have a pdf show up in zathura so that I can see my edits in live time.

### Actual behavior

When the following steps are followed on my system, nothing comes up and all I have is `VimTex: Compilation Complete` at the bottom of my vim. 

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Manjaro Linux
  Vim version: NVIM v0.9.5
  Has clientserver: true
  Servername: /run/user/1000/nvim.35723.0

VimTeX project: poop
  base: poop.tex
  root: /home/daddy
  tex: /home/daddy/poop.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 8
      output: /tmp/nvim.daddy/9GtxsR/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode  -pdf -pvc -pvctimeout- -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'poop.tex'
      pid: 35807
  viewer: Zathura
    cmd_start: zathura  -x "/usr/bin/nvim --headless -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 3:1:'/home/daddy/poop.tex' 'poop.pdf'&
  qf method: LaTeX logfile
```
