### ISSUE TITLE
Contents on Zathura are not recoganizable when doing forward search if the cursor stays on an equation environment

### ISSUE THREAD

**Issue by sierxue** [lervag/vimtex#2881]
### Description

I'm using gVim 9 and Zathura on Ubuntu 20.04.

If my cursor stays on an inline math expression on gVim, I can see the corresponding contents on Zathura clearly when I do a forward search (\lv), as shown in the following screenshot.

![Screenshot from 2024-02-04 20-23-44](https://github.com/lervag/vimtex/assets/19348230/b7d82a8e-d3b3-4050-9f41-901f00a93e9a)

If my cursor stays on an equation on gVim, the corresponding contents on Zathura are not recognizable when I do a forward search (\lv), as shown in the following screenshot.

```
\begin{equation*}
  \lim_{B\to\infty}\hat{G}^B(t) = \hat{G}(t).
\end{equation*}
```

![image](https://github.com/lervag/vimtex/assets/19348230/66de4227-3f22-44ed-ae6e-54fc8854b3c4)

My vimrc settings:
```
let g:tex_flavor = 'latex'
let g:vimtex_view_general_options
    \ = '-reuse-instance -forward-search @tex @line @pdf'
let g:vimtex_syntax_enabled=1
let g:vimtex_view_enabled=1
let g:vimtex_compiler_latexmk = {
      \ 'build_dir': 'output',
      \ 'options' : [
      \   '-auxdir=aux',
      \   '-verbose',
      \   '-file-line-error',
      \   '-synctex=1',
      \   '-interaction=nonstopmode',
      \   '-shell-escape',
      \ ],
      \}
let g:vimtex_view_method = 'zathura'
```

### Do you use a latexmkrc file?

Yes

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 20.04.6 LTS
  Vim version: VIM 9.0 (1-749)
  Has clientserver: true
  Servername: GVIM

VimTeX project: sddsp
  base: sddsp.tex
  root: /media/a/home/Documents/repo-research/sddsp
  tex: /media/a/home/Documents/repo-research/sddsp/sddsp.tex
  main parser: current file verified
  document class: article
  packages: algcompatible algorithm algorithmicx algpseudocode amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm array atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook bbm bigintcalc bitset booktabs calc caption caption3 color colortbl comment datetime2 diagbox empheq enumitem epsfig epstopdf-base etexcmds etoolbox fancyhdr float geometry gettitlestring graphics graphicx hycolor hyperref iftex ifthen ifvtex indentfirst infwarerr intcalc keyval kvdefinekeys kvoptions kvsetkeys letltxmacro ltxcmds makecell mathrsfs mathtools mhsetup multirow nameref natbib pdfescape pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfrcs pgfsys pict2e refcount rerunfilecheck soul subcaption tabularx tikz todonotes tracklang trig ulem uniquecounter url xargs xcolor xkeyval xspace yhmath
  compiler: latexmk
    engine: -pdf
    options:
      -auxdir=aux
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
      -shell-escape
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: process 44464 run
      output: /tmp/v5i6Qg4/1
      cmd: max_print_line=2000 latexmk -auxdir=aux -verbose -file-line-error -synctex=1 -interaction=nonstopmode -shell-escape  -pdf -pvc -pvctimeout- -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'sddsp.tex'
      pid: 44464
  viewer: Zathura
    xwin id: 77594627
    cmd_forward_search: zathura --synctex-forward 554:27:'/media/a/home/Documents/repo-research/sddsp/sddsp.tex' 'sddsp.pdf'&
    cmd_start: zathura  -x "/usr/bin/vim.gtk3 -T dumb --not-a-term -n -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 554:2:'/media/a/home/Documents/repo-research/sddsp/sddsp.tex' 'sddsp.pdf'&
  qf method: LaTeX logfile
```
