### ISSUE TITLE
Synctex doesn't work properly on Mac (Zathura or Skim)

### ISSUE THREAD

**Issue by rltyty** [lervag/vimtex#2889]
### Description

Nvim + vimtex + Zathura once worked fine in my mac. However recently, after I upgraded system and switch to Nvim + lazy.nvim, they don't work properly now. I tried not to use lazy features for Vimtex after I read the help doc. I also tried to use minimal.vim, the problem still exists.

The current status is after I type `<leader>ll` or `<leader>lv`, it can open Zathura/Skim to display the PDF. But the sync doesn't work as expected.

For Zathura (which I mainly use), it reports "VimTex: Viewer cannot find Zathura window ID!" I already read related issues in history. Basically, the issue still exists, which is xdotool can find no id of zathura. So I switch the method to "zathura_simple", then the error disappears as expected. Now here are the sync problems:

1. Forward search is not automatic/continuous. I remember the viewer (Zathura) was able to focus on the point where the cursor was at in the tex file being edited. However, now, I have to manually trigger the forward search by type `<leader>lv` every time. I mean it can sync, but not continuously/automatically.

2. Inverse search doesn't work at all. the cursor is not able to relocate in the editor after I select/click the text here and there in the pdf viewer Zathura.

If you could shed some light on this, I would really appreciate. Thanks in advance.

### Steps to reproduce

`:checkhealth vimtex`

```
VimTeX ~
- OK Vim version should have full support!
- OK Zathura should work properly!
- OK Compiler should work!
```

nvim Lua configuration

```lua
{
    'lervag/vimtex',
    config = function()
        vg.vimtex_view_method = 'zathura_simple'
        -- vg.vimtex_view_method = 'skim'
    end,
    enabled = vg.vimrclevel > 3
},
```

### Do you use a latexmkrc file?

`~/.latexmkrc`

```perl
push @generated_exts, "cb";
push @generated_exts, "cb2";
push @generated_exts, "spl";
push @generated_exts, "nav";
push @generated_exts, "snm";
push @generated_exts, "tdo";
push @generated_exts, "nmo";
push @generated_exts, "brf";
push @generated_exts, "nlg";
push @generated_exts, "nlo";
push @generated_exts, "nls";
push @generated_exts, "synctex.gz";
push @generated_exts, "run.xml";

$pdflatex = "xelatex -synctex=1 %O %S";
$pdf_mode = 5;
$dvi_mode = 0;
$postscript_mode = 0;
```

### VimtexInfo

```yaml
System info:
  OS: macOS 12.7.2 (21G1974)
  Vim version: NVIM v0.9.5
  Has clientserver: true
  Servername: /var/folders/2k/r2yhqxdj0d54j8k7_wp94xj80000gn/T/nvim.rabbit/w5G7fI/nvim.20856.0

VimTeX project: cv
  base: cv.tex
  root: /Users/rabbit/Documents/sci/cv
  tex: /Users/rabbit/Documents/sci/cv/cv.tex
  main parser: current file verified
  document class: article
  packages: atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook bigintcalc bitset enumitem etexcmds etoolbox expl3 fontenc fontspec fontspec-xetex geometry gettitlestring hycolor hyperref iftex ifvtex infwarerr intcalc keyval kvdefinekeys kvoptions kvsetkeys letltxmacro ltxcmds nameref parskip pdfescape pdftexcmds refcount rerunfilecheck stringenc uniquecounter url xcolor xparse
  compiler: latexmk
    engine: -xelatex
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 7
      output: /var/folders/2k/r2yhqxdj0d54j8k7_wp94xj80000gn/T/nvim.rabbit/w5G7fI/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode  -xelatex -pvc -pvctimeout- -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'cv.tex'
      pid: 20860
  viewer: Zathura
    cmd_start: zathura  -x "/Users/rabbit/rmac.local/neovim/bin/nvim --headless -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 57:8:'/Users/rabbit/Documents/sci/cv/cv.tex' 'cv.pdf'&
  qf method: LaTeX logfile
```

**Comment by lervag** [comment]
> I tried not to use lazy features for Vimtex after I read the help doc.

To be honest, my current thought is that you are still lazy loading VimTeX. So let's start by looking at that.

> I also tried to use minimal.vim, the problem still exists.

_Which_ `minimal.vim`? If you can reproduce your problem with a proper `minimal.vim` file, then there is no reason to discuss your _real_ configuration. Instead, you should post the minimal config and the steps you use to reproduce.

> 1. Forward search …
> 2. Inverse search doesn't work at all. …

This sure _sounds_ like a lazy loading issue...

> ```lua
> {
>     'lervag/vimtex',
>     config = function()
>         vg.vimtex_view_method = 'zathura_simple'
>         -- vg.vimtex_view_method = 'skim'
>     end,
>     enabled = vg.vimrclevel > 3
> },
> ```

Please change `config` to `init`. Also, what's the point of `enabled = vg.vimrclevel > 3`?

And, important: Do you perhaps have a global lazy load option for lazy.nvim enabled? In other words, what is your configuration of lazy.nvim itself?

What happens if you run this from a terminal?

`/Users/rabbit/rmac.local/neovim/bin/nvim --headless -c "VimtexInverseSearch 25 '/Users/rabbit/Documents/sci/cv/cv.tex'"`

**Comment by rltyty** [comment]
> ... you are still lazy loading VimTeX

"I tried not to use lazy features" actually means I removed my personal key map which had been set using `keys` attribute, which caused almost all Vimtex commands to disappear, since the `keys` in lazy.nvim plugin spec is a trigger of lazy load. 

I don't think my current situation is about lazy load, because `:Lazy` shows Vimtex is loaded after start.

I also tried to switch `config` to `init`, the problems are still there.

>  what's the point of `enabled = vg.vimrclevel > 3`

`vim.g.vimrclevel` is my personal Vim running level option, 5(default). This is an old simple way to control plugin load in different situations.

>  Do you perhaps have a global lazy load option for lazy.nvim enabled?

No. Just default settings.

> Which `minimal.vim`?

The one suggested in the Issue template.

```vim
set nocompatible
let &runtimepath  = '~/.vim/bundle/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable
" Add relevant options and VimTeX configuration below.

let g:vimtex_view_method = 'zathura_simple'
```

The problems can still reproduce when I run

```
vim -u minimal.vim /Users/rabbit/Documents/sci/cv/cv.tex
```

> What happens if you run this from a terminal?
> 
> /Users/rabbit/rmac.local/neovim/bin/nvim --headless -c "VimtexInverseSearch 25 '/Users/rabbit/Documents/sci/cv/cv.tex'"

The cursor jumps to L25 in the Vim buffer.




P.S., there is a LaTeX Font Warning during compilation (`<leader>ll`) I forgot to mention in my OP.  I didn't think it matters.

`Users/rabbit/Documents/sci/cv/cv.tex|| LaTeX Font Warning: Font shape `TU/KaitiSC(0)/b/n' undefined using `TU/KaitiSC(0)/m/n' instead on input line 24.`

**Comment by lervag** [comment]
> I don't think my current situation is about lazy load, because `:Lazy` shows Vimtex is loaded after start.

Ok, good!

> I also tried to switch `config` to `init`, the problems are still there.

Ok; but notice that you should still keep this change. VimTeX assumes that the options are defined before you load it, and I've found that `config` sometimes messes with this assumption.

> > Which `minimal.vim`?
> 
> The one suggested in the Issue template.
> 
> ```viml
> set nocompatible
> let &runtimepath  = '~/.vim/bundle/vimtex,' . &runtimepath
> let &runtimepath .= ',~/.vim/bundle/vimtex/after'
> filetype plugin indent on
> syntax enable
> " Add relevant options and VimTeX configuration below.
> 
> let g:vimtex_view_method = 'zathura_simple'
> ```

Ok; can we continue the thread using this `minimal.vim`?

> The problems can still reproduce when I run
> 
> ```
> vim -u minimal.vim /Users/rabbit/Documents/sci/cv/cv.tex
> ```

Ok, so the problem persists regardless of whether you are using Vim or neovim? Notice, though, you should use `vim --clean -u minimal.vim ...`; the `--clean` ensures that you don't load any config from your personal runtimepath. Same if you use `nvim`.

> > What happens if you run this from a terminal?
> > /Users/rabbit/rmac.local/neovim/bin/nvim --headless -c "VimtexInverseSearch 25 '/Users/rabbit/Documents/sci/cv/cv.tex'"
> 
> The cursor jumps to L25 in the Vim buffer.

Good, that asserts that you are not lazy loading.

> P.S., there is a LaTeX Font Warning during compilation (`<leader>ll`) I forgot to mention in my OP. I didn't think it matters.

You are right, this is not relevant.

----

Now, I believe the next step for going in depth here is to have a proper LaTeX
test file. I.e., instead of your `cv.tex`, create a minimal LaTeX file such as

```tex
\documentclass{minimal}
\begin{document}
Hello World!

\newpage

Hello Moon!
\end{document}
```

Given `minimal.vim` and `mwe.tex`, you can do `nvim --clean -u minimal.vim mwe.tex`, then:

1. `\ll` to start compilation - does it work as expected? Do the viewer open automatically?

2. Test `\lv` - does it perform the forward sync?

3. Does inverse sync work? (I assume no, as we didn't really change anything yet.)

**Comment by lervag** [comment]
Also, just to be fully sure, could you comment out the config in your `.latexmkrc` file while we test things?

**Comment by rltyty** [comment]
After remove ~/.latexmkrc, and run with `nvim --clean -u minimal.vim mwe.tex`

1. `\ll` compilation works as expected and open the viewer automatically.
2.  If put the cursor on "Hello Moon!" and then `\lv`, it performs forward sync, Zathura scroll to the next page with "Hello Moon!" line highlighted.
3. Inverse sync doesn't work.

**Comment by lervag** [comment]
Ok, so things work except inverse sync. Can you post the output of `:VimtexInfo` after step 2? There's a command there that I want you to run from a terminal to see if there are error messages. Something like this:

```sh
zathura  -x "nvim --headless -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 57:8:'mwe.tex' 'mwe.pdf'&
```

Now, if you run that command (modified to match what you find in `:VimtexInfo`) after you've closed the initial window - what happens if you do inverse sync?

**Comment by rltyty** [comment]
```yaml
System info:
  OS: macOS 12.7.2 (21G1974)
  Vim version: NVIM v0.9.5
  Has clientserver: true
  Servername: /var/folders/2k/r2yhqxdj0d54j8k7_wp94xj80000gn/T/nvim.rabbit/ehpwhg/nvim.26189.0

VimTeX project: mwe
  base: mwe.tex
  root: /Users/rabbit/tmp/test
  tex: /Users/rabbit/tmp/test/mwe.tex
  main parser: current file verified
  document class: minimal
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 5
      output: /var/folders/2k/r2yhqxdj0d54j8k7_wp94xj80000gn/T/nvim.rabbit/ehpwhg/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode  -pdf -pvc -pvctimeout- -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'mwe.tex'
      pid: 26190
  viewer: Zathura
    cmd_start: zathura  -x "/Users/rabbit/rmac.local/neovim/bin/nvim --headless -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 7:1:'/Users/rabbit/tmp/test/mwe.tex' 'mwe.pdf'&
  qf method: LaTeX logfile

```


> run that command (modified to match what you find in :VimtexInfo) after you've closed the initial window 

I'm not sure what do you mean by "the initial window", you mean the initial viewer window?

I closed the viewer zathura window. and run

```shell
$ zathura  -x "/Users/rabbit/rmac.local/neovim/bin/nvim --headless -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 7:1:'/Users/rabbit/tmp/test/mwe.tex' 'mwe.pdf'&
[1] 26555
 ~/tmp/test                                                           
$ warning: Unknown option: best-fit
```

It opens Zathura and do the forward sync to the 2nd page "Hello Moon!" which is as expected.

Then when I click "Hello World!" on the 1st page in Zathura, nothing happened. No error output from the terminal.
No cursor jump in the editor. In Zathura, it says: "Copied selected text to selection clipboard: Hello World!"
