### ISSUE TITLE
VimTex not working when configured to load on "event = "BufEnter *.tex"" in Lazy.nvim

### ISSUE THREAD

**Issue by Jihillestad** [lervag/vimtex#2890]
### Description

VimTex not working when configured to load on "event = "BufEnter *.tex"" in Lazy.nvim. If loaded on startup without the event clause, everything works fine.

return {
  "lervag/vimtex",
  event = "BufEnter *.tex",
  init = function()
    vim.g.vimtex_view_method = "skim"
    vim.g.vimtex_skim_sync = 1
    vim.g.vimtex_skim_activate = 1
  end,
}

### Steps to reproduce

The code below is from my vimtex.lua file in my nvim config folder:

```lua
return {
  "lervag/vimtex",
  event = "BufEnter *.tex",
  init = function()
    vim.g.vimtex_view_method = "skim"
    vim.g.vimtex_skim_sync = 1
    vim.g.vimtex_skim_activate = 1
  end,
}
```

### Expected behavior

Vimtex is loaded when a .tex file is opened in NVIM.

### Actual behavior

Lazy shows that VimTex is loaded, but the plugin is not responding. Everything works fine when vimtex.lua does not have the event clause.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 13.3.1 (22E772610a)
  Vim version: NVIM v0.9.5
  Has clientserver: true
  Servername: NOT_DISCLOSED

VimTeX project: NOT_DISCLOSED
  base: NOT_DISCLOSED.tex
  root: /Users/NOT_DISCLOSED/projects/latex/test
  tex: /Users/NOT_DISCLOSD/projects/latex/test/NOT_DISCLOSED.tex
  main parser: current file verified
  document class: moderncv
  packages: array arydshln atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook bigintcalc bitset calc color colortbl epstopdf-base etoolbox expl3 fancyhdr fontawesome5 fontawesome5-generic-helper geometry gettitlestring graphics graphicx hycolor hyperref iftex ifthen ifvtex infwarerr inputenc intcalc keyval kvdefinekeys kvoptions kvsetkeys l3keys2e letltxmacro ltxcmds microtype moderncvbodyi moderncvcollection moderncvcolorred moderncvcompatibility moderncvfooti moderncvheadii moderncviconsawesome moderncviconssymbols moderncviconstikz moderncvskillmatrix moderncvstylecasual multirow nameref pdfescape pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfrcs pgfsys refcount rerunfilecheck tikz trig tweaklist uniquecounter url xcolor xparse
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Skim
  qf method: LaTeX logfile
```
