### ISSUE TITLE
What is warnings.pm?

### ISSUE THREAD

**Issue by Dorima1** [lervag/vimtex#2891]
### Description

![image](https://github.com/lervag/vimtex/assets/83615435/b588ab65-540d-49e4-ab70-737640c9f3fc)
I am using neovim and texlive and I cannot compile. I don't understand why. Any help is appreciated.

### Expected behavior

I expect to compile. PDF pop up.

### Actual behavior

Instead, I get nothing. I get this instead
![image](https://github.com/lervag/vimtex/assets/83615435/1178a49e-2e18-44ba-b54c-31bffc87b2b0)
And even running latexmk, I get the same issue. Can someone help me please?

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 20.04.6 LTS
  Vim version: NVIM v0.9.5
  Has clientserver: true
  Servername: /run/user/1000/nvim.33469.0

VimTeX project: comp232problems
  base: comp232problems.tex
  root: /home/dreamer/Documents/Concordia/Semesters/Winter 2024/COMP 232/Textbook/Problems
  tex: /home/dreamer/Documents/Concordia/Semesters/Winter 2024/COMP 232/Textbook/Problems/comp232problems.tex
  main parser: current file verified
  document class: scrartcl
  packages: amsmath amssymb amsthm enumitem fancyhdr geometry inputenc parskip
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
