### ISSUE TITLE
Mainfile detection fails when \input is in enumerate environment

### ISSUE THREAD

**Issue by t-ye** [lervag/vimtex#2895]
### Description

`main.tex`:

```vim
\documentclass{article}
\begin{document}
\begin{enumerate}
  \item \input{file.tex}
\end{enumerate}
\end{document}
```

`file.tex`:

```tex
Hello world!
```

### Steps to reproduce

1. Compile (`\ll`) from `main.tex`
2. Compile from `file.tex`

### Expected behavior

Successful compilation with PDF `Hello world!`

### Actual behavior

Compiling in `file.tex` results in an error:

```
VimTeX: Compilation error due to failed mainfile detection!
        Please ensure that VimTeX can locate the proper main .tex file.
        Read ":help vimtex-multi-file" for more info.
```

(I have tried setting `b:vimtex_main` and specifying the TeX root directive in `file.tex`, to no avail.)

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 22.04.2 LTS
  Vim version: VIM 8.2 (1-579, 1969, 580-1848, 4975, 5016, 5023, 5072, 2068, 1849-1854, 1857
  Has clientserver: true
  Servername: VIM

VimTeX project: file
  base: file.tex
  root: (...)
  tex: (...)
  main parser: fallback current file
  document class:
  compiler: latexmk
    engine: -pdf
    options:  -verbose  -file-line-error  -synctex=1  -interaction=nonstopmode
    out_dir: build
    aux_dir: aux
    callback: 1
    continuous: 1
    executable: latexmk
    job:
    jobid: process 271896 dead
    output: /tmp/vdt7z20/1
    cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=non
    pid: 271896
  viewer: General
  qf method: LaTeX logfile
```
