### ISSUE TITLE
Wrong TeXMathZone result from `vimtex#syntax#stack()`

### ISSUE THREAD

**Issue by pilgrimlyieu** [lervag/vimtex#2900]
### Description

Wrong TeXMathZone result from `vimtex#syntax#stack()`

### Steps to reproduce

I've disabled all plugins except for VimTeX with no settings and can reproduce it.

1. Open a new TeX file
2. Type `$  $` and put the cursor in the middle (`$ | $`)
3. Press <kbd>Ctrl</kbd> + <kbd>R</kbd> and input `=vimtex#syntax#stack()`
4. The result is `texMathZoneX`

However, it [should have `texMathZoneTI`](https://github.com/lervag/vimtex/blob/master/doc/vimtex.txt#L5080), shouldn't it? Or else `vimtex#syntax#in('texMathZone[LT]I')` for detecting Inline-Math scope will not work.

The same situation happens to `$$ | $$` `\( | \)` `\[ | \]` too(`Y` `V` `W` respectively).

### Expected behavior

`texMathZoneTI` `texMathZoneTD` `texMathZoneLI` `texMathZoneLD` respectively.

### Actual behavior

As mentioned above.

Something may be relevant to this issue.

To use powerful functions in VimTeX, I've put `markdown.vim` in `~/.vim/plugged/vimtex/after/ftplugin`, and its part of content is shown below.

```vim
call vimtex#options#init()
call vimtex#syntax#core#init_options()
call vimtex#syntax#core#init_rules()
call vimtex#syntax#core#init_highlights()
call vimtex#text_obj#init_buffer()
call vimtex#text_obj#targets#init()
call vimtex#state#init_buffer()
call vimtex#cmd#init_buffer()
call vimtex#motion#init_buffer()
call vimtex#delim#init_buffer()
call vimtex#env#init_buffer()
```

However I can get correct result in markdown file. And when I comment the line `call vimtex#syntax#core#init_rules()`, it also doesn't work too.

Is it a bug or I've misunderstood something? Many thanks in advance!

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 22.04.3 LTS
  Vim version: VIM 9.1 (1-158)
  Has clientserver: true
  Servername: undefined (vim started without --servername)

VimTeX project: a
  base: a.tex
  root: /home/fesmoph/Space
  tex: /home/fesmoph/Space/a.tex
  main parser: fallback current file
  document class: 
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
