### ISSUE TITLE
Compilation failed when using xelatex

### ISSUE THREAD

**Issue by Twix53791** [lervag/vimtex#2901]
### Description

Hi, I am new to latex, I am trying to use xelatex to use the fontspec package, but when I am trying to set the latex file to xelatex with `%!TEX program = xelatex`, the compilation fails, without giving me any error in the log (le). Why?

PS: I use neovim, I installed vimtex via vimplug, I installed latex on arch via pacman, installing the following packages: texlive-basic/bin/latex/binextra/bibtexextra/latexrecommanded/fontsrecommanded.

### Steps to reproduce

**1. vimtex.vim config**
```vim
filetype plugin indent on
syntax enable
let g:vimtex_view_method = 'zathura'
let maplocalleader = ","

let g:vimtex_compiler_latexmk_engines = {
    \ '_'                : '-pdf',
    \ 'pdfdvi'           : '-pdfdvi',
    \ 'pdfps'            : '-pdfps',
    \ 'pdflatex'         : '-pdf',
    \ 'luatex'           : '-lualatex',
    \ 'lualatex'         : '-lualatex',
    \ 'xelatex'          : '-xelatex',
    \ 'context (pdftex)' : '-pdf -pdflatex=texexec',
    \ 'context (luatex)' : '-pdf -pdflatex=context',
    \ 'context (xetex)'  : '-pdf -pdflatex=''texexec --xtx''',
    \}
```

**2. Minimal test file tata.tex**
```latex
\documentclass{article}
    \usepackage[margin=0.7in]{geometry}

\begin{document}

This is a test from tata.

\end{document}
```

And everything works fine !

**3. Set the default latexmk engine to xelatex with**
```vim
let g:vimtex_compiler_latexmk_engines = {
    \ '_'                : '-xelatex',
```
OR at the beginning of the tata.tex file (I tried several syntaxes: % !TEX, %! TEX... seems it doesn't matter...)
```latex
%!TEX program = xelatex
```

And the compilation will fail ! Without any error message in the log (via le shortcut). I got the message "Compilation failed" and no pdf file is produced.

**NOTES**

- When I reload the file and check the infos via li, the engine is well set to xelatex.
- if I change the engine to lualatex, the compilation works, EXCEPT if I am trying to use fontspec by adding alone the line `\usepackage{fontspec}` ; but maybe it is another problem, as I got an error message in the log contrary to the compilation error with xelatex.
- everytime I try to compile, a new file named "xelatex<some number>.fls" is created in the directory where tata.tex is. There are empty, containing only the following:
```
PWD /home/archx/test/koko
INPUT /usr/share/texmf-dist/web2c/texmf.cnf
```

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
System info:
  OS: Linux 6.7.9-arch1-1
  Vim version: NVIM v0.9.5
  Has clientserver: true
  Servername: /run/user/1000/nvim.208573.0

VimTeX project: tata
  base: tata.tex
  root: /home/user/test/koko
  tex: /home/user/test/koko/tata.tex
  main parser: current file verified
  document class: article
  packages: amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm etoolbox geometry iftex ifvtex inputenc keyval kvoptions kvsetkeys ltxcmds parskip
  compiler: latexmk
    engine: -xelatex
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```%!TeX program = xelatex

\documentclass{report}
\usepackage{fontspec}

\begin{document}
This is an example.
\end{document}
```
