### ISSUE TITLE
Cannot create directory: file already exists error when compiling

### ISSUE THREAD

**Issue by Kayzels** [lervag/vimtex#2906]
### Description

Whenever I recompile a file, I get this error popup. The file compiles fine, so it's a false positive. This is in Neovim 10, on Windows 10.

```
Error detected while processing function vimtex#compiler#compile[6]..vimtex#compiler#start[17]..41[3]..59[1]..35:
E739: Cannot create directory C:\Users\Kyzan\Documents\Unisa\Third Year\COS3711 Advanced Programming\COS3711 Notes/./out//C\\Users: file already exists
```

It might be due to the function checking the build details before building.

### Steps to reproduce

1. Create a file and build it, so the output directory exists
2. Build the file again
3. The file builds, but the error appears

### Expected behavior

I expect the file to compile, but to not see this false positive error message.

### Actual behavior

An error message popping up saying the file already exists when recompiling.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: KYZAN-PC (Microsoft Windows 10 Pro)
  Vim version: NVIM v0.10.0-dev-2752+g35239e977
  Has clientserver: true
  Servername: \\.\pipe\nvim.6156.0

VimTeX project: notes
  base: notes.tex
  root: C:\Users\Kyzan\Documents\Unisa\Third Year\COS3711 Advanced Programming\COS3711 Notes
  tex: C:\Users\Kyzan\Documents\Unisa\Third Year\COS3711 Advanced Programming\COS3711 Notes/notes.tex
  main parser: subfiles
  document class: book
  packages: \main/custom adjcalc adjustbox amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm array atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook babel bigintcalc bitset bm booktabs cabin caption caption3 catchfile centernot changepage charter collectbox color colortbl custom enumitem environ epstopdf-base etexcmds etoolbox expl3 fancyhdr fancyvrb float fontaxes fontenc framed fvextra geometry gettitlestring graphics graphicx hycolor hyperref hyphsubst ifluatex ifoddpage ifplatform iftex ifthen ifvtex ifxetex import inconsolata infwarerr intcalc keyval kvdefinekeys kvoptions kvsetkeys lineno ltxcmds minted multicol mweights nameref newtxmath ninecolors notestyles parskip pdfcol pdfescape pdftexcmds pgf pgf-umlcd pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfrcs pgfsys refcount rerunfilecheck shellesc subfiles tabularray tcolorbox textcomp tikz trig trimclip trimspaces uniquecounter upquote url varwidth verbatim wrapfig xcolor xkeyval xparse xstring
  source files:
    C:\Users\Kyzan\Documents\Unisa\Third Year\COS3711 Advanced Programming\COS3711 Notes/notes.tex
    C:\Users\Kyzan\Documents\Unisa\Third Year\COS3711 Advanced Programming\COS3711 Notes/lessons/lesson01.tex
    C:\Users\Kyzan\Documents\Unisa\Third Year\COS3711 Advanced Programming\COS3711 Notes/lessons/lesson02.tex
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -shell-escape
      -interaction=nonstopmode
    out_dir: ./out/
    callback: 1
    continuous: 0
    executable: latexmk
    job: 
      jobid: 43
      output: C:\Users\Kyzan\AppData\Local\Temp\nvim.0\qxX8VB\0
      cmd: set max_print_line=2000 & latexmk -verbose -file-line-error -synctex=1 -shell-escape -interaction=nonstopmode  -pdf -outdir=./out/ "notes.tex"
  viewer: sioyek
    job: 
      pid: -
      cmd: C:\Users\Kyzan\Tools\sioyek-release-windows\sioyek.exe  --inverse-search "C:\Program Files\Neovim\bin\nvim.exe --headless -c \"VimtexInverseSearch %2 '%1'\"" --forward-search-file "C:\\Users\\Kyzan\\Documents\\Unisa\\Third Year\\COS3711 Advanced Programming\\COS3711 Notes\\lessons\\lesson02.tex" --forward-search-line 58 "C:\\Users\\Kyzan\\Documents\\Unisa\\Third Year\\COS3711 Advanced Programming\\COS3711 Notes\\out\\notes.pdf"
    cmd_start: C:\Users\Kyzan\Tools\sioyek-release-windows\sioyek.exe  --inverse-search "C:\Program Files\Neovim\bin\nvim.exe --headless -c \"VimtexInverseSearch %2 '%1'\"" --forward-search-file "C:\\Users\\Kyzan\\Documents\\Unisa\\Third Year\\COS3711 Advanced Programming\\COS3711 Notes\\lessons\\lesson02.tex" --forward-search-line 58 "C:\\Users\\Kyzan\\Documents\\Unisa\\Third Year\\COS3711 Advanced Programming\\COS3711 Notes\\out\\notes.pdf"
  qf method: LaTeX logfile
```
