### ISSUE TITLE
Continuous mode for OpenBSD fails due to option 

### ISSUE THREAD

**Issue by EddieCueto** [lervag/vimtex#2907]
### Description

An option for latexmk (-pvctimeout) does not allow continuous mode to start,  an easy fix for this problem is to add the following, to autoload/vimtex/compiler/latexmk.vim:
```vim
  if self.continuous
    if has("bsd")
        let l:cmd .= ' -pvc -view=none'
    else
        let l:cmd .= ' -pvc -pvctimeout- -view=none'
    endif
```
from lines 152 to 157.

### Steps to reproduce

1. Start continuous mode on OpenBSD 
2. Error displays:
  Latexmk: -pvctimeout- bad option
Latexmk: Bad options specified
Use
   latexmk -help
to get usage information

4. continuous mode fails

### Expected behavior

Countinuouis mode should start

### Actual behavior

Continuous mode fails to start

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: OpenBSD 7.5
  Vim version: NVIM v0.9.5
  Has clientserver: true
  Servername: /tmp/nvim.eduardo/o8rFSR/nvim.75635.0

VimTeX project: 0_front_matter
  base: 0_front_matter.tex
  root: /home/eduardo/Programming/LaTeX/A-study-of-the-training-dynamics-and-relative-efficiency-of-neural-architecture
  tex: /home/eduardo/Programming/LaTeX/A-study-of-the-training-dynamics-and-relative-efficiency-of-neural-architecture/0_front_matter.tex
  main parser: recursive search
  document class: elsarticle
  packages: amsbsy amsfonts amsgen amsmath amsopn amssymb amstext array atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook bigintcalc bitset blindtext calc capt-of caption caption3 color easyReview enumitem epstopdf-base etexcmds etoolbox expl3 float geometry gettitlestring graphics graphicx hycolor hyperref ifluatex iftex ifthen ifvtex infwarerr intcalc keyval kvdefinekeys kvoptions kvsetkeys letltxmacro ltxcmds multido multirow nameref natbib pdfescape pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfrcs pgfsys pst-3d pst-calculate pst-math pst-node pst-plot pst-xkey pstricks pstricks-add refcount rerunfilecheck siunitx soul soul-ori subcaption tikz todonotes translations trig uniquecounter url xcolor xkeyval xparse xspace xstring
  source files:
    0_front_matter.tex
    1_introduction.tex
    2_related_work.tex
    3_efficiency_measure.tex
    4_case_study.tex
    5_validating_eff.tex
    6_conclusions.tex
    7_appendix_a.tex
    8_appendix_b.tex
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
```
