### ISSUE TITLE
Concealing subscript letters stopped working

### ISSUE THREAD

**Issue by ConnerRose** [lervag/vimtex#2910]
### Description

I noticed recently that subscripts using letters are no longer being concealed correctly. I.e., for $v_n$, the subscript n is replaced with an empty box (I think indicating that the character is not found). Can anyone else confirm that this isn't just a problem for me?

<img width="253" alt="Screenshot 2024-04-01 at 20 24 14" src="https://github.com/lervag/vimtex/assets/50835965/794e6860-34b0-47af-b599-3e5a9b07ea5f">

<img width="208" alt="Screenshot 2024-04-01 at 20 22 44" src="https://github.com/lervag/vimtex/assets/50835965/8834149b-78c7-4007-85c8-ee28395228ee">

### Steps to reproduce

Edit a .tex file with concealing on.

### Expected behavior

Subscript letters to be concealed as a smaller version of that letter.

### Actual behavior

Subscript letters concealed as (what I think to be) missing character icons.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 14.4.1 (23E224)
  Vim version: NVIM v0.9.5
  Has clientserver: true
  Servername: /var/folders/fl/_5b_cs253mjgl0gc4ptrqg2r0000gn/T/nvim.conner/4pUIm8/nvim.98532.0

VimTeX project: hw09
  base: hw09.tex
  root: /Users/conner/umich/w24/math420/hw09
  tex: /Users/conner/umich/w24/math420/hw09/hw09.tex
  main parser: current file verified
  document class: report
  packages: amsfonts amsmath amssymb amsthm bm booktabs cancel emptypage enumitem etoolbox fancyhdr float fontenc geometry graphicx hyperref import inputenc mathrsfs mathtools mdframed multicol parskip pdfpages pgfplots siunitx stmaryrd subcaption systeme tcolorbox textcomp thmtools tikz tikz-cd todonotes transparent url xcolor xifthen
  source files:
    hw09.tex
    ../preamble.tex
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Skim
  qf method: LaTeX logfile
```
