### ISSUE TITLE
Viewer (evince) opening on top of neovim instance instead of new window

### ISSUE THREAD

**Issue by speightashley** [lervag/vimtex#2912]
### Description

I use Neovim (Lazyvim) on Hyprland and have setup vimtex with the following settings:

```
return {
  {
    "lervag/vimtex",
    lazy = false,
    config = function()
      vim.g.vimtex_view_general_viewer = "evince"
      vim.g.vimtex_mappings_disable = { ["n"] = { "K" } }
    end,
  },
}
```

When I compile, it opens the view on top of the Nvim instance and not in a separate window.

Is there a way to force evince to open in its own window instead of the existing nvim window?

### Steps to reproduce

Open a tex file in nvim
LocalLeader + ll to compile the tex document

### Expected behavior

Evince opens in separate window so that I can see both Nvim and Evince in split screen. Even if it opens on another workspace it would be fine because I could just move it to the correct workspace but it's opening layered on top of nvim without me being able to separate them. 

### Actual behavior

Evince opens but in the same window as nvim

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Linux 6.8.1-arch1-1
  Vim version: NVIM v0.9.5
  Has clientserver: true
  Servername: /run/user/1000/nvim.707333.0

VimTeX project: test
  base: test.tex
  root: /home/xxxxxxx/Projects/Latex
  tex: /home/xxxxxxx/Projects/Latex/test.tex
  main parser: current file verified
  document class: article
  packages: amsbsy amsgen amsmath amsopn amstext lingmacros tree-dvips
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 42
      output: /tmp/nvim.xxxxx/Br57dm/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode  -pdf -pvc -pvctimeout- -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'test.tex'
      pid: 707657
  viewer: General
    job: 
      pid: -
      cmd: evince '/home/xxxxxx/Projects/Latex/test.pdf'
  qf method: LaTeX logfile
```
