### ISSUE TITLE
inverse search not working WSL 

### ISSUE THREAD

**Issue by 594212** [lervag/vimtex#2914]
### Description

I'm using nvim with wsl Ubuntu and inverse search not working.
I already tried that you describe in others issues:
> 1.  Open ~/textest/main.tex with neovim.
> 2. Open a terminal and go to the project root directory with cd.
> 3. In neovim: Compile the project \ll . Sioyek opens, I can close it.
> 4. In the terminal, run nvim --headless -c "VimtexInverseSearch 10 '~/textest/main.tex'",
> This should open the specified file at the specified line in neovim

It didn't work, cursor not moving.

plugins/vimtex.lua
```lua
return {
    "lervag/vimtex",
    lazy = false,
    init = function()
        -- Use init for configuration, don't use the more common "config".
        vim.g.vimtex_view_general_viewer = 'sioyek'
        vim.g.vimtex_callback_progpath = "C:\\Windows\\system32\\wsl.exe nvim"
    end
}
```
instruction above, was executed in wsl, so I think, vim.g.vimtex_callback_progpath dosn't matter,
if is not working within wsl

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 22.04.4 LTS
  Vim version: NVIM v0.9.4
  Has clientserver: true
  Servername: /run/user/1000//nvim.135906.0

VimTeX project: main
  base: main.tex
  root: /home/sul/textest
  tex: /home/sul/textest/main.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 20
      output: /tmp/nvim.sul/myEqie/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode  -pdf -pvc -pvctimeout- -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'main.tex'
      pid: 137601
  viewer: General
    job: 
      pid: -
      cmd: sioyek '/home/sul/textest/main.pdf'
  qf method: LaTeX logfile
```

**Comment by lervag** [comment]
> I already tried that you describe in others issues:
> 
> > 1. Open ~/textest/main.tex with neovim.
> > 2. Open a terminal and go to the project root directory with cd.
> > 3. In neovim: Compile the project \ll . Sioyek opens, I can close it.
> > 4. In the terminal, run nvim --headless -c "VimtexInverseSearch 10 '~/textest/main.tex'",
> >    This should open the specified file at the specified line in neovim
> 
> It didn't work, cursor not moving.

> ```lua
> return {
>     "lervag/vimtex",
>     lazy = false,
>     init = function()
>         -- Use init for configuration, don't use the more common "config".
>         vim.g.vimtex_view_general_viewer = 'sioyek'
>         vim.g.vimtex_callback_progpath = "C:\\Windows\\system32\\wsl.exe nvim"
>     end
> }
> ```

You did not really read the docs well enough. Sioyek has its own configuration, so you should use this:

```lua
return {
    "lervag/vimtex",
    lazy = false,
    init = function()
        vim.g.vimtex_view_method = 'sioyek'
        -- vim.g.vimtex_callback_progpath = "C:\\Windows\\system32\\wsl.exe nvim"
        -- I believe you can simplify this to:
        vim.g.vimtex_callback_progpath = "wsl nvim"
    end
}
```

Please read `:help vimtex-view-sioyek`, as well as `:help vimtex-faq-wsl` for more info.

**Comment by 594212** [comment]
I'm sorry, I already tried that, while was trying figured out what's going I lost
``vim.g.vimtex_view_method = 'sioyek'``, first time I'm tried with this.
sioyek opens on the correct line, but inverse search not working.


Just so you know, since you mentioned it, I tried again. However, it didn't work.
>You did not really read the docs well enough

this line is hurt 

also, If it is important, instead of adding sioyek.exe  to %PATH I created symbol link to execution
```consol
/usr/bin/sioyek -> /mnt/c/Users/sul/AppData/Local/Microsoft/WinGet/Packages/ahrm.sioyek_Microsoft.Winget.Source_8wekyb3d8bbwe/sioyek-release-windows/sioyek.exe
```
so it is why I don't use 
``vim.g.vimtex_view_sioyek_exe = 'sioyek.exe'``

**Comment by lervag** [comment]
> > You did not really read the docs well enough
> 
> this line is hurt

Sorry, that was not my intent. Using the general viewer (`vimtex_view_method = "general"`) instead of the specific (`vimtex_view_method = "sioyek"`) indicated that you did not know that there _is_ a specific one.

> I'm sorry, I already tried that, while was trying figured out what's going I lost `vim.g.vimtex_view_method = 'sioyek'`, first time I'm tried with this. sioyek opens on the correct line, but inverse search not working.

Ok, do I understand correctly that with this, forward search works as expected? Forward search will not work with `vimtex_view_general_viewer = "sioyek"`, so this is an improvement.

Can you do `:VimtexInfo` again and report the `viewer:` part after you have opened a tex file and after the viewer has started? I want to see the `viewer.job.cmd`.

> also, If it is important, instead of adding sioyek.exe to %PATH I created symbol link to execution
> 
> ```
> /usr/bin/sioyek -> /mnt/c/Users/sul/AppData/Local/Microsoft/WinGet/Packages/ahrm.sioyek_Microsoft.Winget.Source_8wekyb3d8bbwe/sioyek-release-windows/sioyek.exe
> ```
> 
> so it is why I don't use `vim.g.vimtex_view_sioyek_exe = 'sioyek.exe'`

Ok. So, first, I don't use Windows and I may not be able to help you here. But I'll try.

Now, it seems you are using neovim inside Ubuntu in WSL. And that Sioyek is installed on the Windows side of things. It also seems that this works well, except for the inverse search.

Now, I think the first step here is to check that the inverse search method works at all. Can you do this?

* Open a terminal and `cd textest`, then `nvim main.tex`.
* Start compilation (`\ll`), then close the viewer if it opens.
* Open a new terminal and `cd textest`, then:  
    `nvim --headless -c "VimtexInverseSearch 10 '/home/sul/textest/main.tex'"`

The third action should move your cursor in neovim in the first terminal to the specified file at the specified line. Can you test and let me know what happens?

**Comment by 594212** [comment]
>Ok, do I understand correctly that with this, forward search works as expected? Forward search will not work with 
vimtex_view_general_viewer = "sioyek", so this is an improvement.

Year, when I used ``vimtex_view_general_viewer = "sioyek"`` is only opens sioyek but not in correct line, now with
``vimtex_view_method = "sioyek"`` it opens correctly on correct line

>Can you do :VimtexInfo again and report the viewer: part after you have opened a tex file and after the viewer has started? I want to see the viewer.job.cmd.
<details>
<summary>VimtexInfo</summary>
```yaml
viewer: sioyek
    job: 
      pid: 37876
      cmd: sioyek.exe  --inverse-search "wsl nvim --headless -c \"VimtexInverseSearch %2 '%1'\"" --forward-search-file '/home/sul/textest/main.tex' --forward-search-line 15 '/home/sul/textest/main.pdf'
    cmd_start: sioyek.exe  --inverse-search "wsl nvim --headless -c \"VimtexInverseSearch %2 '%1'\"" --forward-search-file '/home/sul/textest/main.tex' --forward-search-line 15 '/home/sul/textest/main.pdf'
  qf method: LaTeX logfile
```
</details>

>Now, I think the first step here is to check that the inverse search method works at all. Can you do this?
>* Open a terminal and cd textest, then nvim main.tex.
>* Start compilation (\ll), then close the viewer if it opens and restart neovim (:q then nvim main.tex).
>* Open a new terminal and cd textest, then:
>* nvim --headless -c "VimtexInverseSearch 10 '/home/sul/textest/main.tex'"
>
>The third action should move your cursor in neovim in the first terminal to the specified file at the specified line. Can you test and let me know what happens?


it is a magic it jumped on correct line!!!
also I tried `wsl nvim --headless -c "VimtexInverseSearch 10 '/home/sul/textest/main.tex'"` and it work.

Maybe I don't use keystroke correctly? 
>Press f4 to toggle synctex mode (toggle_synctex command). While in this mode, right clicking on any text opens the corresponding tex file in the appropriate location.

but is still not working
