### ISSUE TITLE
Inline math environment not detected as text object

### ISSUE THREAD

**Issue by loximann** [lervag/vimtex#2915]
### Description

Commands like `di$`, `va$`, `ts$`, etc, work for displaymath environments, but not got inline math.

### Steps to reproduce

`minimal.vim`
```vim
set nocp
syntax on
filetype plugin on
```
`minimal.tex`
```tex
\documentclass{minimal}
\begin{document}
Hello $World!$
\begin{equation}
World!
\end{equation}
\end{document}
```
1. `vim -u minimal.vim minimal.tex`
2. Move cursor to the first "World!". Type `ts$`.
3. Move cursor to the second "World!". Type `ts$`.

### Expected behavior

2. Changes the `$World!$` to a displaymath environment.
3. Changes the displaymath environment to `$World!$`.

### Actual behavior

2. Nothing happens.
3. Changes the displaymath environment to `$World!$`.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Fedora release 38 (Thirty Eight)
  Vim version: VIM 9.1 (1-158)
  Has clientserver: false

VimTeX project: minimal
  base: minimal.tex
  root: /home/sergio
  tex: /home/sergio/minimal.tex
  main parser: current file verified
  document class: minimal
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
