### ISSUE TITLE
inverse search in zathura opens an extra gvim window

### ISSUE THREAD

**Issue by khumarahn** [lervag/vimtex#2919]
### Description

Hi!

I've been a very happy user of vimtex for quite a few years, and this is my first issue, iirc.

I'm seeing an annoying issue with the inverse search: each time I control-click on a pdf, a fresh gvim window opens and immediately closes, see the video in attachment. Both forward and inverse search work nevertheless

I use vimtex+gvim+zathura+sway, my vimtex config is
```vim
call plug#begin()
Plug 'lervag/vimtex'
call plug#end()

let g:vimtex_view_method = 'zathura_simple'
```

Things used to work well in the same setup previously, but it's hard to say which update caused this. It is not specific to a latex file, happens in all files I tried.

https://github.com/lervag/vimtex/assets/5206045/46262e11-8f71-4f58-aaef-33c3a03969bc

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Gentoo Linux
  Vim version: VIM 9.0 (1-2167)
  Has clientserver: true
  Servername: GVIM

VimTeX project: View5
  base: View5.tex
  root: /home/khu/Downloads/hh
  tex: /home/khu/Downloads/hh/View5.tex
  main parser: current file verified
  document class: lhep
  packages: amsbsy amsfonts amsgen amsmath amsopn amssymb amstext avant dsfont epstopdf-base fix-cm framed geometry graphics graphicx iftex ifvtex keyval mathpazo mathrsfs natbib pifont trig xcolor
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: process 2414656 run
      output: /tmp/vuBV4rb/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode  -pdf -pvc -pvctimeout- -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'View5.tex'
      pid: 2414656
  viewer: Zathura
    cmd_start: zathura  -x "/usr/bin/gvim -T dumb --not-a-term -n -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 47:24:'/home/khu/Downloads/hh/View5.tex' 'Downloads/hh/View5.pdf'&
  qf method: LaTeX logfile
```
