### ISSUE TITLE
Vimtex very slow on basic navigations

### ISSUE THREAD

**Issue by zerogtiger** [lervag/vimtex#2921]
### Description

Navigating a tex buffer is very slow with vimtex enabled, especially when the buffer contains many lines of math. Hardware specs listed below, though with other buffers, neovim is very snappy. I have tried various optimizations (such as no matching paren, turning off concealment, turning off relative numbers, or lazy redraw) to no satisfying result (there is still at least a 200ms delay between pressing `j` and the cursor actually moving). 

I have ran `syntime on` followed later by `syntime report` and the output is as follows

```
TOTAL      COUNT  MATCH   SLOWEST     AVERAGE   NAME               PATTERN
  0.091622   1604   0       0.000216    0.000057  texMathSymbol      [ℵ∐∠≈∗≍∖∩○∪⊙⊕⊗⊔∇∆⋁⋀⊥⋈•∩·⋯∘♣≅∐©∪†⊣‡⋱⋄♢÷≐…↓⇓ℓØ≡∃♭∀⁔≥≥←⟫ℏ♡↩↪⇔ℑɩ∈∞∫∬∭𝚥∧¬<e2>
  0.033115   1604   0       0.000079    0.000021  texCmdGreek        [αβγδ𝝳𝛿𝛅𝞭ϵεζηθϑικλμνξπϖρϱσςτυϕφχψωΓΔΘΛΞΠΣΥΦΧΨΩ]
  0.024520   3640   2049    0.000041    0.000007  texMathDelim       \s*\\\%([bB]igg\?r\?\|right\))
  0.020896   9566   7993    0.000030    0.000002  texMathOper        [-+=/<>|]
  0.019723   7622   6037    0.000075    0.000003  texMathDelim       [()[\]]
  0.019326   11548  9963    0.000074    0.000002  texMathSymbol      \\cdot\ze\%(\>\|[_^]\)
  0.019189   1604   0       0.000043    0.000012  texMathDelim       \s*\\\%([bB]igg\?r\?\|right\)\\rVert\>
  0.019109   1604   0       0.000042    0.000012  texMathDelim       \s*\\\%([bB]igg\?r\?\|right\)\\rangle\>
  0.018628   1604   0       0.000041    0.000012  texMathDelim       \s*\\\%([bB]igg\?r\?\|right\)\\updownarrow\>
  0.018612   1604   0       0.000126    0.000012  texMathDelim       \s*\\\%([bB]igg\?r\?\|right\)\\Uparrow\>
  0.018610   1604   0       0.000072    0.000012  texMathDelim       \s*\\\%([bB]igg\?r\?\|right\)\\downarrow\>
  0.018587   1604   0       0.000042    0.000012  texMathDelim       \s*\\\%([bB]igg\?r\?\|right\)\\Updownarrow\>
  0.018555   1604   0       0.000042    0.000012  texMathDelim       \s*\\\%([bB]igg\?r\?\|right\)\\rvert\>
  0.018494   8882   7309    0.000013    0.000002  texMathSuperSub    \^{\%([-+=()<>:;0-9a-qr-zA-FG-QRTUVW]\|\\\%(beta\|gamma\|delta\|epsilon\|theta\|iota\|phi\|chi\)\>\|\s\)\+}
  0.018481   1604   0       0.000042    0.000012  texMathDelim       \s*\\\%([bB]igg\?r\?\|right\)\\rceil\>
  0.018471   1604   0       0.000098    0.000012  texMathDelim       \s*\\\%([bB]igg\?r\?\|right\)\\uparrow\>
  0.018443   1604   0       0.000042    0.000011  texMathDelim       \s*\\\%([bB]igg\?r\?\|right\)\\}
  0.018437   1604   0       0.000105    0.000011  texMathDelim       \s*\\\%([bB]igg\?r\?\|right\)]
  0.018427   1604   0       0.000043    0.000011  texMathDelim       \s*\\\%([bB]igg\?r\?\|right\)\\|
  0.018414   1604   0       0.000042    0.000011  texMathDelim       \s*\\\%([bB]igg\?r\?\|right\)\\rgroup\>
  0.018365   1604   0       0.000042    0.000011  texMathDelim       \s*\\\%([bB]igg\?r\?\|right\)|
  0.018360   1604   0       0.000041    0.000011  texMathDelim       \s*\\\%([bB]igg\?r\?\|right\)\\Downarrow\>
  0.018352   1604   0       0.000061    0.000011  texMathDelim       \s*\\\%([bB]igg\?r\?\|right\)\\rfloor\>
  0.018352   1604   0       0.000041    0.000011  texMathDelim       \s*\\\%([bB]igg\?r\?\|right\)\\rmoustache\>
  0.018310   1604   0       0.000042    0.000011  texMathDelim       \s*\\\%([bB]igg\?r\?\|right\)\\rbrace\>
  0.018287   1604   0       0.000042    0.000011  texMathDelim       \s*\\\%([bB]igg\?r\?\|right\)>
  0.017318   2062   471     0.000039    0.000008  texMathDelim       \s*\\right)
  0.017183   1604   0       0.000085    0.000011  texMathDelim       \s*\\right\\}
  0.017059   1604   0       0.000039    0.000011  texMathDelim       \s*\\right]
  0.017001   1604   0       0.000042    0.000011  texMathDelim       \s*\\right|
  0.016993   1604   0       0.000039    0.000011  texMathDelim       \s*\\right\\|
  0.016989   1604   0       0.000039    0.000011  texMathDelim       \s*\\rfloor\>
  0.016779   1604   0       0.000039    0.000010  texMathDelim       \s*\\rangle\>
  0.016720   1604   0       0.000038    0.000010  texMathDelim       \s*\\rbrace\>
  0.016680   1604   0       0.000039    0.000010  texMathDelim       \s*\\}
  0.016676   1604   0       0.000041    0.000010  texMathDelim       \s*\\rVert\>
  0.016562   1604   0       0.000047    0.000010  texMathDelim       \s*\\rvert\>
  0.014355   7463   5890    0.000019    0.000002  texMathSuperSub    [_^]
  0.013662   9033   7875    0.000024    0.000002  texMathCmd         \\\a\+
  0.012957   5974   5674    0.000021    0.000002  texMathArg         \\\\\|\\}
  0.012831   5344   5144    0.000024    0.000002  texMathGroup       \\\\\|\\}
  0.012415   6531   4954    0.000013    0.000002  texMathSymbol      \\sum\ze\%(\>\|[_^]\)
  0.011875   5367   3784    0.000013    0.000002  texMathSymbol      \\rightarrow\ze\%(\>\|[_^]\)
  0.009563   3739   2163    0.000025    0.000003  texMathSuperSub    _{\%([-+=()0-9aehijklmnoprstuvx]\|\\\%(beta\|gamma\|rho\|phi\|chi\)\>\|\s\)\+}
  0.009287   3404   1800    0.000023    0.000003  texMathSymbol      \\[dt]\?frac\s*\%(1\|{1}\)\s*\%(2\|{2}\)
  0.008258   20782  19592   0.000018    0.000000  texTabularChar     \\\\
  0.006351   3078   1487    0.000022    0.000002  texMathDelim       \\\%([bB]igg\?l\?\|left\)(\s*
  0.005768   2520   929     0.000008    0.000002  texMathDelimMod    \\\(left\|right\)\>
  0.005462   2454   850     0.000007    0.000002  texMathSymbol      \\leftarrow\ze\%(\>\|[_^]\)
  0.005411   1604   0       0.000013    0.000003  texMathDelim       \\\%([bB]igg\?l\?\|left\|\)\\|\s*
  0.005377   1604   0       0.000013    0.000003  texMathSymbol      \\[dt]\?frac\s*\%(7\|{7}\)\s*\%(8\|{8}\)
  0.004912   1604   0       0.000025    0.000003  texMathSymbol      \\[dt]\?frac\s*\%(5\|{5}\)\s*\%(8\|{8}\)
  0.004833   1604   0       0.000011    0.000003  texMathSymbol      \\[dt]\?frac\s*\%(1\|{1}\)\s*\%(8\|{8}\)
  0.004751   1604   0       0.000011    0.000003  texMathSymbol      \\[dt]\?frac\s*\%(1\|{1}\)\s*\%(3\|{3}\)
```

Hardware: Raspberry Pi 5 8GB
Editor: Neovim v0.9.5
Terminal: urxvt
System: Debian 12 Bookworm

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
`System info:
  OS: Debian GNU/Linux 12 (bookworm)
  Vim version: NVIM v0.9.5
  Has clientserver: true
  Servername: /run/user/1000/nvim.4097.0

VimTeX project: test
  base: test.tex
  root: /home/tiger/test
  tex: /home/tiger/test/test.tex
  main parser: current file verified
  document class: article
  packages: amsbsy amsfonts amsgen amsmath amsopn amssymb amstext array asymptote atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook bigintcalc bitset blkarray calc catchfile color colortbl enumitem epstopdf-base etexcmds etoolbox fancyhdr fontenc geometry gettitlestring graphics graphicx hhline hycolor hyperref ifpdf iftex ifthen ifvtex ifxetex infwarerr inputenc intcalc keyval kvdefinekeys kvoptions kvsetkeys listings lstmisc lstpatch ltxcmds mathtools mhsetup multicol nameref parskip pdfescape pdftexcmds refcount rerunfilecheck titlesec trig uniquecounter url xcolor
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
