### ISSUE TITLE
Calling :VimtexInverseSearch crashes Neovim

### ISSUE THREAD

**Issue by aluminum1** [lervag/vimtex#2928]
### Description

When I execute :VimtexInverseSearch in Neovim 0.9.5, and using the 20 March 2024 git commit of Vimtex, the Neovim instance crashes.

### Steps to reproduce

1. nvim
2. :VimtexInverseSearch

### Expected behavior

That nvim will not crash. An error message of the kind "no line number given" should be displayed.

### Actual behavior

Neovim crashes.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 12.6.7 (21G651)
  Vim version: NVIM v0.9.5
  Has clientserver: true
  Servername: /var/folders/ns/rsd7sj9119z16qbwg6q_14_c0000gn/T/nvim.brucebartlett/f2UZ4V/nvim.20643.0

VimTeX project: Quantum 6j symbols
  base: Quantum 6j symbols.tex
  root: /Users/username/Sync/Research/
  tex: /Users/username/Sync/Research/file.tex
  main parser: current file verified
  document class: article
  packages: amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm atbegshi bm calc caption caption3 epstopdf-base eso-pic etex etexcmds everyshi fontenc geometry graphics graphicx grfext ifluatex ifpdf ifthen ifvtex ifxetex infwarerr inputenc keyval kvdefinekeys kvoptions kvsetkeys lipsum lscape ltxcmds mathtools mhsetup multicol parskip pdflscape pdfpages pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfrcs pgfsys subcaption textcomp tikz tkz-graph trig url xcolor xkeyval xy
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Skim
  qf method: LaTeX logfile
```
