### ISSUE TITLE
Escaped left brace in \phantom breaks highlighting

### ISSUE THREAD

**Issue by danielrainer** [lervag/vimtex#2933]
### Description

When putting an escaped left brace `\{` into a `\phantom` command, the closing brace of the command seems to be ignored and the highlighting (`texConcealedArg`) extends past the end of the phantom command.

### Steps to reproduce

`minimal.vim`:
```vim
set nocompatible
let &runtimepath = '../../vimtex,' . &runtimepath
let &runtimepath .= ',../../vimtex/after'
filetype plugin indent on
syntax enable
```
`minimal.tex`:
```latex
\documentclass{minimal}
\begin{document}
\phantom{\{} This is not part of phantom but highlighted as if it were.
\end{document}
```

### Expected behavior

The sentence should get the default highlighting.

### Actual behavior

The sentence is highlighted as `texConcealedArg`, despite being outside `\phantom`.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Arch Linux
  Vim version: NVIM v0.9.5
  Has clientserver: true
  Servername: /run/user/1000/nvim.34534.0

VimTeX project: minimal
  base: minimal.tex
  root: /home/drainer/projects/vimtex_repro/escaped_braces
  tex: /home/drainer/projects/vimtex_repro/escaped_braces/minimal.tex
  main parser: current file verified
  document class: minimal
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
