### ISSUE TITLE
VimtexCountWords inaccurate on range (apa7 document class)

### ISSUE THREAD

**Issue by A-Daneel** [lervag/vimtex#2935]
### Description

as the title states, when using the apa7 document class `VimtexCountWords` gives an inaccurate word count when done over a range. From my (minimal) testing, it seems to include the title.

The odd thing is, if you run it over the entire document it seems to give the correct word count. Not sure how I'd go about debugging it further (and if it's an issue that belongs here or on the apa7 package).

Would love to take a shot at it, but I'll need some pointers to get started :)

### Steps to reproduce

minimal latex file
```tex
\documentclass[stu]{apa7}

\title{A title}
\shorttitle{A short title}
\author{An author}

\begin{document}

\thispagestyle{empty}
\maketitle

Some text.

Some more text.

\end{document}
```

if you highlight the "some text." line, and run `:'<,'>VimtexCountWords` it'll say it's 4 long. ("some text." + "A title")

if you highlight the "some more text" line, and run `:'<,'>VimtexCountWords` it'll say it's 5 long. ("some more text." + "A title")

If you highlight nothing and run `:VimtexCountWords` it'll give you the correct word count of 7.

### Expected behavior

When following the steps, I'd expect to only get the word count of the selection.

### Actual behavior

Currently I get the selection and the title.

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 22.04.3 LTS
  Vim version: NVIM v0.10.0-dev-2943+gb0f922817
  Has clientserver: true
  Servername: /run/user/1000/nvim.318158.0

VimTeX project: countWords
  base: countWords.tex
  root: /home/daneel/vimtex
  tex: /home/daneel/vimtex/countWords.tex
  main parser: current file verified
  document class: apa7
  packages: atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook bigintcalc bitset bm booktabs calc caption caption3 endfloat etoolbox fancyhdr fontenc geometry gettitlestring graphics graphicx hycolor hyperref iftex ifvtex infwarerr intcalc keyval kvdefinekeys kvoptions kvsetkeys letltxmacro lmodern ltxcmds nameref pdfescape pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfrcs pgfsys refcount rerunfilecheck scalerel stringenc threeparttable tikz trig uniquecounter url xcolor
  compiler: latexmk
    engine: -xelatex
    options:
      -shell-escape
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
