### ISSUE TITLE
commands starting with \if break indentation

### ISSUE THREAD

**Issue by IiroUllin** [lervag/vimtex#2938]
### Description

Indentation breaks when user-defined commands starting with \if are used: extra indent is added on the following line. (May be relevant: I'm using treesitter as well, however "latex" is disabled.)

### Steps to reproduce

```
\documentclass{article}

%	it seems that most command names starting with \if... break indentation
%	however, \iff does not!
\newcommand{\ifa}{trouble}

	\begin{document}
	Indentation breaks when the command is used: \ifa
		\end{document}
```

### Expected behavior

```
\documentclass{article}

%	it seems that most command names starting with \if... break indentation
%	however, \iff does not!
\newcommand{\ifa}{trouble}

\begin{document}
Indentation breaks when the command is used: \ifa
\end{document}
```

### Actual behavior

```
\documentclass{article}

%	it seems that most command names starting with \if... break indentation
%	however, \iff does not!
\newcommand{\ifa}{trouble}

	\begin{document}
	Indentation breaks when the command is used: \ifa
		\end{document}
```

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
System info:
  OS: Debian GNU/Linux 12 (bookworm)
  Vim version: NVIM v0.9.5
  Has clientserver: true
  Servername: /run/user/1000/nvim.48260.0

VimTeX project: bug_indent
  base: bug_indent.tex
  ...
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -lualatex
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
