### ISSUE TITLE
Question: Is it possible to disable the conceal only for `\\`?

### ISSUE THREAD

**Issue by camoz** [lervag/vimtex#2940]
### Description

Hey :)

at first thank you very much for this super helpful plugin!

I tried to disable the `\\` conceals using (in lua/neovim)

```
vim.g.vimtex_syntax_custom_cmds = {
  {name = '\\', mathmode = 0, conceal = 0},
}
```

... but it didn't work, I also tried in vimscript. Disabling other conceals like `alpha` in mathmode works fine.

Could it be that it's not possible at all, maybe because `\\` is perhaps not a real command?

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Linux 6.3.5-arch1-1
  Vim version: NVIM v0.9.5
  Has clientserver: true
  Servername: /run/user/1000/nvim.24720.0

VimTeX project: main
  base: main.tex
  root: /home/merlin/downloads/testlatex
  tex: /home/merlin/downloads/testlatex/main.tex
  main parser: current file verified
  document class: scrletter
  packages: amsmath babel csquotes etoolbox footmisc keyval lmodern scrbase scrkbase scrlayer scrlayer-scrpage scrletter scrlfile scrlfile-hook scrlogo tocbasic typearea
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    out_dir: build
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
