### ISSUE TITLE
VimTeX: Viewer cannot find Zathura window ID!

### ISSUE THREAD

**Issue by DALEE9000** [lervag/vimtex#2941]
### Description

Running Ubuntu 22.04.2. After entering command `\lv` to open Zathura, I receive an error message saying "VimTeX: Viewer cannot find Zathura window ID!", and Zathura doesn't display the pdf.

I have already checked to ensure that Zathura is synctex-enabled. 

```sh
$ ldd /usr/bin/zathura | grep libsynctex
        libsynctex.so.2 => /lib/x86_64-linux-gnu/libsynctex.so.2 (0x00007fbca7e6b000)
```

Moreover, I have indeed ensured that Zathura works from the command line in displaying the desired pdf. If it helps, my version of Zathura is listed below:

```sh
$ zathura --version
zathura 0.4.9
girara 0.3.7 (runtime: 0.3.7)
(plugin) pdf-poppler (0.3.0) (/usr/lib/x86_64-linux-gnu/zathura/libpdf-poppler.so)
```

Additionally, when entering the `cmd_start` output (see below) in the command line, I receive the following error:

```sh
$ zathura  -x "/usr/local/bin/vim -T dumb --not-a-term -n -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 5:14:'/home/cantorian_infinity/test.tex' 'test.pdf'
$ error: Could not connect to session bus: Could not connect: No such file or directory
error: Got no usable data from SyncTeX or D-Bus failed in some way.
```

### Steps to reproduce

`vim -u minimal.vim minimal.tex`

`minimal.tex`

```tex
\documentclass{minimal}

\begin{document}
Hello world!
\end{document}
```

`minimal.vim`

```vim
call plug#begin()
"VimTeX
Plug 'lervag/vimtex'
call plug#end()

let g:vimtex_viewer_method='zathura'


" This will only work if `vim --version` includes `+clientserver`!
" To enable Zathura and Vim to speak to each other
if empty(v:servername) && exists('*remote_startserver')
  call remote_startserver('VIM')
endif

" Get Vim's window ID for switching focus from Zathura to Vim using xdotool.
" Only set this variable once for the current Vim instance.
if !exists("g:vim_window_id")
  let g:vim_window_id = system("xdotool getactivewindow")
endif

function! s:TexFocusVim() abort
  " Give window manager time to recognize focus moved to Zathura;
  " tweak the 200m (200 ms) as needed for your hardware and window manager.
  sleep 200m  

  " Refocus Vim and redraw the screen
  silent execute "!xdotool windowfocus " . expand(g:vim_window_id)
  redraw!
endfunction

augroup vimtex_event_focus
  au!
  au User VimtexEventView call s:TexFocusVim()
augroup END

" So Vim finds Zathura window ID
function! ZathuraHook() abort
  if exists('b:vimtex.viewer.xwin_id') && b:vimtex.viewer.xwin_id <= 0
    silent call system('xdotool windowactivate ' . b:vimtex.viewer.xwin_id . ' --sync')
    silent call system('xdotool windowraise ' . b:vimtex.viewer.xwin_id)
  endif
endfunction

augroup vimrc_vimtex
  autocmd!
  autocmd User VimtexEventView call ZathuraHook()
augroup END
```

### Expected behavior

Zathura to display minimal.pdf

### Actual behavior

VimTeX: Viewer cannot find Zathura window ID! error appears

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 22.04.2 LTS
  Vim version: VIM 9.1 (1-368)
  Has clientserver: true
  Servername: VIM

VimTeX project: test
  base: test.tex
  root: /home/cantorian_infinity
  tex: /home/cantorian_infinity/test.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: process 140322 run
      output: /tmp/v721nFr/1
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode  -pdf -pvc -pvctimeout- -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'test.tex'
      pid: 140322
  viewer: Zathura
    xwin id: 0
    cmd_start: zathura  -x "/usr/local/bin/vim -T dumb --not-a-term -n -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 5:14:'/home/cantorian_infinity/test.tex' 'test.pdf'&
  qf method: LaTeX logfile
```
