### ISSUE TITLE
Use original highlight for concealed text

### ISSUE THREAD

**Issue by handcart2034** [lervag/vimtex#2942]
### Description

Hello there, really appreciate this plugin.
I am a bit confused about the highlight for concealed texts tho, mainly because of the following comment in #2732,

> Conceal displays them in even different colors.

Here is a minimal example on my end,
```
\documentclass[12pt]{article}

\begin{document}

\( \alpha α \)

\end{document}
```

Colorscheme is [gruvbox-material](https://github.com/sainnhe/gruvbox-material), here is how it looks without conceal, note both`\alpha` and the unicode `α` are in green,

![](https://images2.imgbox.com/8b/4c/yTXRojbD_o.png)

Here is how it looks with conceal, hard to read in some colorschemes,

![](https://images2.imgbox.com/3b/e7/KHlxWxXt_o.png)

The reason is that concealed texts are highlighted by `Conceal`group instead of their original group such as `texCmdGreek`. Because of this the suggested method is to `hi clear Conceal` or link `Conceal` to `Normal` group, which makes it look like

![](https://images2.imgbox.com/3a/4c/dYyfvZbK_o.png)

At least the text is readable now, but all concealed texts are highlighted as `Normal`, regardless of the original syntax group.

My question is is it possible to retain syntax group for those `cchar`'s, as suggested by that comment? Thanks for your time.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 14.1.1 (23B81)
  Vim version: VIM 9.1 (1-350)
  Has clientserver: false

VimTeX project: exp
  base: exp.tex
  root: /Users/~
  tex: /Users/~/exp.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -lualatex
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Skim
  qf method: LaTeX logfile
```
