### ISSUE TITLE
Poor error output in bibliography issue

### ISSUE THREAD

**Issue by ThSGM** [lervag/vimtex#2953]
### Description

So I've had a longstanding issue with poor error and warning representation (see [here](https://github.com/lervag/vimtex/issues/2920)) compared to non-vim options. I think the only way to solve such issues is to report errors as they arise. 

Here is a minimal file: 

```tex
\documentclass{article}

\begin{document}
Hello world.

Goodbye.

Here is a reference to \cite{Harris2022}.

\bibliographystyle{plain}
\bibliography{test.bib}
\end{document}
```

Here is the bibliography file:

```bib
@article{Harris2022,
  title={Nonlinear time-domain wave-structure interaction: A parallel fast integral equation approach},
  author={Harris, J.C. and Dombre, E., and Benoit, M. and  Grilli, S.T. and Kuznetsov, K.I.},
  journal={Int. J. Numer. Meth. Fluids},
  volume={94},
  pages={188--222},
  year={2022},
  publisher={Wiley}
}
```

Here is the unhelpful vimtex output:

![image](https://github.com/lervag/vimtex/assets/3396578/10fa1117-dd6c-4681-a0ce-eb738d7baaf1)

Here is the much more helpful Overleaf output:

![image](https://github.com/lervag/vimtex/assets/3396578/cc83a79d-5507-4c1c-b4ca-17440edebd02)

So you can easily see the error is due to Name 2 in bibliography entry having a comma at the end. 

The vimtex error reporting only:
-  notes a very unhelpful reference to the bibliography style file. Can we modify the error reporting to note this issue?
- I also want to remark how the Overleaf reporting has collated all the important errors to the top, and then stylised them in a very clear way (a red box). Obviously some of this might not be as relevant to vim users, but I think it is rather important. 

### Steps to reproduce

Described above.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: DESKTOP-IKHCORQ (Microsoft Windows 11 Enterprise)
  Vim version: NVIM v0.9.5
  Has clientserver: true
  Servername: \\.\pipe\nvim.268520.0

VimTeX project: test
  base: test.tex
  root: C:\Users\myusername\temp
  tex: C:\Users\myusername\temp/test.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 17
      output: C:\Users\myusername\AppData\Local\Temp\nvim.0\OSWATw\0
      cmd: set max_print_line=2000 & latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode  -pdf -pvc -pvctimeout- -view=none -e "$compiling_cmd = ($compiling_cmd ? $compiling_cmd . ' ^& ' : '') . 'echo vimtex_compiler_callback_compiling'" -e "$success_cmd = ($success_cmd ? $success_cmd . ' ^& ' : '') . 'echo vimtex_compiler_callback_success'" -e "$failure_cmd = ($failure_cmd ? $failure_cmd . ' ^& ' : '') . 'echo vimtex_compiler_callback_failure'" "test.tex"
      pid: 249308
  viewer: sioyek
    job: 
      pid: -
      cmd: sioyek.exe  --inverse-search "wsl nvim --headless -c \"VimtexInverseSearch %2 '%1'\"" --forward-search-file "C:\\Users\\myusername\\temp\\test.tex" --forward-search-line 6 "C:\\Users\\trinh\\temp/test.pdf"
    cmd_start: sioyek.exe  --inverse-search "wsl nvim --headless -c \"VimtexInverseSearch %2 '%1'\"" --forward-search-file "C:\\Users\\myusername\\temp\\test.tex" --forward-search-line 6 "C:\\Users\\trinh\\temp/test.pdf"
  qf method: LaTeX logfile
```
