### ISSUE TITLE
Autocompletion using '\' instead of '/' in paths (Windows 10)

### ISSUE THREAD

**Issue by Lucho32-byte** [lervag/vimtex#2954]
### Description

I'm currently using a Windows 10 Laptop (No WSL) but the autocompletion for the following path sources appears to be using backslash "\\" instead of "/":
- [include]
- [input]
- [includepdf]
- [includestandalone]

![imagen](https://github.com/lervag/vimtex/assets/68834994/de9f708a-f40e-4b6b-a854-eff874e11f16)
![imagen](https://github.com/lervag/vimtex/assets/68834994/e03437f8-28ea-44ec-b717-0c00ef169867)
![imagen](https://github.com/lervag/vimtex/assets/68834994/112e2f71-f84b-4e3b-b6d5-6a62d826167d)
![imagen](https://github.com/lervag/vimtex/assets/68834994/3521df44-dee8-4091-b115-ed56da671828)

However, [graphics] source seems to be working fine
![imagen](https://github.com/lervag/vimtex/assets/68834994/88c7d0cd-19ce-4219-b3c9-d5cf594827ee)

Currently as a workaround I've just modified the lines 478, 483, 504 and 525 from the file ``vimtex/autoload/vimtex/complete.vim`` with the function ``substitute`` to patch this behaviour:

```vim
          \ 'word': substitute(fnamemodify(x, ':r'), '\\', '/', 'g'),
          " or
          \ 'word': substitute(x, '\\', '/', 'g'),
```

### Steps to reproduce

1. Minimal folder structure
```
~\test/..
images
  └ stuff.pdf
 src
  │ firstsection.tex
  └ secondsection.tex
  main.tex
```
2. Minimal latex file
```tex
\documentclass[a4paper, 10pt]{article}
\begin{document}

% The problem's with the following commands
\input{}
\include{}
\includepdf{}
\includestandalone{}

% This works fine
\includegraphics{}

\end{document}
```

### Expected behavior

Autocompletion should use the '/' syntax for paths.

### Actual behavior

Instead, autocompletion is using the traditional Windows '\\' syntax.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: LAPTOP-H90H219I (Microsoft Windows 10 Home Single Language)
  Vim version: NVIM v0.9.5
  Has clientserver: true
  Servername: \\.\pipe\nvim.32700.0

VimTeX project: main
  base: main.tex
  root: C:\Users\LUIS\test
  tex: C:\Users\LUIS\test/main.tex
  main parser: fallback current file
  document class: 
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
