### ISSUE TITLE
Cannot call zathura from vimtex

### ISSUE THREAD

**Issue by CCandle** [lervag/vimtex#2955]
### Description

I use zathura as vimtex viewer, but zathura won't open while press '\\lv'. 

### Steps to reproduce

According to other issues, I'd tried to run 
```
zathura  -x "/opt/homebrew/Cellar/neovim/0.9.0/bin/nvim --headless -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 4:14:'/Users/ccandle/Coding/LaTeX/minimal/minimal.tex' 'build/minimal.pdf'&
```
 and it returned
```
error: Could not connect to session bus: Could not connect: No such file or directory
error: Got no usable data from SyncTeX or D-Bus failed in some way.

[1]  + 19760 exit 255   zathura -x  --synctex-forward  'build/main.pdf'
```
But if I remove the '--synctex-forward' option, run 
```
zathura  -x "/opt/homebrew/Cellar/neovim/0.9.0/bin/nvim --headless -c \"VimtexInverseSearch %{line} '%{input}'\"" 'build/minimal.pdf'&
```
 the zathura will open, and obviously the sync function can't work.

nvim calls 'plugins.vim' and the vimtex part is
```vim
let g:tex_flavor = 'latex'
let g:vimtex_view_method = 'zathura'
let g:vimtex_quickfix_mode = 0
let g:vimtex_quickfix_ignore_filters = [
      \ 'Underfull',
      \ 'Overfull'
      \ ]
let g:vimtex_compiler_latexmk_engines = {'_' : '-xelatex'}
let g:vimtex_compiler_latexmk = {
      \ 'build_dir': 'build',
      \ 'callback' : 1,
      \ 'continuous' : 1,
      \ 'executable' : 'latexmk',
      \ 'hooks' : [],
      \ 'options' : [
      \   '-verbose',
      \   '-file-line-error',
      \   '-shell-escape',
      \   '-synctex=1',
      \   '-interaction=nonstopmode',
      \ ],
      \}
let g:maplocalleader=' '
let g:view_enable=1
let g:view_automatic=1
let g:vimtex_texcount_custom_arg = '-ch -total'
```

### Expected behavior

zathura open with sync function.

### Actual behavior

zathura cannot open from vimtex.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 13.4 (22F66)
  Vim version: NVIM v0.9.0
  Has clientserver: true
  Servername: /var/folders/b6/m07vnt4d0mz87_00d_h5k_4c0000gn/T/nvim.ccandle/xklptI/nvim.20181.0

VimTeX project: minimal
  base: minimal.tex
  root: /Users/ccandle/Coding/LaTeX/minimal
  tex: /Users/ccandle/Coding/LaTeX/minimal/minimal.tex
  main parser: fallback current file
  document class: 
  compiler: latexmk
    engine: -xelatex
    options:
      -verbose
      -file-line-error
      -shell-escape
      -synctex=1
      -interaction=nonstopmode
    build_dir: build
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 10
      output: /var/folders/b6/m07vnt4d0mz87_00d_h5k_4c0000gn/T/nvim.ccandle/xklptI/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -shell-escape -synctex=1 -interaction=nonstopmode -xelatex -outdir=build -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'minimal.tex'
      pid: 20200
  viewer: Zathura
    xwin id: 0
    cmd_start: zathura  -x "/opt/homebrew/Cellar/neovim/0.9.0/bin/nvim --headless -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 4:14:'/Users/ccandle/Coding/LaTeX/minimal/minimal.tex' 'build/minimal.pdf'&
  qf method: LaTeX logfile
```
