### ISSUE TITLE
vimtex doesn't seem to recognise latexmkrc requesting lualatex

### ISSUE THREAD

**Issue by aaannestad** [lervag/vimtex#2956]
### Description

I'm trying to compile a file that uses the `fontspec` package, which requires xelatex or lualatex to run. My latexmkrc is set up to trigger that:

```perl
$latex = 'lualatex %O %S';
```

and indeed, the file compiles perfectly well if I run `latexmk file.tex` from the terminal (though it throws an error about creating a pdf when it expected a dvi file that I can't seem to do anything about). But running `\ll` in vimtex results in the compiler giving an error, and complaining that `fontspec` must be run with xelatex or lualatex - clearly indicating that whatever vimtex is doing to call `latexmk` is causing it to miss or ignore my latexmkrc.

To be clear, I'm trying to set this up in my latexmkrc file rather than just doing like `latexmk -lualatex` or whatever because I *never* want to compile with anything other than lualatex or xelatex (which is mostly interchangeable for me), whether that's inside or outside of vim. As far as I'm concerned, engines other than lualatex and xelatex may as well not exist. 

### Steps to reproduce

1. Create an MWE like the following:
```tex
\documentclass{article}
\usepackage{fontspec}
\setmainfont{ [[some font you have on your system]] }
\begin{document}
lorem ipsum
\end{document}
```

2. Ensure that `~/.config/latexmk/latexmkrc` contains the above `$latex = ...` line

3. Open your MWE and do `\ll`

### Expected behavior

Vimtex calls `latexmk`, which in turn calls `lualatex`, which compiles the file normally.

### Actual behavior

Vimtex calls `latexmk` in some way that does *not* in turn cause it to call `lualatex`, meaning you get a fatal error when `fontspec` checks to make sure you're using the right engine.

### Do you use a latexmkrc file?

Yes

### VimtexInfo

```yaml
System info:
  OS: Manjaro Linux
  Vim version: NVIM v0.9.5
  Has clientserver: true
  Servername: /run/user/1000/nvim.2986339.0

VimTeX project: test
  base: test.tex
  root: /home/USER/Documents/test
  tex: /home/USER/Documents/test/test.txt
  main parser: current file verified
  document class: article
  packages: expl3 fontspec xparse
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
