### ISSUE TITLE
Runtime compiler not using xelatex using `vimtex_compiler_latexmk`?

### ISSUE THREAD

**Issue by psr-ai** [lervag/vimtex#2959]
### Description

I am using the following configuration for `vimtex` plugin to use `xelatex`:

```
vim.g.vimtex_compiler_latexmk = {
  executable = 'latexmk',
  options = {
    '-xelatex',  -- Specifies the use of XeLaTeX
    '-file-line-error',
    '-synctex=1',
    '-interaction=nonstopmode',
  },
}
```

And my overall configuration looks like following:

```
-- Enable filetype detection, plugins, and indentation
vim.cmd('filetype plugin indent on')

-- Enable syntax highlighting
vim.cmd('syntax enable')


-- Configure the compiler for VimTeX
vim.g.vimtex_compiler_latexmk = {
  executable = 'latexmk',
  options = {
    '-xelatex',  -- Specifies the use of XeLaTeX
    '-file-line-error',
    '-synctex=1',
    '-interaction=nonstopmode',
  },
}

-- Configure the viewer method for VimTeX
vim.g.vimtex_view_method = 'skim'
vim.g.vimtex_view_skim_sync = 1
vim.g.vimtex_view_skim_activate = 1

vim.g.maplocalleader = ','
```

When I start the live compilation (using `,,` in command mode) for my tex file, I still get the following error:

```
/usr/local/texlive/2023/texmf-dist/tex/latex/fontspec/fontspec.sty|45 error| Fatal Package fontspec Error: The fontspec package requires either XeTeX or LuaTeX. You must change your typesetting engine to, e.g., "xelatex" or "lualatex" instead of "latex" or "pdflatex".
/usr/local/texlive/2023/texmf-dist/tex/latex/fontspec/fontspec.sty|45 error| Emergency stop.
/usr/local/texlive/2023/texmf-dist/tex/latex/fontspec/fontspec.sty|45 error| ==> Fatal error occurred, no output PDF file produced!
```

If I set the default compiler as follows:

```
vim.g.vimtex_compiler_latexmk_engines = {
  _ = '-xelatex',
  xelatex = '-xelatex',
  lualatex = '-lualatex',
}
```

I am able to use the `xelatex`. What am I doing wrong? I checked the variable value of `vim.g.vimtex_compiler_latexmk`, and it has the one provided in the configuration.

### Steps to reproduce

Use my configuration file in `vimtex.lua`

```-- Enable filetype detection, plugins, and indentation
vim.cmd('filetype plugin indent on')

-- Enable syntax highlighting
vim.cmd('syntax enable')


-- Configure the compiler for VimTeX
vim.g.vimtex_compiler_latexmk_engines = {
  _ = '-xelatex',
  xelatex = '-xelatex',
  lualatex = '-lualatex',
}

vim.g.vimtex_compiler_latexmk = {
  executable = 'latexmk',
  options = {
    '-xelatex',  -- Specifies the use of XeLaTeX
    '-file-line-error',
    '-synctex=1',
    '-interaction=nonstopmode',
  },
}

-- Configure the viewer method for VimTeX
vim.g.vimtex_view_method = 'skim'
vim.g.vimtex_view_skim_sync = 1
vim.g.vimtex_view_skim_activate = 1

vim.g.maplocalleader = ','

```

And run the compilation using `,,` after opening a `tex` file which needs `xelatex`.

### Expected behavior

There should be no error.

### Actual behavior

```
/usr/local/texlive/2023/texmf-dist/tex/latex/fontspec/fontspec.sty|45 error| Fatal Package fontspec Error: The fontspec package requires either XeTeX or LuaTeX. You must change your typesetting engine to, e.g., "xelatex" or "lualatex" instead of "latex" or "pdflatex".
/usr/local/texlive/2023/texmf-dist/tex/latex/fontspec/fontspec.sty|45 error| Emergency stop.
/usr/local/texlive/2023/texmf-dist/tex/latex/fontspec/fontspec.sty|45 error| ==> Fatal error occurred, no output PDF file produced!
```

### Do you use a latexmkrc file?

Not for the default configuration

### VimtexInfo

```yaml
System info:
  OS: macOS 14.2 (23C5055b)
  Vim version: NVIM v0.9.5
  Has clientserver: true
  Servername: /var/folders/j2/fp5195293sj3ncq9139kt5f40000gn/T/nvim.psr/dvFERi/nvim.96299.0

VimTeX project: resume
  base: resume.tex
  root: /Users/psr/GitLab/psr.ai/resume
  tex: /Users/psr/GitLab/psr.ai/resume/resume.tex
  main parser: current file verified
  document class: resume-openfont
  packages: array atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook babel bigintcalc bitset enumitem etexcmds expl3 fancyhdr font-color fontawesome fontenc fontspec fontspec-xetex geometry gettitlestring graphics graphicx hycolor hyperref ifluatex iftex ifvtex ifxetex infwarerr intcalc keyval kvdefinekeys kvoptions kvsetkeys lato-font letltxmacro ltxcmds metalogo nameref pdfescape pdftexcmds raleway-font realscripts refcount rerunfilecheck stringenc tabularx titlesec trig ulem uniquecounter url xcolor xltxtra xparse xunicode
  compiler: latexmk
    engine: -pdf
    options:
      -xelatex
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 6
      output: /var/folders/j2/fp5195293sj3ncq9139kt5f40000gn/T/nvim.psr/dvFERi/0
      cmd: max_print_line=2000 latexmk -xelatex -file-line-error -synctex=1 -interaction=nonstopmode  -pdf -pvc -pvctimeout- -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'resume.tex'
      pid: 96359
  viewer: Skim
  qf method: LaTeX logfile
```
