### ISSUE TITLE
Inconsistent syntax highlighting in subscript and superscript

### ISSUE THREAD

**Issue by shivangp76** [lervag/vimtex#2963]
### Description

Greek letters have inconsistent syntax highlighting when placed in a subscript or superscript.

### Steps to reproduce

`minimal.vim`
```vim
set nocompatible
let &runtimepath  = '~/.vim/bundle/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable
```

`minimal.tex`
```tex
\documentclass{article}
\begin{document}

$x_{\alpha}$

$x_{\beta}$

$x_{\gamma}$

$x_{\delta}$

$x_{\zeta}$

\end{document}
```

![image](https://github.com/lervag/vimtex/assets/30023891/763b9000-5bc6-4089-9dcf-f841b872f17c)

### Expected behavior

`\beta` and `\gamma` should have proper syntax highlighting

### Actual behavior

`\beta` and `\gamma` do *not* have proper syntax highlighting

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 14.3.1 (23D60)
  Vim version: NVIM v0.10.0
  Has clientserver: true
  Servername: /var/folders/t2/nx9mnq1j64v9kbrfqr2c04p40000gn/T/nvim.shivang/Ga8A5r/nvim.48783.0

VimTeX project: test
  base: test.tex
  root: /Users/shivang
  tex: /Users/shivang/test.tex
  main parser: current file verified
  document class: article
  packages: atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook bigintcalc bitset etoolbox gettitlestring hycolor hyperref iftex infwarerr intcalc keyval kvdefinekeys kvoptions kvsetkeys ltxcmds nameref pdfescape pdftexcmds refcount rerunfilecheck uniquecounter url
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    out_dir: /Users/shivang
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
