### ISSUE TITLE
How do I get rid of a "latexmk is not executable" error?

### ISSUE THREAD

**Issue by tomchor** [lervag/vimtex#2965]
### Description

I just installed `vimtex` and I'm loving it. However whenever I open a latex file I get the following error:

```
VimTeX: latexmk is not executable
Error detected while processing BufRead Autocommands for "*.tex"..function dist#ft#FTtex[49]..FileType Autocommands for "*"..function <SNR>12_LoadFTPlugin[18]..script /usr/share/vim/vimfiles
/ftplugin/tex_latexSuite.vim[12]../usr/share/vim/vimfiles/ftplugin/latex-suite/main.vim[969]../usr/share/vim/vimfiles/ftplugin/latex-suite/texviewer.vim:
line  895:
/usr/share/vim/vimfiles/ftplugin/latex-suite/bibtools.py:34: SyntaxWarning: invalid escape sequence '\s'
  """ 
```

I should say, I don't use, nor do I need, `latexmk`. So if a simple solution is to just tell `vimtex` to not try to look for `latexmk`, I'm fine with that!

Thank you so much.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Manjaro Linux
  Vim version: VIM 9.1 (1-445)
  Has clientserver: false

VimTeX project: headland
  base: headland.tex
  root: /home/tomas/Dropbox/headland
  tex: /home/tomas/Dropbox/headland/headland.tex
  main parser: current file verified
  document class: ametsocV6.1
  packages: booktabs hyperref ulem
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
