### ISSUE TITLE
supertab completion takes 20 seconds to complete a word when using many latex packages

### ISSUE THREAD

**Issue by thekswenson** [lervag/vimtex#2966]
### Description

When I want to retype a long word that is already in my document, I press `<tab>`, using the supertab plugin.  With vimtex enabled, it takes ~20 seconds to search all of the system tex libraries before showing the list of completions.

I'm filing a bug because this seems like it shouldn't be normal behavior. If it is normal, I'll close the bug.  In that case, is there a workaround to get vimtex to stop searching ALL of the `.sty` (etc.) files on my system?

### Steps to reproduce

1. open the minimal example
2. start typing a word that is already in the document, and press `<tab>`

```vim
" set the runtime path to include Vundle and initialize
set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'ervandew/supertab'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin on

set nocompatible
let &runtimepath  = '~/.vim/bundle/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable
```

```tex
\documentclass{minimal}

\usepackage{hyperref}
\hypersetup{hidelinks}
\usepackage{graphicx}
\usepackage{xspace}
\usepackage{xcolor}
\usepackage{subcaption}
\usepackage{amssymb,amsmath,amsthm}
\usepackage{algorithm,algorithmicx}
\usepackage[noend]{algpseudocode}
\usepackage{todonotes}
\usepackage{tikz,paralist,ifthen}  % For optproblem.

\begin{document}
Hello world!
\end{document}
```

### Expected behavior

I expect a list of completions to show up in a reasonable amount of time.

### Actual behavior

The list shows up after almost 20 seconds.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 24.04 LTS
  Vim version: VIM 9.1 (1-16)
  Has clientserver: true
  Servername: undefined (vim started without --servername)

VimTeX project: minimal2
  base: minimal2.tex
  root: /home/kms
  tex: /home/kms/minimal2.tex
  main parser: current file verified
  document class: minimal
  packages: algorithm algorithmicx algpseudocode amsmath amssymb amsthm graphicx
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
