### ISSUE TITLE
Inverse search does not work with sioyek

### ISSUE THREAD

**Issue by khumarahn** [lervag/vimtex#2967]
### Description

Hi!

With the default config, inverse search should just work, but it doesn't. Not sure where to start.

```
Sioyek ~
https://sioyek.info/
Sioyek is a PDF viewer designed for reading research papers and technical
books.

Configuration: >vim
  let g:vimtex_view_method = 'sioyek'

Inverse search should be automatically configured and work out of the box.
VimTeX will try to pass options to Sioyek to automatically configure inverse
search. This means that, in most cases, inverse search should work as expected
without any further configuration. One may still be interested in learning how
inverse-search configuration works, in which case one should read
|vimtex-synctex-inverse-search|. The interpolation variables for Sioyek
configuration are `%2` and `%1`, not `%l` and `%f`.
```

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Gentoo Linux
  Vim version: VIM 9.0 (1-2167)
  Has clientserver: true
  Servername: GVIM

VimTeX project: hyp.29
  base: hyp.29.tex
  root: /home/khu/cloud/2017_02_22-Markov-YT/hyp
  tex: /home/khu/cloud/2017_02_22-Markov-YT/hyp/hyp.29.tex
  main parser: current file verified
  document class: article
  packages: amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm array atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook bigintcalc bitset calc defpattern enumitem epstopdf-base etexcmds expl3 fp fp-addons fp-basic fp-eqn fp-eval fp-exp fp-pas fp-random fp-snap fp-trigo fp-upn fullpage gettitlestring graphics graphicx hycolor hyperref iftex infwarerr intcalc keyval kvdefinekeys kvoptions kvsetkeys letltxmacro ltxcmds mathtools mhsetup nameref numprint pdfescape pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfplots pgfrcs pgfsys refcount rerunfilecheck tikz tikz-cd tkz-base tkz-euclide trig uniquecounter url xcolor xfp
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: process 1045782 run
      output: /tmp/vsUHX6k/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode  -pdf -pvc -pvctimeout- -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'hyp.29.tex'
      pid: 1045782
  viewer: sioyek
    job: 
      pid: 1045786
      cmd: /opt/sioyek/sioyek  --inverse-search "/usr/bin/gvim -T dumb --not-a-term -n -c \"VimtexInverseSearch %2 '%1'\"" --forward-search-file '/home/khu/cloud/2017_02_22-Markov-YT/hyp/hyp.29.tex' --forward-search-line 173 '/home/khu/cloud/2017_02_22-Markov-YT/hyp/hyp.29.pdf'
    cmd_start: /opt/sioyek/sioyek  --inverse-search "/usr/bin/gvim -T dumb --not-a-term -n -c \"VimtexInverseSearch %2 '%1'\"" --forward-search-file '/home/khu/cloud/2017_02_22-Markov-YT/hyp/hyp.29.tex' --forward-search-line 173 '/home/khu/cloud/2017_02_22-Markov-YT/hyp/hyp.29.pdf'
  qf method: LaTeX logfile
```
