### ISSUE TITLE
package 'unicode-math' yields compile error

### ISSUE THREAD

**Issue by rhscdn** [lervag/vimtex#2970]
### Description

Using nvim with the basic lua lazy.nvim install suggested. I'm seeing an error when put `\usepackage{unicode-math}` in my preamble that reads

```
/usr/share/texlive/texmf-dist/tex/latex/unicode-math/unicode-math.sty:40: Package unicode-math Error: Cannot be run with pdftex!
```

Running `latexmk` on the command-line works just fine and my understanding is that vimtex is running latexmk on its backend?

### Steps to reproduce

```tex
\documentclass{minimal}
% Comment/uncomment line below
\usepackage{unicode-math}
\begin{document}
Hello world!
\end{document}
```

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 24.04 LTS
  Vim version: NVIM v0.11.0-dev
  Has clientserver: true
  Servername: /run/user/1000/nvim.97029.0

VimTeX project: ch1
  base: ch1.tex
  root: ~/Documents/vaults/testing/1-Source/mghr_chem11
  tex: ~/Documents/vaults/testing/1-Source/mghr_chem11/ch1.tex
  main parser: current file verified
  document class: article
  packages: amsbsy amsgen amsmath amsopn amstext array calc chemgreek color epstopdf-base etoolbox expl3 fix-cm fontenc fontspec fontspec-luatex graphics iftex infwarerr l3keys2e ltxcmds lualatex-math mhchem pdftexcmds siunitx translations trig unicode-math unicode-math-luatex xparse
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
