### ISSUE TITLE
viewer shouldn't open automatically when compilation finished

### ISSUE THREAD

**Issue by hongy19** [lervag/vimtex#2972]
### Description

viewer doesn't open automatically when compilation finished for vimtex 2.15, 2.14 but 2.11 could works with same .vimrc configuration and tex file.

```
14:56:50: info
  #0 /home/hongy19/.vim/plugged/vimtex/autoload/vimtex/compiler.vim:240
  In vimtex#compiler#start
    call vimtex#log#info('Compiler started in continuous mode')
  #1 /home/hongy19/.vim/plugged/vimtex/autoload/vimtex/compiler.vim:120
  In vimtex#compiler#compile
    call call('vimtex#compiler#start', a:000)
  Compiler started in continuous mode

14:56:51: info
  #0 /home/hongy19/.vim/plugged/vimtex/autoload/vimtex/compiler.vim:82
  In vimtex#compiler#callback
    call vimtex#log#info('Compilation completed')
  #1 /home/hongy19/.vim/plugged/vimtex/autoload/vimtex/compiler/_template.vim:503
  In s:check_callback
    call vimtex#compiler#callback(l:status)
  #2 /home/hongy19/.vim/plugged/vimtex/autoload/vimtex/compiler/_template.vim:397
  In s:callback_continuous_output
    call s:check_callback(a:msg)
  Compilation completed
```

### Expected behavior

viewer should automatically launch after compilation finished.

### Actual behavior

viewer doesn't automatically launch after compilation finished. but viewer could be launch with command `lv`

### Do you use a latexmkrc file?

yes

### VimtexInfo

```yaml
System info:
  OS: Linux 5.15.153.1-microsoft-standard-WSL2
  Vim version: VIM 9.1 (1-445)
  Has clientserver: false

VimTeX project: elog
  base: elog.tex
  root: /home/hongy19/dev/latex/myTex
  tex: /home/hongy19/dev/latex/myTex/elog.tex
  main parser: current file verified
  document class: article
  packages: amsbsy amsfonts amsgen amsmath amsopn amssymb amstext csvsimple csvsimple-legacy etoolbox expl3 fancyvrb gobble graphics graphicx ifthen
  compiler: latexmk
    engine: -xelatex
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    out_dir: latex.out
    callback: 1
    continuous: 1
    executable: latexmk
    job:
      jobid: process 16048 run
      output: /tmp/vLz54Lh/1
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode  -xelatex -outdir=latex.out -pvc -pvctimeout- -
      pid: 16048
  viewer: MuPDF
    xwin id: 0
    job:
      pid: 16053
      cmd: mupdf '/home/hongy19/dev/latex/myTex/latex.out/elog.pdf'
    cmd_start: mupdf '/home/hongy19/dev/latex/myTex/latex.out/elog.pdf'
  qf method: LaTeX logfile
```
