### ISSUE TITLE
Vimtex: Viewer cannot find Zathura window ID

### ISSUE THREAD

**Issue by coycatrett** [lervag/vimtex#2973]
### Description

When I want to view a converted pdf file from latex using zathura, vimtex reports back with "Vimtex: Viewer cannot find Zathura window ID".

Zathura version:

```
zathura 0.4.9
girara 0.3.7 (runtime: 0.3.7)
(plugin) pdf-poppler (0.3.0) (/usr/lib/x86_64-linux-gnu/zathura/libpdf-poppler.so)
```

minimal vimtex.lua file:
```
return {
    'lervag/vimtex',
    lazy = false,
    init = function()
        vim.cmd('filetype plugin indent on') -- Edit
        vim.g.vimtex_view_method = 'zathura'
    end
}
```

**Edit:** added `vim.cmd('filetype plugin indent on')` to init function and now the Zathura window appears after executing `:VimtexView`. This did not fix the errors below with the lazy reloading nor get rid of the initial error message that the viewer cannot find the zathura window ID.

File tree & Lazy.lua file:

<img width="751" alt="lazy lua" src="https://github.com/lervag/vimtex/assets/63897775/02cc3ccd-ffab-4d46-aa84-0248e09ce75a">

Minimal tex:

```tex
\documentclass{article}

\begin{document}
Hello World!
\end{document}
```

When I run `:VimtexView` in the minimal tex document, this error message appears:

```
Vimtex: Viewer cannot find Zathura window ID!
```

When I reload vimtex with lazy, here is what it reports:

```
Failed to deactivate plugin vimtex

...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:212: module 'vimtex' not found:
^Ino field package.preload['vimtex']
cache_loader: module vimtex not found
cache_loader_lib: module vimtex not found
^Ino file './vimtex.lua'
^Ino file '/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1/vimtex.lua'
^Ino file '/usr/local/share/lua/5.1/vimtex.lua'
^Ino file '/usr/local/share/lua/5.1/vimtex/init.lua'
^Ino file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/vimtex.lua'
^Ino file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/vimtex/init.lua'
^Ino file '/home/ccatrett/.local/share/nvim/lazy-rocks/telescope.nvim/share/lua/5.1/vimtex.lua'
^Ino file '/home/ccatrett/.local/share/nvim/lazy-rocks/telescope.nvim/share/lua/5.1/vimtex/init.lua'
^Ino file './vimtex.so'
^Ino file '/usr/local/lib/lua/5.1/vimtex.so'
^Ino file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/vimtex.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
^Ino file '/home/ccatrett/.local/share/nvim/lazy-rocks/telescope.nvim/lib/lua/5.1/vimtex.so'
```

The relevant results after running `checkhealth`:

```
==============================================================================
lazy: require("lazy.health").check()

lazy.nvim ~
- {lazy.nvim} version `11.9.0`
- OK {git} `version 2.34.1`
- OK no existing packages found by other package managers
- OK packer_compiled.lua not found

luarocks ~
- checking `luarocks` installation
- OK no plugins require `luarocks`, so you can ignore any warnings below
- OK {luarocks} `/usr/bin/luarocks 3.8.0`
- OK {lua5.1} `Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio`

==============================================================================
nvim: require("nvim.health").check()

Configuration ~
- OK no issues found

Runtime ~
- OK $VIMRUNTIME: /opt/nvim-linux64/share/nvim/runtime

Performance ~
- OK Build type: Release

Remote Plugins ~
- OK Up to date

terminal ~
- key_backspace (kbs) terminfo entry: `key_backspace=\177`
- key_dc (kdch1) terminfo entry: `key_dc=\E[3~`

External Tools ~
- OK ripgrep 13.0.0 (/usr/bin/rg)

==============================================================================
vimtex: health#vimtex#check

VimTeX ~
- OK Vim version should have full support!
- OK Zathura should work properly!
- OK Compiler should work!
```

### Steps to reproduce

1. cd to a location containing a .tex file, say test.tex
2. nvim test.tex
3. :VimtexCompile

### Expected behavior

Zathura opens the pdf with no error message from neovim displaying, 'Vimtex: Viewer cannot find Zathura window ID'

### Actual behavior

Zathura opens the pdf with an error message from neovim displaying 'Vimtex: Viewer cannot find Zathura window ID'

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 22.04.4 LTS
  Vim version: NVIM v0.10.0
  Has clientserver: true
  Servername: /run/user/1000//nvim.25398.0

VimTeX project: test
  base: test.tex
  root: /home/ccatrett
  tex: /home/ccatrett/test.tex
  main parser: fallback current file
  document class: 
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 7
      output: /tmp/nvim.ccatrett/Fp8QMy/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode  -pdf -pvc -pvctimeout- -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'test.tex'
      pid: 32026
  viewer: Zathura
    xwin id: 0
    cmd_start: zathura  -x "/opt/nvim-linux64/bin/nvim --headless -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 5:3:'/home/ccatrett/test.tex' 'test.pdf'&
  qf method: LaTeX logfile
```
