### ISSUE TITLE
vimtex compilation fails despite compiling successfully when done from command line

### ISSUE THREAD

**Issue by Espacio-root** [lervag/vimtex#2974]
### Description

I'm generating `.tex` files from `.ipynb` via `jupyter nbconvert`

When running `latexmk -f -pdf test.tex` from the command line, it reports some errors but eventually does generate a pdf. The same, unfortunately, cannot be said about vimtex when executing `:VimtexCompile` from neovim

### Steps to reproduce

1. unzip `hello_world.zip` to obtain `hello_world.tex`
    [hello_world.zip](https://github.com/user-attachments/files/16074064/hello_world.zip)

2. attempt to compile via neovim with the following config:
    ```lua
    vim.g.vimtex_view_method = "zathura"
    vim.g.tex_flavour = "latex"
    vim.g.vimtex_quickfix_mode = 0
    vim.g.vimtex_compiler_method = "latexmk"
    vim.cmd[[set conceallevel=2]]
    vim.g.vimtex_compiler_latexmk = {
      continuous = 1,
      options = {
        "-f",
        "-file-line-error",
        "-interaction=nonstopmode"
      }
    }
    ```

### Expected behavior

The file should report the encountered errors, but eventually compile

### Actual behavior

The file does not compile

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Linux 6.9.7-zen1-1-zen
  Vim version: NVIM v0.11.0-dev-313+gfc9b70826e
  Has clientserver: true
  Servername: /run/user/1000/nvim.561445.0

VimTeX project: hello_world
  base: hello_world.tex
  root: /home/espacio/notes/ml
  tex: /home/espacio/notes/ml/hello_world.tex
  main parser: current file verified
  document class: article
  packages: adjcalc adjustbox alphabeta amsbsy amsfonts amsgen amsmath amsopn amssymb amstext array atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook bigintcalc bitset booktabs calc caption caption3 collectbox color enumerate enumitem environ epstopdf-base etexcmds etoolbox eurosym fancyvrb float fontenc fontspec geometry gettitlestring graphics graphicx grffile hycolor hyperref ifoddpage iftex ifvtex infwarerr inputenc intcalc keyval kvdefinekeys kvoptions kvsetkeys longtable ltcaption ltxcmds mathrsfs nameref parskip pdfcol pdfescape pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgfrcs pgfsys refcount rerunfilecheck soul soul-ori tcolorbox textcomp titling trig trimclip trimspaces ucs ulem unicode-math uniquecounter upquote url varwidth verbatim xcolor xkeyval
  compiler: latexmk
    engine: -pdf
    options:
      -f
      -file-line-error
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
