### ISSUE TITLE
WSL2: Viewer cannot find Zathura window ID!

### ISSUE THREAD

**Issue by Kaiser-Yang** [lervag/vimtex#2980]
### Description

I'm using `wsl2` and `ubuntu 22.04`. When I use `:VimtexView` to open the viewer, it works well. However, after opening the viewer, when I press `j` or `k` to navigate in the neovim. It gives me the information: `Viewer cannot find Zathura window ID!`

### Steps to reproduce

1. Install vimtex with lazy.nvim
2. Use the configuration only specifying the viewer

### Expected behavior

I can use `j` and `k` to scroll up or down.

### Actual behavior

`Viewer cannot find Zathura window ID!`

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 22.04.4 LTS
  Vim version: NVIM v0.10.0
  Has clientserver: true
  Servername: /run/user/1000//nvim.4380.0

VimTeX project: main
  base: main.tex
  root: /home/kaiser
  tex: /home/kaiser/main.tex
  main parser: current file verified
  document class: article
  packages: amsbsy amsgen amsmath amsopn amstext
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
    cmd_start: zathura  -x "/opt/nvim-linux64/bin/nvim --headless -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 30:25:'/home/kaiser/main.tex' 'main.pdf'&
  qf method: LaTeX logfile
```
