### ISSUE TITLE
-shell-escape and pygments for minted

### ISSUE THREAD

**Issue by alhazacod** [lervag/vimtex#2982]
### Description

I need to use minted and i already added the -shell-escape to the latexmkoptions and have python-pygments installed but when i compile it still give me the same two errors: 
`Package minted Error: You must invoke LaTeX with the -shell-escape flag.`
`Package minted Error: You must have 'pygmentize' installed to use this package.`

My vimtex configuration:
```
return {
  "lervag/vimtex",
  lazy = false,     -- we don't want to lazy load VimTeX
  -- tag = "v2.15", -- uncomment to pin to a specific release
  init = function()
    -- VimTeX configuration goes here, e.g.
    vim.g.vimtex_view_method = "zathura"
    vim.g.vimtex_compiler_method = 'latexmk'
    vim.g.vimtex_compiler_latexmk = {
        options = {
            '-shell-escape',
            '-verbose',
            '-file-line-error',
            '-interaction=nonstopmode',
            '-synctex=1'
        }
    }

  end
}
```
When i run `pygmentize -V`:

`Pygments version 2.18.0, (c) 2006-2024 by Georg Brandl, Matthäus Chajdas and contributors.`

Someone have any idea why it's happening?

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
System info:
  OS: Linux 6.9.10-arch1-1
  Vim version: NVIM v0.10.0
  Has clientserver: true
  Servername: /run/user/1000/nvim.30839.0

VimTeX project: main
  base: main.tex
  root: /home/alhazacod/Documents/relatividad_general_physics_latam/tarea3
  tex: /home/alhazacod/Documents/relatividad_general_physics_latam/tarea3/main.tex
  main parser: current file verified
  document class: article
  packages: amsbsy amsfonts amsgen amsmath amsopn amssymb amstext calc catchfile color environ epstopdf-base etexcmds etoolbox expl3 fancyvrb float framed fvextra geometry graphics graphicx ifluatex ifplatform iftex ifthen ifvtex infwarerr inputenc keyval kvoptions kvsetkeys lineno listings listingsutf8 lstmisc lstpatch ltxcmds minted pdfcol pdfescape pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfrcs pgfsys physics shellesc stringenc tcolorbox textcomp tikz tikzfill-common tikzfill.image titling trig trimspaces upquote verbatim xcolor xparse xstring
  compiler: latexmk
    engine: -pdf
    options:
      -shell-escape
      -verbose
      -file-line-error
      -interaction=nonstopmode
      -synctex=1
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 6
      output: /tmp/nvim.alhazacod/DnwYRH/0
      cmd: max_print_line=2000 latexmk -shell-escape -verbose -file-line-error -interaction=nonstopmode -synctex=1  -pdf -pvc -pvctimeout- -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'main.tex'
      pid: 30909
  viewer: Zathura
    xwin id: 35651587
    cmd_start: zathura  -x "/usr/bin/nvim --headless -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 18:1:'/home/alhazacod/Documents/relatividad_general_physics_latam/tarea3/main.tex' 'tarea3/main.pdf'&
  qf method: LaTeX logfile
```

EDIT: it works well when i compile with `latexmk -shell-escape -verbose -file-line-error -interaction=nonstopmode -synctex=1 -pdf main.tex`
