### ISSUE TITLE
Square brackets unnecessarily concealed

### ISSUE THREAD

**Issue by simonmandlik** [lervag/vimtex#2984]
### Description

In text environments like `texttt`, `textit`,  or `textbf`, square brackets are concealed and replaced with no other character.

Is this a bug or feature?

Thanks for the great plugin!

### Steps to reproduce

1. `nvim -u minimal.lua test.tex`
2. Insert `\textit{[]}` and skip to next line
3. Square brackets in italics are not shown

`minimal.lua`:

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
    spec = {
        { "folke/flash.nvim", opts = {} },
        -- add any other plugins here
        { "lervag/vimtex" }
    }
})

vim.opt.conceallevel = 2
```

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 14.5 (23F79)
  Vim version: NVIM v0.10.1
  Has clientserver: true
  Servername: /var/folders/pr/bshcrht5423cbhtz_ls_h_7r0000gp/T/nvim.simon.mandlik/3STFIJ/nvim.901

VimTeX project: test
  base: test.tex
  root: /Users/simon.mandlik/Downloads
  tex: /Users/simon.mandlik/Downloads/test.tex
  main parser: fallback current file
  document class:
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
