### ISSUE TITLE
Vimtex doesn't like any tex file that includes `\startdate{}`

### ISSUE THREAD

**Issue by 0804d23d** [lervag/vimtex#2987]
### Description

I have been running into some troubles with a project with multiple vim files all of a sudden, and it appears that this issue only occurs in that specific directory. But as I tried to come up with a set of minimal test files, I noticed that by introducing `\startdate{}`, I had inadvertently made vimtex very unhappy.

### Steps to reproduce

1. Create an empty tex file anywhere, then open it in vim (vimtex still works properly at this point).
2. Add the following to the file, and if I close vim and reopen that file, vimtex will now stop working:

    ```tex
    \startdate{}
    ```

### Expected behavior

vimtex should load properly as if that line is not there, but apparently, just by adding that line, things will stop working.

(Although something like `\def\startdate#1{\def\@startdate{#1}}` is ok.)

### Actual behavior

vimtex will not load at all, and if I'm working with a multi-file project, then I'll get
<img width="898" alt="Untitled" src="https://github.com/user-attachments/assets/24d82082-5c5d-4d0a-bc6e-6bed475dc76d">

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
I can't call `:VimtexInfo` when I have `\startdate{}` in the tex doc, but otherwise, I have



  OS: macOS 14.1.2 (23B92)
  Vim version: VIM 9.0 (1-1897)
  Has clientserver: true
  Servername: VIM

VimTeX project: main
  base: main.tex
  root: redacted
  tex: redacted
  main parser: recursive search
  document class: article
  packages: afterpage amsbsy amsgen amsmath amsopn amstext array atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook background bbding bigintcalc bitset booktabs calc cancel caption caption3 catchfile color colortbl environ epstopdf-base eso-pic etexcmds etoolbox everypage expl3 fancyhdr fancyvrb float framed fvextra geometry gettitlestring graphics graphicx helvet hycolor hyperref ifluatex ifoddpage ifplatform iftex ifthen ifvtex infwarerr intcalc keyval kvdefinekeys kvoptions kvsetkeys lastpage lastpage2e lastpagemodern letltxmacro lineno listings lmodern lscape lstmisc ltxcmds minted nameref natbib nopageno parskip pdfcol pdfescape pdflscape pdflscape-nometadata pdfpages pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfrcs pgfsys physics pifont refcount rerunfilecheck shellesc soul soul-ori tcolorbox textcomp tikz tikzfill-common tikzfill.image tikzpagenodes trig trimspaces txfonts uniquecounter upquote url varwidth verbatim xcolor xkeyval xparse xstring
  source files:
    main.tex
    preamble.tex
    redacted
  compiler: latexmk
    engine: -pdf -pdflatex="pdflatex -shell-escape %O %S"
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    aux_dir: ./aux
    callback: 1
    continuous: 0
    executable: latexmk
    job: 
      jobid: process 8082 dead
      output: redacted
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode  -pdf -pdflatex="pdflatex -shell-escape %O %S" -emulate-aux-dir -auxdir=./aux 'main.tex'
  viewer: Skim
  qf method: LaTeX logfile
```
