### ISSUE TITLE
MuPDF not updating on write

### ISSUE THREAD

**Issue by samstevens127** [lervag/vimtex#2991]
### Description

When I write to a file after editing it, VimTeX says compilation completed, however the edits are not reflected on my MuPDF window.

### Steps to reproduce

1. nvim test.tex
2. add hello word to test.tex(same body as in the minimal.tex file in the template)
3. run VimtexCompile
4. MuPDF prints hello world
5. Make edit to document body
6. write changes
7. VImTeX: Compilation completed message shows
8. MuPDF still shows initial compilation output

My init.lua:
```
vim.wo.relativenumber = true
vim.wo.number = true

local vim = vim
local Plug = vim.fn['plug#']

vim.call('plug#begin')


Plug('lervag/vimtex')


vim.call('plug#end')


vim.g.vimtex_view_general_viewer = 'mupdf'
vim.g.tex_flavor = 'latex'
```

### Expected behavior

I expected MuPDF to update and show the edits when I wrote.

### Actual behavior

MuPDF window did not reflect edits.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Gentoo Linux
  Vim version: NVIM v0.9.5
  Has clientserver: true
  Servername: /run/user/1000/nvim.3568.0

VimTeX project: minimal
  base: minimal.tex
  root: /home/sam
  tex: /home/sam/minimal.tex
  main parser: current file verified
  document class: minimal
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
