### ISSUE TITLE
when set to true, option vimtex_format_enabled makes neovim hangs when reflowing paragraph 

### ISSUE THREAD

**Issue by nchopin** [lervag/vimtex#2992]
### Description

While editing a latex file, if I I try to reflow a paragraph (gqap), neovim freezes. This happens only when I set option `g:vimtex_format_enabled` to 1. If I set to 0, neovim does not freeze.

MRE: a simple tex file with one paragraph (does not need to be a proper tex file, just one Lorem Ipsum paragraph).

* vim flavour: neovim v0.9.5
* OS: Ubuntu 24.04.1
* vimtex: latest (installed through Plug)

### Steps to reproduce

1. Make sure your `init.vim` contains the line: `let g:vimtex_format_enabled = 1`
2. Open file `lorem.tex` (first Lorem ipsum paragraph)
3. Type `gqap`
4. neovim hangs
5. Type Ctrl-C

```tex
% lorem.tex
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent id magna neque. Morbi imperdiet, massa a auctor mollis, felis purus dictum nunc, et elementum velit ex vitae nulla. Donec consequat purus vitae ante pretium, a interdum sapien congue. Donec consequat euismod imperdiet. Maecenas nulla lectus, dignissim in dui sed, posuere suscipit mi. Nulla vel ex nec odio mollis porta. Nulla at tristique tellus. Nam porttitor luctus elit a commodo. Fusce nec lectus id ipsum lacinia fringilla. Nunc vitae felis id purus tempus rhoncus sed non velit. Nunc faucibus aliquam est eu commodo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam suscipit porta orci, non finibus ante venenatis ut. Morbi quam est, pretium sit amet lorem at, accumsan pharetra nunc.
```

### Expected behavior

neovim does not hang.

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 24.04.1 LTS
  Vim version: NVIM v0.9.5
  Has clientserver: true
  Servername: /run/user/1000/nvim.189443.0

VimTeX project: lorem
  base: lorem.tex
  root: /home/manxac/.config/nvim
  tex: /home/manxac/.config/nvim/lorem.tex
  main parser: fallback current file
  document class: 
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
