### ISSUE TITLE
Minimal vimtex config example for Linux Wayland with Mupdf (ideally for Neovim) and Latexmk

### ISSUE THREAD

**Issue by banana59** [lervag/vimtex#2995]
### Description

Hello,

this is not a issue perse, rather a request. I can't manage to find a config example for vimtex on Linux using Wayland with Mupdf (for Neovim) using Latexmk.
I want to use mupdf since it is also available on windows (or any other pdf viewer available on both OS's). I have read the sections of the documentation regarding Mupdf and couldn't find a valid example using this combination. 

### Steps to reproduce

My minimal vimtex configuration looks like
```lua
vim.g.vimtex_view_method = 'mupdf'

-- Additional vimtex configurations
vim.g.vimtex_compiler_latexmk = {
    build_dir = '.out',
    options = {
        '-shell-escape',
        '-verbose',
        '-file-line-error',
        '-interaction=nonstopmode',
        '-synctex=1'
    }
}
```

### Expected behavior

1. I couldn't find ways to _automatically update Mupdf after the pdf-file change_. Can this be automated?
2. Can the plugin be configured so that it uses the existing window if there is already one window instance open.

### Actual behavior

1. Mupdf have to be manually refreshed using the r key. There is a send_keys option I have already seen, but this seem to happen only once at the beginning if I understand this correct.
2. Pressing _<leader>lv_ opens another instance of the pdf viewer mupdf. 

### Do you use a latexmkrc file?

No, though I have tried $dvi_update_method=2 and $new_viewer_always=0

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 22.04.4 LTS
  Vim version: NVIM v0.10.0
  Has clientserver: true
  Servername: /run/user/1000//nvim.3975.0

VimTeX project: a
  base: a.tex
  root: /tmp
  tex: /tmp/a.tex
  main parser: current file verified
  document class: article
  packages: inputenc
  compiler: latexmk
    engine: -pdf
    options:
      -shell-escape
      -verbose
      -file-line-error
      -interaction=nonstopmode
      -synctex=1
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: MuPDF
    xwin id: 0
  qf method: LaTeX logfile
```
