### ISSUE TITLE
strange bug with `ts$`

### ISSUE THREAD

**Issue by ces42** [lervag/vimtex#2998]
### Description

I stumbled upon this strange bug. It seems to be very rare so rather low-priority. I can try to look into what's happening once I'm less busy...

### Steps to reproduce

1. put this into a tex file

    ```tex
    \[
        \{x \vert \text{$1$ $2$ $3$}\}
        y
    \]
    ```

2. move the cursor to y and do `ts$`

### Expected behavior

`\[ ... \]` should turn to `\begin{equation} ... \end{equation}`

### Actual behavior

nothing happens. If the cursor is in the first line of the displaymath everything seems to work fine. If I delete the `$3$` things also work fine.

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 23.10
  Vim version: NVIM v0.11.0-dev-650+ge961627956
  Has clientserver: true
  Servername: /run/user/1000/nvim.370829.0

VimTeX project: tex
  base: tex.tex
  root: /home/ca/build/vimtex/test/perf-syntax
  tex: /home/ca/build/vimtex/test/perf-syntax/tex.tex
  main parser: fallback current file
  document class: 
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
