### ISSUE TITLE
invalid value for argument cmd: 'kill' is not executable - when compiling tex file

### ISSUE THREAD

**Issue by TomzBench** [lervag/vimtex#2999]
### Description

After successful compile via the default `<localleader>ll` ...My terminal errors with:

```
VimTeX: Compilation completed
Error detected while processing function <SNR>70_callback_nvim_output[8]..<SNR>70_check_callback[4]..vimtex#compiler#callback[40]..User Autocommands for "VimtexEventCompileSuccess"..function vimtex#view#compiler_callback[7]..81[7]..237:    
line    3:
E475: Invalid value for argument cmd: 'kill' is not executable
Press ENTER or type command to continue 
```
I'm using Nvim 10.1 on windows 10.  I think it might be a windows issue.

### Steps to reproduce

1. Navigate to a simple .tex file that will compile
2. `<localleader>ll`

### Expected behavior

Just the PDF viewer should open up, and no error

### Actual behavior

A PDF viewer and a Console will open up - and the terminal will output the error as described in the description

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
System info:
  OS: DESKTOP-1U4SAH1 (Microsoft Windows 11 Pro for Workstations)
  Vim version: NVIM v0.10.1
  Has clientserver: true
  Servername: \\.\pipe\nvim.23896.0

VimTeX project: algebra
  base: algebra.tex
  root: C:\Users\tom\Git\Notes\algebra
  tex: C:\Users\tom\Git\Notes\algebra/algebra.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 7
      output: C:\Users\tom\AppData\Local\Temp\nvim.0\E5fu6D\0
      cmd: set max_print_line=2000 & latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode  -pdf -pvc -pvctimeout- -view=none -e "$compiling_cmd = ($compiling_cmd ? $compiling_cmd . ' ^& ' : '') . 'echo vimtex_compiler_callback_compiling'" -e "$success_cmd = ($success_cmd ? $success_cmd . ' ^& ' : '') . 'echo vimtex_compiler_callback_success'" -e "$failure_cmd = ($failure_cmd ? $failure_cmd . ' ^& ' : '') . 'echo vimtex_compiler_callback_failure'" "algebra.tex"
      pid: 33580
  viewer: MuPDF
    xwin id: 0
    job: 
      pid: -
      cmd: mupdf "C:\\Users\\tom\\Git\\Notes\\algebra/algebra.pdf"
    cmd_start: mupdf "C:\\Users\\tom\\Git\\Notes\\algebra/algebra.pdf"
  qf method: LaTeX logfile
```
