### ISSUE TITLE
Inconsistent spacing of concealed math symbols

### ISSUE THREAD

**Issue by Unturned3** [lervag/vimtex#3002]
### Description

When concealing the `\big` command in math mode, the indentation & spacing of the concealment is messed up. Same issue happens for `\bigg, \Big, \Bigg`.

### Steps to reproduce

Run `nvim -u minimal.vim minimal.tex`.

**minimal.vim**
```vim
set nocompatible
let &runtimepath  = '~/.local/share/nvim/plugged/vimtex,' . &runtimepath
let &runtimepath .= ',~/.local/share/nvim/plugged/vimtex/after'
filetype plugin indent on
syntax enable
set conceallevel=2
```

**minimal.tex**
```tex
\documentclass{minimal}
\begin{document}
\begin{align}
	\big| x \big|
\end{align}
\end{document}
```

### Expected behavior

Concealed display:
```tex
\begin{align*}
        |x|
\end{align*}
```

### Actual behavior

Concealed display:
```tex
\begin{align*}
| x|
\end{align*}
```

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 12.7.1 (21G920)
  Vim version: NVIM v0.10.1
  Has clientserver: true
  Servername: /var/folders/3d/_tm29bhn48l851qxdsg5w39m0000gn/T/nvim.ut/7TudbN/nvim.23134.0

VimTeX project: minimal
  base: minimal.tex
  root: ~/bug
  tex: ~/bug/minimal.tex
  main parser: current file verified
  document class: minimal
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
