### ISSUE TITLE
Previewer is non functional with zathura method

### ISSUE THREAD

**Issue by Felipe-9** [lervag/vimtex#3003]
### Description

Previewer is not working, whenever i try to do `\lv` or `:VimtexView` nothing happens, neither `zathura` nor `zathura_simple` is working, zathura seems to be installed alright on my computer

#### zathura --version
```
zathura 0.5.2
girara 0.4.0 (runtime: 0.4.0)
(plugin) pdf-poppler (0.3.0) (/opt/homebrew/Cellar/zathura/0.5.2/lib/zathura/libpdf-poppler.dylib)
```

### Steps to reproduce

Have my config:

#### Vimtex.lua
```lua
return {
  "lervag/vimtex",
  lazy = false,
  init = function()
    local g = vim.g
    g.vimtex_view_method = "zathura"
    -- g.vimtex_view_method = "zathura_simple"
    g.vimtex_compiler_latexmk_engines = { ["_"] = '-lualatex'}
    g.vimtex_compiler_latexmk = {
      aux_dir = ".build",
      -- out_dir = "",
      options = {
        "-shell-escape",
        "-verbose",
        "-file-line-error",
        "-synctex=1",
        "-interaction=nonstopmode",
      }
    }
    g.vimtex_quickfix_mode = 0
    g.vimtex_mappings_enable = 0
    g.vimtex_log_ignore = ({
      "Underfull",
      "Overfull",
      "specifier changed to",
      "Token not allowed in PDF string",
    })
  end
}
```

### Expected behavior

open pdf previewer on compiling and after pressing the shortucts or the command `:VimtexView`

### Actual behavior

nothing happens, no error, no anything

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
System info:
  OS: macOS 14.6.1 (23G93)
  Vim version: NVIM v0.10.1
  Has clientserver: true
  Servername: /var/folders/5f/hn34hzl13y907124_kr68p380000gn/T/nvim.felipepinto/jsx9et/nvim.94442.0

VimTeX project: MWE
  base: MWE.tex
  root: /Users/felipepinto/.config/nvim.mwe/MWE
  tex: /Users/felipepinto/.config/nvim.mwe/MWE/MWE.tex
  main parser: current file verified
  document class: minipage
  packages: calc ctablestack expl3 fontenc fontsize fontspec fontspec-luatex ifluatex iftex import infwarerr ltxcmds luacode luatex85 luatexbase pdftexcmds shellesc subfiles xfp xkeyval xparse
  compiler: latexmk
    engine: -lualatex
    options:
      -shell-escape
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    aux_dir: .build
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 8
      output: /var/folders/5f/hn34hzl13y907124_kr68p380000gn/T/nvim.felipepinto/jsx9et/0
      cmd: max_print_line=2000 latexmk -shell-escape -verbose -file-line-error -synctex=1 -interaction=nonstopmode  -lualatex -emulate-aux-dir -auxdir=.build -pvc -pvctimeout- -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'MWE.tex'
      pid: 95005
  viewer: Zathura
    xwin id: 0
    cmd_start: zathura  -x "/opt/homebrew/Cellar/neovim/0.10.1/bin/nvim --headless -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 13:1:'/Users/felipepinto/.config/nvim.mwe/MWE/MWE.tex' 'MWE.pdf'&
  qf method: LaTeX logfile
```
