### ISSUE TITLE
Reverse search in zathura does not work in multifile document if auxiliary files included as "\input file"

### ISSUE THREAD

**Issue by sergeG** [lervag/vimtex#3007]
### Description

Hi!
Reverse search  in zathura does work if I use
 
\input{file}

and does not work if 

\input file 

used instead.

### Do you use a latexmkrc file?

$job_name='Project'; $pdflatex = "pdflatex --shell-escape %O %S";

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 20.04.6 LTS
  Vim version: NVIM v0.10.1
  Has clientserver: true
  Servername: /run/user/1000/nvim.2001772.0

VimTeX project: Project
  base: Project.tex
  root: /home/serge/FILES/SCIENCE/Poroshin.git
  tex: /home/serge/FILES/SCIENCE/Poroshin.git/Project.tex
  main parser: buffer variable
  document class: svjour3
  packages: afterpage amsbsy amsfonts amsgen amsmath amsopn amssymb amstext atbegshi atveryend authblk auxhook babel bigintcalc bitset calc cancel cite epstopdf-base etexcmds eucal geometry gettitlestring graphics graphicx hycolor hyperref iftex ifvtex infwarerr inputenc intcalc keyval kvdefinekeys kvoptions kvsetkeys letltxmacro ltxcmds mathtools mhsetup nameref pdfescape pdftexcmds refcount rerunfilecheck setspace times trig uniquecounter url xcolor
  source files:
    Project.tex
    text.tex
    references.tex
  compiler: latexmk
    engine: -pdf
    options:
      -shell-escape
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 14
      output: /tmp/nvim.serge/2sxyFM/0
      cmd: max_print_line=2000 latexmk -shell-escape -verbose -file-line-error -synctex=1 -interaction=nonstopmode  -pdf -pvc -pvctimeout- -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'Project.tex'
      pid: 2002749
  viewer: Zathura
    xwin id: 0
    cmd_start: zathura  -x "/usr/bin/nvim --headless -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 4033:10:'/home/serge/FILES/SCIENCE/Poroshin.git/text.tex' 'Project.pdf'&
  qf method: LaTeX logfile
```
