### ISSUE TITLE
How to disable adding figure caption after \ref{}

### ISSUE THREAD

**Issue by JulioHC00** [lervag/vimtex#3009]
### Description

I'm sorry if this isn't something that VimTex does, but I can't think of any other plugin that may be doing this. Whenever I write \ref{fig:blahblah} I immediately get the caption added after it as a kind of ghost text. It's just there to be seen, but won't appear in the document. Just like below.

![image](https://github.com/user-attachments/assets/448187c0-b5d2-420e-bf78-69d6d0c2d5f7)

This is being quite buggy for me, and I'd like to disable it. I've tried disabling concealing, but it remains there, and I can't find anything in the docs to help me.

### Steps to reproduce

```latex
% Minimal latex document
% Run 
\documentclass{article}

% Package for figures
\usepackage{graphicx}

\begin{document}

\begin{figure}
	\centering
	\includegraphics[width=\linewidth]{missing.png}
	\caption{Some figure here}
	\label{fig:figure}
\end{figure}

Here we refer to the figure \ref{fig:figure}. %Here you get the text "Figure 1: Some figure here" in a lighter colour.


\end{document}
```

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 22.04.5 LTS
  Vim version: NVIM v0.10.2
  Has clientserver: true
  Servername: /run/user/1000/nvim.26660.0

VimTeX project: minimal
  base: minimal.tex
  root: /home/julio/Downloads/latex_test
  tex: /home/julio/Downloads/latex_test/minimal.tex
  main parser: fallback current file
  document class: 
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 7
      output: /tmp/nvim.julio/4PKYWa/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'minimal.tex'
      pid: 26854
  viewer: General
    job: 
      pid: -
      cmd: okular --unique file:'/home/julio/Downloads/latex_test/minimal.pdf'#src:5'/home/julio/Downloads/latex_test/minimal.tex'
  qf method: LaTeX logfile
```
