### ISSUE TITLE
Syntax conceal: Right delimiter `\right)` missing after conceal

### ISSUE THREAD

**Issue by Felipe-9** [lervag/vimtex#3013]
related to #3010
### Description

this code:
```tex
\begin{flalign*}
= \left(
\dots
+ c_1\,(
  e^{-x^2}
  \,(-2\,x)
)
\right) other chars that disappear
\end{flalign*}
```
is being concealed into

```tex
\begin{flalign*}
= (
...
+ c_1 (
  e^{-x^2}
   (-2 x)
)
her chars that disappear
\end{flalign*}
```

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
OS: macOS 14.6.1 (23G93)
  Vim version: NVIM v0.10.1
  Has clientserver: true
  Servername: /var/folders/5f/hn34hzl13y907124_kr68p380000gn/T/nvim.felipepinto/BZxJyY/nvim.76509.0
```
