### ISSUE TITLE
syntax conceal: custom command w concealed delims with incorrect cchar_close being used on conceal

### ISSUE THREAD

**Issue by Felipe-9** [lervag/vimtex#3014]
related to #3010 
### Description

this
```lua
    vim.g.vimtex_syntax_custom_cmds_with_concealed_delims = {
      {
        mathmode = true,
        nargs= 1,
        name = "myVert",
        cchar_open = "‖",
        cchar_close = "‖"
      },
    }
```
results in this
`\myVert{...}` -> `‖ ...|`

also another problem with this (which is not exclusive to it, my others customs have the same problem) the spacing is wrong its only added to the first delimiter, instead of both. eg: `\myvert{x^2}` -> `| x^2|` instead of `| x^2 |`

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
OS: macOS 14.6.1 (23G93)
  Vim version: NVIM v0.10.1
  Has clientserver: true
  Servername: /var/folders/5f/hn34hzl13y907124_kr68p380000gn/T/nvim.felipepinto/BZxJyY/nvim.76509.0
```
