### ISSUE TITLE
compilation error due to failed main file detection

### ISSUE THREAD

**Issue by qqqtwo** [lervag/vimtex#3016]
### Description

I only have one file I am trying to compile with `\ll`.
When i do this I receive this error:

> compilation error due to failed main file detection

### Steps to reproduce

`minimal.tex` :
```tex
\[
  \int_0^1 \frac{dx}{e^x}
\]
```
`~\lua\plugins\vimtex.lua` :

```lua
return {
  'lervag/vimtex',
  config = function()
    -- Set Okular as the viewer with proper options
    vim.g.vimtex_view_method = 'okular'
    vim.g.vimtex_view_general_options = '--unique file:@pdf\\#src:@line@tex'

    -- Set compiler to latexmk
    vim.g.vimtex_compiler_method = 'latexmk'
  end
}
```

`init.lua`:

```lua
-- bootstrap lazy.nvim, LazyVim and your plugins
vim.g.vimtex_compiler_latexmk = {
    build_dir = '',
    callback = 1,
    continuous = 1,
    executable = 'latexmk',
    options = {
        '-pdf',
        '-interaction=nonstopmode',
        '-synctex=1',
    },
}

require("config.lazy")
```

okular is installed and the path added to Path is:
 `C:\ProgramFiles\WindowsApps\KDEe.V.Okular_23.801.1522.0_x64__7vt06qxq7ptv8\bin`

i am on windows 

### Expected behavior

when i compile with `\ll`, the document should compile
and when i do `\lv`, the document should appear in okular

### Actual behavior

when i compile with `\ll`. i get the error:
compilation error due to failed main file detection

when i type `\lv` nothing happens

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: LAPTOP (Microsoft Windows 11 Home)
  Vim version: NVIM v0.10.2
  Has clientserver: true
  Servername: \\.\pipe\nvim.8408.0

VimTeX project: test
  base: test.tex
  root: C:\Users\andro\notes
  tex: C:\Users\andro\notes/test.tex
  main parser: fallback current file
  document class: 
  compiler: latexmk
    engine: -pdf
    options:
      -pdf
      -interaction=nonstopmode
      -synctex=1
    callback: 1
    continuous: 1
    executable: latexmk
  qf method: LaTeX logfile
```
