### ISSUE TITLE
Synctex doesn't work on the first file compiled in a neovim session

### ISSUE THREAD

**Issue by firubat** [lervag/vimtex#3018]
### Description

If I open a neovim session, load a .tex file and compile it, (with default `<localleader>ll` ) it gets compiled and viewed, but synctex doesn't work (no backward or forward search). 

If I run `VimtexView` another instance of the viewer (zathura) will open (still with no synctex).
I tried closing the viewer and using `VimtexView`, tried stopping and resuming compilation, tried closing the buffer and reopening it - all won't get synctex to work, until I reload vimtex (`VimtexReload`), after which things start working as expected.

If I open a _second_ file (before reloading vimtex) and compile it, synctex _will_ work for that file.

### Steps to reproduce

I use the LazyVim distro, a minimal configuration for vimtex is with the following lua:

```lua
return {
  {
    "lervag/vimtex",
    -- settings based on https://www.lazyvim.org/extras/lang/tex
    lazy = false, -- lazy-loading will disable inverse search
    config = function()
      vim.api.nvim_create_autocmd({ "FileType" }, {
        group = vim.api.nvim_create_augroup("lazyvim_vimtex_conceal", { clear = true }),
        pattern = { "bib", "tex", "sty" },
        callback = function()
          vim.g.vimtex_quickfix_method = vim.fn.executable("pplatex") == 1 and "pplatex" or "latexlog"
          vim.g.vimtex_view_method = "zathura"
          vim.cmd([[setl iskeyword+=\]])
        end,
      })
    end,
  },
}
```

(I don't use the lang.tex LazyVim Extra)

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Linux Mint 21.2
  Vim version: NVIM v0.10.0
  Has clientserver: true
  Servername: /run/user/1000/nvim.11131.0

VimTeX project: MW pdflatex
  base: MW pdflatex.tex
  root: /home/ur/Dropbox/LyX and LaTeX
  tex: /home/ur/Dropbox/LyX and LaTeX/MW pdflatex.tex
  main parser: current file verified
  document class: article
  packages: atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook bigintcalc bitset etexcmds gettitlestring hycolor hyperref iftex infwarerr intcalc keyval kvdefinekeys kvoptions kvsetkeys letltxmacro ltxcmds nameref pdfescape pdftexcmds refcount rerunfilecheck uniquecounter url
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 6
      output: /tmp/nvim.ur/Xtk5io/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode  -pdf -pvc -pvctimeout- -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'MW pdflatex.tex'
      pid: 11225
  viewer: General
    job: 
      pid: -
      cmd: xdg-open '/home/ur/Dropbox/LyX and LaTeX/MW pdflatex.pdf'
  qf method: LaTeX logfile
```
