### ISSUE TITLE
Indentation left/right

### ISSUE THREAD

**Issue by switzel** [lervag/vimtex#3023]
### Description

I'm 90% sure that this is within the responsibility of vimtex, if not please tell me.

When I autoindent (=) a (la)tex file involving $\left. \right|$ the following lines pick up an extra indentation. The left symbol can be replaced by other things but apparently the \right| does not "close" it.

### Steps to reproduce

Put the code

    noindent
    $\left. \right|$
    indent

into a file minimal.tex. Type gg=G. It gets indented as
    noindent
    $\left. \right|$
      indent

(actually it is indented already while typing). (Github won't let me upload a .tex file.)

### Expected behavior

The expected indentation is

    noindent
    $\left. \right|$
    indent

### Actual behavior

The indentation vimtex produces is

    noindent
    $\left. \right|$
      indent

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info
  OS: Ubuntu 20.04.3 LTS
  Vim version: VIM 8.2 (1-16, 647, 17-579, 1969, 580-647, 678, 648-1848, 4975, 5016, 5023, 5072, 2068, 1849-1854, 1857, 1855-1857, 1331, 1858, 1858-1859, 1873, 1860-1969, 1992, 1970-1992, 2010, 1993-2068, 2106, 2069-2106, 2108, 2107-2109, 2109-3995, 4563, 4646, 4774, 4895, 4899, 4901, 4919, 213, 1840, 1846-1847, 2110-2112, 2121)
  Has clientserver: true
  Servername: GVIM

VimTeX project: minimal
  base: minimal.tex
  root: /home/switzel/
  tex: /home/switzel/minimal.tex
  main parser: current file
  document class: 
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
