### ISSUE TITLE
missing whitespace in vimtex.txt

### ISSUE THREAD

**Issue by mvhulten** [lervag/vimtex#3026]
### Description

In the [vimtex doc](https://github.com/lervag/vimtex/blob/master/doc/vimtex.txt#L4794) there is no whitespace after the backslash as should be according to the documentation.

### Steps to reproduce
```
:help vimtex
/^FOLDING
```
 
### VimtexInfo

```yaml
System info:
  OS: OpenBSD 7.6
  Vim version: NVIM v0.10.1
  Has clientserver: true
  Servername: /tmp/nvim.mvanhult/MDurAc/nvim.58193.0

VimTeX project: talk
  base: talk.tex
  root: /home/mvanhult/repos/talk-202410-clm
  tex: /home/mvanhult/repos/talk-202410-clm/talk.tex
  main parser: current file verified
  document class: latex/hpcatalks
  packages: amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm array atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook beamerbaseauxtemplates beamerbaseboxes beamerbasecolor beamerbasecompatibility beamerbasedecode beamerbasefont beamerbaseframe beamerbaseframecomponents beamerbaseframesize beamerbaselocalstructure beamerbasemisc beamerbasemodes beamerbasenavigation beamerbasenotes beamerbaseoptions beamerbaseoverlay beamerbaserequires beamerbasesection beamerbasetemplates beamerbasethemes beamerbasetheorems beamerbasetitle beamerbasetoc beamerbasetranslator beamerbasetwoscreens beamerbaseverbatim beamercolorthemedefault beamercolorthemedolphin beamercolorthemerose beamercolorthemestructure beamerfontthemedefault beamerfontthemeprofessionalfonts beamerinnerthemecircles beamerinnerthemedefault beamerinnerthemerounded beamerouterthemedefault beamerouterthemeinfolines beamerthemeBoadilla beamerthemedefault bigintcalc bitset caption caption3 color enumerate environ epstopdf-base etexcmds etoolbox eurosym expl3 fontenc geometry gettitlestring graphics graphicx grfext hpca hycolor hyperref iftex ifthen ifvtex infwarerr inputenc intcalc keyval kvdefinekeys kvoptions kvsetkeys l3keys2e letltxmacro listings listingsutf8 lstmisc ltxcmds nameref natbib ngerman nicefrac pdfcol pdfescape pdftexcmds pgf pgfcalendar pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfgantt pgfkeys pgfmath pgfrcs pgfsys pifont refcount rerunfilecheck sansmathaccent scrlfile scrlfile-hook scrlogo shellesc siunitx stringenc tcolorbox tikz tikzfill-common tikzfill.image translations translator trig trimspaces uniquecounter url verbatim xcolor xparse xxcolor
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
