### ISSUE TITLE
No compilation status updates after a clear (\lc)

### ISSUE THREAD

**Issue by steef435** [lervag/vimtex#3032]
### Description

After clearing with \lc, there are no more status updates for compilation. See steps to reproduce below.

Thank you for VimTeX!

### Steps to reproduce

1. Use \ll to start continuous compilation
2. Write some changes
3. Status bar shows: Compilation completed
4. Use \lc to clear intermediate files
5. Status bar shows: Compilation clean finished
6. Write some changes
7. No more status updates for "Compilation completed" (even though it does compile)

### Expected behavior

Status bar shows: Compilation completed

### Actual behavior

No more status updates for compilation. Pressing \ll after 7. also does not show any status bar updates (such as "Compiler stopped" etc.)

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 15.0 (24A335)
  Vim version: NVIM v0.10.1
  Has clientserver: true
  Servername: /var/folders/rg/rt8764sj2q12nxcvmfgzgbz80000gn/T/nvim.steef/OBoPHt/nvim.69698.0

VimTeX project: main
  base: main.tex
  root: /Users/steef/redacted
  tex: /Users/steef/redacted/main.tex
  main parser: current file verified
  document class: amsart
  packages: amsbsy amsfonts amsgen amsmath amsopn amssymb amstext atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook bigintcalc bitset calc complexity epstopdf-base etoolbox fontenc gettitlestring graphics graphicx hycolor hyperref iftex ifthen infwarerr intcalc keyval kvdefinekeys kvoptions kvsetkeys ltxcmds mycomplexity nameref pdfescape pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfrcs pgfsys refcount rerunfilecheck silence tikz todonotes trig uniquecounter url verbatim xcolor xcomment xkeyval
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 7
      output: /var/folders/rg/rt8764sj2q12nxcvmfgzgbz80000gn/T/nvim.steef/OBoPHt/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode  -pdf -pvc -pvctimeout- -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'main.tex'
      pid: 69703
  viewer: sioyek
    job: 
      pid: -
      cmd: sioyek  --inverse-search "/opt/homebrew/Cellar/neovim/0.10.1/bin/nvim --headless -c \"VimtexInverseSearch %2 '%1'\"" --forward-search-file '/Users/steef/redacted/main.tex' --forward-search-line 121 '/Users/steef/redacted/main.pdf'
    cmd_start: sioyek  --inverse-search "/opt/homebrew/Cellar/neovim/0.10.1/bin/nvim --headless -c \"VimtexInverseSearch %2 '%1'\"" --forward-search-file '/Users/steef/redacted/main.tex' --forward-search-line 121 '/Users/steef/redacted/main.pdf'
  qf method: LaTeX logfile
```
