### ISSUE TITLE
Help with Inverse search with sioyek in macOS

### ISSUE THREAD

**Issue by idr4n** [lervag/vimtex#3033]
### Description

Hi and thanks for a great plugin!

I am using Sioyek as viewer but unfortunately Inverse search is not working for me in macOS, although it does work in VSCode. After the file is opened in Sioyek, right clicking doesn't do anything (with syntex activated).

After compiling the tex file, it opens and highlights the current line in Sioyek as expected. This is the `cmd_start` shown in `VimtexInfo`:

`cmd_start: sioyek  --inverse-search "/path_to/nvim --headless -c \"VimtexInverseSearch %2 '%1'\"" --forward-search-file '/path_to_file/file.tex' --forward-search-line 24 '/path_to_file/file.pdf'`

Now, I have tried adding the current neovim server to the inverse-search command and I got some results. In particular,

```lua
local servername = vim.v.servername
vim.g.vimtex_callback_progpath = "/path_to/nvim --server " .. servername .. " --remote-send"
```

With that, I get

`cmd_start: sioyek  --inverse-search "/Users/iduran/bin/nvim --server /var/folders/3z/gq4tjk914l79tpsg64z45v_00000gn/T/nvim.iduran/0cu7pq/nvim.52063.0 --remote-send --headless -c \"VimtexInverseSearch %2 '%1'\"" --forward-search-file '/path_to_file/file.tex' --forward-search-line 26 '/path_to_file/file.pdf'`

With this, after right clicking in the Sioyek document, it connects with the corresponding nvim instance. However, it sends the command `-hea` and types `dless`. Basically, this happens as `--headless` remains after `--remote-send`, but it means that by adding the servername info it does connect with the current nvim instance.

I think what I would like to do is to be able to change `s:inverse_search_cmd` in https://github.com/lervag/vimtex/blob/9a5ef1d4ac8e4e06071179ebe8121350fcb97861/autoload/vimtex/view/sioyek.vim#L37, but I couldn't find in the docs a way to do so.

If there is a way to accomplish this or you think there is a better approach I would appreciate pointing me in the right direction.

Thanks in advance!

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 15.1 (24B5077a)
  Vim version: NVIM v0.11.0-dev-982+gf72dc2b4c
  Has clientserver: true
  Servername: /var/folders/3z/gq4tjk914l79tpsg64z45v_00000gn/T/nvim.iduran/mq9n9m/nvim.57104.0

VimTeX project: ch04_08_practice_problems
  base: ch04_08_practice_problems.tex
  root: /Users/iduran/pCloud/PSU/Fin335/Practice_problems
  tex: /Users/iduran/pCloud/PSU/Fin335/Practice_problems/ch04_08_practice_problems.tex
  main parser: current file verified
  document class: article
  packages: amsbsy amsgen amsmath amsopn amstext booktabs geometry iftex ifvtex keyval multirow
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: sioyek
  qf method: LaTeX logfile
```
