### ISSUE TITLE
`vim.fn["vimtex#env#is_inside"]("document")` not working when working on an `\include`-ed files that lack a `\begin{document}`

### ISSUE THREAD

**Issue by de-mirage2** [lervag/vimtex#3037]
### Description

After writing into the main-file `\include{Notes/Period4/period4.tex}` to include a sub-file `period4.tex` stored in /Notes/Period4/, VimTeX doesn't recognize how typing into the sub-file `Notes/Period4/period4.tex` is done as a document, and that the sub-file doesn't require `\begin{document}` nor `\end{document}`.

As such, my LuaSnip snippets which depend on `vim.fn["vimtex#env#is_inside"]("document")` don't show up when editing `Notes/Period4/period.tex`, since it can't find the `\begin{document}`.

### Steps to reproduce

1) Create a basic document in main.tex that has an `include` statement i.e. `\include{subfolder/chapter1}`
2) Create a folder in the same directory i.e. `subfolder`
3) Within the directory create a new file i.e. `chapter1.tex`
4) Evaluate `vim.fn["vimtex#env#is_inside"]("document")` in any way possible - I used my LuaSnip snippets which use that condition to verify, by observing if it shows up or not
```lua
function in_doc() 
  local is_in_doc = vim.fn["vimtex#env#is_inside"]("document")
  return (is_in_doc[1] > 0 and is_in_doc[2] > 0 and (vim.api.nvim_eval("vimtex#syntax#in_mathzone()") == 0))
end
```

### Expected behavior

for `vim.fn["vimtex#env#is_inside"]("document")` to be evaluated as true and my snippets seen

### Actual behavior

this doesn't happen

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
Sub-file:

System info:
  OS: Linux 6.8.2-arch2-1
  Vim version: NVIM v0.10.2
  Has clientserver: true
  Servername: /run/user/1000/nvim.1001420.0

VimTeX project: period4
  base: period4.tex
  root: /home/de_mirage/Classwork/HS/11th/USH/Notes/Period4
  tex: /home/de_mirage/Classwork/HS/11th/USH/Notes/Period4/period4.tex
  main parser: fallback current file
  document class: 
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile

Main-file:
System info:
  OS: Linux 6.8.2-arch2-1
  Vim version: NVIM v0.10.2
  Has clientserver: true
  Servername: /run/user/1000/nvim.1005373.0

VimTeX project: APUSH_FN
  base: APUSH_FN.tex
  root: /home/de_mirage/Classwork/HS/11th/USH/Notes
  tex: /home/de_mirage/Classwork/HS/11th/USH/Notes/APUSH_FN.tex
  main parser: current file verified
  document class: memoir
  packages: array booktabs dcolumn delarray epstopdf-base etoolbox expl3 geometry gettitlestring graphics graphicx iftex ifvtex infwarerr keyval kvoptions kvsetkeys ltxcmds nameref pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfrcs pgfsys refcount shortvrb tabularx textcase tikz trig verbatim xcolor xparse xpatch
  source files:
    APUSH_FN.tex
    Period4/period4.tex
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
