### ISSUE TITLE
Adding `-shell-escape` options breaks SyncTex

### ISSUE THREAD

**Issue by ravibrock** [lervag/vimtex#3047]
### Description

Hello, the title basically summarizes the issue. I added the following line of code:
```lua
vim.g.vimtex_compiler_latexmk = { options = { "-shell-escape" } }
```
to my config so that the `minted` package works properly, but since then my SyncTex (when using Sioyek) has been broken. If I comment out that line, it works again. Thank you!

### Steps to reproduce

1. `nvim -u minimal.lua nochapters.tex`
2. Comment out line 44 of `minimal.lua` and try again

minimal.lua:
```lua
-- Bootstrap lazy.nvim
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
  local lazyrepo = "https://github.com/folke/lazy.nvim.git"
  local out = vim.fn.system({ "git", "clone", "--filter=blob:none", "--branch=stable", lazyrepo, lazypath })
  if vim.v.shell_error ~= 0 then
    vim.api.nvim_echo({
      { "Failed to clone lazy.nvim:\n", "ErrorMsg" },
      { out, "WarningMsg" },
      { "\nPress any key to exit..." },
    }, true, {})
    vim.fn.getchar()
    os.exit(1)
  end
end
vim.opt.rtp:prepend(lazypath)

-- Make sure to setup `mapleader` and `maplocalleader` before
-- loading lazy.nvim so that mappings are correct.
-- This is also a good place to setup other settings (vim.opt)
vim.g.mapleader = " "
vim.g.maplocalleader = "\\"

-- Setup lazy.nvim
require("lazy").setup({
    spec = {
        {
            "lervag/vimtex",
            ft = { "tex" },
            cmd = { "VimtexClean", "VimtexCompile", "VimtexInverseSearch", "VimtexView" },
            keys = {
                { "<leader>lc", "<CMD>VimtexClean<CR>", desc = "Clean TeX auxfiles" },
                { "<leader>ll", "<CMD>VimtexCompile<CR>", desc = "Start TeX compilation" },
                { "<leader>ls", "<CMD>silent! !sioyek --execute-command reload<CR>", desc = "Reload Sioyek instance" },
                { "<leader>lv", "<CMD>VimtexView<CR>", desc = "View compiled TeX document" },
                { "<leader>lw", "<CMD>VimtexCountWords<CR>", desc = "Count words in TeX file" },
            },
            config = function()
                vim.g.vimtex_view_method = "sioyek"
                vim.g.vimtex_view_sioyek_options = "--new-window"
                vim.g.tex_flavor = "latex"
                vim.g.vimtex_imaps_enabled = 0
                vim.g.vimtex_fold_enabled = 2
                vim.g.vimtex_compiler_latexmk = { options = { "-shell-escape" } } -- Needed for minted
                vim.keymap.set("i", "<C-x><CR>", "<plug>(vimtex-delim-close)", { silent = true, desc = "Close delimiter" })
                vim.opt.conceallevel = 2 -- Enable VimTeX conceal

                -- Set up autocommands for VimTeX
                vim.api.nvim_create_augroup("VimTeX", {})
                vim.api.nvim_create_autocmd("User", {
                    group = "VimTeX",
                    pattern = "VimtexEventCompileStopped",
                    desc = "VimTeX: Clean up auxiliary files on exit",
                    command = "VimtexClean",
                })
                vim.api.nvim_create_autocmd("User", {
                    group = "VimTeX",
                    pattern = "VimtexEventViewReverse",
                    desc = "VimTeX: Return focus to vim after inverse search trigger in PDF",
                    command = vim.fn.system("osascript -e 'activate application \"iTerm\"'"),
                })
                vim.api.nvim_create_autocmd("User", {
                    group = "VimTeX",
                    pattern = "VimtexEventViewReverse",
                    desc = "VimTeX: Center text vertically after inverse search trigger in PDF",
                    command = "normal! zz",
                })
                vim.api.nvim_create_autocmd("User", {
                    group = "VimTeX",
                    pattern = "VimtexEventViewReverse",
                    desc = "VimTeX: Send cursor to last column after inverse search trigger in PDF",
                    --- @diagnostic disable-next-line: param-type-mismatch
                    callback = function() vim.fn.cursor(".", vim.fn.col("$")) end,
                })
                vim.api.nvim_create_autocmd("InsertLeave", {
                    group = "VimTeX",
                    pattern = { "*.tex", "*.bib" },
                    desc = "VimTeX: Auto replace double quotes in current line with `` and ''",
                    callback = function()
                        --- @diagnostic disable-next-line: param-type-mismatch
                        local line, linenr = vim.fn.getline("."), vim.fn.line(".")
                        local position = vim.api.nvim_win_get_cursor(0)[2] + 1
                        local _, quote_count = string.sub(line, 1, position):gsub('"', '')
                        vim.cmd('silent! %s/\\"\\([^\\"]*\\)\\"/\\`\\`\\1\'\'/')
                        local new_line = vim.fn.getline(linenr)
                        if line ~= new_line then vim.fn.cursor({ linenr, position + quote_count }) end
                    end,
                })
            end,
        }
    },
  -- Configure any other settings here. See the documentation for more details.
  -- colorscheme that will be used when installing plugins.
  install = { colorscheme = { "habamax" } },
  -- automatically check for plugin updates
  checker = { enabled = true },
})
```
nochapters.tex:
```tex
\documentclass{article}

\usepackage{etoolbox}
\usepackage{fbb}
\usepackage{filehook}
\usepackage{GoudyIn}
\usepackage{lettrine}
\usepackage{xstring}

\renewcommand\LettrineFontHook{\GoudyInfamily}
\def\dropcap #1#2 {
    \lettrine[lines=3,findent=1.75mm,nindent=0mm]{#1}{#2}
}

% Switch comments to add dropcap at start of document and no title.
% \let\tmpdocument\document
% \renewcommand{\document}{\tmpdocument\dropcap}
\let\tmpmaketitle\maketitle
\renewcommand{\maketitle}{\tmpmaketitle\dropcap}

\title{Test essay}
\author{Ravi Brock}

\begin{document}
\maketitle
When I was just a little girl, I asked my mother, ``What will I be? Will I be pretty, will I be pretty, will I be pretty?!'' What comes next? Oh right, will I be rich -- which is almost pretty depending on where you shop. And the pretty question infects from conception passing blood and breathe into cells. The word hangs from our mothers hearts in a shrill fluorescent floodlight of worry. Will I be wanted? Worthy? Pretty?
\end{document}
```

### Do you use a latexmkrc file?

Yes

### VimtexInfo

```yaml
System info:
  OS: macOS 13.3.1 (22E772610a)
  Vim version: NVIM v0.11.0-dev-505+g60967cd9a-Homebrew
  Has clientserver: true
  Servername: /var/folders/5j/84p0q84s4452bjhnyb8bjtqr0000gn/T/nvim.ravibrock/mwBY3C/nvim.31604.0

VimTeX project: nochapters
  base: nochapters.tex
  root: /Users/ravibrock/Desktop
  tex: /Users/ravibrock/Desktop/nochapters.tex
  main parser: current file verified
  document class: article
  packages: GoudyIn etoolbox expl3 fbb filehook filehook-2020 fontaxes fontenc ifetex iftex ifthen lettrine mweights textcomp xfp xkeyval xstring
  compiler: latexmk
    engine: -pdf
    options:
      -shell-escape
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 5
      output: /var/folders/5j/84p0q84s4452bjhnyb8bjtqr0000gn/T/nvim.ravibrock/mwBY3C/0
      cmd: max_print_line=2000 latexmk -shell-escape  -pdf -pvc -pvctimeout- -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'nochapters.tex'
      pid: 31631
  viewer: sioyek
    job: 
      pid: -
      cmd: sioyek --new-window --inverse-search "/opt/homebrew/Cellar/neovim/HEAD-60967cd/bin/nvim --headless -c \"VimtexInverseSearch %2 '%1'\"" --forward-search-file '/Users/ravibrock/Desktop/nochapters.tex' --forward-search-line 26 '/Users/ravibrock/Desktop/nochapters.pdf'
    cmd_start: sioyek --new-window --inverse-search "/opt/homebrew/Cellar/neovim/HEAD-60967cd/bin/nvim --headless -c \"VimtexInverseSearch %2 '%1'\"" --forward-search-file '/Users/ravibrock/Desktop/nochapters.tex' --forward-search-line 26 '/Users/ravibrock/Desktop/nochapters.pdf'
  qf method: LaTeX logfile
```
