### ISSUE TITLE
:VimtexInverseSearch closes neovim

### ISSUE THREAD

**Issue by aaronyicongfu** [lervag/vimtex#3051]
### Description

Hi, I just started editing latex on vim (because I'm so tired of using overleaf..) and found vimtex is amazing! Only thing for now is that I cannot get the inverse search to work. As title pretty much says it all, I wonder is this behavior expected or not? Reason I was trying to execute ```:VimtexInverseSearch``` was I could not get inverse search to work with Skim, so I just tested around and encountered this behavior.

Any advice would be highly appreciated, thanks in advance.

### Steps to reproduce

1. nvim --clean -u minimal.vim minimal.tex
2. Execute :VimtexInverseSearch

### Expected behavior

Cursor is moved to somewhere 

### Actual behavior

Neovim closes

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
drwxr-xr-x 28 fyc staff  896 Dec  6 14:42 vimtex
System info:
  OS: macOS 15.1.1 (24B91)
  Vim version: NVIM v0.10.2
  Has clientserver: true
  Servername: /var/folders/pz/bs46hf451gn4vx7_svt7zz580000gn/T/nvim.fyc/m5ABRs/nvim.47837.0

VimTeX project: minimal
  base: minimal.tex
  root: /Users/fyc/toys/reproducer/neovim/vimtex-reverse-search
  tex: /Users/fyc/toys/reproducer/neovim/vimtex-reverse-search/minimal.tex
  main parser: current file verified
  document class: minimal
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
