### ISSUE TITLE
argspell + arggreedy conflicts with nextgroup

### ISSUE THREAD

**Issue by JoseCuevasBtos** [lervag/vimtex#3059]
### Description

Hi there! I was trying to do two things with the `g:vimtex_syntax_custom_cmds` options. For the LaTeX command `\addtocategory{bib_category}{bib_key}` I wanted to both highlight both arguments with the `nextgroup` key, but to also ignore spelling errors on both arguments and it seems as these two are incompatible.

This is a MWE in my `.vimrc`:

```vim
let g:vimtex_syntax_custom_cmds = [
      \ {
      \   'name': 'addtocategory',
      \   'argspell': 0,
      \   'arggreedy': 1,
      \   'nextgroup': 'texOpt,texRefArg'
      \ },
      \]
```

Which does highlight the first group as an option and the second as a reference, however it doesn't ignore spelling on both arguments, just the first. Nevertheless, if I erase the `nextgroup` option, it does ignore spelling on both arguments.

---

Another thing I tried was manually setting the highlight group by using something like this:

```vim
highlight default link texCAddtocategoryArg texRefArg
```

This now highlights arguments as citations, but I have no longer control whatsover of the first argument.

Any advices on how to solve this?

Also I should remark that my issue seems similar, though not completely equal to those treated in  #2240 and #2086.

### VimtexInfo

```yaml
System info:
  OS: ArcoLinux
  Vim version: VIM 9.1 (1-866)
  Has clientserver: true
  Servername: undefined (vim started without --servername)

VimTeX project: analisis-complejo
  base: analisis-complejo.tex
  root: /home/josec/Documentos/LaTeX/an-com-conj-cond
  tex: /home/josec/Documentos/LaTeX/an-com-conj-cond/analisis-complejo.tex
  main parser: current file verified
  document class: book
  packages: ../cuevasthm accents aliasctr amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm arcs array atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook avant babel bbm biblatex bigintcalc bitset blx-case-expl3 bm calc cancel caption caption3 color colortbl csquotes cuevasthm datetime2 enumitem environ epigraph epstopdf-base esint eso-pic etexcmds etoolbox expl3 fancyhdr fontenc gettitlestring graphics graphicx hycolor hyperref ifluatex ifmtarg iftex ifthen ifxetex imakeidx import infwarerr inputenc intcalc keyval kvdefinekeys kvoptions kvsetkeys listings listingsutf8 listofitems logreq longtable lscape lstmisc lstpatch ltcaption ltxcmds manfnt marginnote mathrsfs mathtools mdframed mhsetup multicol nameref needspace nextpage nomencl parseargs pdfcol pdfescape pdflscape pdflscape-nometadata pdfpages pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfplots pgfrcs pgfsys refcount relsize rerunfilecheck scrbase scrlfile scrlfile-hook scrlogo stackengine stringenc subcaption subfiles tcolorbox thm-amsthm thm-autoref thm-kv thm-listof thm-patch thm-restate thmtools tikz tikz-3dplot tikzfill-common tikzfill.image titlesec titletoc tocbasic todonotes tracklang trig trimspaces ulem uniquecounter url varwidth verbatim wasysym wrapfig xcolor xifthen xkeyval xparse yhmath zref-abspage zref-base
  source files:
    analisis-complejo.tex
    ../template.tex
    ../general.tex
    ../graphics.tex
    holomorfismos.tex
    aplicaciones.tex
    superficie.tex
    variedades_anal.tex
    condensado.tex
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 0
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
