### ISSUE TITLE
Problem with compiling files

### ISSUE THREAD

**Issue by peperonnii** [lervag/vimtex#3060]
### Description

Hello, forgive me, i am really new to latex and this plugin but i have spent the past few hours reading into it. And ive hit a roadblock when it comes to compiling.

Ive done everything in the Readme and the plugin loads correctly. Commands work etc.

Then i hit leader l l or VimtexCompile and it just says compilation stopped. It generates some files in my directory and then it stops. Am i missing some packages? I am on arch linux and I have installed the texlive-bin package as per the arch wiki.

here is the output of VimtexLog

```
01:44:59: info
  #0 /home/joebiden/.local/share/nvim/lazy/vimtex/autoload/vimtex/compiler.vim:255
  In vimtex#compiler#stop
    call vimtex#log#info('Compiler stopped (' . b:vimtex.base . ')')
  #1 /home/joebiden/.local/share/nvim/lazy/vimtex/autoload/vimtex/compiler.vim:114
  In vimtex#compiler#compile
    call vimtex#compiler#stop()
  Compiler stopped (test.tex)
```

### Steps to reproduce

here is the minimal document i tested it on.

\documentclass{minimal}
\begin{document}
Hello world!
\end{document}

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
System info:
  OS: Arch Linux
  Vim version: NVIM v0.10.2
  Has clientserver: true
  Servername: /run/user/1000/nvim.372164.0

VimTeX project: test
  base: test.tex
  root: /home/joebiden/Projects/latex
  tex: /home/joebiden/Projects/latex/test.tex
  main parser: current file verified
  document class: article
  packages: inputenc
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 13
      output: /tmp/nvim.joebiden/hXs7MJ/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode  -pdf -pvc -pvctimeout- -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'test.tex'
      pid: 0
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
