### ISSUE TITLE
File '<package>.sty' not found, emergency stop

### ISSUE THREAD

**Issue by ethananthony271** [lervag/vimtex#3061]
### Description

When using vimtex to compile my document, I get the error:

```
File `<package>.sty' not found.
error| Emergency stop.
error| Fatal error occurred, no output PDF file produced!
```

This error is coming up with several different packages such as darkmode, circuitikz, and float. When I run latexmk from my command line, it compiles without an issue. Specifically, the following is the output I get on an example file:

```
Rc files read:
  NONE
Latexmk: This is Latexmk, John Collins, 31 Jan. 2024. Version 4.83.
No existing .aux file, so I'll make a simple one, and require run of *latex.
Latexmk: applying rule 'pdflatex'...
Rule 'pdflatex':  Reasons for rerun
Category 'other':
  Rerun of 'pdflatex' forced or previously required:
    Reason or flag: 'Initial setup'

------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "temp.tex"'
------------
This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023/nixos.org) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./temp.tex
LaTeX2e <2023-11-01> patch level 1
L3 programming layer <2024-02-20>

(/nix/store/jq3pgdrl04wbgrsxhvkglcfv0b1dsj3q-texlive-combined-2023-texmfdist/te
x/latex/base/article.cls
Document Class: article 2023/05/17 v1.4n Standard LaTeX document class

(/nix/store/jq3pgdrl04wbgrsxhvkglcfv0b1dsj3q-texlive-combined-2023-texmfdist/te
x/latex/base/size10.clo))
(/nix/store/jq3pgdrl04wbgrsxhvkglcfv0b1dsj3q-texlive-combined-2023-texmfdist/te
x/latex/darkmode/darkmode.sty
(/nix/store/jq3pgdrl04wbgrsxhvkglcfv0b1dsj3q-texlive-combined-2023-texmfdist/te
x/latex/l3kernel/expl3.sty
(/nix/store/jq3pgdrl04wbgrsxhvkglcfv0b1dsj3q-texlive-combined-2023-texmfdist/te
x/latex/l3backend/l3backend-pdftex.def))
(/nix/store/jq3pgdrl04wbgrsxhvkglcfv0b1dsj3q-texlive-combined-2023-texmfdist/te
x/latex/l3packages/l3keys2e/l3keys2e.sty)
(/nix/store/jq3pgdrl04wbgrsxhvkglcfv0b1dsj3q-texlive-combined-2023-texmfdist/te
x/latex/xcolor/xcolor.sty
(/nix/store/jq3pgdrl04wbgrsxhvkglcfv0b1dsj3q-texlive-combined-2023-texmfdist/te
x/latex/graphics-cfg/color.cfg)
(/nix/store/jq3pgdrl04wbgrsxhvkglcfv0b1dsj3q-texlive-combined-2023-texmfdist/te
x/latex/graphics-def/pdftex.def)
(/nix/store/jq3pgdrl04wbgrsxhvkglcfv0b1dsj3q-texlive-combined-2023-texmfdist/te
x/latex/graphics/mathcolor.ltx))
(/nix/store/jq3pgdrl04wbgrsxhvkglcfv0b1dsj3q-texlive-combined-2023-texmfdist/te
x/latex/pagecolor/pagecolor.sty
(/nix/store/jq3pgdrl04wbgrsxhvkglcfv0b1dsj3q-texlive-combined-2023-texmfdist/te
x/latex/kvoptions/kvoptions.sty
(/nix/store/jq3pgdrl04wbgrsxhvkglcfv0b1dsj3q-texlive-combined-2023-texmfdist/te
x/latex/graphics/keyval.sty)
(/nix/store/jq3pgdrl04wbgrsxhvkglcfv0b1dsj3q-texlive-combined-2023-texmfdist/te
x/generic/ltxcmds/ltxcmds.sty)
(/nix/store/jq3pgdrl04wbgrsxhvkglcfv0b1dsj3q-texlive-combined-2023-texmfdist/te
x/latex/kvsetkeys/kvsetkeys.sty)))) (./temp.aux)
(/nix/store/jq3pgdrl04wbgrsxhvkglcfv0b1dsj3q-texlive-combined-2023-texmfdist/te
x/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) [1{/nix/store/43i94gavdacv9x87kjw3d11lrh05wffn-texlive-combined-2023/share/te
xmf-var/fonts/map/pdftex/updmap/pdftex.map}] (./temp.aux) )</nix/store/jq3pgdrl
04wbgrsxhvkglcfv0b1dsj3q-texlive-combined-2023-texmfdist/fonts/type1/public/ams
fonts/cm/cmr10.pfb>
Output written on temp.pdf (1 page, 16780 bytes).
Transcript written on temp.log.
Latexmk: Getting log file 'temp.log'
Latexmk: Examining 'temp.fls'
Latexmk: Examining 'temp.log'
Latexmk: Log file says output to 'temp.pdf'
Latexmk: All targets (temp.pdf) are up-to-date
```

The example file in question is:

```
\documentclass{article}
\usepackage{darkmode}
\enabledarkmode

\begin{document}

tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd
gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

\end{document}
```

### Steps to reproduce

1. Open a minimal tex document in neovim
2. Use the darkmode package (also an issue with several other packages)
3. Run :VimtexCompileSS

### Expected behavior

The document compiles with no issues as is the case one the command line

### Actual behavior

The error in question is output and the document fails to compile

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Linux 6.6.63
  Vim version: NVIM v0.10.2
  Has clientserver: true
  Servername: /run/user/1000/nvim.29353.0

VimTeX project: temp
  base: temp.tex
  root: /home/ea
  tex: /home/ea/temp.tex
  main parser: current file verified
  document class: article
  packages: darkmode expl3 keyval kvoptions kvsetkeys l3keys2e ltxcmds pagecolor xcolor
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
