### ISSUE TITLE
Severe performance degradation when having `bufferline.nvim`

### ISSUE THREAD

**Issue by moetayuko** [lervag/vimtex#3062]
### Description

When using `bufferline.nvim` and compiling tex (particularly large ones) in the background, neovim becomes unresponsive, and its CPU usage spikes to 100%. This issue resolves once the compilation process is complete. I profiled with `snacks.profiler`, and this function is identified to be the most time-consuming one (it's invoked with an unusually high frequency) https://github.com/akinsho/bufferline.nvim/blob/261a72b90d6db4ed8014f7bda976bcdc9dd7ce76/lua/bufferline/buffers.lua#L54

I don't know why this would happen. Does vimtex create hidden buffers when invoking tex compilers in the background?

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Arch Linux
  Vim version: NVIM v0.10.2
  Has clientserver: true
  Servername: /run/user/1000/nvim.533076.0

VimTeX project: main
  base: main.tex
  root: /home/xxx/doc/thesis
  tex: /home/xxx/doc/thesis/main.tex
  main parser: subfiles
  document class: yanputhesis
  packages: CJKfntef adjcalc adjustbox algorithm algorithmicx algpseudocodex aliascnt amsbsy amsfonts amsgen amsmath amsopn amssymb amstext appendix array atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook biblatex bigintcalc bitset blx-case-expl3 bm bookmark booktabs calc caption caption3 catchfile collectbox color ctexhook currfile diagbox empheq enumerate enumitem eso-pic etexcmds etoolbox expl3 fancyhdr fancyref fifo-stack filehook filehook-2020 float fontenc fontspec fontspec-xetex geometry gettitlestring gincltex graphics graphicx hycolor hyperref ifluatex ifoddpage ifplatform iftex ifthen ifvtex import indentfirst infwarerr intcalc keyval kvdefinekeys kvoptions kvsetkeys l3keys2e layouts listings logreq longtable lscape lstlang1 lstlang2 lstlang3 lstmisc lstpatch ltcaption ltxcmds makecell mathtools mhsetup multicol multirow nameref ninecolors nomencl ntheorem pdfescape pdflscape pdflscape-nometadata pdfpages pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfrcs pgfsys pict2e pifont ragged2e refcount rerunfilecheck scrbase scrlfile scrlfile-hook scrlogo setspace shellesc siunitx standalone stringenc subcaption subfiles svn-prov tabto tabularray tabularx tikz titlesec titletoc tocbasic totcount translations trig trimclip type1cm ulem uniquecounter url varioref varwidth wrapfig xcolor xeCJK xeCJK-listings xeCJKfntef xkeyval xparse xpatch xstring xtemplate xtemplate-2023-10-10
  source files:
    main.tex
    math_commands.tex
    notation.tex
    chapters/intro/intro.tex
  compiler: latexmk
    engine: -xelatex
    options:
      -verbose
      -file-line-error
      -shell-escape
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 18
      output: /tmp/nvim.xxx/wHi5y7/4
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -shell-escape -synctex=1 -interaction=nonstopmode  -xelatex -pvc -pvctimeout- -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'main.tex'
      pid: 533980
  viewer: Zathura
    cmd_start: zathura  -x "/usr/bin/nvim --headless -c \"VimtexInverseSearch %{line}:%{column} '%{input}'\"" --synctex-forward 453:152:'/home/xxx/doc/thesis/chapters/intro/intro.tex' 'main.pdf'&
  qf method: LaTeX logfile
```
