### ISSUE TITLE
Help with Inverse search with sioyek in macOS (again)

### ISSUE THREAD

**Issue by zuxfoucault** [lervag/vimtex#3074]
### Description

Thanks for making this great plugin! I encountered some inverse search issues and try previous closed issue solutions but still doesn't work

### Do you use a latexmkrc file?

yes

### VimtexInfo

```yaml
System info:
  OS: macOS 14.1 (23B74)
  Vim version: NVIM v0.10.2
  Has clientserver: true
  Servername: /var/folders/_p/fm218frs5bldc1q9wb5dyhfm0000gn/T/nvim.zuxfoucaultwong/EWuyg5/nvim.78413.0

VimTeX project:  ...
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
      -shell-escape
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 20
      output: /var/folders/_p/fm218frs5bldc1q9wb5dyhfm0000gn/T/nvim..../EWuyg5/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -shell-escape  -pdf -pvc -pvctimeout- -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'file.tex'
      pid: 80710
  viewer: sioyek
    job: 
      pid: -
      cmd: /usr/local/bin/sioyek  --inverse-search "/usr/local/bin/nvim --headless -c \"VimtexInverseSearch %2 '%1'\"" --forward-search-file '/Users/.tex' --forward-search-line 238 'file.pdf'
    cmd_start: /usr/local/bin/sioyek  --inverse-search "/usr/local/bin/nvim --headless -c \"VimtexInverseSearch %2 '%1'\"" --forward-search-file 'file.tex' --forward-search-line 238 'file.pdf'
  qf method: LaTeX logfile
```
