### ISSUE TITLE
dbus not running on iMac M1

### ISSUE THREAD

**Issue by JayanAXHF** [lervag/vimtex#3076]
### Description

I was trying to get SyncTex to work with VimTex. While setting dbus up, which is required for Zathura, it would not run. The service starts, but when i run `brew services info dbus`, it says that dbus isn't running. I've also tried `dbus-daemon --fork --session --address=$DBUS_SESSION_BUS_ADDRESS` to try to manually start dbus, but it still doesn't work.

### Steps to reproduce

Follow the [guide](https://ejmastnak.com/tutorials/vim-latex/pdf-reader/#building-zathura-and-dependencies-on-macos)'s steps to install and run `dbus`

### Expected behavior

dbus should be running.

### Actual behavior

When running `brew services info dbus`, this is the output:
```
❯ brew services info dbus
dbus (org.freedesktop.dbus-session)
Running: ✘
Loaded: ✔
Schedulable: ✘
```

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 15.0.1 (24A348)
  Vim version: NVIM v0.10.3
  Has clientserver: true
  Servername: /var/folders/0b/t5lzl2n55tgcjq0srpvnd4zw0000gn/T/nvim.sunilchoudhary/8YcjVF/nvim.8435.0

VimTeX project: random
  base: random.tex
  root: /Users/sunilchoudhary/Documents/Latex
  tex: /Users/sunilchoudhary/Documents/Latex/random.tex
  main parser: current file verified
  document class: article
  packages: amsbsy amsgen amsmath amsopn amstext atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook bigintcalc bitset calc comment etexcmds gensymb gettitlestring hycolor hyperref iftex infwarerr intcalc keyval kvdefinekeys kvoptions kvsetkeys letltxmacro ltxcmds multicol nameref pdfescape pdftexcmds pict2e picture refcount rerunfilecheck stix textcomp textgreek trig uniquecounter url
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
