### ISSUE TITLE
vimtex/latexmk issue

### ISSUE THREAD

**Issue by meh-b** [lervag/vimtex#3078]
### Description

hope all is well. vimtex works just fine in general on my Mac.
tried to replicate exact steps with OpenBSD. following setup&issue:

preliminary details: `:checkhealth` only states `biber`/`pstree` are not executable/available respectively. shouldn't be a problem.

`.vimrc` is very minimal, no configuration of tex compiler [so it is just default `latexmk`]. only addendum, specified vimtex 2.15 since neovim on OpenBSD hasn't been updated yet.

`latexmk` works fine on its own separately from vimtex.

error details: running `:VimtexCompile` with minimal tex file gives following error:

```
"latexmk: -pvctimeout- bad option
latexmk: Bad options specified" 
```

would appreciate any help or advice. thanks for all you do!

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
      OS: OpenBSD 7.6
      Vim version: NVIM v0.10.1
      Has clientserver: true
      Servername: /tmp/nvim.creed/ctlydo/nvim.34080.0

VimTex project: main
      base: main.tex
      root: /home/creed
      tex: /home/creed/main.tex
      main parser: current file verified
      document class: article
      compiler: latexmk
        engine: -pdf
        options:
          -verbose
          -file-line-error
          -synctex=1
          -interaction=nonstopmode
        callback: 1
        continuous: 1
        executable: latexmk
      viewer: General
      qf method: LaTeX logfile
```
