### ISSUE TITLE
Issue with `g:vimtex_syntax_custom_cmds`

### ISSUE THREAD

**Issue by awsloth** [lervag/vimtex#3081]
### Description

I am trying to use vimtex_syntax_custom_cmds to allow for math mode in the argument. 

### Steps to reproduce

Use the following code to allow arguments to be in math mode:
```lua
vim.g.vimtex_syntax_custom_cmds = {
    { name = "boxed",
      mathmode = 1,
    },
}
```

```latex
\documentclass{book}
\begin{document}
\begin{description}
    \item[\boxed{c \circ \pi_1}]
        \boxed{\pi + a}
\end{description}
\end{document}
```

Does not show up as math mode in editor

![Image](https://github.com/user-attachments/assets/cd40645e-3176-4900-a650-6446598c7ca1)

### Expected behavior

The line `\pi + a` conceals the symbol `\pi`

### Actual behavior

No conceal occurs.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Linux Mint 22
  Vim version: NVIM v0.10.2
  Has clientserver: true
  Servername: /run/user/1000/nvim.20404.0

VimTeX project: main
  base: main.tex
  root: /home/anna/Documents/uni-work/rsm/project/actual
  tex: /home/anna/Documents/uni-work/rsm/project/actual/main.tex
  main parser: current file verified
  document class: article
  packages: amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm atbegshi atbegshi-ltx atveryend atveryend-ltx biblatex bigintcalc bitset blx-case-expl3 color ebproof epstopdf-base etoolbox expl3 float geometry gettitlestring graphics graphicx hycolor hyperref iftex ifthen ifvtex infwarerr intcalc keyval kvdefinekeys kvoptions kvsetkeys logreq ltxcmds nameref pdfescape pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfrcs pgfsys refcount rerunfilecheck stringenc tikz todonotes trig uniquecounter url xcolor xparse
  source files:
    main.tex
    preamble.tex
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
