### ISSUE TITLE
VimTeX: Viewer cannot find Zathura window ID!

### ISSUE THREAD

**Issue by JayanAXHF** [lervag/vimtex#3083]
### Description

Hi, 
I setup zathura on my M2 MacBook Air recently. After opening a tex file in neovim, it game me the error `VimTeX: Viewer cannot find Zathura window ID!` when I ran `\ll` or `\lv`.  I installed zathura from `zegervdv/zathura`. Judging ffrom the output of `:VimtexInfo`, `xwin id: Failed creating new xdo instance.` and surrounding in particular, I believe that this issue coould be related to `xdotool`.

### Steps to reproduce

1. nvim minimal.tex
2. `\ll` or `\lv`

### Expected behavior

When following the aboe steps, I expected this to trigger forward search.

### Actual behavior

I got the error mentioned in the title

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 15.2 (24C101)
  Vim version: NVIM v0.10.3
  Has clientserver: true
  Servername: /var/folders/dy/vxsx3_md4vd7ngkn6cs70ggw0000gn/T/nvim.jayansunil/kPUtXz/nvim.7919.0

VimTeX project: main
  base: main.tex
  root: /Users/jayansunil/Documents/MUNs/SUMMIT/report_day_2
  tex: /Users/jayansunil/Documents/MUNs/SUMMIT/report_day_2/main.tex
  main parser: current file verified
  document class: pnas-new
  packages: afterpage algorithm algorithmicx algpseudocode amsbsy amsfonts amsgen amsmath amsopn amssymb amstext array atbegshi atbegshi-ltx atveryend atveryend-ltx authblk auxhook babel bigintcalc bitset booktabs calc caption caption3 changepage color colortbl cuted enumitem etexcmds etoolbox expl3 exscale fancyhdr float fontenc fontspec fontspec-xetex footmisc geometry gettitlestring graphics graphicx helvet hycolor hyperref ifmtarg ifpdf iftex ifthen ifvtex ifxetex infwarerr inputenc intcalc jabbrv keyval kvdefinekeys kvoptions kvsetkeys lastpage lastpage2e lastpagemodern lettrine lmodern ltxcmds marginfit marginnote mdframed microtype nameref natbib needspace newfloat pdfescape pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfrcs pgfsys pnasmathematics polyglossia ragged2e refcount rerunfilecheck sidecap stfloats stringenc textcomp tikz titlesec trig uniquecounter url xcolor xfp xifthen xkeyval xparse zref-abspage zref-base
  compiler: latexmk
    engine: -xelatex
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: Failed creating new xdo instance.
    cmd_start: zathura  -x "/usr/local/Cellar/neovim/0.10.3/bin/nvim --headless -c \"VimtexInverseSearch %{line}:%{column} '%{input}'\"" --synctex-forward 71:1:'/Users/jayansunil/Documents/MUNs/SUMMIT/report_day_2/main.tex' 'main.pdf'&
  qf method: LaTeX logfile
```
