### ISSUE TITLE
VimTex returns 'compilation completed' even though latexmk fatals in `\subfile`

### ISSUE THREAD

**Issue by QSmally** [lervag/vimtex#3086]
### Description

VimTex returns a 'compilation completed' message in the command bar, but doesn't open/refresh the document with the selected viewer (as nothing was generated), when a fatal error occurs in a subfile with the `subfiles` package (only specifically tested missing an `\end`).

`minimal.tex`:

```tex
\documentclass[a4paper,10pt]{report}

\usepackage{subfiles}

\begin{document}

\subfile{problem.tex}

\end{document}
```

`problem.tex`:

```tex
\documentclass[minimal.tex]{subfiles}
\begin{document}

\chapter{foo}
\label{foo}

\begin{itemize}
    \item foo
    \item bar
% \end{itemize} % <--- this should generate an error report

\begin{itemize}
    \item foo
    \item bar
\end{itemize}

\end{document}
```

### Steps to reproduce

1. download `minimal.tex` and `problem.tex`
2. `vim -o minimal.tex`
3. `:VimtexCompileSS`
4. returns 'compilation completed'

### Expected behavior

VimTeX to return with the fatal error which occurred. `:VimtexCompileOutput`:

```
... (top omitted)

!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on Compilation/minimal.log.
Latexmk: Getting log file 'Compilation/minimal.log'
Latexmk: Examining 'Compilation/minimal.fls'
Latexmk: Examining 'Compilation/minimal.log'
Latexmk: Errors, so I did not complete making targets
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'Compilation/minimal.log' and/or above output for details
```

### Actual behavior

VimTeX returns with 'compilation completed' as if there was no fatal error which occurred

### Do you use a latexmkrc file?

yes, not relevant (for glossary)

### VimtexInfo

```yaml
System info:
  OS: macOS 12.6.3 (21G419)
  Vim version: VIM 9.1 (1-1050)
  Has clientserver: false

VimTeX project: minimal
  base: minimal.tex
  root: /Users/joey/Test
  tex: /Users/joey/Test/minimal.tex
  main parser: current file verified
  document class: report
  packages: import subfiles
  source files:
    minimal.tex
    problem.tex
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    out_dir: Compilation
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: process 4061 run
      output: /var/folders/1r/34mx0pfj0hn57tfxvjlf9pgc0000gn/T/vAqRn5i/1
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode  -pdf -outdir=Compilation -pvc -pvctimeout- -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'minimal.tex'
      pid: 4061
  viewer: Skim
  qf method: LaTeX logfile
```
