### ISSUE TITLE
use-python3-shebang.patch (Update shebang to Python 3 to fix Lintian warnings)

### ISSUE THREAD

**Issue by krekhovx** [lervag/vimtex#3088]
### Description

Hi, I am trying to add your software to Debian package and I found some warnings from Lintian utility.

Description: Update shebang to Python 3 to fix Lintian warnings
* unusual-interpreter python
* executable-not-elf-or-script

This patch fix it:

```diff
--- vim-vimtex-2.16.orig/autoload/vimtex/complete/tools/convert-cwl
+++ vim-vimtex-2.16/autoload/vimtex/complete/tools/convert-cwl
@@ -1,4 +1,4 @@
-#!/usr/bin/env python
+#!/usr/bin/env python3
 """Convert texstudio cwl files to VimTeX format"""
 import os
 import re
--- vim-vimtex-2.16.orig/autoload/vimtex/complete/tools/symbols-merge.py
+++ vim-vimtex-2.16/autoload/vimtex/complete/tools/symbols-merge.py
@@ -1,4 +1,4 @@
-#!/usr/bin/env python
+#!/usr/bin/env python3
 """Add symbols to complete files"""
 import os
 
--- vim-vimtex-2.16.orig/autoload/vimtex/complete/tools/symbols-parse-json.py
+++ vim-vimtex-2.16/autoload/vimtex/complete/tools/symbols-parse-json.py
@@ -1,3 +1,4 @@
+#!/usr/bin/env python3
 """Blahrg."""
 import json
```

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Debian GNU/Linux trixie/sid
  Vim version: VIM 9.1 (1-948, 950-967)
  Has clientserver: false

VimTeX project: example
  base: example.tex
  root: /home/builder
  tex: /home/builder/example.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
