### ISSUE TITLE
Slow includegraphic completion when existing a lot of files.

### ISSUE THREAD

**Issue by jiangyinzuo** [lervag/vimtex#3089]
### Description

My project file structure is:
```
datasets/
fig1.pdf
fig2.pdf
...
```

`datasets/` contains a lot of files that are not figures.

I want to ignore `datasets/` directory when completing `\includegraphics` commands. What should I do?

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 24.10
  Vim version: NVIM v0.11.0-dev-c7d4a77
  Has clientserver: true
  Servername: /run/user/0//nvim.72964.0

VimTeX project: main
  base: main.tex
  root: /mnt/d/doc2/PROJECTS/gpudb-project-ictdb/graph-ann
  tex: /mnt/d/doc2/PROJECTS/gpudb-project-ictdb/graph-ann/main.tex
  main parser: recursive search
  document class: IEEEtran
  packages: algorithm2e amsbsy amsfonts amsgen amsmath amsopn amssymb amstext array atbegshi atbegshi-ltx atveryend atveryend-ltx bigintcalc bitset cite epstopdf-base etoolbox gettitlestring graphics graphicx grfext hycolor hyperref ifoddpage iftex ifthen infwarerr intcalc keyval kvdefinekeys kvoptions kvsetkeys ltxcmds multirow nameref pdfescape pdftexcmds refcount relsize rerunfilecheck stringenc subfigure tabularx textcomp trig uniquecounter url xcolor xspace
  source files:
    main.tex
    abstract.tex
    1-intro.tex
    2-algos.tex
    3-setup.tex
    4-eval.tex
    5-conclude.tex
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
