### ISSUE TITLE
Neovim stuck when populating quickfix list if if `g:vimtex_quickfix_ignore_filters` is non-empty and quicker.nvim is installed

### ISSUE THREAD

**Issue by Bekaboo** [lervag/vimtex#3096]
### Description

Neovim is stuck when populating quickfix list if `g:vimtex_quickfix_ignore_filters` is non-empty and [quicker.nvim](https://github.com/stevearc/quicker.nvim) (a plugin that provides quickfix enhancements) is installed.

### Steps to reproduce

1. Creat minimal test tex file `test.tex`, this is a tex file with a syntax error that will make vimtex populate the quickfix list on compile:
    ```tex
    %-------------------------
    % Resume in Latex
    % License : MIT
    %------------------------

    \documentclass[letterpaper,9pt]{extarticle}

    \usepackage{latexsym}
    \usepackage[empty]{fullpage}
    \usepackage{titlesec}
    \usepackage{marvosym}
    \usepackage[usenames,dvipsnames]{color}
    \usepackage{verbatim}
    \usepackage{enumitem}
    \usepackage[pdftex]{hyperref}
    \usepackage{fancyhdr}
    \setlength{\footskip}{5pt}
    \linespread{0.8} % small line spacing

    \usepackage{xcolor} % http://ctan.org/pkg/xcolor
    \usepackage{hyperref} % http://ctan.org/pkg/hyperref
    \hypersetup{
      colorlinks=true,
      linkcolor=blue!100!,
      urlcolor=blue!100!
    }

    \pagestyle{fancy}
    \fancyhf{} % clear all header and footer fields
    \fancyfoot{}
    \renewcommand{\headrulewidth}{0pt}
    \renewcommand{\footrulewidth}{0pt}

    % Adjust margins
    \addtolength{\oddsidemargin}{-0.375in}
    \addtolength{\evensidemargin}{-0.375in}
    \addtolength{\textwidth}{1in}
    \addtolength{\topmargin}{-.5in}
    \addtolength{\textheight}{1in}

    \raggedbottom
    \raggedright
    \setlength{\tabcolsep}{0in}

    % Sections formatting
    \titleformat{\section}{
      \vspace{-5pt}\scshape\raggedright\large
    }{}{0em}{}[\color{black}\titlerule \vspace{-4pt}]

    %-------------------------
    % Custom commands
    \newcommand{\resumeItem}[2]{
      \item\small{
        \textbf{#1}{#2 \vspace{-1pt}}
      }
    }

    \newcommand{\resumeItemWithoutTitle}[1]{
      \item\small{
        {\vspace{-1pt}}
      }
    }

    \newcommand{\resumeSubheading}[4]{
        \vspace{-1pt}\item[]
        \begin{tabular*}{0.97\textwidth}{l@{\extracolsep{\fill}}r}
          \textbf{#1} & #2 \\
          {\small#3} & {\small #4} \\
        \end{tabular*}\vspace{-4pt}
    }

    \newcommand{\resumeSubheadingOneline}[2]{
        \vspace{-1pt}\item[]
        \begin{tabular*}{0.97\textwidth}{l@{\extracolsep{\fill}}r}
          \textbf{#1} & #2 \\
        \end{tabular*}\vspace{-4pt}
    }



    \newcommand{\resumeSubItem}[2]{\resumeItem{#1}{#2}\vspace{-4pt}}

    \renewcommand{\labelitemii}{$\circ$}

    \newcommand{\resumeSubHeadingListStart}{\begin{itemize}[leftmargin=*]}
    \newcommand{\resumeSubHeadingListEnd}{\end{itemize}}
    \newcommand{\resumeItemListStart}{\begin{itemize}}
    \newcommand{\resumeItemListEnd}{\end{itemize}\vspace{-4pt}}

    \providecommand{\tightlist}{%
      \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}

    %-------------------------------------------
    %%%%%%  CV STARTS HERE  %%%%%%%%%%%%%%%%%%%%%%%%%%%%


    \begin{document}

    %----------HEADING-----------------
    \begin{tabular*}{\textwidth}{l@{\extracolsep{\fill}}r}
      \textbf{{\LARGE Name}} & Email : \href{mailto:example@gmail.com}{nobody@mail.com}\\
      Mobile : xxxxxxxxxx \\
      Github: \href{https://github.com/example}{https://github.com/example} \\
      LinkedIn: \href{https://www.linkedin.com/in/example/}{https://www.linkedin.com/in/example/} \\
    \end{tabular*}

    %-----------RESEARCH EXPERIENCE-------------------
    \sectionResearch Experience} % Error
    \resumeSubHeadingListStart
        \resumeSubheading
        {Job position}{Location}
        {Advisor}{Duration}
        \resumeItemListStart
            \resumeItem{Topic} \\
                \begin{itemize}
                    \item[\tiny$\bullet$] Highlight 1
                    \item[\tiny$\bullet$] Highlight 2
                    \item[\tiny$\bullet$] Highlight 3
                \end{itemize}
        \resumeItemListEnd
    \resumeSubHeadingListEnd

    %-------------------------------------------
    \end{document}
    ```
2. Create minimal config file `minimal.lua`:
    ```lua
    local tmp = vim.env.TMPDIR or vim.env.TEMPDIR or vim.env.TMP or vim.env.TEMP or "/tmp"
    local data = tmp .. "/" .. (vim.env.NVIM_APPNAME or "nvim")
    local packages_root = data .. "/site"
    local cloned_root = packages_root .. "/pack/packages/start"

    local plugins = {
      ["quicker.nvim"] = "https://github.com/stevearc/quicker.nvim.git",
      ["vimtex"] = "https://github.com/lervag/vimtex.git",
    }

    vim.fn.mkdir(cloned_root, "p")
    vim.opt.pp:prepend(packages_root)
    vim.opt.rtp:prepend(packages_root)

    for plugin_name, url in pairs(plugins) do
      local plugin_path = cloned_root .. "/" .. plugin_name
      if not vim.loop.fs_stat(plugin_path) then
        vim.fn.system({ "git", "clone", url, plugin_path })
      end
    end

    vim.g.vimtex_quickfix_ignore_filters = {
      [[Warning]],
      [[Overfull]],
      [[Underfull]],
      [[Font shape `.*' undefined]],
    }

    require('quicker').setup()
    ```
3. `nvim --clean -u minimal.lua test.tex`
4. `\ll` to start continuous compiling
5. `\ll` again to stop continuous compiling
6. `\ll` again to re-start continuous compiling
7. Neovim is stuck

### Expected behavior

Neovim should not stuck.

### Actual behavior

Neovim is stuck after re-enabling continuous compiling. It is worth noting that if I remove the `g:vimtex_quickfix_ignore_filters` config the bug does not appear.

See also https://github.com/stevearc/quicker.nvim/issues/42

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Arch Linux
  Vim version: NVIM v0.11.0-dev-1720+gac207c3ac2
  Has clientserver: true
  Servername: /run/user/1000/nvim.2088084.0

VimTeX project: test
  base: test.tex
  root: /home/user/scratches
  tex: /home/user/scratches/test.tex
  main parser: current file verified
  document class: extarticle
  packages: atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook bigintcalc bitset color enumitem etoolbox exscale fancyhdr fullpage gettitlestring hycolor hyperref iftex infwarerr intcalc keyval kvdefinekeys kvoptions kvsetkeys latexsym ltxcmds marvosym nameref pdfescape pdftexcmds refcount rerunfilecheck titlesec uniquecounter url verbatim xcolor
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
