### ISSUE TITLE
Line number not parsed correctly when split over multiple lines

### ISSUE THREAD

**Issue by user202729** [lervag/vimtex#3097]
### Description

Example document

```
%! TEX program = pdflatex
\documentclass{article}
\begin{document}
{\bfseries
\fontsize{8.43146}{10}\selectfont This text is set in bold with a nonstandard size\par}
\end{document}
```

The log file contains

```
LaTeX Font Warning: Font shape `OT1/cmr/bx/n' in size <8.43146> not available
(Font)              size <8> substituted on input line 5.
```

but in the quick fix list the line number is not shown, lead to vim not moving the cursor to the correct line.

Another example (probably harder because the error message contains a full stop):

```
\documentclass{article}
\usepackage{rotating}

\begin{document}

\begin{sidewaystable}[]
  \centering
  \caption{A Simple Rotated Table}
  \begin{tabular}{|c|c|c|}
    \hline
    Header 1 & Header 2 & Header 3 \\
    \hline
    Row 1, Col 1 & Row 1, Col 2 & Row 1, Col 3 \\
    \hline
    Row 2, Col 1 & Row 2, Col 2 & Row 2, Col 3 \\
    \hline
    Row 3, Col 1 & Row 3, Col 2 & Row 3, Col 3 \\
    \hline
  \end{tabular}
  \label{tab:sideways_example}
\end{sidewaystable}

\end{document}
```

Log file:

```
LaTeX Warning: No positions in optional float specifier.
               Default added (so using `tbp') on input line 6.
```

### Do you use a latexmkrc file?

doesn't matter

### VimtexInfo

```yaml
System info:
  OS: Arch Linux
  Vim version: VIM 9.1 (1-1071)
  Has clientserver: true
  Servername: vim1

VimTeX project: a
  base: a.tex
  root: /tmp
  tex: /tmp/a.tex
  main parser: current file verified
  document class: article
  packages: amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm asypictureB asypictureBpatch catchfile csquotes currfile currfile-abspath enumitem epstopdf-base etexcmds etoolbox expl3 fancyvrb fastrecompile filecontentsdef filehook filehook-2020 fvextra graphics graphicx ifluatex ifplatform iftex ifthen infwarerr keyval kvoptions kvsetkeys l3keys2e lineno ltxcmds outputdir pdftexcmds personal personal-napkin pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfrcs pgfsys precattl pythonimmediate rotating saveenv shellesc tikz tikz-cd trig typstmathinput unicode-math-input upquote xcolor
  compiler: latexmk
    engine: -lualatex
    options:
      -file-line-error
      -latexoption=-shell-escape
      -latexoption=-recorder
      -synctex=1
      -interaction=nonstopmode
    out_dir: /tmp/.vimtex_build_dir/
    aux_dir: /tmp/.vimtex_build_dir/
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: process 522582 run
      output: /tmp/vAENw65/1
      cmd: max_print_line=2000 latexmk -file-line-error -latexoption=-shell-escape -latexoption=-recorder -synctex=1 -interaction=nonstopmode  -pdf -outdir=/tmp/.vimtex_build_dir/ -emulate-aux-dir -auxdir=/tmp/.vimtex_build_dir/ -pvc -pvctimeout- -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'a.tex'
      pid: 522582
  viewer: Zathura
    xwin id: 75497475
    cmd_start: zathura  -x "/usr/bin/vim -T dumb --not-a-term -n -c \"VimtexInverseSearch %{line}:%{column} '%{input}'\"" --synctex-forward 2:1:'/tmp/a.tex' '.vimtex_build_dir/a.pdf'&
  qf method: LaTeX logfile
```
