### ISSUE TITLE
Can i Suppress: Viewer cannot find Zathura window ID! Warning?

### ISSUE THREAD

**Issue by econhead** [lervag/vimtex#3099]
### Description

I am using vimtex with neovim and zathura as my pdf viewer on Mac OS 15.3.1 and i used this guide to set it up [https://ejmastnak.com/tutorials/vim-latex/intro/](url), Thankyou @ejmastnak for this wonderful guide.

Everything seems to be working fine for me be it forward or inverse search except for this warning as mentioned above everytime is use forward search and the focus form one window to another does not change too.

I have tried multiple ways to resolve this and i have already been through other simiilar issues like #2581, seems like there is no way to fix this afterall and i was wondering if i can suppress this warning altogether as i am using Aerospace as my window tiling manager and i use the default Aerospace keymaps like <Alt-H> and <Alt-L> to move focus manually after doing forward and backward search.

<img width="1744" alt="Image" src="https://github.com/user-attachments/assets/51e321b1-0960-4a2a-bc19-778a256e2d31" />

### Steps to reproduce

1. `nvim minimal.tex`
2. `\lv` or `:VimtexView`
3. Seeing it shows the error `VimTeX: Viewer cannot find Zathura window ID!`

### Expected behavior

No response

### Actual behavior

VimTeX: Viewer cannot find Zathura window ID!

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 15.3.1 (24D70)
  Vim version: NVIM v0.10.4
  Has clientserver: true
  Servername: /var/folders/cv/d0yg9ym90_sbdcymbm01cn480000gn/T/nvim.econhead/Yc3M70/nvim.25736.0

VimTeX project: 10_01_2025
  base: 10_01_2025.tex
  root: /Users/econhead/NOTES/Mathematics/MathClassNotes/10_01_2025
  tex: /Users/econhead/NOTES/Mathematics/MathClassNotes/10_01_2025/10_01_2025.tex
  main parser: current file verified
  document class: article
  packages: amsbsy amsfonts amsgen amsmath amsopn amssymb amstext environ epstopdf-base etoolbox fancyhdr float fontenc graphics graphicx inputenc keyval kvoptions kvsetkeys ltxcmds parskip pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfrcs pgfsys tcolorbox tikz trig trimspaces verbatim xcolor
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 7
      output: /var/folders/cv/d0yg9ym90_sbdcymbm01cn480000gn/T/nvim.econhead/Yc3M70/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode  -pdf -pvc -pvctimeout- -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' '10_01_2025.tex'
      pid: 25888
  viewer: Zathura
    xwin id: Failed creating new xdo instance.
    cmd_start: zathura  -x "/usr/local/Cellar/neovim/0.10.4/bin/nvim --headless -c \"VimtexInverseSearch %{line}:%{column} '%{input}'\"" --synctex-forward 219:1:'/Users/econhead/NOTES/Mathematics/MathClassNotes/10_01_2025/10_01_2025.tex' 'Mathematics/MathClassNotes/10_01_2025/10_01_2025.pdf'&
  qf method: LaTeX logfile
```
