### ISSUE TITLE
Lag when press o, O, u, towards the end of a rather long file

### ISSUE THREAD

**Issue by haoming-li-ling** [lervag/vimtex#3102]
### Description

When vimtex is enabled, pressing o, O, or u towards the end of a 1000-line file is laggy.

This doesn't happen towards the beginning of the same file.

This doesn't happen when vimtex is disabled.

This still happens when vimtex's syntax function is disabled. (However, even with the syntax function disabled, syntime can still generate a report, so I suspect that vimtex's syntax is not truly disabled)

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 14.0 (23A344)
  Vim version: NVIM v0.11.0-dev-1819+g1c81734871
  Has clientserver: true
  Servername: /var/folders/0j/154blqm96cjgtf7dwtccvk680000gn/T/nvim.haomingli/UpppS8/nvim.47089.0

VimTeX project: anti_locality_comp
  base: anti_locality_comp.tex
  root: /Users/haomingli/Documents/MIT/anti_locality/handout_obj
  tex: /Users/haomingli/Documents/MIT/anti_locality/handout_obj/anti_locality_comp.tex
  main parser: current file verified
  document class: article
  packages: amsbsy amsfonts amsgen amsmath amsopn amssymb amstext atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook bigintcalc bitset booktabs calc centernot cgloss cgloss4e cleveref csquotes csvsimple csvsimple-legacy elocalloc enumitem environ epstopdf-base etexcmds etoolbox expex expex-glossonly expl3 fancyvrb fontaxes fontenc forest forest-lib-linguistics geometry gettitlestring gobble graphics graphicx hycolor hyperref iftex ifthen ifvtex infwarerr inlinedef intcalc keyval kvdefinekeys kvoptions kvsetkeys l3keys2e linguex ltxcmds markdown markdownthemewitiko_markdown_defaults multicol mweights nameref natbib newpxmath newpxtext ninecolors paracol paralist pdfescape pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfopts pgfrcs pgfsys pifont refcount rerunfilecheck scalefnt shellesc soul soul-ori tabularray textcomp tikz trig trimspaces uniquecounter url xcolor xkeyval xparse xpatch xspace xstring
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    out_dir: .
    aux_dir: ./output
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: sioyek
  qf method: LaTeX logfile
```
