### ISSUE TITLE
Slow syntax highlighting with lots of inline math

### ISSUE THREAD

**Issue by lennartack** [lervag/vimtex#3107]
### Description

When there is a lot of inline math on the screen, syntax highlighting is very slow. Both vim motions and text input have a very noticable lag on my old laptop. I'm using vimtex 2.16.0.

### Steps to reproduce

minimal.tex:
```latex
\documentclass{article}

\begin{document}


The equation $a + b = c$ holds for $x^2 + y^2 = z^2$, and if $E = mc^2$, then $F = ma$ while $\Delta x \Delta p \geq \frac{h}{2\pi}$; thus, $\int_a^b f(x) \, dx = F(b) - F(a)$, also $\frac{d}{dx}(x^n) = nx^{n-1}$, considering $\sum_{n=1}^{\infty} \frac{1}{n^2} = \frac{\pi^2}{6}$, and $e^{i\pi} + 1 = 0$, so $\lim_{x \to 0} \frac{\sin x}{x} = 1$. When $R = \frac{V}{I}$, we find $\frac{1}{2}mv^2 = mgh$, and $PV = nRT$ implies $I = \int_{C} \mathbf{F} \cdot d\mathbf{r}$, where $F = q(E + v \times B)$, thus $\nabla \cdot \mathbf{E} = \frac{\rho}{\varepsilon_0}$ and $\nabla \times \mathbf{B} = \mu_0 \mathbf{J} + \mu_0\varepsilon_0 \frac{\partial \mathbf{E}}{\partial t}$. Moreover, $|z| = \sqrt{x^2 + y^2}$ when $z = x + yi$, so the recurrence $a_{n+1} = ra_n(1-a_n)$ shows $E(X) = \sum x P(x)$. Given $p(x) = \frac{1}{\sqrt{2\pi\sigma^2}}e^{-\frac{(x-\mu)^2}{2\sigma^2}}$, if $F(s) = \mathcal{L}\{f(t)\}$ then $f(t) = \mathcal{L}^{-1}\{F(s)\}$. Consider $e^x = \sum_{n=0}^{\infty} \frac{x^n}{n!}$ and $\theta = \arccos\left(\frac{x}{r}\right)$, knowing $\nabla^2 \Phi = 0$, with $c = \lambda \nu$, and if $\int_0^{\infty} e^{-x} \, dx = 1$, the power series $f(x) = \sum_{n=0}^{\infty} a_n x^n$ converges for $|x| < R$, as $\frac{d}{dt} \int_{\Omega(t)} \mathbf{F} \, dV = \int_{\Omega(t)} \frac{\partial \mathbf{F}}{\partial t} \, dV + \int_{\partial \Omega(t)} \mathbf{F} \, \mathbf{v} \cdot d\mathbf{S}$.

The equation $a + b = c$ holds for $x^2 + y^2 = z^2$, and if $E = mc^2$, then $F = ma$ while $\Delta x \Delta p \geq \frac{h}{2\pi}$; thus, $\int_a^b f(x) \, dx = F(b) - F(a)$, also $\frac{d}{dx}(x^n) = nx^{n-1}$, considering $\sum_{n=1}^{\infty} \frac{1}{n^2} = \frac{\pi^2}{6}$, and $e^{i\pi} + 1 = 0$, so $\lim_{x \to 0} \frac{\sin x}{x} = 1$. When $R = \frac{V}{I}$, we find $\frac{1}{2}mv^2 = mgh$, and $PV = nRT$ implies $I = \int_{C} \mathbf{F} \cdot d\mathbf{r}$, where $F = q(E + v \times B)$, thus $\nabla \cdot \mathbf{E} = \frac{\rho}{\varepsilon_0}$ and $\nabla \times \mathbf{B} = \mu_0 \mathbf{J} + \mu_0\varepsilon_0 \frac{\partial \mathbf{E}}{\partial t}$. Moreover, $|z| = \sqrt{x^2 + y^2}$ when $z = x + yi$, so the recurrence $a_{n+1} = ra_n(1-a_n)$ shows $E(X) = \sum x P(x)$. Given $p(x) = \frac{1}{\sqrt{2\pi\sigma^2}}e^{-\frac{(x-\mu)^2}{2\sigma^2}}$, if $F(s) = \mathcal{L}\{f(t)\}$ then $f(t) = \mathcal{L}^{-1}\{F(s)\}$. Consider $e^x = \sum_{n=0}^{\infty} \frac{x^n}{n!}$ and $\theta = \arccos\left(\frac{x}{r}\right)$, knowing $\nabla^2 \Phi = 0$, with $c = \lambda \nu$, and if $\int_0^{\infty} e^{-x} \, dx = 1$, the power series $f(x) = \sum_{n=0}^{\infty} a_n x^n$ converges for $|x| < R$, as $\frac{d}{dt} \int_{\Omega(t)} \mathbf{F} \, dV = \int_{\Omega(t)} \frac{\partial \mathbf{F}}{\partial t} \, dV + \int_{\partial \Omega(t)} \mathbf{F} \, \mathbf{v} \cdot d\mathbf{S}$.

The equation $a + b = c$ holds for $x^2 + y^2 = z^2$, and if $E = mc^2$, then $F = ma$ while $\Delta x \Delta p \geq \frac{h}{2\pi}$; thus, $\int_a^b f(x) \, dx = F(b) - F(a)$, also $\frac{d}{dx}(x^n) = nx^{n-1}$, considering $\sum_{n=1}^{\infty} \frac{1}{n^2} = \frac{\pi^2}{6}$, and $e^{i\pi} + 1 = 0$, so $\lim_{x \to 0} \frac{\sin x}{x} = 1$. When $R = \frac{V}{I}$, we find $\frac{1}{2}mv^2 = mgh$, and $PV = nRT$ implies $I = \int_{C} \mathbf{F} \cdot d\mathbf{r}$, where $F = q(E + v \times B)$, thus $\nabla \cdot \mathbf{E} = \frac{\rho}{\varepsilon_0}$ and $\nabla \times \mathbf{B} = \mu_0 \mathbf{J} + \mu_0\varepsilon_0 \frac{\partial \mathbf{E}}{\partial t}$. Moreover, $|z| = \sqrt{x^2 + y^2}$ when $z = x + yi$, so the recurrence $a_{n+1} = ra_n(1-a_n)$ shows $E(X) = \sum x P(x)$. Given $p(x) = \frac{1}{\sqrt{2\pi\sigma^2}}e^{-\frac{(x-\mu)^2}{2\sigma^2}}$, if $F(s) = \mathcal{L}\{f(t)\}$ then $f(t) = \mathcal{L}^{-1}\{F(s)\}$. Consider $e^x = \sum_{n=0}^{\infty} \frac{x^n}{n!}$ and $\theta = \arccos\left(\frac{x}{r}\right)$, knowing $\nabla^2 \Phi = 0$, with $c = \lambda \nu$, and if $\int_0^{\infty} e^{-x} \, dx = 1$, the power series $f(x) = \sum_{n=0}^{\infty} a_n x^n$ converges for $|x| < R$, as $\frac{d}{dt} \int_{\Omega(t)} \mathbf{F} \, dV = \int_{\Omega(t)} \frac{\partial \mathbf{F}}{\partial t} \, dV + \int_{\partial \Omega(t)} \mathbf{F} \, \mathbf{v} \cdot d\mathbf{S}$.

\end{document}
```

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Debian GNU/Linux 12 (bookworm)
  Vim version: NVIM v0.10.4
  Has clientserver: true
  Servername: /run/user/1000/nvim.2376017.0

VimTeX project: test
  base: test.tex
  root: redacted
  tex: redacted
  main parser: current file verified
  document class: article
  packages: enumitem
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: sioyek
  qf method: LaTeX logfile
```
