### ISSUE TITLE
va$ issue: selection is not correct

### ISSUE THREAD

**Issue by zhuosongz** [lervag/vimtex#3111]
### Description

I am using a LazyVim, with the default plugins as well as LuaSnippet and vimtex plugins

### Problem Description

When using `va$` to select math content in LaTeX:
- **Inline math `$...$`**: Only selects from the content to the ending `$` (e.g., `...$`).
- **Display math `$$...$$`**: Selects from the middle `$` to the end (e.g., `$...$$`).

### Steps to Reproduce

1. Create a minimal LaTeX file `test.tex`:
   ```tex
   This is $inline$ math.
   This is $$display$$ math.
   ```

### Expected behavior

When using `va$` to select math content in LaTeX:
- **Inline math `$...$`**:  it should select  (e.g., `$...$`).
- **Display math `$$...$$`**: it should select`$$...$$`).

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 14.3 (23D2057)
  Vim version: NVIM v0.10.1
  Has clientserver: true
  Servername: /var/folders/w0/xkvwk9yx2yj807vfx8931rv40000gn/T/nvim.zhangzs3/kbKg7O/nvim.36678.0

VimTeX project: nsfc_template
  base: 
  root: 
  tex:  
  main parser: current file verified
  document class: ctexart
  packages: CJKfntef algorithm2e algorithmicx algpseudocode amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook bigintcalc bitset bm calc caption caption3 cite color ctexhook ctexpatch enumerate enumitem eso-pic etoolbox expl3 fix-cm fontenc fontspec fontspec-xetex geometry gettitlestring graphics graphicx hycolor hyperref ifluatex ifoddpage iftex ifthen ifvtex ifxetex infwarerr intcalc keyval kvdefinekeys kvoptions kvsetkeys lscape ltxcmds mathptmx metalogo nameref natbib nsfc pdfescape pdflscape pdflscape-nometadata pdfpages pdftexcmds realscripts refcount relsize rerunfilecheck stfloats stringenc subcaption times titlesec trig uniquecounter url xcolor xeCJK xeCJKfntef xltxtra xparse xspace xtemplate xtemplate-2023-10-10 xunicode xunicode-addon zhnumber
  compiler: latexmk
    engine: -xelatex
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```

Below are the log time for my startup:

```
--- Startup times for process: Primary/TUI ---

times in msec
 clock   self+sourced   self:  sourced script
 clock   elapsed:              other lines

000.000  000.000: --- NVIM STARTING ---
000.141  000.141: event init
000.356  000.214: early init
000.967  000.611: locale set
001.027  000.060: init first window
001.468  000.441: inits 1
001.477  000.009: window checked
001.482  000.005: parsing arguments
002.001  000.035  000.035: require('vim.shared')
002.085  000.044  000.044: require('vim.inspect')
002.131  000.035  000.035: require('vim._options')
002.132  000.128  000.049: require('vim._editor')
002.134  000.198  000.034: require('vim._init_packages')
002.136  000.456: init lua interpreter
002.671  000.535: --- NVIM STARTED ---

--- Startup times for process: Embedded ---

times in msec
 clock   self+sourced   self:  sourced script
 clock   elapsed:              other lines

000.000  000.000: --- NVIM STARTING ---
000.081  000.081: event init
000.195  000.114: early init
000.536  000.341: locale set
000.573  000.037: init first window
000.835  000.262: inits 1
000.850  000.015: window checked
000.853  000.003: parsing arguments
001.225  000.026  000.026: require('vim.shared')
001.284  000.029  000.029: require('vim.inspect')
001.318  000.026  000.026: require('vim._options')
001.320  000.092  000.037: require('vim._editor')
001.321  000.161  000.043: require('vim._init_packages')
001.322  000.308: init lua interpreter
002.807  001.485: expanding arguments
002.816  000.009: inits 2
003.029  000.213: init highlight
003.030  000.001: waiting for UI
003.100  000.070: done waiting for UI
003.114  000.014: clear screen
003.172  000.007  000.007: require('vim.keymap')
004.189  000.587  000.587: require('vim.termcap')
004.365  000.123  000.123: require('vim.text')
004.440  001.324  000.607: require('vim._defaults')
004.441  000.004: init default mappings & autocommands
004.559  000.052  000.052: sourcing /opt/homebrew/Cellar/neovim/0.10.1/share/nvim/runtime/ftplugin.vim
004.635  000.022  000.022: sourcing /opt/homebrew/Cellar/neovim/0.10.1/share/nvim/runtime/indent.vim
005.440  000.492  000.492: require('lazy')
005.492  000.042  000.042: require('ffi')
005.595  000.056  000.056: require('vim.fs')
005.759  000.161  000.161: require('vim.uri')
005.767  000.269  000.052: require('vim.loader')
006.140  000.351  000.351: require('lazy.stats')
006.343  000.168  000.168: require('lazy.core.util')
006.568  000.224  000.224: require('lazy.core.config')
006.856  000.113  000.113: require('lazy.core.handler')
007.304  000.116  000.116: require('lazy.pkg')
007.308  000.294  000.178: require('lazy.core.meta')
007.313  000.456  000.162: require('lazy.core.plugin')
007.319  000.750  000.182: require('lazy.core.loader')
008.249  000.115  000.115: require('lazy.core.fragments')
010.239  000.126  000.126: require('lazyvim.util')
010.252  000.332  000.206: require('lazyvim.config')
012.101  000.596  000.596: require('lazyvim.config.options')
012.221  000.099  000.099: require('config.options')
012.337  000.104  000.104: require('lazyvim.util.plugin')
012.496  000.158  000.158: require('lazyvim.util.deprecated')
012.627  000.129  000.129: require('lazyvim.util.inject')
012.801  000.172  000.172: require('lazy.core.handler.event')
014.646  000.282  000.282: require('vim.version')
016.132  000.106  000.106: require('lazyvim.util.pick')
018.143  000.099  000.099: require('lazy.core.handler.cmd')
018.236  000.091  000.091: require('lazy.core.handler.keys')
018.322  000.083  000.083: require('lazy.core.handler.ft')
021.529  000.108  000.108: require('lazyvim.util.ui')
021.668  000.090  000.090: sourcing /opt/homebrew/Cellar/neovim/0.10.1/share/nvim/runtime/filetype.lua
022.350  000.276  000.276: require('vim.treesitter.language')
022.527  000.176  000.176: require('vim.func')
022.718  000.186  000.186: require('vim.func._memoize')
022.771  000.816  000.178: require('vim.treesitter.query')
022.784  001.073  000.257: require('nvim-treesitter.query_predicates')
023.053  000.107  000.107: require('lazyvim')
024.054  000.161  000.161: require('tokyonight.config')
024.056  000.393  000.232: require('tokyonight')
024.085  000.994  000.601: require('tokyonight')
024.246  000.084  000.084: require('tokyonight.util')
024.248  000.160  000.076: require('tokyonight.theme')
024.435  000.081  000.081: require('tokyonight.colors')
024.597  000.085  000.085: require('tokyonight.hsluv')
025.016  000.134  000.134: require('tokyonight.groups')
026.663  000.077  000.077: require('snacks.compat')
026.666  000.308  000.231: require('snacks')
026.667  000.343  000.035: sourcing /Users/usrname/.local/share/nvim/lazy/snacks.nvim/plugin/snacks.lua
027.094  000.028  000.028: sourcing /Users/usrname/.local/share/nvim/lazy/vimtex/plugin/vimtex.vim
027.208  000.012  000.012: sourcing /Users/usrname/.local/share/nvim/lazy/vimtex/ftdetect/cls.vim
027.290  000.010  000.010: sourcing /Users/usrname/.local/share/nvim/lazy/vimtex/ftdetect/tex.vim
027.335  000.009  000.009: sourcing /Users/usrname/.local/share/nvim/lazy/vimtex/ftdetect/tikz.vim
027.564  000.073  000.073: sourcing /opt/homebrew/Cellar/neovim/0.10.1/share/nvim/runtime/plugin/editorconfig.lua
027.637  000.038  000.038: sourcing /opt/homebrew/Cellar/neovim/0.10.1/share/nvim/runtime/plugin/man.lua
028.067  000.110  000.110: sourcing /opt/homebrew/Cellar/neovim/0.10.1/share/nvim/runtime/pack/dist/opt/matchit/plugin/matchit.vim
028.083  000.409  000.299: sourcing /opt/homebrew/Cellar/neovim/0.10.1/share/nvim/runtime/plugin/matchit.vim
028.208  000.084  000.084: sourcing /opt/homebrew/Cellar/neovim/0.10.1/share/nvim/runtime/plugin/matchparen.vim
028.389  000.146  000.146: sourcing /opt/homebrew/Cellar/neovim/0.10.1/share/nvim/runtime/plugin/netrwPlugin.vim
028.467  000.036  000.036: sourcing /opt/homebrew/Cellar/neovim/0.10.1/share/nvim/runtime/plugin/osc52.lua
028.590  000.082  000.082: sourcing /opt/homebrew/Cellar/neovim/0.10.1/share/nvim/runtime/plugin/rplugin.vim
028.674  000.045  000.045: sourcing /opt/homebrew/Cellar/neovim/0.10.1/share/nvim/runtime/plugin/shada.vim
028.725  000.010  000.010: sourcing /opt/homebrew/Cellar/neovim/0.10.1/share/nvim/runtime/plugin/spellfile.vim
029.433  024.675  015.856: require('config.lazy')
029.434  024.694  000.019: sourcing /Users/usrname/.config/nvim/init.lua
029.438  000.229: sourcing vimrc file(s)
029.644  000.029  000.029: sourcing /opt/homebrew/Cellar/neovim/0.10.1/share/nvim/runtime/filetype.lua
029.810  000.035  000.035: sourcing /opt/homebrew/Cellar/neovim/0.10.1/share/nvim/runtime/syntax/synload.vim
029.851  000.143  000.108: sourcing /opt/homebrew/Cellar/neovim/0.10.1/share/nvim/runtime/syntax/syntax.vim
029.856  000.246: inits 3
032.497  002.641: reading ShaDa
032.553  000.056: opening buffers
032.680  000.118  000.118: require('snacks.explorer')
032.717  000.046: BufEnter autocommands
032.719  000.001: editing files in windows
032.735  000.017: VimEnter autocommands
033.056  000.103  000.103: require('snacks.util')
033.073  000.322  000.220: require('snacks.dashboard')
034.478  000.137  000.137: require('snacks.scroll')
034.599  000.104  000.104: require('snacks.animate')
034.900  000.084  000.084: require('vim.ui')
034.902  000.243  000.159: require('snacks.input')
035.055  000.145  000.145: require('snacks.scope')
035.221  000.088  000.088: require('snacks.picker')
035.330  000.107  000.107: require('snacks.picker.config')
035.551  000.220  000.220: require('snacks.picker.config.highlights')
035.897  000.344  000.344: require('snacks.picker.config.defaults')
036.235  000.337  000.337: require('snacks.picker.config.sources')
036.323  000.086  000.086: require('snacks.picker.config.layouts')
037.812  002.943: UIEnter autocommands
037.813  000.001: before starting main loop
037.872  000.003  000.003: require('vim.F')
038.151  000.335: first screen update
038.152  000.001: --- NVIM STARTED ---
```
