### ISSUE TITLE
Inverse search not working

### ISSUE THREAD

**Issue by supinie** [lervag/vimtex#3113]
### Description

I am nix and home-manager on Ubuntu to manage my configuration files, and am struggling to get inverse search using Zathura to work. I have gone through related issues but cannot find a solution, and am not finding any error logs that would be useful to debug with.

### Steps to reproduce

The relevant lines from my nvim configuration are:

```vimscript
                " Filter out some compilation warning messages from QuickFix display
                let g:vimtex_quickfix_ignore_filters = [
                      \ 'Underfull \\hbox',
                      \ 'Overfull \\hbox',
                      \ 'LaTeX Warning: .\+ float specifier changed to',
                      \ 'LaTeX hooks Warning',
                      \ 'Package siunitx Warning: Detected the "physics" package:',
                      \ 'Package hyperref Warning: Token not allowed in a PDF string',
                      \ 'Missing ',
                      \]
                let g:vimtex_view_method = 'zathura'
                let g:tex_flavor='latex'
                set conceallevel=1
                set concealcursor=nc
                let g:tex_conceal='abdmg'

                " Function to toggle vimtex_quickfix_mode
                function! ToggleVimtexQuickfixMode()
                    if g:vimtex_quickfix_mode == 1
                        let g:vimtex_quickfix_mode = 0
                    else
                        let g:vimtex_quickfix_mode = 1
                    endif
                    echo "vimtex_quickfix_mode is now " . g:vimtex_quickfix_mode
                endfunction

                " Map Shift-Q to toggle vimtex_quickfix_mode
                nnoremap <S-q> :call ToggleVimtexQuickfixMode()<CR>

                autocmd BufEnter *.tex set conceallevel=1
                autocmd BufEnter *.tex set concealcursor=nc
```

(I'm not sure why but something else overwrites conceallevel settings hence the last two lines)

and I only have the following for Zathura:

```
        set highlight-color "rgba(255, 255, 139, 0.2)"

```

I'm unsure how to setup a minimal.vim, sorry.

### Expected behavior

Standard compilation with `\ll` and forward search with `\lv` work as expected, but `<C-click>` in Zathura does nothing.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 24.04.2 LTS
  Vim version: NVIM v0.10.4
  Has clientserver: true
  Servername: /run/user/1790402/nvim.754323.0

VimTeX project: main
  base: main.tex
  root: /home/jcl24/git/cubic_isomorphism_problem
  tex: /home/jcl24/git/cubic_isomorphism_problem/main.tex
  main parser: current file verified
  document class: article
  packages: amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm atbegshi atbegshi-ltx atveryend atveryend-ltx babel bigintcalc bitset color etoolbox geometry gettitlestring hycolor hyperref iftex ifvtex infwarerr intcalc keyval kvdefinekeys kvoptions kvsetkeys ltxcmds nameref pdfescape pdftexcmds refcount rerunfilecheck stringenc uniquecounter url
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 10
      output: /tmp/nvim.1790402/0O7jUc/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode  -pdf -pvc -pvctimeout- -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'main.tex'
      pid: 754374
  viewer: Zathura
    xwin id: 0
    cmd_start: zathura  -x "/nix/store/jg3ia0rsj2jd9vyhdx4m7kz4xi7n7wl1-neovim-unwrapped-0.10.4/bin/nvim --headless -c \"VimtexInverseSearch %{line}:%{column} '%{input}'\"" --synctex-forward 13:1:'/home/jcl24/git/cubic_isomorphism_problem/main.tex' 'main.pdf'&
  qf method: LaTeX logfile
```
