### ISSUE TITLE
Ctrl+U behaves unexpectedly in tabular environment

### ISSUE THREAD

**Issue by user202729** [lervag/vimtex#3117]
### Description

Consider the following document.

```
\documentclass{article}
\begin{document}
\begin{tabular}{cc}
1 & 2 \\
& 4
\end{tabular}
\end{document}
```

If the whole document is selected then press `=`, it is reformatted as follows (assume tabstop = 2)

```
\documentclass{article}
\begin{document}
\begin{tabular}{cc}
  1 & 2 \\
    & 4
\end{tabular}
\end{document}
```

So far, so good. However the problem happens when the document is as follows

```
\documentclass{article}
\begin{document}
\begin{tabular}{cc}
  1 & 2 \\
  3[cursor] & 4
\end{tabular}
\end{document}
```

and the user presses ctrl-U in insert mode, the document becomes

```
\documentclass{article}
\begin{document}
\begin{tabular}{cc}
  1 & 2 \\
   [cursor] & 4
\end{tabular}
\end{document}
```

(note that there are 3 spaces before the cursor). This is hardly what the user wants.

(Not sure if this is fixable because after all the same indent function is used for both ctrl-U and =.)

Side note: `c^` in normal mode doesn't have this problem, obviously.

### Do you use a latexmkrc file?

yes

### VimtexInfo

```yaml
System info:
  OS: Arch Linux
  Vim version: VIM 9.1 (1-1071)
  Has clientserver: true
  Servername: vim2

VimTeX project: a
  base: a.tex
  root: /tmp
  tex: /tmp/a.tex
  main parser: fallback current file
...
```
