### ISSUE TITLE
Zathura window does not open after compiling!

### ISSUE THREAD

**Issue by econhead** [lervag/vimtex#3120]
### Description

I have been using Zathura as my PDF viewer for almost three weeks now, and it used to work just fine. Today, after compiling a document, the PDF viewer did not show up. So, I tried using Skim as my PDF viewer instead, and it worked perfectly.

I tried debugging it on my own, but nothing seems to work. Zathura was working fine when used for opening other PDFs directly from the terminal. I thought DBus might be causing some issues, so I tried reinstalling it. However, even after reinstalling DBus, Zathura is still working fine, but when I use it as my PDF viewer in VimTeX, it does not open.

This is my `vimtex.lua` file

```lua
return {
  "lervag/vimtex",
  lazy = false, -- we don't want to lazy load VimTeX
  -- tag = "v2.15", -- uncomment to pin to a specific release
  init = function()
    -- VimTeX configuration goes here, e.g.
    vim.g.vimtex_view_method = "zathura_simple"
    -- vim.g.vimtex_view_skim_sync = 1
    vim.g.vimtex_quickfix_ignore_filters = {
      "Underfull",
      "Overfull",
    }
    vim.o.conceallevel = 1
    vim.g.tex_conceal = "abdmg"
    -- vim.g.vimtex_view_forward_search_on_start = 0
    vim.g.vimtex_compiler_latexmk = {
      aux_dir = "/Users/econhead/.texfiles/",
    }
    vim.g.vimtex_quickfix_mode = 0
  end,
}
```

### Output of Checkhealth for VimTeX

```
vimtex: health#vimtex#check

VimTeX ~
- OK Vim version should have full support!
- OK Zathura should work properly!
- OK Compiler should work!
```

### Steps to reproduce

1. vim `minimal.tex`

   ```tex
   \documentclass{minimal}
   \begin{document}
   Hello world!
   \end{document}
   ```

2. `:VimtexCompile`

### Expected behavior

After Compiling zathura window should open!

### Actual behavior

After Compiling Zathura window does not show up!

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 15.3.1 (24D70)
  Vim version: NVIM v0.10.4
  Has clientserver: true
  Servername: /var/folders/cv/d0yg9ym90_sbdcymbm01cn480000gn/T/nvim.econhead/wwrL7z/nvim.5780.0

VimTeX project: minimal
  base: minimal.tex
  root: /Users/econhead
  tex: /Users/econhead/minimal.tex
  main parser: fallback current file
  document class: 
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    aux_dir: /Users/econhead/.texfiles/
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 9
      output: /var/folders/cv/d0yg9ym90_sbdcymbm01cn480000gn/T/nvim.econhead/wwrL7z/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode  -pdf -emulate-aux-dir -auxdir=/Users/econhead/.texfiles/ -pvc -pvctimeout- -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'minimal.tex'
      pid: 6137
  viewer: Zathura
    cmd_start: zathura  -x "/opt/homebrew/Cellar/neovim/0.10.4_1/bin/nvim --headless -c \"VimtexInverseSearch %{line}:%{column} '%{input}'\"" --synctex-forward 4:30:'/Users/econhead/minimal.tex' 'minimal.pdf'&
  qf method: LaTeX logfile
```
