### ISSUE TITLE
Reuse window doesn't work

### ISSUE THREAD

**Issue by ai4bing** [lervag/vimtex#3121]
### Description

The `--reuse-window` option  doesn't work now.
Every time I `:VimtexView` it opens another window.

### Expected behavior

Should use the same window when VimtexView is executed.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 15.2 (24C101)
  Vim version: NVIM v0.10.4
  Has clientserver: true
  Servername: /var/folders/ml/cbds1cb560d33vjv2bfh9vyw0000gn/T/nvim.mbx/P2bYEU/nvim.36255.0

VimTeX project: main
  base: main.tex
  root: /Users/mbx/test/textest
  tex: /Users/mbx/test/textest/main.tex
  main parser: fallback current file
  document class: 
  packages: amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm auxhook bm booktabs calc color empheq etexcmds etoolbox expl3 geometry graphics graphicx iftex ifvtex infwarerr keyval kvdefinekeys kvoptions kvsetkeys l3keys2e lipsum ltxcmds mathtools mdframed mhsetup needspace pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfplots pgfrcs pgfsys psfrag tikz trig xcolor xparse zref-abspage zref-base
  compiler: latexmk
    engine: -xelatex
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 16
      output: /var/folders/ml/cbds1cb560d33vjv2bfh9vyw0000gn/T/nvim.mbx/P2bYEU/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode  -xelatex -pvc -pvctimeout- -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'main.tex'
      pid: 38733
  viewer: sioyek
    job: 
      pid: -
      cmd: /Applications/sioyek.app/Contents/MacOS/sioyek --reuse-window --inverse-search "/opt/homebrew/Cellar/neovim/0.10.4_1/bin/nvim --headless -c \"VimtexInverseSearch %2 '%1'\"" --forward-search-file '/Users/mbx/test/textest/main.tex' --forward-search-line 1 '/Users/mbx/test/textest/main.pdf'
    cmd_start: /Applications/sioyek.app/Contents/MacOS/sioyek --reuse-window --inverse-search "/opt/homebrew/Cellar/neovim/0.10.4_1/bin/nvim --headless -c \"VimtexInverseSearch %2 '%1'\"" --forward-search-file '/Users/mbx/test/textest/main.tex' --forward-search-line 1 '/Users/mbx/test/textest/main.pdf'
  qf method: LaTeX logfile
```
