### ISSUE TITLE
E5009 error in :checkhealth vimtex compiler check

### ISSUE THREAD

**Issue by sadid** [lervag/vimtex#3125]
### Description

The `:checkhealth` nvim gives an error while everything else seems to be working, including compilation (` ,ll`), the viewer, and Synctex. The error happens in the running buffer and not the health report.

I have the same error on macos as well.

### Steps to reproduce

1. nvim (this happen even on default nvim buffer)
2. issue :checkhealth

### Expected behavior

no error show up while running checkhealth

### Actual behavior

```bash

E5009: Invalid $VIMRUNTIME: /usr/share/nvim/runtime
Error executing lua: function health#vimtex#check[8]..<SNR>194_check_compiler, line 3: Vim(if):E1174: String required for argument 1
stack traceback:
        [C]: in function 'call'
        /usr/share/nvim/runtime/lua/vim/health.lua:429: in function '_check'
        [string "<nvim>"]:1: in main chunk

```

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Linux 6.13.7-zen1-1-zen
  Vim version: NVIM v0.10.4
  Has clientserver: true
  Servername: /run/user/1000/nvim.2142322.0

VimTeX project: test
  base: test.tex
  root: /home/sadid/Desktop/test/latexify
  tex: /home/sadid/Desktop/test/latexify/test.tex
  main parser: fallback current file
  document class: 
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
