### ISSUE TITLE
latexmk has no pvctimeout option

### ISSUE THREAD

**Issue by lucasreddinger** [lervag/vimtex#3129]
### Description

Hi,

A web search found zero results for this. Sorry if it's been asked.

I installed vimtex and tried to compile. I get this:

```
Latexmk: -pvctimeout- bad option

Latexmk: Bad options specified
Use
   latexmk -help
to get usage information
```

Snippet from ``latexmk -h`:

```
   -print=ps      - when file is to be printed, print the ps file (default)
   -print=pdf     - when file is to be printed, print the pdf file
   -pv    - preview document.  (Side effect turn off continuous preview)
   -pv-   - turn off preview mode
   -pvc   - preview document and continuously update.  (This also turns
                on force mode, so errors do not cause latexmk to stop.)
            (Side effect: turn off ordinary preview mode.)
   -pvc-  - turn off -pvc
   -quiet    - silence progress messages from called programs
   -r <file> - Read custom RC file
```

So what should I do, besides `sed -ibk '%s/-pvctimeout-//g' .vim/plugged/vimtex/autoload/vimtex/compiler/latexmk.vim` ?

Am I missing out on something important?

Thanks for all your work on this project!

BTW, I am on this:

```
menthe% uname -mrs 
OpenBSD 7.6 amd64
menthe% latexmk -v 

Latexmk, John Collins, 19 Jan. 2017. Version 4.52c
menthe% 
```

I'm running the newest texlive package for OpenBSD, so I cannot upgrade, if that's the solution.

### Steps to reproduce

Install OpenBSD. Install texlive and vim from OpenBSD packages-latest. Install vim-plug and vimtex.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: OpenBSD 7.6
  Vim version: VIM 9.1 (1-1006)
  Has clientserver: false

VimTeX project: ms
  base: ms.tex
  root: /home/lucas/gh-wd/ccr/paper
  tex: /home/lucas/gh-wd/ccr/paper/ms.tex
  main parser: current file verified
  document class: scrartcl
  packages: XCharter adjcalc adjustbox amsbsy amsgen amsmath amsopn amstext array atbegshi
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: process 66270 run
      output: /tmp/vzahnPR/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=n
      pid: 66270
  viewer: MuPDF
    xwin id: 0
    job: 
      pid: 26983
      cmd: mupdf '/home/lucas/gh-wd/ccr/paper/ms.pdf'
    cmd_start: mupdf '/home/lucas/gh-wd/ccr/paper/ms.pdf'
  qf method: LaTeX logfile
```
