### ISSUE TITLE
`out_dir` ignored with `vimtex_compiler_generic`

### ISSUE THREAD

**Issue by JayanAXHF** [lervag/vimtex#3130]
### Description

I was trying to get tectonic to work with vimtex, in particular, I wanted to get continuous compilation to work. After some digging, I managed to get it to work. The problem is that, `tectonic -X watch` outputs in the `build/default` directory. Even after setting `out_dir` in my `init.lua` file, Vimtex still refuses to read the file.

### Steps to reproduce

1. Add the following snippet to your `init.lua` file:
```lua
vim.g.vimtex_compiler_generic = {
	command = "tectonic -X watch",
	out_dir = "build/default",
}
```
2. Compile with `<localleader>ll` and try to view with `<localleader>lv`.

`minimal.tex` file:
```latex
\documentclass{minimal}
\begin{document}
Hello world!
\end{document}
```

### Expected behavior

I expected Vimtex to open the pdf in my pdf viewer

### Actual behavior

Vimtex errors with `Vimtex: Viewer cannot read PDF file!`

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 15.2 (24C101)
  Vim version: NVIM v0.10.3
  Has clientserver: true
  Servername: /var/folders/dy/vxsx3_md4vd7ngkn6cs70ggw0000gn/T/nvim.jayansunil/DchT2l/nvim.75751.0

VimTeX project: main
  base: main.tex
  root: /Users/jayansunil/Dev/testing/src
  tex: /Users/jayansunil/Dev/testing/src/main.tex
  main parser: current file verified
  document class: rho-class/rho
  packages: babel
  compiler: generic
    options:
      -Z
      search-path=/usr/local/texlive/2025/texmf-dist/tex/latex/biblatex
    out_dir: build/main
    job: 
      jobid: 9
      output: /var/folders/dy/vxsx3_md4vd7ngkn6cs70ggw0000gn/T/nvim.jayansunil/DchT2l/2
      cmd: tectonic -X watch 
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```
