### ISSUE TITLE
Help request: Can't figure out how to disable the inline preview after \ref{} calls

### ISSUE THREAD

**Issue by richardsc** [lervag/vimtex#3135]
### Description

As in the title, my default configuration of vimtex displays "ghost text" after a \ref{} that inserts a preview of the things I'm referencing, e.g. the figure caption, equation number, etc (see screenshot). Apologies if I just completely missed this in the manual (I'm new to both neovim and vimtex), but I'd be very grateful if someone could point me at the lua options (I'm using Lazyvim) to disable it.

Thanks for a great plugin! I'm a 15 year Emacs+Auctex user, and vimtex is a big draw for convincing me to "change teams" 😄 

<img width="1297" alt="Image" src="https://github.com/user-attachments/assets/94c4884f-e9f2-429e-92e2-363c7d39b887" />

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 15.3.1 (24D70)
  Vim version: NVIM v0.10.4
  Has clientserver: true
  Servername: /var/folders/pj/42xw7sns6kq9pwkf72h9zdyr0000gn/T/nvim.richardsc/9g6h91/nvim.95580.0

VimTeX project: 01_document_with_figure
  base: 01_document_with_figure.tex
  root: /Users/richardsc/research/work/misc/025_vimtex_examples
  tex: /Users/richardsc/research/work/misc/025_vimtex_examples/01_document_with_figure.tex
  main parser: current file verified
  document class: article
  packages: anysize epstopdf-base fancyhdr graphics graphicx keyval lineno natbib trig
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
