### ISSUE TITLE
When vimtex-compile is started for multiple independent tex documents, the pdf viewer opens only for the last one.

### ISSUE THREAD

**Issue by omnster** [lervag/vimtex#3136]
### Description

I observed the following behavior today.  I have two independent latex files in the same directory (one is a manuscript, and another is the response to peer review), and I am going to make changes in both (write a bit of response, then adjust the manuscript).  So I open both files in side-by-side vim splits and hit `<leader>ll` in each.  I noticed that if I start compiling the second file before the PDF viewer opens for the first one, this viewer for the first one will not open.  In other words, it seems that when I start to compile multiple files at once, the PDF viewer will open only for the last one.

I'd rather not call this an issue, just a minor inconsistency.

Thanks for the great plugin!

### Steps to reproduce

I am using `minimal.vim` from the example, and two files `minimal1.tex` and `minimal2.tex` that are both a copy of `minimal.tex` from the example.
 
1. `vim -u minimal.vim minimal1.tex minimal2.tex`
2. Open two files in splits, then `:windo VimtexCompile`

Both PDFs are produced, but only one is opened in the viewer.

### Expected behavior

I expect two PDF viewers to be started.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: EndeavourOS Linux
  Vim version: VIM 9.1 (1-1169)
  Has clientserver: true
  Servername: VIM1

VimTeX project: m1
  base: m1.tex
  root: /tmp/vimtextest
  tex: /tmp/vimtextest/m1.tex
  main parser: current file verified
  document class: minimal
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
