### ISSUE TITLE
inverse search behaves strangely when in insert mode

### ISSUE THREAD

**Issue by user202729** [lervag/vimtex#3137]
### Description

1. make some long document

<details>
<summary>Code</summary>

```tex
\documentclass{article}
\begin{document}

first page

first page

first page

first page

first page

first page

first page

first page

first page

first page

first page

\clearpage

second page

second page

second page

second page

second page

second page

second page

second page

second page

second page

second page

\end{document}
```
</details>

2. compile with synctex enabled
3. move vim cursor to the start of the document and **enter insert mode in vim**. Notice `-- INSERT --` appear in status bar of vim
4. ctrl-click on **zathura** on the second page, see cursor move to the correct line (let's say line 40) and `-- INSERT --` still appear in status bar of vim
5. press `[↓]` arrow. Notice now cursor is on line **2** instead of 41.

Not sure if this has anything to do with xdotool (I have xdotool enabled so that when inverse search is performed then the cursor get moved to click on vim window). Might be some race condition on vim side as well.

As a hack, I figure out this works, but I don't know why

```diff
diff --git a/autoload/vimtex/view.vim b/autoload/vimtex/view.vim
index 6cdae5c6..be5335f8 100644
--- a/autoload/vimtex/view.vim
+++ b/autoload/vimtex/view.vim
@@ -122,6 +128,7 @@ function! vimtex#view#inverse_search(line, filename, column = 0) abort " {{{1
     call b:vimtex.viewer.xdo_focus_vim()
   endif
   redraw
+  call feedkeys("\<esc>")
 
   if exists('#User#VimtexEventViewReverse')
     doautocmd <nomodeline> User VimtexEventViewReverse
```

### Do you use a latexmkrc file?

Yes

### VimtexInfo

```yaml
System info:
  OS: Arch Linux
  Vim version: VIM 9.1 (1-1071)
  Has clientserver: true
  Servername: vim

VimTeX project: a
  base: a.tex
  root: /tmp
  tex: /tmp/a.tex
  main parser: current file verified
  document class: myclass
  packages: amsthm cleveref
  compiler: latexmk
    engine: -lualatex
    options:
      -file-line-error
      -latexoption=-shell-escape
      -latexoption=-recorder
      -synctex=1
      -interaction=nonstopmode
    out_dir: /tmp/.vimtex_build_dir/
    aux_dir: /tmp/.vimtex_build_dir/
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: process 1654969 run
      output: /tmp/vxna8EV/2
      cmd: max_print_line=2000 latexmk -file-line-error -latexoption=-shell-escape -latexoption=-recorder -synctex=1 -interaction=nonstopmode  -lualatex -outdir=/tmp/.vimtex_build_dir/ -emulate-aux-dir -auxdir=/tmp/.vimtex_build_dir/ -pvc -pvctimeout- -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'a.tex'
      pid: 1654969
  viewer: Zathura
    xwin id: 58720259
    cmd_start: zathura  -x "/usr/bin/vim -T dumb --not-a-term -n -c \"VimtexInverseSearch %{line}:%{column} '%{input}'\"" --synctex-forward 6:10:'/tmp/a.tex' '.vimtex_build_dir/a.pdf'&
  qf method: LaTeX logfile
```
