### ISSUE TITLE
vimtex doesn't update which TeX Live version to use when in MacVim

### ISSUE THREAD

**Issue by jaythad13** [lervag/vimtex#3142]
### Description

I recently updated TeX Live 2024 to TeX Live 2025. In TL2025 I downloaded the fixdif package which I did not have in my TL2024 distribution (this behaviour is the same regardless of the package — it works for say, rsfso as well).

If I try to compile test.tex which uses fixdif with latexmk directly in the terminal then latexmk calls pdfTeX which uses TL2025 and there are no problems. See the first line of the log file below.

```
This is pdfTeX, Version 3.141592653-2.6-1.40.27 (TeX Live 2025) (preloaded format=pdflatex 2025.4.2)  3 APR 2025 02:03
```

 However, if I compile test.tex using vimtex, then latexmk calls pdfTeX which uses TL2024 and then it can't find the file fixdif.sty. Again, the first line of the log file is below

```
This is pdfTeX, Version 3.141592653-2.6-1.40.26 (TeX Live 2024) (preloaded format=pdflatex 2024.6.20)  3 APR 2025 01:49
```
and searching for "fixdif" shows the following error in the log file

```
! LaTeX Error: File `fixdif.sty' not found.
```

What's most strange about this is that this only happens when I compile in the MacVim app. When I compile (even using the MacVim terminal vim) in the terminal, there is no problem.

I'm using vimtex through vim-plug on MacVim (on MacOS Sequoia). My .vimrc is below

```
" default color scheme
colorscheme habamax

" default font
set guifont=DejaVu\ Sans\ Mono:h11

" enables file type detection, file-specific plugins, and file-specific indentation

filetype on
filetype plugin on
filetype indent on

" key mappings

" map up-down key bindings to consider wrapping (j -> gj, k -> gk) 
noremap j gj
noremap k gk

" manages plugins with vim-plug

call plug#begin()

Plug 'lervag/vimtex'

Plug 'SirVer/ultisnips'

Plug 'petRUShka/vim-sage'

" currently DISABLED
if has('nvim')
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
  Plug 'Shougo/deoplete.nvim'
  Plug 'roxma/nvim-yarp'
  Plug 'roxma/vim-hug-neovim-rpc'
endif
" let g:deoplete#enable_at_startup = 1

call plug#end()

" VimTeX settings

" maps cmpl to compile in normal mode instead of ll
nmap <localleader>cmpl <Plug>(vimtex-compile)

let g:tex_flavor='latex'

let g:vimtex_view_method='skim'	" uses Skim as the VimTeX PDF viewer

let g:vimtex_quickfix_open_on_warning=0	" don't open QuickFix for warnings, only for errors
let g:vimtex_quickfix_autoclose_after_keystrokes=2	" close the QuickFix window automatically after 2 keystrokes

set conceallevel=2	" concealment
let g:tex_conceal='abdmg'

" spell check settings

setlocal spell
set spelllang=en_gb
inoremap <C-l> <c-g>u<Esc>[s1z=`]a<c-g>u

" UltiSnips settings

let g:UltiSnipsExpandTrigger       = '<Tab>'    " use Tab to expand snippets
let g:UltiSnipsJumpForwardTrigger  = '<Tab>'    " use Tab to move forward through tabstops
let g:UltiSnipsJumpBackwardTrigger = '<S-Tab>'	" use Shift-Tab to move backward through tabstops

" deoplete settings for VimTeX
" currently DISABLED

" let g:deoplete#enable_at_startup = 1

  call deoplete#custom#var('omni', 'input_patterns', {
          \ 'tex': g:vimtex#re#deoplete
          \})

set completeopt-=preview

" VimCompletesMe settings for VimTeX

let g:vcm_default_maps = 0

imap <C-x> <plug>vim_completes_me_forward
imap <C-z> <plug>vim_completes_me_backward

  augroup VimCompletesMeTex
    autocmd!
    autocmd FileType tex
        \ let b:vcm_omni_pattern = g:vimtex#re#neocomplete
  augroup END
  
" makes conceal look nice and not greyed out
hi clear Conceal
```

 I know my .zshrc path is fine because latexmk works on its own, but here it is just in case
```
/opt/homebrew/opt/m4/bin:/opt/homebrew/opt/m4/bin:/usr/local/texlive/2025/bin/universal-darwin::/opt/homebrew/bin:/Library/Frameworks/Python.framework/Versions/3.12/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/TeX/texbin:/Users/jayden/.cargo/bin:/opt/homebrew/bin/pstoedit
```

Thank you for helping out with this and creating this software! I hope this is enough to help me with this issue

### Steps to reproduce

1. write a tex file `minimal.tex` that requires a package that you downloaded in TL2025 but is not in your TL2024 distro
2. `latexmk -pdf test.tex` or `latexmk minimal.tex`
3. delete all auxiliary files
4. compile `minimal.tex` in vimtex in MacVim

An example of minimal.tex
```
\documentclass{article}
\usepackage{fixdif}
\begin{document}
$\d f$ is the differential of $f$.
\end{document}
```

### Expected behavior

`test.tex` compiles in vimtex and with latexmk using TL2025

### Actual behavior

`test.tex` compiles in latexmk using TL2025. However, in vimtex in MacVim an error is shown for missing package

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 14.0 (23A344)
  Vim version: VIM 9.1 (1-1128)
  Has clientserver: true
  Servername: VIM

VimTeX project: test
  base: test.tex
  root: /Users/jayden/Desktop/Math/LaTeX test
  tex: /Users/jayden/Desktop/Math/LaTeX test/test.tex
  main parser: current file verified
  document class: hmcpset
  packages: amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook bigintcalc bitset boxedminipage calc classico enumitem eso-pic etoolbox eulervm fixdif float fontaxes fontenc geometry gettitlestring graphics graphicx hw-preamble hycolor hyperref ifluatex ifmtarg ifpdf iftex ifthen ifvtex ifxetex import inconsolata infwarerr intcalc keyval kvdefinekeys kvoptions kvsetkeys ltxcmds mathpazo mathrsfs nameref parskip pdfescape pdfpages pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfrcs pgfsys refcount rerunfilecheck stringenc textcomp tikz tikz-cd transparent transparent-nometadata trig uniquecounter url xcolor xifthen xkeyval
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Skim
  qf method: LaTeX logfile
```
