### ISSUE TITLE
Duplicate tag "<plug>(vimtex-toggle-star)"

### ISSUE THREAD

**Issue by chardoncs** [lervag/vimtex#3148]
### Description

Looks like there are two `<plug>(vimtex-toggle-star)` in the tags file.

~~Is it caused by commit c6bab47 ?~~

![Image](https://github.com/user-attachments/assets/b7cc50b1-966d-48c1-b6da-1b263001130a)

![Image](https://github.com/user-attachments/assets/472dcdf1-9002-47b8-9b63-0b0868e88707)

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Linux 6.6.7-arch1-1
  LaTeX version: pdfTeX 3.141592653-2.6-1.40.27 (TeX Live 2026/dev/Arch Linux)
  Vim version: NVIM v0.11.0
  Has clientserver: true
  Servername: /run/user/1000/nvim.20901.0
  $PATH:
    - /home/chardon/.bun/bin
    - /home/chardon/.cargo/bin
    - /home/chardon/.local/bin
    - /home/chardon/.local/share/gem/ruby/default/bin
    - /home/chardon/go/bin
    - /opt/cuda/bin
    - /opt/cuda/nsight_compute
    - /opt/cuda/nsight_systems/bin
    - /usr/bin
    - /usr/bin/core_perl
    - /usr/bin/site_perl
    - /usr/bin/vendor_perl
    - /usr/lib/emscripten
    - /usr/lib/jvm/default/bin
    - /usr/lib/rustup/bin
    - /usr/local/bin
    - /usr/local/sbin
    - /var/lib/flatpak/exports/bin

VimTeX project: f
  base: f.tex
  root: /tmp
  tex: /tmp/f.tex
  main parser: fallback current file
  document class: 
  compiler: latexmk
    engine: -xelatex
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
      -shell-escape
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
