### ISSUE TITLE
\cite does not show the citation keys when it goes to the next line

### ISSUE THREAD

**Issue by vasi786** [lervag/vimtex#3158]
### Description

Hi, I am writing a document and found that `\cite` when started in a line loads the citation keys in the line _n_. However, due to the text wrap when I go to the next line _n+1_, it does not load the citation keys anymore. Is this expected behavior and any workarounds for it?

### Steps to reproduce

```tex
\documentclass{article}
\usepackage{cite}
\begin{document}
Huntington’s disease, Alzheimer’s disease, and Parkinson’s disease \cite{Hageman2010, Kakkar2016, Osterlund2020,Osterlund2023}.
\bibliographystyle{unsrt}
\bibliography{Zotero}
\end{document}
```

### Expected behavior

The citation keys should show up in the autocomplete menu when I go to the next line, i.e., for Osterlund2020 and Osterlund2023

### Actual behavior

For the citation keys Osterlund2020 and Osterlund2023, the citation keys do not show in the autocomplete menu.

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
System info:
  OS: macOS 15.4.1 (24E263)
  LaTeX version: pdfTeX 3.141592653-2.6-1.40.27 (TeX Live 2025)
  Vim version: NVIM v0.11.0
  Has clientserver: true
  Servername: /var/folders/jj/87vb3tgx2914zy_7nfv3lwt80000gn/T/nvim.vasi/o42g6J/nvim.29122.0
  $PATH:

VimTeX project: main
  base: main.tex
  root: 
  tex: 
  main parser: current file verified
  document class: article
  packages: amsbsy amsfonts amsgen amsmath amsopn amssymb amstext array atbegshi atbegshi-ltx atveryend atveryend-ltx babel bigintcalc bitset calc caption caption3 chemgreek cite color colortbl epstopdf-base etoolbox expl3 geometry gettitlestring graphics graphicx hycolor hyperref iftex ifthen ifvtex infwarerr inputenc intcalc keyval kvdefinekeys kvoptions kvsetkeys l3keys2e ltxcmds mhchem nameref pdfescape pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfrcs pgfsys refcount rerunfilecheck setspace siunitx stringenc tikz todonotes translations trig uniquecounter upgreek url xcolor xkeyval xparse
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Skim
  qf method: LaTeX logfile
```
