### ISSUE TITLE
PDF is opened in default PDF viewer not Skim

### ISSUE THREAD

**Issue by oskargirardin** [lervag/vimtex#3166]
### Description

Hello,

I am on Mac OS and the PDF file of my latex projects are not being opened in the desired program (skim) but the default PDF viewer (Preview). This happens despite setting the required option. Here is my setup function:

```lua
return {
    "lervag/vimtex",
    setup = function()
        vim.g.vimtex_view_method = 'skim'
        vim.g.vimtex_view_general_viewer = 'skim'
        vim.g.vimtex_view_skim_sync = 1
        vim.g.vimtex_view_skim_activate = 1
    end
}
```
My skim version is 1.7.4 and I have the latest vimtex version.

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
VimTeX project: main
  base: main.tex
  root: ...
  tex: ... 
  main parser: current file verified
  document class: acmart
  packages: MnSymbol amsbsy amsfonts amsgen amsmath amsopn amstext array atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook bigintcalc bitset booktabs caption caption3 centernot cleveref color colortbl comment environ epstopdf-base etoolbox everyshi fancyhdr float fontaxes fontenc geometry gettitlestring graphics graphicx hycolor hyperref ifluatex iftex ifthen ifvtex ifxetex infwarerr intcalc keyval kvdefinekeys kvoptions kvsetkeys libertine listing ltxcmds manyfoot microtype mweights nameref natbib nccfoots newtxmath pdfescape pdftexcmds refcount rerunfilecheck rotating subcaption tabularx textcomp totpages trig trimspaces uniquecounter upquote url wasysym xcolor xkeyval xspace xstring zi4
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 5
      output: /var/folders/1w/_0k12dnj7y1gxzk1w4zw8lgr7j8284/T/nvim.<usr>/869J7y/1
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode  -pdf -pvc -pvctimeout- -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'main.tex'
      pid: 70357
  viewer: General
    job: 
      pid: -
      cmd: open '<file-path>/main.pdf'
  qf method: LaTeX logfile
```
