### ISSUE TITLE
Got no auto-suggestions and auto-completions for \documentclass and \usepackage

### ISSUE THREAD

**Issue by shaolun-huang** [lervag/vimtex#3168]
### Description

If I understand the opening of the section of `COMPLETE PACKAGE FILE` from `vimtex.txt` correctly, VimTex should be able to suggest or even complete the latex packages I installed or options for documentclass. When I created a new LaTex file, the only suggestions I got were the snippets.

### Setup
I use `lazy.nvim` to for package managements. Other packages I use VimTex with are `hrsh7th/nvim-cmp` and `micangl/cmp-vimtex`.

* VimTex:
```	
	{
		"lervag/vimtex",
		lazy = false,
		init = function()
			vim.g.vimtex_view_method = "skim" -- showed in the official example
			vim.g.vimtex_compiler_method = "latexmk" -- showd in the official example

			vim.g.vimtex_compiler_latexmk = {
				options = {
					"-xelatex",
				},
			}
			vim.g.vimtex_compiler_latex_engines = {
				_ = "-xelatex",
			}

			vim.g.vimtex_parser_bib_backend = "bibtex"
		end,
	}
```

* nvim-cmp:
```
	{
		"hrsh7th/nvim-cmp",
		dependencies = {
			"saadparwaiz1/cmp_luasnip",
			"hrsh7th/cmp-path",
			-- "micangl/cmp-vimtex", -- I added for vimtex completion
		},
		config = function()
			require("luasnip.loaders.from_vscode").lazy_load()

			local cmp = require("cmp")
			local ls = require("luasnip")
			--- Other configs
                        --- ...

			-- Autocomplete for LaTex
			cmp.setup.filetype({ "tex", "latex" }, {
				sources = {
					{ name = "vimtex" },
					{ name = "buffer" },
				},
			})
		end,
	}
```

### minimal.tex:
```
\documentclass{article}
\usepackage{physics}

\begin{document}
    Tao's book \cite{tao_analysis_2022}

    \bibliographystyle{plain}
    \bibliography{test.bib}
\end{document}
```

### test.bib
```
@book{tao_analysis_2022,
	address = {Singapore},
	author = {Tao, Terence},
	copyright = {https://www.springernature.com/gp/researchers/text-and-data-mining},
	date-added = {2025-05-11 22:54:34 +0800},
	date-modified = {2025-05-11 22:54:34 +0800},
	doi = {10.1007/978-981-19-7261-4},
	isbn = {978-981-19-7261-4},
	language = {en},
	publisher = {Springer Nature Singapore},
	series = {Texts and {Readings} in {Mathematics}},
	title = {Analysis {I}},
	url = {https://link.springer.com/10.1007/978-981-19-7261-4},
	urldate = {2025-03-12},
	volume = {37},
	year = {2022},
	bdsk-url-1 = {https://link.springer.com/10.1007/978-981-19-7261-4},
	bdsk-url-2 = {https://doi.org/10.1007/978-981-19-7261-4}}
```

To reproduce, just type out the contents in `minimal.tex`.

Remark: Even `<C-x><C-o>` does not show any suggestions.

### Expected behavior

* Shows a list of possible values after typing out `\documentclass{` such as `article`, `report` and etc.
* Show a list of packages after typing out `\usepackage{` such as `physics`.
* Show all possible citations from `test.bib` after typing out `\cite{`. In this case, tao_analysis_2022.

### Actual behavior

Got no suggestions.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 15.4.1 (24E263)
  LaTeX version: pdfTeX 3.141592653-2.6-1.40.27 (TeX Live 2025)
  Vim version: NVIM v0.11.1
  Has clientserver: true
  Servername: /var/folders/w7/dksrkkdd18vgm535vvd_xjnh0000gn/T/nvim.simonhuang/yjUazc/nvim.12600.0

VimTeX project: main
  base: main.tex
  root: /Users/simonhuang/documents_local/physics-local/test_latex
  tex: /Users/simonhuang/documents_local/physics-local/test_latex/main.tex
  main parser: current file verified
  document class: article
  packages: amsbsy amsgen amsmath amsopn amstext expl3 physics xparse
  compiler: latexmk
    engine: -pdf
    options:
      -xelatex
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 8
      output: /var/folders/w7/dksrkkdd18vgm535vvd_xjnh0000gn/T/nvim.simonhuang/yjUazc/0
      cmd: max_print_line=2000 latexmk -xelatex  -pdf -pvc -pvctimeout- -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'main.tex'
      pid: 12755
  viewer: Skim
  qf method: LaTeX logfile
```
