### ISSUE TITLE
Conceal symbols get dimmed `Conceal` hl group, not `tex*Concealed*`

### ISSUE THREAD

**Issue by danielwe** [lervag/vimtex#3171]
### Description

Greek letters and other symbols substituted by the conceal functionality get the dimmed `Conceal` highlight group rather than the appropriate `tex*Concealed*` group. This makes equations hard to read and somewhat negates the benefit of the conceal functionality.

### Steps to reproduce

1. `nvim -u minimal.lua minimal.tex`

minimal.lua:
```lua
vim.cmd([[
set nocompatible
let &runtimepath  = '~/.local/share/nvim/lazy/vimtex,' . &runtimepath
let &runtimepath .= ',~/.local/share/nvim/lazy/vimtex'
filetype plugin indent on
syntax enable
set conceallevel=2
]])
```
minimal.tex
```tex
\documentclass{minimal}
\begin{document}
\begin{equation}
  i \hbar \frac{d}{dt} |\psi\rangle = \hat{H} |\psi\rangle
\end{equation}
\end{document}
```

### Expected behavior

Symbols substituted by conceal highlighted in a way that matches other math symbols.

### Actual behavior

Symbols substituted by conceal are dimmed and hard to read, see screenshot:

<img width="363" alt="Image" src="https://github.com/user-attachments/assets/9c767aa3-7efe-44c6-a4b1-95f3e1dd0af6" />

### Do you use a latexmkrc file?

NA

### VimtexInfo

```yaml
System info:
  OS: macOS 15.5 (24F74)
  LaTeX version: pdfTeX 3.141592653-2.6-1.40.27 (TeX Live 2025)
  Vim version: NVIM v0.11.1
  Has clientserver: true
  Servername: /var/folders/57/1z4jgn5133lbbbrnnt4vf_zw0000gn/T/nvim.daniel/FPZeRH/nvim.76408.0
  $PATH:
    - /Library/Apple/usr/bin
    - /Library/TeX/texbin
    - /System/Cryptexes/App/usr/bin
    - /Users/daniel/.cargo/bin
    - /Users/daniel/.juliaup/bin
    - /Users/daniel/.local/bin
    - /Users/daniel/src/ghostty/macos/build/ReleaseLocal/Ghostty.app/Contents/MacOS
    - /bin
    - /opt/X11/bin
    - /opt/homebrew/bin
    - /opt/homebrew/sbin
    - /sbin
    - /usr/bin
    - /usr/local/bin
    - /usr/sbin
    - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
    - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin
    - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin

VimTeX project: minimal
  base: minimal.tex
  root: /Users/daniel
  tex: /Users/daniel/minimal.tex
  main parser: current file verified
  document class: minimal
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
