### ISSUE TITLE
quickfix_ignore_filters not taking effect

### ISSUE THREAD

**Issue by Giessen** [lervag/vimtex#3177]
### Description

The following is my config. 
{
    "lervag/vimtex",
    lazy = false,     -- we don't want to lazy load VimTeX
    init = function()
      -- VimTeX configuration goes here, e.g.
      vim.g.vimtex_view_method = "zathura_simple" 
      vim.g.vimtex_view_general_viewer = 'zathura'
      vim.g.vimtex_callback_progpath = '~/.local/bin/lvim' 
      vim.g.tex_flavor = 'latex'             
      vim.g.vimtex_quickfix_mode = 0          
      vim.g.vimtex_compiler_progname = 'nvr'  

      vim.g.vimtex_quickfix_ignore_filters = {-- not working!!!
       'Package fontspec Warning',
       'Underfull',
       'Overfull'
      }
    end,
  },

After run vimtex compile, I expect the underfull error in the following picture will not show anymore. But It persists.

![Image](https://github.com/user-attachments/assets/d3c7de9e-7130-460b-8858-e5711838f1df)

### Steps to reproduce

1.open test.tex with lunarvim or neovim.
2.run vimtex compile

[test.tex.zip](https://github.com/user-attachments/files/20634878/test.tex.zip)

### Do you use a latexmkrc file?

NO

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 20.04.6 LTS
  Vim version: NVIM v0.11.0-dev-3c803483a
  Has clientserver: true
  Servername: /mnt/wslg/runtime-dir/lvim.15195.0

VimTeX project: New_IEEEtran_how-to
  base: New_IEEEtran_how-to.tex
  root: /home/x/0_wsl2_notes
  tex: /home/x/0_wsl2_notes/New_IEEEtran_how-to.tex
  main parser: current file verified
  document class: IEEEtran
  packages: algorithmic amsfonts amsmath array balance graphicx stfloats subfig textcomp url verbatim
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 6
      output: /tmp/lvim.x/1wPj2c/4
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode  -pdf -pvc -pvctimeout- -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'New_IEEEtran_how-to.tex'
      pid: 16223
  viewer: Zathura
  qf method: LaTeX logfile
```
