### ISSUE TITLE
After setting g:vimtex_format_enabled to true, all marks get deleted when reformatting a paragraph using gqap

### ISSUE THREAD

**Issue by wienen** [lervag/vimtex#3179]
### Description

When doing `gqap` in a latex file, while having `g:vimtex_format_enabled = 1`, marks get deleted. I use the `gqap` a lot when writing paragraphs and I have a shortcut setting a mark at the point where I am invoking the command. I then run the command and get back to the mark by using \`\<mark\>. When `g:vimtex_format_enabled = 1`, I get an error stating that the mark has not been set. If I set `g:vimtex_format_enabled = 0`, everything works as planned.

### Steps to reproduce

1. `$ vim -u minimal.vim minimal.tex`
2. Move to line 5, word 5
3. Set mark: `ms`
4. Format paragraph: `gqap`
5. Return to mark: `s

### Expected behavior

I expect the cursor to be at line 5, word 5. 

### Actual behavior

THe cursor is at the line below the paragraph, and an error is shown stating that the mark is not set.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 15.5 (24F74)
  Vim version: VIM 9.1 (1-1300)
  Has clientserver: false

VimTeX project: minimal
  base: minimal.tex
  root: /Users/hanswienen/Documents/Development/vim
  tex: /Users/hanswienen/Documents/Development/vim/minimal.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Skim
  qf method: LaTeX logfile
```
