### ISSUE TITLE
Loading Bug in Kitty/Foot

### ISSUE THREAD

**Issue by MrJulianBlack** [lervag/vimtex#3183]
### Description

Hi,

I have a quite strange error that i cannot quite pinpoint yet.

When working with a multifile project, e.g. a main file with an `\include{...}` and a side file, I get a bug when first opening neovim. The source of the error is the dialog asking to choose the main file, when opening the side file from the command line.

In a terminal like Konsole, Alacritty, this works as expected. When in Kitty or Foot, the whole terminal is blank instead until the popup menu is dismissed (esc, or pressing a number), only then neovim becomes actually visible.

The bug happens for ui style nvim as well as legacy. It does not happen when neovim is already open and I open the file by `:e side_file.tex`, then I can see the dialog as expected. I can also force the dialog to appear by running `:echo vimtex#init()` after opening the file. It is strictly something about the startup. 

My guess would be the dialog blocking further loading of neovim somehow, also blocking the rendering? Not sure how this relates to different behaviour in different terminals. It will also NOT happen if running everything inside tmux in kitty or foot, in that case i can see the dialog. But I can not force the correct behaviour by setting `$TERM` differently.

I realize this might very well be an issue higher up in the context of how neovim draws the window when detecting different terminals. Your Plugin is just the only case where I noted this problem, so maybe you can point me in a direction.

Thank you for the your plugin and your work!

### Steps to reproduce

This happens when my `init.vim` contains nothing but

Having a multi file project with two possible main files, both including a side file. Then, from shell in terminal, I run `nvim side_file.tex`.

Minimal init.vim:

```vim
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath

call plug#begin()
" Latex support
Plug 'lervag/vimtex'
call plug#end()

```

### Expected behavior

I would expect neovim to open, and the dialog to show up to choose the main file, just like it happens in Konsole and Alacritty.

### Actual behavior

The whole terminal stays blank. Nothing at all is visible. But the program is still responsible, pressing esc will abort the dialog as it should, and then neovim becomes visible.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Arch Linux
  LaTeX version: pdfTeX 3.141592653-2.6-1.40.27 (TeX Live 2026/dev/Arch Linux)
  Vim version: NVIM v0.11.2
  Has clientserver: true
  Servername: /run/user/1000/nvim.134057.0
  $PATH:
    - /home/me/.local/share/gem/ruby/3.4.0/bin
    - /usr/bin
    - /usr/bin/core_perl
    - /usr/bin/site_perl
    - /usr/bin/vendor_perl
    - /usr/lib/jvm/default/bin
    - /usr/local/bin
    - /usr/local/sbin

VimTeX project: exercise18
  base: exercise18.tex
  root: /home/me/exercises
  tex: /home/me/exercises/exercise18.tex
  main parser: fallback current file
  document class: 
  document class options: 
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
  qf method: LaTeX logfile
```
