### ISSUE TITLE
Natbib warning in the wrong file when using \input.

### ISSUE THREAD

**Issue by ludovicschwartz** [lervag/vimtex#3185]
### Description

When jumping to the warning of undefined citation, Vimtex jumps to the main file and not to the file in which the error is happening. 
(VScode works properly for the exact same tex file)

### Steps to reproduce

main.tex :
```
\documentclass{report}
\usepackage{natbib}
\bibliographystyle{plainnat}
\begin{document}
\input{aux.tex}
\bibliography{ref.bib}
\end{document}
```

aux.tex :
`\citet{testcite}`

ref.bib :
``

After running `:VimtexCompile`, the following warning appears 
``main.tex|1 warning| Package natbib Warning: Citation `testcite' on page 1 undefined on input line 1.``

Run `:cnext`

### Expected behavior

The editor jumps to aux.tex on line 1.

### Actual behavior

The editor jumps to main.tex on line 1.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 20.04.3 LTS
  Vim version: NVIM v0.9.5
  Has clientserver: true
  Servername: /run/user/1000/nvim.11396.0

VimTeX project: main
  base: main.tex
  root: 
  tex: 
  main parser: local file
  document class: report
  packages: algorithm algorithmicx algpseudocode amsbsy amsfonts amsgen amsmath amsopn amssymb amstext atbegshi-ltx atveryend-ltx bbm bigintcalc bitset color dsfont epstopdf-base etoolbox float gettitlestring graphics graphicx hycolor hyperref iftex ifthen import infwarerr inputenc intcalc keyval kvdefinekeys kvoptions kvsetkeys ltxcmds nameref natbib pdfescape pdftexcmds preamble refcount rerunfilecheck stringenc subfiles trig uniquecounter url xspace
  source files:
    main.tex
    aux.tex
  compiler: latexmk
    engine: -pdf
    options:
      -pdf
      -pdflatex=lualatex
      -verbose
      -file-line-error
      -synctex=1
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 24
      output: /tmp/nvim.ludovic/1S2dbi/1
      cmd: max_print_line=2000 latexmk -pdf -pdflatex=lualatex -verbose -file-line-error -synctex=1 -pdf -pvc -pvctimeout- -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'main.tex'
      pid: 11936
  viewer: Zathura
    xwin id: 48234499
  qf method: LaTeX logfile
```
