### ISSUE TITLE
zathura inverse search not working

### ISSUE THREAD

**Issue by khumarahn** [lervag/vimtex#3188]
### Description

Hi. This woudn't be the only issue about inverse search with zathura, but it seems different from https://github.com/lervag/vimtex/issues/3172

I made an intermediate script test.sh below which intercepts calls from zathura to vim, and I can see that zathura is indeed sending the commands, but vim does not react.

`.vimrc`:

```vim
set noswapfile

call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex'
call plug#end()

let g:vimtex_view_method = 'zathura_simple'
"let g:vimtex_callback_progpath = '/usr/bin/vim'
let g:vimtex_callback_progpath = '/home/khu/test.sh'

filetype plugin on
filetype indent on
syntax on

set expandtab
set shiftwidth=4
set softtabstop=4

colorscheme industry
au GUIEnter * colorscheme default
```

test.sh:

```sh
echo $@ >> ~/test.log
vim $@ >> ~/test.log 2>&1
```

test.log:
```
...
-T dumb --not-a-term -n -c VimtexInverseSearch 274:-1 '/home/khu/test/./toy.tex'
^L[39m[24;1H"274:-1" [New]
-T dumb --not-a-term -n -c VimtexInverseSearch 372:-1 '/home/khu/test/./toy.tex'
^L[39m[24;1H"372:-1" [New]
```

I can run manually
```sh
vim -T dumb --not-a-term -n -c VimtexInverseSearch 372:-1 '/home/khu/test/./toy.tex'
```
but vim/gvim still do not react.

~/.config/zathura/zathurarc:
```config
set selection-clipboard clipboard
```

This issue is quite strange: I have an identical computer (same system, same packages, same config, only different hardware and kernel), where the inverse search with zathura works. And I experience an an additional potentially related problem: zathura does not invoke the inverse search command on ctrl+right click, like it used to. I have to instead drag-select with ctrl pressed.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Linux 6.15.3-gentoo-dist
  LaTeX version: pdfTeX 3.141592653-2.6-1.40.26 (TeX Live 2024 Gentoo Linux)
  Vim version: VIM 9.1 (1-794)
  Has clientserver: true
  Servername: GVIM1
  $PATH:
    - /etc/eselect/wine/bin
    - /opt/bin
    - /usr/bin
    - /usr/lib/llvm/20/bin
    - /usr/lib64/opencascade/bin
    - /usr/local/bin
    - /usr/local/sbin

VimTeX project: toy
  base: toy.tex
  root: /home/khu/test
  tex: /home/khu/test/toy.tex
  main parser: current file verified
  document class: amsart
  document class options: 12pt=true a4paper=true
  packages: amsbsy amsfonts amsgen amsmath amsopn amssymb amstext atbegshi atbegshi-ltx atveryend atveryend-ltx bigintcalc bitset enumitem epstopdf-base etoolbox fullpage gettitlestring graphics graphicx hycolor hyperref iftex infwarerr inputenc intcalc keyval kvdefinekeys kvoptions kvsetkeys ltxcmds nameref pdfescape pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfplots pgfrcs pgfsys refcount rerunfilecheck stringenc tikz trig uniquecounter url xcolor
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: process 31473 run
      output: /tmp/v3efOnU/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode  -pdf -pvc -pvctimeout- -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'toy.tex'
      pid: 31473
  viewer: Zathura
    cmd_start: zathura  -x "/home/khu/test.sh -T dumb --not-a-term -n -c \"VimtexInverseSearch %{line}:%{column} '%{input}'\"" --synctex-forward 1:1:'/home/khu/test/toy.tex' 'toy.pdf'&
  qf method: LaTeX logfile
```
