### ISSUE TITLE
Continuous Compilation Hang (round 2)

### ISSUE THREAD

**Issue by fuzzybear3965** [lervag/vimtex#736]
I'm having a problem with vimtex on a Windows machine when spaces are in the path. The callback is not triggered successfully (so success/failure is never indicated). None of my settings in my vimrc file affect this. However, I have managed to correct for this problem by modifying `latexmk.vim`.  The change I made to [latexmk.vim](https://github.com/lervag/vimtex/blob/master/autoload/vimtex/latexmk.vim#L816) is below.
```vim
call vimtex#util#set_default('g:vimtex_latexmk_progname',
      \ get(v:, 'progname', get(v:, 'progpath')))
```
"should" become
```vim
call vimtex#util#set_default('g:vimtex_latexmk_progname',
      \ get(v:, 'progpath', get(v:, 'progname')))
```
in order that the callback is able to message gvim. Note that, in my case, performing the above change modifies the default value of `g:vimtex_latexmk_progname` from `C:\Users\John Rinehart\Programs\vim_64\gvim.exe` to `gvim.exe` for me.

This seems related to #297.

**Comment by lervag** [comment]
Hi! I'll look into this later, I'm currently working on a pretty big refactoring (cf. #651), and it will be easier to address this problem after rather than before.

In the meantime, it seems you have a workaround that works. There was a reason I used `progpath` instead of `progname`, but I see now that I should properly escape it.

**Comment by fuzzybear3965** [comment]
No stresses, @lervag. It's good to see you're still hard at work. I want you to know that I've been a vimtex advocate for ~2 years, now. gvim + vimtex is my sole LaTeX IDE (and I do all of my Ph.D. and personal write-ups using LaTeX).

**Comment by lervag** [comment]
Happy to hear that you like vimtex :)

I'm curious, could you not just set the option to solve this issue? There is a reason I use `progpath`, and I don't really want to change the default. It should work. You should be able to just do `set g:vimtex_latexmk_progname = v:progname`.

Another thing you could do that would be helpful: Could you open the compiler output `:VimtexOutput` or `\lo` and see if it says anything related to this for the case where the callback does not work?

**Comment by fuzzybear3965** [comment]
Yeah, I can change the option. That's a good idea.

The issue I'm having is on my work computer. I'm not going into work until tomorrow. I'll try to remember to  check the `:VimtexOutput` tomorrow. Are you hoping to see something like "could not execute callback - bad program name"?

**Comment by lervag** [comment]
Yes, or at least something that might hint at why the callback does not
work.

Den tir. 28. mar. 2017, 22.06 skrev John Rinehart <notifications@github.com

**Comment by lervag** [comment]
There's been a ton of updates the last week. Could you test on the most recent version? I think I have the same problem, and since `gvim` is not in my path on windows, I was not able to get callbacks working. I know too little about windows and the cmd stuff to fix it, though :(

Note the new option: `g:vimtex_compiler_progname`, and also `g:vimtex_compiler_latexmk` for setting `latexmk` related options. See updated docs.

**Comment by fuzzybear3965** [comment]
Hey, @lervag, you've been busy! No problem. I'll make some time to do this tonight/tomorrow. Give me 24 hours.

**Comment by lervag** [comment]
Yes, the last two weeks have been quite heavy on vimtex. I've restructured and refactored quite abit, and I'm currently continuing this. The goal is to support the new jobs api in Vim (and perhaps also neovim), and I also hope this will make it easier to get things working properly on windows.

**Comment by lervag** [comment]
I think things should now have improved. The callbacks should work. The Vim jobs api is enabled, if available. Etc. I don't think you need to change the `g:vimtex_compiler_progname` option any longer, either. Please test, I'd be happy to get some feedback, be it positive or negative. :)

**Comment by fuzzybear3965** [comment]
Okay, 24 hours later I'm back with some information. It still seems that compilation is broken on Windows when the path to vim/gvim has spaces. I'm on commit ddaa9bc6ba5406a5bba9890e49dcd64c877398b7 and below I've included the output from `:VimtexInfo`, `latexmk`, and I've also included the settings I've used to modify vim for use with `vimtex` (my `vimtex.vimrc`).

:VimtexInfo Output
============
```vim
vimtex project: test
  base: test.tex
  root: C:\Users\John Rinehart
  tex: C:\Users\John Rinehart\test.tex
  out: C:\Users\John Rinehart/test.pdf
  log: C:\Users\John Rinehart/test.log
  aux: C:\Users\John Rinehart/test.aux
  compiler: latexmk
    backend: jobs
    output: C:\Users\JOHNRI~1\AppData\Local\Temp\VIAEFF2.tmp
    configuration: 
      continuous: 1
      callback: 1
      latexmk options: 
        -verbose
        -pdf
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
    job: process 7072 dead
    cmd: set max_print_line=2000 & latexmk -verbose -pdf -file-line-error -synctex=1 -interaction=nonstopmode -pvc -e "$pdf_previewer = 'SumatraPDF'" -e "$success_cmd = '""""C:\Users\John Rinehart\Programs\vim_64\gvim.exe"""" --servername GVIM2 --remote-expr \"vimtex\#compiler\#callback\\(1\\)\"'" -e "$failure_cmd = '""""C:\Users\John Rinehart\Programs\vim_64\gvim.exe"""" --servername GVIM2 --remote-expr \"vimtex\#compiler\#callback\\(0\\)\"'" "test.tex"
  viewer: General
  qf: LaTeX logfile
    config: 
      fix_paths: 1
      packages: 
        default: 1
      default: 1
```

latexmkrc (tmp file) output
================
```
Latexmk: Stopping because executing following code from command line
    $success_cmd = '"C:\Users\John
gave an error:
    Can't find string terminator "'" anywhere before EOF at (eval 11) line 1.

C:\texlive\2016\bin\win32\runscript.tlu:679: command failed with exit code 2:
perl.exe c:\texlive\2016\texmf-dist\scripts\latexmk\latexmk.pl -verbose -pdf -file-line-error -synctex=1 -interaction=nonstopmode -pvc -e "$pdf_previewer = 'SumatraPDF'" -e "$success_cmd = '""""C:\Users\John Rinehart\Programs\vim_64\gvim.exe"""" --servername GVIM2 --remote-expr \"vimtex\#compiler\#callback\\(1\\)\"'" -e "$failure_cmd = '""""C:\Users\John Rinehart\Programs\vim_64\gvim.exe"""" --servername GVIM2 --remote-expr \"vimtex\#compiler\#callback\\(0\\)\"'" "test.tex"
```

vimtex.vimrc
========
```vim
nmap <F9> <plug>(vimtex-compile)
if has("win32")
   let g:vimtex_view_general_viewer = 'SumatraPDF'
"   let g:vimtex_latexmk_progname='gvim'
elseif has("unix")
   let g:vimtex_view_general_viewer = 'mupdf'
   "let g:vimtex_latexmk_progname='vim'
endif
```

**Comment by lervag** [comment]
How strange. This works for me with similar options on Windows. My path to gvim is `C:\Program Files (x86)\Vim\Vim80\gvim.exe`, which does contain spaces.

Could you try to set `g:vimtex_view_automatic = 0`? I dont expect it to make a difference, but as far as I can see it is the only thing that is different...

I'm on Windows 10. I don't know what makes a difference on Windows systems. :\

Just to make sure: If you do `let g:vimtex_compiler_progname = 'gvim'`, things work as expected?

**Comment by fuzzybear3965** [comment]
Putting `let g:vimtex_view_automatic = 0` in my `vimtex.vimrc` file and resourcing it doesn't fix the callback.

However, placing `let g:vimtex_compiler_progname = 'gvim'` in my `vimtex.vimrc` *does* manage to fix the problem caused by the space in the path. However, I get a pop-up in `gvim` claiming `E449: Invalid expression received: Send expression failed.` The tmp file output and the `:VimtexInfo` output are supplied below.

tmp file output
==========
```
Latexmk: All targets (test.pdf) are up-to-date
2017, version: 4.52c.
Not using a previewer
------------
Running '"gvim" --servername GVIM --remote-expr "vimtex\#compiler\#callback\(1\)"'
------------
```
:VimtexInfo output
============
```
vimtex project: test
  base: test.tex
  root: C:\Users\John Rinehart
  tex: C:\Users\John Rinehart\test.tex
  out: C:\Users\John Rinehart/test.pdf
  log: C:\Users\John Rinehart/test.log
  aux: C:\Users\John Rinehart/test.aux
  compiler: latexmk
    backend: jobs
    output: C:\Users\JOHNRI~1\AppData\Local\Temp\VIA87F2.tmp
    configuration: 
      continuous: 1
      callback: 1
      latexmk options: 
        -verbose
        -pdf
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
    job: process 11524 run
    cmd: set max_print_line=2000 & latexmk -verbose -pdf -file-line-error -synctex=1 -interaction=nonstopmode -pvc -view=none -e "$success_cmd = '""""gvim"""" --servername GVIM --remote-expr \"vimtex\#compiler\#callback\\(1\\)\"'" -e "$failure_cmd = '""""gvim"""" --servername GVIM --remote-expr \"vimtex\#compiler\#callback\\(0\\)\"'" "test.tex"
  viewer: General
  qf: LaTeX logfile
    config: 
      fix_paths: 1
      packages: 
        default: 1
      default: 1
```

**Comment by lervag** [comment]
Does the error contain more information than that? If so, could you paste the entire message here? Note that you can see old messages with `:messages`. I think we should solve that problem.

Btw, could you try this:

```vim
let g:vimtex_compiler_latexmk = {
      \ 'backend' : 'process',
      \}
```

I.e., use the "old" backend instead of the new. Perhaps we get more understandable error messages, or perhaps it even works..?

**Comment by fuzzybear3965** [comment]
I'm not sure which error you are asking about. There is the gvim pop-up error message regarding the send expression and the error message generated by latex regarding the string terminator. But, I included the full text of both error messages. So, there is no more information for either message.

Including 
```
let g:vimtex_compiler_latexmk = {
      \ 'backend' : 'process',
      \}
```
in my `vimtex.vimrc` does not change the behavior of vimtex with regards to [my most recent comment](https://github.com/lervag/vimtex/issues/736#issuecomment-293067999).

**Comment by lervag** [comment]
I meant the pop-up message, but it doesn't matter if there was no more info.

But ok, I checked the error message, and I understand: The problem is that I've added `\\` infront of the parantheses for the callback function on windows. I needed this for things to work on my end on Windows, and so I thought this was a general windows thing. apparently not. :(

So, what to do..??? Things will work for you with no error if you have the `progname` set and if you remove the `\\`s in the code (see line 175 in `compiler/latexmk.vim`). But I need to understand exactly when we need those slashes.

So: What's your `latexmk` version?

Could you test with the same test that I use? I've just pushed an example as you should see above in the thread. At `VIMTEX/test/issues/736`. If you open a terminal/cmd window/whatever, and write `gvim -u minivimrc`, it should automatically start compilation.

**Comment by fuzzybear3965** [comment]
I have two Windows machines at my disposal: one is proving troublesome with vimtex and the other is functional. The troublesome one is my work machine (PC). The functional one is my laptop. Both use Windows 10 and similar OS configuration and installed software.

I ran some tests using the same `vimtex.vimrc` file on both machines (all of my vim settings are network-synchronized between them). Below I document some of that work. There are four use cases that I studied before I tried your recommendation at the end of the last message (at the bottom of this message). I only adjusted two things: 1) `let g:vimtex_compiler_progname` and 2) the double slashes in the callback. I describe those test conditions below.

| Test Number | `g:vimtex_compiler_progname`  | Double Slashes |
| -------------- | ------------- | ------------- |
| 1 (desired) | unset (set by vimtex automatically)  | Present  |
| 2 (least invasive) | `gvim.exe`  | Present |
| 3 | unset (set by vimtex automatically)  | Removed  |
| 4 (most invasive) | `gvim.exe`  | Removed  |

Again, each test was run on each machine. The results are described below.

Test 1
====
_vimtex.vimrc_
```vim
nmap <F9> <plug>(vimtex-compile)
if has("win32")
   let g:vimtex_view_general_viewer = 'SumatraPDF'
endif
```
_line 175(ish)_
```vim
          let l:func = l:cb . ' --remote-expr '
                \ . (has('win32')
                \   ? '\"vimtex\#compiler\#callback\\(' . l:val . '\\)\"'
                \   : '\"vimtex\#compiler\#callback(' . l:val . ')\"')
```
#### Work machine results
_latexmk temporary file output_
```vim
Latexmk: Stopping because executing following code from command line
    $success_cmd = '"C:\Users\John
gave an error:
    Can't find string terminator "'" anywhere before EOF at (eval 11) line 1.
C:\texlive\2016\bin\win32\runscript.tlu:679: command failed with exit code 2:
perl.exe c:\texlive\2016\texmf-dist\scripts\latexmk\latexmk.pl -verbose -pdf -file-line-error -synctex=1 -interaction=nonstopmode -pvc -e "$pdf_previewer = 'SumatraPDF'" -e "$success_cmd = '""""C:\Users\John Rinehart\Programs\vim_64\gvim.exe"""" --servername GVIM --remote-expr \"vimtex\#compiler\#callback\\(1\\)\"'" -e "$failure_cmd = '""""C:\Users\John Rinehart\Programs\vim_64\gvim.exe"""" --servername GVIM --remote-expr \"vimtex\#compiler\#callback\\(0\\)\"'" "test.tex"
```
_:VimtexInfo output_
```
vimtex project: test
  base: test.tex
  root: C:\Users\John Rinehart
  tex: C:\Users\John Rinehart\test.tex
  out: C:\Users\John Rinehart/test.pdf
  log: C:\Users\John Rinehart/test.log
  aux: C:\Users\John Rinehart/test.aux
  compiler: latexmk
    backend: jobs
    output: C:\Users\JOHNRI~1\AppData\Local\Temp\VIA8CA4.tmp
    configuration:
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -pdf
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
    job: process 9644 dead
    cmd: set max_print_line=2000 & latexmk -verbose -pdf -file-line-error -synctex=1 -interaction=nonstopmode -pvc -e "$pdf_previewer = 'SumatraPDF'" -e "$success_cmd = '""""C:\Users\John Rinehart\Programs\vim_64\gvim.exe"""" --servername GVIM --remote-expr \"vimtex\#compiler\#callback\\(1\\)\"'" -e "$failure_cmd = '""""C:\Users\John Rinehart\Programs\vim_64\gvim.exe"""" --servername GVIM --remote-expr \"vimtex\#compiler\#callback\\(0\\)\"'" "test.tex"
  viewer: General
  qf: LaTeX logfile
    config:
      fix_paths: 1
      packages:
        default: 1
      default: 1
```
latexmk starts and quickly exits without producing any output (neither log files nor PDF).
PDF viewer does not open automatically.

#### Laptop results
Test 1
====
_vimtex.vimrc_
```vim

```
_line 175(ish)_
```vim

```
#### Work machine results
_latexmk temporary file output_

_:VimtexInfo output_
#### Laptop results
_latexmk temporary file output_

_:VimtexInfo output_

**Comment by fuzzybear3965** [comment]
Test 1
====
_vimtex.vimrc_
```vim
nmap <F9> <plug>(vimtex-compile)
if has("win32")
   let g:vimtex_view_general_viewer = 'SumatraPDF'
endif
```
_line 175(ish)_
```vim
          let l:func = l:cb . ' --remote-expr '
                \ . (has('win32')
                \   ? '\"vimtex\#compiler\#callback\\(' . l:val . '\\)\"'
                \   : '\"vimtex\#compiler\#callback(' . l:val . ')\"')
```
#### Work machine results
_latexmk temporary file output_
```vim
Latexmk: Stopping because executing following code from command line
    $success_cmd = '"C:\Users\John
gave an error:
    Can't find string terminator "'" anywhere before EOF at (eval 11) line 1.
C:\texlive\2016\bin\win32\runscript.tlu:679: command failed with exit code 2:
perl.exe c:\texlive\2016\texmf-dist\scripts\latexmk\latexmk.pl -verbose -pdf -file-line-error -synctex=1 -interaction=nonstopmode -pvc -e "$pdf_previewer = 'SumatraPDF'" -e "$success_cmd = '""""C:\Users\John Rinehart\Programs\vim_64\gvim.exe"""" --servername GVIM --remote-expr \"vimtex\#compiler\#callback\\(1\\)\"'" -e "$failure_cmd = '""""C:\Users\John Rinehart\Programs\vim_64\gvim.exe"""" --servername GVIM --remote-expr \"vimtex\#compiler\#callback\\(0\\)\"'" "test.tex"
```
_:VimtexInfo output_
```
vimtex project: test
  base: test.tex
  root: C:\Users\John Rinehart
  tex: C:\Users\John Rinehart\test.tex
  out: C:\Users\John Rinehart/test.pdf
  log: C:\Users\John Rinehart/test.log
  aux: C:\Users\John Rinehart/test.aux
  compiler: latexmk
    backend: jobs
    output: C:\Users\JOHNRI~1\AppData\Local\Temp\VIA8CA4.tmp
    configuration:
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -pdf
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
    job: process 9644 dead
    cmd: set max_print_line=2000 & latexmk -verbose -pdf -file-line-error -synctex=1 -interaction=nonstopmode -pvc -e "$pdf_previewer = 'SumatraPDF'" -e "$success_cmd = '""""C:\Users\John Rinehart\Programs\vim_64\gvim.exe"""" --servername GVIM --remote-expr \"vimtex\#compiler\#callback\\(1\\)\"'" -e "$failure_cmd = '""""C:\Users\John Rinehart\Programs\vim_64\gvim.exe"""" --servername GVIM --remote-expr \"vimtex\#compiler\#callback\\(0\\)\"'" "test.tex"
  viewer: General
  qf: LaTeX logfile
    config:
      fix_paths: 1
      packages:
        default: 1
      default: 1
```
latexmk starts and quickly exits without producing any output (neither log files nor PDF).
PDF viewer does not open automatically.

#### Laptop results
_latexmk temporary file output_
```
Latexmk: Stopping because executing following code from command line
    $success_cmd = '"gvim
gave an error:
    Can't find string terminator "'" anywhere before EOF at (eval 13) line 1.
```
_:VimtexInfo output_
```
vimtex project: test
  base: test.tex
  root: C:\Users\JohnRinehart
  tex: C:\Users\JohnRinehart\test.tex
  out: C:\Users\JohnRinehart/test.pdf
  log:
  aux:
  compiler: latexmk
    backend: jobs
    output: C:\Users\JOHNRI~2\AppData\Local\Temp\VIADDD3.tmp
    configuration:
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -pdf
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
    job: process 5748 dead
    cmd: set max_print_line=2000 & latexmk -verbose -pdf -file-line-error -synctex=1 -interaction=nonstopmode -pvc -e "$pdf_previewer = 'SumatraPDF'" -e "$success_cmd = '""""gvim"""" --servername GVIM2 --remote-expr \"vimtex\#compiler\#callback\\(1\\)\"'" -e "$failure_cmd = '""""gvim"""" --servername GVIM2 --remote-expr \"vimtex\#compiler\#callback\\(0\\)\"'" "test.tex"
  viewer: General
  qf: LaTeX logfile
    config:
      fix_paths: 1
      packages:
        default: 1
      default: 1
```
latexmk starts and quickly exits without producing any output (neither log files nor PDF).
PDF viewer does not open automatically.

**Comment by fuzzybear3965** [comment]
Test 2
====
_vimtex.vimrc_
```vim
nmap <F9> <plug>(vimtex-compile)
if has("win32")
   let g:vimtex_view_general_viewer = 'SumatraPDF'
   let g:vimtex_compiler_progname = 'gvim'
endif
```
_line 175(ish)_
```vim
          let l:func = l:cb . ' --remote-expr '
                \ . (has('win32')
                \   ? '\"vimtex\#compiler\#callback\\(' . l:val . '\\)\"'
                \   : '\"vimtex\#compiler\#callback(' . l:val . ')\"')
```
#### Work machine results
_latexmk temporary file output_
```
Latexmk: applying rule 'pdflatex'...
This is pdfTeX, Version 3.14159265-2.6-1.40.17 (TeX Live 2016/W32TeX) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./test.tex
LaTeX2e <2017/01/01> patch level 3
Babel <3.9r> and hyphenation patterns for 83 language(s) loaded.
(c:/texlive/2016/texmf-dist/tex/latex/base/minimal.cls
Document Class: minimal 2001/05/25 Standard LaTeX minimal class
) (./tesLatexmk: Log file says output to 'test.pdf'
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'test.aux'
------------
Run number 2 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -file-line-error -synctex==== TeX engine is 'pdfTeX'
Latexmk: applying rule 'pdflatex'...
Latexmk: Log file says output to 'test.pdf'
Latexmk: I have not found a previewer that is already running. 
   So I will start it for 'test.pdf'
------------
------------
Running 'start SumatraPDF  "test.pdf"'
------------
------------
Running '"gvim" --servername GVIM --remote-expr "vimtex\#compiler\#callback\(1\)"'
------------
minimal 2001/05/25 Standard LaTeX minimal class
) (./test.aux) [1{c:/texlive/2016/texmf-var/fonts/map/pdftex/updmap/pdftex.map}] (./test.aux) )<c:/texlive/2016/texmf-dist/fonts/type1/public/amsfonts/cm/cmr10.pfb>
Output written on test.pdf (1 page, 9468 bytes).
SyncTeX written on test.synctex.gz.
Transcript written on test.log.
=== TeX engine is 'pdfTeX'
Latexmk: All targets (test.pdf) are up-to-date
For rule 'view', running '&if_source(  )' ...
```

_:VimtexInfo output_
```
vimtex project: test
  base: test.tex
  root: C:\Users\John Rinehart
  tex: C:\Users\John Rinehart\test.tex
  out: C:\Users\John Rinehart/test.pdf
  log: C:\Users\John Rinehart/test.log
  aux: C:\Users\John Rinehart/test.aux
  compiler: latexmk
    backend: jobs
    output: C:\Users\JOHNRI~1\AppData\Local\Temp\VIABDF1.tmp
    configuration:
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -pdf
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
    job: process 10372 run
    cmd: set max_print_line=2000 & latexmk -verbose -pdf -file-line-error -synctex=1 -interaction=nonstopmode -pvc -e "$pdf_previewer = 'SumatraPDF'" -e "$success_cmd = '""""gvim"""" --servername GVIM --remote-expr \"vimtex\#compiler\#callback\\(1\\)\"'" -e "$failure_cmd = '""""gvim"""" --servername GVIM --remote-expr \"vimtex\#compiler\#callback\\(0\\)\"'" "test.tex"
  viewer: General
  qf: LaTeX logfile
    config:
      fix_paths: 1
      packages:
        default: 1
      default: 1
```
latexmk works great and all auxiliary/log/PDF files are generated.
Error window pops up complaining about invalid send expression.

#### Laptop results
_latexmk temporary file output_
```
Latexmk: Stopping because executing following code from command line
    $success_cmd = '"C:\Users\John
gave an error:
    Can't find string terminator "'" anywhere before EOF at (eval 11) line 1.

C:\texlive\2016\bin\win32\runscript.tlu:679: command failed with exit code 2:
perl.exe c:\texlive\2016\texmf-dist\scripts\latexmk\latexmk.pl -verbose -pdf -file-line-error -synctex=1 -interaction=nonstopmode -pvc -e "$pdf_previewer = 'SumatraPDF'" -e "$success_cmd = '""""C:\Users\John Rinehart\Programs\vim_64\gvim.exe"""" --servername GVIM --remote-expr \"vimtex\#compiler\#callback(1)\"'" -e "$failure_cmd = '""""C:\Users\John Rinehart\Programs\vim_64\gvim.exe"""" --servername GVIM --remote-expr \"vimtex\#compiler\#callback(0)\"'" "test.tex"
```
_:VimtexInfo output_
```
vimtex project: test
  base: test.tex
  root: C:\Users\John Rinehart
  tex: C:\Users\John Rinehart\test.tex
  out: C:\Users\John Rinehart/test.pdf
  log: C:\Users\John Rinehart/test.log
  aux: C:\Users\John Rinehart/test.aux
  compiler: latexmk
    backend: jobs
    output: C:\Users\JOHNRI~1\AppData\Local\Temp\VIABB16.tmp
    configuration:
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -pdf
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
    job: process 9012 dead
    cmd: set max_print_line=2000 & latexmk -verbose -pdf -file-line-error -synctex=1 -interaction=nonstopmode -pvc -e "$pdf_previewer = 'SumatraPDF'" -e "$success_cmd = '""""C:\Users\John Rinehart\Programs\vim_64\gvim.exe"""" --servername GVIM --remote-expr \"vimtex\#compiler\#callback(1)\"'" -e "$failure_cmd = '""""C:\Users\John Rinehart\Programs\vim_64\gvim.exe"""" --servername GVIM --remote-expr \"vimtex\#compiler\#callback(0)\"'" "test.tex"
  viewer: General
  qf: LaTeX logfile
    config:
      fix_paths: 1
      packages:
        default: 1
      default: 1
```
