### ISSUE TITLE
No compiler feedback in nvim

### ISSUE THREAD

**Issue by rthrmt** [lervag/vimtex#767]
I don't get any compilation feedback in neovim anymore. It did work before. It does compile correctly (creates a pdf, etc.).

Here is a minimal vimrc file:
```vim
call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex', { 'for': ['tex', 'latex'] }
call plug#end()

filetype plugin indent on
syntax enable

let g:vimtex_compiler_progname = "/usr/bin/nvr"
```

Edit: @lervag updated formatting and removed some unimportant comments from vimrc sample.

**Comment by lervag** [comment]
Hi. Sorry, I am currently implementing support for neovim's `jobstart` and `job-control` interface. It worked for me, so I thought it would work for others, and so I updated the default backend to `nvim` if possible, see `:h g:vimtex_compiler_latexmk` and read about the `backend` key.

Could you report the output of `VimtexInfo` / `\li` after you have started compilation. Also, could you inspect the `latexmk` output through `VimtexOutput` / `\lo`, there might be some helpful info.

**Comment by lervag** [comment]
I'm closing this since I can't reproduce it. However, feel free to reopen if you can provide more details that will make it possible for me to reproduce.

**Comment by rthrmt** [comment]
Here is the output of VimtexInfo, I changed the filenames due to privacy.

```
vimtex project: dummy_project
  base: dummy.tex
  root: /home/user/Project/
  tex: /home/user/Project/dummy.tex
  out: /home/user/Project/dummy.pdf
  log: /home/user/Project/dummy.log
  aux: /home/user/Project/dummy.aux
  packages: 
    tikz: 1
  compiler: latexmk
    backend: nvim
    output: /tmp/nvim3bUIL5/1
    configuration: 
      continuous: 1
      callback: 1
      latexmk options: 
        -verbose
        -pdf
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
    pid: 4004
    cmd: max_print_line=2000 latexmk -verbose -pdf -file-line-error -synctex=1 -interaction=nonstopmode -pvc -e '$pdf_previewer = "okular --unique"' -e '$success_cmd = "'""/usr/bin/nvr""' --servername /tmp/nvim3bUIL5/0 --remote-expr \"vimtex\#compiler\#callback(1)\""' -e '$failure_cmd = "'""/usr/bin/nvr""' --servername /tmp/nvim3bUIL5/0 --remote-expr \"vimtex\#compiler\#callback(0)\""' 'dummy.tex'
  viewer: General
  qf: LaTeX logfile
    config: 
      fix_paths: 1
      packages: 
        default: 1
      default: 1

```

When I try to issue :VimtexOutput nvim complains that there is no such command.
