### ISSUE TITLE
Cannot open pdf with viewer

### ISSUE THREAD

**Issue by ranebrown** [lervag/vimtex#774]
### Explain the issue

I am attempting to use Texworks as a pdf viewer on windows. Somehow the path is not being creating correctly. When using the `VimtexView` command Texworks attempts to open the pdf but the path is shown as "C:    ex/minimal.pdf" when it should be "C:\tex\minimal.pdf"

### Minimal working example

```tex
\documentclass{minimal}
\begin{document}

Hello World!

\end{document}
```

### Minimal vimrc file

```vim
set nocompatible
let &rtp = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable

let g:vimtex_view_method = 'general'
let g:vimtex_view_general_viewer = 'texworks.exe'
let g:vimtex_compiler_latexmk = {
    \ 'callback' : 0,
    \ 'continuous' : 0,
    \}
```

**Comment by lervag** [comment]
I edited your minimal vimrc file: You don't need to specify settings that are already defaults.

Could you provide the output of `:VimtexInfo` after you have tried to open the viewer?

**Comment by Clyde-fare** [comment]
Vimtex is also breaking for me on windows 10 and GVIM 8. Both compiling and viewing pdfs fail as the path to the compiler and to the pdf is wrong. On attempting to view the pdf I get the following error in SumatraPDF:  

    error loading C:\UsersClyde\Dropbox\Project Stuff\Thesis\oniom_pah\SERSCLYDETEMP\ONIOM_PAH\ONIOM_PAH2SKEL.PDF

Where as the correct path that was previously getting loaded fine is 

    C:\Users\Clyde\Temp\oniom_pah\oniom_pah2_skel.pdf

I can see that commit f98e904aa8617b6128ca9553a92a2e2783774278 introduced the bug because I have no problem with the code prior to this commit.

**Comment by lervag** [comment]
I am not convinced that your problem is the same, @Clyde-fare. Could you please open a new issue and provide a minimal vimrc file (and example) that reproduces your issue?

**Comment by ranebrown** [comment]
```
vimtex project: minimal
    base: minimal.tex
    root: C:\tex
    tex: C:\tex\minimal.tex
    out: C:\tex/minimal.pdf
    log: C:\tex/minimal.log
    aux: C:\tex/minimal.aux
    compiler: latexmk
        backend: jobs
        output: C:\Users\e343641\AppData\Local\Temp\1\VIAA280.tmp
        configuration:
            continuous: 0
            callback: 0
            latexmk options:
                -verbose
                -pdf
                -file-line-error
                -synctex=1
                -interaction=nonstopmode
    viewer: General
    process:
        pid: -
        cmd: start /b "cmd /s /c "texworks.exe "C:             ex/minimal.pdf" >nul""
    qf: LaTex logfile
        config:
            fix_paths: 1
            packages:
                default: 1
            default: 1
```
