### ISSUE TITLE
Cannot output any files (pdf, aux, fdb_latexmk, fls, log)

### ISSUE THREAD

**Issue by gilgameshskytrooper** [lervag/vimtex#780]
### Explain the issue

Currently running the most recent version of vimtex on neovim. Installed Neovim via Mac Homebrew and vimtex via Plug.

I use the following `.vimrc` file (`~/.config/nvim/init.vim` for neovim):

```vim
call plug#begin('~/.local/share/nvim/plugged')
Plug 'lervag/vimtex'
Plug 'mhinz/vim-startify'
Plug 'https://github.com/vim-airline/vim-airline'
Plug 'octol/vim-cpp-enhanced-highlight'
Plug 'benmills/vimux'
Plug 'rizzatti/dash.vim'
Plug 'https://github.com/morhetz/gruvbox' 
Plug 'Valloric/YouCompleteMe'
call plug#end()

"Path/Environment Stuff
let $PATH .= ':/usr/local/bin'

"Theming
set termguicolors
let $NVIM_TUI_ENABLE_TRUE_COLOR=1
set background=dark
let g:gruvbox_contrast_dark="soft"
let g:gruvbox_contrast_light="soft"
let g:gruvbox_bold=1
let g:gruvbox_italic=1
colorscheme gruvbox
if has('gui_running')
	guifont="FantasqueSansMono-Regular:12
endif

let g:airline_theme="gruvbox" "use gruvbox for airline as well
let g:airline_powerline_fonts = 1 "get powerline fonts
let g:airline#extensions#tabline#enabled = 1 "turn on the top of airline
let g:airline#extensions#tabline#fnamemod = '#t' "set the top tabline to show you buffer (tab) name

"Key Remapping
inoremap jk <ESC>
inoremap kj <ESC>
map <C-J> :bprev<CR>
map <C-K> :bnext<CR>
nnoremap qq :w\|bd<cr>
let mapleader = "\<Space>"
nmap <leader>T :enew<cr>

"VimTex Settings
let g:vimtex_latexmk_options = '-pdf -pdflatex="pdflatex --shell-escape %O %S" -verbose -file-line-error -synctex=1 -interaction=nonstopmode'
let &rtp = '~/.local/share/nvim/plugged/vimtex,' . &rtp
let &rtp .= ',~/.local/share/nvim/plugged/vimtex,'
let g:vimtex_view_method = 'skim'

"Vim Formatting
set hidden
filetype plugin indent on
syntax on
set number
set encoding=utf-8

"YouCompleteMe Code Hinting
let g:ycm_server_python_interpreter = '/usr/local/bin/python3'
let g:ycm_enable_diagnostic_highlighting = 1
let g:ycm_always_populate_loc_list = 1
let g:ycm_open_loclist_on_ycm_diags = 1
let g:ycm_global_ycm_extra_conf = '/Users/andrewlee/.config/nvim/default_ycm.py'`
```

### Minimal working example

A minimal working LaTeX example:

```tex
\documentclass{minimal}
\begin{document}

Hello world!

\end{document}
```

`\ll` yields `compiler: started continuous mode`. No further output, no output files generated.

The output from `\lo` is:

```
sh: and: command not found
sh: and: command not found
sh: and: command not found
sh: and: command not found
```

The output from `\li` is:

```
vimtex project: test
    base test.tex
    root: /Users/.../
    tex: /Users/.../test.tex
    out: /Users/.../test.pdf
    log: /Users/.../test.log
    aux: /Users/.../test.aux
    compiler: latexmk
        backend: nvim
        output: /var/folders/4v/jn67z09......../nvimKixnRJ/2
       configurations:
           continous: 1
           callback: 1
           latexmk option:
               -verbose
               -pdf
               -file-line-error
               -syntex=1
               -interaction=nonstopmode
           pid: 0
           cmd: set max_print_line 2000; and latexmk -verbose -pdf -file-line-error -syntex=1 -interaction=nonstopmode -pvc -e '$pdf_previewer = "/Applications/Skim.app/Contents/SharedSupport/displayline"' -e '$success_cmd = "'"'/usr/local/bin/nvim'"' --servername /var/folders/4v/jn67z0956rz.../T/nvimKixnRJ/0 --remote-expr \"vimtex\#cimpiler\#callback(1)\""' -e '$failure_cmd = "'"'/usr/local/bin/nvim'"' --servername /var/folders/4v/jn...../T/nvimKixnRJ/0 --remote-expr \"vimtex\#compiler\#callback(0)\""' 'test.tex'
    view: Skim
    qf: LaTeX logfile
        config:
            fix_path:1
            packages:
                default: 1
            default:1
```

More specifically, I am using this in OSX, and my shell is fish. `:echo $SHELL` gives `/usr/local/bin/fish`.

Furthermore, doing a manual `latexmk -pdf test.tex` produces the correct files.

Thanks

----

Update by @lervag: I've cleaned up the post and removed unneeded information.
