### ISSUE TITLE
Failing to Compile Images

### ISSUE THREAD

**Issue by JasonB579** [lervag/vimtex#792]
### Explain the issue

I'm using neovim and just switched to using vimtex and I really like it, but I'm running into an issue with images that I try to put into the LaTeX. If there is no filetype attached to the image I get the error:

> ./exampleTEX.tex:6: LaTeX Error: File `calvin_and_hobbes_wallpaper' not found.

If there is a filetype I get the error:

> ./exampleTEX.tex:6: LaTeX Error: Cannot determine size of graphic in calvin_and_hobbes_wallpaper.png (no BoundingBox).

I gave my init.vim file (neovim's  version of .vimrc) as well as my latex to a friend who also uses neovim and vimtex and there was no issue compiling for him, so I'm assuming there's an issue with having some package installed that I'm not aware of or something. Any help would be appreciated!

### Minimal working example

For reference, `calvin_and_hobbes_wallpaper.png` is a `png` file in the same folder with as the `tex` file.

```tex
\documentclass{article}                                                                               
\usepackage{graphicx}                                                                                 
                                                                                                      
\begin{document}                                                                                      
                                                                                                      
  \includegraphics{calvin_and_hobbes_wallpaper.png}                                                   
                                                                                                      
\end{document}        
```

### Minimal vimrc file

My `init.vim` file is in `~/.config/nvim/`

```vim
set nocompatible
filetype off
set rtp+=~/.config/nvim/bundle/Vundle.vim                                                             
call vundle#begin('~/.config/nvim/bundle')                                                            
Plugin 'VundleVim/Vundle.vim'                                                                         
Plugin 'lervag/vimtex'                                                                                
call vundle#end()
filetype plugin indent on

let g:vimtex_latexmk_progname='~/.local/bin/nvr'
```

### latexmkrc file

This is my `.latexmkrc` file. It's currently in my home directory.

```
$pdflatex = 'pdflatex --shell-escape -synctex=1 %O %S'; 
```

**Comment by JasonB579** [comment]
One thing I forgot to mention is that it won't compile with vimtex, but if I directly run pdflatex it compiles without any issue.

**Comment by JasonB579** [comment]
A BIT MORE INFO:

So I've been continually playing with this trying to find the issue, and I have a bit more info that might help diagnose this.

The output of :VimtexInfo is:
```
vimtex project: Blocklove_2                                                                                                                                     
  base: Blocklove_2.tex                                                                                                                                         
  root: /home/jason/Documents/Electronics_1/Exercise_2                                                                                                          
  tex: /home/jason/Documents/Electronics_1/Exercise_2/Blocklove_2.tex                                                                                           
  out: /home/jason/Documents/Electronics_1/Exercise_2/Blocklove_2.pdf                                                                                           
  log: /home/jason/Documents/Electronics_1/Exercise_2/Blocklove_2.log                                                                                           
  aux: /home/jason/Documents/Electronics_1/Exercise_2/Blocklove_2.aux                                                                                           
  compiler: latexmk                                                                                                                                             
    backend: nvim                                                                                                                                               
    output: /tmp/nvimITE8L9/1                                                                                                                                   
    configuration:                                                                                                                                              
      continuous: 1                                                                                                                                             
      callback: 1                                                                                                                                               
      latexmk options:                                                                                                                                          
        -verbose                                                                                                                                                
        -pdf                                                                                                                                                    
        -file-line-error                                                                                                                                        
        -synctex=1                                                                                                                                              
        -interaction=nonstopmode                                                                                                                                
  viewer: General                                                                                                                                               
  qf: LaTeX logfile                                                                                                                                             
    config:                                                                                                                                                     
      fix_paths: 1                                                                                                                                              
      packages:                                                                                                                                                 
        default: 1                                                                                                                                              
      default: 1
```

Also if I run the command `latexmk -verbose -pdf -file-line-error -synctex=1 -interaction=nonstopmode Blocklove_2.tex` it fully compiles. It still gets the error during the first run, but it ends up making it through several runs and the resulting pdf has all of the images.

**Comment by lervag** [comment]
First: I've edited your first post and e.g. removed unnecessary comments in the `init.vim` file. While reading your `init.vim`, I noticed that you are using an old option: `g:vimtex_latexmk_progname`. Change that to `g:vimtex_compiler_progname`.

So, it seems to me that you have two separate issues. The first you mention is a LaTeX related issue, not a vimtex related issue. When you compile the figure, you either have "missing figure", or "missing bounding box". The latter implies that the LaTeX code is correct, but that there is something "wrong" with the image. Could you try to compile with a different image, same syntax?

Next, the vimtex related issue: You can't compile from vimtex. To understand this, I need some more info. Could you do the following:

1. Open the minimal LaTeX example, but comment out the `\includegraphics` and instead type "Hello world" (or similar). Use the minimal `init.vim` file with the updated option (see above). E.g. `nvim -u init.vim`.
2. Now start compilation with `\ll` (or `:VimtexCompile`).
3. It should start to compile. Copy the output from `\li` (`:VimtexInfo`) and `\lo` (`:VimtexCompileOutput`) here. The latter is the output from the `latexmk` program, and often contains valuable info when things don't work.

**Comment by JasonB579** [comment]
As far as the LaTeX related issue goes with those errors, I don't actually think it is a LaTeX issue. I'm perfectly able to compile it without errors with other things. I was using the LaTeX-Suite for Vim before I switched to vimtex and it compiled with no issues. If I separately use pdflatex to compile it it works perfectly fine. It also happens with any image in this situation. I don't know if there is a problem with the LaTeX that the other compilers are not recognizing, but it has not previously been an issue...I will keep looking into that issue, though, as it seems to be an issue when exporting as a .dvi rather than a .pdf.

Output from `\li` when run with just Hello World instead of the `\includegraphics` line:
```
vimtex project: exampleTEX
  base: exampleTEX.tex
  root: /home/jason/Documents/latex_fail_example
  tex: /home/jason/Documents/latex_fail_example/exampleTEX.tex
  out: 
  log: /home/jason/Documents/latex_fail_example/exampleTEX.log
  aux: /home/jason/Documents/latex_fail_example/exampleTEX.aux
  compiler: latexmk
    backend: nvim
    output: /tmp/nvim5SFhjC/1
    configuration: 
      continuous: 1
      callback: 1
      latexmk options: 
        -verbose
        -pdf
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
  viewer: General
  qf: LaTeX logfile
    config: 
      fix_paths: 1
      packages: 
        default: 1
      default: 1
```

The output from `\lo` is blank, which seems like a bit of an issue...

**Comment by lervag** [comment]
Let's focus on the compilation issue for now, and return to the image thing later.

The `VimtexInfo` output implies that you have not tried to run `:VimtexCompile`. If you did, there should be more info in the info blob. Can you try to run the command directly, with `:VimtexCompile` instead of `\ll`?

Do you have `latexmk` installed? I assume you do, since you have a `.latexmkrc` file. And you should have recieved a warning if not. But still...?

By default, `vimtex` tells latexmk to compile directly to pdf. Thus it should not export as `.dvi`.

Before your next tests, could you do a `latexmk -C` in the test folder, to make sure that there are no latex generated files present?

**Comment by JasonB579** [comment]
Running it with `:VimtexCompile` did give better output, and also appears to have fixed all of the issues! So the new `:VimtexInfo` is as follows:
```
vimtex project: exampleTEX
  base: exampleTEX.tex
  root: /home/jason/Documents/latex_fail_example
  tex: /home/jason/Documents/latex_fail_example/exampleTEX.tex
  out: /home/jason/Documents/latex_fail_example/exampleTEX.pdf
  log: /home/jason/Documents/latex_fail_example/exampleTEX.log
  aux: /home/jason/Documents/latex_fail_example/exampleTEX.aux
  compiler: latexmk
    backend: nvim
    output: /tmp/nvimQrDvsJ/1
    configuration: 
      continuous: 1
      callback: 1
      latexmk options: 
        -verbose
        -pdf
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
    pid: 8476
    cmd: max_print_line=2000 latexmk -verbose -pdf -file-line-error -synctex=1 -interaction=nonstopmod
e -pvc -e '$pdf_previewer = "xdg-open"' -e '$success_cmd = "'"'~/.local/bin/nvr'"' --servername /tmp/n
vimQrDvsJ/0 --remote-expr \"vimtex\#compiler\#callback(1)\""' -e '$failure_cmd = "'"'~/.local/bin/nvr'
"' --servername /tmp/nvimQrDvsJ/0 --remote-expr \"vimtex\#compiler\#callback(0)\""' 'exampleTEX.tex'
  viewer: General
  qf: LaTeX logfile
    config: 
      fix_paths: 1
      packages: 
        default: 1
      default: 1
```

So now it appears there might be an issue with the shortcut `\ll` 

Also, yes I have `latexmk` installed.
